In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="lseg_us_eqt_short_interest_factor_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2026-02-02 20:00:03.000,2026-02-02 19:18:00.000,2026-02-02,A,42293446.16,-231594.60,9.503872e+07,2.280769e+05,1.322375e+08,5.294060e+03,-3.937758e+07,2.276769e+06,-5.069923e+07,2.115547e+06,-8.211554e+07,1.502166e+06,6.104241e+08,-6.136834e+05,2026-02-02
1,2026-02-02 20:00:03.000,2026-02-02 19:59:00.000,2026-02-02,AA,-8992471.23,-7439262.63,-1.867140e+07,-8.921885e+06,1.671445e+07,-9.551017e+06,-5.753506e+07,-7.608132e+06,-1.942274e+07,-9.036643e+06,9.321165e+07,-8.053674e+06,5.292476e+07,-2.796637e+07,2026-02-02
2,2026-02-02 20:00:03.000,2026-02-02 20:01:00.000,2026-02-02,AAA,68621.83,-9413.71,1.355465e+05,6.200827e+04,3.319536e+05,-1.093546e+05,6.207353e+04,-2.322469e+05,2.627407e+05,-1.879955e+05,4.125397e+05,-5.138512e+04,7.736905e+05,-3.865882e+05,2026-02-02
3,2026-02-02 20:00:03.000,2026-02-02 20:01:00.000,2026-02-02,AAAA,138.91,-55.98,-4.499037e+05,-8.899868e+04,-6.527691e+05,-1.397926e+05,-1.422454e+06,-3.036716e+05,-2.392356e+06,-4.870969e+05,-3.071749e+06,-6.359202e+05,-1.043285e+07,-1.424242e+06,2026-02-02
4,2026-02-02 20:00:03.000,2026-02-02 20:01:00.000,2026-02-02,AAAC,122145.40,1805.56,-4.882172e+03,1.527430e+03,-9.331388e+04,1.405469e+03,3.638861e+04,9.764021e+02,-2.010704e+05,4.516614e+02,-4.948236e+05,-2.430232e+02,-2.803301e+06,-3.360864e+01,2026-02-02
5,2026-02-02 20:00:03.000,2026-02-02 19:59:00.000,2026-02-02,AAAU,20355626.32,-1570636.51,-3.225219e+06,-9.017710e+06,1.858415e+07,-3.131214e+06,2.977818e+07,-3.284605e+06,2.459568e+07,-5.043588e+06,4.066951e+07,-6.610155e+06,6.649884e+07,-4.039323e+07,2026-02-02
6,2026-02-02 20:00:03.000,2026-02-02 16:00:00.000,2026-02-02,AACB,-487571.25,20.80,-1.484754e+06,3.479663e+01,-1.555392e+06,-3.247652e+02,-2.350851e+06,2.040831e+02,-2.257036e+06,2.716394e+01,-2.980739e+06,-4.146545e+03,-1.450455e+07,6.391466e+04,2026-02-02
7,2026-02-02 20:00:03.000,2026-02-02 12:42:00.000,2026-02-02,AACBR,1333.51,-11724.65,5.133431e+03,-1.230454e+04,5.574239e+03,-1.233143e+04,7.533898e+03,-1.208340e+04,2.346019e+03,-1.262839e+04,3.530196e+03,-1.270067e+04,5.148736e+04,-1.476261e+04,2026-02-02
8,2026-02-02 20:00:03.000,2026-02-02 09:41:00.000,2026-02-02,AACBU,-10.61,0.00,2.369664e+04,-6.584842e+03,4.182934e+04,-1.322653e+04,8.242549e+04,-2.459823e+04,1.129998e+05,-3.620513e+04,1.554264e+05,-4.810517e+04,4.682118e+05,-1.561162e+05,2026-02-02
9,2026-02-02 20:00:03.000,2026-02-02 16:11:00.000,2026-02-02,AACG,-2124.01,15.17,3.596155e+02,-4.620750e+03,-1.595776e+03,-6.255326e+03,1.022415e+04,-1.373682e+04,2.054162e+04,-2.312390e+04,3.260846e+04,-1.621969e+04,-4.121052e+04,-4.357082e+04,2026-02-02

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_short_interest_factor_daily_v1_2_1', back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2024-01-24 20:00:03.000,2024-01-24 19:01:00.000,2024-01-24,A,-11966238.82,-166488.74,3.124196e+07,-5.604448e+05,9.610030e+07,-2.033625e+06,1.588953e+08,-4.186411e+05,3.192670e+08,1.735875e+06,3.914769e+08,1.644181e+06,1.097940e+09,1.272624e+07,2024-01-24
1,2024-01-24 20:00:03.000,2024-01-24 20:00:00.000,2024-01-24,AA,13061331.24,3309260.55,5.869312e+07,4.343967e+06,6.143698e+07,8.774404e+06,4.073746e+06,1.080472e+07,-4.508364e+07,1.776675e+07,-1.553669e+06,1.522261e+07,1.583268e+08,9.565214e+06,2024-01-24
2,2024-01-24 20:00:03.000,2024-01-24 20:01:00.000,2024-01-24,AAA,7438.13,3915.78,-3.630603e+04,1.593366e+03,-1.614954e+05,-3.190105e+03,-2.819962e+05,1.334182e+05,-2.759828e+05,1.838636e+05,-3.794538e+05,1.487653e+05,1.593455e+06,2.446005e+05,2024-01-24
3,2024-01-24 20:00:03.000,2024-01-24 20:01:00.000,2024-01-24,AAAU,-4562000.67,1493898.72,-1.604603e+07,1.099898e+06,-1.743682e+07,7.677061e+05,-2.350761e+07,3.483654e+06,-2.159594e+07,4.009300e+06,-1.590840e+07,3.679555e+06,-6.820348e+06,9.870164e+06,2024-01-24
4,2024-01-24 20:00:03.000,2024-01-24 18:42:00.000,2024-01-24,AACG,486.85,-627.79,-1.314263e+04,-2.191201e+03,-1.342922e+04,-2.438811e+03,-2.821076e+04,-1.090746e+04,-3.233302e+04,-1.417721e+04,-1.178671e+04,-1.633673e+04,-2.542130e+04,-1.779029e+04,2024-01-24
5,2024-01-24 20:00:03.000,2024-01-24 16:01:00.000,2024-01-24,AACI,970.18,-98.01,-1.002474e+05,1.221655e+04,-2.358936e+04,1.529538e+04,1.288753e+05,2.359512e+04,-6.585664e+04,3.195863e+04,4.312626e+05,4.161097e+04,4.104040e+06,1.217363e+05,2024-01-24
6,2024-01-24 20:00:03.000,2024-01-24 11:44:00.000,2024-01-24,AACIU,0.00,0.00,2.282826e+03,-1.202143e+02,3.772690e+03,-2.044757e+02,7.119049e+03,-4.317136e+02,1.063944e+04,-6.874235e+02,1.338398e+04,-9.797757e+02,-1.113874e+04,-1.645955e+02,2024-01-24
7,2024-01-24 20:00:03.000,2024-01-24 10:52:00.000,2024-01-24,AACIW,0.00,-0.53,1.145912e+03,-2.481299e+01,2.947958e+03,-4.135873e+01,3.011309e+03,2.251743e+01,2.911964e+03,-1.150483e+01,3.007673e+03,2.803958e+01,9.462441e+03,7.741575e+02,2024-01-24
8,2024-01-24 20:00:03.000,2024-01-24 19:01:00.000,2024-01-24,AACT,-1315155.06,-69842.19,2.364271e+06,-7.552586e+04,2.973664e+06,-7.937338e+04,-7.643598e+05,-1.037544e+05,-1.233363e+06,-1.185572e+05,1.695631e+06,-1.307692e+05,1.187280e+07,-1.324122e+05,2024-01-24
9,2024-01-24 20:00:03.000,2024-01-24 19:01:00.000,2024-01-24,AACT.WS,873.58,1680.52,1.504620e+04,1.434890e+03,3.059219e+04,1.255530e+03,-2.245250e+04,1.644027e+03,2.150227e+04,2.321160e+03,4.642967e+04,2.586572e+03,-7.010323e+04,8.230361e+03,2024-01-24

In [6]:
df =  Unifier.get_dataframe(name="lseg_us_eqt_short_interest_factor_daily_v1_2_1", key='PSR', back_to='2020-10-29',up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2024-01-30 20:00:03.000,2024-01-30 20:01:00.000,2024-01-30,PSR,-10644.26,14376.33,-1.225589e+06,-56435.269470,-1.066001e+06,-44159.330384,-7.047026e+06,-163900.871874,-6.735012e+06,-213510.846866,-5.179820e+06,-205626.706402,-3.228570e+06,-1.154997e+06,2024-01-30
1,2024-01-25 20:00:03.000,2024-01-25 20:01:00.000,2024-01-25,PSR,36713.62,18611.52,2.090009e+05,18355.456265,-5.843387e+06,28536.452647,-5.518121e+06,-187996.243714,-6.423743e+06,-369444.615213,-4.839241e+06,-82668.317864,-8.717930e+06,-1.214764e+06,2024-01-25
2,2024-01-08 20:00:03.000,2024-01-08 20:01:00.000,2024-01-08,PSR,-422749.26,-195023.45,-9.630584e+05,-213867.617544,1.482446e+06,9931.587467,-5.331094e+05,40082.292893,-3.530539e+06,-91076.272541,-5.708661e+06,-633822.945158,-3.921754e+06,-1.704619e+06,2024-01-08
3,2024-01-09 20:00:03.000,2024-01-09 20:01:00.000,2024-01-09,PSR,-10444.38,13776.54,-5.828831e+05,-174851.636509,3.549193e+06,-275257.886922,-1.262205e+05,73646.141941,-1.509104e+06,-101574.121436,-5.468419e+06,-652764.643921,-3.939764e+06,-1.691822e+06,2024-01-09
4,2024-01-11 20:00:03.000,2024-01-11 20:01:00.000,2024-01-11,PSR,149449.54,-179.67,1.137084e+05,27190.166645,-4.538639e+05,-154960.553657,5.322190e+05,96580.267173,-6.892563e+05,-40054.951477,-3.842704e+06,34821.676783,-3.838580e+06,-1.653692e+06,2024-01-11
5,2024-01-26 20:00:03.000,2024-01-26 20:01:00.000,2024-01-26,PSR,-48609.33,-47133.72,1.371769e+05,-39986.189896,3.154021e+04,-57079.993374,-5.696935e+06,-233573.615377,-6.065495e+06,-389854.511729,-4.991476e+06,-139723.939859,-8.813162e+06,-1.285822e+06,2024-01-26
6,2024-01-24 20:00:03.000,2024-01-24 20:01:00.000,2024-01-24,PSR,69369.09,5552.54,-9.880277e+03,-16856.481232,-5.979223e+06,-71695.124476,-5.566679e+06,-173318.943303,-1.945157e+06,-448729.995438,-5.545212e+06,-99890.357682,-8.843635e+06,-1.217174e+06,2024-01-24
7,2023-12-29 20:00:03.000,2023-12-29 20:01:00.000,2023-12-29,PSR,-951371.33,29877.94,-9.148805e+05,61575.749658,-1.977191e+06,26171.797730,-4.934834e+06,-109003.486317,-7.070873e+06,-655744.858221,-6.773701e+06,-570589.343027,-4.719340e+06,-1.728946e+06,2023-12-29
8,2024-01-22 20:00:03.000,2024-01-22 20:01:00.000,2024-01-22,PSR,-181623.38,-17193.31,-6.122888e+06,-77175.284713,-6.068745e+06,-139829.908187,-6.132552e+06,-371576.425589,-5.096962e+06,-136037.049502,-6.329124e+06,-235154.147182,-8.765331e+06,-1.925474e+06,2024-01-22
9,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,2024-01-17,PSR,91262.09,-40471.95,2.432833e+05,-120498.615001,4.160988e+05,-100806.948824,4.041304e+06,-375322.469166,4.442234e+05,-25615.423537,-8.595081e+05,-200015.244533,-2.929754e+06,-1.851999e+06,2024-01-17

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="lseg_us_eqt_short_interest_factor_daily_v1_2_1", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for lseg_us_eqt_short_interest_factor_daily_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_eqt_short_interest_factor_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_short_interest_factor_daily_v1_2_1", target_location="./data")