In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="lseg_us_eqt_short_interest_factor_1min_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2026-04-01 09:51:03.000,2026-04-01 09:51:00.000,2026-04-01,AAVM,3193.00,0.00,-20335.95,-19487.52,-18767.39,-13708.13,-13831.12,-13708.13,-46261.13,-22113.43,2026-04-01
1,2026-04-01 09:55:03.000,2026-04-01 09:55:00.000,2026-04-01,AAVM,1276.55,0.00,-19059.40,-19487.52,-17490.84,-13708.13,-12554.57,-13708.13,-44984.58,-22113.43,2026-04-01
2,2026-04-01 10:00:03.000,2026-04-01 10:00:00.000,2026-04-01,AAVM,-31.91,-31.83,-19091.31,-19519.35,-17522.75,-13739.96,-12586.48,-13739.96,-45016.49,-22145.26,2026-04-01
3,2026-04-01 11:29:03.000,2026-04-01 11:29:00.000,2026-04-01,AAVM,32.06,0.00,9058.01,-0.48,-17490.69,-13739.96,-16421.58,-13739.96,-44984.43,-22145.26,2026-04-01
4,2026-04-01 11:57:03.000,2026-04-01 11:57:00.000,2026-04-01,AAVM,0.00,483.15,9058.01,482.67,-17490.69,-13256.81,-16421.58,-13256.81,-44984.43,-21662.11,2026-04-01
5,2026-04-01 12:11:03.000,2026-04-01 12:11:00.000,2026-04-01,AAVM,-160.73,0.00,8897.28,482.67,-17651.42,-13256.81,-16582.31,-13256.81,-45145.16,-21662.11,2026-04-01
6,2026-04-01 13:20:03.000,2026-04-01 13:20:00.000,2026-04-01,AAVM,1675.96,1675.95,10417.54,2158.62,-15975.46,-11580.86,-14845.07,-11580.86,-43469.20,-19986.16,2026-04-01
7,2026-04-01 16:05:03.000,2026-04-01 16:05:00.000,2026-04-01,AAVM,0.00,-31.94,5984.93,2095.33,-15975.46,-11612.80,-15975.46,-11612.80,-43469.20,-20018.10,2026-04-01
8,2026-04-01 04:01:03.000,2026-04-01 04:01:00.000,2026-04-01,ABCL,-17671.03,0.00,-411270.39,-191900.90,-673651.15,-234938.14,-2121704.20,-501186.53,-4400086.05,-665024.56,2026-04-01
9,2026-04-01 04:02:03.000,2026-04-01 04:02:00.000,2026-04-01,ABCL,1146.18,0.00,-410124.21,-191900.90,-672504.97,-234938.14,-2120558.02,-501186.53,-4398939.87,-665024.56,2026-04-01

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_short_interest_factor_1min_v1_2_1', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2021-01-26 07:06:03.000,2021-01-26 07:06:00.000,2021-01-26,AACQW,-530.00,0,-518429.59,19754.36,-516862.59,19754.36,-596331.75,71848.34,-717638.52,131674.58,2021-01-26
1,2021-01-26 07:28:03.000,2021-01-26 07:28:00.000,2021-01-26,AACQW,-795.00,0,-517356.25,19754.36,-517657.59,19754.36,-597402.03,71848.34,-718433.52,131674.58,2021-01-26
2,2021-01-26 08:14:03.000,2021-01-26 08:14:00.000,2021-01-26,AACQW,-368.35,0,-522773.58,19754.36,-518025.94,19754.36,-601357.08,71848.34,-718801.87,131674.58,2021-01-26
3,2021-01-26 08:15:03.000,2021-01-26 08:15:00.000,2021-01-26,AACQW,-2281.65,0,-525055.23,19754.36,-520307.59,19754.36,-603821.51,71848.34,-721083.52,131674.58,2021-01-26
4,2021-01-26 08:18:03.000,2021-01-26 08:18:00.000,2021-01-26,AACQW,-253.00,0,-525308.23,19754.36,-520560.59,19754.36,-604074.51,71848.34,-721336.52,131674.58,2021-01-26
5,2021-01-26 08:19:03.000,2021-01-26 08:19:00.000,2021-01-26,AACQW,-25.00,0,-522663.23,19754.36,-520585.59,19754.36,-604099.51,71848.34,-721361.52,131674.58,2021-01-26
6,2021-01-26 08:24:03.000,2021-01-26 08:24:00.000,2021-01-26,AACQW,-2216.00,0,-524307.33,19754.36,-522801.59,19754.36,-606315.51,71848.34,-723577.52,131674.58,2021-01-26
7,2021-01-26 09:21:03.000,2021-01-26 09:21:00.000,2021-01-26,AACQW,-255.00,0,-526540.39,19754.36,-523056.59,19754.36,-628254.07,71848.34,-723832.52,131674.58,2021-01-26
8,2021-01-26 09:31:03.000,2021-01-26 09:31:00.000,2021-01-26,AACQW,-54646.16,0,-521883.67,16825.83,-577702.75,19754.36,-657687.25,71848.34,-778478.68,131674.58,2021-01-26
9,2021-01-26 09:32:03.000,2021-01-26 09:32:00.000,2021-01-26,AACQW,-4764.50,0,-521139.78,16825.83,-582467.25,19754.36,-662451.75,71848.34,-783243.18,131674.58,2021-01-26

In [6]:
df =  Unifier.get_dataframe(name="lseg_us_eqt_short_interest_factor_1min_v1_2_1", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2026-04-06 09:31:03.000,2026-04-06 09:31:00.000,2026-04-06,PSR,0.00,0.00,0.00,0.00,0.00,0.00,-158008.50,23518.35,-363754.38,16772.99,2026-04-06
1,2026-04-06 09:39:03.000,2026-04-06 09:39:00.000,2026-04-06,PSR,0.00,-376.24,0.00,-376.24,0.00,-376.24,-158008.50,23142.11,-362111.36,16396.75,2026-04-06
2,2026-04-06 09:46:03.000,2026-04-06 09:46:00.000,2026-04-06,PSR,-941.25,0.00,-941.25,-376.24,-941.25,-376.24,-158949.75,23142.11,-363052.61,16396.75,2026-04-06
3,2026-04-06 09:56:03.000,2026-04-06 09:56:00.000,2026-04-06,PSR,0.00,-94.19,-941.25,-470.43,-941.25,-470.43,-158949.75,23047.92,-363052.61,16302.56,2026-04-06
4,2026-04-06 10:04:03.000,2026-04-06 10:04:00.000,2026-04-06,PSR,4444.59,0.00,3503.34,-470.43,3503.34,-470.43,-154598.24,23141.00,-359157.38,16210.92,2026-04-06
5,2026-04-06 10:05:03.000,2026-04-06 10:05:00.000,2026-04-06,PSR,0.00,94.59,3503.34,-375.84,3503.34,-375.84,-154598.24,23235.59,-359157.38,16305.51,2026-04-06
6,2026-04-06 10:10:03.000,2026-04-06 10:10:00.000,2026-04-06,PSR,0.00,94.53,3503.34,-281.31,3503.34,-281.31,-153667.84,23330.12,-360624.50,16400.04,2026-04-06
7,2026-04-06 10:19:03.000,2026-04-06 10:19:00.000,2026-04-06,PSR,4632.21,0.00,8135.55,-281.31,8135.55,-281.31,-142712.99,23330.12,-355900.61,38100.11,2026-04-06
8,2026-04-06 10:49:03.000,2026-04-06 10:49:00.000,2026-04-06,PSR,0.00,0.00,8135.55,-281.31,8135.55,-281.31,-142712.99,20350.41,-352328.79,38008.38,2026-04-06
9,2026-04-06 11:30:03.000,2026-04-06 11:30:00.000,2026-04-06,PSR,-945.00,945.29,7190.55,663.98,7190.55,663.98,-143141.51,21295.70,-353549.24,38953.67,2026-04-06

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="lseg_us_eqt_short_interest_factor_1min_v1_2_1", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for lseg_us_eqt_short_interest_factor_1min_v1_2_1...
Found 1 files to download.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_short_interest_factor_1min_v1_2_1", target_location="./data")