In [20]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [21]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [23]:
df =  Unifier.get_dataframe(name="lseg_us_eqt_short_interest_factor_daily_v1_2", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2025-12-11 20:00:03.000,2025-12-11 20:01:00.000,2025-12-11,AAAC,-2.503850e+05,250385.01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2025-12-11
1,2025-12-11 20:00:03.000,2025-12-11 20:00:00.000,2025-12-11,AAL,-4.396815e+08,4786187.04,4.253601e+08,1.942573e+06,4.787156e+08,4.955851e+06,1.761908e+09,-3.236213e+07,2.339419e+09,-8.988874e+07,2.142923e+09,-8.542139e+07,3.767392e+09,-1.555504e+08,2025-12-11
2,2025-12-11 20:00:03.000,2025-12-11 16:16:00.000,2025-12-11,AALG,-7.486810e+03,18278.09,-1.168321e+04,2.771357e+04,2.039256e+05,7.207002e+04,7.172505e+05,5.158322e+04,1.202711e+06,7.351797e+03,9.679585e+05,2.524822e+04,2.656420e+06,8.129183e+04,2025-12-11
3,2025-12-11 20:00:03.000,2025-12-11 16:11:00.000,2025-12-11,AAPG,8.358890e+03,-831.02,1.944306e+05,-1.356099e+04,3.710848e+05,-1.466741e+04,7.781637e+05,-1.819093e+04,1.115468e+06,-9.888624e+03,1.650232e+06,-2.461359e+04,7.479350e+06,-7.515973e+04,2025-12-11
4,2025-12-11 20:00:03.000,2025-12-11 19:01:00.000,2025-12-11,AB,-3.555766e+06,115852.71,-3.332301e+07,-6.202522e+05,-2.093482e+07,-7.353000e+05,-5.047845e+06,-1.237171e+06,6.226767e+06,-1.126099e+06,1.113317e+07,-1.661230e+06,2.268563e+07,-3.896103e+06,2025-12-11
5,2025-12-11 20:00:03.000,2025-12-11 19:29:00.000,2025-12-11,ABL,5.045076e+06,-23218.72,7.539174e+06,-1.437511e+04,1.203960e+07,-1.118251e+04,9.328866e+06,3.480304e+04,1.090955e+07,1.340681e+05,1.091241e+07,1.600132e+05,-9.779897e+06,3.835578e+05,2025-12-11
6,2025-12-11 20:00:03.000,2025-12-11 19:55:00.000,2025-12-11,ABLV,-4.216500e+02,1256.31,-1.505233e+05,-1.263347e+04,-2.597144e+05,-1.553150e+04,9.518213e+06,3.741203e+05,9.437905e+06,3.703273e+05,9.355702e+06,3.653588e+05,8.625900e+06,3.501092e+05,2025-12-11
7,2025-12-11 20:00:03.000,2025-12-11 16:00:00.000,2025-12-11,ABLVW,-1.507500e+02,684.68,-1.308974e+02,-1.494841e+03,-3.615622e+02,-1.307085e+03,-1.873204e+03,8.519413e+02,-1.798339e+03,9.381499e+02,-1.877392e+03,2.053246e+03,1.596888e+02,-1.398343e+03,2025-12-11
8,2025-12-11 20:00:03.000,2025-12-11 20:00:00.000,2025-12-11,ABNB,8.091807e+07,9715.85,3.988382e+08,-4.718404e+06,8.999086e+08,-6.473384e+06,5.668316e+08,-1.614450e+07,-1.203697e+08,-2.576899e+07,-1.639401e+08,-2.846112e+07,-1.105532e+09,-8.804309e+06,2025-12-11
9,2025-12-11 20:00:03.000,2025-12-11 16:52:00.000,2025-12-11,ABNG,-1.660000e+01,-3255.47,9.034283e+03,-4.176934e+03,-7.067504e+03,-8.705693e+03,4.808880e+04,-1.123524e+04,4.401587e+04,-1.103490e+04,5.580530e+04,-1.250860e+04,5.580530e+04,-1.250860e+04,2025-12-11

In [24]:
df = Unifier.get_dataframe(name='lseg_us_eqt_short_interest_factor_daily_v1_2', back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2024-01-18 20:00:03.000,2024-01-18 18:35:00.000,2024-01-18,AAGR,-5827.94,5389.27,1.240574e+05,-76901.790840,2.241988e+05,-154960.797240,-8.680780e+04,-3.219795e+05,-1.521270e+04,-4.294740e+05,6.089365e+06,-1.172861e+05,7.780311e+06,-1.870830e+05,2024-01-18
1,2024-01-18 20:00:03.000,2024-01-18 19:29:00.000,2024-01-18,AAN,311708.57,-12108.84,1.797419e+06,-35717.816635,1.431358e+04,-40578.300088,1.264697e+06,9.657580e+03,8.678537e+06,1.222009e+04,1.273832e+07,2.278215e+03,9.684514e+06,-1.041394e+06,2024-01-18
2,2024-01-18 20:00:03.000,2024-01-18 20:01:00.000,2024-01-18,AAPX,133269.39,-29118.53,1.158032e+05,-26297.435500,1.191365e+05,-27350.420500,1.191365e+05,-2.735042e+04,1.191365e+05,-2.735042e+04,1.191365e+05,-2.735042e+04,1.191365e+05,-2.735042e+04,2024-01-18
3,2024-01-18 20:00:03.000,2024-01-18 18:36:00.000,2024-01-18,ABEO,-175279.82,16902.13,-2.575436e+05,-2178.671960,-3.286732e+05,9073.739376,-3.735867e+05,-6.358650e+04,1.129959e+06,-1.124019e+05,5.584972e+06,-2.545581e+05,1.739690e+06,-3.239106e+05,2024-01-18
4,2024-01-18 20:00:03.000,2024-01-18 19:01:00.000,2024-01-18,ABG,-4322413.88,-31729.58,-1.641415e+06,88149.900801,-4.313850e+06,182475.371638,-8.201698e+06,8.437999e+04,1.850235e+05,1.469343e+05,2.288265e+07,4.145633e+04,9.999419e+07,-1.106920e+06,2024-01-18
5,2024-01-18 20:00:03.000,2024-01-18 16:01:00.000,2024-01-18,ABIO,-2544.01,-5167.10,-6.611115e+03,-3467.950710,-7.689158e+03,5448.766058,-2.426788e+04,2.921854e+04,-4.790312e+04,4.310327e+04,-5.653510e+04,4.716348e+04,-8.616654e+04,5.256176e+04,2024-01-18
6,2024-01-18 20:00:03.000,2024-01-18 19:01:00.000,2024-01-18,ABRpE,-2450.05,-1041.20,4.066098e+04,-1038.410307,-3.510190e+04,-15068.212412,2.094133e+05,1.085188e+03,-4.834611e+04,-2.261761e+04,5.173350e+04,-3.208150e+04,7.316045e+05,5.955598e+04,2024-01-18
7,2024-01-18 20:00:03.000,2024-01-18 19:48:00.000,2024-01-18,ABVC,-572.53,586.80,7.390653e+05,-233431.478486,1.222692e+06,-357351.848261,2.226406e+06,-4.475965e+05,6.454614e+07,4.174984e+06,6.712536e+07,3.931345e+06,1.427547e+07,8.152769e+06,2024-01-18
8,2024-01-18 20:00:03.000,2024-01-18 19:27:00.000,2024-01-18,ACRS,-27974.25,19632.32,7.188014e+06,-2495.333529,2.068604e+05,-857818.770053,2.313232e+04,-1.192395e+06,1.796032e+06,-1.358468e+06,2.514270e+06,-1.582160e+06,7.150528e+06,-1.347324e+06,2024-01-18
9,2024-01-18 20:00:03.000,2024-01-18 19:01:00.000,2024-01-18,ADCT,-837285.85,-13407.73,-1.748009e+06,59231.203673,-6.094864e+05,29530.749727,1.809231e+06,1.243935e+05,2.025356e+06,1.363672e+05,2.217562e+06,1.441780e+05,1.622288e+07,2.523148e+03,2024-01-18

In [25]:
df =  Unifier.get_dataframe(name="lseg_us_eqt_short_interest_factor_daily_v1_2", key='PSR', back_to='2020-10-29',up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2022-08-26 20:00:03.000,2022-08-26 20:01:00.000,2022-08-26,PSR,-170210.87,-19017.72,5.470507e+05,-153417.207809,-6.846596e+05,-98482.302219,8.906873e+06,276809.150484,8.862790e+06,201372.565028,8.481679e+06,265046.752616,5.118314e+06,8.479381e+05,2022-08-26
1,2022-05-03 20:00:03.000,2022-05-03 20:01:00.000,2022-05-03,PSR,-155880.97,-19577.57,-6.215867e+06,-146588.204308,-5.943303e+06,-428974.358537,-6.622549e+06,-590763.488141,-5.040319e+06,-574932.352901,-4.944967e+06,-566503.574778,1.273668e+06,-9.487360e+05,2022-05-03
2,2022-05-13 20:00:03.000,2022-05-13 20:01:00.000,2022-05-13,PSR,427069.62,123005.11,-6.736551e+05,128953.594458,-1.253176e+06,257124.398725,-7.846375e+06,90364.666495,-8.107740e+06,-147442.850151,-4.971979e+06,-363284.146113,-1.743348e+06,-9.420314e+05,2022-05-13
3,2022-10-13 20:00:03.000,2022-10-13 20:01:00.000,2022-10-13,PSR,13869.81,-115661.50,-7.493760e+04,-189385.584989,-7.760232e+05,-195841.203118,-1.980173e+06,109037.865893,-3.827454e+06,390946.422405,-4.637548e+06,315283.791636,2.547246e+06,6.458902e+05,2022-10-13
4,2022-09-08 20:00:03.000,2022-09-08 20:01:00.000,2022-09-08,PSR,201427.77,39878.88,3.295396e+05,-7967.656620,-3.365848e+05,-62061.971819,-3.372251e+06,-86052.075510,1.411145e+06,-34228.505003,5.719919e+06,229913.923891,1.150230e+06,7.704045e+05,2022-09-08
5,2022-05-31 20:00:03.000,2022-05-31 20:01:00.000,2022-05-31,PSR,-868323.88,95573.57,-2.164084e+05,99937.831049,-1.311440e+05,63486.359192,-1.478052e+05,-161441.828986,-9.606288e+05,151329.970090,-7.711207e+06,-68616.528067,-6.124466e+05,-1.515305e+06,2022-05-31
6,2022-09-28 20:00:03.000,2022-09-28 20:01:00.000,2022-09-28,PSR,163883.80,-49343.52,-5.119921e+04,473271.552002,-2.556776e+06,330808.376894,-2.605466e+06,195260.489577,-2.490964e+06,368288.751997,-4.999483e+06,272582.126730,5.003492e+06,1.341709e+06,2022-09-28
7,2022-05-09 20:00:03.000,2022-05-09 20:01:00.000,2022-05-09,PSR,-336467.28,-117044.61,-7.064080e+05,-145299.988987,-6.733820e+06,-216978.800822,-6.672869e+06,-523605.692453,-3.745367e+06,-742531.023380,-6.008917e+06,-611739.155165,6.337727e+04,-1.251941e+06,2022-05-09
8,2022-04-25 20:00:03.000,2022-04-25 20:01:00.000,2022-04-25,PSR,-19694.53,-12272.93,-9.649264e+05,-84371.005807,3.085314e+06,-222441.038574,8.090160e+05,-242138.863794,6.598114e+05,-188876.547379,7.433100e+06,-407156.514289,9.087100e+06,-2.054774e+05,2022-04-25
9,2022-05-24 20:00:03.000,2022-05-24 20:01:00.000,2022-05-24,PSR,28499.14,26893.86,5.728377e+04,-181412.045454,-2.409933e+05,-142911.005184,-5.441116e+05,-145616.877152,-1.659579e+06,-67277.656291,-7.430867e+06,-396532.806118,4.177895e+05,-1.427450e+06,2022-05-24

## Download data file for a specific date using asof_date

In [26]:
Unifier.replicate(name="lseg_us_eqt_short_interest_factor_daily_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_eqt_short_interest_factor_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_short_interest_factor_daily_v1_2. Downloaded 1 files.