In [10]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [11]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [19]:
df =  Unifier.get_dataframe(name="lseg_us_eqt_short_interest_factor_1min_v1_2", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2025-12-09 04:24:03.000,2025-12-09 04:24:00.000,2025-12-09,A,-285.06,0,-1.997877e+08,-10714.9,-1.997877e+08,-10714.9,-1.866180e+08,788960.70,-3.149373e+08,1932022.08,2025-12-09
1,2025-12-09 07:01:03.000,2025-12-09 07:01:00.000,2025-12-09,A,-1830.86,0,-1.998119e+08,-10714.9,-1.997896e+08,-10714.9,-1.866199e+08,788960.70,-3.149392e+08,1932022.08,2025-12-09
2,2025-12-09 07:11:03.000,2025-12-09 07:11:00.000,2025-12-09,A,14321.00,0,-1.998089e+08,-10714.9,-1.997753e+08,-10714.9,-1.866055e+08,788960.70,-3.149248e+08,1932022.08,2025-12-09
3,2025-12-09 08:01:03.000,2025-12-09 08:01:00.000,2025-12-09,A,-3669.14,0,-1.998135e+08,-10714.9,-1.997789e+08,-10714.9,-1.866092e+08,788960.70,-3.149285e+08,1932022.08,2025-12-09
4,2025-12-09 08:02:03.000,2025-12-09 08:02:00.000,2025-12-09,A,19337.53,0,-1.997942e+08,-10714.9,-1.997596e+08,-10714.9,-1.865899e+08,788960.70,-3.149092e+08,1932022.08,2025-12-09
5,2025-12-09 08:28:03.000,2025-12-09 08:28:00.000,2025-12-09,A,2297.82,0,-1.998202e+08,-10714.9,-1.997573e+08,-10714.9,-1.865870e+08,798908.34,-3.149069e+08,1932022.08,2025-12-09
6,2025-12-09 08:32:03.000,2025-12-09 08:32:00.000,2025-12-09,A,143.78,0,-1.998200e+08,-10714.9,-1.997571e+08,-10714.9,-1.865868e+08,798908.34,-3.149067e+08,1932022.08,2025-12-09
7,2025-12-09 08:38:03.000,2025-12-09 08:38:00.000,2025-12-09,A,111329.75,0,-1.997087e+08,-10714.9,-1.996458e+08,-10714.9,-1.864605e+08,798908.34,-3.147954e+08,1932022.08,2025-12-09
8,2025-12-09 08:39:03.000,2025-12-09 08:39:00.000,2025-12-09,A,2146.50,0,-1.997066e+08,-10714.9,-1.996437e+08,-10714.9,-1.864485e+08,798908.34,-3.147932e+08,1932022.08,2025-12-09
9,2025-12-09 08:42:03.000,2025-12-09 08:42:00.000,2025-12-09,A,572.40,0,-1.997047e+08,-10714.9,-1.996431e+08,-10714.9,-1.864479e+08,798908.34,-3.147927e+08,1932022.08,2025-12-09

In [20]:
df = Unifier.get_dataframe(name='lseg_us_eqt_short_interest_factor_1min_v1_2', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2021-01-21 07:18:03.000,2021-01-21 07:18:00.000,2021-01-21,A,645.00,0,1.347619e+08,-8980.32,1.508831e+08,-302624.99,1.508831e+08,-302624.99,3.168307e+08,458176.29,2021-01-21
1,2021-01-21 08:34:03.000,2021-01-21 08:34:00.000,2021-01-21,A,-1923.00,0,1.347594e+08,-8980.32,1.508812e+08,-302624.99,1.508812e+08,-302624.99,3.168284e+08,458176.29,2021-01-21
2,2021-01-21 08:56:03.000,2021-01-21 08:56:00.000,2021-01-21,A,25995.00,0,1.347854e+08,-8980.32,1.509072e+08,-302624.99,1.509072e+08,-302624.99,3.168544e+08,458176.29,2021-01-21
3,2021-01-21 08:57:03.000,2021-01-21 08:57:00.000,2021-01-21,A,1950.00,0,1.347874e+08,-8980.32,1.509091e+08,-302624.99,1.509091e+08,-302624.99,3.168563e+08,458176.29,2021-01-21
4,2021-01-21 08:58:03.000,2021-01-21 08:58:00.000,2021-01-21,A,-128.75,0,1.347872e+08,-8980.32,1.509090e+08,-302624.99,1.509090e+08,-302624.99,3.168562e+08,458176.29,2021-01-21
5,2021-01-21 08:59:03.000,2021-01-21 08:59:00.000,2021-01-21,A,516.53,0,1.347878e+08,-8980.32,1.509095e+08,-302624.99,1.509095e+08,-302624.99,3.168566e+08,458176.29,2021-01-21
6,2021-01-21 09:25:03.000,2021-01-21 09:25:00.000,2021-01-21,A,-128.94,0,1.347885e+08,-8980.32,1.509094e+08,-302624.99,1.509094e+08,-302624.99,3.168553e+08,458176.29,2021-01-21
7,2021-01-21 09:26:03.000,2021-01-21 09:26:00.000,2021-01-21,A,0.00,1289,1.347885e+08,-7691.32,1.509094e+08,-301335.99,1.509094e+08,-301335.99,3.168521e+08,459465.29,2021-01-21
8,2021-01-21 09:29:03.000,2021-01-21 09:29:00.000,2021-01-21,A,7326.21,0,1.347866e+08,-7691.32,1.509167e+08,-301335.99,1.509167e+08,-301335.99,3.168598e+08,459465.29,2021-01-21
9,2021-01-21 09:30:03.000,2021-01-21 09:30:00.000,2021-01-21,A,4211.68,0,1.347909e+08,-7691.32,1.509209e+08,-301335.99,1.509209e+08,-301335.99,3.168640e+08,459465.29,2021-01-21

In [21]:
df =  Unifier.get_dataframe(name="lseg_us_eqt_short_interest_factor_1min_v1_2", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2025-11-21 09:31:03.000,2025-11-21 09:31:00.000,2025-11-21,PSR,0.00,0.00,-39840.87,3428.32,-152954.53,19450.50,-180754.41,25293.69,-405309.54,81262.19,2025-11-21
1,2025-11-21 09:34:03.000,2025-11-21 09:34:00.000,2025-11-21,PSR,0.00,271.44,-39840.87,3699.76,-152954.53,19721.94,-180754.41,25565.13,-408193.11,81533.63,2025-11-21
2,2025-11-21 09:39:03.000,2025-11-21 09:39:00.000,2025-11-21,PSR,0.00,0.00,-39840.87,3881.71,-152954.53,19721.94,-180754.41,25565.13,-408193.11,81162.12,2025-11-21
3,2025-11-21 09:43:03.000,2025-11-21 09:43:00.000,2025-11-21,PSR,0.00,0.00,-39840.87,3881.71,-152954.53,19812.76,-180754.41,25565.13,-405966.99,81162.12,2025-11-21
4,2025-11-21 09:51:03.000,2025-11-21 09:51:00.000,2025-11-21,PSR,0.00,0.00,-39840.87,3972.92,-152954.53,19812.76,-180754.41,25565.13,-405966.99,81162.12,2025-11-21
5,2025-11-21 09:54:03.000,2025-11-21 09:54:00.000,2025-11-21,PSR,0.00,0.00,-39840.87,3972.92,-152954.53,19812.76,-180754.41,25565.13,-405966.99,81162.12,2025-11-21
6,2025-11-21 10:02:03.000,2025-11-21 10:02:00.000,2025-11-21,PSR,-90.52,90.52,-39931.39,4063.44,-153045.05,19903.28,-180844.93,25655.65,-397250.73,63639.08,2025-11-21
7,2025-11-21 10:07:03.000,2025-11-21 10:07:00.000,2025-11-21,PSR,0.00,90.60,-39749.08,4154.04,-152863.44,19993.88,-180844.93,25746.25,-396137.61,63822.57,2025-11-21
8,2025-11-21 10:15:03.000,2025-11-21 10:15:00.000,2025-11-21,PSR,0.00,0.00,-38565.27,4062.88,-152863.44,19993.88,-180844.93,25746.25,-395951.96,63915.40,2025-11-21
9,2025-11-21 10:22:03.000,2025-11-21 10:22:00.000,2025-11-21,PSR,0.00,0.00,-38474.02,4062.88,-164338.20,19993.88,-180844.93,25746.25,-395951.96,63915.40,2025-11-21

## Download data file for a specific date using asof_date

In [22]:
Unifier.replicate(name="lseg_us_eqt_short_interest_factor_1min_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_eqt_short_interest_factor_1min_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_short_interest_factor_1min_v1_2. Downloaded 1 files.