In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name="xtech_security_master_evt_lst", asof_date='2024-01-18', limit=10)
display(df)

,lstuniqueid,scexhid,listsourceflag,globalstatuscd,issid,issuername,secid,securitydescription,parvalue,parvaluecurencd,...,eventlabel21,eventvalue21,eventlabel22,eventvalue22,eventlabel23,eventvalue23,eventlabel24,eventvalue24,evtchangedate,asof_date
0,16556,6556,M,A,6309,West India Biscuit Company Limited,6557,Ordinary Shares,NaN,BBD,...,None,None,None,None,None,None,None,None,2001-02-21,2001-02-21
1,16557,6557,M,I,6311,West Indies Rum Distilleries Ltd.,6558,Ordinary Shares,1.70,BBD,...,None,None,None,None,None,None,None,None,2001-02-21,2001-02-21
2,16699,6699,M,I,6448,Egyptian Contracting (Mokhtar Ibrahim),6700,Ordinary Shares,5.00,EGP,...,None,None,None,None,None,None,None,None,2001-02-21,2001-02-21
3,1997,997,M,I,988,Fuzfoi Papir Rt.,997,Ordinary Shares,1000.00,HUF,...,None,None,None,None,None,None,None,None,2001-01-29,2001-01-29
4,14120,4120,M,I,3976,Takioji Neris Pva,4121,Ordinary Shares,5.00,LTL,...,None,None,None,None,None,None,None,None,2001-01-29,2001-01-29
5,18085,8085,M,I,7819,Mandatum Pankki,8103,Ordinary Shares - Class B,2.00,FIM,...,None,None,None,None,None,None,None,None,2001-03-01,2001-03-01
6,18092,8092,M,I,7823,OP Corporate Bank Plc,8110,Ordinary Shares - Class A,NaN,EUR,...,None,None,None,None,None,None,None,None,2001-03-01,2001-03-01
7,18286,8286,M,A,8007,Konecranes Oyj,8301,Ordinary Shares,2.00,EUR,...,None,None,None,None,None,None,None,None,2001-03-01,2001-03-01
8,18085,8085,M,I,7819,Mandatum Pankki,8103,Ordinary Shares - Class B,2.00,FIM,...,None,None,None,None,None,None,None,None,2001-03-01,2001-03-01
9,18497,8497,M,A,8214,Tecnomen Oyj,8515,Ordinary Shares,0.04,FIM,...,None,None,None,None,None,None,None,None,2001-03-01,2001-03-01

## Retrieve data for a specific date range using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_security_master_evt_lst', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,DDOG,US23804L1035,DDOG,RegularMkt,EQT,Call,2,...,0,7,0,0,0,0.00,0.288500,0,0.000000,2024-01-31
1,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,DDOG,US23804L1035,DDOG,RegularMkt,EQT,Call,1,...,0,0,0,1,1,9.35,0.000000,0,0.142084,2024-01-31
2,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,DDOG,US23804L1035,DDOG,RegularMkt,EQT,Call,21,...,0,0,0,1,36,10.20,0.000000,0,11.090772,2024-01-31
3,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,DE,US2441991054,DE,RegularMkt,EQT,Call,2,...,0,1,0,0,0,0.00,0.135279,0,0.000000,2024-01-31
4,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,DFS,US2547091080,DFS,RegularMkt,EQT,Call,16,...,0,0,0,1,2,2.80,0.000000,0,0.181221,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,ENPH,US29355A1079,ENPH,RegularMkt,EQT,Put,15,...,0,0,0,1,1,15.95,0.000000,0,0.144648,2024-01-31
96,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,ENPH,US29355A1079,ENPH,RegularMkt,EQT,Put,15,...,0,1,0,0,0,0.00,0.275198,0,0.000000,2024-01-31
97,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,ENPH,US29355A1079,ENPH,RegularMkt,EQT,Put,15,...,0,1,0,0,0,0.00,0.254442,0,0.000000,2024-01-31
98,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,ENPH,US29355A1079,ENPH,RegularMkt,EQT,Call,19,...,0,0,0,1,1,11.90,0.000000,0,0.196768,2024-01-31
99,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:13:00.000,ENPH,US29355A1079,ENPH,RegularMkt,EQT,Call,21,...,0,1,0,0,0,0.00,0.260604,0,0.000000,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name='xtech_us_eqt_options_flow_r3k_with_isin_1min_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,7,...,0,0,0,2,3,0.010000,0.000,0,0.015,2014-03-05
1,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,7,...,0,5,0,0,0,0.000000,0.780,0,0.000,2014-03-05
2,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,7,...,0,0,0,1,4,0.030000,0.000,0,0.056,2014-03-05
3,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,7,...,0,7,0,10,19,0.050000,0.476,0,0.323,2014-03-05
4,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,7,...,0,0,0,3,3,0.063333,0.000,0,0.069,2014-03-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,28,...,0,0,0,1,5,2.400000,0.000,0,1.885,2014-03-05
96,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,28,...,0,0,0,1,1,0.710000,0.000,0,0.183,2014-03-05
97,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,4,...,0,1,0,0,0,0.000000,1.278,0,0.000,2014-03-05
98,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,4,...,0,1,0,0,0,0.000000,0.638,0,0.000,2014-03-05
99,2014-03-05,2014-03-05 23:30:30.000,2014-03-05 13:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,4,...,0,0,0,1,2,2.650000,0.000,0,0.828,2014-03-05

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='xtech_us_eqt_options_flow_r3k_with_isin_1min_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,5,...,0,1,0,0,0,0.000000,0.000334,0.0,0.000000,2024-01-03
1,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,5,...,0,1,0,0,0,0.000000,0.001593,0.0,0.000000,2024-01-03
2,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,5,...,0,1,0,1,1,0.020000,0.005948,0.0,0.004573,2024-01-03
3,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,5,...,0,1,0,0,0,0.000000,0.025438,0.0,0.000000,2024-01-03
4,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,5,...,0,1,0,4,6,0.031667,0.049125,0.0,0.041770,2024-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,19,...,0,1,0,1,1,0.060000,0.087580,0.0,0.019471,2024-01-03
96,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,19,...,0,33,0,2,2,0.040000,9.557004,0.0,0.027563,2024-01-03
97,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,19,...,0,0,0,1,1,0.030000,0.000000,0.0,0.010483,2024-01-03
98,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,19,...,0,1,0,0,0,0.000000,0.029558,0.0,0.000000,2024-01-03
99,2024-01-03,2024-01-03 23:30:30.000,2024-01-03 14:31:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,19,...,0,2,0,1,1,0.010000,0.021910,0.0,0.003943,2024-01-03

## Download data file for a specific date using asof_date

In [12]:
Unifier.replicate(name="xtech_us_eqt_options_flow_r3k_with_isin_1min_trial", target_location="./data", asof_date='2026-01-12')

Starting native python replication for xtech_us_eqt_options_flow_r3k_with_isin_1min_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_options_flow_r3k_with_isin_1min_trial. Downloaded 1 files.