In [3]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [4]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name="xtech_us_eqt_options_flow_with_isin", asof_date='2024-01-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,OLED,US91347P1057,OLED,RegularMkt,EQT,Call,22,...,0,1,0,0,0,0.00,0.1782,0,0.0000,2020-05-19
1,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,ORCL,US68389X1054,ORCL,RegularMkt,EQT,Put,26,...,0,1,0,0,0,0.00,0.0676,0,0.0000,2020-05-19
2,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,PAYX,US7043261079,PAYX,RegularMkt,EQT,Call,18,...,0,0,0,1,1,3.29,0.0000,0,0.1851,2020-05-19
3,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,PETS,US7163821066,PETS,RegularMkt,EQT,Call,21,...,0,0,0,1,1,10.02,0.0000,0,0.1483,2020-05-19
4,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,PSX,US7185461040,PSX,RegularMkt,EQT,Call,21,...,0,1,0,0,0,0.00,0.0815,0,0.0000,2020-05-19
5,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,QEP,US74733V1008,QEP,RegularMkt,EQT,Call,15,...,0,0,0,2,2,0.15,0.0000,0,0.0038,2020-05-19
6,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,RICK,US74934Q1085,RICK,RegularMkt,EQT,Call,17,...,0,0,0,1,10,0.21,0.0000,0,0.1330,2020-05-19
7,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,RRR,US75700L1089,RRR,RegularMkt,EQT,Put,19,...,0,1,0,0,0,0.00,0.0116,0,0.0000,2020-05-19
8,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,RRR,US75700L1089,RRR,RegularMkt,EQT,Put,19,...,0,0,0,1,2,0.88,0.0000,0,0.0234,2020-05-19
9,2020-05-19,2020-05-19 23:30:30.000,2020-05-19 19:34:00.000,RTW,US74980D1000,RTW,RegularMkt,EQT,Call,16,...,0,1,0,0,0,0.00,0.0000,0,0.0000,2020-05-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='xtech_us_eqt_options_flow_with_isin', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:55:00.000,HD,US4370761029,HD,RegularMkt,EQT,Put,2,...,0,3,0,0,0,0.00,2.733126,0,0.000000,2024-01-31
1,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:55:00.000,HD,US4370761029,HD,RegularMkt,EQT,Call,2,...,0,1,0,0,0,0.00,2.166273,0,0.000000,2024-01-31
2,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:55:00.000,HD,US4370761029,HD,RegularMkt,EQT,Call,2,...,0,2,0,0,0,0.00,0.122372,0,0.000000,2024-01-31
3,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:55:00.000,HD,US4370761029,HD,RegularMkt,EQT,Call,16,...,0,1,0,0,0,0.00,0.291793,0,0.000000,2024-01-31
4,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:55:00.000,HON,US4385161066,HON,RegularMkt,EQT,Put,2,...,0,0,0,1,3,0.91,0.000000,0,0.150288,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:56:00.000,AMZN,US0231351067,AMZN,RegularMkt,EQT,Call,2,...,0,1,0,0,0,0.00,0.055752,0,0.000000,2024-01-31
96,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:56:00.000,AMZN,US0231351067,AMZN,RegularMkt,EQT,Call,2,...,0,7,0,0,0,0.00,5.596495,0,0.000000,2024-01-31
97,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:56:00.000,AMZN,US0231351067,AMZN,RegularMkt,EQT,Call,2,...,0,1,0,1,20,3.02,0.103936,0,1.040336,2024-01-31
98,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:56:00.000,AMZN,US0231351067,AMZN,RegularMkt,EQT,Call,2,...,0,1,0,1,5,2.23,0.142794,0,0.237671,2024-01-31
99,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:56:00.000,AMZN,US0231351067,AMZN,RegularMkt,EQT,Call,2,...,0,2,0,0,0,0.00,0.070746,0,0.000000,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name='xtech_us_eqt_options_flow_with_isin',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,3,...,0,1,0,0,0,0.000000,0.0032,0.0,0.0000,2020-04-03
1,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,3,...,0,1,0,0,0,0.000000,0.0008,0.0,0.0000,2020-04-03
2,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,3,...,0,2,0,2,4,0.010000,0.0060,0.0,0.0024,2020-04-03
3,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,3,...,0,1,0,2,21,5.107143,0.0037,0.0,0.0010,2020-04-03
4,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,3,...,0,5,0,5,9,0.020000,0.0472,0.0,0.0100,2020-04-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,15,...,0,0,0,3,5,17.410000,0.0000,0.0,1.6160,2020-04-03
96,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,15,...,0,1,0,1,1,19.630000,0.3230,0.0,0.3230,2020-04-03
97,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,15,...,0,1,0,0,0,0.000000,0.3174,0.0,0.0000,2020-04-03
98,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,15,...,0,1,0,0,0,0.000000,0.4144,0.0,0.0000,2020-04-03
99,2020-04-03,2020-04-03 23:30:30.000,2020-04-03 19:50:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,15,...,0,0,0,2,6,2.206667,0.0000,0.0,1.0452,2020-04-03

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [10]:
df = Unifier.get_dataframe(name='xtech_us_eqt_options_flow_with_isin',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-08,2024-01-08 23:30:30.000,2024-01-08 20:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,26,...,0,1,0,0,0,0.00,0.125156,0,0.000000,2024-01-08
1,2024-01-08,2024-01-08 23:30:30.000,2024-01-08 20:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,26,...,0,5,0,5,120,3.50,2.148735,0,19.833000,2024-01-08
2,2024-01-08,2024-01-08 23:30:30.000,2024-01-08 20:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,26,...,0,0,0,2,2,2.21,0.000000,0,0.328204,2024-01-08
3,2024-01-08,2024-01-08 23:30:30.000,2024-01-08 20:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,26,...,0,2,0,2,52,1.30,0.289012,0,7.517588,2024-01-08
4,2024-01-08,2024-01-08 23:30:30.000,2024-01-08 20:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,26,...,0,0,0,1,1,0.71,0.000000,0,0.112611,2024-01-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-18,2024-01-18 23:30:30.000,2024-01-18 20:03:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,15,...,0,0,0,2,5,0.79,0.000000,0,0.567505,2024-01-18
96,2024-01-18,2024-01-18 23:30:30.000,2024-01-18 20:03:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,15,...,0,1,0,0,0,0.00,0.954252,0,0.000000,2024-01-18
97,2024-01-18,2024-01-18 23:30:30.000,2024-01-18 20:03:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,15,...,0,0,0,1,4,2.79,0.000000,0,0.962372,2024-01-18
98,2024-01-18,2024-01-18 23:30:30.000,2024-01-18 20:03:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,15,...,0,0,0,1,1,4.10,0.000000,0,0.289326,2024-01-18
99,2024-01-18,2024-01-18 23:30:30.000,2024-01-18 20:03:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,15,...,0,0,0,5,10,2.45,0.000000,0,2.521450,2024-01-18

## Download data file for a specific date using asof_date

In [11]:
Unifier.replicate(name="xtech_us_eqt_options_flow_with_isin", target_location="./data", asof_date='2026-01-12')

Starting native python replication for xtech_us_eqt_options_flow_with_isin (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_options_flow_with_isin. Downloaded 1 files.