In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_daily_bid_ask_distribution", asof_date='2026-10-21', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,strike,bin_low,bin_high,midpoint,yes_price,adjusted_yes_price,probability,daily_volume,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,2.50,None,None,None,0.0,99.0,0.000000,0.00,2026-10-21 14:08:35.165,2026-10-20
1,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,2.75,None,None,None,99.0,99.0,0.000000,0.00,2026-10-21 14:08:35.165,2026-10-20
2,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,3.00,None,None,None,99.0,99.0,0.000000,0.00,2026-10-21 14:08:35.165,2026-10-20
3,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,3.25,None,None,None,98.5,98.5,0.510204,0.00,2026-10-21 14:08:35.165,2026-10-20
4,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,3.50,None,None,None,98.5,98.5,1.020408,0.00,2026-10-21 14:08:35.165,2026-10-20
5,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,3.75,None,None,None,97.5,97.5,15.306122,0.00,2026-10-21 14:08:35.165,2026-10-20
6,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,4.00,None,None,None,82.5,82.5,69.387755,4075.18,2026-10-21 14:08:35.165,2026-10-20
7,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,4.25,None,None,None,14.5,14.5,10.204082,971.50,2026-10-21 14:08:35.165,2026-10-20
8,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,4.50,None,None,None,4.5,4.5,4.081633,41.00,2026-10-21 14:08:35.165,2026-10-20
9,fed_levels,KXFED,KXFED-26DEC,2026-12-09,threshold,4.75,None,None,None,0.5,0.5,-0.510204,100.00,2026-10-21 14:08:35.165,2026-10-20

## Retrieve data for a specific date range using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_bid_ask_distribution', back_to='2026-09-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,strike,bin_low,bin_high,midpoint,yes_price,adjusted_yes_price,probability,daily_volume,asof_datetime,asof_date
0,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.0,None,None,None,0.0,98.5,0.000000,0.0,2026-10-21 14:05:57.935,2026-09-27
1,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.1,None,None,None,98.5,98.5,0.510204,0.0,2026-10-21 14:05:57.935,2026-09-27
2,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.2,None,None,None,98.5,98.5,14.285714,93.5,2026-10-21 14:05:57.935,2026-09-27
3,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.3,None,None,None,84.5,84.5,40.816327,0.0,2026-10-21 14:05:57.935,2026-09-27
4,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.4,None,None,None,44.5,44.5,32.142857,40.0,2026-10-21 14:05:57.935,2026-09-27
5,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.5,None,None,None,13.0,13.0,10.714286,0.0,2026-10-21 14:05:57.935,2026-09-27
6,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.6,None,None,None,2.5,2.5,2.040816,0.0,2026-10-21 14:05:57.935,2026-09-27
7,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.7,None,None,None,0.5,0.5,-0.510204,0.0,2026-10-21 14:05:57.935,2026-09-27
8,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.8,None,None,None,0.5,0.5,0.000000,0.0,2026-10-21 14:05:57.935,2026-09-27
9,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26SEP,2026-10-14,threshold,2.9,None,None,None,0.5,0.5,0.000000,0.0,2026-10-21 14:05:57.935,2026-09-27

## Retrieve data for a specific date with a specific contract_preamble (key='contract_preamble') using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_bid_ask_distribution',key='KXFED-26OCT', asof_date='2026-10-22', limit=100)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,strike,bin_low,bin_high,midpoint,yes_price,adjusted_yes_price,probability,daily_volume,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,2.50,None,None,None,0.0,99.5,0.000000,0.0,2026-10-21 14:05:27.905,2026-09-05
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,2.75,None,None,None,99.5,99.5,-0.510204,0.0,2026-10-21 14:05:27.905,2026-09-05
2,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.00,None,None,None,99.5,99.5,1.020408,0.0,2026-10-21 14:05:27.905,2026-09-05
3,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.25,None,None,None,98.5,98.5,2.040816,455.0,2026-10-21 14:05:27.905,2026-09-05
4,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.50,None,None,None,96.5,96.5,37.244898,548.0,2026-10-21 14:05:27.905,2026-09-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,5.25,None,None,None,0.5,0.5,0.000000,0.0,2026-10-21 14:06:07.631,2026-10-04
96,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,2.50,None,None,None,0.0,99.5,0.000000,0.0,2026-10-21 14:05:46.861,2026-09-19
97,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,2.75,None,None,None,99.5,99.5,0.000000,0.0,2026-10-21 14:05:46.861,2026-09-19
98,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.00,None,None,None,99.5,99.5,0.000000,0.0,2026-10-21 14:05:46.861,2026-09-19
99,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.25,None,None,None,99.5,99.5,-0.510204,0.0,2026-10-21 14:05:46.861,2026-09-19

## Retrieve data for a specific date range with a specific contract_preamble (key='contract_preamble') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_bid_ask_distribution',key='KXFED-26OCT', back_to='2026-09-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,strike,bin_low,bin_high,midpoint,yes_price,adjusted_yes_price,probability,daily_volume,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,2.50,None,None,None,0.0,99.5,0.000000,0,2026-10-21 14:05:27.905,2026-09-05
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,2.75,None,None,None,99.5,99.5,-0.510204,0,2026-10-21 14:05:27.905,2026-09-05
2,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.00,None,None,None,99.5,99.5,1.020408,0,2026-10-21 14:05:27.905,2026-09-05
3,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.25,None,None,None,98.5,98.5,2.040816,455,2026-10-21 14:05:27.905,2026-09-05
4,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.50,None,None,None,96.5,96.5,37.244898,548,2026-10-21 14:05:27.905,2026-09-05
5,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.75,None,None,None,60.0,60.0,56.122449,9,2026-10-21 14:05:27.905,2026-09-05
6,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,4.00,None,None,None,5.0,5.0,4.591837,128,2026-10-21 14:05:27.905,2026-09-05
7,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,4.25,None,None,None,0.5,0.5,-0.510204,0,2026-10-21 14:05:27.905,2026-09-05
8,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,4.50,None,None,None,0.5,0.5,0.000000,0,2026-10-21 14:05:27.905,2026-09-05
9,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,4.75,None,None,None,1.0,0.5,0.000000,0,2026-10-21 14:05:27.905,2026-09-05

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="kalshi_macro_daily_bid_ask_distribution", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_macro_daily_bid_ask_distribution...
Found 1 files to download.
Native replication completed for kalshi_macro_daily_bid_ask_distribution. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_daily_bid_ask_distribution", target_location="./data")