In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_daily_distribution", asof_date='2026-10-21', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,strike,bin_low,bin_high,midpoint,yes_price,adjusted_yes_price,probability,daily_volume,asof_datetime,asof_date
0,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26FEB,2026-03-11,threshold,2.3,None,None,None,0,77,22.448980,0,2026-10-21 12:12:05.097,2026-02-10
1,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26FEB,2026-03-11,threshold,2.4,None,None,None,77,77,9.183673,0,2026-10-21 12:12:05.097,2026-02-10
2,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26FEB,2026-03-11,threshold,2.5,None,None,None,68,68,7.142857,0,2026-10-21 12:12:05.097,2026-02-10
3,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26FEB,2026-03-11,threshold,2.6,None,None,None,61,61,7.142857,0,2026-10-21 12:12:05.097,2026-02-10
4,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26FEB,2026-03-11,threshold,2.7,None,None,None,54,54,54.081633,0,2026-10-21 12:12:05.097,2026-02-10
5,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26JAN,2026-02-13,threshold,2.3,None,None,None,0,86,13.265306,0,2026-10-21 12:12:05.097,2026-02-10
6,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26JAN,2026-02-13,threshold,2.4,None,None,None,86,86,19.387755,64,2026-10-21 12:12:05.097,2026-02-10
7,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26JAN,2026-02-13,threshold,2.5,None,None,None,67,67,42.857143,575,2026-10-21 12:12:05.097,2026-02-10
8,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26JAN,2026-02-13,threshold,2.6,None,None,None,25,25,1.020408,312,2026-10-21 12:12:05.097,2026-02-10
9,core_cpi_releases,KXCPICOREYOY,KXCPICOREYOY-26JAN,2026-02-13,threshold,2.7,None,None,None,24,24,20.408163,0,2026-10-21 12:12:05.097,2026-02-10

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_distribution', back_to='2026-09-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,strike,bin_low,bin_high,midpoint,yes_price,adjusted_yes_price,probability,daily_volume,asof_datetime,asof_date
0,core_cpi_releases,KXCPICOREYOY,CPICOREYOY-23AUG,2023-09-13,threshold,3.90,None,None,None,0,94,0.000000,0,2026-10-21 09:15:47.012,2023-08-14
1,core_cpi_releases,KXCPICOREYOY,CPICOREYOY-23AUG,2023-09-13,threshold,4.00,None,None,None,89,94,5.102041,0,2026-10-21 09:15:47.012,2023-08-14
2,core_cpi_releases,KXCPICOREYOY,CPICOREYOY-23AUG,2023-09-13,threshold,4.10,None,None,None,94,94,25.510204,12,2026-10-21 09:15:47.012,2023-08-14
3,core_cpi_releases,KXCPICOREYOY,CPICOREYOY-23AUG,2023-09-13,threshold,4.20,None,None,None,69,69,26.530612,0,2026-10-21 09:15:47.012,2023-08-14
4,core_cpi_releases,KXCPICOREYOY,CPICOREYOY-23AUG,2023-09-13,threshold,4.30,None,None,None,43,43,28.571429,0,2026-10-21 09:15:47.012,2023-08-14
5,core_cpi_releases,KXCPICOREYOY,CPICOREYOY-23AUG,2023-09-13,threshold,4.40,None,None,None,15,15,14.285714,0,2026-10-21 09:15:47.012,2023-08-14
6,fed_levels,KXFED,FED-23DEC,2023-12-13,threshold,2.75,None,None,None,0,98,0.000000,0,2026-10-21 09:15:47.012,2023-08-14
7,fed_levels,KXFED,FED-23DEC,2023-12-13,threshold,3.00,None,None,None,98,98,0.000000,0,2026-10-21 09:15:47.012,2023-08-14
8,fed_levels,KXFED,FED-23DEC,2023-12-13,threshold,3.25,None,None,None,0,97,0.000000,0,2026-10-21 09:15:47.012,2023-08-14
9,fed_levels,KXFED,FED-23DEC,2023-12-13,threshold,3.50,None,None,None,0,97,0.000000,0,2026-10-21 09:15:47.012,2023-08-14

## Retrieve data for a specific date with a specific contract_preamble (key='contract_preamble') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_distribution',key='KXFED-26OCT', asof_date='2026-10-15', limit=10)
display(df)

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date range with a specific contract_preamble (key='contract_preamble') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_distribution',key='KXFED-26OCT', back_to='2026-09-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,contract_preamble,expiry_date,method,strike,bin_low,bin_high,midpoint,yes_price,adjusted_yes_price,probability,daily_volume,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,2.50,None,None,None,0.0,99.0,0.000000,0.00,2026-10-21 14:05:46.861,2026-09-19
1,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,2.75,None,None,None,87.0,99.0,0.000000,0.00,2026-10-21 14:05:46.861,2026-09-19
2,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.00,None,None,None,99.0,99.0,0.000000,0.00,2026-10-21 14:05:46.861,2026-09-19
3,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.25,None,None,None,98.0,98.0,0.000000,0.00,2026-10-21 14:05:46.861,2026-09-19
4,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.50,None,None,None,98.0,98.0,1.020408,0.00,2026-10-21 14:05:46.861,2026-09-19
5,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,3.75,None,None,None,98.0,98.0,40.816327,343.58,2026-10-21 14:05:46.861,2026-09-19
6,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,4.00,None,None,None,58.0,58.0,57.142857,1008.63,2026-10-21 14:05:46.861,2026-09-19
7,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,4.25,None,None,None,2.0,2.0,1.020408,1537.46,2026-10-21 14:05:46.861,2026-09-19
8,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,4.50,None,None,None,1.0,1.0,0.000000,0.00,2026-10-21 14:05:46.861,2026-09-19
9,fed_levels,KXFED,KXFED-26OCT,2026-10-28,threshold,4.75,None,None,None,0.0,1.0,0.000000,0.00,2026-10-21 14:05:46.861,2026-09-19

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="kalshi_macro_daily_distribution", target_location="./data", asof_date='2026-10-15')

Downloading using native python implementation for kalshi_macro_daily_distribution...
Found 1 files to download.
Native replication completed for kalshi_macro_daily_distribution. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_daily_distribution", target_location="./data")