In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name="kalshi_macro_market_settlements", asof_date='2026-12-22', limit=10)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,settlement_bounds_type,settlement_floor,settlement_timer_seconds,is_provisional,volume,open_interest,last_price,source_tier,asof_datetime,asof_date
0,CPI-21JUL-T0.7,CPI-21JUL,KXCPI,binary,Will the Consumer Price Index (CPI) increase b...,Above 0.7%,0.7% or below,finalized,no,2021-07-13 20:49:15.200,...,default,None,0,None,22562.00,0.00,0.3900,historical,2026-10-21 07:10:53.414,2021-08-12
1,KXPAYROLLS-25SEP-T-100000,KXPAYROLLS-25SEP,KXPAYROLLS,binary,Will above -100000 jobs be added in September ...,"Above -100,000","Above -100,000",finalized,yes,2025-08-13 15:06:05.935,...,default,None,300,None,94138.00,0.00,0.9700,historical,2026-10-21 07:10:53.414,2025-11-20
2,KXPAYROLLS-25SEP-T0,KXPAYROLLS-25SEP,KXPAYROLLS,binary,Will above 0 jobs be added in September 2025?,Above 0,Above 0,finalized,yes,2025-08-13 15:06:05.935,...,default,None,300,None,469888.00,0.00,0.7900,historical,2026-10-21 07:10:53.414,2025-11-20
3,KXPAYROLLS-25SEP-T100000,KXPAYROLLS-25SEP,KXPAYROLLS,binary,Will above 100000 jobs be added in September 2...,"Above 100,000","Above 100,000",finalized,yes,2025-08-13 15:06:05.935,...,default,None,300,None,88513.00,0.00,0.1000,historical,2026-10-21 07:10:53.414,2025-11-20
4,KXPAYROLLS-25SEP-T125000,KXPAYROLLS-25SEP,KXPAYROLLS,binary,Will above 125000 jobs be added in September 2...,"Above 125,000","Above 125,000",finalized,no,2025-08-13 15:06:05.935,...,default,None,300,None,46800.00,0.00,0.0600,historical,2026-10-21 07:10:53.414,2025-11-20
5,KXPAYROLLS-25SEP-T25000,KXPAYROLLS-25SEP,KXPAYROLLS,binary,Will above 25000 jobs be added in September 2025?,"Above 25,000","Above 25,000",finalized,yes,2025-08-13 15:06:05.935,...,default,None,300,None,393253.00,0.00,0.5800,historical,2026-10-21 07:10:53.414,2025-11-20
6,KXPAYROLLS-25SEP-T50000,KXPAYROLLS-25SEP,KXPAYROLLS,binary,Will above 50000 jobs be added in September 2025?,"Above 50,000","Above 50,000",finalized,yes,2025-08-13 15:06:05.935,...,default,None,300,None,218963.00,0.00,0.3600,historical,2026-10-21 07:10:53.414,2025-11-20
7,KXPAYROLLS-25SEP-T75000,KXPAYROLLS-25SEP,KXPAYROLLS,binary,Will above 75000 jobs be added in September 2025?,"Above 75,000","Above 75,000",finalized,yes,2025-08-13 15:06:05.935,...,default,None,300,None,229487.00,0.00,0.2000,historical,2026-10-21 07:10:53.414,2025-11-20
8,KXU3-25SEP-T3.8,KXU3-25SEP,KXU3,binary,Will the unemployment rate (U-3) be above 3.8%...,Above 3.8%,Above 3.8%,finalized,yes,2025-08-13 15:06:01.866,...,default,None,300,None,5157.00,0.00,0.9900,historical,2026-10-21 07:10:53.414,2025-11-20
9,KXU3-25SEP-T3.9,KXU3-25SEP,KXU3,binary,Will the unemployment rate (U-3) be above 3.9%...,Above 3.9%,Above 3.9%,finalized,yes,2025-08-13 15:06:01.866,...,default,None,300,None,7114.00,0.00,0.9800,historical,2026-10-21 07:10:53.414,2025-11-20

## Retrieve data for a specific date range using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='kalshi_macro_market_settlements', back_to='2025-12-01', up_to='2026-12-31', limit=100)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,settlement_bounds_type,settlement_floor,settlement_timer_seconds,is_provisional,volume,open_interest,last_price,source_tier,asof_datetime,asof_date
0,U3-21NOV-T4.3,U3-21NOV,KXU3,binary,Will the **unemployment rate** (U-3) be above ...,Above 4.3%,4.3% or below,finalized,no,2021-11-08 14:54:49.499,...,default,None,50400,None,4674.00,0.00,0.7200,historical,2026-10-21 07:10:53.414,2021-12-04
1,FED-24NOV-T3.50,FED-24NOV,KXFED,binary,Will the upper bound of the federal funds rate...,Above 3.50%,Above 3.50%,finalized,yes,2023-07-05 15:29:07.216,...,default,None,0,None,14108.00,0.00,0.9900,historical,2026-10-21 07:10:53.414,2024-11-08
2,FED-24NOV-T3.75,FED-24NOV,KXFED,binary,Will the upper bound of the federal funds rate...,Above 3.75%,Above 3.75%,finalized,yes,2023-07-05 15:29:07.216,...,default,None,0,None,14040.00,0.00,0.9900,historical,2026-10-21 07:10:53.414,2024-11-08
3,FED-24NOV-T4.00,FED-24NOV,KXFED,binary,Will the upper bound of the federal funds rate...,Above 4.00%,Above 4.00%,finalized,yes,2023-07-05 15:29:07.216,...,default,None,0,None,10886.00,0.00,0.9900,historical,2026-10-21 07:10:53.414,2024-11-08
4,FED-24NOV-T4.25,FED-24NOV,KXFED,binary,Will the upper bound of the federal funds rate...,Above 4.25%,Above 4.25%,finalized,yes,2023-07-05 15:29:07.216,...,default,None,0,None,37099.00,0.00,0.9900,historical,2026-10-21 07:10:53.414,2024-11-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,KXCPICOREYOY-26MAR-T2.5,KXCPICOREYOY-26MAR,KXCPICOREYOY,binary,Will the rate of core CPI inflation be above 2...,Above 2.5%,Above 2.5%,finalized,yes,2026-02-17 19:47:59.693,...,default,None,3600,None,38000.03,0.00,0.8600,historical,2026-10-21 07:10:53.414,2026-04-10
96,KXCPICOREYOY-26MAR-T2.6,KXCPICOREYOY-26MAR,KXCPICOREYOY,binary,Will the rate of core CPI inflation be above 2...,Above 2.6%,Above 2.6%,finalized,no,2026-02-17 19:47:59.693,...,default,None,3600,None,32525.27,0.00,0.5300,historical,2026-10-21 07:10:53.414,2026-04-10
97,KXCPICOREYOY-26MAR-T2.7,KXCPICOREYOY-26MAR,KXCPICOREYOY,binary,Will the rate of core CPI inflation be above 2...,Above 2.7%,Above 2.7%,finalized,no,2026-02-17 19:47:59.693,...,default,None,3600,None,40309.74,0.00,0.1400,historical,2026-10-21 07:10:53.414,2026-04-10
98,KXCPICOREYOY-26MAR-T2.8,KXCPICOREYOY-26MAR,KXCPICOREYOY,binary,Will the rate of core CPI inflation be above 2...,Above 2.8%,Above 2.8%,finalized,no,2026-02-17 19:47:59.693,...,default,None,3600,None,12573.29,0.00,0.0900,historical,2026-10-21 07:10:53.414,2026-04-10
99,KXCPICOREYOY-26MAR-T2.9,KXCPICOREYOY-26MAR,KXCPICOREYOY,binary,Will the rate of core CPI inflation be above 2...,Above 2.9%,Above 2.9%,finalized,no,2026-02-17 19:47:59.693,...,default,None,3600,None,8699.12,0.00,0.0800,historical,2026-10-21 07:10:53.414,2026-04-10

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name='kalshi_macro_market_settlements',key='KXFED-25DEC-T3.75', asof_date='2026-12-10', limit=10)
display(df)

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [10]:
df = Unifier.get_dataframe(name='kalshi_macro_market_settlements',key='KXFED-25DEC-T3.75', back_to='2025-12-01', up_to='2026-12-31', limit=10)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [11]:
Unifier.replicate(name="kalshi_macro_market_settlements", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_macro_market_settlements...
Found 1 files to download.
Native replication completed for kalshi_macro_market_settlements. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_market_settlements", target_location="./data")