In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_trades_tick", asof_date='2026-10-22', limit=10)
display(df)

,trade_id,ticker,event_ticker,series_ticker,timestamp,date,yes_price,no_price,count,taker_price,notional_usd,taker_outcome_side,taker_book_side,is_block_trade,source_tier,asof_datetime,asof_date
0,07243291-6671-9f99-b607-9f1ecdc6f597,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,2026-10-21 01:20:03.802,2026-10-21,0.9200,0.0800,24.00,0.9200,22.0800,yes,bid,False,live,2026-10-22 02:33:01.415,2026-10-21
1,07243290-86b1-9e39-bde5-02de43212227,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,2026-10-21 01:20:05.885,2026-10-21,0.9200,0.0800,50.00,0.9200,46.0000,yes,bid,False,live,2026-10-22 02:33:01.415,2026-10-21
2,07243290-86b1-bc05-d2b2-a0f473a5a8c3,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,2026-10-21 01:20:05.993,2026-10-21,0.9200,0.0800,24.00,0.9200,22.0800,yes,bid,False,live,2026-10-22 02:33:01.415,2026-10-21
3,072432de-9a31-beb1-be4e-c4746510bf0b,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,2026-10-21 01:34:49.919,2026-10-21,0.9200,0.0800,24.00,0.9200,22.0800,yes,bid,False,live,2026-10-22 02:33:01.415,2026-10-21
4,072432de-8ad1-b201-7d98-96c5046b481b,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,2026-10-21 01:34:50.876,2026-10-21,0.9200,0.0800,50.00,0.9200,46.0000,yes,bid,False,live,2026-10-22 02:33:01.415,2026-10-21
5,07243354-bd31-87fd-dc0a-2b8d38777643,KXCPI-26DEC-T-0.1,KXCPI-26DEC,KXCPI,2026-10-21 03:21:21.238,2026-10-21,0.9200,0.0800,24.00,0.9200,22.0800,yes,bid,False,live,2026-10-22 02:33:01.415,2026-10-21
6,07243554-4421-9b48-9580-1c91430ca6a1,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,2026-10-21 00:34:36.715,2026-10-21,0.9300,0.0700,140.00,0.9300,130.2000,yes,bid,False,live,2026-10-22 02:33:01.415,2026-10-21
7,07242c27-cb59-ac71-efd6-8f2f9f6a2815,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,2026-10-21 01:20:03.901,2026-10-21,0.9300,0.0700,24.00,0.0700,1.6800,no,ask,False,live,2026-10-22 02:33:01.415,2026-10-21
8,07242c26-2b99-91bd-1e3c-2e381c38d149,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,2026-10-21 01:20:05.885,2026-10-21,0.9300,0.0700,50.00,0.0700,3.5000,no,ask,False,live,2026-10-22 02:33:01.415,2026-10-21
9,07242c7b-c809-a0f3-19b6-ac718d654997,KXCPI-26DEC-T0.0,KXCPI-26DEC,KXCPI,2026-10-21 01:34:49.991,2026-10-21,0.9300,0.0700,24.00,0.0700,1.6800,no,ask,False,live,2026-10-22 02:33:01.415,2026-10-21

## Retrieve data for a specific date range using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='kalshi_macro_trades_tick', back_to='2026-10-01', up_to='2026-10-23', limit=100)
display(df)

,trade_id,ticker,event_ticker,series_ticker,timestamp,date,yes_price,no_price,count,taker_price,notional_usd,taker_outcome_side,taker_book_side,is_block_trade,source_tier,asof_datetime,asof_date
0,072301e7-dad1-9175-0dbc-aba71657f699,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-10-03 00:04:02.669,2026-10-03,0.8500,0.1500,1.00,0.1500,0.1500,no,ask,False,live,2026-10-21 14:05:17.461,2026-10-03
1,0723017a-7871-83ad-9d93-b2475a3542d6,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-10-03 00:40:11.923,2026-10-03,0.9600,0.0400,2.00,0.9600,1.9200,yes,bid,False,live,2026-10-21 14:05:17.461,2026-10-03
2,072303de-5ac1-84ac-be3c-9d16b2005a52,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-10-03 00:40:11.923,2026-10-03,0.9500,0.0500,23.00,0.9500,21.8500,yes,bid,False,live,2026-10-21 14:05:17.461,2026-10-03
3,0723017a-ac51-9dc1-9afd-d413a95d21d1,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-10-03 00:40:22.481,2026-10-03,0.8500,0.1500,25.00,0.1500,3.7500,no,ask,False,live,2026-10-21 14:05:17.461,2026-10-03
4,072303d8-bd51-97c3-ae2e-6227eff6646d,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-10-03 00:47:45.676,2026-10-03,0.9500,0.0500,1.00,0.9500,0.9500,yes,bid,False,live,2026-10-21 14:05:17.461,2026-10-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,07230359-d101-94f0-f99c-c639d46a685f,KXCPI-26OCT-T0.2,KXCPI-26OCT,KXCPI,2026-10-03 00:03:49.877,2026-10-03,0.6200,0.3800,1.00,0.3800,0.3800,no,ask,False,live,2026-10-21 14:05:17.461,2026-10-03
96,07250e15-a699-afdc-3ad6-b6e206a844ba,KXCPI-26OCT-T0.2,KXCPI-26OCT,KXCPI,2026-10-03 19:01:26.621,2026-10-03,0.6100,0.3900,10.00,0.3900,3.9000,no,ask,False,live,2026-10-21 14:05:17.461,2026-10-03
97,07250f8c-a2f9-a769-06ea-bebe78fc76bc,KXCPI-26OCT-T0.2,KXCPI-26OCT,KXCPI,2026-10-03 19:01:26.621,2026-10-03,0.6300,0.3700,1.00,0.3700,0.3700,no,ask,False,live,2026-10-21 14:05:17.461,2026-10-03
98,0724ff91-1769-b326-ef72-40271f739f7a,KXCPI-26OCT-T0.3,KXCPI-26OCT,KXCPI,2026-10-03 05:35:57.341,2026-10-03,0.4900,0.5100,1.00,0.5100,0.5100,no,ask,False,live,2026-10-21 14:05:17.461,2026-10-03
99,0724fce1-ce69-aee6-764f-e0d14ad98992,KXCPI-26OCT-T0.3,KXCPI-26OCT,KXCPI,2026-10-03 07:16:37.127,2026-10-03,0.4900,0.5100,1.00,0.5100,0.5100,no,ask,False,live,2026-10-21 14:05:17.461,2026-10-03

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [12]:
df = Unifier.get_dataframe(name='kalshi_macro_trades_tick',key='KXCPI-26NOV-T-0.1', asof_date='2026-10-23', limit=10)
display(df)

,trade_id,ticker,event_ticker,series_ticker,timestamp,date,yes_price,no_price,count,taker_price,notional_usd,taker_outcome_side,taker_book_side,is_block_trade,source_tier,asof_datetime,asof_date
0,2f0b6dcf-20fa-5085-7a4a-c3aa9a55db63,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-05-06 03:16:19.853,2026-05-06,0.8900,0.1100,1.00,0.8900,0.8900,yes,bid,False,historical,2026-10-21 13:09:06.974,2026-05-06
1,5d8b7f23-9afc-6520-0ebe-84217c87015f,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-05-06 23:27:17.234,2026-05-06,0.9500,0.0500,1.00,0.9500,0.9500,yes,bid,False,historical,2026-10-21 13:09:06.974,2026-05-06
2,1d73269e-e20e-6ee7-94ac-1c9ea8eab405,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-05-06 23:27:52.295,2026-05-06,0.8500,0.1500,8.00,0.1500,1.2000,no,ask,False,historical,2026-10-21 13:09:06.974,2026-05-06
3,ac4651ac-b727-616d-8c70-872f4e28182f,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-05-06 23:27:52.295,2026-05-06,0.8900,0.1100,4.00,0.1100,0.4400,no,ask,False,historical,2026-10-21 13:09:06.974,2026-05-06
4,3c541161-f930-7a29-39fc-06e09c2f2354,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-06-30 00:31:30.258,2026-06-30,0.8200,0.1800,2.00,0.1800,0.3600,no,ask,False,historical,2026-10-21 13:49:25.638,2026-06-30
5,72f98da8-715a-7343-1d97-9330e9c5e10b,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-06-30 00:31:30.258,2026-06-30,0.8200,0.1800,10.00,0.1800,1.8000,no,ask,False,historical,2026-10-21 13:49:25.638,2026-06-30
6,f361e883-acb1-7c71-0b0f-94fdf3c2d24a,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-06-30 00:31:30.258,2026-06-30,0.8100,0.1900,15.00,0.1900,2.8500,no,ask,False,historical,2026-10-21 13:49:25.638,2026-06-30
7,dcb46642-30cb-70c3-14a4-10ee2d5c9a25,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-06-30 16:12:51.103,2026-06-30,0.8100,0.1900,1.00,0.1900,0.1900,no,ask,False,historical,2026-10-21 13:49:25.638,2026-06-30
8,7be3779c-27e7-62ef-0348-2082e995d6d5,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-06-30 17:11:49.501,2026-06-30,0.8100,0.1900,3.00,0.1900,0.5700,no,ask,False,historical,2026-10-21 13:49:25.638,2026-06-30
9,072409d6-7d59-a62c-55e1-7127fabf9ffb,KXCPI-26NOV-T-0.1,KXCPI-26NOV,KXCPI,2026-10-20 04:54:36.464,2026-10-20,0.9100,0.0900,20.00,0.9100,18.2000,yes,bid,False,live,2026-10-22 02:33:01.497,2026-10-20

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [13]:
df = Unifier.get_dataframe(name='kalshi_macro_trades_tick',key='KXFED-26OCT-T4.00', back_to='2026-10-01', up_to='2026-10-23', limit=10)
display(df)

,trade_id,ticker,event_ticker,series_ticker,timestamp,date,yes_price,no_price,count,taker_price,notional_usd,taker_outcome_side,taker_book_side,is_block_trade,source_tier,asof_datetime,asof_date
0,0725bfd8-60d9-adb6-a5ca-477be5d78cdb,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-11 02:24:22.512,2026-10-11,0.1600,0.8400,2.78,0.8400,2.3352,no,ask,False,live,2026-10-21 14:07:35.771,2026-10-11
1,0725837a-23f9-96e0-bf21-8131b6259c4a,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-11 04:17:13.812,2026-10-11,0.1700,0.8300,5.00,0.1700,0.8500,yes,bid,False,live,2026-10-21 14:07:35.771,2026-10-11
2,07258184-19b9-987c-f070-f8927dd7fd22,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-11 06:06:59.688,2026-10-11,0.1700,0.8300,5.00,0.1700,0.8500,yes,bid,False,live,2026-10-21 14:07:35.771,2026-10-11
3,072589a0-6b59-95a8-8f3e-d0993b19f276,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-11 15:36:00.205,2026-10-11,0.1700,0.8300,2.00,0.1700,0.3400,yes,bid,False,live,2026-10-21 14:07:35.771,2026-10-11
4,0725888f-6819-bf34-eb2a-79cd05ffe73e,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-11 16:34:10.923,2026-10-11,0.1700,0.8300,50.00,0.1700,8.5000,yes,bid,False,live,2026-10-21 14:07:35.771,2026-10-11
5,07259665-44b9-837c-bf38-9de09dca2ff2,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-11 19:21:47.311,2026-10-11,0.1700,0.8300,47.00,0.1700,7.9900,yes,bid,False,live,2026-10-21 14:07:35.771,2026-10-11
6,07259304-2f79-af00-e1dd-328dee2e163e,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-11 23:00:37.574,2026-10-11,0.1700,0.8300,27.79,0.1700,4.7243,yes,bid,False,live,2026-10-21 14:07:35.771,2026-10-11
7,072479eb-11e9-aebc-470b-0d15661e67df,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-18 00:57:27.671,2026-10-18,0.1100,0.8900,10.15,0.8900,9.0335,no,ask,False,live,2026-10-21 14:08:01.715,2026-10-18
8,07247e32-f669-a65b-7bdf-daacb206e3fe,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-18 00:57:27.671,2026-10-18,0.1100,0.8900,20.00,0.8900,17.8000,no,ask,False,live,2026-10-21 14:08:01.715,2026-10-18
9,07247e9b-19c1-9c4e-c94c-cbd4f28eee46,KXFED-26OCT-T4.00,KXFED-26OCT,KXFED,2026-10-18 01:48:34.447,2026-10-18,0.1300,0.8700,5.00,0.1300,0.6500,yes,bid,False,live,2026-10-21 14:08:01.715,2026-10-18

## Download data file for a specific date using asof_date

In [14]:
Unifier.replicate(name="kalshi_macro_trades_tick", target_location="./data", asof_date='2026-10-15')

Downloading using native python implementation for kalshi_macro_trades_tick...
Found 1 files to download.
Native replication completed for kalshi_macro_trades_tick. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_trades_tick", target_location="./data")