In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_daily_prices", asof_date='2026-10-21', limit=10)
display(df)

,dataset,series_ticker,event_ticker,ticker,contract_preamble,strike,close_time,last_price,last_trade_time,vwap_price,volume,trade_count,yes_bid_close,yes_ask_close,candle_volume,open_interest,asof_datetime,asof_date
0,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T-0.1,CPI-23OCT,-0.1,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,0.00,2026-10-21 09:23:40.896,2023-10-03
1,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T-0.2,CPI-23OCT,-0.2,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,0.00,2026-10-21 09:23:40.896,2023-10-03
2,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T-0.3,CPI-23OCT,-0.3,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,0.00,2026-10-21 09:23:40.896,2023-10-03
3,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.0,CPI-23OCT,0.0,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,997.00,1039.00,2026-10-21 09:23:40.896,2023-10-03
4,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.1,CPI-23OCT,0.1,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,466.00,2026-10-21 09:23:40.896,2023-10-03
5,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.2,CPI-23OCT,0.2,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,0.00,2026-10-21 09:23:40.896,2023-10-03
6,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.4,CPI-23OCT,0.4,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,6.00,2026-10-21 09:23:40.896,2023-10-03
7,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.5,CPI-23OCT,0.5,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,0.00,2026-10-21 09:23:40.896,2023-10-03
8,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.6,CPI-23OCT,0.6,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,0.00,2026-10-21 09:23:40.896,2023-10-03
9,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.7,CPI-23OCT,0.7,2023-11-14 13:25:00.000,None,None,None,None,0,None,None,0.00,0.00,2026-10-21 09:23:40.896,2023-10-03

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_prices', back_to='2026-10-01', up_to='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,event_ticker,ticker,contract_preamble,strike,close_time,last_price,last_trade_time,vwap_price,volume,trade_count,yes_bid_close,yes_ask_close,candle_volume,open_interest,asof_datetime,asof_date
0,headline_cpi_end_of_year,KXACPI,ACPI-2023,ACPI-23-B2.5,ACPI-23,2.5,2024-01-11 15:00:23.184,0.1100,2023-10-15 15:07:19.096,0.121662,2539.00,4,None,None,NaN,NaN,2026-10-21 09:24:30.396,2023-10-15
1,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T-0.1,CPI-23OCT,-0.1,2023-11-14 13:25:00.000,NaN,NaN,NaN,NaN,0,None,None,0.00,300.00,2026-10-21 09:24:30.396,2023-10-15
2,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T-0.2,CPI-23OCT,-0.2,2023-11-14 13:25:00.000,NaN,NaN,NaN,NaN,0,None,None,0.00,0.00,2026-10-21 09:24:30.396,2023-10-15
3,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.0,CPI-23OCT,0.0,2023-11-14 13:25:00.000,0.8600,2023-10-15 23:51:16.290,0.795805,2713.00,6,None,None,1045.00,7890.00,2026-10-21 09:24:30.396,2023-10-15
4,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.1,CPI-23OCT,0.1,2023-11-14 13:25:00.000,0.5300,2023-10-15 19:07:00.816,0.464716,651.00,10,None,None,201.00,2788.00,2026-10-21 09:24:30.396,2023-10-15
5,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.2,CPI-23OCT,0.2,2023-11-14 13:25:00.000,0.0600,2023-10-15 23:45:28.988,0.080354,226.00,5,None,None,0.00,1555.00,2026-10-21 09:24:30.396,2023-10-15
6,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.3,CPI-23OCT,0.3,2023-11-14 13:25:00.000,0.0900,2023-10-15 19:07:54.539,0.097246,69.00,2,None,None,0.00,997.00,2026-10-21 09:24:30.396,2023-10-15
7,headline_cpi_releases_mom,KXCPI,CPI-23OCT,CPI-23OCT-T0.5,CPI-23OCT,0.5,2023-11-14 13:25:00.000,NaN,NaN,NaN,NaN,0,None,None,100.00,100.00,2026-10-21 09:24:30.396,2023-10-15
8,core_cpi_releases,KXCPICOREYOY,CPICOREYOY-23OCT,CPICOREYOY-23OCT-T3.6,CPICOREYOY-23OCT,3.6,2023-11-14 13:25:00.000,NaN,NaN,NaN,NaN,0,None,None,0.00,60.00,2026-10-21 09:24:30.396,2023-10-15
9,core_cpi_releases,KXCPICOREYOY,CPICOREYOY-23OCT,CPICOREYOY-23OCT-T3.7,CPICOREYOY-23OCT,3.7,2023-11-14 13:25:00.000,NaN,NaN,NaN,NaN,0,None,None,100.00,100.00,2026-10-21 09:24:30.396,2023-10-15

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_prices',key='KXFED-26OCT-T4.00', asof_date='2026-10-22', limit=10)
display(df)

,dataset,series_ticker,event_ticker,ticker,contract_preamble,strike,close_time,last_price,last_trade_time,vwap_price,volume,trade_count,yes_bid_close,yes_ask_close,candle_volume,open_interest,asof_datetime,asof_date
0,fed_levels,KXFED,KXFED-26OCT,KXFED-26OCT-T4.00,KXFED-26OCT,4,2026-10-28 17:55:00.000,0.1400,2026-10-20 21:05:54.742,0.137170,266.02,31,0.1500,0.1600,1182.14,71883.13,2026-10-22 02:33:01.497,2026-10-20
1,fed_levels,KXFED,KXFED-26OCT,KXFED-26OCT-T4.00,KXFED-26OCT,4,2026-10-28 17:55:00.000,0.1200,2026-10-21 21:33:40.259,0.130988,479.32,35,0.1200,0.1300,307.45,71906.43,2026-10-22 02:33:01.415,2026-10-21

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='kalshi_macro_daily_prices',key='KXFED-26OCT-T4.00', back_to='2026-10-01', up_to='2026-10-22', limit=10)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="kalshi_macro_daily_prices", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_macro_daily_prices...
Found 1 files to download.
Native replication completed for kalshi_macro_daily_prices. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_daily_prices", target_location="./data")