In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="kalshi_macro_candles_1h", asof_date='2026-10-21', limit=10)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXCPI-26DEC-T-0.1,60,2026-10-20 04:00:00.000,2026-10-20,0.8800,0.8800,0.8600,0.8700,0.9100,0.9200,...,0.9200,0.9100,0.9200,0.9199,0.9100,950.87,3599.87,live,2026-10-22 02:33:07.037,2026-10-20
1,KXCPI-26DEC-T-0.1,60,2026-10-20 11:00:00.000,2026-10-20,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,NaN,NaN,NaN,NaN,0.9200,0.00,3599.87,live,2026-10-22 02:33:07.037,2026-10-20
2,KXCPI-26DEC-T-0.1,60,2026-10-20 13:00:00.000,2026-10-20,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,NaN,NaN,NaN,NaN,0.9200,0.00,3599.87,live,2026-10-22 02:33:07.037,2026-10-20
3,KXCPI-26DEC-T-0.1,60,2026-10-20 16:00:00.000,2026-10-20,0.8700,0.8700,0.8700,0.8700,0.8800,0.8800,...,NaN,NaN,NaN,NaN,0.9200,0.00,3599.87,live,2026-10-22 02:33:07.037,2026-10-20
4,KXCPI-26DEC-T-0.1,60,2026-10-20 18:00:00.000,2026-10-20,0.8700,0.9100,0.8700,0.9000,0.8800,0.9200,...,0.9200,0.8900,0.9200,0.9033,0.9200,1168.38,3601.01,live,2026-10-22 02:33:07.037,2026-10-20
5,KXCPI-26DEC-T-0.1,60,2026-10-20 19:00:00.000,2026-10-20,0.9000,0.9000,0.8900,0.8900,0.9200,0.9200,...,0.9200,0.9200,0.9200,0.9200,0.9200,200.00,3801.01,live,2026-10-22 02:33:07.037,2026-10-20
6,KXCPI-26DEC-T-0.1,60,2026-10-20 20:00:00.000,2026-10-20,0.8900,0.9100,0.8900,0.9100,0.9200,0.9200,...,0.9100,0.9100,0.9100,0.9100,0.9200,24.00,3825.01,live,2026-10-22 02:33:07.037,2026-10-20
7,KXCPI-26DEC-T0.0,60,2026-10-20 01:00:00.000,2026-10-20,0.7900,0.7900,0.7900,0.7900,0.8000,0.8000,...,0.8000,0.8000,0.8000,0.8000,0.9000,1.00,3626.35,live,2026-10-22 02:33:07.037,2026-10-20
8,KXCPI-26DEC-T0.0,60,2026-10-20 02:00:00.000,2026-10-20,0.7900,0.7900,0.7900,0.7900,0.8000,0.8000,...,0.8000,0.8000,0.8000,0.8000,0.8000,1.00,3627.35,live,2026-10-22 02:33:07.037,2026-10-20
9,KXCPI-26DEC-T0.0,60,2026-10-20 03:00:00.000,2026-10-20,0.7900,0.7900,0.7900,0.7900,0.8000,0.8000,...,0.8000,0.8000,0.8000,0.8000,0.8000,4.00,3631.35,live,2026-10-22 02:33:07.037,2026-10-20

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='kalshi_macro_candles_1h', back_to='2026-10-01', up_to='2026-10-21', limit=10)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXCPI-26DEC-T0.5,60,2026-10-12 01:00:00.000,2026-10-12,0.1100,0.1100,0.1100,0.1100,0.1200,0.1200,...,NaN,NaN,NaN,NaN,0.1500,0.00,4984.00,live,2026-10-21 14:07:41.562,2026-10-12
1,KXCPI-26DEC-T0.5,60,2026-10-12 02:00:00.000,2026-10-12,0.1100,0.1400,0.1100,0.1300,0.1200,0.3400,...,0.1200,0.1200,0.1200,0.1200,0.1500,2910.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12
2,KXCPI-26DEC-T0.5,60,2026-10-12 03:00:00.000,2026-10-12,0.1300,0.1400,0.1300,0.1400,0.2700,0.2800,...,NaN,NaN,NaN,NaN,0.1200,0.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12
3,KXCPI-26DEC-T0.5,60,2026-10-12 04:00:00.000,2026-10-12,0.1400,0.1500,0.1300,0.1500,0.2700,0.2700,...,NaN,NaN,NaN,NaN,0.1200,0.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12
4,KXCPI-26DEC-T0.5,60,2026-10-12 05:00:00.000,2026-10-12,0.1500,0.1500,0.1300,0.1500,0.2700,0.2700,...,NaN,NaN,NaN,NaN,0.1200,0.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12
5,KXCPI-26DEC-T0.5,60,2026-10-12 06:00:00.000,2026-10-12,0.1500,0.1500,0.1500,0.1500,0.2700,0.2700,...,NaN,NaN,NaN,NaN,0.1200,0.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12
6,KXCPI-26DEC-T0.5,60,2026-10-12 07:00:00.000,2026-10-12,0.1500,0.1500,0.1400,0.1500,0.2600,0.2600,...,NaN,NaN,NaN,NaN,0.1200,0.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12
7,KXCPI-26DEC-T0.5,60,2026-10-12 08:00:00.000,2026-10-12,0.1500,0.1500,0.1400,0.1500,0.2600,0.2600,...,NaN,NaN,NaN,NaN,0.1200,0.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12
8,KXCPI-26DEC-T0.5,60,2026-10-12 09:00:00.000,2026-10-12,0.1500,0.1500,0.1400,0.1500,0.2600,0.2600,...,NaN,NaN,NaN,NaN,0.1200,0.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12
9,KXCPI-26DEC-T0.5,60,2026-10-12 10:00:00.000,2026-10-12,0.1500,0.1500,0.1400,0.1500,0.2600,0.2600,...,NaN,NaN,NaN,NaN,0.1200,0.00,6194.00,live,2026-10-21 14:07:41.562,2026-10-12

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='kalshi_macro_candles_1h',key='KXFED-26OCT-T4.00', asof_date='2026-10-21', limit=10)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXFED-26OCT-T4.00,60,2026-09-11 02:00:00.000,2026-09-11,0.0700,0.0700,0.0700,0.0700,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
1,KXFED-26OCT-T4.00,60,2026-09-11 03:00:00.000,2026-09-11,0.0700,0.0700,0.0700,0.0700,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
2,KXFED-26OCT-T4.00,60,2026-09-11 04:00:00.000,2026-09-11,0.0700,0.0700,0.0700,0.0700,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
3,KXFED-26OCT-T4.00,60,2026-09-11 05:00:00.000,2026-09-11,0.0700,0.0700,0.0400,0.0500,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
4,KXFED-26OCT-T4.00,60,2026-09-11 06:00:00.000,2026-09-11,0.0500,0.0500,0.0500,0.0500,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
5,KXFED-26OCT-T4.00,60,2026-09-11 07:00:00.000,2026-09-11,0.0500,0.0500,0.0400,0.0400,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
6,KXFED-26OCT-T4.00,60,2026-09-11 08:00:00.000,2026-09-11,0.0400,0.0600,0.0400,0.0600,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
7,KXFED-26OCT-T4.00,60,2026-09-11 09:00:00.000,2026-09-11,0.0600,0.0600,0.0500,0.0600,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
8,KXFED-26OCT-T4.00,60,2026-09-11 10:00:00.000,2026-09-11,0.0600,0.0800,0.0600,0.0800,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11
9,KXFED-26OCT-T4.00,60,2026-09-11 11:00:00.000,2026-09-11,0.0800,0.0900,0.0800,0.0900,0.1000,0.1000,...,None,None,None,None,0.1000,0.00,10040.06,live,2026-10-21 14:04:10.936,2026-09-11

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='kalshi_macro_candles_1h',key='KXFED-26OCT-T4.00', back_to='2026-10-01', up_to='2026-10-21', limit=10)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXFED-26OCT-T4.00,60,2026-10-13 01:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,0.1900,0.1900,0.1900,0.1900,0.2000,21.00,70668.31,live,2026-10-21 14:07:53.046,2026-10-13
1,KXFED-26OCT-T4.00,60,2026-10-13 02:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,0.1900,0.1900,0.1900,0.1900,0.1900,24.90,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
2,KXFED-26OCT-T4.00,60,2026-10-13 03:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,NaN,NaN,NaN,NaN,0.1900,0.00,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
3,KXFED-26OCT-T4.00,60,2026-10-13 04:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,NaN,NaN,NaN,NaN,0.1900,0.00,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
4,KXFED-26OCT-T4.00,60,2026-10-13 05:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,NaN,NaN,NaN,NaN,0.1900,0.00,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
5,KXFED-26OCT-T4.00,60,2026-10-13 06:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,0.1800,0.1800,0.1800,0.1800,0.1900,5.95,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
6,KXFED-26OCT-T4.00,60,2026-10-13 07:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,NaN,NaN,NaN,NaN,0.1800,0.00,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
7,KXFED-26OCT-T4.00,60,2026-10-13 08:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,NaN,NaN,NaN,NaN,0.1800,0.00,70693.21,live,2026-10-21 14:07:53.046,2026-10-13
8,KXFED-26OCT-T4.00,60,2026-10-13 09:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,0.1900,0.1900,0.1900,0.1900,0.1800,21.00,70714.21,live,2026-10-21 14:07:53.046,2026-10-13
9,KXFED-26OCT-T4.00,60,2026-10-13 10:00:00.000,2026-10-13,0.1800,0.1800,0.1800,0.1800,0.1900,0.1900,...,NaN,NaN,NaN,NaN,0.1900,0.00,70714.21,live,2026-10-21 14:07:53.046,2026-10-13

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="kalshi_macro_candles_1h", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_macro_candles_1h...
Found 1 files to download.
Native replication completed for kalshi_macro_candles_1h. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_macro_candles_1h", target_location="./data")