In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## XTech US Equity Options Trades

In [4]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_options_trades",  back_to='2025-11-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_at,okey_ts,okey_tk,okey_yr,okey_mn,okey_dy,...,svolm10,sopxm10,sdivm10,serrm10,pnlm10,pnlm10err,multihedge,timestamp_cst,securityid,asof_date
0,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.733,QQQ,EQT,NMS,QQQ,2026,6,18,...,0.171227,0.351170,0.000000,None,-0.027522,None,None,2026-06-18 14:11:25.733258,551883,2026-06-18
1,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.763,QQQ,EQT,NMS,QQQ,2026,6,22,...,0.191848,4.445160,0.055693,None,-0.015918,None,None,2026-06-18 14:11:25.763287,551883,2026-06-18
2,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.793,QQQ,EQT,NMS,QQQ,2026,6,18,...,0.143107,0.440575,0.000000,None,-0.078369,None,None,2026-06-18 14:11:25.793317,551883,2026-06-18
3,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.811,CELH,EQT,NMS,CELH,2026,7,10,...,0.854872,12.568500,0.043414,None,-0.061454,None,None,2026-06-18 14:11:25.810934,393300,2026-06-18
4,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.811,CELH,EQT,NMS,CELH,2026,6,18,...,5.861110,11.940500,0.000000,None,0.065467,None,None,2026-06-18 14:11:25.810934,393300,2026-06-18
5,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.835,QQQ,EQT,NMS,QQQ,2026,6,22,...,0.164343,0.651061,0.055693,None,-0.019699,None,None,2026-06-18 14:11:25.835358,551883,2026-06-18
6,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.947,QQQ,EQT,NMS,QQQ,2026,6,18,...,0.171227,0.351170,0.000000,None,-0.034479,None,None,2026-06-18 14:11:25.947468,551883,2026-06-18
7,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.947,QQQ,EQT,NMS,QQQ,2026,6,18,...,0.171227,0.351170,0.000000,None,-0.034479,None,None,2026-06-18 14:11:25.947468,551883,2026-06-18
8,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.947,QQQ,EQT,NMS,QQQ,2026,6,22,...,0.201851,3.370570,0.055693,None,-0.021588,None,None,2026-06-18 14:11:25.947468,551883,2026-06-18
9,2026-06-18,2026-06-18 23:30:00.000,2026-06-18 19:11:25.967,QQQ,EQT,NMS,QQQ,2026,6,18,...,0.153552,0.613106,0.000000,None,-0.059543,None,None,2026-06-18 14:11:25.967487,551883,2026-06-18

In [5]:
df = Unifier.get_dataframe(name="xtech_us_eqt_options_trades", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_at,okey_ts,okey_tk,okey_yr,okey_mn,okey_dy,...,svolm10,sopxm10,sdivm10,serrm10,pnlm10,pnlm10err,multihedge,timestamp_cst,securityid,asof_date
0,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:05.524,GOOG,EQT,NMS,GOOG,2024,12,20,...,0.250617,3.244760,-0.002662,None,0.000548,None,None,2024-01-31 12:49:05.524300,4579564,2024-01-31
1,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:05.682,QCOM,EQT,NMS,QCOM,2024,2,16,...,0.382365,2.563190,0.001168,None,-0.026684,None,None,2024-01-31 12:49:05.682235,41729,2024-01-31
2,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:05.682,QCOM,EQT,NMS,QCOM,2024,2,16,...,0.386718,1.072020,0.001168,None,-0.028939,None,None,2024-01-31 12:49:05.682235,41729,2024-01-31
3,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:05.863,JOBY,EQT,NMS,JOBY,2026,1,16,...,0.833002,0.686333,-0.012577,None,0.082895,None,None,2024-01-31 12:49:05.863429,6648092,2024-01-31
4,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:06.663,ETSY,EQT,NMS,ETSY,2024,2,16,...,0.507793,2.344300,0.003582,None,-0.032362,None,None,2024-01-31 12:49:06.663348,4458843,2024-01-31
5,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:06.891,CMG,EQT,NMS,CMG,2024,9,20,...,0.275888,329.265000,-0.000850,None,1.376820,None,None,2024-01-31 12:49:06.891488,328951,2024-01-31
6,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:07.360,RIG,EQT,NMS,RIG,2024,2,9,...,0.552808,0.028853,-0.013707,None,-0.008392,None,None,2024-01-31 12:49:07.359916,631742,2024-01-31
7,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:07.656,PLUG,EQT,NMS,PLUG,2024,2,2,...,2.484030,0.018229,0.223357,None,-0.000785,None,None,2024-01-31 12:49:07.656145,41404,2024-01-31
8,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:07.853,PLUG,EQT,NMS,PLUG,2024,2,2,...,1.512800,0.156321,0.223357,None,-0.000300,None,None,2024-01-31 12:49:07.853335,41404,2024-01-31
9,2024-01-31,2024-01-31 23:30:00.000,2024-01-31 18:49:07.884,PLUG,EQT,NMS,PLUG,2024,2,2,...,1.512800,0.156321,0.223357,None,0.002969,None,None,2024-01-31 12:49:07.884364,41404,2024-01-31

In [6]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_options_trades", key="JOBY", back_to='2025-11-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_at,okey_ts,okey_tk,okey_yr,okey_mn,okey_dy,...,svolm10,sopxm10,sdivm10,serrm10,pnlm10,pnlm10err,multihedge,timestamp_cst,securityid,asof_date
0,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 15:36:36.466,JOBY,EQT,NMS,JOBY,2026,2,20,...,0.772385,1.385890,-0.012965,None,-0.023672,None,None,2026-01-09 09:36:36.466228,6648092,2026-01-09
1,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 15:36:43.530,JOBY,EQT,NMS,JOBY,2026,2,20,...,0.772296,1.787340,-0.013060,None,0.007659,None,None,2026-01-09 09:36:43.530374,6648092,2026-01-09
2,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 15:36:43.695,JOBY,EQT,NMS,JOBY,2026,1,16,...,0.779971,0.185827,0.021943,None,0.008769,None,None,2026-01-09 09:36:43.694658,6648092,2026-01-09
3,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 15:36:46.159,JOBY,EQT,NMS,JOBY,2026,2,20,...,0.779940,1.018920,-0.013060,None,0.011324,None,None,2026-01-09 09:36:46.158900,6648092,2026-01-09
4,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:13.733,JOBY,EQT,NMS,JOBY,2026,7,17,...,0.823930,2.459430,0.008123,None,0.091538,None,None,2026-01-09 11:44:13.732576,6648092,2026-01-09
5,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:14.434,JOBY,EQT,NMS,JOBY,2026,1,9,...,1.343260,5.325000,0.000000,None,-0.261035,None,None,2026-01-09 11:44:14.433511,6648092,2026-01-09
6,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:16.843,JOBY,EQT,NMS,JOBY,2026,2,20,...,0.802298,1.276780,-0.010508,None,0.008894,None,None,2026-01-09 11:44:16.842993,6648092,2026-01-09
7,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:16.963,JOBY,EQT,NMS,JOBY,2026,7,17,...,0.818642,1.475850,0.008123,None,-0.031432,None,None,2026-01-09 11:44:16.963467,6648092,2026-01-09
8,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:20.457,JOBY,EQT,NMS,JOBY,2026,7,17,...,0.823927,2.460140,0.007930,None,0.096831,None,None,2026-01-09 11:44:20.457210,6648092,2026-01-09
9,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:24.367,JOBY,EQT,NMS,JOBY,2026,1,9,...,1.343260,5.325000,0.000000,None,-0.251740,None,None,2026-01-09 11:44:24.367138,6648092,2026-01-09

### Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_eqt_options_trades", target_location="./data", asof_date='2025-03-12')

### Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_options_trades", target_location="./data")

## XTech US Equity Options Flow

In [7]:
df = Unifier.get_dataframe(name="xtech_us_equity_options_flow_1min", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,SRTY,SRTY,RegularMkt,EQT,Put,16,2,...,0,0,0,1,5,2.60,0.000000,0,0.171404,2024-01-23
1,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,TMF,TMF,RegularMkt,EQT,Put,15,3,...,0,0,0,1,1,1.84,0.000000,0,0.070134,2024-01-23
2,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,TSCO,TSCO,RegularMkt,EQT,Call,16,2,...,0,1,0,0,0,0.00,0.240901,0,0.000000,2024-01-23
3,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,UBER,UBER,RegularMkt,EQT,Call,26,1,...,0,0,0,1,1,1.44,0.000000,0,0.023669,2024-01-23
4,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,UBER,UBER,RegularMkt,EQT,Put,26,1,...,0,1,0,0,0,0.00,0.027729,0,0.000000,2024-01-23
5,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,UBER,UBER,RegularMkt,EQT,Call,16,2,...,0,0,0,1,4,1.16,0.000000,0,0.221058,2024-01-23
6,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,UBER,UBER,RegularMkt,EQT,Put,23,2,...,0,0,0,1,1,0.25,0.000000,0,0.022686,2024-01-23
7,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,UBER,UBER,RegularMkt,EQT,Call,15,3,...,0,2,0,0,0,0.00,0.211243,0,0.000000,2024-01-23
8,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,UBER,UBER,RegularMkt,EQT,Call,15,3,...,0,1,0,0,0,0.00,0.520558,0,0.000000,2024-01-23
9,2024-01-23,2024-01-23 23:30:30.000,2024-01-23 18:08:00.000,UBER,UBER,RegularMkt,EQT,Call,15,3,...,0,0,0,1,1,1.17,0.000000,0,0.074731,2024-01-23

In [8]:
df =  Unifier.get_dataframe(name="xtech_us_equity_options_flow_1min", key="UBER", back_to='2025-11-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Call,8,5,...,0,0,0,1,3,0.310000,0.000000,0,0.044001,2026-05-05
1,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Call,8,5,...,0,0,0,2,6,2.198333,0.000000,0,0.192955,2026-05-05
2,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Call,18,9,...,0,0,0,1,2,1.820000,0.000000,0,0.255188,2026-05-05
3,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Call,8,5,...,0,0,0,3,11,1.139091,0.000000,0,0.306717,2026-05-05
4,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Put,8,5,...,0,1,0,14,96,0.950000,0.025676,0,2.464896,2026-05-05
5,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Call,8,5,...,0,1,0,0,0,0.000000,0.032205,0,0.000000,2026-05-05
6,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Put,15,5,...,0,0,0,1,1,2.440000,0.000000,0,0.051577,2026-05-05
7,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Call,8,5,...,0,0,0,3,5,0.420000,0.000000,0,0.087308,2026-05-05
8,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Call,18,6,...,0,2,0,0,0,0.000000,0.221725,0,0.000000,2026-05-05
9,2026-05-05,2026-05-05 23:30:30.000,2026-05-05 16:50:00.000,UBER,UBER,RegularMkt,EQT,Put,8,5,...,0,0,0,1,8,2.050000,0.000000,0,0.254262,2026-05-05

In [9]:
df =  Unifier.get_dataframe(name="xtech_us_equity_options_flow_1min", back_to='2025-11-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PALL,PALL,RegularMkt,EQT,Put,18,6,...,0,0,0,1,1,4.940,0.000000,0,0.189907,2026-04-22
1,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Call,15,5,...,0,0,0,1,1,7.310,0.000000,0,0.185897,2026-04-22
2,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Call,18,6,...,0,1,0,0,0,0.000,0.277094,0,0.000000,2026-04-22
3,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Put,24,4,...,0,1,0,0,0,0.000,0.006646,0,0.000000,2026-04-22
4,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Call,18,9,...,0,1,0,0,0,0.000,0.376546,0,0.000000,2026-04-22
5,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Call,24,4,...,0,1,0,4,8,2.040,0.067718,0,0.541746,2026-04-22
6,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Call,24,4,...,0,1,0,0,0,0.000,0.132921,0,0.000000,2026-04-22
7,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Put,24,4,...,0,1,0,0,0,0.000,0.240839,0,0.000000,2026-04-22
8,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Call,1,5,...,0,0,0,2,5,2.604,0.000000,0,0.548995,2026-04-22
9,2026-04-22,2026-04-22 23:30:30.000,2026-04-22 14:54:00.000,PANW,PANW,RegularMkt,EQT,Put,22,5,...,0,0,0,1,6,10.270,0.000000,0,1.264962,2026-04-22

### Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_equity_options_flow_1min", target_location="./data", asof_date='2025-03-12')

Starting native python replication for xtech_us_eqt_short_interest_factor_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_short_interest_factor_daily_v1_2. Downloaded 1 files.

### Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_options_flow_1min", target_location="./data")