In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_etf_flow_daily_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2022-03-17 20:00:03.000,2022-03-17 16:26:00.000,1,ESGE,8648,7.968367e+07,4.066791e+07,3.299264e+07,4981,3664,...,4.505745e+07,2.860310e+07,6097,2495,3474960.52,2548159.84,470,343,2022-03-17,2022-03-17
1,2022-03-17 20:00:03.000,2022-03-17 17:17:00.000,1,CLOU,8279,1.624708e+07,1.066095e+07,5.111668e+06,5479,2777,...,1.495699e+07,8.156369e+05,7719,353,215670.54,258783.46,110,102,2022-03-17,2022-03-17
2,2022-03-17 20:00:03.000,2022-03-17 19:58:00.000,1,DBC,16449,1.538606e+08,9.226290e+07,5.273399e+07,10037,6411,...,1.440943e+08,9.025727e+05,16223,226,5185919.17,3677830.19,613,474,2022-03-17,2022-03-17
3,2022-03-17 20:00:03.000,2022-03-17 19:59:00.000,1,QID,39947,3.480565e+08,1.678054e+08,1.671861e+08,19957,19855,...,1.355541e+08,1.994374e+08,16212,23721,8181540.78,4883425.19,942,601,2022-03-17,2022-03-17
4,2022-03-17 20:00:03.000,2022-03-17 20:00:00.000,1,GUSH,22964,2.757863e+08,1.381781e+08,1.114808e+08,12630,10332,...,1.623533e+08,8.730551e+07,14331,8633,13615763.26,12511677.47,1088,999,2022-03-17,2022-03-17
5,2022-03-17 20:00:03.000,2022-03-17 20:00:00.000,1,KWEB,242753,1.322211e+09,7.286098e+08,5.508989e+08,135535,106380,...,7.263981e+08,5.531106e+08,128883,113861,20299494.51,22402835.75,3900,4103,2022-03-17,2022-03-17
6,2022-03-17 20:00:03.000,2022-03-17 20:01:00.000,1,ARKG,21800,1.028739e+08,5.795064e+07,4.058100e+07,12450,9349,...,9.074210e+07,7.789541e+06,19826,1965,2577609.27,1764655.35,567,395,2022-03-17,2022-03-17
7,2022-03-17 20:00:03.000,2022-03-17 20:01:00.000,1,EFAV,6901,7.882731e+07,4.022219e+07,3.395998e+07,3939,2948,...,7.221469e+07,1.967484e+06,6676,223,2093230.18,2551906.04,183,198,2022-03-17,2022-03-17
8,2022-03-17 20:00:03.000,2022-03-17 20:01:00.000,1,ERX,48043,3.961148e+08,2.144982e+08,1.678917e+08,27078,20920,...,3.101022e+08,7.228759e+07,39200,8842,8637369.15,5087589.98,1020,607,2022-03-17,2022-03-17
9,2022-03-17 20:00:03.000,2022-03-17 20:01:00.000,1,FEZ,31394,2.293518e+08,1.385501e+08,8.975051e+07,19108,12204,...,1.949549e+08,3.334568e+07,27072,4322,630563.80,420646.95,94,66,2022-03-17,2022-03-17

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-30 20:00:03.000,2024-01-30 16:16:00.000,1,USIG,6901,4.986394e+07,2.182428e+07,2.300084e+07,3281,3619,...,1.572175e+07,2.910336e+07,2364,4537,2540249.20,2498575.26,308,326,2024-01-30,2024-01-30
1,2024-01-30 20:00:03.000,2024-01-30 17:13:00.000,1,CLOU,1772,5.429430e+06,2.269719e+06,2.751853e+06,957,814,...,3.465549e+06,1.556023e+06,1212,559,267999.14,139858.50,87,57,2024-01-30,2024-01-30
2,2024-01-30 20:00:03.000,2024-01-30 17:55:00.000,1,RDVY,3680,5.822730e+07,2.541421e+07,2.126659e+07,1977,1684,...,4.256245e+07,4.118351e+06,3088,436,5838845.91,5707653.61,538,394,2024-01-30,2024-01-30
3,2024-01-30 20:00:03.000,2024-01-30 19:57:00.000,1,KRE,60768,3.772894e+08,1.414698e+08,2.294458e+08,23400,37317,...,5.353666e+07,3.173790e+08,9056,51710,3218193.67,3155539.28,549,507,2024-01-30,2024-01-30
4,2024-01-30 20:00:03.000,2024-01-30 20:00:00.000,1,GGLL,2702,7.501809e+06,2.380038e+06,3.880960e+06,1206,1484,...,2.499125e+06,3.761873e+06,1003,1691,702311.41,538499.93,215,150,2024-01-30,2024-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-17 20:00:03.000,2024-01-17 20:00:00.000,1,SPXS,28614,3.403682e+08,1.390114e+08,1.446852e+08,13254,11881,...,1.008981e+08,1.827985e+08,1186,8529,35685945.72,20985734.96,3122,1787,2024-01-17,2024-01-17
96,2024-01-17 20:00:03.000,2024-01-17 20:00:00.000,1,TMF,116069,8.116788e+08,3.329914e+08,4.473099e+08,50288,65204,...,3.319194e+08,4.483819e+08,47227,68288,20782878.30,10594642.94,3011,1481,2024-01-17,2024-01-17
97,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,ACWV,1087,1.259282e+07,8.783819e+06,3.071103e+06,686,400,...,1.173648e+07,1.184453e+05,1073,13,413787.64,324115.18,37,53,2024-01-17,2024-01-17
98,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,DGRO,11913,7.834654e+07,3.479788e+07,3.140220e+07,6484,5428,...,3.236722e+07,3.383286e+07,5062,6851,7849946.17,4296521.50,1448,783,2024-01-17,2024-01-17
99,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,IEO,1781,1.133325e+07,4.434709e+06,5.996452e+06,798,982,...,6.086218e+06,4.344943e+06,1016,738,508668.21,393420.18,81,79,2024-01-17,2024-01-17

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_trial',key='FTCS', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2020-12-31 20:00:03.000,2020-12-31 16:01:00.000,1,FTCS,1762,2.194621e+07,8664144.82,6441725.85,1045,716,...,8577282.76,6528587.91,982,780,4153413.78,2686927.80,330,178,2020-12-31,2020-12-31
1,2022-06-27 20:00:03.000,2022-06-27 16:16:00.000,1,FTCS,1526,1.900853e+07,8274902.69,4987645.20,876,647,...,12894161.53,368386.58,1427,36,3527539.46,2218446.80,260,230,2022-06-27,2022-06-27
2,2020-07-14 20:00:03.000,2020-07-14 16:01:00.000,1,FTCS,2395,2.738691e+07,11258817.10,10620094.06,1191,1153,...,16917753.00,4961158.17,1510,269,3008539.23,2499459.91,259,220,2020-07-14,2020-07-14
3,2020-12-29 20:00:03.000,2020-12-29 16:01:00.000,1,FTCS,1760,2.429320e+07,7754395.69,8032809.97,887,838,...,4479769.58,11307436.21,397,989,5044204.06,3461790.49,370,258,2020-12-29,2020-12-29
4,2021-11-12 20:00:03.000,2021-11-12 16:01:00.000,1,FTCS,1423,1.343950e+07,4739489.62,3790476.02,847,574,...,7622884.08,907081.75,1237,186,2639694.45,2269843.41,296,244,2021-11-12,2021-11-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-04-05 20:00:03.000,2023-04-05 16:16:00.000,1,FTCS,2841,5.318158e+07,27228138.24,13538009.38,1581,1259,...,33039084.66,7727062.90,1918,909,5943352.10,6472080.85,407,270,2023-04-05,2023-04-05
96,2023-08-21 20:00:03.000,2023-08-21 16:16:00.000,1,FTCS,2057,2.356115e+07,8722512.17,8818489.05,1065,918,...,14404811.27,3136190.17,1365,63,2838699.13,3181446.51,294,307,2023-08-21,2023-08-21
97,2021-12-06 20:00:03.000,2021-12-06 16:01:00.000,1,FTCS,2197,1.944968e+07,8875118.82,5416789.43,1263,933,...,13915395.87,376512.55,2140,56,2745092.15,2412675.10,417,333,2021-12-06,2021-12-06
98,2020-05-06 20:00:03.000,2020-05-06 16:01:00.000,1,FTCS,1847,2.648623e+07,8223040.98,8915195.70,988,858,...,9549504.86,7588731.93,1090,757,5825769.33,3522223.86,422,231,2020-05-06,2020-05-06
99,2021-11-24 20:00:03.000,2021-11-24 16:01:00.000,1,FTCS,1840,1.484869e+07,5169663.33,5004527.62,966,873,...,5669763.00,4504428.09,1146,694,2525826.97,2148668.40,292,282,2021-11-24,2021-11-24

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_trial',key='FTCS', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,FTCS,2545,2.607478e+07,8272864.70,11966340.98,1218,1318,...,6532281.90,13706923.89,955,1530,3602759.04,2232813.47,366,228,2024-01-17,2024-01-17
1,2024-01-16 20:00:03.000,2024-01-16 17:41:00.000,1,FTCS,2729,2.533248e+07,10278060.74,9645419.41,1434,1284,...,14015434.07,5908046.02,1950,663,3072773.02,2336224.01,397,261,2024-01-16,2024-01-16
2,2024-01-02 20:00:03.000,2024-01-02 16:16:00.000,1,FTCS,2746,2.941589e+07,12201558.71,9932868.31,1466,1279,...,19169974.23,2964452.84,2252,493,3714505.32,3566961.98,393,386,2024-01-02,2024-01-02
3,2024-01-18 20:00:03.000,2024-01-18 16:16:00.000,1,FTCS,2500,2.714933e+07,10100906.80,10753794.62,1233,1224,...,12707257.93,8147443.47,1082,995,3618295.11,2676335.69,349,225,2024-01-18,2024-01-18
4,2024-01-29 20:00:03.000,2024-01-29 16:16:00.000,1,FTCS,2586,2.274960e+07,7341564.70,9911815.31,1296,1283,...,9747876.53,7505503.51,1383,1190,3530891.27,1965333.04,363,254,2024-01-29,2024-01-29
5,2024-01-26 20:00:03.000,2024-01-26 16:16:00.000,1,FTCS,2434,2.382428e+07,8038692.71,10905475.18,1156,1277,...,10183064.32,8761103.53,973,1461,2975218.26,1904892.28,315,235,2024-01-26,2024-01-26

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="lseg_us_etf_flow_daily_v1_2_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for lseg_us_etf_flow_daily_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_etf_flow_daily_v1_2_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_etf_flow_daily_v1_2_trial", target_location="./data")