In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="lseg_us_etf_flow_1min_v1_2_1", asof_date='2026-08-06', limit=10)
display(df)

,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2023-06-22 09:31:03.000,2023-06-22 09:31:00.000,0,ACTV,1,2007.2000,1003.60,1003.60,0,0,...,1003.60,1003.60,0,0,0.0,0.0,0,0,2023-06-22,2023-06-22
1,2023-06-22 09:37:03.000,2023-06-22 09:37:00.000,0,ACTV,1,3072.0000,0.00,3072.00,0,1,...,0.00,3072.00,0,1,0.0,0.0,0,0,2023-06-22,2023-06-22
2,2023-06-22 10:02:03.000,2023-06-22 10:02:00.000,0,ACTV,1,61.3050,0.00,0.01,0,1,...,0.00,0.01,0,1,0.0,61.3,0,1,2023-06-22,2023-06-22
3,2023-06-22 10:24:03.000,2023-06-22 10:24:00.000,0,ACTV,5,73993.9400,73993.94,0.00,5,0,...,73993.94,0.00,5,0,0.0,0.0,0,0,2023-06-22,2023-06-22
4,2023-06-22 10:31:03.000,2023-06-22 10:31:00.000,0,ACTV,1,3075.0000,0.00,3075.00,0,1,...,0.00,3075.00,0,1,0.0,0.0,0,0,2023-06-22,2023-06-22
5,2023-06-22 10:41:03.000,2023-06-22 10:41:00.000,0,ACTV,1,5967.4012,0.00,0.00,0,1,...,0.00,0.00,0,1,5967.4,0.0,1,0,2023-06-22,2023-06-22
6,2023-06-22 10:51:03.000,2023-06-22 10:51:00.000,0,ACTV,1,307.0000,0.00,307.00,0,1,...,0.00,307.00,0,1,0.0,0.0,0,0,2023-06-22,2023-06-22
7,2023-06-22 11:36:03.000,2023-06-22 11:36:00.000,0,ACTV,1,66041.7200,66041.72,0.00,1,0,...,66041.72,0.00,1,0,0.0,0.0,0,0,2023-06-22,2023-06-22
8,2023-06-22 12:04:03.000,2023-06-22 12:04:00.000,0,ACTV,1,2212.5600,0.00,2212.56,0,1,...,0.00,2212.56,0,1,0.0,0.0,0,0,2023-06-22,2023-06-22
9,2023-06-22 12:09:03.000,2023-06-22 12:09:00.000,0,ACTV,2,3136.5000,1568.25,1568.25,1,1,...,1568.25,1568.25,1,1,0.0,0.0,0,0,2023-06-22,2023-06-22

## Retrieve data for a specific date range using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_1min_v1_2_1', back_to='2026-08-06', up_to='2026-08-07', limit=100)
display(df)

,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2026-08-06 04:12:03.000,2026-08-06 04:12:00.000,1,AAPE,3,14800.00,12333.33,2466.67,2,0,...,14800.00,0.00,3,0,0.0,0.0,0,0,2026-08-06,2026-08-06
1,2026-08-06 04:51:03.000,2026-08-06 04:51:00.000,1,AAPE,1,14.80,0.00,14.80,0,1,...,7.40,7.40,0,0,0.0,0.0,0,0,2026-08-06,2026-08-06
2,2026-08-06 05:12:03.000,2026-08-06 05:12:00.000,1,AAPE,1,14.79,0.00,14.79,0,1,...,0.00,14.79,0,1,0.0,0.0,0,0,2026-08-06,2026-08-06
3,2026-08-06 05:15:03.000,2026-08-06 05:15:00.000,1,AAPE,1,340.86,340.86,0.00,1,0,...,340.86,0.00,1,0,0.0,0.0,0,0,2026-08-06,2026-08-06
4,2026-08-06 07:15:03.000,2026-08-06 07:15:00.000,1,AAPE,1,1336.50,1336.50,0.00,1,0,...,1336.50,0.00,1,0,0.0,0.0,0,0,2026-08-06,2026-08-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026-08-06 13:29:03.000,2026-08-06 13:29:00.000,0,AAPE,1,218.10,218.10,0.00,1,0,...,218.10,0.00,1,0,0.0,0.0,0,0,2026-08-06,2026-08-06
96,2026-08-06 13:35:03.000,2026-08-06 13:35:00.000,0,AAPE,1,218.40,218.40,0.00,1,0,...,218.40,0.00,1,0,0.0,0.0,0,0,2026-08-06,2026-08-06
97,2026-08-06 13:45:03.000,2026-08-06 13:45:00.000,0,AAPE,1,1253.02,1253.02,0.00,1,0,...,1253.02,0.00,1,0,0.0,0.0,0,0,2026-08-06,2026-08-06
98,2026-08-06 13:46:03.000,2026-08-06 13:46:00.000,0,AAPE,1,218.55,218.55,0.00,1,0,...,218.55,0.00,1,0,0.0,0.0,0,0,2026-08-06,2026-08-06
99,2026-08-06 13:55:03.000,2026-08-06 13:55:00.000,0,AAPE,1,219.15,219.15,0.00,1,0,...,219.15,0.00,1,0,0.0,0.0,0,0,2026-08-06,2026-08-06

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_1min_v1_2_1',key='ARKK', asof_date='2024-01-01', limit=100)
display(df)

,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2023-02-23 04:01:03.000,2023-02-23 04:01:00.000,1,ARKK,2,4077.74,2038.87,2038.87,0,0,...,1019.43,3058.30,0,1,0,0,0,0,2023-02-23,2023-02-23
1,2023-02-23 04:02:03.000,2023-02-23 04:02:00.000,1,ARKK,7,9296.98,1328.14,7968.84,1,6,...,1328.14,7968.84,1,6,0,0,0,0,2023-02-23,2023-02-23
2,2023-02-23 04:04:03.000,2023-02-23 04:04:00.000,1,ARKK,5,24253.53,24253.53,0.00,5,0,...,19402.82,4850.71,4,1,0,0,0,0,2023-02-23,2023-02-23
3,2023-02-23 04:06:03.000,2023-02-23 04:06:00.000,1,ARKK,2,203.96,101.98,101.98,1,1,...,101.98,101.98,1,1,0,0,0,0,2023-02-23,2023-02-23
4,2023-02-23 04:07:03.000,2023-02-23 04:07:00.000,1,ARKK,12,53380.33,53380.33,0.00,12,0,...,48931.97,4448.36,11,1,0,0,0,0,2023-02-23,2023-02-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-02-23 07:32:03.000,2023-02-23 07:32:00.000,1,ARKK,2,4118.78,4118.78,0.00,2,0,...,4118.78,0.00,2,0,0,0,0,0,2023-02-23,2023-02-23
96,2023-02-23 07:33:03.000,2023-02-23 07:33:00.000,1,ARKK,4,10315.34,7736.50,2578.84,3,1,...,7736.50,2578.84,3,1,0,0,0,0,2023-02-23,2023-02-23
97,2023-02-23 07:34:03.000,2023-02-23 07:34:00.000,1,ARKK,1,4074.00,4074.00,0.00,1,0,...,4074.00,0.00,1,0,0,0,0,0,2023-02-23,2023-02-23
98,2023-02-23 07:35:03.000,2023-02-23 07:35:00.000,1,ARKK,29,268574.59,203746.24,64828.35,22,7,...,203746.24,64828.35,22,7,0,0,0,0,2023-02-23,2023-02-23
99,2023-02-23 07:36:03.000,2023-02-23 07:36:00.000,1,ARKK,14,46382.65,3313.05,43069.60,1,13,...,3313.05,43069.60,1,13,0,0,0,0,2023-02-23,2023-02-23

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [12]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_1min_v1_2_1', key='EMXC', back_to='2023-01-01', up_to='2024-06-01', limit=100)
display(df)

,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2023-07-26 09:19:03.000,2023-07-26 09:19:00.000,1,EMXC,1,2162.8000,1081.40,1081.40,0,0,...,2162.80,0.00,1,0,0.00,0.00,0,0,2023-07-26,2023-07-26
1,2023-07-26 09:20:03.000,2023-07-26 09:20:00.000,1,EMXC,1,269.1500,269.15,0.00,1,0,...,0.00,269.15,0,1,0.00,0.00,0,0,2023-07-26,2023-07-26
2,2023-07-26 09:31:03.000,2023-07-26 09:31:00.000,0,EMXC,13,590131.6549,363157.94,226973.71,8,5,...,317763.20,272368.46,7,6,0.00,0.00,0,0,2023-07-26,2023-07-26
3,2023-07-26 09:32:03.000,2023-07-26 09:32:00.000,0,EMXC,56,592686.7126,420064.69,169339.06,40,16,...,388313.62,201090.13,37,19,3282.96,0.00,2,0,2023-07-26,2023-07-26
4,2023-07-26 09:33:03.000,2023-07-26 09:33:00.000,0,EMXC,22,174188.1100,172842.41,0.00,22,0,...,172842.41,0.00,22,0,1345.70,0.00,1,0,2023-07-26,2023-07-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-07-26 11:08:03.000,2023-07-26 11:08:00.000,0,EMXC,2,11218.3944,5609.20,5609.20,1,1,...,5609.20,5609.20,1,1,0.00,0.00,0,0,2023-07-26,2023-07-26
96,2023-07-26 11:09:03.000,2023-07-26 11:09:00.000,0,EMXC,2,16229.9354,8114.97,8114.97,1,1,...,8114.97,8114.97,1,1,0.00,0.00,0,0,2023-07-26,2023-07-26
97,2023-07-26 11:10:03.000,2023-07-26 11:10:00.000,0,EMXC,2,5772.5800,2886.29,2886.29,1,1,...,5772.58,0.00,2,0,0.00,0.00,0,0,2023-07-26,2023-07-26
98,2023-07-26 11:11:03.000,2023-07-26 11:11:00.000,0,EMXC,1,5395.0000,5395.00,0.00,1,0,...,5395.00,0.00,1,0,0.00,0.00,0,0,2023-07-26,2023-07-26
99,2023-07-26 11:12:03.000,2023-07-26 11:12:00.000,0,EMXC,9,39921.7798,22178.77,13480.66,5,4,...,22178.77,13480.66,5,4,0.00,4262.35,0,2,2023-07-26,2023-07-26

## Download data file for a specific date using asof_date

In [13]:
Unifier.replicate(name="lseg_us_etf_flow_1min_v1_2_1", target_location="./data", asof_date='2025-01-13')

Downloading using native python implementation for lseg_us_etf_flow_1min_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_etf_flow_1min_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_etf_flow_1min_v1_2_1", target_location="./data")