In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [4]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name="lseg_us_etf_flow_daily_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2020-07-17 20:00:03.000,2020-07-17 20:01:00.000,1,AAAU,494,3.550357e+06,1723754.52,975392.96,280,210,...,1700717.61,998429.87,265,228,671548.59,179661.16,56,10,2020-07-17,2020-07-17
1,2020-07-17 20:00:03.000,2020-07-17 20:01:00.000,1,AADR,28,2.001244e+05,85822.62,37676.46,18,9,...,56387.67,67111.42,15,12,54359.76,22265.51,4,2,2020-07-17,2020-07-17
2,2020-07-17 20:00:03.000,2020-07-17 16:01:00.000,1,AAXJ,6760,6.916708e+07,34192773.31,34337266.29,3236,3523,...,35520235.71,33009803.90,3279,3481,417044.68,219998.14,34,21,2020-07-17,2020-07-17
3,2020-07-17 20:00:03.000,2020-07-17 20:01:00.000,1,ABEQ,32,7.073435e+04,17659.73,21614.18,18,13,...,3556.17,35717.74,9,22,0.00,31460.43,0,3,2020-07-17,2020-07-17
4,2020-07-17 20:00:03.000,2020-07-17 20:01:00.000,1,ACES,520,1.804826e+06,761100.12,842173.33,306,213,...,642398.35,960875.13,277,242,160942.76,40609.72,47,21,2020-07-17,2020-07-17
5,2020-07-17 20:00:03.000,2020-07-17 20:01:00.000,1,ACIO,18,6.588244e+04,32204.76,23474.88,11,6,...,35182.74,20496.90,11,6,0.00,10202.80,0,3,2020-07-17,2020-07-17
6,2020-07-17 20:00:03.000,2020-07-17 20:01:00.000,1,ACSG,6,4.049330e+03,3374.44,674.89,5,0,...,4049.33,0.00,4,2,0.00,0.00,0,0,2020-07-17,2020-07-17
7,2020-07-17 20:00:03.000,2020-07-17 20:01:00.000,1,ACSI,5,7.685300e+02,17.50,751.03,3,1,...,0.00,768.53,1,4,0.00,0.00,0,0,2020-07-17,2020-07-17
8,2020-07-17 20:00:03.000,2020-07-17 16:01:00.000,1,ACT,46,6.817609e+04,33837.63,24308.16,23,22,...,33570.87,24574.92,23,23,7762.56,2267.73,5,2,2020-07-17,2020-07-17
9,2020-07-17 20:00:03.000,2020-07-17 20:01:00.000,1,ACWF,32,5.590840e+05,17929.85,494708.50,16,15,...,15008.31,497630.03,17,15,12828.65,33616.99,2,5,2020-07-17,2020-07-17

## Retrieve data for a specific date range using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_1', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-02 20:00:03.000,2024-01-02 20:01:00.000,1,AAA,53,1.576802e+05,6.588189e+04,9.044803e+04,27,25,...,5.083237e+04,1.054976e+05,25,28,324.79,1025.47,3,2,2024-01-02,2024-01-02
1,2024-01-02 20:00:03.000,2024-01-02 20:01:00.000,1,AAAU,1758,2.781265e+07,1.000134e+07,1.091454e+07,868,888,...,1.028472e+07,1.063117e+07,867,891,3332243.29,3564524.73,231,134,2024-01-02,2024-01-02
2,2024-01-02 20:00:03.000,2024-01-02 16:16:00.000,1,AADR,28,3.289354e+04,8.048180e+03,1.368056e+04,12,15,...,8.048180e+03,1.368056e+04,12,15,991.77,10173.02,2,5,2024-01-02,2024-01-02
3,2024-01-02 20:00:03.000,2024-01-02 19:32:00.000,1,AAPB,1230,2.397715e+06,1.189539e+06,7.612946e+05,693,536,...,1.176249e+06,7.745849e+05,634,595,301561.19,145319.49,127,21,2024-01-02,2024-01-02
4,2024-01-02 20:00:03.000,2024-01-02 19:47:00.000,1,AAPD,2027,1.110456e+07,4.038395e+06,4.580597e+06,1019,1007,...,4.020703e+06,4.598289e+06,1032,995,1383705.36,1101862.77,189,124,2024-01-02,2024-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-02 20:00:03.000,2024-01-02 20:01:00.000,1,ARKC,23,8.545122e+03,5.314080e+03,1.273340e+03,11,11,...,5.540510e+03,1.046920e+03,12,11,1541.61,416.09,1,2,2024-01-02,2024-01-02
96,2024-01-02 20:00:03.000,2024-01-02 20:01:00.000,1,ARKD,84,2.518650e+05,9.542845e+04,1.329806e+05,42,41,...,8.011308e+04,1.482960e+05,37,46,6285.25,17170.67,9,12,2024-01-02,2024-01-02
97,2024-01-02 20:00:03.000,2024-01-02 19:40:00.000,1,ARKF,8936,3.986029e+07,1.758964e+07,1.822817e+07,4124,4811,...,1.791827e+07,1.789954e+07,4167,4769,1598426.63,2444054.35,480,410,2024-01-02,2024-01-02
98,2024-01-02 20:00:03.000,2024-01-02 20:00:00.000,1,ARKG,29580,1.369080e+08,5.887218e+07,6.500450e+07,15087,14492,...,5.841009e+07,6.546659e+07,15006,14572,8236185.91,4795139.16,865,548,2024-01-02,2024-01-02
99,2024-01-02 20:00:03.000,2024-01-02 20:00:00.000,1,ARKK,156367,1.236807e+09,6.190026e+08,5.394874e+08,83104,73149,...,6.134669e+08,5.450231e+08,82810,73556,41440641.56,36876852.67,3584,2290,2024-01-02,2024-01-02

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_1',key='FTCS', asof_date='2024-01-01', limit=100)
display(df)

,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2016-10-14 20:00:03.000,2016-10-14 16:00:00.000,0,FTCS,110,1.162582e+06,122003.12,384159.41,50,59,...,188270.92,317891.61,51,59,482575.25,173844.32,29,21,2016-10-14,2016-10-14
1,2017-03-31 20:00:03.000,2017-03-31 16:01:00.000,1,FTCS,102,9.121132e+05,366771.42,189074.92,62,39,...,309937.12,245909.21,62,40,185199.04,171067.82,21,17,2017-03-31,2017-03-31
2,2016-11-16 20:00:03.000,2016-11-16 16:00:00.000,0,FTCS,210,2.818460e+06,830946.70,1299545.50,105,104,...,745364.82,1385127.38,88,122,253469.04,434498.87,34,37,2016-11-16,2016-11-16
3,2013-11-29 20:00:03.000,2013-11-29 12:52:00.000,0,FTCS,36,5.978803e+05,455462.59,112272.98,30,5,...,448401.29,119334.28,30,6,20096.94,10047.84,2,1,2013-11-29,2013-11-29
4,2016-06-14 20:00:03.000,2016-06-14 16:01:00.000,1,FTCS,112,9.127753e+05,306403.35,92075.06,77,34,...,310148.05,88330.37,81,31,185764.32,328532.59,17,17,2016-06-14,2016-06-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2021-11-05 20:00:03.000,2021-11-05 16:01:00.000,1,FTCS,1641,1.745928e+07,6559388.85,5635113.13,895,745,...,6239292.81,5955209.12,877,764,3434864.59,1829911.86,305,230,2021-11-05,2021-11-05
96,2021-06-22 20:00:03.000,2021-06-22 16:01:00.000,1,FTCS,1824,2.177926e+07,6417800.47,8118177.29,988,835,...,6620672.93,7915304.87,958,866,3140711.36,4102573.52,288,250,2021-06-22,2021-06-22
97,2016-11-28 20:00:03.000,2016-11-28 15:59:00.000,0,FTCS,167,1.569955e+06,381171.82,414771.68,97,69,...,264690.36,531253.15,81,86,531465.63,242545.51,49,24,2016-11-28,2016-11-28
98,2021-09-16 20:00:03.000,2021-09-16 16:01:00.000,1,FTCS,2467,2.596494e+07,11678511.86,8090276.07,1372,1094,...,11519651.26,8249136.75,1367,1100,2978561.31,3217593.76,350,260,2021-09-16,2021-09-16
99,2021-12-07 20:00:03.000,2021-12-07 16:03:00.000,1,FTCS,2186,1.950476e+07,6067325.04,6518576.05,1147,1038,...,5815660.44,6770240.58,1107,1079,4494187.54,2424666.96,383,340,2021-12-07,2021-12-07

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_1',key='FTCS', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-10 20:00:03.000,2024-01-10 16:16:00.000,1,FTCS,3591,2.639224e+07,9187483.25,9505854.65,1864,1726,...,9334174.36,9359163.63,1863,1728,3698044.04,4000862.71,628,332,2024-01-10,2024-01-10
1,2024-01-03 20:00:03.000,2024-01-03 16:16:00.000,1,FTCS,3038,4.342894e+07,11507781.41,25615143.33,1438,1599,...,11854462.28,25268462.50,1433,1605,3222308.48,3083704.81,394,363,2024-01-03,2024-01-03
2,2024-01-29 20:00:03.000,2024-01-29 16:16:00.000,1,FTCS,2586,2.274960e+07,7723746.00,9776073.19,1311,1274,...,7680586.73,9819232.53,1320,1265,3345728.83,1904056.29,363,254,2024-01-29,2024-01-29
3,2024-01-11 20:00:03.000,2024-01-11 16:16:00.000,1,FTCS,2876,3.769933e+07,12126521.23,18661891.24,1369,1506,...,11972154.67,18816257.87,1375,1501,3991278.51,2919641.39,368,265,2024-01-11,2024-01-11
4,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,FTCS,2545,2.607478e+07,9281362.80,11389683.81,1250,1293,...,9532694.54,11138352.00,1246,1299,3233279.52,2170452.17,366,228,2024-01-17,2024-01-17
5,2024-01-25 20:00:03.000,2024-01-25 16:16:00.000,1,FTCS,2273,2.626156e+07,7690799.90,9476452.75,1077,1192,...,8032995.99,9134256.58,1089,1183,4746742.12,4347567.11,294,272,2024-01-25,2024-01-25
6,2024-01-05 20:00:03.000,2024-01-05 16:36:00.000,1,FTCS,3632,3.652303e+07,15843540.36,13550915.55,1881,1750,...,15589302.24,13805153.73,1858,1774,3322880.72,3805690.95,358,318,2024-01-05,2024-01-05
7,2024-01-02 20:00:03.000,2024-01-02 16:16:00.000,1,FTCS,2746,2.941589e+07,11480743.58,11119110.84,1378,1367,...,11554128.46,11045725.98,1380,1365,4016792.65,2799247.27,393,386,2024-01-02,2024-01-02
8,2024-01-26 20:00:03.000,2024-01-26 16:16:00.000,1,FTCS,2434,2.382428e+07,8111250.13,10398250.92,1211,1222,...,8395069.85,10114431.23,1239,1195,3416506.80,1898270.61,315,235,2024-01-26,2024-01-26
9,2024-01-04 20:00:03.000,2024-01-04 16:16:00.000,1,FTCS,2652,2.630406e+07,8875059.73,9910971.95,1269,1382,...,9133688.97,9652342.77,1289,1363,2993734.38,4524291.20,399,377,2024-01-04,2024-01-04
10,2024-01-18 20:00:03.000,2024-01-18 16:16:00.000,1,FTCS,2500,2.714933e+07,9681016.63,9918394.14,1244,1255,...,9323922.14,10275488.61,1253,1245,3982835.02,3567086.56,349,225,2024-01-18,2024-01-18
11,2024-01-19 20:00:03.000,2024-01-19 16:16:00.000,1,FTCS,3070,3.253094e+07,15369433.02,9809684.50,1800,1268,...,15011920.28,10167197.23,1775,1295,4013711.83,3338112.09,354,236,2024-01-19,2024-01-19
12,2024-01-23 20:00:03.000,2024-01-23 16:16:00.000,1,FTCS,2661,2.648140e+07,10149130.57,10249554.41,1384,1275,...,10193972.72,10204712.25,1384,1277,2950364.18,3132352.13,345,277,2024-01-23,2024-01-23
13,2024-01-16 20:00:03.000,2024-01-16 17:41:00.000,1,FTCS,2729,2.533248e+07,9932380.80,10094523.55,1388,1340,...,9893769.63,10133134.69,1383,1346,3045199.62,2260373.36,397,261,2024-01-16,2024-01-16
14,2024-01-30 20:00:03.000,2024-01-30 16:16:00.000,1,FTCS,2341,2.346161e+07,6877857.70,10069055.57,1067,1273,...,7392148.28,9554765.00,1095,1246,3240877.96,3273820.25,349,306,2024-01-30,2024-01-30
15,2024-01-08 20:00:03.000,2024-01-08 16:16:00.000,1,FTCS,3039,3.176131e+07,11536626.67,11962007.27,1427,1610,...,11531466.85,11967167.11,1421,1618,2742212.27,5520467.24,343,330,2024-01-08,2024-01-08
16,2024-01-24 20:00:03.000,2024-01-24 16:16:00.000,1,FTCS,3747,3.818258e+07,15006685.95,15853581.48,1850,1896,...,14314765.25,16545502.06,1807,1940,3871194.39,3451118.66,353,257,2024-01-24,2024-01-24
17,2024-01-12 20:00:03.000,2024-01-12 19:49:00.000,1,FTCS,2723,3.820619e+07,12847803.02,18819868.23,1416,1306,...,12795356.55,18872314.69,1432,1291,4842558.68,1695958.01,356,208,2024-01-12,2024-01-12
18,2024-01-31 20:00:03.000,2024-01-31 16:16:00.000,1,FTCS,2850,4.868074e+07,18746114.84,22703416.26,1304,1545,...,18701495.88,22748035.26,1293,1557,4410874.10,2820337.59,365,211,2024-01-31,2024-01-31
19,2024-01-09 20:00:03.000,2024-01-09 16:16:00.000,1,FTCS,3172,4.018719e+07,14064823.80,17893960.79,1445,1726,...,14147166.14,17811618.47,1454,1718,4954438.12,3273967.11,379,304,2024-01-09,2024-01-09
20,2024-01-22 20:00:03.000,2024-01-22 16:16:00.000,1,FTCS,3236,3.573628e+07,15452704.22,13272948.57,1720,1515,...,15685504.39,13040148.45,1700,1535,3868944.94,3141685.45,448,287,2024-01-22,2024-01-22

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="lseg_us_etf_flow_daily_v1_2_1", target_location="./data", asof_date='2007-01-04')

Downloading using native python implementation for lseg_us_etf_flow_daily_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_etf_flow_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_etf_flow_daily_v1_2_1", target_location="./data")