In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_etf_flow_daily_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2017-12-22 20:00:03.000,2017-12-22 16:00:00.000,0,TFI,9119,3.960922e+07,17937137.25,14458317.88,5653,3465,...,17347418.86,15048036.35,5465,3653,3970400.19,3243364.48,1293,292,2017-12-22,2017-12-22
1,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,AAXJ,2981,5.073639e+07,32367679.42,16690439.99,1761,1219,...,30791530.38,18266589.05,1724,1257,1444489.51,233782.08,86,27,2017-12-22,2017-12-22
2,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,ACWI,4089,7.966487e+07,27717219.59,43907635.43,2058,2030,...,28214645.60,43410209.43,2075,2013,2747774.71,5292239.52,184,97,2017-12-22,2017-12-22
3,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,BNDX,2685,2.647918e+07,10015099.27,9161569.07,1292,1392,...,10484363.79,8692304.63,1398,1286,4550279.68,2752236.31,400,309,2017-12-22,2017-12-22
4,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,CSJ,1718,7.227388e+07,28078255.46,28449672.87,956,761,...,28780402.70,27747525.66,970,747,9180171.17,6565781.71,253,214,2017-12-22,2017-12-22
5,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,DVY,2657,4.764281e+07,14926716.71,20624057.53,1164,1492,...,15318813.43,20231960.80,1191,1465,5620582.01,6471449.86,262,262,2017-12-22,2017-12-22
6,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,IEI,1463,4.919373e+07,14149484.82,25475440.79,684,778,...,14220504.13,25404421.41,686,777,4304893.36,5263907.38,149,198,2017-12-22,2017-12-22
7,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,IJT,1346,1.488509e+07,6295172.73,4600301.61,768,577,...,5856537.74,5038936.58,736,608,2122887.30,1866732.46,202,137,2017-12-22,2017-12-22
8,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,IUSG,2477,4.226553e+07,15948487.96,13365191.75,1533,943,...,15131820.41,14181859.32,1379,1098,6920715.64,6031136.79,408,281,2017-12-22,2017-12-22
9,2017-12-22 20:00:03.000,2017-12-22 16:01:00.000,1,MBB,1984,4.614998e+07,17844666.79,17818706.43,1054,929,...,16707976.31,18955396.85,1051,933,4155485.74,6331121.88,283,345,2017-12-22,2017-12-22

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_1_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-30 20:00:03.000,2024-01-30 16:16:00.000,1,AAXJ,5213,6.746054e+07,3.245713e+07,3.343401e+07,2846,2366,...,3.352205e+07,3.236909e+07,2839,2374,7.111142e+05,8.582874e+05,56,53,2024-01-30,2024-01-30
1,2024-01-30 20:00:03.000,2024-01-30 16:16:00.000,1,IGSB,6865,1.763258e+08,9.067642e+07,7.415148e+07,3261,3602,...,9.180679e+07,7.302112e+07,3264,3599,6.782200e+06,4.715665e+06,425,285,2024-01-30,2024-01-30
2,2024-01-30 20:00:03.000,2024-01-30 16:16:00.000,1,IXUS,10048,1.309665e+08,5.280714e+07,6.857599e+07,4828,5219,...,6.116612e+07,6.021701e+07,5121,4927,4.860535e+06,4.722829e+06,363,352,2024-01-30,2024-01-30
3,2024-01-30 20:00:03.000,2024-01-30 16:16:00.000,1,USIG,6901,4.986394e+07,2.372826e+07,1.861915e+07,4014,2886,...,2.324167e+07,1.910574e+07,3870,3031,4.293319e+06,3.223216e+06,308,326,2024-01-30,2024-01-30
4,2024-01-30 20:00:03.000,2024-01-30 16:26:00.000,1,IUSB,9276,1.784465e+08,7.845357e+07,7.340867e+07,4700,4575,...,7.560557e+07,7.625667e+07,4559,4717,1.977527e+07,6.809036e+06,682,412,2024-01-30,2024-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-30 20:00:03.000,2024-01-30 20:00:00.000,1,SPY,446040,2.478383e+10,1.188291e+10,1.142736e+10,227575,216453,...,1.186581e+10,1.144446e+10,228163,217877,8.220926e+08,6.514661e+08,19264,12049,2024-01-30,2024-01-30
96,2024-01-30 20:00:03.000,2024-01-30 20:00:00.000,1,SQQQ,111213,1.145637e+09,4.845266e+08,4.646050e+08,57426,53786,...,4.900573e+08,4.590742e+08,57551,53662,1.027655e+08,9.374018e+07,8339,7346,2024-01-30,2024-01-30
97,2024-01-30 20:00:03.000,2024-01-30 20:00:00.000,1,TECL,26818,1.550163e+08,7.218459e+07,7.189606e+07,13255,13538,...,7.094059e+07,7.314006e+07,13140,13678,5.668805e+06,5.266858e+06,905,634,2024-01-30,2024-01-30
98,2024-01-30 20:00:03.000,2024-01-30 20:00:00.000,1,TLT,146012,3.731637e+09,1.919993e+09,1.680197e+09,72700,72600,...,1.923201e+09,1.676990e+09,72758,73254,7.731244e+07,5.413432e+07,4332,2769,2024-01-30,2024-01-30
99,2024-01-30 20:00:03.000,2024-01-30 20:00:00.000,1,TMF,91912,5.787492e+08,2.783175e+08,2.680739e+08,46734,44692,...,2.766475e+08,2.697440e+08,46692,45219,2.002084e+07,1.233692e+07,3115,1518,2024-01-30,2024-01-30

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_1_trial',key='FTCS', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2020-05-13 20:00:03.000,2020-05-13 16:01:00.000,1,FTCS,4709,6.511946e+07,19037057.23,33936420.23,2083,2625,...,18964805.96,34008671.55,2052,2657,8241444.53,3904533.70,556,285,2020-05-13,2020-05-13
1,2020-12-02 20:00:03.000,2020-12-02 16:01:00.000,1,FTCS,3201,2.919948e+07,11685626.35,9426805.97,1833,1367,...,11546677.28,9565755.05,1788,1413,5969281.53,2117761.50,440,191,2020-12-02,2020-12-02
2,2020-09-15 20:00:03.000,2020-09-15 16:01:00.000,1,FTCS,3954,3.944573e+07,14530432.38,9606771.74,2266,1687,...,14167036.90,9970167.18,2184,1770,8682674.90,6625848.06,883,643,2020-09-15,2020-09-15
3,2020-04-16 20:00:03.000,2020-04-16 16:01:00.000,1,FTCS,3647,4.865040e+07,22093888.12,12511598.21,2218,1428,...,21508943.42,13096542.93,2109,1537,7168605.27,6876312.42,684,376,2020-04-16,2020-04-16
4,2020-09-18 20:00:03.000,2020-09-18 16:01:00.000,1,FTCS,3225,5.112983e+07,19425579.95,20636019.60,1463,1761,...,18753253.84,21308345.73,1449,1776,6717454.47,4350775.88,335,178,2020-09-18,2020-09-18
5,2020-05-05 20:00:03.000,2020-05-05 16:01:00.000,1,FTCS,2927,3.717035e+07,17199586.96,11717777.96,1726,1200,...,16424284.80,12493080.13,1641,1286,4117904.98,4135080.64,331,270,2020-05-05,2020-05-05
6,2020-09-09 20:00:03.000,2020-09-09 16:01:00.000,1,FTCS,3281,5.207557e+07,28601485.98,15048863.73,1953,1327,...,27995415.05,15654934.59,1952,1328,5183837.57,3241384.64,355,264,2020-09-09,2020-09-09
7,2020-11-11 20:00:03.000,2020-11-11 16:01:00.000,1,FTCS,3145,4.725883e+07,21102855.87,16739037.40,1819,1325,...,20461302.74,17380590.53,1767,1378,6255735.56,3161202.48,438,255,2020-11-11,2020-11-11
8,2018-12-28 20:00:03.000,2018-12-28 16:01:00.000,1,FTCS,3290,4.907579e+07,27898843.18,12814576.22,2174,1115,...,27375673.32,13337746.17,2153,1137,4430585.77,3931784.20,184,183,2018-12-28,2018-12-28
9,2021-08-04 20:00:03.000,2021-08-04 16:01:00.000,1,FTCS,3198,3.565894e+07,17419543.27,12331149.10,1979,1218,...,17314515.57,12436176.84,1963,1234,3956717.77,1951530.00,380,273,2021-08-04,2021-08-04
10,2021-04-07 20:00:03.000,2021-04-07 16:01:00.000,1,FTCS,2939,3.300532e+07,14337845.62,9376071.37,1924,1014,...,13997587.18,9716329.86,1868,1071,6063053.03,3228349.64,439,332,2021-04-07,2021-04-07
11,2023-06-29 20:00:03.000,2023-06-29 16:16:00.000,1,FTCS,4116,5.708877e+07,21333350.11,20039379.46,2125,1990,...,23226296.83,18146432.77,2273,1843,10210468.60,5505572.96,677,386,2023-06-29,2023-06-29
12,2019-10-14 20:00:03.000,2019-10-14 16:01:00.000,1,FTCS,1382,1.418473e+07,5950152.37,3316852.72,819,562,...,5930511.00,3336494.12,823,559,3634089.26,1283632.69,183,125,2019-10-14,2019-10-14
13,2019-08-29 20:00:03.000,2019-08-29 17:22:00.000,1,FTCS,2435,2.879730e+07,11945639.69,7104549.83,1512,922,...,10553831.41,8496358.10,1387,1048,6569137.21,3177974.76,425,234,2019-08-29,2019-08-29
14,2020-01-03 20:00:03.000,2020-01-03 16:01:00.000,1,FTCS,2195,2.535665e+07,12238692.46,7047574.18,1328,866,...,11790605.83,7495660.78,1309,886,4388200.49,1682183.80,261,167,2020-01-03,2020-01-03
15,2019-10-15 20:00:03.000,2019-10-15 16:01:00.000,1,FTCS,1531,1.725166e+07,9415822.36,3025048.54,943,587,...,9200839.95,3240030.97,937,594,2876713.78,1934073.06,189,144,2019-10-15,2019-10-15
16,2019-11-13 20:00:03.000,2019-11-13 16:01:00.000,1,FTCS,2449,2.008564e+07,8479755.12,7304472.83,1412,1036,...,7935128.52,7849099.48,1365,1084,3242316.96,1059093.71,268,130,2019-11-13,2019-11-13
17,2020-01-24 20:00:03.000,2020-01-24 17:24:00.000,1,FTCS,2472,1.864080e+07,8282364.56,4944093.58,1472,999,...,8251922.89,4974535.24,1452,1018,3079472.89,2334870.80,304,204,2020-01-24,2020-01-24
18,2019-11-15 20:00:03.000,2019-11-15 16:01:00.000,1,FTCS,1911,1.437196e+07,4900236.66,3068807.56,1336,574,...,3936461.30,4032582.95,1157,754,5290207.98,1112706.52,544,170,2019-11-15,2019-11-15

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_daily_v1_2_1_trial',key='FTCS', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_etf_flow_daily_v1_2_1_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for lseg_us_etf_flow_daily_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_etf_flow_daily_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_etf_flow_daily_v1_2_1_trial", target_location="./data")