In [3]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [4]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name="lseg_us_etf_flow_1min_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2023-05-03 04:01:03.000,2023-05-03 04:01:00.000,1,ARKK,3,421.84,210.92,210.92,1,1,...,140.61,281.23,1,2,0,0,0,0,2023-05-03,2023-05-03
1,2023-05-03 04:01:03.000,2023-05-03 04:01:00.000,1,KRBN,2,9048.00,4524.00,4524.00,0,0,...,0.00,9048.00,0,2,0,0,0,0,2023-05-03,2023-05-03
2,2023-05-03 04:01:03.000,2023-05-03 04:01:00.000,1,SPY,12,187187.23,77994.68,109192.55,4,6,...,85794.15,101393.08,1,2,0,0,0,0,2023-05-03,2023-05-03
3,2023-05-03 04:01:03.000,2023-05-03 04:01:00.000,1,UPRO,12,213095.80,44394.96,168700.84,2,9,...,106547.90,106547.90,0,0,0,0,0,0,2023-05-03,2023-05-03
4,2023-05-03 04:01:03.000,2023-05-03 04:01:00.000,1,URTY,4,20023.00,12514.38,7508.62,1,0,...,10011.50,10011.50,0,0,0,0,0,0,2023-05-03,2023-05-03
5,2023-05-03 04:01:03.000,2023-05-03 04:01:00.000,1,USO,9,71788.34,55835.38,15952.96,6,1,...,35894.17,35894.17,0,0,0,0,0,0,2023-05-03,2023-05-03
6,2023-05-03 04:01:03.000,2023-05-03 04:01:00.000,1,VTWO,1,3474.50,1737.25,1737.25,0,0,...,1737.25,1737.25,0,0,0,0,0,0,2023-05-03,2023-05-03
7,2023-05-03 04:02:03.000,2023-05-03 04:02:00.000,1,SPY,7,194202.94,138716.39,55486.55,5,2,...,97101.47,97101.47,0,0,0,0,0,0,2023-05-03,2023-05-03
8,2023-05-03 04:02:03.000,2023-05-03 04:02:00.000,1,USO,1,625.70,625.70,0.00,1,0,...,312.85,312.85,0,0,0,0,0,0,2023-05-03,2023-05-03
9,2023-05-03 04:03:03.000,2023-05-03 04:03:00.000,1,SPY,5,148538.90,59415.56,89123.34,2,3,...,74269.45,74269.45,0,0,0,0,0,0,2023-05-03,2023-05-03

## Retrieve data for a specific date range using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_1min_v1_2_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,QLD,4,33330.76,16665.38,16665.38,1,1,...,16665.38,16665.38,0,0,0,0,0,0,2024-01-31,2024-01-31
1,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,RETL,4,72.45,63.39,9.06,3,0,...,72.45,0.00,4,0,0,0,0,0,2024-01-31,2024-01-31
2,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,SPHD,1,42.50,21.25,21.25,0,0,...,42.50,0.00,1,0,0,0,0,0,2024-01-31,2024-01-31
3,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,TSLT,46,32389.71,5985.06,26404.65,8,37,...,16194.86,16194.86,0,0,0,0,0,0,2024-01-31,2024-01-31
4,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,VT,1,1461.60,730.80,730.80,0,0,...,1461.60,0.00,1,0,0,0,0,0,2024-01-31,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 04:33:03.000,2024-01-31 04:33:00.000,1,TSLT,22,54265.57,25899.48,28366.09,9,10,...,27132.78,27132.78,0,0,0,0,0,0,2024-01-31,2024-01-31
96,2024-01-31 04:33:03.000,2024-01-31 04:33:00.000,1,XLV,4,43051.75,32288.81,10762.94,3,1,...,43051.75,0.00,4,0,0,0,0,0,2024-01-31,2024-01-31
97,2024-01-31 04:34:03.000,2024-01-31 04:34:00.000,1,QLD,10,3727.55,2609.28,1118.27,7,3,...,0.00,3727.55,0,10,0,0,0,0,2024-01-31,2024-01-31
98,2024-01-31 04:34:03.000,2024-01-31 04:34:00.000,1,RETL,1,99.48,99.48,0.00,1,0,...,99.48,0.00,1,0,0,0,0,0,2024-01-31,2024-01-31
99,2024-01-31 04:34:03.000,2024-01-31 04:34:00.000,1,SPHD,1,425.00,425.00,0.00,1,0,...,425.00,0.00,1,0,0,0,0,0,2024-01-31,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_1min_v1_2_trial',key='ARKK', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2022-03-16 04:01:03.000,2022-03-16 04:01:00.000,1,ARKK,16,271556.09,144264.17,127291.92,7,6,...,169722.56,101833.53,9,5,0,0,0,0,2022-03-16,2022-03-16
1,2022-03-16 04:02:03.000,2022-03-16 04:02:00.000,1,ARKK,11,61642.65,16811.63,44831.02,3,8,...,39227.14,22415.51,7,4,0,0,0,0,2022-03-16,2022-03-16
2,2022-03-16 04:03:03.000,2022-03-16 04:03:00.000,1,ARKK,8,200575.86,175503.88,25071.98,7,1,...,175503.88,25071.98,7,1,0,0,0,0,2022-03-16,2022-03-16
3,2022-03-16 04:04:03.000,2022-03-16 04:04:00.000,1,ARKK,27,132362.45,88241.63,44120.82,18,9,...,14706.94,117655.51,3,24,0,0,0,0,2022-03-16,2022-03-16
4,2022-03-16 04:05:03.000,2022-03-16 04:05:00.000,1,ARKK,7,22813.50,13036.29,9777.21,4,3,...,19554.43,3259.07,6,1,0,0,0,0,2022-03-16,2022-03-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-03-16 05:54:03.000,2022-03-16 05:54:00.000,1,ARKK,1,11296.00,0.00,11296.00,0,1,...,0.00,11296.00,0,1,0,0,0,0,2022-03-16,2022-03-16
96,2022-03-16 05:55:03.000,2022-03-16 05:55:00.000,1,ARKK,2,22592.00,0.00,22592.00,0,2,...,0.00,22592.00,0,2,0,0,0,0,2022-03-16,2022-03-16
97,2022-03-16 05:56:03.000,2022-03-16 05:56:00.000,1,ARKK,1,28240.00,0.00,28240.00,0,1,...,0.00,28240.00,0,1,0,0,0,0,2022-03-16,2022-03-16
98,2022-03-16 05:58:03.000,2022-03-16 05:58:00.000,1,ARKK,2,28296.48,0.00,28296.48,0,2,...,0.00,28296.48,0,2,0,0,0,0,2022-03-16,2022-03-16
99,2022-03-16 05:59:03.000,2022-03-16 05:59:00.000,1,ARKK,10,18610.70,0.00,18610.70,0,10,...,0.00,18610.70,0,10,0,0,0,0,2022-03-16,2022-03-16

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [10]:
df = Unifier.get_dataframe(name='lseg_us_etf_flow_1min_v1_2_trial',key='NVDX', back_to='2024-01-01', up_to='2024-06-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-02-07 04:01:03.000,2024-02-07 04:01:00.000,1,NVDX,5,1082.25,324.68,757.58,1,3,...,1082.25,0.00,5,0,0,0,0,0,2024-02-07,2024-02-07
1,2024-02-07 04:02:03.000,2024-02-07 04:02:00.000,1,NVDX,10,11152.96,4461.18,6691.78,4,6,...,0.00,11152.96,0,10,0,0,0,0,2024-02-07,2024-02-07
2,2024-02-07 04:03:03.000,2024-02-07 04:03:00.000,1,NVDX,1,900.00,900.00,0.00,1,0,...,900.00,0.00,1,0,0,0,0,0,2024-02-07,2024-02-07
3,2024-02-07 04:04:03.000,2024-02-07 04:04:00.000,1,NVDX,1,1490.50,0.00,1490.50,0,1,...,0.00,1490.50,0,1,0,0,0,0,2024-02-07,2024-02-07
4,2024-02-07 04:06:03.000,2024-02-07 04:06:00.000,1,NVDX,1,300.00,300.00,0.00,1,0,...,300.00,0.00,1,0,0,0,0,0,2024-02-07,2024-02-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-02-07 07:42:03.000,2024-02-07 07:42:00.000,1,NVDX,2,963.36,0.00,963.36,0,2,...,963.36,0.00,2,0,0,0,0,0,2024-02-07,2024-02-07
96,2024-02-07 07:44:03.000,2024-02-07 07:44:00.000,1,NVDX,1,2709.45,0.00,2709.45,0,1,...,2709.45,0.00,1,0,0,0,0,0,2024-02-07,2024-02-07
97,2024-02-07 07:45:03.000,2024-02-07 07:45:00.000,1,NVDX,1,602.20,0.00,602.20,0,1,...,602.20,0.00,1,0,0,0,0,0,2024-02-07,2024-02-07
98,2024-02-07 07:48:03.000,2024-02-07 07:48:00.000,1,NVDX,4,3274.17,3274.17,0.00,4,0,...,3274.17,0.00,4,0,0,0,0,0,2024-02-07,2024-02-07
99,2024-02-07 07:50:03.000,2024-02-07 07:50:00.000,1,NVDX,3,181.31,60.44,120.87,1,2,...,181.31,0.00,3,0,0,0,0,0,2024-02-07,2024-02-07

## Download data file for a specific date using asof_date

In [11]:
Unifier.replicate(name="lseg_us_etf_flow_1min_v1_2_trial", target_location="./data", asof_date='2025-01-13')

Starting native python replication for lseg_us_etf_flow_1min_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_etf_flow_1min_v1_2_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_etf_flow_1min_v1_2_trial", target_location="./data")