In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [ ]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r2k_daily_v1_2", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2025-12-23,60,2025-12-23 16:11:00.000,2025-12-23 20:00:03.000,2.906808e+08,3.448279e+08,-5.414703e+07,2.727331e+08,3.627756e+08,-9.004250e+07,...,159862,208509,147145,208088,94923,95812,92918,193891,Consumer Staples,2025-12-23
1,2025-12-23,77,2025-12-23 18:16:00.000,2025-12-23 20:00:03.000,4.910348e+08,5.362040e+08,-4.516917e+07,4.427529e+08,5.844859e+08,-1.417330e+08,...,263314,321083,244526,314458,138702,138954,140847,253004,Communication Services,2025-12-23
2,2025-12-23,195,2025-12-23 19:01:00.000,2025-12-23 20:00:03.000,1.735640e+09,1.978697e+09,-2.430574e+08,1.607826e+09,2.106511e+09,-4.986846e+08,...,724671,931126,669889,931510,386644,388196,464264,869797,Consumer Discretionary,2025-12-23
3,2025-12-23,406,2025-12-23 19:01:00.000,2025-12-23 20:00:03.000,1.777437e+09,2.170342e+09,-3.929052e+08,1.732814e+09,2.214965e+09,-4.821513e+08,...,783888,987535,728416,958059,438467,444336,524194,787513,Financials,2025-12-23
4,2025-12-23,256,2025-12-23 19:01:00.000,2025-12-23 20:00:03.000,3.335636e+09,3.514655e+09,-1.790187e+08,3.253832e+09,3.596458e+09,-3.426263e+08,...,1331426,1392059,1271733,1371803,661854,664649,1068160,1171131,Industrials,2025-12-23
5,2025-12-23,100,2025-12-23 19:01:00.000,2025-12-23 20:00:03.000,5.502806e+08,6.225908e+08,-7.231017e+07,5.194330e+08,6.534383e+08,-1.340053e+08,...,238527,298590,219672,295382,113573,114210,108366,233957,Real Estate,2025-12-23
6,2025-12-23,31,2025-12-23 19:01:00.000,2025-12-23 20:00:03.000,4.479370e+08,4.563945e+08,-8.457530e+06,4.317150e+08,4.726166e+08,-4.090160e+07,...,120262,134098,113708,133472,71141,71642,102917,117115,Utilities,2025-12-23
7,2025-12-23,383,2025-12-23 19:41:00.000,2025-12-23 20:00:03.000,2.954608e+09,3.368566e+09,-4.139581e+08,2.766409e+09,3.556765e+09,-7.903562e+08,...,1403014,1863750,1298227,1879386,748691,753986,894956,1789880,Health Care,2025-12-23
8,2025-12-23,104,2025-12-23 19:56:00.000,2025-12-23 20:00:03.000,1.099550e+09,1.092238e+09,7.312307e+06,1.127883e+09,1.063904e+09,6.397936e+07,...,586784,557103,572728,542260,248675,248680,514009,433075,Energy,2025-12-23
9,2025-12-23,83,2025-12-23 19:59:00.000,2025-12-23 20:00:03.000,9.963366e+08,9.651106e+08,3.122593e+07,1.003471e+09,9.579759e+08,4.549551e+07,...,462427,455473,449737,451223,185595,185270,409002,416251,Materials,2025-12-23

In [ ]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r2k_daily_v1_2", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-11,61,2024-01-11 16:00:00.000,2024-01-11 20:00:03.000,3.632213e+08,3.929694e+08,-29748034.99,3.761654e+08,3.800252e+08,-3.859824e+06,...,149907,169361,145745,167988,67351,67586,114782,156143,Consumer Staples,2024-01-11
1,2024-01-11,414,2024-01-11 16:08:00.000,2024-01-11 20:00:03.000,3.719342e+09,3.697205e+09,22136735.31,3.680993e+09,3.735554e+09,-5.456083e+07,...,1614075,1730005,1572178,1705165,651776,655037,1222742,1541110,Health Care,2024-01-11
2,2024-01-11,276,2024-01-11 17:24:00.000,2024-01-11 20:00:03.000,1.628180e+09,1.571759e+09,56421372.85,1.670243e+09,1.529696e+09,1.405474e+08,...,816837,778935,789350,749840,336395,334297,576069,564742,Industrials,2024-01-11
3,2024-01-11,77,2024-01-11 18:53:00.000,2024-01-11 20:00:03.000,3.095958e+08,3.811703e+08,-71574458.68,2.975204e+08,3.932457e+08,-9.572525e+07,...,208565,252201,197924,246885,86030,86528,106244,203315,Communication Services,2024-01-11
4,2024-01-11,223,2024-01-11 19:00:00.000,2024-01-11 20:00:03.000,1.671065e+09,1.675963e+09,-4897574.97,1.702048e+09,1.644980e+09,5.706760e+07,...,753540,783723,742308,765847,309174,309684,590469,665967,Consumer Discretionary,2024-01-11
5,2024-01-11,376,2024-01-11 19:00:00.000,2024-01-11 20:00:03.000,1.582727e+09,1.535647e+09,47079716.53,1.605471e+09,1.512903e+09,9.256867e+07,...,717334,754466,698225,746659,294353,292899,551472,652632,Financials,2024-01-11
6,2024-01-11,102,2024-01-11 19:00:00.000,2024-01-11 20:00:03.000,6.226701e+08,6.489694e+08,-26299270.85,6.121129e+08,6.595266e+08,-4.741371e+07,...,308095,348122,291429,347994,116385,115610,144393,295186,Real Estate,2024-01-11
7,2024-01-11,33,2024-01-11 19:00:00.000,2024-01-11 20:00:03.000,2.258856e+08,2.576022e+08,-31716598.10,2.138876e+08,2.696001e+08,-5.571253e+07,...,89159,125062,83758,128323,40656,41595,61451,143916,Utilities,2024-01-11
8,2024-01-11,106,2024-01-11 19:22:00.000,2024-01-11 20:00:03.000,9.842286e+08,1.030497e+09,-46268868.65,9.920665e+08,1.022660e+09,-3.059313e+07,...,439290,453587,430533,443463,167907,167279,297795,343905,Energy,2024-01-11
9,2024-01-11,216,2024-01-11 19:51:00.000,2024-01-11 20:00:03.000,5.706982e+09,5.723123e+09,-16141247.38,5.727046e+09,5.703059e+09,2.398767e+07,...,1711380,1764169,1653804,1788270,687242,692276,1400756,1816030,Information Technology,2024-01-11

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r2k_daily_v1_2", target_location="./data", asof_date='2025-03-12')

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r2k_daily_v1_2", target_location="./data")