In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [ ]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_sp500_daily_v1_2", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2026-01-23,76,2026-01-23 17:58:00.000,2026-01-23 20:00:03.000,2.161328e+10,2.258714e+10,-9.738561e+08,2.092323e+10,2.327719e+10,-2.353957e+09,...,2077559,2498919,2007244,2561233,1026306,1029371,1802575,2681225,Financials,2026-01-23
1,2026-01-23,59,2026-01-23 19:01:00.000,2026-01-23 20:00:03.000,1.595172e+10,1.384880e+10,2.102925e+09,1.532706e+10,1.447346e+10,8.536007e+08,...,1460569,1511829,1386199,1565877,726846,725818,1299233,1585365,Health Care,2026-01-23
2,2026-01-23,31,2026-01-23 19:01:00.000,2026-01-23 20:00:03.000,4.693192e+09,4.442730e+09,2.504619e+08,4.353048e+09,4.782874e+09,-4.298259e+08,...,609897,800428,583921,821241,268005,268879,500060,875088,Utilities,2026-01-23
3,2026-01-23,23,2026-01-23 19:46:00.000,2026-01-23 20:00:03.000,2.014214e+10,1.631101e+10,3.831126e+09,1.890836e+10,1.754480e+10,1.363562e+09,...,1612601,1439232,1538723,1483373,718418,720502,1478275,1378723,Communication Services,2026-01-23
4,2026-01-23,36,2026-01-23 19:48:00.000,2026-01-23 20:00:03.000,8.221967e+09,7.345604e+09,8.763634e+08,8.480412e+09,7.087159e+09,1.393254e+09,...,1180519,885666,1168451,877806,420650,419488,1192302,726281,Consumer Staples,2026-01-23
5,2026-01-23,79,2026-01-23 19:53:00.000,2026-01-23 20:00:03.000,1.452128e+10,1.490415e+10,-3.828650e+08,1.424774e+10,1.517769e+10,-9.299548e+08,...,1462761,1651449,1427185,1683749,773513,779983,1414091,1664346,Industrials,2026-01-23
6,2026-01-23,48,2026-01-23 19:58:00.000,2026-01-23 20:00:03.000,2.462790e+10,1.929224e+10,5.335663e+09,2.447458e+10,1.944556e+10,5.029026e+09,...,1988922,1813816,1899097,1895264,960421,963528,1872632,1810831,Consumer Discretionary,2026-01-23
7,2026-01-23,31,2026-01-23 19:58:00.000,2026-01-23 20:00:03.000,3.043115e+09,2.914757e+09,1.283580e+08,3.027964e+09,2.929908e+09,9.805579e+07,...,406613,434301,394747,437621,195042,194939,345339,413333,Real Estate,2026-01-23
8,2026-01-23,21,2026-01-23 20:00:00.000,2026-01-23 20:00:03.000,5.875293e+09,6.322178e+09,-4.468844e+08,5.896944e+09,6.300528e+09,-4.035838e+08,...,854379,927046,837919,941714,311458,311675,781678,996461,Energy,2026-01-23
9,2026-01-23,70,2026-01-23 20:00:00.000,2026-01-23 20:00:03.000,6.945095e+10,6.912264e+10,3.283176e+08,6.945228e+10,6.912131e+10,3.309690e+08,...,5789524,5863652,5305104,6344034,2833196,2857772,5016437,6615277,Information Technology,2026-01-23

In [ ]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_sp500_daily_v1_2", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-16,72,2024-01-16 17:28:00.000,2024-01-16 20:00:03.000,1.404436e+10,1.286803e+10,1.176335e+09,1.414774e+10,1.276465e+10,1.383093e+09,...,1644756,1811614,1636306,1816240,659192,659778,1565044,1840177,Financials,2024-01-16
1,2024-01-16,38,2024-01-16 19:29:00.000,2024-01-16 20:00:03.000,5.748915e+09,5.561269e+09,1.876461e+08,5.497008e+09,5.813175e+09,-3.161669e+08,...,731097,910825,709253,919110,317462,317812,525848,989057,Consumer Staples,2024-01-16
2,2024-01-16,64,2024-01-16 19:38:00.000,2024-01-16 20:00:03.000,1.116845e+10,1.099809e+10,1.703639e+08,1.077842e+10,1.138812e+10,-6.097017e+08,...,1068684,1204410,1059443,1203401,548078,550396,1006142,1196879,Health Care,2024-01-16
3,2024-01-16,31,2024-01-16 19:41:00.000,2024-01-16 20:00:03.000,2.581595e+09,2.892187e+09,-3.105916e+08,2.625442e+09,2.848340e+09,-2.228977e+08,...,419019,432567,413315,429391,177599,176979,367129,370492,Real Estate,2024-01-16
4,2024-01-16,30,2024-01-16 19:47:00.000,2024-01-16 20:00:03.000,2.326628e+09,3.229015e+09,-9.023875e+08,2.145076e+09,3.410567e+09,-1.265490e+09,...,411970,575749,402561,582974,154617,155074,290489,651628,Utilities,2024-01-16
5,2024-01-16,23,2024-01-16 19:58:00.000,2024-01-16 20:00:03.000,3.694589e+09,6.154383e+09,-2.459794e+09,3.240030e+09,6.608941e+09,-3.368911e+09,...,575383,968881,524143,1019134,275462,275265,269140,1259806,Energy,2024-01-16
6,2024-01-16,22,2024-01-16 19:59:00.000,2024-01-16 20:00:03.000,8.670451e+09,9.350066e+09,-6.796149e+08,8.675350e+09,9.345166e+09,-6.698160e+08,...,897960,893956,887437,891050,365517,365921,823502,821600,Communication Services,2024-01-16
7,2024-01-16,53,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,2.227953e+10,1.942060e+10,2.858931e+09,2.211266e+10,1.958747e+10,2.525189e+09,...,1931185,1876165,1912459,1885402,864135,862475,1714893,2019431,Consumer Discretionary,2024-01-16
8,2024-01-16,78,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1.219944e+10,1.301579e+10,-8.163531e+08,1.209690e+10,1.311833e+10,-1.021430e+09,...,1444255,1642967,1419791,1664066,664093,667471,1302264,1728316,Industrials,2024-01-16
9,2024-01-16,64,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,4.407449e+10,3.895441e+10,5.120082e+09,4.582130e+10,3.720760e+10,8.613700e+09,...,3021864,2610508,3051419,2574890,1353382,1354896,3152788,2369959,Information Technology,2024-01-16

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_sp500_daily_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_equity_sector_flow_r1k_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_equity_sector_flow_r1k_daily_v1_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_sp500_daily_v1_2", target_location="./data")