In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [ ]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r3k_daily_v1_2", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2025-11-19,555,2025-11-19 18:35:00.000,2025-11-19 20:00:03.000,2.493158e+10,2.384422e+10,None,2.526866e+10,2.350714e+10,None,...,4030688,4250338,3935753,4228091,1841801,1840851,3629143,3765761,Financials,2025-11-19
1,2025-11-19,162,2025-11-19 19:01:00.000,2025-11-19 20:00:03.000,4.002786e+09,4.702109e+09,None,3.755088e+09,4.949807e+09,None,...,917004,1158256,864684,1163626,449245,452099,635677,1048453,Real Estate,2025-11-19
2,2025-11-19,484,2025-11-19 19:11:00.000,2025-11-19 20:00:03.000,2.358473e+10,2.278997e+10,None,2.312825e+10,2.324644e+10,None,...,4602211,4813785,4466975,4843336,2110267,2110032,4128597,4577773,Health Care,2025-11-19
3,2025-11-19,120,2025-11-19 19:18:00.000,2025-11-19 20:00:03.000,8.878532e+09,9.482635e+09,None,8.550223e+09,9.810944e+09,None,...,1776091,1919852,1663355,2010671,756321,760398,1515109,1983396,Consumer Staples,2025-11-19
4,2025-11-19,71,2025-11-19 19:23:00.000,2025-11-19 20:00:03.000,5.960624e+09,6.177742e+09,None,5.757899e+09,6.380467e+09,None,...,1020895,1154357,986574,1176364,450922,454555,927873,1163645,Utilities,2025-11-19
5,2025-11-19,137,2025-11-19 19:38:00.000,2025-11-19 20:00:03.000,5.868421e+09,5.732033e+09,None,5.922249e+09,5.678206e+09,None,...,1427400,1461663,1403953,1453463,553778,553456,1368876,1314445,Energy,2025-11-19
6,2025-11-19,134,2025-11-19 19:59:00.000,2025-11-19 20:00:03.000,5.881737e+09,6.137198e+09,None,5.615225e+09,6.403710e+09,None,...,1412286,1599921,1380889,1603767,614479,615410,1208320,1576806,Materials,2025-11-19
7,2025-11-19,123,2025-11-19 20:00:00.000,2025-11-19 20:00:03.000,2.805772e+10,2.619164e+10,None,2.770180e+10,2.654757e+10,None,...,2731618,2864949,2616677,2929216,1338135,1344111,2390667,2864000,Communication Services,2025-11-19
8,2025-11-19,316,2025-11-19 20:00:00.000,2025-11-19 20:00:03.000,3.430494e+10,3.339599e+10,None,3.287527e+10,3.482565e+10,None,...,4464384,4723988,4262266,4847491,2165062,2169897,3918637,4710373,Consumer Discretionary,2025-11-19
9,2025-11-19,424,2025-11-19 20:00:00.000,2025-11-19 20:00:03.000,2.215785e+10,2.403511e+10,None,2.175081e+10,2.444215e+10,None,...,4106283,4448946,3988831,4457780,2035341,2040785,3526438,4332271,Industrials,2025-11-19

In [ ]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r3k_daily_v1_2", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-22,532,2024-01-22 18:18:00.000,2024-01-22 20:00:03.000,1.942283e+10,1.802801e+10,None,1.935029e+10,1.810055e+10,None,...,3300399,3135789,3273862,3097607,1260502,1257134,2999363,2694827,Financials,2024-01-22
1,2024-01-22,532,2024-01-22 19:00:00.000,2024-01-22 20:00:03.000,1.711985e+10,1.692441e+10,None,1.738679e+10,1.665747e+10,None,...,3211752,3133837,3193933,3072646,1366027,1362572,2941165,2664689,Health Care,2024-01-22
2,2024-01-22,74,2024-01-22 19:00:00.000,2024-01-22 20:00:03.000,2.602825e+09,3.160333e+09,None,2.358919e+09,3.404238e+09,None,...,538136,729226,521055,736460,209880,211278,335547,808879,Utilities,2024-01-22
3,2024-01-22,165,2024-01-22 19:06:00.000,2024-01-22 20:00:03.000,4.171689e+09,6.248162e+09,None,4.104794e+09,6.315057e+09,None,...,956042,1035188,939767,1025355,363444,364678,713513,957015,Real Estate,2024-01-22
4,2024-01-22,120,2024-01-22 19:38:00.000,2024-01-22 20:00:03.000,7.977639e+09,8.619007e+09,None,7.624626e+09,8.972020e+09,None,...,1230615,1270775,1199855,1279353,500202,502252,997680,1293146,Consumer Staples,2024-01-22
5,2024-01-22,348,2024-01-22 19:44:00.000,2024-01-22 20:00:03.000,2.784324e+10,2.564688e+10,None,2.738294e+10,2.610718e+10,None,...,3705932,3468007,3615730,3485629,1523510,1520147,3174290,3398840,Consumer Discretionary,2024-01-22
6,2024-01-22,142,2024-01-22 19:54:00.000,2024-01-22 20:00:03.000,7.082024e+09,5.915291e+09,None,6.968598e+09,6.028717e+09,None,...,1251024,1182183,1239877,1153924,444995,441574,1059663,893838,Energy,2024-01-22
7,2024-01-22,131,2024-01-22 19:56:00.000,2024-01-22 20:00:03.000,4.113036e+09,3.764751e+09,None,4.206045e+09,3.671743e+09,None,...,833634,749432,836915,729750,312162,310602,786217,598748,Materials,2024-01-22
8,2024-01-22,125,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1.144877e+10,1.164656e+10,None,1.109863e+10,1.199670e+10,None,...,1369161,1401711,1328423,1388389,566478,567684,996838,1295107,Communication Services,2024-01-22
9,2024-01-22,442,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1.457303e+10,1.491373e+10,None,1.459866e+10,1.488810e+10,None,...,2894746,2814117,2867727,2773169,1194387,1186440,2613085,2503154,Industrials,2024-01-22

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r3k_daily_v1_2", target_location="./data", asof_date='2025-03-12')

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r3k_daily_v1_2", target_location="./data")