In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [ ]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_sp500_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2026-01-23,76,2026-01-23 17:58:00.000,2026-01-23 20:00:03.000,2.161328e+10,2.258714e+10,-9.738561e+08,2.092323e+10,2.327719e+10,-2.353957e+09,...,2077559,2498919,2007244,2561233,1026306,1029371,1802575,2681225,Financials,2026-01-23
1,2026-01-23,59,2026-01-23 19:01:00.000,2026-01-23 20:00:03.000,1.595172e+10,1.384880e+10,2.102925e+09,1.532706e+10,1.447346e+10,8.536007e+08,...,1460569,1511829,1386199,1565877,726846,725818,1299233,1585365,Health Care,2026-01-23
2,2026-01-23,31,2026-01-23 19:01:00.000,2026-01-23 20:00:03.000,4.693192e+09,4.442730e+09,2.504619e+08,4.353048e+09,4.782874e+09,-4.298259e+08,...,609897,800428,583921,821241,268005,268879,500060,875088,Utilities,2026-01-23
3,2026-01-23,23,2026-01-23 19:46:00.000,2026-01-23 20:00:03.000,2.014214e+10,1.631101e+10,3.831126e+09,1.890836e+10,1.754480e+10,1.363562e+09,...,1612601,1439232,1538723,1483373,718418,720502,1478275,1378723,Communication Services,2026-01-23
4,2026-01-23,36,2026-01-23 19:48:00.000,2026-01-23 20:00:03.000,8.221967e+09,7.345604e+09,8.763634e+08,8.480412e+09,7.087159e+09,1.393254e+09,...,1180519,885666,1168451,877806,420650,419488,1192302,726281,Consumer Staples,2026-01-23
5,2026-01-23,79,2026-01-23 19:53:00.000,2026-01-23 20:00:03.000,1.452128e+10,1.490415e+10,-3.828650e+08,1.424774e+10,1.517769e+10,-9.299548e+08,...,1462761,1651449,1427185,1683749,773513,779983,1414091,1664346,Industrials,2026-01-23
6,2026-01-23,48,2026-01-23 19:58:00.000,2026-01-23 20:00:03.000,2.462790e+10,1.929224e+10,5.335663e+09,2.447458e+10,1.944556e+10,5.029026e+09,...,1988922,1813816,1899097,1895264,960421,963528,1872632,1810831,Consumer Discretionary,2026-01-23
7,2026-01-23,31,2026-01-23 19:58:00.000,2026-01-23 20:00:03.000,3.043115e+09,2.914757e+09,1.283580e+08,3.027964e+09,2.929908e+09,9.805579e+07,...,406613,434301,394747,437621,195042,194939,345339,413333,Real Estate,2026-01-23
8,2026-01-23,21,2026-01-23 20:00:00.000,2026-01-23 20:00:03.000,5.875293e+09,6.322178e+09,-4.468844e+08,5.896944e+09,6.300528e+09,-4.035838e+08,...,854379,927046,837919,941714,311458,311675,781678,996461,Energy,2026-01-23
9,2026-01-23,70,2026-01-23 20:00:00.000,2026-01-23 20:00:03.000,6.945095e+10,6.912264e+10,3.283176e+08,6.945228e+10,6.912131e+10,3.309690e+08,...,5789524,5863652,5305104,6344034,2833196,2857772,5016437,6615277,Information Technology,2026-01-23

In [4]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_sp500_daily_v1_2_1", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-24,61,2024-01-24 19:01:00.000,2024-01-24 20:00:03.000,1.122193e+10,1.183961e+10,-6.176854e+08,1.077837e+10,1.228316e+10,-1.504790e+09,...,1141508,1169295,1148798,1161997,535466,542650,1141543,1169296,Health Care,2024-01-24
1,2024-01-24,30,2024-01-24 19:01:00.000,2024-01-24 20:00:03.000,2.891062e+09,3.203108e+09,-3.120458e+08,3.060929e+09,3.033242e+09,2.768715e+07,...,577089,594981,576582,595483,174146,176809,577201,594883,Utilities,2024-01-24
2,2024-01-24,30,2024-01-24 19:21:00.000,2024-01-24 20:00:03.000,2.461318e+09,2.451575e+09,9.742980e+06,2.400995e+09,2.511898e+09,-1.109025e+08,...,420517,424290,420396,424411,159055,162073,420358,424462,Real Estate,2024-01-24
3,2024-01-24,19,2024-01-24 19:28:00.000,2024-01-24 20:00:03.000,1.542120e+10,1.432256e+10,1.098640e+09,1.538138e+10,1.436239e+10,1.018984e+09,...,1167740,1130150,1164328,1133561,496536,499008,1166555,1131347,Communication Services,2024-01-24
4,2024-01-24,70,2024-01-24 19:47:00.000,2024-01-24 20:00:03.000,1.154385e+10,1.168640e+10,-1.425526e+08,1.111906e+10,1.211119e+10,-9.921252e+08,...,1468563,1479574,1472270,1475857,553867,556254,1468538,1479640,Financials,2024-01-24
5,2024-01-24,18,2024-01-24 19:50:00.000,2024-01-24 20:00:03.000,3.294364e+09,2.960489e+09,3.338750e+08,3.244790e+09,3.010063e+09,2.347264e+08,...,534031,525852,533627,526253,173991,173429,534160,525738,Energy,2024-01-24
6,2024-01-24,52,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,2.049635e+10,1.977809e+10,7.182585e+08,2.023151e+10,2.004292e+10,1.885878e+08,...,2003826,1967177,1983486,1987509,881151,893382,2002789,1968235,Consumer Discretionary,2024-01-24
7,2024-01-24,36,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,5.973902e+09,6.911585e+09,-9.376830e+08,5.971849e+09,6.913638e+09,-9.417896e+08,...,889280,892815,885938,896152,318489,322509,889764,892349,Consumer Staples,2024-01-24
8,2024-01-24,78,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1.155257e+10,1.240517e+10,-8.525962e+08,1.117215e+10,1.278558e+10,-1.613424e+09,...,1477295,1513765,1481983,1509075,636716,645470,1477283,1513821,Industrials,2024-01-24
9,2024-01-24,61,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,5.017207e+10,4.761166e+10,2.560408e+09,5.003457e+10,4.774915e+10,2.285419e+09,...,3219933,2983363,3197203,3006084,1495054,1500099,3217739,2985598,Information Technology,2024-01-24

## Download data file for a specific date using asof_date

In [5]:
Unifier.replicate(name="xtech_us_equity_sector_flow_sp500_daily_v1_2_1", target_location="./data", asof_date='2025-03-05')

Downloading using native python implementation for xtech_us_equity_sector_flow_sp500_daily_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_equity_sector_flow_sp500_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_sp500_daily_v1_2_1", target_location="./data")