In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r1k_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2026-06-25,62,2026-06-25 18:56:00.000,2026-06-25 20:00:03.000,4.895954e+09,4.265783e+09,6.301705e+08,4.433002e+09,4.728735e+09,-2.957330e+08,...,892442,899741,889004,903157,353428,355703,892440,899783,Real Estate,2026-06-25
1,2026-06-25,157,2026-06-25 19:13:00.000,2026-06-25 20:00:03.000,2.356079e+10,2.662878e+10,-3.067988e+09,2.264989e+10,2.753968e+10,-4.889790e+09,...,3362675,3483390,3360587,3485451,1494031,1507541,3361961,3484195,Financials,2026-06-25
2,2026-06-25,40,2026-06-25 19:30:00.000,2026-06-25 20:00:03.000,5.666994e+09,4.623291e+09,1.043703e+09,5.419717e+09,4.870568e+09,5.491495e+08,...,847059,838263,845212,840108,331605,333691,846864,838485,Utilities,2026-06-25
3,2026-06-25,34,2026-06-25 19:32:00.000,2026-06-25 20:00:03.000,5.127524e+09,5.459409e+09,-3.318850e+08,4.985378e+09,5.601555e+09,-6.161769e+08,...,905087,892701,905805,891969,332401,330620,904816,892992,Energy,2026-06-25
4,2026-06-25,104,2026-06-25 19:54:00.000,2026-06-25 20:00:03.000,2.167957e+10,2.180348e+10,-1.239074e+08,2.116091e+10,2.232214e+10,-1.161238e+09,...,2331949,2366706,2321251,2377387,1055942,1061927,2332105,2366614,Health Care,2026-06-25
5,2026-06-25,124,2026-06-25 19:55:00.000,2026-06-25 20:00:03.000,2.838930e+10,2.896796e+10,-5.786625e+08,2.819374e+10,2.916352e+10,-9.697862e+08,...,3500223,3599776,3495262,3604715,1577746,1590885,3498114,3601974,Consumer Discretionary,2026-06-25
6,2026-06-25,60,2026-06-25 19:58:00.000,2026-06-25 20:00:03.000,9.632248e+09,9.525167e+09,1.070816e+08,8.922632e+09,1.023478e+10,-1.312151e+09,...,1539526,1557286,1535953,1560847,621748,624332,1539436,1557423,Consumer Staples,2026-06-25
7,2026-06-25,51,2026-06-25 19:58:00.000,2026-06-25 20:00:03.000,5.637480e+09,5.738603e+09,-1.011224e+08,5.333399e+09,6.042684e+09,-7.092851e+08,...,1000065,999206,997632,1001633,419740,421970,999499,999809,Materials,2026-06-25
8,2026-06-25,50,2026-06-25 20:00:00.000,2026-06-25 20:00:03.000,2.071456e+10,2.041014e+10,3.044141e+08,2.069344e+10,2.043126e+10,2.621821e+08,...,2017852,2103620,2013675,2107792,932170,941785,2021456,2100043,Communication Services,2026-06-25
9,2026-06-25,174,2026-06-25 20:00:00.000,2026-06-25 20:00:03.000,3.067169e+10,2.589728e+10,4.774405e+09,2.912303e+10,2.744595e+10,1.677079e+09,...,3267396,3269154,3253343,3283174,1625645,1628040,3265563,3271093,Industrials,2026-06-25

In [5]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r1k_daily_v1_2_1", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-22,150,2024-01-22 18:18:00.000,2024-01-22 20:00:03.000,1.703445e+10,1.594464e+10,1.089813e+09,1.641621e+10,1.656288e+10,-1.466703e+08,...,2558526,2548379,2552966,2553917,936306,937217,2557980,2549021,Financials,2024-01-22
1,2024-01-22,106,2024-01-22 19:01:00.000,2024-01-22 20:00:03.000,1.341790e+10,1.273074e+10,6.871623e+08,1.312457e+10,1.302406e+10,1.005117e+08,...,1553428,1538160,1557604,1533972,676639,677595,1553368,1538288,Health Care,2024-01-22
2,2024-01-22,39,2024-01-22 19:01:00.000,2024-01-22 20:00:03.000,2.440976e+09,2.733031e+09,-2.920543e+08,2.490509e+09,2.683498e+09,-1.929893e+08,...,563557,579503,562053,581004,174004,175608,563602,579485,Utilities,2024-01-22
3,2024-01-22,60,2024-01-22 19:06:00.000,2024-01-22 20:00:03.000,3.368485e+09,4.512227e+09,-1.143742e+09,3.396634e+09,4.484078e+09,-1.087445e+09,...,700871,688170,697674,691362,243744,245200,700861,688215,Real Estate,2024-01-22
4,2024-01-22,55,2024-01-22 19:38:00.000,2024-01-22 20:00:03.000,7.252275e+09,7.132822e+09,1.194534e+08,7.285103e+09,7.099995e+09,1.851083e+08,...,1127490,1082811,1119312,1090986,413445,415542,1128073,1082257,Consumer Staples,2024-01-22
5,2024-01-22,122,2024-01-22 19:45:00.000,2024-01-22 20:00:03.000,2.446574e+10,2.197156e+10,2.494181e+09,2.431347e+10,2.212384e+10,2.189633e+09,...,2866258,2724619,2832546,2758313,1162707,1164277,2868090,2722861,Consumer Discretionary,2024-01-22
6,2024-01-22,30,2024-01-22 19:54:00.000,2024-01-22 20:00:03.000,3.699779e+09,3.444084e+09,2.556943e+08,3.637187e+09,3.506676e+09,1.305110e+08,...,643126,644616,642764,644969,209066,207485,643145,644629,Energy,2024-01-22
7,2024-01-22,50,2024-01-22 19:56:00.000,2024-01-22 20:00:03.000,3.435841e+09,3.044678e+09,3.911625e+08,3.469351e+09,3.011168e+09,4.581839e+08,...,598541,591462,597992,592008,218383,218010,598435,591596,Materials,2024-01-22
8,2024-01-22,41,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1.083678e+10,1.072530e+10,1.114835e+08,1.074575e+10,1.081633e+10,-7.057743e+07,...,1231025,1187047,1224864,1193206,462027,463578,1230148,1187944,Communication Services,2024-01-22
9,2024-01-22,158,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1.216382e+10,1.226165e+10,-9.783558e+07,1.202967e+10,1.239579e+10,-3.661185e+08,...,1884543,1881194,1884082,1881636,773970,771210,1884081,1881756,Industrials,2024-01-22

## Download data file for a specific date using asof_date

In [6]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r1k_daily_v1_2_1", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_equity_sector_flow_r1k_daily_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_equity_sector_flow_r1k_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r1k_daily_v1_2_1", target_location="./data")