In [2]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [3]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [8]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_daily_v1_2", key="sp500", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2026-01-02 00:00:00.000,60,2026-01-02 16:11:00.000,2026-01-02 20:00:03.000,1.092192e+10,9.659014e+09,1.262910e+09,1.152428e+10,9.056655e+09,2.467630e+09,...,1176879,1218875,1213001,598946,596908,1207159,1190600,Health Care,sp500,2026-01-02 00:00:00.000
1,2026-01-02 00:00:00.000,23,2026-01-02 16:12:00.000,2026-01-02 20:00:03.000,1.690580e+10,1.432292e+10,2.582882e+09,1.652461e+10,1.470411e+10,1.820503e+09,...,1601695,1534732,1674447,756422,758206,1441054,1648884,Communication Services,sp500,2026-01-02 00:00:00.000
2,2026-01-02 00:00:00.000,76,2026-01-02 16:13:00.000,2026-01-02 20:00:03.000,1.858184e+10,1.570314e+10,2.878696e+09,1.908820e+10,1.519678e+10,3.891418e+09,...,1813900,2085943,1801653,917344,915926,2237837,1582141,Financials,sp500,2026-01-02 00:00:00.000
3,2026-04-30 00:00:00.000,31,2026-04-30 18:38:00.000,2026-04-30 20:00:03.000,7.299412e+09,5.564991e+09,1.734421e+09,7.373600e+09,5.490804e+09,1.882797e+09,...,874268,982250,867068,354986,355170,960808,844982,Utilities,sp500,2026-04-30 00:00:00.000
4,2026-04-30 00:00:00.000,22,2026-04-30 19:58:00.000,2026-04-30 20:00:03.000,7.402551e+09,7.068031e+09,3.345198e+08,8.264750e+09,6.205832e+09,2.058918e+09,...,697825,1101599,678635,339720,339635,1289426,491108,Energy,sp500,2026-04-30 00:00:00.000
5,2026-04-30 00:00:00.000,26,2026-04-30 20:00:00.000,2026-04-30 20:00:03.000,5.413718e+09,5.669968e+09,-2.562504e+08,5.183217e+09,5.900468e+09,-7.172511e+08,...,813750,718151,825420,319394,319286,660986,882681,Materials,sp500,2026-04-30 00:00:00.000
6,2026-04-23 00:00:00.000,76,2026-04-23 17:49:00.000,2026-04-23 20:00:03.000,1.888172e+10,1.846825e+10,4.134644e+08,1.895586e+10,1.839411e+10,5.617467e+08,...,2134154,2217246,2128760,954156,959543,2295107,2021349,Financials,sp500,2026-04-23 00:00:00.000
7,2026-04-23 00:00:00.000,58,2026-04-23 19:33:00.000,2026-04-23 20:00:03.000,1.501657e+10,1.492936e+10,8.721076e+07,1.487384e+10,1.507209e+10,-1.982531e+08,...,1591344,1460611,1606549,720701,720958,1414630,1598459,Health Care,sp500,2026-04-23 00:00:00.000
8,2026-04-23 00:00:00.000,23,2026-04-23 20:00:00.000,2026-04-23 20:00:03.000,1.361774e+10,1.430823e+10,-6.904986e+08,1.335671e+10,1.456926e+10,-1.212545e+09,...,1377250,1206198,1383814,534604,538217,1117171,1439284,Communication Services,sp500,2026-04-23 00:00:00.000
9,2026-01-02 00:00:00.000,31,2026-01-02 17:18:00.000,2026-01-02 20:00:03.000,3.405751e+09,2.919696e+09,4.860546e+08,3.502882e+09,2.822566e+09,6.803160e+08,...,424285,639276,400830,212389,209426,694391,327185,Utilities,sp500,2026-01-02 00:00:00.000

In [10]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_daily_v1_2", key="sp500", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2024-01-25 00:00:00.000,64,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,5.378104e+10,5.126204e+10,2.519002e+09,5.471385e+10,5.032922e+10,4.384628e+09,...,3196740,3344996,3230714,1577862,1590691,3238119,3311682,Information Technology,sp500,2024-01-25 00:00:00.000
1,2024-01-16 00:00:00.000,38,2024-01-16 19:29:00.000,2024-01-16 20:00:03.000,5.748915e+09,5.561269e+09,1.876461e+08,5.497008e+09,5.813175e+09,-3.161669e+08,...,910825,709253,919110,317462,317812,525848,989057,Consumer Staples,sp500,2024-01-16 00:00:00.000
2,2024-01-16 00:00:00.000,31,2024-01-16 19:41:00.000,2024-01-16 20:00:03.000,2.581595e+09,2.892187e+09,-3.105916e+08,2.625442e+09,2.848340e+09,-2.228977e+08,...,432567,413315,429391,177599,176979,367129,370492,Real Estate,sp500,2024-01-16 00:00:00.000
3,2024-01-16 00:00:00.000,30,2024-01-16 19:47:00.000,2024-01-16 20:00:03.000,2.326628e+09,3.229015e+09,-9.023875e+08,2.145076e+09,3.410567e+09,-1.265490e+09,...,575749,402561,582974,154617,155074,290489,651628,Utilities,sp500,2024-01-16 00:00:00.000
4,2024-01-16 00:00:00.000,23,2024-01-16 19:58:00.000,2024-01-16 20:00:03.000,3.694589e+09,6.154383e+09,-2.459794e+09,3.240030e+09,6.608941e+09,-3.368911e+09,...,968881,524143,1019134,275462,275265,269140,1259806,Energy,sp500,2024-01-16 00:00:00.000
5,2024-01-16 00:00:00.000,28,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,2.711085e+09,3.150670e+09,-4.395851e+08,2.557803e+09,3.303951e+09,-7.461483e+08,...,523160,378007,529771,180859,181277,280234,598096,Materials,sp500,2024-01-16 00:00:00.000
6,2024-01-12 00:00:00.000,53,2024-01-12 19:58:00.000,2024-01-12 20:00:03.000,1.965119e+10,1.970962e+10,-5.842300e+07,1.821415e+10,2.114666e+10,-2.932511e+09,...,1869846,1559507,1933379,799517,807060,1246861,2148066,Consumer Discretionary,sp500,2024-01-12 00:00:00.000
7,2024-01-12 00:00:00.000,78,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,8.935899e+09,1.053182e+10,-1.595918e+09,8.679451e+09,1.078827e+10,-2.108815e+09,...,1448530,1126238,1466878,548474,553257,952868,1590399,Industrials,sp500,2024-01-12 00:00:00.000
8,2024-01-17 00:00:00.000,64,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,3.891628e+10,3.572109e+10,3.195186e+09,3.936406e+10,3.527331e+10,4.090750e+09,...,2442136,2629312,2435180,1184556,1188326,2611196,2430262,Information Technology,sp500,2024-01-17 00:00:00.000
9,2024-01-24 00:00:00.000,31,2024-01-24 19:20:00.000,2024-01-24 20:00:03.000,2.218468e+09,2.732380e+09,-5.139112e+08,1.968165e+09,2.982683e+09,-1.014518e+09,...,489225,295700,508556,160340,163763,169284,585153,Real Estate,sp500,2024-01-24 00:00:00.000

In [11]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_daily_v1_2", key="r1k", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2026-04-15 00:00:00.000,136,2026-04-15 20:00:00.000,2026-04-15 20:00:03.000,9.834641e+10,8.731047e+10,1.103594e+10,1.008504e+11,8.480645e+10,1.604399e+10,...,6304826,7624013,6174502,3246014,3250075,8214267,5473716,Information Technology,r1k,2026-04-15 00:00:00.000
1,2026-04-23 00:00:00.000,41,2026-04-23 16:32:00.000,2026-04-23 20:00:03.000,4.776763e+09,4.040971e+09,7.357919e+08,5.083670e+09,3.734064e+09,1.349606e+09,...,627164,920614,598323,300011,297524,982035,518784,Utilities,r1k,2026-04-23 00:00:00.000
2,2026-04-23 00:00:00.000,52,2026-04-23 19:59:00.000,2026-04-23 20:00:03.000,6.374590e+09,6.157811e+09,2.167787e+08,6.147950e+09,6.384451e+09,-2.365009e+08,...,1175808,998670,1198740,474502,476309,877314,1233296,Materials,r1k,2026-04-23 00:00:00.000
3,2026-04-23 00:00:00.000,36,2026-04-23 20:00:00.000,2026-04-23 20:00:03.000,6.507748e+09,6.780030e+09,-2.722821e+08,6.446129e+09,6.841649e+09,-3.955200e+08,...,1031460,1017722,1030240,371413,371775,1012040,983972,Energy,r1k,2026-04-23 00:00:00.000
4,2026-04-15 00:00:00.000,64,2026-04-15 18:01:00.000,2026-04-15 20:00:03.000,4.032799e+09,3.806699e+09,2.261008e+08,4.148806e+09,3.690692e+09,4.581137e+08,...,744256,785217,729403,315979,313174,733703,671767,Real Estate,r1k,2026-04-15 00:00:00.000
5,2026-04-15 00:00:00.000,60,2026-04-15 20:00:00.000,2026-04-15 20:00:03.000,7.512288e+09,7.898701e+09,-3.864134e+08,7.397505e+09,8.013484e+09,-6.159789e+08,...,1223253,1220025,1221433,500147,500170,1133214,1173576,Consumer Staples,r1k,2026-04-15 00:00:00.000
6,2026-04-23 00:00:00.000,159,2026-04-23 17:49:00.000,2026-04-23 20:00:03.000,2.338256e+10,2.276137e+10,6.211882e+08,2.355089e+10,2.259304e+10,9.578495e+08,...,3105313,3246145,3072512,1394902,1400164,3241949,2757383,Financials,r1k,2026-04-23 00:00:00.000
7,2026-04-23 00:00:00.000,106,2026-04-23 19:33:00.000,2026-04-23 20:00:03.000,1.819766e+10,1.820362e+10,-5.953458e+06,1.798921e+10,1.841207e+10,-4.228536e+08,...,2349854,2038780,2381761,1016635,1020416,1918658,2410186,Health Care,r1k,2026-04-23 00:00:00.000
8,2026-04-23 00:00:00.000,46,2026-04-23 20:00:00.000,2026-04-23 20:00:03.000,1.558327e+10,1.649334e+10,-9.100678e+08,1.506835e+10,1.700827e+10,-1.939917e+09,...,1904013,1582416,1931683,738741,744435,1452057,2019607,Communication Services,r1k,2026-04-23 00:00:00.000
9,2026-04-30 00:00:00.000,159,2026-04-30 16:59:00.000,2026-04-30 20:00:03.000,2.842953e+10,2.549991e+10,2.929618e+09,2.896499e+10,2.496445e+10,4.000541e+09,...,2898263,3849126,2797637,1476494,1476782,4108316,2312325,Financials,r1k,2026-04-30 00:00:00.000

In [12]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_daily_v1_2", key="r1k", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2024-01-22 00:00:00.000,64,2024-01-22 19:06:00.000,2024-01-22 20:00:03.000,3.498972e+09,5.561256e+09,-2.062284e+09,3.435087e+09,5.625141e+09,-2.190054e+09,...,714592,661554,710431,254979,256485,548350,735409,Real Estate,r1k,2024-01-22 00:00:00.000
1,2024-01-22 00:00:00.000,59,2024-01-22 19:38:00.000,2024-01-22 20:00:03.000,7.448770e+09,7.403998e+09,4.477200e+07,7.090339e+09,7.762429e+09,-6.720902e+08,...,1122779,1017059,1141686,423799,425724,833288,1197281,Consumer Staples,r1k,2024-01-22 00:00:00.000
2,2024-01-23 00:00:00.000,127,2024-01-23 19:58:00.000,2024-01-23 20:00:03.000,2.310322e+10,2.161555e+10,1.487673e+09,2.220389e+10,2.251488e+10,-3.109912e+08,...,2571641,2313332,2633584,1083067,1090110,1905577,2684695,Consumer Discretionary,r1k,2024-01-23 00:00:00.000
3,2024-01-23 00:00:00.000,165,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1.560662e+10,1.499914e+10,6.074875e+08,1.566278e+10,1.494298e+10,7.197948e+08,...,2237300,2408846,2215130,981216,986971,2424798,2011796,Industrials,r1k,2024-01-23 00:00:00.000
4,2024-01-31 00:00:00.000,117,2024-01-31 19:00:00.000,2024-01-31 20:00:03.000,1.812351e+10,1.949303e+10,-1.369519e+09,1.755983e+10,2.005670e+10,-2.496875e+09,...,1989301,1824406,2006955,864260,868721,1715778,2028055,Health Care,r1k,2024-01-31 00:00:00.000
5,2024-01-31 00:00:00.000,157,2024-01-31 19:05:00.000,2024-01-31 20:00:03.000,1.852957e+10,2.183500e+10,-3.305432e+09,1.760686e+10,2.275771e+10,-5.150849e+09,...,2997812,2493780,3031655,1086245,1098308,2139754,3193183,Financials,r1k,2024-01-31 00:00:00.000
6,2024-01-31 00:00:00.000,48,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1.630375e+10,1.812492e+10,-1.821176e+09,1.641479e+10,1.801387e+10,-1.599080e+09,...,1951810,1698463,1979806,746017,746596,1436475,1972857,Communication Services,r1k,2024-01-31 00:00:00.000
7,2024-01-29 00:00:00.000,127,2024-01-29 19:23:00.000,2024-01-29 20:00:03.000,2.732095e+10,2.061852e+10,6.702437e+09,2.839842e+10,1.954105e+10,8.857372e+09,...,2281485,3272696,2212275,1210538,1205698,3291980,1838370,Consumer Discretionary,r1k,2024-01-29 00:00:00.000
8,2024-01-29 00:00:00.000,165,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1.347631e+10,1.167025e+10,1.806062e+09,1.410009e+10,1.104647e+10,3.053620e+09,...,1617879,1957530,1558337,776494,768936,1980844,1282417,Industrials,r1k,2024-01-29 00:00:00.000
9,2024-01-12 00:00:00.000,59,2024-01-12 19:00:00.000,2024-01-12 20:00:03.000,5.192917e+09,4.792209e+09,4.007078e+08,5.285630e+09,4.699497e+09,5.861323e+08,...,762377,745586,757416,303151,303597,669925,710080,Consumer Staples,r1k,2024-01-12 00:00:00.000

In [15]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_daily_v1_2", key="r2k", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2026-04-17 00:00:00.000,261,2026-04-17 17:48:00.000,2026-04-17 20:00:03.000,7.490535e+09,7.817518e+09,-3.269829e+08,7.473199e+09,7.834853e+09,-3.616541e+08,...,1998689,1904230,1952446,917243,924140,1720741,1694621,Industrials,r2k,2026-04-17 00:00:00.000
1,2026-04-17 00:00:00.000,197,2026-04-17 19:51:00.000,2026-04-17 20:00:03.000,2.707591e+09,2.566402e+09,1.411892e+08,2.662012e+09,2.611982e+09,5.002962e+07,...,1146294,1189660,1105905,509390,509799,1090015,907953,Consumer Discretionary,r2k,2026-04-17 00:00:00.000
2,2026-04-16 00:00:00.000,31,2026-04-16 16:57:00.000,2026-04-16 20:00:03.000,8.937727e+08,8.099523e+08,8.382040e+07,9.302499e+08,7.734751e+08,1.567748e+08,...,214921,259559,208852,120483,120671,271482,185609,Utilities,r2k,2026-04-16 00:00:00.000
3,2026-04-16 00:00:00.000,104,2026-04-16 17:43:00.000,2026-04-16 20:00:03.000,1.756222e+09,1.499214e+09,2.570077e+08,1.818410e+09,1.437026e+09,3.813836e+08,...,632548,780518,595530,299204,298888,713367,454071,Energy,r2k,2026-04-16 00:00:00.000
4,2026-04-16 00:00:00.000,82,2026-04-16 19:58:00.000,2026-04-16 20:00:03.000,9.623290e+08,1.022784e+09,-6.045492e+07,9.206608e+08,1.064452e+09,-1.437914e+08,...,435474,392026,428792,184733,185579,301035,363886,Materials,r2k,2026-04-16 00:00:00.000
5,2026-01-02 00:00:00.000,258,2026-01-02 16:00:00.000,2026-01-02 20:00:03.000,4.227546e+09,3.821414e+09,4.061321e+08,4.451053e+09,3.597907e+09,8.531454e+08,...,1447184,1639404,1379089,725713,720922,1558877,1057066,Industrials,r2k,2026-01-02 00:00:00.000
6,2026-01-02 00:00:00.000,198,2026-01-02 16:04:00.000,2026-01-02 20:00:03.000,1.998111e+09,1.851309e+09,1.468018e+08,2.052121e+09,1.797298e+09,2.548229e+08,...,862501,924342,831167,418185,416344,834775,644395,Consumer Discretionary,r2k,2026-01-02 00:00:00.000
7,2026-01-02 00:00:00.000,419,2026-01-02 16:00:00.000,2026-01-02 20:00:03.000,2.304737e+09,2.249766e+09,5.497114e+07,2.339841e+09,2.214663e+09,1.251782e+08,...,1130624,994323,1108479,499676,499245,814353,964154,Financials,r2k,2026-01-02 00:00:00.000
8,2026-01-02 00:00:00.000,80,2026-01-02 16:04:00.000,2026-01-02 20:00:03.000,6.432053e+08,6.063063e+08,3.689890e+07,6.521374e+08,5.973742e+08,5.476324e+07,...,334619,284219,323795,159689,160986,184877,218360,Communication Services,r2k,2026-01-02 00:00:00.000
9,2026-01-02 00:00:00.000,396,2026-01-02 16:05:00.000,2026-01-02 20:00:03.000,3.829643e+09,4.089804e+09,-2.601612e+08,3.725592e+09,4.193856e+09,-4.682640e+08,...,2281054,1802808,2292002,946947,952707,1501203,2123632,Health Care,r2k,2026-01-02 00:00:00.000

In [13]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_daily_v1_2", key="r2k", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2024-01-31 00:00:00.000,222,2024-01-31 19:00:00.000,2024-01-31 20:00:03.000,1.949055e+09,2.257543e+09,-3.084882e+08,1.891199e+09,2.315399e+09,-4.241996e+08,...,922249,741820,906671,346611,354054,565435,777003,Consumer Discretionary,r2k,2024-01-31 00:00:00.000
1,2024-01-31 00:00:00.000,276,2024-01-31 19:36:00.000,2024-01-31 20:00:03.000,2.062332e+09,2.470542e+09,-4.082108e+08,1.963918e+09,2.568956e+09,-6.050387e+08,...,1012472,777744,994083,396646,405732,496544,802206,Industrials,r2k,2024-01-31 00:00:00.000
2,2024-01-25 00:00:00.000,61,2024-01-25 16:01:00.000,2024-01-25 20:00:03.000,3.900883e+08,3.453025e+08,4.478579e+07,3.974565e+08,3.379343e+08,5.952222e+07,...,144328,149720,140274,63998,63243,120741,119243,Consumer Staples,r2k,2024-01-25 00:00:00.000
3,2024-01-25 00:00:00.000,102,2024-01-25 19:00:00.000,2024-01-25 20:00:03.000,5.613005e+08,5.637604e+08,-2.459916e+06,5.634643e+08,5.615965e+08,1.867845e+06,...,253218,260883,247223,97791,97492,111079,137938,Real Estate,r2k,2024-01-25 00:00:00.000
4,2024-01-22 00:00:00.000,216,2024-01-22 16:00:00.000,2024-01-22 20:00:03.000,6.316561e+09,6.649625e+09,-3.330639e+08,6.446858e+09,6.519328e+09,-7.246949e+07,...,1251873,1235251,1249378,532922,531160,1070670,1151373,Information Technology,r2k,2024-01-22 00:00:00.000
5,2024-01-11 00:00:00.000,216,2024-01-11 19:51:00.000,2024-01-11 20:00:03.000,5.706982e+09,5.723123e+09,-1.614125e+07,5.727046e+09,5.703059e+09,2.398767e+07,...,1764169,1653804,1788270,687242,692276,1400756,1816030,Information Technology,r2k,2024-01-11 00:00:00.000
6,2024-01-22 00:00:00.000,276,2024-01-22 18:42:00.000,2024-01-22 20:00:03.000,2.243991e+09,2.012403e+09,2.315874e+08,2.326439e+09,1.929955e+09,3.964834e+08,...,893923,1052209,858854,401897,397469,963897,609570,Industrials,r2k,2024-01-22 00:00:00.000
7,2024-01-22 00:00:00.000,222,2024-01-22 19:00:00.000,2024-01-22 20:00:03.000,2.131665e+09,1.866054e+09,2.656113e+08,2.250667e+09,1.747052e+09,5.036156e+08,...,742585,954884,710107,342042,337534,900060,502516,Consumer Discretionary,r2k,2024-01-22 00:00:00.000
8,2024-01-16 00:00:00.000,376,2024-01-16 19:00:00.000,2024-01-16 20:00:03.000,1.252007e+09,1.441300e+09,-1.892928e+08,1.203248e+09,1.490059e+09,-2.868106e+08,...,754000,576239,750167,279255,281667,367367,678563,Financials,r2k,2024-01-16 00:00:00.000
9,2024-01-16 00:00:00.000,77,2024-01-16 19:32:00.000,2024-01-16 20:00:03.000,3.399716e+08,3.133323e+08,2.663931e+07,3.537327e+08,2.995712e+08,5.416155e+07,...,232068,240383,218492,93086,93348,153645,133561,Communication Services,r2k,2024-01-16 00:00:00.000

In [16]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_daily_v1_2", key="r3k", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2026-05-08 00:00:00.000,566,2026-05-08 19:05:00.000,2026-05-08 20:00:03.000,2.537113e+10,2.773867e+10,-2.367540e+09,2.503135e+10,2.807845e+10,-3.047102e+09,...,4746111,4335763,4736109,1994575,1994494,3988175,4603242,Financials,r3k,2026-05-08 00:00:00.000
1,2026-05-08 00:00:00.000,494,2026-05-08 19:54:00.000,2026-05-08 20:00:03.000,2.445443e+10,2.575947e+10,-1.305042e+09,2.453826e+10,2.567565e+10,-1.137389e+09,...,5271549,4761209,5247694,2276514,2282305,4213933,5029297,Health Care,r3k,2026-05-08 00:00:00.000
2,2026-05-08 00:00:00.000,123,2026-05-08 20:00:00.000,2026-05-08 20:00:03.000,1.772458e+10,1.808537e+10,-3.607902e+08,1.727969e+10,1.853025e+10,-1.250554e+09,...,2404121,2183324,2416294,1019831,1022134,1936955,2229704,Communication Services,r3k,2026-05-08 00:00:00.000
3,2026-04-17 00:00:00.000,72,2026-04-17 17:48:00.000,2026-04-17 20:00:03.000,6.503662e+09,5.853814e+09,6.498478e+08,6.846087e+09,5.511388e+09,1.334699e+09,...,963176,1123259,948223,438936,439431,1162570,842043,Utilities,r3k,2026-04-17 00:00:00.000
4,2026-04-17 00:00:00.000,140,2026-04-17 19:54:00.000,2026-04-17 20:00:03.000,1.432074e+10,1.310436e+10,1.216376e+09,1.498092e+10,1.244418e+10,2.536737e+09,...,2398129,2650355,2369284,959463,959602,2733037,2167194,Energy,r3k,2026-04-17 00:00:00.000
5,2026-04-17 00:00:00.000,133,2026-04-17 19:59:00.000,2026-04-17 20:00:03.000,9.671186e+09,9.645721e+09,2.546558e+07,9.664809e+09,9.652098e+09,1.271128e+07,...,1964945,1969753,1954154,816817,817243,1932982,1868234,Materials,r3k,2026-04-17 00:00:00.000
6,2026-04-16 00:00:00.000,345,2026-04-16 20:00:00.000,2026-04-16 20:00:03.000,1.035356e+11,9.660188e+10,6.933713e+09,1.045554e+11,9.558210e+10,8.973259e+09,...,9669609,9994527,9590859,4434582,4441286,10027256,9016479,Information Technology,r3k,2026-04-16 00:00:00.000
7,2026-04-30 00:00:00.000,140,2026-04-30 17:45:00.000,2026-04-30 20:00:03.000,1.097315e+10,1.010212e+10,8.710250e+08,1.188731e+10,9.187956e+09,2.699355e+09,...,1693767,2264685,1640199,820427,818578,2440369,1239916,Energy,r3k,2026-04-30 00:00:00.000
8,2026-04-30 00:00:00.000,72,2026-04-30 18:38:00.000,2026-04-30 20:00:03.000,8.679965e+09,6.910519e+09,1.769446e+09,8.868122e+09,6.722361e+09,2.145761e+09,...,1180759,1351274,1159284,513489,514202,1344260,1104865,Utilities,r3k,2026-04-30 00:00:00.000
9,2026-04-30 00:00:00.000,134,2026-04-30 20:00:00.000,2026-04-30 20:00:03.000,8.807794e+09,8.542132e+09,2.656628e+08,8.659411e+09,8.690515e+09,-3.110335e+07,...,1721521,1829863,1695051,754852,751758,1765262,1649987,Materials,r3k,2026-04-30 00:00:00.000

In [14]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_daily_v1_2", key="r3k", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2024-01-11 00:00:00.000,532,2024-01-11 19:00:00.000,2024-01-11 20:00:03.000,1.646088e+10,1.691252e+10,None,1.648796e+10,1.688544e+10,None,...,3348493,3164642,3306991,1373124,1375212,2738993,3061962,Health Care,r3k,2024-01-11 00:00:00.000
1,2024-01-11 00:00:00.000,532,2024-01-11 19:44:00.000,2024-01-11 20:00:03.000,1.781871e+10,1.822796e+10,None,1.809933e+10,1.794733e+10,None,...,3240832,2938311,3218376,1244130,1245427,2536323,3142378,Financials,r3k,2024-01-11 00:00:00.000
2,2024-01-11 00:00:00.000,125,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1.149768e+10,1.154568e+10,None,1.159728e+10,1.144609e+10,None,...,1602444,1472808,1598147,614960,618319,1305146,1516125,Communication Services,r3k,2024-01-11 00:00:00.000
3,2024-01-30 00:00:00.000,74,2024-01-30 19:00:00.000,2024-01-30 20:00:03.000,2.674182e+09,2.521800e+09,None,2.593983e+09,2.601999e+09,None,...,593759,581281,589525,195277,193396,546398,532937,Utilities,r3k,2024-01-30 00:00:00.000
4,2024-01-30 00:00:00.000,142,2024-01-30 19:40:00.000,2024-01-30 20:00:03.000,9.677858e+09,7.340731e+09,None,1.015812e+10,6.860466e+09,None,...,1352153,1834897,1301662,575845,566509,1918862,875111,Energy,r3k,2024-01-30 00:00:00.000
5,2024-01-30 00:00:00.000,131,2024-01-30 19:57:00.000,2024-01-30 20:00:03.000,3.748314e+09,3.973134e+09,None,3.757382e+09,3.964066e+09,None,...,776973,802807,758848,316472,315099,716057,678543,Materials,r3k,2024-01-30 00:00:00.000
6,2024-01-25 00:00:00.000,531,2024-01-25 19:00:00.000,2024-01-25 20:00:03.000,2.093809e+10,1.857752e+10,None,2.091141e+10,1.860420e+10,None,...,3006850,3088123,2969187,1326678,1322382,2709380,2671033,Health Care,r3k,2024-01-25 00:00:00.000
7,2024-01-25 00:00:00.000,532,2024-01-25 19:33:00.000,2024-01-25 20:00:03.000,1.937493e+10,1.737350e+10,None,1.953877e+10,1.720965e+10,None,...,3243847,3248192,3234616,1295444,1288655,2773019,3049351,Financials,r3k,2024-01-25 00:00:00.000
8,2024-01-25 00:00:00.000,125,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1.488432e+10,1.217659e+10,None,1.550361e+10,1.155730e+10,None,...,1559017,1788982,1524178,669020,668839,1664301,1270164,Communication Services,r3k,2024-01-25 00:00:00.000
9,2024-01-12 00:00:00.000,74,2024-01-12 19:00:00.000,2024-01-12 20:00:03.000,2.349897e+09,2.721017e+09,None,2.451340e+09,2.619574e+09,None,...,515962,487671,512512,178010,178600,396307,429200,Utilities,r3k,2024-01-12 00:00:00.000

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_daily_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for xtech_us_eqt_short_interest_factor_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_short_interest_factor_daily_v1_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_daily_v1_2", target_location="./data")