In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r2k_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2026-04-17,58,2026-04-17 16:01:00.000,2026-04-17 20:00:03.000,4.147285e+08,3.922105e+08,2.251798e+07,4.084438e+08,3.984952e+08,9.948658e+06,...,294377,308103,294735,307739,137568,138107,294379,308133,Consumer Staples,2026-04-17
1,2026-04-17,375,2026-04-17 17:05:00.000,2026-04-17 20:00:03.000,5.213891e+09,4.978727e+09,2.351639e+08,5.257615e+09,4.935002e+09,3.226130e+08,...,2327631,2386971,2337064,2377476,906997,907022,2327338,2387505,Health Care,2026-04-17
2,2026-04-17,400,2026-04-17 17:49:00.000,2026-04-17 20:00:03.000,3.628813e+09,3.348551e+09,2.802626e+08,3.508594e+09,3.468769e+09,3.982492e+07,...,1664697,1710975,1667665,1707898,642608,642239,1664923,1710994,Financials,2026-04-17
3,2026-04-17,254,2026-04-17 17:49:00.000,2026-04-17 20:00:03.000,6.891307e+09,7.705254e+09,-8.139466e+08,6.798269e+09,7.798292e+09,-1.000023e+09,...,2044314,2185789,2048516,2181537,899087,906282,2042037,2188224,Industrials,2026-04-17
4,2026-04-17,95,2026-04-17 17:49:00.000,2026-04-17 20:00:03.000,9.425974e+08,8.547336e+08,8.786380e+07,8.905020e+08,9.068289e+08,-1.632693e+07,...,425774,439419,426889,438271,139356,138415,425950,439297,Real Estate,2026-04-17
5,2026-04-17,31,2026-04-17 17:49:00.000,2026-04-17 20:00:03.000,1.173034e+09,1.357041e+09,-1.840070e+08,1.223484e+09,1.306590e+09,-8.310530e+07,...,268711,272451,270273,270889,133141,133891,268175,273000,Utilities,2026-04-17
6,2026-04-17,75,2026-04-17 17:56:00.000,2026-04-17 20:00:03.000,1.091119e+09,9.380856e+08,1.530335e+08,1.077376e+09,9.518287e+08,1.255471e+08,...,544386,565929,544143,566154,227303,228566,544407,565962,Communication Services,2026-04-17
7,2026-04-17,103,2026-04-17 19:15:00.000,2026-04-17 20:00:03.000,2.335341e+09,2.407448e+09,-7.210764e+07,2.326497e+09,2.416292e+09,-8.979531e+07,...,1036937,1033662,1035994,1034582,373634,373616,1037119,1033545,Energy,2026-04-17
8,2026-04-17,190,2026-04-17 19:51:00.000,2026-04-17 20:00:03.000,2.560485e+09,2.512370e+09,4.811497e+07,2.528073e+09,2.544781e+09,-1.670739e+07,...,1240603,1291506,1240113,1291935,497608,498246,1241493,1290736,Consumer Discretionary,2026-04-17
9,2026-04-17,81,2026-04-17 19:59:00.000,2026-04-17 20:00:03.000,1.660019e+09,1.660478e+09,-4.583130e+05,1.639808e+09,1.680689e+09,-4.088080e+07,...,775098,807819,773288,809618,303039,302736,775315,807646,Materials,2026-04-17

In [5]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r2k_daily_v1_2_1", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-17,322,2024-01-17 16:05:00.000,2024-01-17 20:00:03.000,1.161016e+09,1.118088e+09,42928300.29,1.164022e+09,1.115082e+09,48939768.79,...,701433,691620,701105,691895,241937,240515,701550,691673,Financials,2024-01-17
1,2024-01-17,54,2024-01-17 16:21:00.000,2024-01-17 20:00:03.000,3.050300e+08,3.311925e+08,-26162495.64,3.189133e+08,3.173092e+08,1604106.50,...,140805,141033,141022,140812,55529,55495,140841,141028,Consumer Staples,2024-01-17
2,2024-01-17,29,2024-01-17 16:21:00.000,2024-01-17 20:00:03.000,1.785398e+08,1.999402e+08,-21400392.57,1.758957e+08,2.025842e+08,-26688546.39,...,82056,79140,81966,79229,30699,30965,82074,79139,Utilities,2024-01-17
3,2024-01-17,89,2024-01-17 17:29:00.000,2024-01-17 20:00:03.000,8.534753e+08,9.150495e+08,-61574190.94,8.680275e+08,9.004973e+08,-32469808.56,...,454428,452631,454117,452933,140478,139893,454409,452725,Energy,2024-01-17
4,2024-01-17,237,2024-01-17 18:43:00.000,2024-01-17 20:00:03.000,1.267269e+09,1.282299e+09,-15030282.93,1.279987e+09,1.269581e+09,10405570.46,...,774317,760535,768418,766395,271215,270840,774378,760597,Industrials,2024-01-17
5,2024-01-17,184,2024-01-17 19:01:00.000,2024-01-17 20:00:03.000,1.263747e+09,1.258105e+09,5642347.91,1.265117e+09,1.256736e+09,8380895.23,...,669981,667062,670094,666923,231657,229568,670231,666913,Consumer Discretionary,2024-01-17
6,2024-01-17,86,2024-01-17 19:01:00.000,2024-01-17 20:00:03.000,5.400482e+08,5.590132e+08,-18964978.34,5.594155e+08,5.396459e+08,19769602.15,...,330774,327962,330163,328558,92733,93510,330851,327947,Real Estate,2024-01-17
7,2024-01-17,182,2024-01-17 19:02:00.000,2024-01-17 20:00:03.000,2.532456e+09,2.615706e+09,-83250394.23,2.542546e+09,2.605616e+09,-63069541.31,...,1054738,1044596,1046028,1053284,380183,377621,1055066,1044363,Information Technology,2024-01-17
8,2024-01-17,62,2024-01-17 19:14:00.000,2024-01-17 20:00:03.000,2.256946e+08,2.184505e+08,7244042.47,2.321673e+08,2.119778e+08,20189576.38,...,211188,203926,210755,204352,64611,63745,211171,203986,Communication Services,2024-01-17
9,2024-01-17,321,2024-01-17 19:36:00.000,2024-01-17 20:00:03.000,1.807003e+09,1.817663e+09,-10660477.23,1.817980e+09,1.806686e+09,11293513.36,...,1236557,1211455,1238347,1209566,413883,413399,1236453,1211771,Health Care,2024-01-17

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r2k_daily_v1_2_1", target_location="./data", asof_date='2025-03-07')

Downloading using native python implementation for xtech_us_equity_sector_flow_r2k_daily_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_equity_sector_flow_r2k_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r2k_daily_v1_2_1", target_location="./data")