In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r3k_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2025-12-05,546,2025-12-05 16:55:00.000,2025-12-05 20:00:03.000,2.513182e+10,2.394983e+10,None,2.606038e+10,2.302127e+10,None,...,4354454,4493945,4348504,4499775,1798766,1807035,4358190,4490542,Financials,2025-12-05
1,2025-12-05,136,2025-12-05 19:03:00.000,2025-12-05 20:00:03.000,5.813765e+09,5.778557e+09,None,5.873699e+09,5.718623e+09,None,...,1533381,1575572,1533931,1574993,544136,548578,1535915,1573126,Energy,2025-12-05
2,2025-12-05,133,2025-12-05 19:47:00.000,2025-12-05 20:00:03.000,5.788178e+09,6.505426e+09,None,6.104978e+09,6.188626e+09,None,...,1499088,1536813,1496010,1539871,577878,580827,1498562,1537422,Materials,2025-12-05
3,2025-12-05,418,2025-12-05 19:56:00.000,2025-12-05 20:00:03.000,2.257600e+10,2.212052e+10,None,2.307683e+10,2.161969e+10,None,...,4172581,4335965,4174154,4334217,1911756,1923163,4178037,4330778,Industrials,2025-12-05
4,2025-12-05,71,2025-12-05 19:57:00.000,2025-12-05 20:00:03.000,4.994387e+09,5.560691e+09,None,5.200789e+09,5.354289e+09,None,...,933909,974109,930932,977078,390087,393929,932755,975306,Utilities,2025-12-05
5,2025-12-05,469,2025-12-05 19:59:00.000,2025-12-05 20:00:03.000,1.885035e+10,1.837058e+10,None,1.930283e+10,1.791809e+10,None,...,3989343,4087533,3992717,4084039,1689931,1705385,3988346,4088844,Health Care,2025-12-05
6,2025-12-05,122,2025-12-05 20:00:00.000,2025-12-05 20:00:03.000,2.844748e+10,2.675445e+10,None,2.759253e+10,2.760940e+10,None,...,3500773,3659666,3446637,3713774,1481745,1482778,3512157,3648357,Communication Services,2025-12-05
7,2025-12-05,311,2025-12-05 20:00:00.000,2025-12-05 20:00:03.000,3.376461e+10,2.938765e+10,None,3.387605e+10,2.927621e+10,None,...,4523052,4472970,4467640,4528306,1976431,1984205,4541075,4455138,Consumer Discretionary,2025-12-05
8,2025-12-05,118,2025-12-05 20:00:00.000,2025-12-05 20:00:03.000,1.013490e+10,9.386906e+09,None,9.813728e+09,9.708080e+09,None,...,1827094,1759423,1792072,1794430,692291,691951,1827839,1758748,Consumer Staples,2025-12-05
9,2025-12-05,339,2025-12-05 20:00:00.000,2025-12-05 20:00:03.000,7.077903e+10,6.402313e+10,None,7.028063e+10,6.452153e+10,None,...,8961631,8711719,8731914,8941351,3962294,3972571,8986389,8687170,Information Technology,2025-12-05

In [ ]:
df = Unifier.get_dataframe(name="xtech_us_equity_sector_flow_r3k_daily_v1_2_1", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-22,532,2024-01-22 18:18:00.000,2024-01-22 20:00:03.000,1.942283e+10,1.802801e+10,None,1.935029e+10,1.810055e+10,None,...,3300399,3135789,3273862,3097607,1260502,1257134,2999363,2694827,Financials,2024-01-22
1,2024-01-22,532,2024-01-22 19:00:00.000,2024-01-22 20:00:03.000,1.711985e+10,1.692441e+10,None,1.738679e+10,1.665747e+10,None,...,3211752,3133837,3193933,3072646,1366027,1362572,2941165,2664689,Health Care,2024-01-22
2,2024-01-22,74,2024-01-22 19:00:00.000,2024-01-22 20:00:03.000,2.602825e+09,3.160333e+09,None,2.358919e+09,3.404238e+09,None,...,538136,729226,521055,736460,209880,211278,335547,808879,Utilities,2024-01-22
3,2024-01-22,165,2024-01-22 19:06:00.000,2024-01-22 20:00:03.000,4.171689e+09,6.248162e+09,None,4.104794e+09,6.315057e+09,None,...,956042,1035188,939767,1025355,363444,364678,713513,957015,Real Estate,2024-01-22
4,2024-01-22,120,2024-01-22 19:38:00.000,2024-01-22 20:00:03.000,7.977639e+09,8.619007e+09,None,7.624626e+09,8.972020e+09,None,...,1230615,1270775,1199855,1279353,500202,502252,997680,1293146,Consumer Staples,2024-01-22
5,2024-01-22,348,2024-01-22 19:44:00.000,2024-01-22 20:00:03.000,2.784324e+10,2.564688e+10,None,2.738294e+10,2.610718e+10,None,...,3705932,3468007,3615730,3485629,1523510,1520147,3174290,3398840,Consumer Discretionary,2024-01-22
6,2024-01-22,142,2024-01-22 19:54:00.000,2024-01-22 20:00:03.000,7.082024e+09,5.915291e+09,None,6.968598e+09,6.028717e+09,None,...,1251024,1182183,1239877,1153924,444995,441574,1059663,893838,Energy,2024-01-22
7,2024-01-22,131,2024-01-22 19:56:00.000,2024-01-22 20:00:03.000,4.113036e+09,3.764751e+09,None,4.206045e+09,3.671743e+09,None,...,833634,749432,836915,729750,312162,310602,786217,598748,Materials,2024-01-22
8,2024-01-22,125,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1.144877e+10,1.164656e+10,None,1.109863e+10,1.199670e+10,None,...,1369161,1401711,1328423,1388389,566478,567684,996838,1295107,Communication Services,2024-01-22
9,2024-01-22,442,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1.457303e+10,1.491373e+10,None,1.459866e+10,1.488810e+10,None,...,2894746,2814117,2867727,2773169,1194387,1186440,2613085,2503154,Industrials,2024-01-22

## Download data file for a specific date using asof_date

In [5]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r3k_daily_v1_2_1", target_location="./data", asof_date='2025-03-06')

Downloading using native python implementation for xtech_us_equity_sector_flow_r3k_daily_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_equity_sector_flow_r3k_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_sector_flow_r3k_daily_v1_2_1", target_location="./data")