In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name="xtech_us_equity_options_flow_daily_v2_4", asof_date='2024-01-31', limit=10)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 14:09:00.000 UTC,ABCB,ABCB,RegularMkt,EQT,Call,20,10,...,0,0,0,3,10,0.755000,0.0000,0,0.7911,2023-04-19
1,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 16:07:00.000 UTC,ABCB,ABCB,RegularMkt,EQT,Put,21,7,...,0,0,0,1,20,2.900000,0.0000,0,1.3720,2023-04-19
2,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 16:53:00.000 UTC,ABCB,ABCB,RegularMkt,EQT,Put,19,5,...,0,0,0,1,1,5.300000,0.0000,0,0.0000,2023-04-19
3,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 18:01:00.000 UTC,ABCB,ABCB,RegularMkt,EQT,Put,21,4,...,0,1,0,0,0,0.000000,0.0123,0,0.0000,2023-04-19
4,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 17:29:00.000 UTC,ACA,ACA,RegularMkt,EQT,Call,17,11,...,0,0,0,1,1,3.500000,0.0000,0,0.1809,2023-04-19
5,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 15:49:00.000 UTC,ACCD,ACCD,RegularMkt,EQT,Call,21,4,...,0,0,0,1,1,0.300000,0.0000,0,0.0055,2023-04-19
6,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 17:53:00.000 UTC,ACCD,ACCD,RegularMkt,EQT,Call,19,5,...,0,0,0,2,3,0.133333,0.0000,0,0.0229,2023-04-19
7,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 19:32:00.000 UTC,ACCD,ACCD,RegularMkt,EQT,Call,19,1,...,0,0,0,31,54,1.903704,0.0000,0,2.7124,2023-04-19
8,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 13:31:00.000 UTC,ADN,ADN,RegularMkt,EQT,Put,16,6,...,0,1,0,0,0,0.000000,0.0040,0,0.0000,2023-04-19
9,2023-04-19 20:15:03.000 UTC,2023-04-19,2023-04-19 15:50:00.000 UTC,ADN,ADN,RegularMkt,EQT,Put,19,5,...,0,1,0,0,0,0.000000,0.0002,0,0.0000,2023-04-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily_v2_4', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 18:32:00.000 UTC,AAN,AAN,RegularMkt,EQT,Call,15,3,...,0,1,0,0,0,0.000000,0.182355,0,0.000000,2024-01-31
1,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:05:00.000 UTC,AAN,AAN,RegularMkt,EQT,Put,21,6,...,0,0,0,1,10,4.600000,0.000000,0,0.164217,2024-01-31
2,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:07:00.000 UTC,AAN,AAN,RegularMkt,EQT,Put,15,3,...,0,1,0,1,2,0.550000,0.109742,0,0.027617,2024-01-31
3,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:39:00.000 UTC,AAN,AAN,RegularMkt,EQT,Call,20,9,...,0,0,0,1,1,1.000000,0.000000,0,0.031859,2024-01-31
4,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 17:03:00.000 UTC,ABEO,ABEO,RegularMkt,EQT,Call,15,3,...,0,3,0,0,0,0.000000,0.079559,0,0.000000,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:33:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Put,9,2,...,0,6,0,2,51,0.469804,0.090928,0,0.202625,2024-01-31
96,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:39:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Put,15,3,...,0,7,0,3,11,0.611818,0.225578,0,0.124971,2024-01-31
97,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:41:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Call,1,3,...,0,5,0,4,5,0.308000,0.073850,0,0.052348,2024-01-31
98,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:42:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Call,21,6,...,0,44,0,10,156,0.357628,26.302694,0,3.476745,2024-01-31
99,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:43:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Call,16,1,...,0,0,0,4,14,0.280714,0.000000,0,0.831380,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily_v2_4', key='SPXW', asof_date='2024-01-01', limit=10)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 05:09:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,21,7,...,0,0,0,1,30,43.400002,0.000000,0,147.304802,2023-04-26
1,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 05:27:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Call,1,5,...,0,1,0,0,0,0.000000,0.349148,0,0.000000,2023-04-26
2,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 05:58:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Call,23,5,...,0,2,0,0,0,0.000000,48.373801,0,0.000000,2023-04-26
3,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 06:16:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,31,8,...,0,0,0,3,3,80.800003,0.000000,0,22.332750,2023-04-26
4,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 06:16:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Call,16,6,...,0,2,0,0,0,0.000000,28.250101,0,0.000000,2023-04-26
5,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 07:23:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,2,6,...,0,1,0,0,0,0.000000,13.264175,0,0.000000,2023-04-26
6,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 07:24:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,31,7,...,0,1,0,0,0,0.000000,2.541960,0,0.000000,2023-04-26
7,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 07:24:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,31,7,...,0,1,0,0,0,0.000000,2.167580,0,0.000000,2023-04-26
8,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 07:34:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,19,5,...,0,1,0,0,0,0.000000,27.555001,0,0.000000,2023-04-26
9,2023-04-26 20:15:03.000 UTC,2023-04-26,2023-04-26 07:34:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Call,16,6,...,0,1,0,0,0,0.000000,43.265880,0,0.000000,2023-04-26

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily_v2_4',key='SPX', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 08:14:00.000 UTC,SPX,SPX,PreMkt,EQT,Put,16,8,...,0,1,0,0,0,0.000000,1.408450,0,0.000000,2024-01-23
1,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 08:14:00.000 UTC,SPX,SPX,PreMkt,EQT,Put,18,10,...,0,0,0,1,10,0.900000,0.000000,0,1.567060,2024-01-23
2,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 08:16:00.000 UTC,SPX,SPX,PreMkt,EQT,Put,19,4,...,0,1,0,0,0,0.000000,0.164014,0,0.000000,2024-01-23
3,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 08:17:00.000 UTC,SPX,SPX,PreMkt,EQT,Put,15,3,...,0,1,0,0,0,0.000000,0.279044,0,0.000000,2024-01-23
4,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 08:18:00.000 UTC,SPX,SPX,PreMkt,EQT,Put,15,3,...,0,1,0,0,0,0.000000,0.389742,0,0.000000,2024-01-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 14:59:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,16,8,...,0,1,0,0,0,0.000000,11.603800,0,0.000000,2024-01-23
96,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 14:59:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,16,8,...,0,0,0,1,2,54.799999,0.000000,0,22.796200,2024-01-23
97,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 14:59:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,19,7,...,0,12,0,8,11,103.881817,227.987600,0,131.893997,2024-01-23
98,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 15:00:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,21,6,...,0,5,0,0,0,0.000000,59.368100,0,0.000000,2024-01-23
99,2024-01-23 21:15:03.000 UTC,2024-01-23,2024-01-23 15:00:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,17,5,...,0,1,0,0,0,0.000000,2.428440,0,0.000000,2024-01-23

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_equity_options_flow_daily_v2_4", target_location="./data", asof_date='2014-01-31')

Starting native python replication for xtech_us_equity_options_flow_daily_v2_3 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_options_flow_daily_v2_3. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_options_flow_daily_v2_4", target_location="./data")

Starting native python replication for xtech_us_equity_options_flow_daily_v2_3 (parallel)...
Found 3095 files to download.