In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_equity_options_flow_daily_v2_3", asof_date='2024-01-31', limit=10)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:11:00.000 UTC,NDX,NDX,RegularMkt,EQT,Put,19,10,...,0,1,0,0,0,0.00,0.858,0.000,0.000,2018-08-06
1,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:05:00.000 UTC,NDX,NDX,RegularMkt,EQT,Put,21,9,...,0,1,0,0,0,0.00,1.113,0.000,0.000,2018-08-06
2,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:05:00.000 UTC,NDX,NDX,RegularMkt,EQT,Put,21,9,...,0,1,0,0,0,0.00,0.408,0.000,0.000,2018-08-06
3,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:05:00.000 UTC,NDX,NDX,RegularMkt,EQT,Put,19,10,...,0,1,0,0,0,0.00,2.262,0.000,0.000,2018-08-06
4,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:04:00.000 UTC,RUT,RUT,RegularMkt,EQT,Call,19,10,...,0,1,0,0,0,0.00,1.555,0.000,0.000,2018-08-06
5,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:01:00.000 UTC,XLY,XLY,RegularMkt,EQT,Call,21,12,...,0,2,0,0,0,0.00,1.140,0.000,0.000,2018-08-06
6,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:01:00.000 UTC,RUT,RUT,RegularMkt,EQT,Put,19,10,...,2,0,1,0,0,0.00,0.000,4.486,0.000,2018-08-06
7,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:07:00.000 UTC,NDX,NDX,RegularMkt,EQT,Put,19,10,...,0,3,0,0,0,0.00,2.527,0.000,0.000,2018-08-06
8,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:01:00.000 UTC,ECL,ECL,RegularMkt,EQT,Put,14,9,...,0,0,0,1,12,2.13,0.000,0.000,2.352,2018-08-06
9,2018-08-06 20:52:03.000 UTC,2018-08-06,2018-08-06 20:01:00.000 UTC,ECL,ECL,RegularMkt,EQT,Put,14,9,...,0,1,0,0,0,0.00,2.268,0.000,0.000,2018-08-06

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily_v2_3', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:04:00.000 UTC,UNP,UNP,RegularMkt,EQT,Put,20,9,...,0,8,0,0,0,0.00000,42.910024,0,0.000000,2024-01-31
1,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:01:00.000 UTC,UVIX,UVIX,RegularMkt,EQT,Put,19,4,...,0,0,0,1,27,0.15000,0.000000,0,0.152970,2024-01-31
2,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:02:00.000 UTC,ABAT,ABAT,RegularMkt,EQT,Put,16,2,...,0,0,0,1,1,0.15000,0.000000,0,0.002142,2024-01-31
3,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 19:38:00.000 UTC,CVE,CVE,RegularMkt,EQT,Put,9,2,...,0,2,0,2,5,0.21000,0.107182,0,0.048897,2024-01-31
4,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 20:14:00.000 UTC,UAL,UAL,RegularMkt,EQT,Put,2,2,...,0,5,0,28,197,0.08599,1.091516,0,1.609006,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:32:00.000 UTC,ADAP,ADAP,RegularMkt,EQT,Put,16,2,...,11,0,2,0,0,0.00000,0.000000,0,0.000000,2024-01-31
96,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 20:46:00.000 UTC,META,META,RegularMkt,EQT,Call,16,2,...,0,26,0,9,50,1.08340,7.880575,0,5.333355,2024-01-31
97,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 15:50:00.000 UTC,CBRE,CBRE,RegularMkt,EQT,Put,16,2,...,0,1,0,2,25,0.40000,0.185172,0,0.925862,2024-01-31
98,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:08:00.000 UTC,DUK,DUK,RegularMkt,EQT,Put,21,6,...,0,1,0,0,0,0.00000,0.130831,0,0.000000,2024-01-31
99,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 20:46:00.000 UTC,FSLR,FSLR,RegularMkt,EQT,Put,19,4,...,0,0,0,2,2,10.82500,0.000000,0,0.532794,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily_v2_3', key='SPXW', asof_date='2024-01-01', limit=10)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:11:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Call,18,7,...,0,1,0,0,0,0,0.024,0,0,2018-07-17
1,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:09:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,23,7,...,0,1,0,0,0,0,2.000,0,0,2018-07-17
2,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:07:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,21,9,...,0,1,0,0,0,0,11.298,0,0,2018-07-17
3,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:07:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,28,9,...,0,1,0,0,0,0,25.346,0,0,2018-07-17
4,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:07:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,21,9,...,0,1,0,0,0,0,4.880,0,0,2018-07-17
5,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:07:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,21,9,...,0,1,0,0,0,0,5.073,0,0,2018-07-17
6,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:07:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,21,9,...,0,1,0,0,0,0,3.458,0,0,2018-07-17
7,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:07:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,19,10,...,0,1,0,0,0,0,1.992,0,0,2018-07-17
8,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:07:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,21,9,...,0,2,0,0,0,0,7.024,0,0,2018-07-17
9,2018-07-17 20:56:03.000 UTC,2018-07-17,2018-07-17 20:07:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,21,9,...,0,1,0,0,0,0,3.234,0,0,2018-07-17

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily_v2_3',key='SPX', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 20:09:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,19,7,...,0,5,0,1,1,80.100000,230.53840,0.0,10.340200,2024-01-31
1,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:02:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,18,10,...,0,2,0,0,0,0.000000,29.99990,0.0,0.000000,2024-01-31
2,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:15:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,19,12,...,0,0,0,2,31,317.072903,0.00000,0.0,759.898300,2024-01-31
3,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:23:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,17,5,...,0,1,0,1,1,62.500000,8.55177,0.0,8.517150,2024-01-31
4,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:26:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,20,12,...,0,0,0,6,2250,18.820000,0.00000,0.0,7271.572500,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:17:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,19,4,...,0,0,0,1,1,9.900000,0.00000,0.0,3.701110,2024-01-31
96,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 19:15:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,19,4,...,0,1,0,1,27,19.300000,31.18256,0.0,103.105980,2024-01-31
97,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 20:58:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,19,4,...,0,0,0,7,14,52.074286,0.00000,0.0,113.046660,2024-01-31
98,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:35:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,17,5,...,0,2,0,0,0,0.000000,21.07260,0.0,0.000000,2024-01-31
99,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:21:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,0,0,2,21,1.050000,0.00000,0.0,4.930554,2024-01-31

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="xtech_us_equity_options_flow_daily_v2_3", target_location="./data", asof_date='2014-01-31')

Starting native python replication for xtech_us_equity_options_flow_daily_v2_3 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_options_flow_daily_v2_3. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_options_flow_daily_v2_3", target_location="./data")

Starting native python replication for xtech_us_equity_options_flow_daily_v2_3 (parallel)...
Found 3095 files to download.