In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name="xtech_us_equity_options_flow_daily", asof_date='2024-01-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 13:31:00.000,AAOI,AAOI,RegularMkt,EQT,Put,20,11,...,0,0,0,1,1,0.560000,0.0000,0,0.0084,2020-10-29
1,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 13:31:00.000,ACIA,ACIA,RegularMkt,EQT,Put,19,2,...,0,1,0,0,0,0.000000,0.0816,0,0.0000,2020-10-29
2,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 13:31:00.000,ACIA,ACIA,RegularMkt,EQT,Put,19,2,...,0,1,0,0,0,0.000000,0.1336,0,0.0000,2020-10-29
3,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 13:31:00.000,ACIA,ACIA,RegularMkt,EQT,Call,21,5,...,0,0,0,1,1,1.650000,0.0000,0,0.1921,2020-10-29
4,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 19:40:00.000,ACMR,ACMR,RegularMkt,EQT,Call,20,11,...,0,4,0,16,28,2.285750,0.2628,0,1.9313,2020-10-29
5,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 15:21:00.000,ACMR,ACMR,RegularMkt,EQT,Call,20,11,...,0,1,0,4,4,0.780000,0.0381,0,0.1553,2020-10-29
6,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 13:31:00.000,ACMR,ACMR,RegularMkt,EQT,Call,20,11,...,0,0,0,1,1,0.850000,0.0000,0,0.0339,2020-10-29
7,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 19:17:00.000,ADS,ADS,RegularMkt,EQT,Call,30,10,...,0,0,0,5,6,4.326000,0.0000,0,0.0377,2020-10-29
8,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 19:39:00.000,ADS,ADS,RegularMkt,EQT,Call,30,10,...,0,2,0,6,43,0.470000,0.2590,0,0.5585,2020-10-29
9,2020-10-29,2020-10-29 23:30:30.000,2020-10-29 18:42:00.000,ADS,ADS,RegularMkt,EQT,Call,15,1,...,0,0,0,3,5,0.666667,0.0000,0,0.2191,2020-10-29

## Retrieve data for a specific date range using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:34:00.000,AMAM,AMAM,RegularMkt,EQT,Put,19,7,...,0,4,0,0,0,0.000000,0.254595,0,0.000000,2024-01-31
1,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 14:31:00.000,AMKR,AMKR,RegularMkt,EQT,Call,16,2,...,0,1,0,0,0,0.000000,0.027773,0,0.000000,2024-01-31
2,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 14:31:00.000,AMKR,AMKR,RegularMkt,EQT,Call,21,6,...,0,1,0,0,0,0.000000,0.082930,0,0.000000,2024-01-31
3,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:52:00.000,APO,APO,RegularMkt,EQT,Put,2,2,...,0,3,0,3,12,0.083333,0.301120,0,0.223959,2024-01-31
4,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:14:00.000,APO,APO,RegularMkt,EQT,Put,9,2,...,0,2,0,0,0,0.000000,0.076436,0,0.000000,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 18:13:00.000,CAN,CAN,RegularMkt,EQT,Put,16,2,...,0,2,0,1,1,0.200000,0.017710,0,0.000863,2024-01-31
96,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 15:41:00.000,CAN,CAN,RegularMkt,EQT,Call,23,2,...,0,2,0,0,0,0.000000,0.005333,0,0.000000,2024-01-31
97,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:52:00.000,CAN,CAN,RegularMkt,EQT,Call,15,3,...,0,10,0,7,45,0.074545,0.164287,0,0.087620,2024-01-31
98,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 14:31:00.000,CAN,CAN,RegularMkt,EQT,Call,15,3,...,0,1,0,0,0,0.000000,0.001639,0,0.000000,2024-01-31
99,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 16:02:00.000,CAN,CAN,RegularMkt,EQT,Call,17,1,...,0,1,0,1,1,0.375000,0.043880,0,0.004546,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 17:56:00.000,AAPL,AAPL,RegularMkt,EQT,Call,30,10,...,0,6,0,8,57,48.352857,0.0433,0.0000,0.0000,2020-10-27
1,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 20:00:00.000,AAPL,AAPL,RegularMkt,EQT,Put,30,10,...,0,17,0,23,93,0.009545,0.6314,0.0000,0.2220,2020-10-27
2,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 19:59:00.000,AAPL,AAPL,RegularMkt,EQT,Put,30,10,...,0,19,0,1,1,0.003077,0.2550,0.0000,0.0042,2020-10-27
3,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 19:50:00.000,AAPL,AAPL,RegularMkt,EQT,Put,30,10,...,0,16,0,17,74,0.019600,0.3204,0.0000,0.2515,2020-10-27
4,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 19:49:00.000,AAPL,AAPL,RegularMkt,EQT,Put,30,10,...,0,30,0,18,105,0.021622,0.7637,0.0000,0.5742,2020-10-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 19:52:00.000,AAPL,AAPL,RegularMkt,EQT,Put,6,11,...,63,68,4,68,168,3.149726,22.3911,5.1804,13.7339,2020-10-27
96,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 20:00:00.000,AAPL,AAPL,RegularMkt,EQT,Call,6,11,...,78,237,23,238,753,1.895261,56.6665,6.3009,60.7831,2020-10-27
97,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 20:00:00.000,AAPL,AAPL,RegularMkt,EQT,Call,6,11,...,342,887,95,1100,4148,2.217740,256.7706,27.0437,327.4334,2020-10-27
98,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 19:59:00.000,AAPL,AAPL,RegularMkt,EQT,Put,6,11,...,1,58,1,56,286,3.178211,15.3656,0.0791,22.6356,2020-10-27
99,2020-10-27,2020-10-27 23:30:30.000,2020-10-27 20:00:00.000,AAPL,AAPL,RegularMkt,EQT,Call,6,11,...,40,230,20,272,754,1.493285,50.9988,3.0953,57.9115,2020-10-27

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [10]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_daily',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:49:00.000,AAPL,AAPL,RegularMkt,EQT,Put,2,2,...,0,10,0,10,74,0.002500,0.032027,0.000000,0.095024,2024-01-29
1,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:16:00.000,AAPL,AAPL,RegularMkt,EQT,Put,2,2,...,0,11,0,3,4,0.006667,0.340093,0.000000,0.012026,2024-01-29
2,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:56:00.000,AAPL,AAPL,RegularMkt,EQT,Put,2,2,...,0,9,0,9,17,0.013125,0.089563,0.000000,0.067847,2024-01-29
3,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 21:00:00.000,AAPL,AAPL,RegularMkt,EQT,Put,2,2,...,0,59,0,41,1190,0.020667,19.729136,0.000000,7.362240,2024-01-29
4,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:59:00.000,AAPL,AAPL,RegularMkt,EQT,Put,2,2,...,0,96,0,92,962,0.033187,8.483006,0.000000,10.237000,2024-01-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:59:00.000,AAPL,AAPL,RegularMkt,EQT,Call,23,2,...,0,16,0,1,1,0.842000,3.827092,0.000000,0.131838,2024-01-29
96,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:57:00.000,AAPL,AAPL,RegularMkt,EQT,Put,23,2,...,0,71,0,78,307,0.824583,33.798369,0.000000,39.839148,2024-01-29
97,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:53:00.000,AAPL,AAPL,RegularMkt,EQT,Put,23,2,...,0,64,0,90,373,1.609991,55.043680,0.000000,64.646474,2024-01-29
98,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:58:00.000,AAPL,AAPL,RegularMkt,EQT,Call,23,2,...,0,86,0,28,167,1.458933,51.193075,0.000000,33.649168,2024-01-29
99,2024-01-29,2024-01-29 23:30:30.000,2024-01-29 20:59:00.000,AAPL,AAPL,RegularMkt,EQT,Put,23,2,...,1,64,1,55,157,2.324120,41.570751,0.202178,31.634215,2024-01-29

## Download data file for a specific date using asof_date

In [11]:
Unifier.replicate(name="xtech_us_equity_options_flow_daily", target_location="./data", asof_date='2026-01-12')

Starting native python replication for xtech_us_equity_options_flow_daily (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_options_flow_daily. Downloaded 1 files.