In [ ]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [ ]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name="xtech_us_equity_options_flow_1min_v2_4", asof_date='2024-01-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Call,17,1,...,0,1,0,0,0,0.00,2.100,0.00,0.000,2014-05-15
1,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Call,17,5,...,0,1,0,0,0,0.00,0.004,0.00,0.000,2014-05-15
2,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Call,21,6,...,0,1,0,0,0,0.00,0.096,0.00,0.000,2014-05-15
3,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Call,21,6,...,0,0,0,1,12,0.72,0.000,0.00,0.180,2014-05-15
4,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Call,17,5,...,0,0,0,2,50,3.51,0.000,0.00,0.000,2014-05-15
5,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Put,17,1,...,10,0,1,0,0,0.00,0.000,0.37,0.000,2014-05-15
6,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Put,19,7,...,0,1,0,0,0,0.00,0.024,0.00,0.000,2014-05-15
7,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Call,19,7,...,0,0,0,2,50,3.51,0.000,0.00,0.050,2014-05-15
8,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Put,21,6,...,0,0,0,23,318,3.50,0.000,0.00,0.000,2014-05-15
9,2014-05-15,2014-05-15 23:30:30.000,2014-05-15 13:31:00.000,AA,AA,RegularMkt,EQT,Put,21,6,...,0,0,0,1,23,0.21,0.000,0.00,0.345,2014-05-15

## Retrieve data for a specific date range using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_1min_v2_4', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 05:51:00.000,SPXW,SPXW,NextDay,EQT,Call,31,1,...,0,0,0,1,10,3.70,0.000000,0,7.022600,2024-01-31
1,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 05:52:00.000,SPXW,SPXW,NextDay,EQT,Put,31,1,...,0,1,0,0,0,0.00,3.138540,0,0.000000,2024-01-31
2,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 05:52:00.000,SPXW,SPXW,NextDay,EQT,Call,31,1,...,0,1,0,0,0,0.00,1.404532,0,0.000000,2024-01-31
3,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 05:52:00.000,SPXW,SPXW,NextDay,EQT,Put,8,2,...,0,0,0,1,1,54.65,0.000000,0,2.989100,2024-01-31
4,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 05:52:00.000,SPXW,SPXW,NextDay,EQT,Put,14,2,...,0,0,0,1,1,62.20,0.000000,0,3.882060,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 06:19:00.000,SPXW,SPXW,PreMkt,EQT,Call,31,1,...,0,1,0,0,0,0.00,1.085830,0,0.000000,2024-01-31
96,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 06:19:00.000,SPXW,SPXW,PreMkt,EQT,Put,31,1,...,0,0,0,1,1,12.97,0.000000,0,1.084450,2024-01-31
97,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 06:19:00.000,SPXW,SPXW,PreMkt,EQT,Call,31,1,...,0,1,0,0,0,0.00,0.987074,0,0.000000,2024-01-31
98,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 06:19:00.000,SPXW,SPXW,PreMkt,EQT,Put,31,1,...,0,0,0,1,1,26.86,0.000000,0,0.972553,2024-01-31
99,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 06:19:00.000,SPXW,SPXW,PreMkt,EQT,Call,31,1,...,0,3,0,0,0,0.00,8.038363,0,0.000000,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_1min_v2_4', key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:30:00.000,AAPL,AAPL,RegularMkt,EQT,Call,22,3,...,0,1,0,0,0,0.000000,1.890,0.0,0.000,2014-02-26
1,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Call,22,3,...,0,0,0,1,1,19.450000,0.000,0.0,0.464,2014-02-26
2,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Call,22,3,...,0,0,0,8,119,2.512941,0.000,0.0,44.068,2014-02-26
3,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,19,4,...,0,0,0,1,2,19.450000,0.000,0.0,1.580,2014-02-26
4,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Call,19,7,...,0,0,0,2,5,9.010000,0.000,0.0,4.935,2014-02-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,28,2,...,0,1,0,0,0,0.000000,0.252,0.0,0.000,2014-02-26
96,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,28,2,...,0,1,0,1,2,11.800000,0.101,0.0,0.202,2014-02-26
97,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,7,3,...,0,0,0,1,1,4.250000,0.000,0.0,0.367,2014-02-26
98,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,7,3,...,0,2,0,0,0,0.000000,0.156,0.0,0.000,2014-02-26
99,2014-02-26,2014-02-26 23:30:30.000,2014-02-26 13:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,28,2,...,0,6,0,0,0,0.000000,0.300,0.0,0.000,2014-02-26

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_equity_options_flow_1min_v2_4', key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Call,26,1,...,0,2,0,0,0,0.000000,0.006823,0,0.000000,2024-01-26
1,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,26,1,...,0,2,0,0,0,0.000000,0.021504,0,0.000000,2024-01-26
2,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Call,26,1,...,0,4,0,1,1,9.080000,0.078179,0,0.000000,2024-01-26
3,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,26,1,...,0,6,0,8,105,0.010000,0.423707,0,0.230663,2024-01-26
4,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Call,26,1,...,0,0,0,1,2,6.390000,0.000000,0,0.000000,2024-01-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,16,2,...,0,0,0,1,1,16.100000,0.000000,0,0.052506,2024-01-26
96,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Call,16,2,...,0,1,0,0,0,0.000000,0.053300,0,0.000000,2024-01-26
97,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,23,2,...,0,1,0,0,0,0.000000,0.021996,0,0.000000,2024-01-26
98,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,23,2,...,0,3,0,0,0,0.000000,0.542285,0,0.000000,2024-01-26
99,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 14:31:00.000,AAPL,AAPL,RegularMkt,EQT,Put,23,2,...,0,1,0,3,11,0.920909,0.115030,0,1.265330,2024-01-26

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_equity_options_flow_1min_v2_4", target_location="./data", asof_date='2026-01-12')

Starting native python replication for xtech_us_equity_options_flow_1min_v2_3 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_options_flow_1min_v2_3. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_options_flow_1min_v2_4", target_location="./data")