In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [2]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.17)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (3.0.0)
Requirement already satisfied: boto3 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (1.42.66)
Requirement already satisfied: botocore<1.43.0,>=1.42.66 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (1.42.66)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from botocore<1.43.0,>=1.42.66->boto3->unifier) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from botocore<1.43.0,>=1.42.66->boto3->unifier) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.66->boto3->unifier) (1.17.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.4.1)
Requirement already satisfied: tzdata in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_etf_options_flow_daily_v2_2", asof_date='2024-01-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 13:31:00.000,ARKW,ARKW,RegularMkt,EQT,Call,20,5,...,0,1,0,0,0,0.000000,0.0575,0,0.0000,2022-05-05
1,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 17:05:00.000,ARKW,ARKW,RegularMkt,EQT,Call,20,5,...,0,1,0,3,3,0.910000,0.0596,0,0.1366,2022-05-05
2,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 18:45:00.000,ARKW,ARKW,RegularMkt,EQT,Call,20,5,...,0,5,0,0,0,0.000000,0.0183,0,0.0000,2022-05-05
3,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 13:41:00.000,ARKW,ARKW,RegularMkt,EQT,Call,17,6,...,0,0,0,1,1,3.400000,0.0000,0,0.0914,2022-05-05
4,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 13:51:00.000,ARKW,ARKW,RegularMkt,EQT,Put,17,6,...,0,0,0,1,1,75.320000,0.0000,0,0.0000,2022-05-05
5,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 13:52:00.000,ARKW,ARKW,RegularMkt,EQT,Put,17,6,...,0,0,0,1,1,60.090000,0.0000,0,0.0000,2022-05-05
6,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 13:52:00.000,ARKW,ARKW,RegularMkt,EQT,Put,17,6,...,0,1,0,0,0,0.000000,0.0000,0,0.0000,2022-05-05
7,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 16:27:00.000,ARKW,ARKW,RegularMkt,EQT,Put,17,6,...,0,1,0,3,6,5.323333,0.0858,0,0.5057,2022-05-05
8,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 13:53:00.000,ARKW,ARKW,RegularMkt,EQT,Put,17,6,...,0,0,0,1,1,54.900000,0.0000,0,0.0000,2022-05-05
9,2022-05-05,2022-05-05 23:30:30.000,2022-05-05 17:22:00.000,ARKW,ARKW,RegularMkt,EQT,Call,17,6,...,0,1,0,2,4,1.130000,0.5558,0,0.2798,2022-05-05

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_daily_v2_2', back_to='2022-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 19:58:00.000,BITO,BITO,RegularMkt,EQT,Put,31,3,...,0,0,0,6,48,0.013333,0.0000,0.0,0.0312,2022-03-29
1,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 16:02:00.000,BITO,BITO,RegularMkt,EQT,Put,31,3,...,0,7,0,10,40,0.016154,0.1163,0.0,0.0614,2022-03-29
2,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 17:55:00.000,BITO,BITO,RegularMkt,EQT,Call,31,3,...,0,10,0,41,258,2.054246,0.1821,0.0,0.5096,2022-03-29
3,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 19:31:00.000,BITO,BITO,RegularMkt,EQT,Call,31,3,...,0,9,0,38,347,1.541376,0.3217,0.0,1.9354,2022-03-29
4,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 20:00:00.000,BITO,BITO,RegularMkt,EQT,Call,31,3,...,0,41,0,151,994,0.466921,1.0375,0.0,11.0672,2022-03-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 15:32:00.000,LABD,LABD,RegularMkt,EQT,Call,14,4,...,0,1,0,10,16,0.283333,0.0095,0.0,0.1872,2022-03-29
96,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 13:31:00.000,LABD,LABD,RegularMkt,EQT,Call,14,4,...,0,0,0,1,1,0.350000,0.0000,0.0,0.0124,2022-03-29
97,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 13:31:00.000,QQQM,QQQM,RegularMkt,EQT,Call,14,4,...,0,1,0,0,0,0.000000,0.1197,0.0,0.0000,2022-03-29
98,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 13:31:00.000,QQQM,QQQM,RegularMkt,EQT,Put,14,4,...,0,0,0,1,1,3.920000,0.0000,0.0,0.1275,2022-03-29
99,2022-03-29,2022-03-29 23:30:30.000,2022-03-29 13:31:00.000,QQQM,QQQM,RegularMkt,EQT,Put,20,5,...,0,1,0,0,0,0.000000,0.1480,0.0,0.0000,2022-03-29

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_daily_v2_2',key='KWEB', asof_date='2023-09-12', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 16:20:00.000,KWEB,KWEB,RegularMkt,EQT,Call,27,5,...,0,0,0,4,31,3.356667,0.0000,0.0000,0.0018,2022-05-26
1,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 19:59:00.000,KWEB,KWEB,RegularMkt,EQT,Call,27,5,...,0,94,0,158,1229,0.820511,2.8262,0.0000,7.5900,2022-05-26
2,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 19:57:00.000,KWEB,KWEB,RegularMkt,EQT,Put,27,5,...,0,34,0,104,1079,0.183947,1.4176,0.0000,7.4113,2022-05-26
3,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 20:00:00.000,KWEB,KWEB,RegularMkt,EQT,Call,27,5,...,4,56,1,147,1337,0.476776,3.1491,0.0292,10.1957,2022-05-26
4,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 19:59:00.000,KWEB,KWEB,RegularMkt,EQT,Put,27,5,...,0,55,0,57,531,0.201967,3.0953,0.0000,4.1218,2022-05-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 19:39:00.000,KWEB,KWEB,RegularMkt,EQT,Call,20,1,...,1,17,1,6,11,1.096818,6.4609,0.0883,0.9712,2022-05-26
96,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 16:59:00.000,KWEB,KWEB,RegularMkt,EQT,Put,27,5,...,0,2,0,7,19,0.008571,0.0025,0.0000,0.0143,2022-05-26
97,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 19:06:00.000,KWEB,KWEB,RegularMkt,EQT,Call,3,6,...,0,3,0,14,118,0.148889,0.0248,0.0000,1.0755,2022-05-26
98,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 13:39:00.000,KWEB,KWEB,RegularMkt,EQT,Call,1,7,...,0,0,0,1,100,3.200000,0.0000,0.0000,3.0300,2022-05-26
99,2022-05-26,2022-05-26 23:30:30.000,2022-05-26 18:38:00.000,KWEB,KWEB,RegularMkt,EQT,Call,15,7,...,0,13,0,5,74,1.612727,3.3316,0.0000,2.6614,2022-05-26

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_daily_v2_2',key='KWEB', back_to='2022-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 19:59:00.000,KWEB,KWEB,RegularMkt,EQT,Put,22,4,...,3,61,2,36,899,0.031098,1.2123,0.0054,1.8915,2022-04-22
1,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 19:47:00.000,KWEB,KWEB,RegularMkt,EQT,Call,22,4,...,0,23,0,62,383,0.230178,0.2883,0.0000,1.6353,2022-04-22
2,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 20:00:00.000,KWEB,KWEB,RegularMkt,EQT,Put,22,4,...,0,37,0,61,561,0.175214,1.1234,0.0000,2.3847,2022-04-22
3,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 20:00:00.000,KWEB,KWEB,RegularMkt,EQT,Put,22,4,...,0,53,0,51,170,0.289174,4.7424,0.0000,0.7076,2022-04-22
4,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 19:38:00.000,KWEB,KWEB,RegularMkt,EQT,Call,22,4,...,0,16,0,70,988,0.091369,0.4138,0.0000,2.8050,2022-04-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 19:33:00.000,KWEB,KWEB,RegularMkt,EQT,Put,20,5,...,0,8,0,19,32,0.296500,2.6247,0.0000,0.6027,2022-04-22
96,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 19:56:00.000,KWEB,KWEB,RegularMkt,EQT,Call,20,5,...,30,37,2,18,374,0.538237,13.7822,0.8820,10.8332,2022-04-22
97,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 19:56:00.000,KWEB,KWEB,RegularMkt,EQT,Call,20,5,...,0,32,0,14,58,0.503077,10.7017,0.0000,1.5846,2022-04-22
98,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 14:52:00.000,KWEB,KWEB,RegularMkt,EQT,Call,20,5,...,0,17,0,1,10,0.175000,8.6580,0.0000,0.1760,2022-04-22
99,2022-04-22,2022-04-22 23:30:30.000,2022-04-22 20:00:00.000,KWEB,KWEB,RegularMkt,EQT,Call,27,5,...,0,1,0,2,2,1.343333,0.0314,0.0000,0.0652,2022-04-22

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_etf_options_flow_daily_v2_2", target_location="./data", asof_date='2026-01-13')

Starting native python replication for xtech_us_etf_options_flow_daily_v2_2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_etf_options_flow_daily_v2_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_etf_options_flow_daily_v2_2", target_location="./data")