In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_etf_options_flow_with_isin_daily_v2_2", asof_date='2024-01-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:31:00.000,ARKW,US00214Q4010,ARKW,RegularMkt,EQT,Put,16,...,0,1,0,0,0,0.000000,0.0258,0,0.0000,2022-08-02
1,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:31:00.000,ARKW,US00214Q4010,ARKW,RegularMkt,EQT,Put,16,...,0,2,0,0,0,0.000000,0.3828,0,0.0000,2022-08-02
2,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:31:00.000,ARKW,US00214Q4010,ARKW,RegularMkt,EQT,Call,20,...,0,2,0,0,0,0.000000,0.6000,0,0.0000,2022-08-02
3,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 16:23:00.000,ARKW,US00214Q4010,ARKW,RegularMkt,EQT,Call,20,...,0,3,0,0,0,0.000000,1.0836,0,0.0000,2022-08-02
4,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:31:00.000,BIL,US78468R6633,BIL,RegularMkt,EQT,Call,16,...,0,0,0,4,5,0.536000,0.0000,0,0.2460,2022-08-02
5,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:31:00.000,BIL,US78468R6633,BIL,RegularMkt,EQT,Call,16,...,0,0,0,3,3,0.036667,0.0000,0,0.3918,2022-08-02
6,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:31:00.000,BIL,US78468R6633,BIL,RegularMkt,EQT,Call,21,...,0,0,0,1,1,0.520000,0.0000,0,0.0000,2022-08-02
7,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:31:00.000,BIL,US78468R6633,BIL,RegularMkt,EQT,Call,21,...,0,0,0,1,1,0.010000,0.0000,0,0.1730,2022-08-02
8,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:31:00.000,BNO,US91167Q1004,BNO,RegularMkt,EQT,Call,20,...,0,0,0,2,4,5.022500,0.0000,0,0.3236,2022-08-02
9,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 19:25:00.000,BOIL,US74347Y8701,BOIL,RegularMkt,EQT,Put,19,...,0,6,0,10,33,0.829675,0.3025,0,0.9363,2022-08-02

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_with_isin_daily_v2_2', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:55:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,2,...,0,7,0,1,1,0.002500,0.087012,0,0.002109,2024-01-31
1,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 22:21:00.000,BITO,US74347G4405,BITO,PreMkt,EQT,Call,2,...,0,26,0,34,2714,0.470023,18.996330,0,0.009421,2024-01-31
2,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 21:00:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,2,...,0,64,0,28,60,0.077027,4.069336,0,0.375383,2024-01-31
3,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 21:00:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,2,...,0,7,0,76,508,0.323133,0.263068,0,2.614173,2024-01-31
4,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 21:00:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,2,...,0,217,0,135,1208,0.109816,12.504043,0,7.771425,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 14:31:00.000,NVDS,US46144X4209,NVDS,RegularMkt,EQT,Call,16,...,0,0,0,2,2,1.550000,0.000000,0,0.188731,2024-01-31
96,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 14:31:00.000,PFIX,US82889N8552,PFIX,RegularMkt,EQT,Call,16,...,0,0,0,1,1,0.350000,0.000000,0,0.024368,2024-01-31
97,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 14:50:00.000,PSI,US46137V6478,PSI,RegularMkt,EQT,Call,16,...,0,0,0,2,2,0.575000,0.000000,0,0.078509,2024-01-31
98,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 20:24:00.000,QQQM,US46138G6492,QQQM,RegularMkt,EQT,Put,16,...,0,2,0,1,1,0.200000,0.720178,0,0.064300,2024-01-31
99,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 15:05:00.000,QQQM,US46138G6492,QQQM,RegularMkt,EQT,Call,16,...,0,0,0,2,2,4.675000,0.000000,0,0.253849,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_with_isin_daily_v2_2',key='BITO', asof_date='2024-01-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 18:58:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,5,...,0,17,0,12,67,0.010000,0.3804,0.000,0.0804,2022-08-02
1,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 19:55:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,5,...,0,49,0,86,1506,0.193658,1.3811,0.000,9.3282,2022-08-02
2,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 19:58:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,5,...,0,71,0,134,1223,0.207191,6.7269,0.000,7.5235,2022-08-02
3,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 19:58:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,5,...,0,104,0,110,1130,0.105977,8.1046,0.000,5.7220,2022-08-02
4,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 19:42:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,5,...,0,16,0,19,72,0.506552,0.3190,0.000,0.3551,2022-08-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 17:05:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,12,...,0,2,0,1,1,0.706667,0.1720,0.000,0.0065,2022-08-02
96,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 13:46:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,26,...,0,1,0,0,0,0.000000,0.0031,0.000,0.0000,2022-08-02
97,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 20:00:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,26,...,15,999,3,32,230,0.088685,88.7035,0.228,3.4739,2022-08-02
98,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 19:52:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,26,...,0,2,0,2,2,0.617500,0.0448,0.000,0.0300,2022-08-02
99,2022-08-02,2022-08-02 23:30:30.000,2022-08-02 19:55:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,16,...,0,3,0,6,29,1.045303,0.1255,0.000,0.5307,2022-08-02

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_with_isin_daily_v2_2',key='BITO', back_to='2024-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 18:30:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,3,...,0,39,0,10,129,0.016667,2.023881,0,0.186772,2024-05-01
1,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 19:52:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,3,...,0,22,0,14,72,0.022353,0.402014,0,0.159852,2024-05-01
2,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 19:54:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,3,...,0,11,0,14,123,0.067143,0.099548,0,0.491165,2024-05-01
3,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 20:00:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,3,...,0,94,0,82,729,0.071992,6.055710,0,3.746313,2024-05-01
4,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 20:00:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,3,...,0,85,0,4,105,0.099138,4.379245,0,0.671041,2024-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 19:04:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,20,...,0,13,0,11,86,0.866567,16.922092,0,4.610857,2024-05-01
96,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 16:38:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Call,20,...,0,1,0,3,26,0.800000,0.042268,0,1.170965,2024-05-01
97,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 19:50:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,31,...,0,3,0,7,7,2.632500,0.332722,0,0.386232,2024-05-01
98,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 16:12:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,31,...,0,1,0,13,33,12.032857,0.054387,0,1.555305,2024-05-01
99,2024-05-01,2024-05-01 23:30:30.000,2024-05-01 15:31:00.000,BITO,US74347G4405,BITO,RegularMkt,EQT,Put,17,...,0,4,0,3,5,0.452857,0.184489,0,0.178545,2024-05-01

## Download data file for a specific date using asof_date

In [12]:
Unifier.replicate(name="xtech_us_etf_options_flow_with_isin_daily_v2_2", target_location="./data", asof_date='2026-01-13')

Starting native python replication for xtech_us_etf_options_flow_with_isin_daily_v2_2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_etf_options_flow_with_isin_daily_v2_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_etf_options_flow_with_isin_daily_v2_2", target_location="./data")