In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_with_isin_1min_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-05-12,2023-05-12 09:31:00.000,2023-05-12 09:31:03.000,0,NA,None,1,1465.5100,732.76,732.76,...,1,0.00,1465.51,0,1,0.00,0.00,0,0,2023-05-12
1,2023-05-12,2023-05-12 09:31:00.000,2023-05-12 09:31:03.000,0,TANNI,None,1,1382.7000,691.35,691.35,...,1,0.00,1382.70,0,1,0.00,0.00,0,0,2023-05-12
2,2023-05-12,2023-05-12 09:32:00.000,2023-05-12 09:32:03.000,0,TANNI,None,1,2836.3113,0.00,0.00,...,1,0.00,0.00,0,1,0.00,2836.31,0,1,2023-05-12
3,2023-05-12,2023-05-12 09:40:00.000,2023-05-12 09:40:03.000,0,NA,None,1,102.8565,0.00,0.00,...,0,0.00,0.00,1,0,0.00,102.86,0,1,2023-05-12
4,2023-05-12,2023-05-12 09:44:00.000,2023-05-12 09:44:03.000,0,TANNI,None,1,50.2900,0.00,50.29,...,0,50.29,0.00,1,0,0.00,0.00,0,0,2023-05-12
5,2023-05-12,2023-05-12 09:46:00.000,2023-05-12 09:46:03.000,0,NA,None,1,12.8700,0.00,0.00,...,1,0.00,0.00,1,0,0.00,12.87,0,1,2023-05-12
6,2023-05-12,2023-05-12 09:51:00.000,2023-05-12 09:51:03.000,0,TANNI,None,6,5821.3500,970.23,4851.12,...,3,970.23,4851.12,1,5,0.00,0.00,0,0,2023-05-12
7,2023-05-12,2023-05-12 09:54:00.000,2023-05-12 09:54:03.000,0,NA,None,1,83.2000,0.00,83.20,...,1,0.00,83.20,0,1,0.00,0.00,0,0,2023-05-12
8,2023-05-12,2023-05-12 09:54:00.000,2023-05-12 09:54:03.000,0,TANNI,None,3,8031.9810,7781.00,0.00,...,1,7781.00,0.00,3,0,250.98,0.00,1,0,2023-05-12
9,2023-05-12,2023-05-12 09:55:00.000,2023-05-12 09:55:03.000,0,TANNI,None,7,30510.9590,0.00,6475.80,...,2,0.00,6475.80,2,5,17561.81,6473.35,3,2,2023-05-12

## Retrieve data for a specific date range using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_1min_v1_2_1', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 09:31:00.000,2024-01-31 09:31:03.000,0,ZIEXT,NaN,1,1000.00,500.00,500.00,...,1,0.00,1000.00,0,1,0.0,0.00,0,0,2024-01-31
1,2024-01-31,2024-01-31 16:11:00.000,2024-01-31 16:11:03.000,1,ZIEXT,NaN,1,0.00,0.00,0.00,...,0,0.00,0.00,0,1,0.0,0.00,0,0,2024-01-31
2,2024-01-31,2024-01-31 16:36:00.000,2024-01-31 16:36:03.000,1,CTEST,NaN,1,1253.00,626.50,626.50,...,1,626.50,626.50,0,0,0.0,0.00,0,0,2024-01-31
3,2024-01-31,2024-01-31 17:01:00.000,2024-01-31 17:01:03.000,1,ZIEXT,NaN,1,0.00,0.00,0.00,...,0,0.00,0.00,0,1,0.0,0.00,0,0,2024-01-31
4,2024-01-31,2024-01-31 17:28:00.000,2024-01-31 17:28:03.000,1,MTEST.A,NaN,1,1252.00,626.00,626.00,...,1,626.00,626.00,0,0,0.0,0.00,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 10:26:00.000,2024-01-31 10:26:03.000,0,AGO,BMG0585R1060,4,1077.88,269.47,808.41,...,2,269.47,808.41,1,3,0.0,0.00,0,0,2024-01-31
96,2024-01-31,2024-01-31 10:27:00.000,2024-01-31 10:27:03.000,0,AGO,BMG0585R1060,3,248.73,82.91,165.82,...,2,82.91,165.82,1,2,0.0,0.00,0,0,2024-01-31
97,2024-01-31,2024-01-31 10:28:00.000,2024-01-31 10:28:03.000,0,AGO,BMG0585R1060,10,14255.39,4276.62,5836.22,...,3,9978.77,134.07,7,3,0.0,4142.55,0,1,2024-01-31
98,2024-01-31,2024-01-31 10:29:00.000,2024-01-31 10:29:03.000,0,AGO,BMG0585R1060,23,72813.11,12663.15,60149.96,...,8,15828.94,56984.17,5,18,0.0,0.00,0,0,2024-01-31
99,2024-01-31,2024-01-31 10:30:00.000,2024-01-31 10:30:03.000,0,AGO,BMG0585R1060,14,7706.11,1651.31,6054.80,...,4,2752.18,4953.93,5,9,0.0,0.00,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [12]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_1min_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-08-08,2023-08-08 04:01:00.000,2023-08-08 04:01:03.000,1,AAPL,US0378331005,171,616686.54,530134.04,86552.50,...,18,522921.34,93765.20,145,26,0,0,0,0,2023-08-08
1,2023-08-08,2023-08-08 04:02:00.000,2023-08-08 04:02:03.000,1,AAPL,US0378331005,92,307858.32,274395.46,33462.86,...,15,274395.46,33462.86,82,10,0,0,0,0,2023-08-08
2,2023-08-08,2023-08-08 04:03:00.000,2023-08-08 04:03:03.000,1,AAPL,US0378331005,29,121873.65,113468.57,8405.08,...,7,88253.33,33620.32,21,8,0,0,0,0,2023-08-08
3,2023-08-08,2023-08-08 04:04:00.000,2023-08-08 04:04:03.000,1,AAPL,US0378331005,38,235135.70,136131.19,99004.51,...,7,111380.07,123755.63,18,20,0,0,0,0,2023-08-08
4,2023-08-08,2023-08-08 04:05:00.000,2023-08-08 04:05:03.000,1,AAPL,US0378331005,38,149159.57,129533.31,19626.26,...,7,113832.30,35327.27,29,9,0,0,0,0,2023-08-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-08-08,2023-08-08 05:36:00.000,2023-08-08 05:36:03.000,1,AAPL,US0378331005,17,57408.39,50654.46,6753.93,...,1,43900.53,13507.86,13,4,0,0,0,0,2023-08-08
96,2023-08-08,2023-08-08 05:37:00.000,2023-08-08 05:37:03.000,1,AAPL,US0378331005,27,159532.46,64994.71,94537.75,...,6,64994.71,94537.75,11,16,0,0,0,0,2023-08-08
97,2023-08-08,2023-08-08 05:38:00.000,2023-08-08 05:38:03.000,1,AAPL,US0378331005,10,7690.64,3076.26,4614.38,...,1,2307.19,5383.45,3,7,0,0,0,0,2023-08-08
98,2023-08-08,2023-08-08 05:39:00.000,2023-08-08 05:39:03.000,1,AAPL,US0378331005,17,89223.24,20993.70,68229.54,...,5,10496.85,78726.39,2,15,0,0,0,0,2023-08-08
99,2023-08-08,2023-08-08 05:40:00.000,2023-08-08 05:40:03.000,1,AAPL,US0378331005,22,209418.53,85671.22,123747.31,...,4,114228.29,95190.24,12,10,0,0,0,0,2023-08-08

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [13]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_1min_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-29,2024-01-29 04:01:00.000,2024-01-29 04:01:03.000,1,AAPL,US0378331005,134,646310.18,229102.49,417207.69,...,35,238748.91,407561.27,48,83,0,0,0,0,2024-01-29
1,2024-01-29,2024-01-29 04:02:00.000,2024-01-29 04:02:03.000,1,AAPL,US0378331005,68,343151.09,95880.45,247270.64,...,17,75695.09,267456.00,15,53,0,0,0,0,2024-01-29
2,2024-01-29,2024-01-29 04:03:00.000,2024-01-29 04:03:03.000,1,AAPL,US0378331005,15,59325.86,51415.75,7910.11,...,4,39550.57,19775.29,10,5,0,0,0,0,2024-01-29
3,2024-01-29,2024-01-29 04:04:00.000,2024-01-29 04:04:03.000,1,AAPL,US0378331005,20,35243.09,19383.70,15859.39,...,8,19383.70,15859.39,11,9,0,0,0,0,2024-01-29
4,2024-01-29,2024-01-29 04:05:00.000,2024-01-29 04:05:03.000,1,AAPL,US0378331005,3,2311.60,2311.60,0.00,...,2,770.53,1541.07,1,2,0,0,0,0,2024-01-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-29,2024-01-29 05:36:00.000,2024-01-29 05:36:03.000,1,AAPL,US0378331005,8,42861.08,0.00,42861.08,...,1,5357.63,37503.44,1,7,0,0,0,0,2024-01-29
96,2024-01-29,2024-01-29 05:37:00.000,2024-01-29 05:37:03.000,1,AAPL,US0378331005,4,961.04,0.00,961.04,...,1,0.00,961.04,0,4,0,0,0,0,2024-01-29
97,2024-01-29,2024-01-29 05:38:00.000,2024-01-29 05:38:03.000,1,AAPL,US0378331005,20,84379.15,12656.87,71722.28,...,5,21094.79,63284.36,5,15,0,0,0,0,2024-01-29
98,2024-01-29,2024-01-29 05:39:00.000,2024-01-29 05:39:03.000,1,AAPL,US0378331005,10,64771.44,0.00,64771.44,...,2,6477.14,58294.30,1,9,0,0,0,0,2024-01-29
99,2024-01-29,2024-01-29 05:40:00.000,2024-01-29 05:40:03.000,1,AAPL,US0378331005,5,1922.12,0.00,1922.12,...,1,768.85,1153.27,2,3,0,0,0,0,2024-01-29

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="lseg_us_eqt_flow_with_isin_1min_v1_2_1", target_location="./data", asof_date='2026-01-12')

Downloading using native python implementation for lseg_us_eqt_flow_with_isin_1min_v1_2...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_with_isin_1min_v1_2. Downloaded 1 files.

## Downlaod all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_with_isin_1min_v1_2_1", target_location="./data")