In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_equity_flow_1min_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-02-23,2023-02-23 04:01:00.000,2023-02-23 04:01:03.000,1,AA,1,243.80,121.90,121.90,0,...,1,121.90,121.90,0,0,0,0,0,0,2023-02-23
1,2023-02-23,2023-02-23 04:02:00.000,2023-02-23 04:02:03.000,1,AA,28,43514.33,31081.66,12432.67,20,...,4,32635.75,10878.58,21,7,0,0,0,0,2023-02-23
2,2023-02-23,2023-02-23 04:13:00.000,2023-02-23 04:13:03.000,1,AA,1,49.26,49.26,0.00,1,...,0,49.26,0.00,1,0,0,0,0,0,2023-02-23
3,2023-02-23,2023-02-23 04:30:00.000,2023-02-23 04:30:03.000,1,AA,9,108778.43,0.00,108778.43,0,...,4,0.00,108778.43,0,9,0,0,0,0,2023-02-23
4,2023-02-23,2023-02-23 04:45:00.000,2023-02-23 04:45:03.000,1,AA,2,487.10,0.00,487.10,0,...,1,0.00,487.10,0,2,0,0,0,0,2023-02-23
5,2023-02-23,2023-02-23 04:50:00.000,2023-02-23 04:50:03.000,1,AA,3,729.95,0.00,729.95,0,...,2,0.00,729.95,0,3,0,0,0,0,2023-02-23
6,2023-02-23,2023-02-23 04:54:00.000,2023-02-23 04:54:03.000,1,AA,1,48.65,0.00,48.65,0,...,0,0.00,48.65,0,1,0,0,0,0,2023-02-23
7,2023-02-23,2023-02-23 04:55:00.000,2023-02-23 04:55:03.000,1,AA,5,6574.80,0.00,6574.80,0,...,2,0.00,6574.80,0,5,0,0,0,0,2023-02-23
8,2023-02-23,2023-02-23 04:56:00.000,2023-02-23 04:56:03.000,1,AA,6,972.05,0.00,972.05,0,...,3,0.00,972.05,0,6,0,0,0,0,2023-02-23
9,2023-02-23,2023-02-23 05:03:00.000,2023-02-23 05:03:03.000,1,AA,1,48.41,0.00,48.41,0,...,1,0.00,48.41,0,1,0,0,0,0,2023-02-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_1min_v1_2_1', back_to='2021-01-31', up_to='2021-02-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_1min_v1_2',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2023-12-29 14:42:03.000,2023-12-29 14:42:00.000,0,AAPL,572,9.651912e+06,5500914.93,2902323.21,374,198,...,8403238.14,0.0,556,16,809950.66,438723.28,48,26,2023-12-29,2023-12-29
1,2023-12-29 14:56:03.000,2023-12-29 14:56:00.000,0,AAPL,811,1.013778e+07,6125172.11,2650074.47,550,261,...,8775246.58,0.0,801,10,750021.08,612517.21,60,49,2023-12-29,2023-12-29
2,2023-12-29 14:58:03.000,2023-12-29 14:58:00.000,0,AAPL,610,8.529222e+06,4278593.26,2922307.16,359,251,...,7200900.42,0.0,602,8,741063.54,587257.90,53,42,2023-12-29,2023-12-29
3,2023-12-29 14:59:03.000,2023-12-29 14:59:00.000,0,AAPL,565,6.361811e+06,3310393.60,1925433.02,352,213,...,5235826.62,0.0,552,13,653070.85,472913.37,58,42,2023-12-29,2023-12-29
4,2023-12-29 15:01:03.000,2023-12-29 15:01:00.000,0,AAPL,754,1.228503e+07,5376735.09,5637425.27,375,379,...,11014160.36,0.0,736,18,733191.15,537673.51,45,33,2023-12-29,2023-12-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-12-26 12:14:03.000,2023-12-26 12:14:00.000,0,AAPL,610,1.265134e+07,7881163.15,2903586.42,434,176,...,10784749.57,0.0,602,8,1119954.76,746636.51,54,36,2023-12-26,2023-12-26
96,2023-12-26 12:15:03.000,2023-12-26 12:15:00.000,0,AAPL,704,1.259454e+07,5993141.49,4812403.17,402,302,...,10805544.67,0.0,691,13,1198628.30,590369.16,67,33,2023-12-26,2023-12-26
97,2023-12-26 12:18:03.000,2023-12-26 12:18:00.000,0,AAPL,490,5.141232e+06,3095231.23,912830.91,355,135,...,4008062.13,0.0,488,2,629538.55,503630.84,60,48,2023-12-26,2023-12-26
98,2023-12-26 15:07:03.000,2023-12-26 15:07:00.000,0,AAPL,686,1.552286e+07,8508158.59,4457732.02,453,233,...,12965890.61,0.0,680,6,1742362.26,814610.93,77,36,2023-12-26,2023-12-26
99,2023-12-26 15:11:03.000,2023-12-26 15:11:00.000,0,AAPL,456,5.843936e+06,2947599.24,1845453.44,290,166,...,4793052.68,0.0,448,8,768938.93,281944.27,60,22,2023-12-26,2023-12-26

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_1min_v1_2_1',key='AAPL', back_to='2022-01-01', up_to='2022-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2022-01-12,2022-01-12 04:01:00.000,2022-01-12 04:01:03.000,1,AAPL,70,334450.00,226948.21,107501.79,47,...,16,234115.00,100335.00,49,21,0,0,0,0,2022-01-12
1,2022-01-12,2022-01-12 04:02:00.000,2022-01-12 04:02:03.000,1,AAPL,38,196101.11,175458.89,20642.22,34,...,8,175458.89,20642.22,34,4,0,0,0,0,2022-01-12
2,2022-01-12,2022-01-12 04:03:00.000,2022-01-12 04:03:03.000,1,AAPL,65,255822.49,228272.38,27550.11,58,...,22,173172.15,82650.34,44,21,0,0,0,0,2022-01-12
3,2022-01-12,2022-01-12 04:04:00.000,2022-01-12 04:04:03.000,1,AAPL,37,388671.08,273120.22,115550.86,26,...,11,283624.84,105046.24,27,10,0,0,0,0,2022-01-12
4,2022-01-12,2022-01-12 04:05:00.000,2022-01-12 04:05:03.000,1,AAPL,62,417378.05,343327.11,74050.94,51,...,7,376986.63,40391.42,56,6,0,0,0,0,2022-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-01-12,2022-01-12 05:36:00.000,2022-01-12 05:36:03.000,1,AAPL,16,63623.20,63623.20,0.00,16,...,2,19882.25,43740.95,5,11,0,0,0,0,2022-01-12
96,2022-01-12,2022-01-12 05:37:00.000,2022-01-12 05:37:03.000,1,AAPL,10,15819.89,15819.89,0.00,10,...,3,14237.90,1581.99,9,1,0,0,0,0,2022-01-12
97,2022-01-12,2022-01-12 05:38:00.000,2022-01-12 05:38:03.000,1,AAPL,14,61702.34,44073.10,17629.24,10,...,1,48480.41,13221.93,11,3,0,0,0,0,2022-01-12
98,2022-01-12,2022-01-12 05:39:00.000,2022-01-12 05:39:03.000,1,AAPL,13,37635.06,34740.06,2895.00,12,...,4,26055.04,11580.02,9,4,0,0,0,0,2022-01-12
99,2022-01-12,2022-01-12 05:40:00.000,2022-01-12 05:40:03.000,1,AAPL,11,7737.76,7737.76,0.00,11,...,3,4924.03,2813.73,7,4,0,0,0,0,2022-01-12

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="lseg_us_equity_flow_1min_v1_2_1", target_location="./data", asof_date='2012-01-12')

Starting native python replication for lseg_us_equity_flow_1min_v1_2_1 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_equity_flow_1min_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_flow_1min_v1_2_1", target_location="./data")