In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-07-19,2023-07-19 09:30:00.000,2023-07-19 09:30:03.000,1,ABCB,US03076K1088,1,3949.0000,1974.50,1974.50,...,1,1974.50,1974.50,0,0,0.00,0,0,0,2023-07-19
1,2023-07-19,2023-07-19 09:31:00.000,2023-07-19 09:31:03.000,0,ABCB,US03076K1088,59,204931.6100,138936.68,65994.93,...,16,93782.26,111149.35,27,32,0.00,0,0,0,2023-07-19
2,2023-07-19,2023-07-19 09:32:00.000,2023-07-19 09:32:03.000,0,ABCB,US03076K1088,26,35571.0400,2736.23,32834.81,...,9,4104.35,31466.69,3,23,0.00,0,0,0,2023-07-19
3,2023-07-19,2023-07-19 09:33:00.000,2023-07-19 09:33:03.000,0,ABCB,US03076K1088,64,83845.5900,58953.93,24891.66,...,5,55023.67,28821.92,42,22,0.00,0,0,0,2023-07-19
4,2023-07-19,2023-07-19 09:34:00.000,2023-07-19 09:34:03.000,0,ABCB,US03076K1088,27,30267.8200,8968.24,21299.58,...,6,16815.46,13452.36,15,12,0.00,0,0,0,2023-07-19
5,2023-07-19,2023-07-19 09:35:00.000,2023-07-19 09:35:03.000,0,ABCB,US03076K1088,5,4606.9870,3487.16,921.40,...,1,3487.16,921.40,4,1,198.43,0,1,0,2023-07-19
6,2023-07-19,2023-07-19 09:36:00.000,2023-07-19 09:36:03.000,0,ABCB,US03076K1088,35,47412.9375,32546.99,10837.24,...,9,21709.75,21674.49,19,16,4028.70,0,2,0,2023-07-19
7,2023-07-19,2023-07-19 09:37:00.000,2023-07-19 09:37:03.000,0,ABCB,US03076K1088,50,103342.8800,84741.16,18601.72,...,7,43404.01,59938.87,21,29,0.00,0,0,0,2023-07-19
8,2023-07-19,2023-07-19 09:38:00.000,2023-07-19 09:38:03.000,0,ABCB,US03076K1088,43,71705.3700,15008.10,56697.27,...,13,13340.53,58364.84,8,35,0.00,0,0,0,2023-07-19
9,2023-07-19,2023-07-19 09:39:00.000,2023-07-19 09:39:03.000,0,ABCB,US03076K1088,15,12813.5700,1708.48,11105.09,...,9,2562.71,10250.86,3,12,0.00,0,0,0,2023-07-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:03:00.000,2024-01-31 04:03:03.000,1,AA,US0138721065,2,61.0500,45.79,15.26,...,2,61.05,0.00,2,0,0.00,0.00,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:17:00.000,2024-01-31 04:17:03.000,1,AA,US0138721065,1,1525.0000,1525.00,0.00,...,0,1525.00,0.00,1,0,0.00,0.00,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:32:00.000,2024-01-31 04:32:03.000,1,AA,US0138721065,2,60.8000,60.80,0.00,...,1,30.40,30.40,1,1,0.00,0.00,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:47:00.000,2024-01-31 04:47:03.000,1,AA,US0138721065,10,13204.2900,10563.43,2640.86,...,0,11883.86,1320.43,9,1,0.00,0.00,0,0,2024-01-31
4,2024-01-31,2024-01-31 05:05:00.000,2024-01-31 05:05:03.000,1,AA,US0138721065,1,30.5600,30.56,0.00,...,1,0.00,30.56,0,1,0.00,0.00,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 10:13:00.000,2024-01-31 10:13:03.000,0,AA,US0138721065,125,265637.7534,103553.57,159990.73,...,14,101428.47,162115.84,48,77,576.43,1517.02,1,1,2024-01-31
96,2024-01-31,2024-01-31 10:14:00.000,2024-01-31 10:14:03.000,0,AA,US0138721065,135,267012.6241,140047.20,96549.35,...,17,140047.20,96549.35,77,58,12248.89,18167.18,3,2,2024-01-31
97,2024-01-31,2024-01-31 10:15:00.000,2024-01-31 10:15:03.000,0,AA,US0138721065,143,506738.7509,214631.04,276402.96,...,20,225261.92,265772.07,68,75,15704.76,0.00,7,0,2024-01-31
98,2024-01-31,2024-01-31 10:16:00.000,2024-01-31 10:16:03.000,0,AA,US0138721065,146,323980.5633,108265.88,135729.91,...,21,112703.97,131291.82,80,66,64819.63,15165.15,5,1,2024-01-31
99,2024-01-31,2024-01-31 10:17:00.000,2024-01-31 10:17:03.000,0,AA,US0138721065,94,164429.6900,41629.34,89419.74,...,11,48626.35,82422.73,33,61,9098.97,24281.64,1,2,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-07-28,2023-07-28 04:01:00.000,2023-07-28 04:01:03.000,1,AAPL,US0378331005,58,193885.77,88585.74,105300.03,...,23,80228.59,113657.18,24,34,0,0,0,0,2023-07-28
1,2023-07-28,2023-07-28 04:02:00.000,2023-07-28 04:02:03.000,1,AAPL,US0378331005,35,198208.69,124588.32,73620.37,...,11,118925.21,79283.48,21,14,0,0,0,0,2023-07-28
2,2023-07-28,2023-07-28 04:03:00.000,2023-07-28 04:03:03.000,1,AAPL,US0378331005,6,15537.33,15537.33,0.00,...,3,10358.22,5179.11,4,2,0,0,0,0,2023-07-28
3,2023-07-28,2023-07-28 04:04:00.000,2023-07-28 04:04:03.000,1,AAPL,US0378331005,12,32031.69,16015.84,16015.84,...,7,13346.54,18685.15,5,7,0,0,0,0,2023-07-28
4,2023-07-28,2023-07-28 04:05:00.000,2023-07-28 04:05:03.000,1,AAPL,US0378331005,9,37088.01,37088.01,0.00,...,2,24725.34,12362.67,6,3,0,0,0,0,2023-07-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-07-28,2023-07-28 05:39:00.000,2023-07-28 05:39:03.000,1,AAPL,US0378331005,9,23533.05,0.00,23533.05,...,5,10459.13,13073.92,4,5,0,0,0,0,2023-07-28
96,2023-07-28,2023-07-28 05:40:00.000,2023-07-28 05:40:03.000,1,AAPL,US0378331005,31,170076.27,98753.96,71322.31,...,5,131671.95,38404.32,24,7,0,0,0,0,2023-07-28
97,2023-07-28,2023-07-28 05:41:00.000,2023-07-28 05:41:03.000,1,AAPL,US0378331005,3,5838.00,0.00,5838.00,...,0,5838.00,0.00,3,0,0,0,0,0,2023-07-28
98,2023-07-28,2023-07-28 05:42:00.000,2023-07-28 05:42:03.000,1,AAPL,US0378331005,24,151245.51,56717.07,94528.44,...,4,69320.86,81924.65,11,13,0,0,0,0,2023-07-28
99,2023-07-28,2023-07-28 05:43:00.000,2023-07-28 05:43:03.000,1,AAPL,US0378331005,11,83909.28,53396.81,30512.47,...,2,53396.81,30512.47,7,4,0,0,0,0,2023-07-28

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-09,2024-01-09 04:01:00.000,2024-01-09 04:01:03.000,1,AAPL,US0378331005,106,319481.06,272764.49,46716.57,...,22,256187.64,63293.42,85,21,0,0,0,0,2024-01-09
1,2024-01-09,2024-01-09 04:02:00.000,2024-01-09 04:02:03.000,1,AAPL,US0378331005,57,286042.72,245896.37,40146.35,...,9,240878.08,45164.64,48,9,0,0,0,0,2024-01-09
2,2024-01-09,2024-01-09 04:03:00.000,2024-01-09 04:03:03.000,1,AAPL,US0378331005,47,238281.35,131815.21,106466.14,...,6,167303.93,70977.42,33,14,0,0,0,0,2024-01-09
3,2024-01-09,2024-01-09 04:04:00.000,2024-01-09 04:04:03.000,1,AAPL,US0378331005,56,461320.85,354228.51,107092.34,...,10,329514.89,131805.96,40,16,0,0,0,0,2024-01-09
4,2024-01-09,2024-01-09 04:05:00.000,2024-01-09 04:05:03.000,1,AAPL,US0378331005,17,67542.33,27811.55,39730.78,...,5,39730.78,27811.55,10,7,0,0,0,0,2024-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-09,2024-01-09 05:36:00.000,2024-01-09 05:36:03.000,1,AAPL,US0378331005,14,19984.58,5709.88,14274.70,...,3,8564.82,11419.76,6,8,0,0,0,0,2024-01-09
96,2024-01-09,2024-01-09 05:37:00.000,2024-01-09 05:37:03.000,1,AAPL,US0378331005,3,740.14,246.71,493.43,...,0,246.71,493.43,1,2,0,0,0,0,2024-01-09
97,2024-01-09,2024-01-09 05:38:00.000,2024-01-09 05:38:03.000,1,AAPL,US0378331005,12,90324.36,45162.18,45162.18,...,5,45162.18,45162.18,6,6,0,0,0,0,2024-01-09
98,2024-01-09,2024-01-09 05:39:00.000,2024-01-09 05:39:03.000,1,AAPL,US0378331005,2,3146.38,3146.38,0.00,...,0,3146.38,0.00,2,0,0,0,0,0,2024-01-09
99,2024-01-09,2024-01-09 05:40:00.000,2024-01-09 05:40:03.000,1,AAPL,US0378331005,7,8143.81,6980.41,1163.40,...,2,6980.41,1163.40,6,1,0,0,0,0,2024-01-09

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1", target_location="./data", asof_date='2026-01-12')

Downloading using native python implementation for lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1. Downloaded 1 files.

## Downlaod all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1", target_location="./data")