In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_with_isin_daily_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2020-03-06,2020-03-06 18:31:00.000,2020-03-06 20:00:03.000,1,A,US00846U1016,34462,2.281104e+08,1.300384e+08,9.500657e+07,...,7485,1.307701e+08,9.427488e+07,18379,16082,1372571.27,1692893.83,193,239,2020-03-06
1,2020-03-06,2020-03-06 19:58:00.000,2020-03-06 20:00:03.000,1,AA,US0138721065,61314,1.166684e+08,5.727797e+07,5.160236e+07,...,7856,5.664879e+07,5.223154e+07,30285,31027,4116479.62,3671603.70,917,664,2020-03-06
2,2020-03-06,2020-03-06 20:01:00.000,2020-03-06 20:00:03.000,1,AAAU,US7154261025,918,5.178729e+06,3.413034e+06,1.323254e+06,...,240,3.238574e+06,1.497714e+06,531,387,363192.50,79247.97,76,14,2020-03-06
3,2020-03-06,2020-03-06 17:52:00.000,2020-03-06 20:00:03.000,1,AACG,US00211V1061,70,8.948464e+03,1.704660e+03,6.984470e+03,...,23,1.722570e+03,6.966560e+03,34,36,27.23,232.10,5,5,2020-03-06
4,2020-03-06,2020-03-06 20:01:00.000,2020-03-06 20:00:03.000,1,AADR,US00768Y2063,56,9.203103e+05,1.292497e+05,5.874962e+05,...,24,3.964583e+05,3.202876e+05,33,22,108848.12,94716.32,16,4,2020-03-06
5,2020-03-06,2020-03-06 20:00:00.000,2020-03-06 20:00:03.000,1,AAL,US02376R1023,231768,8.717437e+08,4.333881e+08,2.934971e+08,...,43276,4.241877e+08,3.026975e+08,133669,98097,77737769.53,67120761.59,15229,7668,2020-03-06
6,2020-03-06,2020-03-06 20:01:00.000,2020-03-06 20:00:03.000,1,AAMC,VI02153X1080,44,5.620629e+04,1.242044e+04,3.696102e+04,...,12,1.239877e+04,3.698269e+04,32,12,4436.36,2388.46,4,2,2020-03-06
7,2020-03-06,2020-03-06 16:00:00.000,2020-03-06 20:00:03.000,0,AAME,US0482091008,19,1.767810e+03,1.395130e+03,3.676400e+02,...,8,1.228460e+03,5.343100e+02,13,5,5.04,0.00,1,0,2020-03-06
8,2020-03-06,2020-03-06 18:31:00.000,2020-03-06 20:00:03.000,1,AAN,US0025353006,11585,3.571336e+07,1.719768e+07,1.744576e+07,...,2536,1.533070e+07,1.931274e+07,5323,6261,635461.69,434454.57,163,117,2020-03-06
9,2020-03-06,2020-03-06 16:03:00.000,2020-03-06 20:00:03.000,1,AAOI,US03823U1025,6059,6.893215e+06,2.728686e+06,3.373771e+06,...,936,2.771824e+06,3.330632e+06,2832,3227,346121.05,444638.20,107,115,2020-03-06

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_daily_v1_2_1', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-08,2024-01-08 19:01:00.000,2024-01-08 20:00:03.000,1,A,US00846U1016,24462,1.632557e+08,1.052314e+08,5.371729e+07,...,5613,1.040284e+08,5.492026e+07,13497,10964,2661418.69,1645589.38,441,306,2024-01-08
1,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AA,US0138721065,46948,1.500690e+08,6.576694e+07,6.618504e+07,...,6999,5.820643e+07,7.374556e+07,22802,24146,9402977.83,8714056.07,924,826,2024-01-08
2,2024-01-08,2024-01-08 20:01:00.000,2024-01-08 20:00:03.000,1,AAA,US46144X6105,61,2.293470e+05,1.037669e+05,9.478193e+04,...,19,1.039515e+05,9.459733e+04,39,22,30798.09,0.00,4,0,2024-01-08
3,2024-01-08,2024-01-08 19:22:00.000,2024-01-08 20:00:03.000,1,AAAU,US38150K1034,2260,3.727521e+07,1.668852e+07,1.499600e+07,...,629,1.617365e+07,1.551087e+07,1157,1103,2834566.80,2756123.62,297,190,2024-01-08
4,2024-01-08,2024-01-08 19:04:00.000,2024-01-08 20:00:03.000,1,AACG,US00211V1061,97,1.855058e+04,2.855930e+03,1.324724e+04,...,23,2.438990e+03,1.366416e+04,43,54,2139.50,307.94,10,6,2024-01-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-08,2024-01-08 19:01:00.000,2024-01-08 20:00:03.000,1,ACM,US00766T1007,11745,5.589152e+07,2.966698e+07,2.566620e+07,...,2634,2.997819e+07,2.535500e+07,5010,6734,233296.15,325043.76,86,114,2024-01-08
96,2024-01-08,2024-01-08 19:59:00.000,2024-01-08 20:00:03.000,1,ACMR,US00108J1097,11361,1.270047e+07,6.662334e+06,4.844835e+06,...,1640,5.905813e+06,5.601356e+06,5812,5549,515267.11,678031.46,289,207,2024-01-08
97,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,ACN,IE00B4BNMY34,35875,5.463867e+08,3.105081e+08,1.940116e+08,...,10773,3.143500e+08,1.901697e+08,18201,17674,16219340.45,25647642.21,1319,1444,2024-01-08
98,2024-01-08,2024-01-08 16:29:00.000,2024-01-08 20:00:03.000,1,ACNB,US0008681092,569,1.097194e+06,5.336354e+05,4.813639e+05,...,184,5.924850e+05,4.225143e+05,237,332,57774.47,24420.52,18,23,2024-01-08
99,2024-01-08,2024-01-08 16:01:00.000,2024-01-08 20:00:03.000,1,ACNT,US8715651076,347,8.427873e+04,5.489203e+04,2.451208e+04,...,90,5.357896e+04,2.582516e+04,300,47,3865.74,1008.86,1,3,2024-01-08

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_daily_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2019-07-12,2019-07-12 19:54:00.000,2019-07-12 20:00:03.000,1,AAPL,US0378331005,143624,3.486262e+09,1.436331e+09,1.608420e+09,...,27269,1.474883e+09,1.569868e+09,67881,75741,2.147263e+08,2.267845e+08,5490,6216,2019-07-12
1,2019-05-08,2019-05-08 20:00:00.000,2019-05-08 20:00:03.000,1,AAPL,US0378331005,201898,5.227719e+09,2.208788e+09,2.191031e+09,...,46896,2.176357e+09,2.223462e+09,97877,104016,4.396845e+08,3.882155e+08,9282,7988,2019-05-08
2,2019-08-07,2019-08-07 20:00:00.000,2019-08-07 20:00:03.000,1,AAPL,US0378331005,276562,6.483863e+09,2.513751e+09,2.946187e+09,...,60880,2.503262e+09,2.956676e+09,135327,141234,5.311348e+08,4.927903e+08,11201,9800,2019-08-07
3,2020-03-13,2020-03-13 20:00:00.000,2020-03-13 20:00:03.000,1,AAPL,US0378331005,935531,2.367170e+10,1.024046e+10,1.033991e+10,...,282457,1.008081e+10,1.049956e+10,463215,472314,1.559549e+09,1.531786e+09,52050,49268,2020-03-13
4,2019-08-29,2019-08-29 20:00:00.000,2019-08-29 20:00:03.000,1,AAPL,US0378331005,167183,4.329899e+09,1.648462e+09,1.858366e+09,...,35486,1.659720e+09,1.847107e+09,77183,89998,4.141007e+08,4.089706e+08,8199,8532,2019-08-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-05-18,2023-05-18 20:00:00.000,2023-05-18 20:00:03.000,1,AAPL,US0378331005,592429,1.056137e+10,5.064161e+09,4.319906e+09,...,113592,5.065733e+09,4.318335e+09,340542,251887,6.744557e+08,5.028511e+08,39427,23406,2023-05-18
96,2023-12-27,2023-12-27 20:00:00.000,2023-12-27 20:00:03.000,1,AAPL,US0378331005,542011,8.227349e+09,3.620305e+09,3.567855e+09,...,100987,3.677934e+09,3.510226e+09,317622,224389,5.631950e+08,4.759941e+08,35532,20947,2023-12-27
97,2019-07-03,2019-07-03 17:00:00.000,2019-07-03 20:00:03.000,1,AAPL,US0378331005,92329,2.284550e+09,1.106502e+09,8.482727e+08,...,18272,1.119417e+09,8.353576e+08,47823,44505,1.623457e+08,1.674298e+08,4147,4512,2019-07-03
98,2019-08-02,2019-08-02 19:59:00.000,2019-08-02 20:00:03.000,1,AAPL,US0378331005,344037,7.840545e+09,3.279687e+09,3.371215e+09,...,79613,3.257119e+09,3.393783e+09,165302,178734,5.963560e+08,5.932869e+08,15696,13829,2019-08-02
99,2023-02-16,2023-02-16 20:00:00.000,2023-02-16 20:00:03.000,1,AAPL,US0378331005,512425,9.734367e+09,4.321802e+09,4.112509e+09,...,111213,4.342909e+09,4.091402e+09,248965,263460,7.008214e+08,5.992344e+08,54631,25225,2023-02-16

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_daily_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,US0378331005,990710,1.406572e+10,6.739308e+09,5.706525e+09,...,203637,6.718754e+09,5.727078e+09,558557,432153,8.381063e+08,7.817779e+08,69901,36457,2024-01-02
1,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,US0378331005,754607,1.047012e+10,5.324264e+09,4.027101e+09,...,140374,5.294603e+09,4.056762e+09,436132,318474,5.894122e+08,5.293452e+08,44543,28370,2024-01-16
2,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,US0378331005,470667,6.941078e+09,3.434455e+09,2.791790e+09,...,82988,3.442340e+09,2.783905e+09,286746,183919,4.031384e+08,3.116944e+08,29492,17846,2024-01-12
3,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,US0378331005,672809,1.207373e+10,5.862620e+09,5.141551e+09,...,121439,5.773583e+09,5.230588e+09,390683,282126,5.512614e+08,5.182930e+08,32778,25601,2024-01-19
4,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,US0378331005,635508,9.891279e+09,4.744796e+09,4.130843e+09,...,110062,4.674756e+09,4.200882e+09,371266,264241,5.258774e+08,4.897631e+08,31153,25473,2024-01-25
5,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,US0378331005,704292,1.117920e+10,4.903110e+09,4.848632e+09,...,141705,4.847464e+09,4.904278e+09,404312,299980,8.093261e+08,6.181319e+08,52306,25291,2024-01-04
6,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,US0378331005,708796,1.073480e+10,5.462671e+09,4.016835e+09,...,125197,5.574549e+09,3.904957e+09,422318,286474,6.501838e+08,6.051145e+08,34884,29397,2024-01-22
7,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,US0378331005,659234,1.011811e+10,5.140608e+09,3.874886e+09,...,122228,5.194947e+09,3.820547e+09,410217,249013,6.224780e+08,4.801413e+08,45877,26645,2024-01-08
8,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,US0378331005,530828,7.405986e+09,3.703151e+09,2.830986e+09,...,98430,3.666996e+09,2.867141e+09,316857,213971,4.414514e+08,4.303981e+08,32092,23895,2024-01-09
9,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,US0378331005,587962,9.457487e+09,4.396980e+09,4.025837e+09,...,105630,4.417371e+09,4.005446e+09,348478,239484,4.926221e+08,5.420481e+08,27663,27274,2024-01-24
10,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,US0378331005,527086,7.671505e+09,3.881987e+09,2.852431e+09,...,91847,3.861606e+09,2.872812e+09,319856,207229,4.602497e+08,4.768365e+08,25365,23987,2024-01-23
11,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,US0378331005,589939,7.998797e+09,3.962558e+09,3.250855e+09,...,105210,3.856046e+09,3.357367e+09,362427,227509,4.216349e+08,3.637488e+08,31244,22398,2024-01-29
12,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,US0378331005,682093,9.944367e+09,4.911012e+09,3.772293e+09,...,131699,4.867751e+09,3.815554e+09,384467,297626,6.964564e+08,5.646060e+08,41131,26399,2024-01-30
13,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,US0378331005,646606,9.724189e+09,4.725496e+09,3.810025e+09,...,129159,4.727787e+09,3.807734e+09,374680,271926,5.098485e+08,6.788193e+08,36482,31635,2024-01-03
14,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,US0378331005,673751,9.609475e+09,4.544943e+09,4.074560e+09,...,129057,4.461645e+09,4.157858e+09,380986,292765,5.103516e+08,4.796210e+08,36375,23940,2024-01-31
15,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,US0378331005,547902,7.957503e+09,3.802293e+09,3.215115e+09,...,100340,3.825576e+09,3.191832e+09,330178,217724,5.180600e+08,4.220353e+08,33851,20631,2024-01-10
16,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,US0378331005,585481,8.165045e+09,3.881386e+09,3.334522e+09,...,105856,3.852553e+09,3.363355e+09,340434,245045,5.133696e+08,4.357680e+08,33131,20739,2024-01-17
17,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,US0378331005,776996,1.390008e+10,6.246976e+09,6.053243e+09,...,144853,6.214716e+09,6.085502e+09,438270,338726,8.478937e+08,7.519638e+08,39267,31652,2024-01-18
18,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,US0378331005,527636,8.032383e+09,3.920825e+09,3.412678e+09,...,92767,3.889177e+09,3.444326e+09,312636,214999,3.436649e+08,3.552153e+08,24908,19583,2024-01-26
19,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,US0378331005,675337,1.058505e+10,4.966160e+09,4.240622e+09,...,132526,4.993287e+09,4.213496e+09,389878,285451,7.655776e+08,6.126888e+08,46270,25440,2024-01-05
20,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,US0378331005,573585,8.242853e+09,3.807336e+09,3.516374e+09,...,105517,3.842186e+09,3.481524e+09,329199,244386,5.234246e+08,3.957190e+08,35207,19919,2024-01-11

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="lseg_us_eqt_flow_with_isin_daily_v1_2_1", target_location="./data", asof_date='2026-01-08')

Downloading using native python implementation for lseg_us_eqt_flow_with_isin_daily_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_with_isin_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_with_isin_daily_v1_2_1", target_location="./data")