In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2016-07-13,2016-07-13 17:17:00.000,2016-07-13 20:00:03.000,1,A,US00846U1016,12161,8.557536e+07,4.412210e+07,4.049776e+07,...,1404,4.430258e+07,4.031729e+07,5969,6191,4.373738e+05,5.181187e+05,75,71,2016-07-13
1,2016-07-13,2016-07-13 19:15:00.000,2016-07-13 20:00:03.000,1,AA,US0138171014,62369,2.475836e+08,9.595139e+07,1.235348e+08,...,7248,9.971192e+07,1.197743e+08,26151,36218,1.241070e+07,1.568669e+07,1349,1674,2016-07-13
2,2016-07-13,2016-07-13 16:03:00.000,2016-07-13 20:00:03.000,1,AAC,US0003071083,944,2.445216e+06,8.504677e+05,1.423614e+06,...,265,8.243051e+05,1.449777e+06,378,564,1.332491e+05,3.788565e+04,29,6,2016-07-13
3,2016-07-13,2016-07-13 19:59:00.000,2016-07-13 20:00:03.000,1,AAL,US02376R1023,88815,5.171402e+08,2.359648e+08,2.301545e+08,...,9765,2.353023e+08,2.308170e+08,44728,44086,2.613440e+07,2.488648e+07,1657,1548,2016-07-13
4,2016-07-13,2016-07-13 16:03:00.000,2016-07-13 20:00:03.000,1,AAN,US0025353006,3796,1.216817e+07,5.585637e+06,6.195180e+06,...,595,5.700958e+06,6.079859e+06,1611,2185,2.427780e+05,1.445731e+05,30,39,2016-07-13
5,2016-07-13,2016-07-13 16:01:00.000,2016-07-13 20:00:03.000,1,AAOI,US03823U1025,1390,2.342166e+06,1.224001e+06,8.285744e+05,...,314,1.213233e+06,8.393419e+05,802,588,1.985433e+05,9.104763e+04,29,29,2016-07-13
6,2016-07-13,2016-07-13 16:01:00.000,2016-07-13 20:00:03.000,1,AAON,US0003602069,1417,4.519298e+06,2.739797e+06,1.610845e+06,...,302,2.722475e+06,1.628167e+06,892,524,3.749714e+04,1.311600e+05,17,32,2016-07-13
7,2016-07-13,2016-07-13 17:17:00.000,2016-07-13 20:00:03.000,1,AAP,US00751Y1064,9181,1.462234e+08,7.271425e+07,7.056797e+07,...,2248,7.247682e+07,7.080540e+07,4358,4822,1.377223e+06,1.563937e+06,106,102,2016-07-13
8,2016-07-13,2016-07-13 20:00:00.000,2016-07-13 20:00:03.000,1,AAPL,US0378331005,144495,2.437937e+09,9.025030e+08,1.267047e+09,...,20289,9.254879e+08,1.244062e+09,68786,75709,1.290393e+08,1.393476e+08,5043,5260,2016-07-13
9,2016-07-13,2016-07-13 18:12:00.000,2016-07-13 20:00:03.000,1,AAT,US0240131047,2357,1.084025e+07,7.521159e+06,3.110531e+06,...,428,7.469682e+06,3.162009e+06,1429,928,1.686188e+05,3.993801e+04,31,15,2016-07-13

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-23,2024-01-23 19:01:00.000,2024-01-23 20:00:03.000,1,A,US00846U1016,19094,1.023307e+08,5.660209e+07,4.229884e+07,...,4969,5.772645e+07,4.117448e+07,9560,9533,1236773.72,2193030.06,307,257,2024-01-23
1,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AA,US0138721065,76570,2.647145e+08,1.345395e+08,1.025955e+08,...,11518,1.339311e+08,1.032039e+08,40190,36380,14628825.24,12950686.72,1604,1283,2024-01-23
2,2024-01-23,2024-01-23 19:47:00.000,2024-01-23 20:00:03.000,1,AADI,US00032Q1040,2201,6.530427e+05,2.600712e+05,3.209890e+05,...,347,2.432641e+05,3.377961e+05,1030,1171,36412.57,35569.93,74,69,2024-01-23
3,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAL,US02376R1023,123370,6.908552e+08,2.825064e+08,3.093098e+08,...,17622,2.845123e+08,3.073040e+08,58899,64471,56953054.86,42085945.64,4020,3640,2024-01-23
4,2024-01-23,2024-01-23 19:01:00.000,2024-01-23 20:00:03.000,1,AAN,US00258W1080,3417,2.193509e+06,1.281522e+06,8.723924e+05,...,601,1.215029e+06,9.388851e+05,1756,1661,25822.05,13772.80,32,38,2024-01-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-23,2024-01-23 19:01:00.000,2024-01-23 20:00:03.000,1,AKR,US0042391096,10654,2.145445e+07,1.149542e+07,9.715679e+06,...,1167,1.152750e+07,9.683591e+06,5277,5377,158345.08,85008.92,46,55,2024-01-23
96,2024-01-23,2024-01-23 16:21:00.000,2024-01-23 20:00:03.000,1,AKRO,US00973Y1082,9713,1.128133e+07,5.798483e+06,5.323761e+06,...,1660,5.970484e+06,5.151760e+06,4223,5489,74727.05,84363.79,55,70,2024-01-23
97,2024-01-23,2024-01-23 19:24:00.000,2024-01-23 20:00:03.000,1,AKTS,US00973N1028,1016,1.030347e+05,2.081709e+04,5.383991e+04,...,229,2.817678e+04,4.648016e+04,318,698,5719.57,22658.09,31,140,2024-01-23
98,2024-01-23,2024-01-23 16:21:00.000,2024-01-23 20:00:03.000,1,AKYA,US00974H1041,1601,7.540559e+05,3.064088e+05,4.160868e+05,...,240,3.191550e+05,4.033407e+05,685,915,24526.08,7034.24,23,21,2024-01-23
99,2024-01-23,2024-01-23 19:01:00.000,2024-01-23 20:00:03.000,1,AL,US00912X3026,12157,3.612304e+07,2.126514e+07,1.385038e+07,...,1897,1.670707e+07,1.840845e+07,6693,5464,515315.77,492205.77,161,196,2024-01-23

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2018-12-18,2018-12-18 20:00:00.000,2018-12-18 20:00:03.000,1,AAPL,US0378331005,210832,5.463072e+09,2.385438e+09,2.223513e+09,...,49115,2.393152e+09,2.215799e+09,109151,101676,4.449036e+08,4.092173e+08,12147,10777,2018-12-18
1,2018-08-14,2018-08-14 20:00:00.000,2018-08-14 20:00:03.000,1,AAPL,US0378331005,151689,3.856322e+09,1.474591e+09,1.868593e+09,...,27639,1.467064e+09,1.876120e+09,70904,80783,2.683653e+08,2.447718e+08,7061,5936,2018-08-14
2,2018-07-16,2018-07-16 20:00:00.000,2018-07-16 20:00:03.000,1,AAPL,US0378331005,103081,2.785276e+09,1.328447e+09,1.141238e+09,...,20968,1.041861e+09,1.427823e+09,49829,53250,1.629598e+08,1.526315e+08,4599,4564,2018-07-16
3,2018-11-28,2018-11-28 20:00:00.000,2018-11-28 20:00:03.000,1,AAPL,US0378331005,313599,7.960034e+09,3.256012e+09,3.072701e+09,...,76186,3.177518e+09,3.151196e+09,162738,150859,8.165596e+08,8.147603e+08,21553,17890,2018-11-28
4,2018-09-18,2018-09-18 20:00:00.000,2018-09-18 20:00:03.000,1,AAPL,US0378331005,262380,6.753731e+09,2.722050e+09,2.946533e+09,...,55632,2.698288e+09,2.970294e+09,133859,128504,5.629012e+08,5.222476e+08,12276,10159,2018-09-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018-12-06,2018-12-06 20:00:00.000,2018-12-06 20:00:03.000,1,AAPL,US0378331005,319804,7.179479e+09,2.987815e+09,3.015535e+09,...,83500,2.939057e+09,3.064293e+09,158618,161142,6.222574e+08,5.538714e+08,21068,16723,2018-12-06
96,2016-06-23,2016-06-23 20:00:00.000,2016-06-23 20:00:03.000,1,AAPL,US0378331005,184115,3.027101e+09,1.356530e+09,1.358264e+09,...,25055,1.360428e+09,1.354366e+09,88062,96053,1.588484e+08,1.534580e+08,5955,6089,2016-06-23
97,2016-09-06,2016-09-06 20:00:00.000,2016-09-06 20:00:03.000,1,AAPL,US0378331005,135788,2.614388e+09,1.198243e+09,1.072781e+09,...,22121,1.194970e+09,1.076053e+09,68267,67520,1.735878e+08,1.697767e+08,6597,6188,2016-09-06
98,2016-04-29,2016-04-29 20:00:00.000,2016-04-29 20:00:03.000,1,AAPL,US0378331005,360069,5.965174e+09,2.462544e+09,2.554573e+09,...,68801,2.438964e+09,2.578154e+09,174189,185879,5.149547e+08,4.331017e+08,27126,15264,2016-04-29
99,2018-08-22,2018-08-22 20:00:00.000,2018-08-22 20:00:03.000,1,AAPL,US0378331005,140097,3.992977e+09,1.493493e+09,1.922872e+09,...,28696,1.472677e+09,1.943688e+09,67201,72893,2.962032e+08,2.804090e+08,7184,6752,2018-08-22

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,US0378331005,646606,9.724189e+09,4.725496e+09,3.810025e+09,...,129159,4.727787e+09,3.807734e+09,374680,271926,5.098485e+08,6.788193e+08,36482,31635,2024-01-03
1,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,US0378331005,585481,8.165045e+09,3.881386e+09,3.334522e+09,...,105856,3.852553e+09,3.363355e+09,340434,245045,5.133696e+08,4.357680e+08,33131,20739,2024-01-17
2,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,US0378331005,547902,7.957503e+09,3.802293e+09,3.215115e+09,...,100340,3.825576e+09,3.191832e+09,330178,217724,5.180600e+08,4.220353e+08,33851,20631,2024-01-10
3,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,US0378331005,704292,1.117920e+10,4.903110e+09,4.848632e+09,...,141705,4.847464e+09,4.904278e+09,404312,299980,8.093261e+08,6.181319e+08,52306,25291,2024-01-04
4,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,US0378331005,527086,7.671505e+09,3.881987e+09,2.852431e+09,...,91847,3.861606e+09,2.872812e+09,319856,207229,4.602497e+08,4.768365e+08,25365,23987,2024-01-23
5,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,US0378331005,776996,1.390008e+10,6.246976e+09,6.053243e+09,...,144853,6.214716e+09,6.085502e+09,438270,338726,8.478937e+08,7.519638e+08,39267,31652,2024-01-18
6,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,US0378331005,672809,1.207373e+10,5.862620e+09,5.141551e+09,...,121439,5.773583e+09,5.230588e+09,390683,282126,5.512614e+08,5.182930e+08,32778,25601,2024-01-19
7,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,US0378331005,470667,6.941078e+09,3.434455e+09,2.791790e+09,...,82988,3.442340e+09,2.783905e+09,286746,183919,4.031384e+08,3.116944e+08,29492,17846,2024-01-12
8,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,US0378331005,673751,9.609475e+09,4.544943e+09,4.074560e+09,...,129057,4.461645e+09,4.157858e+09,380986,292765,5.103516e+08,4.796210e+08,36375,23940,2024-01-31
9,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,US0378331005,754607,1.047012e+10,5.324264e+09,4.027101e+09,...,140374,5.294603e+09,4.056762e+09,436132,318474,5.894122e+08,5.293452e+08,44543,28370,2024-01-16
10,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,US0378331005,635508,9.891279e+09,4.744796e+09,4.130843e+09,...,110062,4.674756e+09,4.200882e+09,371266,264241,5.258774e+08,4.897631e+08,31153,25473,2024-01-25
11,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,US0378331005,990710,1.406572e+10,6.739308e+09,5.706525e+09,...,203637,6.718754e+09,5.727078e+09,558557,432153,8.381063e+08,7.817779e+08,69901,36457,2024-01-02
12,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,US0378331005,589939,7.998797e+09,3.962558e+09,3.250855e+09,...,105210,3.856046e+09,3.357367e+09,362427,227509,4.216349e+08,3.637488e+08,31244,22398,2024-01-29
13,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,US0378331005,682093,9.944367e+09,4.911012e+09,3.772293e+09,...,131699,4.867751e+09,3.815554e+09,384467,297626,6.964564e+08,5.646060e+08,41131,26399,2024-01-30
14,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,US0378331005,530828,7.405986e+09,3.703151e+09,2.830986e+09,...,98430,3.666996e+09,2.867141e+09,316857,213971,4.414514e+08,4.303981e+08,32092,23895,2024-01-09
15,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,US0378331005,659234,1.011811e+10,5.140608e+09,3.874886e+09,...,122228,5.194947e+09,3.820547e+09,410217,249013,6.224780e+08,4.801413e+08,45877,26645,2024-01-08
16,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,US0378331005,587962,9.457487e+09,4.396980e+09,4.025837e+09,...,105630,4.417371e+09,4.005446e+09,348478,239484,4.926221e+08,5.420481e+08,27663,27274,2024-01-24
17,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,US0378331005,708796,1.073480e+10,5.462671e+09,4.016835e+09,...,125197,5.574549e+09,3.904957e+09,422318,286474,6.501838e+08,6.051145e+08,34884,29397,2024-01-22
18,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,US0378331005,573585,8.242853e+09,3.807336e+09,3.516374e+09,...,105517,3.842186e+09,3.481524e+09,329199,244386,5.234246e+08,3.957190e+08,35207,19919,2024-01-11
19,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,US0378331005,675337,1.058505e+10,4.966160e+09,4.240622e+09,...,132526,4.993287e+09,4.213496e+09,389878,285451,7.655776e+08,6.126888e+08,46270,25440,2024-01-05
20,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,US0378331005,527636,8.032383e+09,3.920825e+09,3.412678e+09,...,92767,3.889177e+09,3.444326e+09,312636,214999,3.436649e+08,3.552153e+08,24908,19583,2024-01-26

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1", target_location="./data", asof_date='2026-01-08')

Downloading using native python implementation for lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1", target_location="./data")