In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_with_isin_daily_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-04-11,2007-04-11 17:08:00.000,2007-04-11 20:00:03.000,1,A,US00846U1016,8888,9.031479e+07,3.224747e+07,5.719955e+07,...,951,6.260319e+06,8.318670e+07,606,8280,165129.88,702643.94,16,29,2007-04-11
1,2007-04-11,2007-04-11 17:44:00.000,2007-04-11 20:00:03.000,1,AA,US0138171014,50483,5.891779e+08,2.976314e+08,2.819314e+08,...,5276,2.722001e+08,3.073628e+08,26231,24252,4394765.95,5220276.65,369,372,2007-04-11
2,2007-04-11,2007-04-11 16:00:00.000,2007-04-11 20:00:03.000,0,AAA,US02143N1037,79,1.263565e+06,7.193882e+05,3.770008e+05,...,21,5.450847e+05,5.513042e+05,12,9,147105.78,20070.06,4,1,2007-04-11
3,2007-04-11,2007-04-11 15:29:00.000,2007-04-11 20:00:03.000,0,AAB.WS,NaN,6,4.345000e+04,2.844000e+04,1.501000e+04,...,1,1.145500e+04,3.199500e+04,1,4,0.00,0.00,0,0,2007-04-11
4,2007-04-11,2007-04-11 16:01:00.000,2007-04-11 20:00:03.000,1,AAC,US8293571027,439,7.566798e+05,3.601416e+05,3.570997e+05,...,116,3.640801e+05,3.531613e+05,20,16,12571.76,26866.68,14,18,2007-04-11
5,2007-04-11,2007-04-11 15:58:00.000,2007-04-11 20:00:03.000,0,AACC,US04543P1003,561,1.794535e+06,1.026214e+06,7.639949e+05,...,140,9.295608e+05,8.606485e+05,55,37,0.00,4325.88,0,2,2007-04-11
6,2007-04-11,2007-04-11 17:08:00.000,2007-04-11 20:00:03.000,1,AAI,US00949P1084,14006,4.388519e+07,2.287587e+07,2.072226e+07,...,1326,2.196770e+07,2.163042e+07,859,808,106779.28,180277.27,35,53,2007-04-11
7,2007-04-11,2007-04-11 16:00:00.000,2007-04-11 20:00:03.000,0,AAME,US0482091008,32,7.206728e+04,1.202253e+04,4.778634e+04,...,12,1.516230e+04,4.464657e+04,10,16,4408.89,7849.52,2,2,2007-04-11
8,2007-04-11,2007-04-11 15:59:00.000,2007-04-11 20:00:03.000,0,AANB,US0033901010,3,7.594300e+03,1.484580e+03,6.109730e+03,...,2,3.797150e+03,3.797150e+03,0,0,0.00,0.00,0,0,2007-04-11
9,2007-04-11,2007-04-11 16:04:00.000,2007-04-11 20:00:03.000,1,AAON,US0003602069,228,8.185301e+05,2.464567e+05,5.597501e+05,...,72,4.534740e+05,3.527328e+05,64,33,6595.44,5727.80,2,2,2007-04-11

## Retrieve data for a specific date range using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_daily_v1_2', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-22,2024-01-22 19:01:00.000,2024-01-22 20:00:03.000,1,A,US00846U1016,24845,1.562852e+08,99673223.95,53642515.61,...,5213,1.284889e+08,24826835.88,18945,5900,1547909.85,1421592.18,328,278,2024-01-22
1,2024-01-22,2024-01-22 19:56:00.000,2024-01-22 20:00:03.000,1,AA,US0138721065,46609,1.467629e+08,93640844.80,47984892.92,...,6431,1.359445e+08,5681230.88,44857,1735,3238229.37,1898896.03,1128,672,2024-01-22
2,2024-01-22,2024-01-22 20:01:00.000,2024-01-22 20:00:03.000,1,AAA,US46144X6105,24,6.091857e+04,18807.68,37077.54,...,8,2.794259e+04,27942.59,2,0,5033.35,0.00,5,0,2024-01-22
3,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAAU,US38150K1034,1926,6.144968e+07,20750638.57,33377130.97,...,401,4.678125e+07,7346518.43,1544,161,4047935.22,3273973.61,179,131,2024-01-22
4,2024-01-22,2024-01-22 19:07:00.000,2024-01-22 20:00:03.000,1,AACG,US00211V1061,168,1.922372e+04,467.76,16656.42,...,42,8.363580e+03,8760.56,3,10,477.02,1622.58,11,14,2024-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-22,2024-01-22 16:01:00.000,2024-01-22 20:00:03.000,1,ACNT,US8715651076,143,4.586393e+04,18901.52,26846.77,...,43,2.354488e+04,22203.40,5,1,83.98,31.56,1,2,2024-01-22
96,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,ACON,US6551872012,2005,2.726378e+05,53796.58,179751.56,...,723,2.956752e+04,203980.59,130,1875,21255.57,17834.08,229,251,2024-01-22
97,2024-01-22,2024-01-22 14:26:00.000,2024-01-22 20:00:03.000,0,ACONW,US6551871105,1,3.900000e+00,0.00,0.00,...,1,0.000000e+00,0.00,0,0,3.90,0.00,1,0,2024-01-22
98,2024-01-22,2024-01-22 19:14:00.000,2024-01-22 20:00:03.000,1,ACOR,US00484M7002,111,2.359460e+05,180210.96,49210.67,...,39,1.853516e+05,44070.03,60,51,6473.54,50.88,3,2,2024-01-22
99,2024-01-22,2024-01-22 19:57:00.000,2024-01-22 20:00:03.000,1,ACP,US0030571063,2162,3.984211e+06,2186135.99,1540099.86,...,419,1.804736e+06,1921499.75,40,54,191918.87,66056.38,87,22,2024-01-22

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_daily_v1_2',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-08,2007-02-08 20:00:00.000,2007-02-08 20:00:03.000,1,AAPL,US0378331005,112598,2.032911e+09,9.969550e+08,9.863288e+08,...,15532,1.010496e+09,9.727882e+08,57111,55476,28308223.18,21319423.81,1565,1177,2007-02-08
1,2007-01-11,2007-01-11 20:00:00.000,2007-01-11 20:00:03.000,1,AAPL,US0378331005,231957,4.861693e+09,2.323565e+09,2.408443e+09,...,32571,2.103386e+09,2.628622e+09,101463,130149,67452135.59,62232804.83,3154,2943,2007-01-11
2,2007-02-05,2007-02-05 20:00:00.000,2007-02-05 20:00:03.000,1,AAPL,US0378331005,96779,1.695616e+09,7.598101e+08,8.929953e+08,...,11835,3.026589e+08,1.350147e+09,15505,76943,23822862.93,18987486.66,1347,1047,2007-02-05
3,2007-02-26,2007-02-26 20:00:00.000,2007-02-26 20:00:03.000,1,AAPL,US0378331005,102005,1.935809e+09,9.507773e+08,9.310895e+08,...,14418,1.150675e+09,7.311919e+08,62623,39356,27594296.76,26347891.02,1446,1364,2007-02-26
4,2007-02-13,2007-02-13 19:59:00.000,2007-02-13 20:00:03.000,1,AAPL,US0378331005,100533,1.735861e+09,7.666717e+08,9.226778e+08,...,11817,4.338331e+08,1.255516e+09,27679,71790,25993288.65,20518113.71,1515,1128,2007-02-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-06-19,2007-06-19 20:00:00.000,2007-06-19 20:00:03.000,1,AAPL,US0378331005,144641,4.027333e+09,1.853637e+09,2.040225e+09,...,24733,1.390324e+09,2.503538e+09,52027,92566,78603398.20,54868277.98,2780,1934,2007-06-19
96,2007-06-20,2007-06-20 20:00:00.000,2007-06-20 20:00:03.000,1,AAPL,US0378331005,142863,3.816616e+09,1.755577e+09,1.955162e+09,...,23716,1.104609e+09,2.606130e+09,43290,99533,58399867.46,47477556.83,2147,1748,2007-06-20
97,2007-06-28,2007-06-28 20:00:00.000,2007-06-28 20:00:03.000,1,AAPL,US0378331005,126974,3.538269e+09,1.643460e+09,1.773569e+09,...,22593,9.583380e+08,2.458692e+09,38737,87995,68841415.16,52397943.48,2499,1887,2007-06-28
98,2007-04-27,2007-04-27 19:59:00.000,2007-04-27 20:00:03.000,1,AAPL,US0378331005,92993,2.241219e+09,1.090425e+09,1.065621e+09,...,13763,1.295624e+09,8.604224e+08,52990,39764,44798473.32,40374780.73,1859,1631,2007-04-27
99,2007-06-15,2007-06-15 20:00:00.000,2007-06-15 20:00:03.000,1,AAPL,US0378331005,106493,2.661257e+09,1.361937e+09,1.226623e+09,...,12410,2.414433e+09,1.741262e+08,98547,7572,42480714.27,30217103.23,1580,1190,2007-06-15

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_daily_v1_2',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,US0378331005,573593,8.499696e+09,4.130628e+09,3.580027e+09,...,105521,4.536398e+09,3.174257e+09,254275,319317,4.970836e+08,2.919579e+08,35207,19919,2024-01-11
1,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,US0378331005,646673,9.850288e+09,4.962282e+09,3.895570e+09,...,129184,5.887301e+09,2.970551e+09,337365,309308,5.323861e+08,4.600496e+08,36499,31646,2024-01-03
2,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,US0378331005,659244,1.029335e+10,5.566822e+09,3.684005e+09,...,122232,7.146958e+09,2.103868e+09,426813,231163,6.522098e+08,3.903147e+08,45879,26647,2024-01-08
3,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,US0378331005,754695,1.064378e+10,5.534916e+09,4.143439e+09,...,140422,6.128546e+09,3.549808e+09,468751,285943,5.864017e+08,3.790271e+08,44587,28380,2024-01-16
4,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,US0378331005,672874,1.247752e+10,6.400096e+09,5.082925e+09,...,121471,7.644141e+09,3.838881e+09,532463,140411,5.415680e+08,4.529306e+08,32810,25615,2024-01-19
5,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,US0378331005,585486,8.177438e+09,4.069354e+09,3.347696e+09,...,105859,4.263990e+09,3.153060e+09,301897,283518,4.652283e+08,2.951595e+08,33131,20739,2024-01-17
6,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,US0378331005,587965,9.464530e+09,4.085500e+09,4.528231e+09,...,105631,2.183976e+09,6.429755e+09,217942,370023,4.297140e+08,4.210849e+08,27663,27274,2024-01-24
7,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,US0378331005,704321,1.160613e+10,5.085703e+09,5.255791e+09,...,141719,3.824969e+09,6.516526e+09,285462,418792,8.521401e+08,4.124940e+08,52306,25296,2024-01-04
8,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,US0378331005,635511,9.921383e+09,4.652936e+09,4.391468e+09,...,110064,4.187532e+09,4.856872e+09,305904,329605,4.808354e+08,3.961437e+08,31153,25473,2024-01-25
9,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,US0378331005,673799,9.649775e+09,4.751167e+09,4.091920e+09,...,129080,4.310247e+09,4.532841e+09,419311,254487,4.901400e+08,3.165473e+08,36382,23948,2024-01-31
10,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,US0378331005,470683,6.976981e+09,3.291219e+09,3.002975e+09,...,82997,1.538530e+09,4.755664e+09,141921,326966,4.153750e+08,2.674128e+08,29498,17852,2024-01-12
11,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,US0378331005,530847,7.457587e+09,4.198502e+09,2.517493e+09,...,98441,5.814233e+09,9.017617e+08,453102,77735,4.232342e+08,3.183575e+08,32096,23905,2024-01-09
12,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,US0378331005,527096,7.690177e+09,4.095794e+09,2.835907e+09,...,91853,4.247200e+09,2.684500e+09,294083,229944,3.875323e+08,3.709440e+08,25365,23987,2024-01-23
13,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,US0378331005,547962,8.236493e+09,4.186085e+09,3.235029e+09,...,100367,5.489186e+09,1.931929e+09,394721,153237,4.965947e+08,3.187833e+08,33865,20667,2024-01-10
14,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,US0378331005,990770,1.412446e+10,6.623133e+09,6.059657e+09,...,203661,5.313069e+09,7.369722e+09,246489,744247,9.361314e+08,5.055404e+08,69922,36466,2024-01-02
15,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,US0378331005,708837,1.076401e+10,5.608460e+09,4.200627e+09,...,125211,4.332346e+09,5.476742e+09,387027,321791,5.172395e+08,4.376786e+08,34889,29419,2024-01-22
16,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,US0378331005,675348,1.073244e+10,5.060611e+09,4.557467e+09,...,132532,3.601085e+09,6.016993e+09,349875,324250,7.120352e+08,4.023235e+08,46270,25440,2024-01-05
17,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,US0378331005,682124,9.997138e+09,5.243468e+09,3.764531e+09,...,131716,4.989186e+09,4.018813e+09,331875,350249,5.983342e+08,3.908052e+08,41139,26414,2024-01-30
18,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,US0378331005,590109,8.135219e+09,3.895651e+09,3.483823e+09,...,105286,2.352413e+09,5.027061e+09,218967,369775,4.377972e+08,3.179474e+08,31284,22478,2024-01-29
19,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,US0378331005,777010,1.407412e+10,6.441001e+09,6.411099e+09,...,144863,6.152252e+09,6.699848e+09,461588,313288,6.676443e+08,5.543803e+08,39269,31654,2024-01-18
20,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,US0378331005,527653,8.164333e+09,3.866420e+09,3.615050e+09,...,92776,4.173273e+09,3.308197e+09,306436,220072,3.827252e+08,3.001382e+08,24914,19586,2024-01-26

## Download data file for a specific date using asof_date

In [5]:
Unifier.replicate(name="lseg_us_eqt_flow_with_isin_daily_v1_2", target_location="./data", asof_date='2026-01-12')

Starting native python replication for lseg_us_eqt_flow_with_isin_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_with_isin_daily_v1_2. Downloaded 1 files.