In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [2]:
pip install unifier

Requirement already satisfied: unifier in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (0.1.20)
Requirement already satisfied: requests in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (3.0.1)
Requirement already satisfied: boto3 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (1.42.75)
Requirement already satisfied: botocore<1.43.0,>=1.42.75 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.42.75)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Simply Import and initialize Unifier and Go!

In [3]:
from unifier import unifier as Unifier

In [4]:
Unifier.user = 'clement.perroud@cfm.com'
Unifier.token ='0458d4f1-4b1d-440c-aa16-daf2d07c87c6'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name="lseg_us_equity_flow_1min_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CL,41,137321.6820,36842.40,97129.97,12,29,...,0.00,133972.37,0,41,3349.31,0.00,1,0,2024-01-12,2024-01-12
1,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLB,2,3092.8978,1546.45,1546.45,1,1,...,0.00,3092.90,0,2,0.00,0.00,0,0,2024-01-12,2024-01-12
2,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLBK,1,18.4300,0.00,18.43,0,1,...,0.00,18.43,0,1,0.00,0.00,0,0,2024-01-12,2024-01-12
3,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLBT,2,813.0539,0.00,406.52,0,2,...,406.52,0.00,0,0,0.00,406.53,0,1,2024-01-12,2024-01-12
4,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLDX,5,9059.2900,0.00,9059.29,0,5,...,0.00,9059.29,0,5,0.00,0.00,0,0,2024-01-12,2024-01-12
5,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLF,82,156452.3323,55330.70,99213.67,29,53,...,7631.82,146912.55,4,78,0.00,1907.96,0,1,2024-01-12,2024-01-12
6,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLFD,8,6930.5800,0.00,6930.58,0,8,...,0.00,6930.58,0,8,0.00,0.00,0,0,2024-01-12,2024-01-12
7,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLH,2,2476.0400,2476.04,0.00,2,0,...,2476.04,0.00,2,0,0.00,0.00,0,0,2024-01-12,2024-01-12
8,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLM,12,36348.3698,12116.12,12116.12,6,6,...,9087.09,15145.16,0,2,6058.06,6058.06,2,2,2024-01-12,2024-01-12
9,2024-01-12 12:05:03.000,2024-01-12 12:05:00.000,0,CLMB,3,4714.8000,0.00,4714.80,0,3,...,0.00,4714.80,0,3,0.00,0.00,0,0,2024-01-12,2024-01-12

## Retrieve data for a specific date range using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_1min_v1_2', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IEP,16,74773.8924,11683.42,53743.73,2,11,...,35050.26,30376.89,1,0,4673.37,4673.37,1,1,2024-01-31,2024-01-31
1,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IEUR,2,134718.1250,0.00,134718.12,0,2,...,0.00,134718.12,0,2,0.00,0.00,0,0,2024-01-31,2024-01-31
2,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IEX,26,100653.7260,46455.57,50326.86,12,14,...,0.00,96782.43,0,26,0.00,3871.30,0,1,2024-01-31,2024-01-31
3,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IEZ,5,18548.5800,11129.15,7419.43,3,2,...,7419.43,11129.15,2,3,0.00,0.00,0,0,2024-01-31,2024-01-31
4,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IFF,30,62517.9430,22923.25,37510.77,11,19,...,60434.01,0.00,30,0,0.00,2083.93,0,1,2024-01-31,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IPG,48,66102.7732,41314.23,23411.40,30,18,...,64725.63,0.00,48,0,0.00,1377.14,0,1,2024-01-31,2024-01-31
96,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IPGP,5,1286.2950,514.52,771.78,2,3,...,0.00,1286.30,0,5,0.00,0.00,0,0,2024-01-31,2024-01-31
97,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IPI,6,1986.7600,331.13,1655.63,1,5,...,0.00,1986.76,0,6,0.00,0.00,0,0,2024-01-31,2024-01-31
98,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IQ,13,3704.5500,0.00,3704.55,0,13,...,1852.28,1852.28,0,0,0.00,0.00,0,0,2024-01-31,2024-01-31
99,2024-01-31 12:21:03.000,2024-01-31 12:21:00.000,0,IQDG,1,7990.2240,0.00,0.00,0,1,...,0.00,0.00,0,0,7990.22,0.00,1,0,2024-01-31,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_1min_v1_2',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2023-12-29 14:42:03.000,2023-12-29 14:42:00.000,0,AAPL,572,9.651912e+06,5500914.93,2902323.21,374,198,...,8403238.14,0.0,556,16,809950.66,438723.28,48,26,2023-12-29,2023-12-29
1,2023-12-29 14:56:03.000,2023-12-29 14:56:00.000,0,AAPL,811,1.013778e+07,6125172.11,2650074.47,550,261,...,8775246.58,0.0,801,10,750021.08,612517.21,60,49,2023-12-29,2023-12-29
2,2023-12-29 14:58:03.000,2023-12-29 14:58:00.000,0,AAPL,610,8.529222e+06,4278593.26,2922307.16,359,251,...,7200900.42,0.0,602,8,741063.54,587257.90,53,42,2023-12-29,2023-12-29
3,2023-12-29 14:59:03.000,2023-12-29 14:59:00.000,0,AAPL,565,6.361811e+06,3310393.60,1925433.02,352,213,...,5235826.62,0.0,552,13,653070.85,472913.37,58,42,2023-12-29,2023-12-29
4,2023-12-29 15:01:03.000,2023-12-29 15:01:00.000,0,AAPL,754,1.228503e+07,5376735.09,5637425.27,375,379,...,11014160.36,0.0,736,18,733191.15,537673.51,45,33,2023-12-29,2023-12-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-12-26 12:14:03.000,2023-12-26 12:14:00.000,0,AAPL,610,1.265134e+07,7881163.15,2903586.42,434,176,...,10784749.57,0.0,602,8,1119954.76,746636.51,54,36,2023-12-26,2023-12-26
96,2023-12-26 12:15:03.000,2023-12-26 12:15:00.000,0,AAPL,704,1.259454e+07,5993141.49,4812403.17,402,302,...,10805544.67,0.0,691,13,1198628.30,590369.16,67,33,2023-12-26,2023-12-26
97,2023-12-26 12:18:03.000,2023-12-26 12:18:00.000,0,AAPL,490,5.141232e+06,3095231.23,912830.91,355,135,...,4008062.13,0.0,488,2,629538.55,503630.84,60,48,2023-12-26,2023-12-26
98,2023-12-26 15:07:03.000,2023-12-26 15:07:00.000,0,AAPL,686,1.552286e+07,8508158.59,4457732.02,453,233,...,12965890.61,0.0,680,6,1742362.26,814610.93,77,36,2023-12-26,2023-12-26
99,2023-12-26 15:11:03.000,2023-12-26 15:11:00.000,0,AAPL,456,5.843936e+06,2947599.24,1845453.44,290,166,...,4793052.68,0.0,448,8,768938.93,281944.27,60,22,2023-12-26,2023-12-26

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [10]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_1min_v1_2',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-26 12:26:03.000,2024-01-26 12:26:00.000,0,AAPL,543,7.223674e+06,1609695.34,4177225.90,185,358,...,0.00,5786921.24,5,538,851409.10,585343.76,64,44,2024-01-26,2024-01-26
1,2024-01-26 15:45:03.000,2024-01-26 15:45:00.000,0,AAPL,1149,1.955797e+07,5991649.82,11319452.07,438,711,...,0.00,17311101.89,16,1133,1463868.99,782999.69,86,46,2024-01-26,2024-01-26
2,2024-01-26 12:28:03.000,2024-01-26 12:28:00.000,0,AAPL,618,9.129676e+06,2422761.94,5140982.65,228,390,...,0.00,7563744.59,13,605,945468.07,620463.42,64,42,2024-01-26,2024-01-26
3,2024-01-26 15:46:03.000,2024-01-26 15:46:00.000,0,AAPL,1619,2.952052e+07,8469600.79,18716997.23,529,1085,...,0.00,27186598.02,42,1577,1221664.70,1112261.89,67,61,2024-01-26,2024-01-26
4,2024-01-26 15:47:03.000,2024-01-26 15:47:00.000,0,AAPL,1205,2.376606e+07,9861436.43,11557603.51,576,629,...,0.00,21419039.94,37,1168,1498938.34,848083.53,76,43,2024-01-26,2024-01-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-26 12:23:03.000,2024-01-26 12:23:00.000,0,AAPL,534,9.965538e+06,5617279.14,2855294.71,346,188,...,8472573.85,0.00,522,12,839792.56,653171.99,45,35,2024-01-26,2024-01-26
96,2024-01-26 15:43:03.000,2024-01-26 15:43:00.000,0,AAPL,1275,1.978384e+07,7789400.17,9542791.04,608,667,...,0.00,17332191.21,44,1231,1644773.74,806870.14,106,52,2024-01-26,2024-01-26
97,2024-01-26 12:24:03.000,2024-01-26 12:24:00.000,0,AAPL,568,7.918428e+06,2718474.39,4056800.24,232,336,...,3178523.90,3596750.73,265,303,515813.09,627340.24,37,45,2024-01-26,2024-01-26
98,2024-01-26 12:25:03.000,2024-01-26 12:25:00.000,0,AAPL,804,1.153297e+07,3758257.92,6325922.68,317,487,...,0.00,10084180.60,18,786,788947.27,659846.81,55,46,2024-01-26,2024-01-26
99,2024-01-26 12:27:03.000,2024-01-26 12:27:00.000,0,AAPL,606,6.906783e+06,1618421.15,4387972.84,190,416,...,0.00,6006393.99,13,593,547071.94,353317.29,48,31,2024-01-26,2024-01-26

## Download data file for a specific date using asof_date

In [14]:
Unifier.replicate(name="lseg_us_equity_flow_1min_v1_2", target_location="./data", asof_date='2012-01-12')

Downloading using native python implementation for lseg_us_equity_flow_1min_v1_2...
Found 1 files to download.
Native replication completed for lseg_us_equity_flow_1min_v1_2. Downloaded 1 files.