In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_equity_flow_daily_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2009-12-24,2009-12-24 13:01:00.000,2009-12-24 20:00:03.000,0,A,3607,2.264907e+07,9.350640e+06,1.260416e+07,1433,...,490,9.278514e+06,1.267629e+07,1425,2181,1.181110e+05,5.761553e+05,11,74,2009-12-24
1,2009-12-24,2009-12-24 16:10:00.000,2009-12-24 20:00:03.000,1,AA,36306,2.317330e+08,1.073039e+08,9.388428e+07,19177,...,4332,1.071451e+08,9.404303e+07,19193,17113,1.585936e+07,1.468551e+07,1530,1375,2009-12-24
2,2009-12-24,2009-12-24 12:59:00.000,2009-12-24 20:00:03.000,0,AAC,198,1.299097e+05,6.577373e+04,6.114778e+04,104,...,49,6.395918e+04,6.296233e+04,109,88,1.813170e+03,1.175010e+03,4,7,2009-12-24
3,2009-12-24,2009-12-24 13:01:00.000,2009-12-24 20:00:03.000,0,AACC,100,1.090004e+05,7.402592e+04,3.253810e+04,68,...,23,7.827123e+04,2.829279e+04,70,29,0.000000e+00,2.436400e+03,0,1,2009-12-24
4,2009-12-24,2009-12-24 13:15:00.000,2009-12-24 20:00:03.000,0,AAI,4641,5.921789e+06,2.506590e+06,2.986065e+06,2033,...,381,2.514038e+06,2.978617e+06,2046,2594,2.179640e+05,2.111696e+05,54,62,2009-12-24
5,2009-12-24,2009-12-24 10:42:00.000,2009-12-24 20:00:03.000,0,AAME,2,2.710000e+02,2.030000e+02,6.800000e+01,1,...,1,2.710000e+02,0.000000e+00,2,0,0.000000e+00,0.000000e+00,0,0,2009-12-24
6,2009-12-24,2009-12-24 13:02:00.000,2009-12-24 20:00:03.000,0,AAN,591,2.568096e+06,9.844656e+05,1.447923e+06,232,...,171,9.517934e+05,1.480595e+06,233,356,9.956156e+04,3.614561e+04,10,3,2009-12-24
7,2009-12-24,2009-12-24 13:01:00.000,2009-12-24 20:00:03.000,0,AAON,46,1.422979e+05,1.080259e+05,3.228805e+04,33,...,14,1.060419e+05,3.427205e+04,32,13,1.983990e+03,0.000000e+00,1,0,2009-12-24
8,2009-12-24,2009-12-24 13:05:00.000,2009-12-24 20:00:03.000,0,AAP,2754,1.498320e+07,7.213243e+06,7.156901e+06,1383,...,449,7.455258e+06,6.914885e+06,1437,1316,3.593367e+05,2.537166e+05,81,17,2009-12-24
9,2009-12-24,2009-12-24 17:00:00.000,2009-12-24 20:00:03.000,1,AAPL,87340,3.703759e+09,1.697216e+09,1.437638e+09,46423,...,21756,1.686117e+09,1.448738e+09,46464,40875,3.000365e+08,2.688682e+08,4327,4396,2009-12-24

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_daily_v1_2_1', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 19:01:00.000,2024-01-31 20:00:03.000,1,A,20346,1.345426e+08,6.403340e+07,6.753254e+07,10001,...,5704,8.645961e+07,4.510633e+07,10186,10159,1416810.66,1559848.91,284,276,2024-01-31
1,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AA,50628,1.631646e+08,5.519060e+07,8.529827e+07,24397,...,7666,5.526160e+07,8.522727e+07,24386,26242,13369037.12,9306669.06,1224,990,2024-01-31
2,2024-01-31,2024-01-31 20:01:00.000,2024-01-31 20:00:03.000,1,AAA,59,8.715196e+04,6.851273e+04,1.344052e+04,48,...,17,7.013964e+04,1.181361e+04,44,14,5023.58,175.10,2,2,2024-01-31
3,2024-01-31,2024-01-31 20:01:00.000,2024-01-31 20:00:03.000,1,AAAU,2126,4.138189e+07,1.843880e+07,1.843155e+07,1048,...,525,1.831460e+07,1.855575e+07,1045,1081,2018972.43,2492565.62,134,195,2024-01-31
4,2024-01-31,2024-01-31 16:00:00.000,2024-01-31 20:00:03.000,1,AACG,55,1.576397e+03,3.976600e+02,9.448800e+02,12,...,16,4.458900e+02,8.966500e+02,15,40,63.62,170.24,1,10,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 19:54:00.000,2024-01-31 20:00:03.000,1,ACN,44842,7.983049e+08,4.941465e+08,2.806495e+08,21257,...,13920,3.228296e+08,4.519663e+08,21871,22971,11647353.96,11861586.96,1218,1326,2024-01-31
96,2024-01-31,2024-01-31 16:36:00.000,2024-01-31 20:00:03.000,1,ACNB,777,1.866312e+06,8.223065e+05,1.012887e+06,281,...,221,8.890905e+05,9.461026e+05,304,473,1713.55,29405.73,8,25,2024-01-31
97,2024-01-31,2024-01-31 16:01:00.000,2024-01-31 20:00:03.000,1,ACNT,309,8.027972e+04,4.096789e+04,1.799592e+04,237,...,86,4.530503e+04,1.365877e+04,240,67,684.83,20631.07,2,3,2024-01-31
98,2024-01-31,2024-01-31 19:41:00.000,2024-01-31 20:00:03.000,1,ACON,1553,6.259741e+05,2.157043e+05,3.066701e+05,759,...,440,2.110455e+05,3.113290e+05,749,804,23441.91,80157.86,88,110,2024-01-31
99,2024-01-31,2024-01-31 12:52:00.000,2024-01-31 20:00:03.000,0,ACONW,10,6.135750e+02,1.868000e+01,5.422700e+02,0,...,8,5.605000e+01,5.049000e+02,1,8,0.00,52.62,0,2,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_daily_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2010-09-07,2010-09-07 20:00:00.000,2010-09-07 20:00:03.000,1,AAPL,69713,3.031655e+09,1.271227e+09,1.302757e+09,34566,...,19619,1.272090e+09,1.301894e+09,34637,35076,2.302370e+08,2.274338e+08,3250,3319,2010-09-07
1,2011-01-27,2011-01-27 20:00:00.000,2011-01-27 20:00:03.000,1,AAPL,56707,3.383849e+09,1.429972e+09,1.506897e+09,27644,...,16399,1.383858e+09,1.553011e+09,27253,29454,2.305132e+08,2.164666e+08,2362,2450,2011-01-27
2,2010-04-19,2010-04-19 20:02:00.000,2010-04-19 20:00:03.000,1,AAPL,110689,4.888897e+09,2.096929e+09,2.149614e+09,54755,...,29698,2.097154e+09,2.149389e+09,54870,55819,3.320353e+08,3.103188e+08,4985,4481,2010-04-19
3,2010-12-10,2010-12-10 19:59:00.000,2010-12-10 20:00:03.000,1,AAPL,52067,2.817381e+09,1.266739e+09,1.203318e+09,25721,...,14387,1.268947e+09,1.201111e+09,25877,26190,1.718210e+08,1.755032e+08,2062,2299,2010-12-10
4,2010-10-19,2010-10-19 20:00:00.000,2010-10-19 20:00:03.000,1,AAPL,256450,1.314669e+10,5.733391e+09,5.672261e+09,127987,...,77418,5.729551e+09,5.676101e+09,128482,127968,8.600757e+08,8.809599e+08,12058,12098,2010-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2011-01-24,2011-01-24 20:00:00.000,2011-01-24 20:00:03.000,1,AAPL,112029,6.738503e+09,3.266222e+09,2.510840e+09,61293,...,31887,3.155300e+09,2.621763e+09,59394,52634,4.889833e+08,4.724575e+08,5524,5019,2011-01-24
96,2010-04-20,2010-04-20 20:02:00.000,2010-04-20 20:00:03.000,1,AAPL,143882,6.486266e+09,2.875390e+09,2.929734e+09,71161,...,37253,2.880694e+09,2.924430e+09,71980,71902,3.528550e+08,3.282865e+08,5407,4509,2010-04-20
97,2010-01-19,2010-01-19 20:00:00.000,2010-01-19 20:00:03.000,1,AAPL,120526,5.081640e+09,2.371631e+09,2.106083e+09,62903,...,29214,2.368775e+09,2.108940e+09,63065,57461,3.120419e+08,2.918830e+08,4662,4503,2010-01-19
98,2009-07-15,2009-07-15 20:00:00.000,2009-07-15 20:00:03.000,1,AAPL,89437,2.500632e+09,1.215006e+09,1.037081e+09,46233,...,18316,1.216938e+09,1.035150e+09,46763,42674,1.242257e+08,1.243181e+08,2158,2463,2009-07-15
99,2010-09-16,2010-09-16 20:00:00.000,2010-09-16 20:00:03.000,1,AAPL,131870,6.168242e+09,2.870884e+09,2.569232e+09,69233,...,31461,2.867245e+09,2.572871e+09,69932,61938,3.868189e+08,3.413075e+08,5584,4483,2010-09-16

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_daily_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,675337,1.058505e+10,4.966160e+09,4.240622e+09,390963,...,132526,4.993287e+09,4.213496e+09,389878,285451,7.655776e+08,6.126888e+08,46270,25440,2024-01-05
1,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,589939,7.998797e+09,3.962558e+09,3.250855e+09,364379,...,105210,3.856046e+09,3.357367e+09,362427,227509,4.216349e+08,3.637488e+08,31244,22398,2024-01-29
2,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,708796,1.073480e+10,5.462671e+09,4.016835e+09,422157,...,125197,5.574549e+09,3.904957e+09,422318,286474,6.501838e+08,6.051145e+08,34884,29397,2024-01-22
3,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,547902,7.957503e+09,3.802293e+09,3.215115e+09,331119,...,100340,3.825576e+09,3.191832e+09,330178,217724,5.180600e+08,4.220353e+08,33851,20631,2024-01-10
4,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,527636,8.032383e+09,3.920825e+09,3.412678e+09,313998,...,92767,3.889177e+09,3.444326e+09,312636,214999,3.436649e+08,3.552153e+08,24908,19583,2024-01-26
5,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,587962,9.457487e+09,4.396980e+09,4.025837e+09,348045,...,105630,4.417371e+09,4.005446e+09,348478,239484,4.926221e+08,5.420481e+08,27663,27274,2024-01-24
6,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,776996,1.390008e+10,6.246976e+09,6.053243e+09,438197,...,144853,6.214716e+09,6.085502e+09,438270,338726,8.478937e+08,7.519638e+08,39267,31652,2024-01-18
7,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,585481,8.165045e+09,3.881386e+09,3.334522e+09,342783,...,105856,3.852553e+09,3.363355e+09,340434,245045,5.133696e+08,4.357680e+08,33131,20739,2024-01-17
8,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,754607,1.047012e+10,5.324264e+09,4.027101e+09,436856,...,140374,5.294603e+09,4.056762e+09,436132,318474,5.894122e+08,5.293452e+08,44543,28370,2024-01-16
9,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,527086,7.671505e+09,3.881987e+09,2.852431e+09,319880,...,91847,3.861606e+09,2.872812e+09,319856,207229,4.602497e+08,4.768365e+08,25365,23987,2024-01-23
10,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,635508,9.891279e+09,4.744796e+09,4.130843e+09,372405,...,110062,4.674756e+09,4.200882e+09,371266,264241,5.258774e+08,4.897631e+08,31153,25473,2024-01-25
11,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,659234,1.011811e+10,5.140608e+09,3.874886e+09,411671,...,122228,5.194947e+09,3.820547e+09,410217,249013,6.224780e+08,4.801413e+08,45877,26645,2024-01-08
12,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,990710,1.406572e+10,6.739308e+09,5.706525e+09,562908,...,203637,6.718754e+09,5.727078e+09,558557,432153,8.381063e+08,7.817779e+08,69901,36457,2024-01-02
13,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,530828,7.405986e+09,3.703151e+09,2.830986e+09,317939,...,98430,3.666996e+09,2.867141e+09,316857,213971,4.414514e+08,4.303981e+08,32092,23895,2024-01-09
14,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,673751,9.609475e+09,4.544943e+09,4.074560e+09,382567,...,129057,4.461645e+09,4.157858e+09,380986,292765,5.103516e+08,4.796210e+08,36375,23940,2024-01-31
15,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,646606,9.724189e+09,4.725496e+09,3.810025e+09,374656,...,129159,4.727787e+09,3.807734e+09,374680,271926,5.098485e+08,6.788193e+08,36482,31635,2024-01-03
16,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,470667,6.941078e+09,3.434455e+09,2.791790e+09,288123,...,82988,3.442340e+09,2.783905e+09,286746,183919,4.031384e+08,3.116944e+08,29492,17846,2024-01-12
17,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,682093,9.944367e+09,4.911012e+09,3.772293e+09,387356,...,131699,4.867751e+09,3.815554e+09,384467,297626,6.964564e+08,5.646060e+08,41131,26399,2024-01-30
18,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,672809,1.207373e+10,5.862620e+09,5.141551e+09,388844,...,121439,5.773583e+09,5.230588e+09,390683,282126,5.512614e+08,5.182930e+08,32778,25601,2024-01-19
19,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,704292,1.117920e+10,4.903110e+09,4.848632e+09,407780,...,141705,4.847464e+09,4.904278e+09,404312,299980,8.093261e+08,6.181319e+08,52306,25291,2024-01-04
20,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,573585,8.242853e+09,3.807336e+09,3.516374e+09,330364,...,105517,3.842186e+09,3.481524e+09,329199,244386,5.234246e+08,3.957190e+08,35207,19919,2024-01-11

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_equity_flow_daily_v1_2_1", target_location="./data", asof_date='2026-01-12')

Starting native python replication for lseg_us_equity_flow_daily_v1_2_1 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_equity_flow_daily_v1_2_1. Downloaded 1 files.

## Downlaod all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_flow_daily_v1_2_1", target_location="./data")