In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_with_isin_1min_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IWF,US4642876142,12,435023.55,0.00,398771.59,...,3,0.00,398771.59,0,12,0.00,36251.96,0,1,2007-01-26
1,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IWH,NaN,4,0.00,0.00,0.00,...,1,0.00,0.00,4,0,0.00,0.00,0,0,2007-01-26
2,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IWM,US4642876555,41,2180096.00,2073749.85,106346.15,...,1,0.00,2180096.00,0,41,0.00,0.00,0,0,2007-01-26
3,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IWN,US4642876308,1,7958.92,0.00,0.00,...,0,0.00,0.00,1,0,7958.92,0.00,1,0,2007-01-26
4,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IWO,US4642876480,4,78740.00,78740.00,0.00,...,0,39370.00,39370.00,0,0,0.00,0.00,0,0,2007-01-26
5,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IWOV,US46114T5083,9,16926.00,9403.33,7522.67,...,1,15045.33,1880.67,8,1,0.00,0.00,0,0,2007-01-26
6,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IWR,US4642874998,3,30502.99,30502.99,0.00,...,0,0.00,30502.99,0,3,0.00,0.00,0,0,2007-01-26
7,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IXB,NaN,4,0.00,0.00,0.00,...,2,0.00,0.00,0,4,0.00,0.00,0,0,2007-01-26
8,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IXD,NaN,4,0.00,0.00,0.00,...,2,0.00,0.00,0,4,0.00,0.00,0,0,2007-01-26
9,2007-01-26,2007-01-26 14:38:00.000,2007-01-26 14:38:03.000,0,IXE,NaN,4,0.00,0.00,0.00,...,2,0.00,0.00,0,4,0.00,0.00,0,0,2007-01-26

## Retrieve data for a specific date range using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_1min_v1_2', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AADI,US00032Q1040,1,40.71,20.36,20.36,...,1,20.36,20.36,0,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPB,US38747R8842,1,192.60,96.30,96.30,...,1,96.30,96.30,0,0,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPD,US25461A3041,1,396.53,198.26,198.26,...,1,0.00,396.53,0,1,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,US0378331005,163,891117.18,563098.59,328018.59,...,44,194077.67,697039.51,35,127,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,US00287Y1091,4,4122.70,3607.36,515.34,...,2,1030.68,3092.02,0,2,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,BULZ,US0636795595,2,1043.67,782.75,260.92,...,1,521.84,521.84,0,0,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,C,US1729674242,7,21848.50,15606.07,6242.43,...,3,18727.29,3121.21,6,1,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,CAG,US2058871029,1,29.45,14.72,14.72,...,1,29.45,0.00,1,0,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,CAN,US1347481020,5,2179.00,1525.30,653.70,...,2,1089.50,1089.50,0,0,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,CATX,US46489V1044,1,11.40,5.70,5.70,...,1,5.70,5.70,0,0,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_1min_v1_2',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-02,2007-02-02 14:39:00.000,2007-02-02 14:39:03.000,0,AAPL,US0378331005,125,2.159642e+06,596061.28,1459918.19,...,26,0.00,2055979.47,2,123,51831.41,51831.41,3,3,2007-02-02
1,2007-02-02,2007-02-02 14:40:00.000,2007-02-02 14:40:03.000,0,AAPL,US0378331005,133,1.818647e+06,382873.07,1408425.93,...,16,150414.42,1640884.58,12,121,13674.04,13674.04,1,1,2007-02-02
2,2007-02-02,2007-02-02 14:41:00.000,2007-02-02 14:41:03.000,0,AAPL,US0378331005,192,3.014673e+06,1515187.17,1436680.07,...,18,31402.84,2920464.40,6,186,62805.69,0.00,4,0,2007-02-02
3,2007-02-02,2007-02-02 14:42:00.000,2007-02-02 14:42:03.000,0,AAPL,US0378331005,299,6.107402e+06,1378761.34,4687788.54,...,14,183834.84,5882715.03,9,290,0.00,40852.19,0,2,2007-02-02
4,2007-02-02,2007-02-02 14:43:00.000,2007-02-02 14:43:03.000,0,AAPL,US0378331005,76,9.920526e+05,300226.44,665719.50,...,8,13053.33,952892.61,2,74,13053.32,13053.32,1,1,2007-02-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-02-02,2007-02-02 16:16:00.000,2007-02-02 16:16:03.000,1,AAPL,US0378331005,16,4.817070e+05,210746.81,270960.19,...,0,30106.69,451600.31,1,15,0.00,0.00,0,0,2007-02-02
96,2007-02-02,2007-02-02 16:17:00.000,2007-02-02 16:17:03.000,1,AAPL,US0378331005,2,2.197000e+05,0.00,219700.00,...,1,0.00,219700.00,0,2,0.00,0.00,0,0,2007-02-02
97,2007-02-02,2007-02-02 16:18:00.000,2007-02-02 16:18:03.000,1,AAPL,US0378331005,6,1.034998e+05,86249.79,17249.96,...,1,17249.96,86249.79,1,5,0.00,0.00,0,0,2007-02-02
98,2007-02-02,2007-02-02 16:19:00.000,2007-02-02 16:19:03.000,1,AAPL,US0378331005,12,6.591160e+05,329558.00,329558.00,...,3,54926.33,604189.67,1,11,0.00,0.00,0,0,2007-02-02
99,2007-02-02,2007-02-02 16:20:00.000,2007-02-02 16:20:03.000,1,AAPL,US0378331005,5,1.267190e+05,25343.80,101375.20,...,2,0.00,126719.00,0,5,0.00,0.00,0,0,2007-02-02

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_with_isin_1min_v1_2',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-22,2024-01-22 04:01:00.000,2024-01-22 04:01:03.000,1,AAPL,US0378331005,127,485364.00,212107.89,273256.11,...,36,36306.76,449057.24,0,108,0,0,0,0,2024-01-22
1,2024-01-22,2024-01-22 04:02:00.000,2024-01-22 04:02:03.000,1,AAPL,US0378331005,122,261691.76,141570.95,120120.81,...,31,169456.14,92235.62,79,43,0,0,0,0,2024-01-22
2,2024-01-22,2024-01-22 04:03:00.000,2024-01-22 04:03:03.000,1,AAPL,US0378331005,39,263949.12,135358.52,128590.60,...,15,0.00,263949.12,0,39,0,0,0,0,2024-01-22
3,2024-01-22,2024-01-22 04:04:00.000,2024-01-22 04:04:03.000,1,AAPL,US0378331005,25,148253.48,88952.09,59301.39,...,8,0.00,148253.48,0,25,0,0,0,0,2024-01-22
4,2024-01-22,2024-01-22 04:05:00.000,2024-01-22 04:05:03.000,1,AAPL,US0378331005,14,20722.64,10361.32,10361.32,...,3,0.00,20722.64,0,14,0,0,0,0,2024-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-22,2024-01-22 05:36:00.000,2024-01-22 05:36:03.000,1,AAPL,US0378331005,19,127557.87,60422.15,67135.72,...,3,127557.87,0.00,19,0,0,0,0,0,2024-01-22
96,2024-01-22,2024-01-22 05:37:00.000,2024-01-22 05:37:03.000,1,AAPL,US0378331005,18,84524.32,51653.75,32870.57,...,4,84524.32,0.00,18,0,0,0,0,0,2024-01-22
97,2024-01-22,2024-01-22 05:38:00.000,2024-01-22 05:38:03.000,1,AAPL,US0378331005,27,144813.79,144813.79,0.00,...,3,144813.79,0.00,27,0,0,0,0,0,2024-01-22
98,2024-01-22,2024-01-22 05:39:00.000,2024-01-22 05:39:03.000,1,AAPL,US0378331005,11,31689.70,31689.70,0.00,...,2,31689.70,0.00,11,0,0,0,0,0,2024-01-22
99,2024-01-22,2024-01-22 05:40:00.000,2024-01-22 05:40:03.000,1,AAPL,US0378331005,10,12291.35,7374.81,4916.54,...,2,12291.35,0.00,10,0,0,0,0,0,2024-01-22

## Download data file for a specific date using asof_date

In [5]:
Unifier.replicate(name="lseg_us_eqt_flow_with_isin_1min_v1_2", target_location="./data", asof_date='2026-01-12')

Starting native python replication for lseg_us_eqt_flow_with_isin_1min_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_with_isin_1min_v1_2. Downloaded 1 files.