In [2]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Requirement already satisfied: unifier in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (0.1.20)
Requirement already satisfied: requests in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (3.0.1)
Requirement already satisfied: boto3 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (1.42.75)
Requirement already satisfied: botocore<1.43.0,>=1.42.75 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.42.75)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Simply Import and initialize Unifier and Go!

In [4]:
from unifier import unifier as Unifier

In [6]:
Unifier.user = 'clement.perroud@cfm.com'
Unifier.token ='0458d4f1-4b1d-440c-aa16-daf2d07c87c6'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name="lseg_us_equity_flow_daily_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2007-05-03 20:00:03.000,2007-05-03 17:56:00.000,1,A,7070,9.366426e+07,3.811282e+07,5.483989e+07,3321,3186,...,4.822213e+07,44730576.04,628,560,341122.72,370424.87,25,43,2007-05-03,2007-05-03
1,2007-05-03 20:00:03.000,2007-05-03 16:01:00.000,1,AA,22009,2.196692e+08,1.097084e+08,1.082094e+08,10723,11133,...,1.655850e+08,52332890.23,16306,5686,713296.54,1038027.08,70,100,2007-05-03,2007-05-03
2,2007-05-03 20:00:03.000,2007-05-03 16:05:00.000,1,AAA,873,1.805448e+07,9.434347e+06,7.938817e+06,476,383,...,1.071989e+07,6653271.70,420,453,470100.78,211214.41,18,10,2007-05-03,2007-05-03
3,2007-05-03 20:00:03.000,2007-05-03 15:54:00.000,0,AAB.WS,9,3.061800e+04,3.737500e+02,3.024425e+04,0,8,...,0.000000e+00,30618.00,0,9,0.00,0.00,0,0,2007-05-03,2007-05-03
4,2007-05-03 20:00:03.000,2007-05-03 17:52:00.000,1,AAC,176,1.392332e+05,7.481442e+04,4.208900e+04,112,58,...,5.510281e+04,61800.61,13,10,17680.81,4649.00,14,8,2007-05-03,2007-05-03
5,2007-05-03 20:00:03.000,2007-05-03 16:01:00.000,1,AACC,1210,3.978197e+06,1.522249e+06,2.413812e+06,518,637,...,1.907715e+06,2028345.79,100,125,31492.77,10642.93,8,2,2007-05-03,2007-05-03
6,2007-05-03 20:00:03.000,2007-05-03 16:04:00.000,1,AAI,5052,1.558678e+07,8.307983e+06,6.990603e+06,2432,2226,...,7.722417e+06,7576168.88,307,301,105414.86,182779.51,25,64,2007-05-03,2007-05-03
7,2007-05-03 20:00:03.000,2007-05-03 15:16:00.000,0,AAME,55,4.265591e+04,2.565570e+04,1.443856e+04,31,23,...,1.902097e+04,21073.30,4,4,2561.64,0.00,2,0,2007-05-03,2007-05-03
8,2007-05-03 20:00:03.000,2007-05-03 16:01:00.000,1,AAON,106,3.426420e+05,1.768575e+05,1.632000e+05,55,50,...,1.307635e+05,209294.04,38,68,2584.50,0.00,1,0,2007-05-03,2007-05-03
9,2007-05-03 20:00:03.000,2007-05-03 16:03:00.000,1,AAP,2635,2.060007e+07,9.334037e+06,1.121757e+07,1195,1435,...,4.511792e+06,16039817.96,507,2117,18611.98,29843.92,3,5,2007-05-03,2007-05-03

## Retrieve data for a specific date range using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_daily_v1_2', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-31 20:00:03.000,2024-01-31 19:01:00.000,1,A,20346,1.345426e+08,6.364153e+07,6.830170e+07,9808,10534,...,8.236222e+07,4.958101e+07,8009,12336,1441446.81,1157926.26,284,276,2024-01-31,2024-01-31
1,2024-01-31 20:00:03.000,2024-01-31 20:00:00.000,1,AA,50629,1.633656e+08,6.069572e+07,9.601453e+07,22743,27878,...,4.979014e+07,1.069201e+08,18210,32347,3738674.20,2916697.35,1224,990,2024-01-31,2024-01-31
2,2024-01-31 20:00:03.000,2024-01-31 20:01:00.000,1,AAA,59,8.715196e+04,6.851273e+04,1.344052e+04,48,10,...,3.972063e+04,4.223263e+04,2,1,5023.58,175.10,2,2,2024-01-31,2024-01-31
3,2024-01-31 20:00:03.000,2024-01-31 20:01:00.000,1,AAAU,2126,4.138189e+07,1.850738e+07,1.767958e+07,894,926,...,1.838491e+07,1.780205e+07,5,12,2227689.24,2967233.72,134,195,2024-01-31,2024-01-31
4,2024-01-31 20:00:03.000,2024-01-31 16:00:00.000,1,AACG,55,1.576397e+03,2.666600e+02,1.075900e+03,6,34,...,6.723800e+02,6.702000e+02,0,0,63.62,170.25,1,10,2024-01-31,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 20:00:03.000,2024-01-31 19:54:00.000,1,ACN,44842,7.983049e+08,4.818308e+08,2.863110e+08,20269,24570,...,2.360871e+08,5.320547e+08,17643,27199,14997019.05,15166029.24,1218,1326,2024-01-31,2024-01-31
96,2024-01-31 20:00:03.000,2024-01-31 16:36:00.000,1,ACNB,777,1.866312e+06,7.977230e+05,1.031034e+06,267,509,...,6.686112e+05,1.160146e+06,242,535,4892.23,32663.48,8,25,2024-01-31,2024-01-31
97,2024-01-31 20:00:03.000,2024-01-31 16:01:00.000,1,ACNT,309,8.027972e+04,4.657849e+04,2.081418e+04,259,49,...,5.296041e+04,1.443225e+04,285,24,867.46,12019.58,2,3,2024-01-31,2024-01-31
98,2024-01-31 20:00:03.000,2024-01-31 19:41:00.000,1,ACON,1553,6.259741e+05,2.142709e+05,3.361392e+05,667,742,...,2.790747e+05,2.713356e+05,15,10,27776.33,47787.61,88,110,2024-01-31,2024-01-31
99,2024-01-31 20:00:03.000,2024-01-31 12:52:00.000,0,ACONW,10,6.135750e+02,1.868000e+01,5.201600e+02,0,9,...,2.821100e+02,2.567400e+02,0,2,0.00,74.73,0,2,2024-01-31,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_daily_v1_2',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2007-01-24 20:00:03.000,2007-01-24 20:00:00.000,1,AAPL,148219,2.778857e+09,1.272891e+09,1.429485e+09,65094,70829,...,7.244373e+08,1.977938e+09,10648,73667,4.712886e+07,29352081.76,2509,1553,2007-01-24,2007-01-24
1,2007-04-11 20:00:03.000,2007-04-11 19:58:00.000,1,AAPL,90178,1.778261e+09,7.733503e+08,9.682233e+08,38637,48679,...,2.570907e+08,1.484483e+09,13452,76708,2.337352e+07,13313386.22,1172,653,2007-04-11,2007-04-11
2,2007-04-12 20:00:03.000,2007-04-12 20:00:00.000,1,AAPL,94822,2.136885e+09,1.067023e+09,1.028432e+09,48286,45503,...,1.292068e+09,8.033875e+08,62653,31676,2.362334e+07,17805869.51,1109,775,2007-04-12,2007-04-12
3,2007-04-04 20:00:03.000,2007-04-04 19:58:00.000,1,AAPL,75736,1.579033e+09,6.906815e+08,8.477731e+08,34081,40981,...,9.356863e+07,1.444886e+09,5372,70349,2.436585e+07,16213036.31,1148,760,2007-04-04,2007-04-04
4,2007-01-10 20:00:03.000,2007-01-10 20:00:00.000,1,AAPL,472060,9.897434e+09,5.006490e+09,4.673504e+09,221927,206092,...,6.494691e+09,3.185303e+09,310734,161253,1.229741e+08,94466025.20,5918,4512,2007-01-10,2007-01-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-06-21 20:00:03.000,2007-06-21 20:00:00.000,1,AAPL,136947,3.733139e+09,1.872319e+09,1.744490e+09,69712,64621,...,2.466124e+09,1.150685e+09,93014,43927,6.763338e+07,48696094.97,2443,1754,2007-06-21,2007-06-21
96,2007-07-20 20:00:03.000,2007-07-20 20:00:00.000,1,AAPL,182393,5.587747e+09,2.732041e+09,2.691276e+09,90243,89455,...,2.876340e+09,2.546978e+09,93248,89143,9.747377e+07,66956286.52,3210,2220,2007-07-20,2007-07-20
97,2007-07-18 20:00:03.000,2007-07-18 20:00:00.000,1,AAPL,126992,3.543079e+09,1.683761e+09,1.773031e+09,61026,64193,...,1.375703e+09,2.081089e+09,49139,77812,4.699626e+07,39291027.40,1659,1382,2007-07-18,2007-07-18
98,2007-06-27 20:00:03.000,2007-06-27 20:00:00.000,1,AAPL,156432,4.085005e+09,2.025488e+09,1.945415e+09,78430,75447,...,1.681851e+09,2.289052e+09,66141,90288,6.574184e+07,48360657.26,2508,1832,2007-06-27,2007-06-27
99,2007-06-04 20:00:03.000,2007-06-04 20:00:00.000,1,AAPL,144699,3.770507e+09,1.907768e+09,1.768571e+09,74328,69268,...,2.281297e+09,1.395042e+09,87650,57048,5.513501e+07,39032709.06,2076,1492,2007-06-04,2007-06-04

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_daily_v1_2',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-23 20:00:03.000,2024-01-23 20:00:00.000,1,AAPL,527096,7.690177e+09,4.095794e+09,2.835907e+09,327963,197667,...,4.247200e+09,2.684500e+09,294083,229944,3.875323e+08,3.709440e+08,25365,23987,2024-01-23,2024-01-23
1,2024-01-10 20:00:03.000,2024-01-10 20:00:00.000,1,AAPL,547962,8.236493e+09,4.186085e+09,3.235029e+09,347582,199699,...,5.489186e+09,1.931929e+09,394721,153237,4.965947e+08,3.187833e+08,33865,20667,2024-01-10,2024-01-10
2,2024-01-26 20:00:03.000,2024-01-26 20:00:00.000,1,AAPL,527653,8.164333e+09,3.866420e+09,3.615050e+09,311708,214627,...,4.173273e+09,3.308197e+09,306436,220072,3.827252e+08,3.001382e+08,24914,19586,2024-01-26,2024-01-26
3,2024-01-05 20:00:03.000,2024-01-05 20:00:00.000,1,AAPL,675348,1.073244e+10,5.060611e+09,4.557467e+09,394186,277242,...,3.601085e+09,6.016993e+09,349875,324250,7.120352e+08,4.023235e+08,46270,25440,2024-01-05,2024-01-05
4,2024-01-03 20:00:03.000,2024-01-03 20:00:00.000,1,AAPL,646673,9.850288e+09,4.962282e+09,3.895570e+09,384971,260417,...,5.887301e+09,2.970551e+09,337365,309308,5.323861e+08,4.600496e+08,36499,31646,2024-01-03,2024-01-03
5,2024-01-04 20:00:03.000,2024-01-04 20:00:00.000,1,AAPL,704321,1.160613e+10,5.085703e+09,5.255791e+09,410959,291530,...,3.824969e+09,6.516526e+09,285462,418792,8.521401e+08,4.124940e+08,52306,25296,2024-01-04,2024-01-04
6,2024-01-09 20:00:03.000,2024-01-09 20:00:00.000,1,AAPL,530847,7.457587e+09,4.198502e+09,2.517493e+09,348168,182397,...,5.814233e+09,9.017617e+08,453102,77735,4.232342e+08,3.183575e+08,32096,23905,2024-01-09,2024-01-09
7,2024-01-22 20:00:03.000,2024-01-22 20:00:00.000,1,AAPL,708837,1.076401e+10,5.608460e+09,4.200627e+09,424080,282016,...,4.332346e+09,5.476742e+09,387027,321791,5.172395e+08,4.376786e+08,34889,29419,2024-01-22,2024-01-22
8,2024-01-02 20:00:03.000,2024-01-02 20:00:00.000,1,AAPL,990770,1.412446e+10,6.623133e+09,6.059657e+09,542285,446477,...,5.313069e+09,7.369722e+09,246489,744247,9.361314e+08,5.055404e+08,69922,36466,2024-01-02,2024-01-02
9,2024-01-12 20:00:03.000,2024-01-12 20:00:00.000,1,AAPL,470683,6.976981e+09,3.291219e+09,3.002975e+09,281035,189186,...,1.538530e+09,4.755664e+09,141921,326966,4.153750e+08,2.674128e+08,29498,17852,2024-01-12,2024-01-12
10,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,1,AAPL,672874,1.247752e+10,6.400096e+09,5.082925e+09,417858,250310,...,7.644141e+09,3.838881e+09,532463,140411,5.415680e+08,4.529306e+08,32810,25615,2024-01-19,2024-01-19
11,2024-01-25 20:00:03.000,2024-01-25 20:00:00.000,1,AAPL,635511,9.921383e+09,4.652936e+09,4.391468e+09,364205,269872,...,4.187532e+09,4.856872e+09,305904,329605,4.808354e+08,3.961437e+08,31153,25473,2024-01-25,2024-01-25
12,2024-01-17 20:00:03.000,2024-01-17 20:00:00.000,1,AAPL,585486,8.177438e+09,4.069354e+09,3.347696e+09,350633,232777,...,4.263990e+09,3.153060e+09,301897,283518,4.652283e+08,2.951595e+08,33131,20739,2024-01-17,2024-01-17
13,2024-01-31 20:00:03.000,2024-01-31 20:00:00.000,1,AAPL,673799,9.649775e+09,4.751167e+09,4.091920e+09,399686,271692,...,4.310247e+09,4.532841e+09,419311,254487,4.901400e+08,3.165473e+08,36382,23948,2024-01-31,2024-01-31
14,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,1,AAPL,777010,1.407412e+10,6.441001e+09,6.411099e+09,444246,329015,...,6.152252e+09,6.699848e+09,461588,313288,6.676443e+08,5.543803e+08,39269,31654,2024-01-18,2024-01-18
15,2024-01-24 20:00:03.000,2024-01-24 20:00:00.000,1,AAPL,587965,9.464530e+09,4.085500e+09,4.528231e+09,329297,256206,...,2.183976e+09,6.429755e+09,217942,370023,4.297140e+08,4.210849e+08,27663,27274,2024-01-24,2024-01-24
16,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,1,AAPL,659244,1.029335e+10,5.566822e+09,3.684005e+09,432591,223277,...,7.146958e+09,2.103868e+09,426813,231163,6.522098e+08,3.903147e+08,45879,26647,2024-01-08,2024-01-08
17,2024-01-29 20:00:03.000,2024-01-29 20:00:00.000,1,AAPL,590109,8.135219e+09,3.895651e+09,3.483823e+09,360768,226701,...,2.352413e+09,5.027061e+09,218967,369775,4.377972e+08,3.179474e+08,31284,22478,2024-01-29,2024-01-29
18,2024-01-11 20:00:03.000,2024-01-11 20:00:00.000,1,AAPL,573593,8.499696e+09,4.130628e+09,3.580027e+09,335537,237369,...,4.536398e+09,3.174257e+09,254275,319317,4.970836e+08,2.919579e+08,35207,19919,2024-01-11,2024-01-11
19,2024-01-30 20:00:03.000,2024-01-30 20:00:00.000,1,AAPL,682124,9.997138e+09,5.243468e+09,3.764531e+09,398518,282550,...,4.989186e+09,4.018813e+09,331875,350249,5.983342e+08,3.908052e+08,41139,26414,2024-01-30,2024-01-30
20,2024-01-16 20:00:03.000,2024-01-16 20:00:00.000,1,AAPL,754695,1.064378e+10,5.534916e+09,4.143439e+09,447716,304345,...,6.128546e+09,3.549808e+09,468751,285943,5.864017e+08,3.790271e+08,44587,28380,2024-01-16,2024-01-16

## Download data file for a specific date using asof_date

In [12]:
Unifier.replicate(name="lseg_us_equity_flow_daily_v1_2", target_location="./data", asof_date='2026-01-12')

Downloading using native python implementation for lseg_us_equity_flow_daily_v1_2...
Found 1 files to download.
Native replication completed for lseg_us_equity_flow_daily_v1_2. Downloaded 1 files.