In [3]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [4]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [11]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_features_with_isin_values_sp500_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,isin,asof_date
0,A,f_ecd80e69e4f3,0.096859,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
1,A,f_cabe6516a7e5,0.670642,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
2,A,f_6e5f7fff46ae,0.640286,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
3,A,f_f103882b4d24,0.999561,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
4,A,f_ff67edf40f1b,0.814899,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
5,A,f_2a2b252d85ce,-0.607257,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
6,A,f_3b7e3291f900,-0.049880,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
7,A,f_5d4fcd16363e,0.912833,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
8,A,f_6c8b3ca972d9,0.599188,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13
9,A,f_64b8a014ff6e,0.611020,True,2018-09-13 20:00:00.000,2018-09-13 20:00:03.000,SP500,US00846U1016,2018-09-13

## Retrieve data for a specific date range using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_features_with_isin_values_sp500_v1_2', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,isin,asof_date
0,CB,f_1c5965eaa2b4,0.032722,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,CH0044328745,2024-01-31
1,ANSS,f_1c5965eaa2b4,0.449517,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US03662Q1058,2024-01-31
2,AOS,f_1c5965eaa2b4,-0.823648,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US8318652091,2024-01-31
3,ABT,f_1c5965eaa2b4,0.537910,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US0028241000,2024-01-31
4,ADBE,f_1c5965eaa2b4,-0.835149,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US00724F1012,2024-01-31
...,...,...,...,...,...,...,...,...,...
95,DLTR,f_1c5965eaa2b4,0.594802,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US2567461080,2024-01-31
96,D,f_1c5965eaa2b4,-1.543411,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US25746U1097,2024-01-31
97,DOV,f_1c5965eaa2b4,-0.124773,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US2600031080,2024-01-31
98,DTE,f_1c5965eaa2b4,-0.888412,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US2333311072,2024-01-31
99,EMN,f_1c5965eaa2b4,-1.215535,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,SP500,US2774321002,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_features_with_isin_values_sp500_v1_2',key='AAN', asof_date='2024-01-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_features_with_isin_values_sp500_v1_2',key='AAN', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_eqt_flow_features_with_isin_values_sp500_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for xtech_us_eqt_flow_features_with_isin_values_sp500_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_features_with_isin_values_sp500_v1_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_features_with_isin_values_sp500_v1_2", target_location="./data")