In [2]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [3]:
from unifier import unifier as Unifier

In [7]:
# Unifier.user = 'unifier username'
# Unifier.token = 'unifier api token'
Unifier.user = 'rabele@bamfunds.com'
Unifier.token = '018bd5cb-c4ad-4e24-87b9-559e790a3c8b'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_features_with_isin_labels_sp500_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,use_risk_model,label_name,label_value,isin,ticker,timestamp,asof_datetime,asof_date
0,True,target_res_ret_63d,0.109811,US00846U1016,A,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
1,False,target_fwd_ret_10d,0.208813,US00846U1016,A,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
2,False,target_fwd_ret_42d,0.021028,US00846U1016,A,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
3,True,target_res_ret_21d,0.068534,US00846U1016,A,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
4,False,target_fwd_ret_63d,0.185550,US00846U1016,A,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
5,True,target_res_ret_42d,0.039022,US00846U1016,A,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
6,False,target_fwd_ret_21d,0.142423,US00846U1016,A,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
7,True,target_res_ret_10d,0.115095,US00846U1016,A,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
8,False,target_fwd_ret_21d,0.050264,US0138171014,AA,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13
9,True,target_res_ret_42d,-0.139126,US0138171014,AA,2011-10-13 20:00:00.000,2011-10-13 20:00:03.000,2011-10-13

## Retrieve data for a specific date range using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_features_with_isin_labels_sp500_v1_2', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,isin,ticker,timestamp,asof_datetime,asof_date
0,False,target_fwd_ret_10d,0.015730,CH0044328745,CB,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
1,False,target_fwd_ret_10d,-0.045236,US03662Q1058,ANSS,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
2,False,target_fwd_ret_10d,0.023483,US8318652091,AOS,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
3,False,target_fwd_ret_10d,0.045002,US0028241000,ABT,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
4,False,target_fwd_ret_10d,0.038329,US00724F1012,ADBE,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
...,...,...,...,...,...,...,...,...
95,False,target_fwd_ret_10d,-0.031208,US2567461080,DLTR,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
96,False,target_fwd_ret_10d,-0.063080,US25746U1097,D,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
97,False,target_fwd_ret_10d,-0.010705,US2600031080,DOV,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
98,False,target_fwd_ret_10d,-0.056729,US2333311072,DTE,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03
99,False,target_fwd_ret_10d,-0.011772,US2774321002,EMN,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,2024-01-03

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_features_with_isin_labels_sp500_v1_2',key='CB', asof_date='2024-01-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,isin,ticker,timestamp,asof_datetime,asof_date
0,False,target_fwd_ret_10d,0.017649,US1712321017,CB,2010-01-05 20:00:00.000,2010-01-05 20:00:03.000,2010-01-05
1,False,target_fwd_ret_21d,-0.013393,US1712321017,CB,2010-01-05 20:00:00.000,2010-01-05 20:00:03.000,2010-01-05
2,False,target_fwd_ret_42d,0.056692,US1712321017,CB,2010-01-05 20:00:00.000,2010-01-05 20:00:03.000,2010-01-05
3,False,target_fwd_ret_63d,0.059600,US1712321017,CB,2010-01-05 20:00:00.000,2010-01-05 20:00:03.000,2010-01-05
4,True,target_res_ret_10d,0.020203,US1712321017,CB,2010-01-05 20:00:00.000,2010-01-05 20:00:03.000,2010-01-05
...,...,...,...,...,...,...,...,...
95,True,target_res_ret_63d,0.105039,US1712321017,CB,2010-03-15 20:00:00.000,2010-03-15 20:00:03.000,2010-03-15
96,False,target_fwd_ret_10d,0.010558,US1712321017,CB,2010-01-22 20:00:00.000,2010-01-22 20:00:03.000,2010-01-22
97,False,target_fwd_ret_21d,0.055654,US1712321017,CB,2010-01-22 20:00:00.000,2010-01-22 20:00:03.000,2010-01-22
98,False,target_fwd_ret_42d,0.083864,US1712321017,CB,2010-01-22 20:00:00.000,2010-01-22 20:00:03.000,2010-01-22
99,False,target_fwd_ret_63d,0.119653,US1712321017,CB,2010-01-22 20:00:00.000,2010-01-22 20:00:03.000,2010-01-22

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_features_with_isin_labels_sp500_v1_2',key='CB', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,isin,ticker,timestamp,asof_datetime,asof_date
0,False,target_fwd_ret_10d,0.069259,CH0044328745,CB,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,2024-01-09
1,False,target_fwd_ret_21d,0.080950,CH0044328745,CB,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,2024-01-09
2,False,target_fwd_ret_42d,0.123692,CH0044328745,CB,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,2024-01-09
3,False,target_fwd_ret_63d,0.099048,CH0044328745,CB,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,2024-01-09
4,True,target_res_ret_10d,0.018252,CH0044328745,CB,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,2024-01-09
...,...,...,...,...,...,...,...,...
95,True,target_res_ret_63d,0.022297,CH0044328745,CB,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,2024-01-16
96,False,target_fwd_ret_10d,0.062888,CH0044328745,CB,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,2024-01-18
97,False,target_fwd_ret_21d,0.087048,CH0044328745,CB,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,2024-01-18
98,False,target_fwd_ret_42d,0.119769,CH0044328745,CB,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,2024-01-18
99,False,target_fwd_ret_63d,0.067871,CH0044328745,CB,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,2024-01-18

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="xtech_us_eqt_flow_features_with_isin_labels_sp500_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for xtech_us_eqt_flow_features_with_isin_labels_sp500_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_features_with_isin_labels_sp500_v1_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_features_with_isin_labels_sp500_v1_2", target_location="./data")