In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="lseg_us_equity_flow_r3k_1min_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2018-12-26,2018-12-26 04:01:00.000,2018-12-26 04:01:03.000,1,BRK.B,2,2994.56,2245.92,748.64,1,...,1,1497.28,1497.28,0,0,0,0,0,0,2018-12-26
1,2018-12-26,2018-12-26 04:01:00.000,2018-12-26 04:01:03.000,1,GE,2,434.70,326.03,108.68,1,...,1,217.35,217.35,0,0,0,0,0,0,2018-12-26
2,2018-12-26,2018-12-26 04:01:00.000,2018-12-26 04:01:03.000,1,INTC,1,87.40,43.70,43.70,0,...,1,43.70,43.70,0,0,0,0,0,0,2018-12-26
3,2018-12-26,2018-12-26 04:01:00.000,2018-12-26 04:01:03.000,1,NVDA,6,16324.95,14964.54,1360.41,5,...,1,8162.48,8162.48,0,0,0,0,0,0,2018-12-26
4,2018-12-26,2018-12-26 04:04:00.000,2018-12-26 04:04:03.000,1,GE,1,255.30,255.30,0.00,1,...,0,127.65,127.65,0,0,0,0,0,0,2018-12-26
5,2018-12-26,2018-12-26 04:05:00.000,2018-12-26 04:05:03.000,1,BRK.B,2,938.35,469.17,469.17,1,...,0,469.17,469.17,0,0,0,0,0,0,2018-12-26
6,2018-12-26,2018-12-26 04:06:00.000,2018-12-26 04:06:03.000,1,BRK.B,1,2820.00,0.00,2820.00,0,...,0,2820.00,0.00,1,0,0,0,0,0,2018-12-26
7,2018-12-26,2018-12-26 04:06:00.000,2018-12-26 04:06:03.000,1,INTC,1,2097.60,2097.60,0.00,1,...,0,1048.80,1048.80,0,0,0,0,0,0,2018-12-26
8,2018-12-26,2018-12-26 04:24:00.000,2018-12-26 04:24:03.000,1,GIS,1,2113.44,1056.72,1056.72,0,...,1,0.00,2113.44,0,1,0,0,0,0,2018-12-26
9,2018-12-26,2018-12-26 04:25:00.000,2018-12-26 04:25:03.000,1,V,16,120910.00,86904.06,34005.94,11,...,1,45341.25,75568.75,0,4,0,0,0,0,2018-12-26

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_r3k_1min_v1_2_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RM,15,4.500485e+03,600.06,3900.42,2,...,6,0.00,4500.48,0,15,0.00,0.00,0,0,2024-01-31
1,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RMBS,369,1.253948e+06,506336.90,747611.53,149,...,57,16991.17,1236957.26,5,364,0.00,0.00,0,0,2024-01-31
2,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,ROCK,45,7.384207e+04,39382.44,34459.64,24,...,18,62355.53,11486.54,38,7,0.00,0.00,0,0,2024-01-31
3,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,ROVR,50,6.284271e+04,5027.42,55301.58,0,...,7,30792.93,29536.07,0,1,0.00,2513.71,0,2,2024-01-31
4,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RPD,171,5.678996e+05,454983.87,112915.71,137,...,22,564578.53,3321.05,170,1,0.00,0.00,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,ASIX,64,5.176261e+04,1617.58,46909.86,5,...,10,0.00,48527.45,0,64,2426.37,808.79,3,1,2024-01-31
96,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,ASLE,210,1.477508e+05,58044.96,89705.84,66,...,18,73171.82,74578.97,1,3,0.00,0.00,0,0,2024-01-31
97,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,ATI,1259,3.424538e+06,1297461.97,2127076.02,477,...,160,46240.78,3378297.21,17,1242,0.00,0.00,0,0,2024-01-31
98,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,AVDX,160,1.989627e+05,19896.27,179066.46,16,...,20,2487.03,196475.70,2,158,0.00,0.00,0,0,2024-01-31
99,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,AVTR,369,1.331321e+06,530363.61,793741.47,148,...,58,1316889.25,7215.83,366,3,3607.92,3607.92,1,1,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_r3k_1min_v1_2_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2018-11-30,2018-11-30 04:01:00.000,2018-11-30 04:01:03.000,1,AAPL,3,26861.800,22384.83,4476.97,2,...,1,22384.83,4476.97,2,0,0.00,0.00,0,0,2018-11-30
1,2018-11-30,2018-11-30 04:03:00.000,2018-11-30 04:03:03.000,1,AAPL,1,2868.960,0.00,2868.96,0,...,1,2868.96,0.00,1,0,0.00,0.00,0,0,2018-11-30
2,2018-11-30,2018-11-30 04:06:00.000,2018-11-30 04:06:03.000,1,AAPL,6,46595.800,7765.97,38829.83,1,...,3,46595.80,0.00,6,0,0.00,0.00,0,0,2018-11-30
3,2018-11-30,2018-11-30 04:11:00.000,2018-11-30 04:11:03.000,1,AAPL,1,13796.090,0.00,13796.09,0,...,1,13796.09,0.00,1,0,0.00,0.00,0,0,2018-11-30
4,2018-11-30,2018-11-30 04:16:00.000,2018-11-30 04:16:03.000,1,AAPL,3,13613.960,0.00,13613.96,0,...,2,13613.96,0.00,3,0,0.00,0.00,0,0,2018-11-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018-11-30,2018-11-30 08:00:00.000,2018-11-30 08:00:03.000,1,AAPL,4,75891.250,75891.25,0.00,4,...,1,75891.25,0.00,4,0,0.00,0.00,0,0,2018-11-30
96,2018-11-30,2018-11-30 08:01:00.000,2018-11-30 08:01:03.000,1,AAPL,72,2921120.784,933135.81,1825700.49,25,...,26,2758836.30,0.00,71,1,81142.24,81142.24,2,2,2018-11-30
97,2018-11-30,2018-11-30 08:02:00.000,2018-11-30 08:02:03.000,1,AAPL,21,410277.170,156296.06,253981.11,7,...,3,371203.15,39074.02,19,2,0.00,0.00,0,0,2018-11-30
98,2018-11-30,2018-11-30 08:03:00.000,2018-11-30 08:03:03.000,1,AAPL,1,3576.800,3576.80,0.00,1,...,0,3576.80,0.00,1,0,0.00,0.00,0,0,2018-11-30
99,2018-11-30,2018-11-30 08:04:00.000,2018-11-30 08:04:03.000,1,AAPL,8,126087.500,94565.62,31521.88,6,...,1,126087.50,0.00,8,0,0.00,0.00,0,0,2018-11-30

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_r3k_1min_v1_2_trial',key='AAPL', back_to='2019-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2022-02-28,2022-02-28 15:16:00.000,2022-02-28 15:16:03.000,0,AAPL,1318,1.822903e+07,9474118.46,7316509.01,745,...,250,16790627.47,0.00,1290,28,829849.79,608556.51,60,44,2022-02-28
1,2022-02-28,2022-02-28 15:17:00.000,2022-02-28 15:17:03.000,0,AAPL,1252,1.751988e+07,9403642.89,6590946.13,732,...,235,15994589.02,0.00,1227,25,839610.97,685682.29,60,49,2022-02-28
2,2022-02-28,2022-02-28 15:18:00.000,2022-02-28 15:18:03.000,0,AAPL,2251,4.267902e+07,23548354.64,16419384.15,1339,...,382,39759178.48,208560.31,2194,57,1839122.70,872161.28,97,46,2022-02-28
3,2022-02-28,2022-02-28 15:20:00.000,2022-02-28 15:20:03.000,0,AAPL,1249,1.744150e+07,8595068.75,7394133.07,668,...,242,15989201.81,0.00,1218,31,740111.53,712182.79,53,51,2022-02-28
4,2022-02-28,2022-02-28 15:21:00.000,2022-02-28 15:21:03.000,0,AAPL,2191,3.614650e+07,20655142.72,12703242.73,1358,...,395,33358385.45,0.00,2140,51,1748758.09,1039356.22,106,63,2022-02-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-02-28,2022-02-28 18:53:00.000,2022-02-28 18:53:03.000,1,AAPL,5,8.458242e+04,50749.45,33832.97,3,...,2,84582.42,0.00,5,0,0.00,0.00,0,0,2022-02-28
96,2022-02-28,2022-02-28 18:54:00.000,2022-02-28 18:54:03.000,1,AAPL,39,7.938961e+05,671758.25,122137.86,33,...,4,793896.11,0.00,39,0,0.00,0.00,0,0,2022-02-28
97,2022-02-28,2022-02-28 18:55:00.000,2022-02-28 18:55:03.000,1,AAPL,23,5.393468e+05,328298.04,211048.74,14,...,6,539346.78,0.00,23,0,0.00,0.00,0,0,2022-02-28
98,2022-02-28,2022-02-28 18:56:00.000,2022-02-28 18:56:03.000,1,AAPL,60,1.571226e+06,301151.63,1270074.25,8,...,17,1414103.29,157122.59,54,6,0.00,0.00,0,0,2022-02-28
99,2022-02-28,2022-02-28 18:57:00.000,2022-02-28 18:57:03.000,1,AAPL,21,7.266232e+05,484415.48,242207.74,14,...,5,726623.22,0.00,21,0,0.00,0.00,0,0,2022-02-28

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="lseg_us_equity_flow_r3k_1min_v1_2_trial", target_location="./data", asof_date='2025-01-17')

Starting native python replication for lseg_us_equity_flow_r3k_1min_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_equity_flow_r3k_1min_v1_2_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_flow_r3k_1min_v1_2_trial", target_location="./data")