In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_equity_flow_r3k_daily_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2012-08-23,2012-08-23 16:01:00.000,2012-08-23 20:00:03.000,1,AACC,165,2.431508e+05,1.680184e+05,7.322558e+04,92,...,43,1.264320e+05,1.148119e+05,15,11,1.271320e+03,6.355000e+02,1,1,2012-08-23
1,2012-08-23,2012-08-23 20:00:00.000,2012-08-23 20:00:03.000,1,AAPL,88300,9.905431e+09,4.482254e+09,4.542219e+09,43824,...,30594,4.618101e+09,4.406372e+09,46892,41407,4.430700e+08,4.378882e+08,3963,3968,2012-08-23
2,2012-08-23,2012-08-23 16:01:00.000,2012-08-23 20:00:03.000,1,ABFS,1349,2.179914e+06,8.360900e+05,1.216207e+06,582,...,254,8.350470e+05,1.217250e+06,307,559,6.910050e+04,5.851654e+04,42,17,2012-08-23
3,2012-08-23,2012-08-23 16:01:00.000,2012-08-23 20:00:03.000,1,ACOR,1232,3.344181e+06,1.845221e+06,1.435293e+06,668,...,212,1.647542e+06,1.632972e+06,135,130,3.613299e+04,2.753366e+04,14,11,2012-08-23
4,2012-08-23,2012-08-23 16:01:00.000,2012-08-23 20:00:03.000,1,ADM,14048,7.779735e+07,3.803822e+07,3.676297e+07,6387,...,1424,3.754678e+07,3.725441e+07,757,866,9.683698e+05,2.027795e+06,168,265,2012-08-23
5,2012-08-23,2012-08-23 19:14:00.000,2012-08-23 20:00:03.000,1,ADTN,17731,5.574605e+07,3.003772e+07,2.456895e+07,9800,...,2753,3.859696e+07,1.600970e+07,12492,5239,4.858324e+05,6.535535e+05,147,204,2012-08-23
6,2012-08-23,2012-08-23 16:03:00.000,2012-08-23 20:00:03.000,1,ADVS,1749,5.093932e+06,2.516027e+06,2.488468e+06,880,...,358,3.385825e+06,1.618670e+06,817,181,6.678935e+04,2.264650e+04,22,8,2012-08-23
7,2012-08-23,2012-08-23 16:01:00.000,2012-08-23 20:00:03.000,1,AEGR,350,9.331728e+05,5.800743e+05,3.372478e+05,170,...,89,6.193883e+05,2.979338e+05,37,35,1.201496e+04,3.835760e+03,7,2,2012-08-23
8,2012-08-23,2012-08-23 16:05:00.000,2012-08-23 20:00:03.000,1,AGM,167,5.403197e+05,1.377820e+05,3.665427e+05,57,...,41,2.486890e+05,2.556358e+05,16,14,3.008227e+04,5.912660e+03,9,2,2012-08-23
9,2012-08-23,2012-08-23 18:56:00.000,2012-08-23 20:00:03.000,1,AKS,34464,5.490619e+07,2.549622e+07,2.807441e+07,14647,...,3449,2.663423e+07,2.693640e+07,1294,1326,8.199805e+05,5.155741e+05,542,306,2012-08-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_r3k_daily_v1_2_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-17,2024-01-17 19:01:00.000,2024-01-17 20:00:03.000,1,ABM,9578,2.263332e+07,1.331082e+07,9.089611e+06,5095,...,1442,2.205646e+07,343968.44,9396,182,125528.75,107363.25,66,66,2024-01-17
1,2024-01-17,2024-01-17 19:01:00.000,2024-01-17 20:00:03.000,1,AESI,9310,1.563058e+07,8.253357e+06,6.953330e+06,4885,...,1219,1.371222e+07,1494467.40,7017,238,239238.48,184652.77,169,132,2024-01-17
2,2024-01-17,2024-01-17 19:01:00.000,2024-01-17 20:00:03.000,1,AGR,10155,1.903314e+07,1.136531e+07,7.233550e+06,5180,...,1510,1.118661e+07,7412249.09,4820,5334,234447.70,199826.34,158,132,2024-01-17
3,2024-01-17,2024-01-17 19:53:00.000,2024-01-17 20:00:03.000,1,AGS,2746,2.128892e+06,1.403977e+06,6.771934e+05,1750,...,388,1.777074e+06,304097.30,2001,436,20213.49,27508.15,33,39,2024-01-17
4,2024-01-17,2024-01-17 19:01:00.000,2024-01-17 20:00:03.000,1,AKR,8122,1.503220e+07,5.734689e+06,9.138861e+06,3406,...,984,9.982162e+05,13875333.86,330,7096,70278.20,88368.95,35,68,2024-01-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-17,2024-01-17 16:21:00.000,2024-01-17 20:00:03.000,1,EVCM,2401,1.469014e+06,6.152533e+05,8.349980e+05,1128,...,329,4.226609e+05,1027590.47,828,1256,6134.76,12628.33,13,41,2024-01-17
96,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,EVGO,15454,6.555758e+06,3.596112e+06,2.716690e+06,6222,...,1915,3.106232e+06,3206569.70,211,291,162328.71,80627.37,359,191,2024-01-17
97,2024-01-17,2024-01-17 19:59:00.000,2024-01-17 20:00:03.000,1,EWBC,20871,7.417762e+07,3.054381e+07,4.278485e+07,9404,...,3612,2.108446e+07,52244203.58,6571,14300,458612.54,390352.98,145,144,2024-01-17
98,2024-01-17,2024-01-17 19:46:00.000,2024-01-17 20:00:03.000,1,EXLS,16931,3.516759e+07,1.877420e+07,1.566678e+07,11042,...,2279,3.289725e+07,1543728.66,15921,1006,567786.63,158827.13,354,94,2024-01-17
99,2024-01-17,2024-01-17 17:54:00.000,2024-01-17 20:00:03.000,1,EXPE,30427,2.371493e+08,1.162912e+08,1.150584e+08,15114,...,6968,1.350629e+08,96286590.23,16267,14152,2917948.03,2881867.92,423,413,2024-01-17

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_r3k_daily_v1_2_trial', key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2012-08-31,2012-08-31 20:00:00.000,2012-08-31 20:00:03.000,1,AAPL,72442,7.900390e+09,3.601989e+09,3.671724e+09,36076,...,23997,3.746380e+09,3.527333e+09,36580,35860,3.250710e+08,3.016053e+08,2913,2795,2012-08-31
1,2013-01-04,2013-01-04 20:00:00.000,2013-01-04 20:00:03.000,1,AAPL,123199,1.112861e+10,4.815866e+09,5.442290e+09,57922,...,40399,4.214086e+09,6.044070e+09,51299,71899,4.271002e+08,4.433557e+08,4742,4865,2013-01-04
2,2012-09-20,2012-09-20 20:00:00.000,2012-09-20 20:00:03.000,1,AAPL,64351,7.681337e+09,3.535246e+09,3.529198e+09,32435,...,20902,3.838792e+09,3.225652e+09,33954,30396,3.030503e+08,3.138427e+08,2615,2707,2012-09-20
3,2012-07-26,2012-07-26 19:59:00.000,2012-07-26 20:00:03.000,1,AAPL,91851,8.115819e+09,3.816493e+09,3.697302e+09,46836,...,29953,3.590167e+09,3.923628e+09,44778,47073,3.072679e+08,2.947558e+08,3488,3394,2012-07-26
4,2012-12-18,2012-12-18 20:00:00.000,2012-12-18 20:00:03.000,1,AAPL,128525,1.158483e+10,5.691551e+09,5.001276e+09,68241,...,43409,6.236518e+09,4.456309e+09,74468,54057,4.778017e+08,4.142000e+08,5245,4605,2012-12-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2013-01-02,2013-01-02 20:00:00.000,2013-01-02 20:00:03.000,1,AAPL,116507,1.081082e+10,5.011265e+09,4.895515e+09,59109,...,39594,4.476720e+09,5.430060e+09,54182,62325,4.686037e+08,4.354384e+08,5158,4820,2013-01-02
96,2019-04-05,2019-04-05 20:00:00.000,2019-04-05 20:00:03.000,1,AAPL,123415,3.460675e+09,1.683385e+09,1.435619e+09,61987,...,27522,1.923037e+09,1.195966e+09,74262,48953,1.783422e+08,1.633297e+08,6778,6243,2019-04-05
97,2018-11-27,2018-11-27 20:00:00.000,2018-11-27 20:00:03.000,1,AAPL,264681,6.801316e+09,3.085665e+09,3.000452e+09,135865,...,65042,3.824293e+09,2.261825e+09,152111,112550,3.808124e+08,3.343862e+08,16167,14191,2018-11-27
98,2012-11-29,2012-11-29 20:00:00.000,2012-11-29 20:00:03.000,1,AAPL,97858,1.041884e+10,4.712687e+09,4.830997e+09,48637,...,33723,5.015202e+09,4.528481e+09,50912,46902,4.638555e+08,4.113027e+08,4272,3839,2012-11-29
99,2012-07-05,2012-07-05 19:59:00.000,2012-07-05 20:00:03.000,1,AAPL,107353,1.028681e+10,4.816729e+09,4.607416e+09,54403,...,33794,5.285518e+09,4.138628e+09,60289,47064,4.430064e+08,4.196589e+08,4688,4435,2012-07-05

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_equity_flow_r3k_daily_v1_2_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,754695,1.064378e+10,5.534916e+09,4.143439e+09,447716,...,140422,6.128546e+09,3.549808e+09,468751,285943,5.864017e+08,3.790271e+08,44587,28380,2024-01-16
1,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,682124,9.997138e+09,5.243468e+09,3.764531e+09,398518,...,131716,4.989186e+09,4.018813e+09,331875,350249,5.983342e+08,3.908052e+08,41139,26414,2024-01-30
2,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,777010,1.407412e+10,6.441001e+09,6.411099e+09,444246,...,144863,6.152252e+09,6.699848e+09,461588,313288,6.676443e+08,5.543803e+08,39269,31654,2024-01-18
3,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,547962,8.236493e+09,4.186085e+09,3.235029e+09,347582,...,100367,5.489186e+09,1.931929e+09,394721,153237,4.965947e+08,3.187833e+08,33865,20667,2024-01-10
4,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,672874,1.247752e+10,6.400096e+09,5.082925e+09,417858,...,121471,7.644141e+09,3.838881e+09,532463,140411,5.415680e+08,4.529306e+08,32810,25615,2024-01-19
5,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,704321,1.160613e+10,5.085703e+09,5.255791e+09,410959,...,141719,3.824969e+09,6.516526e+09,285462,418792,8.521401e+08,4.124940e+08,52306,25296,2024-01-04
6,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,673799,9.649775e+09,4.751167e+09,4.091920e+09,399686,...,129080,4.310247e+09,4.532841e+09,419311,254487,4.901400e+08,3.165473e+08,36382,23948,2024-01-31
7,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,530847,7.457587e+09,4.198502e+09,2.517493e+09,348168,...,98441,5.814233e+09,9.017617e+08,453102,77735,4.232342e+08,3.183575e+08,32096,23905,2024-01-09
8,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,470683,6.976981e+09,3.291219e+09,3.002975e+09,281035,...,82997,1.538530e+09,4.755664e+09,141921,326966,4.153750e+08,2.674128e+08,29498,17852,2024-01-12
9,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,527096,7.690177e+09,4.095794e+09,2.835907e+09,327963,...,91853,4.247200e+09,2.684500e+09,294083,229944,3.875323e+08,3.709440e+08,25365,23987,2024-01-23
10,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,635511,9.921383e+09,4.652936e+09,4.391468e+09,364205,...,110064,4.187532e+09,4.856872e+09,305904,329605,4.808354e+08,3.961437e+08,31153,25473,2024-01-25
11,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,527653,8.164333e+09,3.866420e+09,3.615050e+09,311708,...,92776,4.173273e+09,3.308197e+09,306436,220072,3.827252e+08,3.001382e+08,24914,19586,2024-01-26
12,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,587965,9.464530e+09,4.085500e+09,4.528231e+09,329297,...,105631,2.183976e+09,6.429755e+09,217942,370023,4.297140e+08,4.210849e+08,27663,27274,2024-01-24
13,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,990770,1.412446e+10,6.623133e+09,6.059657e+09,542285,...,203661,5.313069e+09,7.369722e+09,246489,744247,9.361314e+08,5.055404e+08,69922,36466,2024-01-02
14,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,585486,8.177438e+09,4.069354e+09,3.347696e+09,350633,...,105859,4.263990e+09,3.153060e+09,301897,283518,4.652283e+08,2.951595e+08,33131,20739,2024-01-17
15,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,659244,1.029335e+10,5.566822e+09,3.684005e+09,432591,...,122232,7.146958e+09,2.103868e+09,426813,231163,6.522098e+08,3.903147e+08,45879,26647,2024-01-08
16,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,675348,1.073244e+10,5.060611e+09,4.557467e+09,394186,...,132532,3.601085e+09,6.016993e+09,349875,324250,7.120352e+08,4.023235e+08,46270,25440,2024-01-05
17,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,708837,1.076401e+10,5.608460e+09,4.200627e+09,424080,...,125211,4.332346e+09,5.476742e+09,387027,321791,5.172395e+08,4.376786e+08,34889,29419,2024-01-22
18,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,590109,8.135219e+09,3.895651e+09,3.483823e+09,360768,...,105286,2.352413e+09,5.027061e+09,218967,369775,4.377972e+08,3.179474e+08,31284,22478,2024-01-29
19,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,573593,8.499696e+09,4.130628e+09,3.580027e+09,335537,...,105521,4.536398e+09,3.174257e+09,254275,319317,4.970836e+08,2.919579e+08,35207,19919,2024-01-11
20,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,646673,9.850288e+09,4.962282e+09,3.895570e+09,384971,...,129184,5.887301e+09,2.970551e+09,337365,309308,5.323861e+08,4.600496e+08,36499,31646,2024-01-03

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_equity_flow_r3k_daily_v1_2_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for lseg_us_equity_flow_r3k_daily_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_equity_flow_r3k_daily_v1_2_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_flow_r3k_daily_v1_2_trial", target_location="./data")