In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-23,2007-03-23 04:16:00.000,2007-03-23 04:16:03.000,1,PXR,US7042271079,2,25170,18877.5,6292.5,...,1,25170,0,2,0,0,0,0,0,2007-03-23
1,2007-03-23,2007-03-23 05:10:00.000,2007-03-23 05:10:03.000,1,AMGN,US0311621009,1,5820,2910.0,2910.0,...,1,5820,0,1,0,0,0,0,0,2007-03-23
2,2007-03-23,2007-03-23 05:51:00.000,2007-03-23 05:51:03.000,1,AMGN,US0311621009,1,5815,5815.0,0.0,...,1,5815,0,1,0,0,0,0,0,2007-03-23
3,2007-03-23,2007-03-23 06:06:00.000,2007-03-23 06:06:03.000,1,IMCL,US45245W1099,2,15328,11496.0,3832.0,...,1,15328,0,2,0,0,0,0,0,2007-03-23
4,2007-03-23,2007-03-23 06:17:00.000,2007-03-23 06:17:03.000,1,XTO,US98385X1063,1,5436,2718.0,2718.0,...,1,5436,0,1,0,0,0,0,0,2007-03-23
5,2007-03-23,2007-03-23 06:20:00.000,2007-03-23 06:20:03.000,1,AMGN,US0311621009,1,58150,0.0,58150.0,...,0,0,58150,0,1,0,0,0,0,2007-03-23
6,2007-03-23,2007-03-23 06:23:00.000,2007-03-23 06:23:03.000,1,AMGN,US0311621009,4,116000,0.0,116000.0,...,1,87000,29000,2,0,0,0,0,0,2007-03-23
7,2007-03-23,2007-03-23 06:34:00.000,2007-03-23 06:34:03.000,1,FTO,US35914P1057,2,33100,16550.0,16550.0,...,1,16550,16550,0,0,0,0,0,0,2007-03-23
8,2007-03-23,2007-03-23 06:34:00.000,2007-03-23 06:34:03.000,1,VLO,US91913Y1001,2,62900,31450.0,31450.0,...,1,0,62900,0,2,0,0,0,0,2007-03-23
9,2007-03-23,2007-03-23 06:37:00.000,2007-03-23 06:37:03.000,1,HAL,US4062161017,1,3080,1540.0,1540.0,...,1,0,3080,0,1,0,0,0,0,2007-03-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AADI,US00032Q1040,1,40.7100,20.36,20.36,...,1,20.36,20.36,0,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,US0378331005,163,891117.1800,563098.59,328018.59,...,44,194077.67,697039.51,35,127,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,US00287Y1091,4,4122.7000,3607.36,515.34,...,2,1030.68,3092.02,0,2,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABNB,US0090661010,10,23302.4700,19807.10,3495.37,...,5,8155.86,15146.61,0,3,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABT,US0028241000,1,1134.1000,567.05,567.05,...,1,1134.10,0.00,1,0,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FLNG,BMG359472021,1,1519.5000,759.75,759.75,...,1,0.00,1519.50,0,1,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FMC,US3024913036,1,114.9800,57.49,57.49,...,1,57.49,57.49,0,0,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FSR,US33813J1060,29,4471.2685,3469.09,1002.18,...,14,2158.54,2312.73,0,1,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FTI,GB00BDSFG982,2,183.6000,45.90,137.70,...,1,0.00,183.60,0,2,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,GDDY,US3802371076,2,11881.0000,5940.50,5940.50,...,1,0.00,11881.00,0,2,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-10,2007-01-10 04:51:00.000,2007-01-10 04:51:03.000,1,AAPL,US0378331005,1,46225.00,23112.50,23112.50,...,1,23112.50,23112.50,0,0,0,0,0,0,2007-01-10
1,2007-01-10,2007-01-10 05:27:00.000,2007-01-10 05:27:03.000,1,AAPL,US0378331005,3,84012.10,0.00,84012.10,...,2,42006.05,42006.05,0,0,0,0,0,0,2007-01-10
2,2007-01-10,2007-01-10 05:49:00.000,2007-01-10 05:49:03.000,1,AAPL,US0378331005,1,9233.00,9233.00,0.00,...,0,9233.00,0.00,1,0,0,0,0,0,2007-01-10
3,2007-01-10,2007-01-10 05:50:00.000,2007-01-10 05:50:03.000,1,AAPL,US0378331005,4,46160.00,23080.00,23080.00,...,1,34620.00,11540.00,2,0,0,0,0,0,2007-01-10
4,2007-01-10,2007-01-10 05:52:00.000,2007-01-10 05:52:03.000,1,AAPL,US0378331005,4,36932.00,9233.00,27699.00,...,1,13849.50,23082.50,0,1,0,0,0,0,2007-01-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-01-10,2007-01-10 08:24:00.000,2007-01-10 08:24:03.000,1,AAPL,US0378331005,112,2896710.50,2159601.13,737109.37,...,17,2870847.01,25863.49,111,1,0,0,0,0,2007-01-10
96,2007-01-10,2007-01-10 08:25:00.000,2007-01-10 08:25:03.000,1,AAPL,US0378331005,202,6971563.01,5453004.73,1518558.28,...,31,6281309.25,690253.76,182,20,0,0,0,0,2007-01-10
97,2007-01-10,2007-01-10 08:26:00.000,2007-01-10 08:26:03.000,1,AAPL,US0378331005,172,5559857.20,3038526.61,2521330.59,...,31,5268934.44,290922.76,163,9,0,0,0,0,2007-01-10
98,2007-01-10,2007-01-10 08:27:00.000,2007-01-10 08:27:03.000,1,AAPL,US0378331005,72,2321274.35,1354076.70,967197.65,...,9,2256794.51,64479.84,70,2,0,0,0,0,2007-01-10
99,2007-01-10,2007-01-10 08:28:00.000,2007-01-10 08:28:03.000,1,AAPL,US0378331005,110,3890141.21,2652369.01,1237772.20,...,18,3748681.53,141459.68,106,4,0,0,0,0,2007-01-10

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_trial',key='AAPL', back_to='2019-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2019-01-25,2019-01-25 04:01:00.000,2019-01-25 04:01:03.000,1,AAPL,US0378331005,17,126242.26,70547.15,55695.11,...,2,70547.15,55695.11,6,4,0,0,0,0,2019-01-25
1,2019-01-25,2019-01-25 04:03:00.000,2019-01-25 04:03:03.000,1,AAPL,US0378331005,19,148825.00,23498.68,125326.32,...,3,148825.00,0.00,19,0,0,0,0,0,2019-01-25
2,2019-01-25,2019-01-25 04:04:00.000,2019-01-25 04:04:03.000,1,AAPL,US0378331005,10,94260.24,0.00,94260.24,...,2,94260.24,0.00,10,0,0,0,0,0,2019-01-25
3,2019-01-25,2019-01-25 04:05:00.000,2019-01-25 04:05:03.000,1,AAPL,US0378331005,6,153246.47,0.00,153246.47,...,2,153246.47,0.00,6,0,0,0,0,0,2019-01-25
4,2019-01-25,2019-01-25 04:06:00.000,2019-01-25 04:06:03.000,1,AAPL,US0378331005,9,71763.00,0.00,71763.00,...,1,55815.67,15947.33,7,2,0,0,0,0,2019-01-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-01-25,2019-01-25 07:33:00.000,2019-01-25 07:33:03.000,1,AAPL,US0378331005,1,15371.00,15371.00,0.00,...,0,0.00,15371.00,0,1,0,0,0,0,2019-01-25
96,2019-01-25,2019-01-25 07:36:00.000,2019-01-25 07:36:03.000,1,AAPL,US0378331005,2,159397.27,159397.27,0.00,...,0,0.00,159397.27,0,2,0,0,0,0,2019-01-25
97,2019-01-25,2019-01-25 07:37:00.000,2019-01-25 07:37:03.000,1,AAPL,US0378331005,1,9222.60,9222.60,0.00,...,0,0.00,9222.60,0,1,0,0,0,0,2019-01-25
98,2019-01-25,2019-01-25 07:38:00.000,2019-01-25 07:38:03.000,1,AAPL,US0378331005,9,158351.06,140756.50,17594.56,...,2,0.00,158351.06,0,9,0,0,0,0,2019-01-25
99,2019-01-25,2019-01-25 07:40:00.000,2019-01-25 07:40:03.000,1,AAPL,US0378331005,1,15370.00,15370.00,0.00,...,1,0.00,15370.00,0,1,0,0,0,0,2019-01-25

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_trial", target_location="./data", asof_date='2025-01-17')

Starting native python replication for lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_trial. Downloaded 1 files.