In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-19,2007-01-19 16:10:00.000,2007-01-19 20:00:03.000,1,A,US00846U1016,7490,8.964939e+07,3.884082e+07,4.978291e+07,...,1051,4.477798e+07,4.384575e+07,603,525,287220.50,738442.10,32,73,2007-01-19
1,2007-01-19,2007-01-19 18:52:00.000,2007-01-19 20:00:03.000,1,AA,US0138171014,35516,4.089700e+08,2.230228e+08,1.779946e+08,...,4460,3.252258e+08,7.579162e+07,24473,1610,3817271.93,4135305.50,356,382,2007-01-19
2,2007-01-19,2007-01-19 16:03:00.000,2007-01-19 20:00:03.000,1,AACC,US04543P1003,521,1.170652e+06,5.415880e+05,5.861754e+05,...,106,5.419617e+05,5.858017e+05,52,67,16589.43,26299.52,6,6,2007-01-19
3,2007-01-19,2007-01-19 16:04:00.000,2007-01-19 20:00:03.000,1,AAI,US00949P1084,4607,1.665235e+07,7.532117e+06,8.957890e+06,...,593,1.165119e+07,4.838819e+06,2196,319,70677.71,91661.74,20,19,2007-01-19
4,2007-01-19,2007-01-19 16:13:00.000,2007-01-19 20:00:03.000,1,AAON,US0003602069,156,5.981691e+05,3.192061e+05,2.359706e+05,...,41,2.901201e+05,2.650566e+05,61,68,22530.03,20462.31,2,1,2007-01-19
5,2007-01-19,2007-01-19 16:07:00.000,2007-01-19 20:00:03.000,1,AAP,US00751Y1064,3441,2.564073e+07,1.450187e+07,1.099423e+07,...,705,1.928833e+07,6.207774e+06,2561,832,110197.70,34424.79,12,4,2007-01-19
6,2007-01-19,2007-01-19 20:00:00.000,2007-01-19 20:00:03.000,1,AAPL,US0378331005,226821,4.264110e+09,2.064665e+09,2.122834e+09,...,29790,1.610434e+09,2.577065e+09,90496,136325,48582051.81,28028853.90,2574,1493,2007-01-19
7,2007-01-19,2007-01-19 16:01:00.000,2007-01-19 20:00:03.000,1,AATI,US00752J1088,1113,1.070037e+06,4.164477e+05,6.341652e+05,...,147,5.209298e+05,5.296831e+05,71,75,14078.30,5346.06,7,3,2007-01-19
8,2007-01-19,2007-01-19 17:51:00.000,2007-01-19 20:00:03.000,1,AAWW,US0491642056,364,2.324789e+06,1.099567e+06,1.211916e+06,...,105,1.101440e+06,1.210042e+06,30,54,13306.67,0.00,2,0,2007-01-19
9,2007-01-19,2007-01-19 16:01:00.000,2007-01-19 20:00:03.000,1,ABAX,US0025671050,1322,8.886112e+06,2.736429e+06,6.049543e+06,...,315,4.465150e+06,4.320822e+06,205,354,22999.72,77140.12,9,20,2007-01-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-12,2024-01-12 19:16:00.000,2024-01-12 20:00:03.000,1,A,US00846U1016,25449,1.592554e+08,7.855911e+07,7.781867e+07,...,5563,74399837.32,8.197794e+07,9089,16359,1406199.28,1471424.83,285,262,2024-01-12
1,2024-01-12,2024-01-12 19:59:00.000,2024-01-12 20:00:03.000,1,AA,US0138721065,35957,1.167746e+08,4.303165e+07,7.075130e+07,...,5060,17131959.93,9.665099e+07,4908,31049,1561367.93,1430242.19,528,510,2024-01-12
2,2024-01-12,2024-01-12 19:59:00.000,2024-01-12 20:00:03.000,1,AADI,US00032Q1040,1481,4.479829e+05,2.206009e+05,1.820728e+05,...,255,200708.66,2.019651e+05,46,42,20592.55,24716.66,54,47,2024-01-12
3,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAL,US02376R1023,177521,1.064509e+09,3.399502e+08,6.400644e+08,...,27121,7375988.62,9.726386e+08,3176,173881,61887448.28,22606577.36,9840,3951,2024-01-12
4,2024-01-12,2024-01-12 19:53:00.000,2024-01-12 20:00:03.000,1,AAN,US00258W1080,2985,1.614325e+06,6.750641e+05,9.092941e+05,...,480,243449.82,1.340908e+06,167,2818,14448.23,15518.86,21,31,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-12,2024-01-12 19:14:00.000,2024-01-12 20:00:03.000,1,AKR,US0042391096,7553,1.115046e+07,4.799029e+06,6.222139e+06,...,893,4897691.27,6.123477e+06,215,224,93958.85,35332.34,61,32,2024-01-12
96,2024-01-12,2024-01-12 17:53:00.000,2024-01-12 20:00:03.000,1,AKRO,US00973Y1082,8801,1.247308e+07,4.403543e+06,7.895147e+06,...,1452,3313512.22,8.985178e+06,2835,5955,67817.15,106571.80,60,88,2024-01-12
97,2024-01-12,2024-01-12 16:21:00.000,2024-01-12 20:00:03.000,1,AKTS,US00973N1028,1421,2.555558e+05,4.512428e+04,1.551393e+05,...,314,104183.28,9.608034e+04,21,79,17693.87,37598.27,160,212,2024-01-12
98,2024-01-12,2024-01-12 17:43:00.000,2024-01-12 20:00:03.000,1,AKYA,US00974H1041,2007,1.356798e+06,6.390633e+05,6.586420e+05,...,290,637385.06,6.603202e+05,66,59,47359.65,11732.73,36,33,2024-01-12
99,2024-01-12,2024-01-12 19:01:00.000,2024-01-12 20:00:03.000,1,AL,US00912X3026,8797,1.769634e+07,6.758241e+06,1.043079e+07,...,1491,4157950.19,1.303109e+07,2432,6339,245600.60,261705.07,175,176,2024-01-12

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-11,2007-01-11 20:00:00.000,2007-01-11 20:00:03.000,1,AAPL,NaN,231957,4.861693e+09,2.323565e+09,2.408443e+09,...,32571,2.103386e+09,2.628622e+09,101463,130149,6.745214e+07,62232804.83,3154,2943,2007-01-11
1,2007-03-09,2007-03-09 19:46:00.000,2007-03-09 20:00:03.000,1,AAPL,US0378331005,77687,1.398205e+09,6.579510e+08,7.054014e+08,...,9750,6.223274e+08,7.410250e+08,31058,36805,1.681228e+07,18040168.12,888,641,2007-03-09
2,2007-01-18,2007-01-18 20:00:00.000,2007-01-18 20:00:03.000,1,AAPL,US0378331005,392606,7.594444e+09,3.660066e+09,3.804852e+09,...,55460,3.267379e+09,4.197539e+09,169677,222927,7.623361e+07,53292802.15,4036,2844,2007-01-18
3,2007-01-29,2007-01-29 19:58:00.000,2007-01-29 20:00:03.000,1,AAPL,US0378331005,150123,2.694978e+09,1.339595e+09,1.309082e+09,...,18967,1.409048e+09,1.239629e+09,76792,73186,2.967418e+07,16626621.64,1666,908,2007-01-29
4,2007-02-08,2007-02-08 20:00:00.000,2007-02-08 20:00:03.000,1,AAPL,US0378331005,112598,2.032911e+09,9.969550e+08,9.863288e+08,...,15532,1.010496e+09,9.727882e+08,57111,55476,2.830822e+07,21319423.81,1565,1177,2007-02-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-06-18,2007-06-18 20:00:00.000,2007-06-18 20:00:03.000,1,AAPL,US0378331005,137967,3.920900e+09,1.988440e+09,1.801436e+09,...,24034,2.060146e+09,1.729731e+09,71922,65685,7.411737e+07,56906223.55,2613,1995,2007-06-18
96,2007-06-05,2007-06-05 20:00:00.000,2007-06-05 20:00:03.000,1,AAPL,US0378331005,146685,3.921671e+09,1.952765e+09,1.864373e+09,...,25540,2.756827e+09,1.060311e+09,103362,43321,6.295086e+07,41582985.86,2345,1537,2007-06-05
97,2007-04-17,2007-04-17 19:35:00.000,2007-04-17 20:00:03.000,1,AAPL,US0378331005,118749,2.368288e+09,1.095818e+09,1.200795e+09,...,14411,9.090009e+08,1.387611e+09,47792,70957,4.261623e+07,29059241.47,2113,1444,2007-04-17
98,2007-07-23,2007-07-23 20:00:00.000,2007-07-23 20:00:03.000,1,AAPL,US0378331005,156667,5.165113e+09,2.478960e+09,2.479957e+09,...,30523,2.245151e+09,2.713766e+09,68645,88021,1.110831e+08,95112398.71,3335,2860,2007-07-23
99,2007-06-19,2007-06-19 20:00:00.000,2007-06-19 20:00:03.000,1,AAPL,US0378331005,144641,4.027333e+09,1.853637e+09,2.040225e+09,...,24733,1.390324e+09,2.503538e+09,52027,92566,7.860340e+07,54868277.98,2780,1934,2007-06-19

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,US0378331005,990770,1.412446e+10,6.623133e+09,6.059657e+09,...,203661,5.313069e+09,7.369722e+09,246489,744247,9.361314e+08,5.055404e+08,69922,36466,2024-01-02
1,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,US0378331005,704321,1.160613e+10,5.085703e+09,5.255791e+09,...,141719,3.824969e+09,6.516526e+09,285462,418792,8.521401e+08,4.124940e+08,52306,25296,2024-01-04
2,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,US0378331005,675348,1.073244e+10,5.060611e+09,4.557467e+09,...,132532,3.601085e+09,6.016993e+09,349875,324250,7.120352e+08,4.023235e+08,46270,25440,2024-01-05
3,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,US0378331005,672874,1.247752e+10,6.400096e+09,5.082925e+09,...,121471,7.644141e+09,3.838881e+09,532463,140411,5.415680e+08,4.529306e+08,32810,25615,2024-01-19
4,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,US0378331005,682124,9.997138e+09,5.243468e+09,3.764531e+09,...,131716,4.989186e+09,4.018813e+09,331875,350249,5.983342e+08,3.908052e+08,41139,26414,2024-01-30
5,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,US0378331005,646673,9.850288e+09,4.962282e+09,3.895570e+09,...,129184,5.887301e+09,2.970551e+09,337365,309308,5.323861e+08,4.600496e+08,36499,31646,2024-01-03
6,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,US0378331005,547962,8.236493e+09,4.186085e+09,3.235029e+09,...,100367,5.489186e+09,1.931929e+09,394721,153237,4.965947e+08,3.187833e+08,33865,20667,2024-01-10
7,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,US0378331005,673799,9.649775e+09,4.751167e+09,4.091920e+09,...,129080,4.310247e+09,4.532841e+09,419311,254487,4.901400e+08,3.165473e+08,36382,23948,2024-01-31
8,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,US0378331005,659244,1.029335e+10,5.566822e+09,3.684005e+09,...,122232,7.146958e+09,2.103868e+09,426813,231163,6.522098e+08,3.903147e+08,45879,26647,2024-01-08
9,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,US0378331005,590109,8.135219e+09,3.895651e+09,3.483823e+09,...,105286,2.352413e+09,5.027061e+09,218967,369775,4.377972e+08,3.179474e+08,31284,22478,2024-01-29
10,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,US0378331005,470683,6.976981e+09,3.291219e+09,3.002975e+09,...,82997,1.538530e+09,4.755664e+09,141921,326966,4.153750e+08,2.674128e+08,29498,17852,2024-01-12
11,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,US0378331005,527653,8.164333e+09,3.866420e+09,3.615050e+09,...,92776,4.173273e+09,3.308197e+09,306436,220072,3.827252e+08,3.001382e+08,24914,19586,2024-01-26
12,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,US0378331005,585486,8.177438e+09,4.069354e+09,3.347696e+09,...,105859,4.263990e+09,3.153060e+09,301897,283518,4.652283e+08,2.951595e+08,33131,20739,2024-01-17
13,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,US0378331005,754695,1.064378e+10,5.534916e+09,4.143439e+09,...,140422,6.128546e+09,3.549808e+09,468751,285943,5.864017e+08,3.790271e+08,44587,28380,2024-01-16
14,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,US0378331005,635511,9.921383e+09,4.652936e+09,4.391468e+09,...,110064,4.187532e+09,4.856872e+09,305904,329605,4.808354e+08,3.961437e+08,31153,25473,2024-01-25
15,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,US0378331005,587965,9.464530e+09,4.085500e+09,4.528231e+09,...,105631,2.183976e+09,6.429755e+09,217942,370023,4.297140e+08,4.210849e+08,27663,27274,2024-01-24
16,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,US0378331005,527096,7.690177e+09,4.095794e+09,2.835907e+09,...,91853,4.247200e+09,2.684500e+09,294083,229944,3.875323e+08,3.709440e+08,25365,23987,2024-01-23
17,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,US0378331005,777010,1.407412e+10,6.441001e+09,6.411099e+09,...,144863,6.152252e+09,6.699848e+09,461588,313288,6.676443e+08,5.543803e+08,39269,31654,2024-01-18
18,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,US0378331005,530847,7.457587e+09,4.198502e+09,2.517493e+09,...,98441,5.814233e+09,9.017617e+08,453102,77735,4.232342e+08,3.183575e+08,32096,23905,2024-01-09
19,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,US0378331005,708837,1.076401e+10,5.608460e+09,4.200627e+09,...,125211,4.332346e+09,5.476742e+09,387027,321791,5.172395e+08,4.376786e+08,34889,29419,2024-01-22
20,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,US0378331005,573593,8.499696e+09,4.130628e+09,3.580027e+09,...,105521,4.536398e+09,3.174257e+09,254275,319317,4.970836e+08,2.919579e+08,35207,19919,2024-01-11

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial. Downloaded 1 files.