In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_r3k_daily_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-19,2007-01-19 16:10:00.000,2007-01-19 20:00:03.000,1,A,7485,8.957113e+07,3.830808e+07,4.992130e+07,3711,...,1051,3.773032e+07,5.049906e+07,3735,3750,3.346672e+05,1007085.00,32,73,2007-01-19
1,2007-01-19,2007-01-19 18:52:00.000,2007-01-19 20:00:03.000,1,AA,35502,4.084841e+08,2.121450e+08,1.834921e+08,19057,...,4460,2.135025e+08,1.821346e+08,19592,15910,6.278538e+06,6568464.97,356,382,2007-01-19
2,2007-01-19,2007-01-19 16:03:00.000,2007-01-19 20:00:03.000,1,AACC,521,1.170652e+06,5.246003e+05,5.831003e+05,262,...,106,5.199406e+05,5.877601e+05,264,257,2.433409e+04,38617.58,6,6,2007-01-19
3,2007-01-19,2007-01-19 16:04:00.000,2007-01-19 20:00:03.000,1,AAI,4604,1.663660e+07,7.227532e+06,9.017165e+06,2100,...,593,7.221779e+06,9.022918e+06,2102,2502,1.278162e+05,264089.29,20,19,2007-01-19
4,2007-01-19,2007-01-19 16:13:00.000,2007-01-19 20:00:03.000,1,AAON,156,5.981691e+05,3.194612e+05,2.317233e+05,92,...,41,3.202574e+05,2.309271e+05,91,64,2.652226e+04,20462.31,2,1,2007-01-19
5,2007-01-19,2007-01-19 16:07:00.000,2007-01-19 20:00:03.000,1,AAP,3429,2.547768e+07,1.393067e+07,1.139453e+07,1916,...,705,1.397020e+07,1.135500e+07,1943,1486,1.226888e+05,29800.08,12,4,2007-01-19
6,2007-01-19,2007-01-19 20:00:00.000,2007-01-19 20:00:03.000,1,AAPL,226821,4.264110e+09,2.040741e+09,2.010729e+09,106087,...,29790,2.033817e+09,2.017653e+09,113992,112829,1.150057e+08,97633561.25,2574,1493,2007-01-19
7,2007-01-19,2007-01-19 16:01:00.000,2007-01-19 20:00:03.000,1,AATI,1113,1.070037e+06,4.035285e+05,6.341565e+05,452,...,147,4.155746e+05,6.221104e+05,463,650,2.342861e+04,8923.55,7,3,2007-01-19
8,2007-01-19,2007-01-19 17:51:00.000,2007-01-19 20:00:03.000,1,AAWW,364,2.324789e+06,1.141111e+06,1.170372e+06,188,...,105,1.160207e+06,1.151275e+06,188,176,1.330667e+04,0.00,2,0,2007-01-19
9,2007-01-19,2007-01-19 16:01:00.000,2007-01-19 20:00:03.000,1,ABAX,1322,8.886112e+06,2.713369e+06,5.999022e+06,494,...,315,2.749798e+06,5.962593e+06,522,800,2.790534e+04,145814.95,9,20,2007-01-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_daily_v1_2_1_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-03,2024-01-03 19:45:00.000,2024-01-03 20:00:03.000,1,A,40118,2.456688e+08,1.346988e+08,1.056200e+08,19343,...,9755,1.359247e+08,1.043941e+08,19561,20557,2852794.01,2497150.36,670,575,2024-01-03
1,2024-01-03,2024-01-03 19:58:00.000,2024-01-03 20:00:03.000,1,AA,58059,2.295624e+08,1.024996e+08,1.010211e+08,28669,...,8814,1.050930e+08,9.842772e+07,28727,29331,14021097.00,12020564.48,934,1056,2024-01-03
2,2024-01-03,2024-01-03 19:51:00.000,2024-01-03 20:00:03.000,1,AADI,2831,8.863158e+05,3.067795e+05,4.105110e+05,1248,...,381,2.739500e+05,4.433405e+05,1108,1723,89473.77,79551.32,149,78,2024-01-03
3,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAL,99031,5.188467e+08,2.050433e+08,2.350984e+08,47775,...,15404,2.053650e+08,2.347768e+08,47186,51844,41812932.87,36892018.61,4156,2584,2024-01-03
4,2024-01-03,2024-01-03 19:01:00.000,2024-01-03 20:00:03.000,1,AAN,5819,4.621547e+06,2.361119e+06,2.111310e+06,2716,...,706,1.967432e+06,2.504997e+06,2751,3067,113446.51,35671.36,37,41,2024-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-03,2024-01-03 19:01:00.000,2024-01-03 20:00:03.000,1,AKR,8884,1.771578e+07,9.927397e+06,7.652824e+06,4787,...,1244,9.877704e+06,7.702517e+06,4745,4139,79358.48,56205.72,60,24,2024-01-03
96,2024-01-03,2024-01-03 19:24:00.000,2024-01-03 20:00:03.000,1,AKRO,11021,1.454053e+07,6.976612e+06,6.998613e+06,4724,...,2128,8.372093e+06,5.603132e+06,4964,6055,350093.76,215210.54,84,74,2024-01-03
97,2024-01-03,2024-01-03 19:35:00.000,2024-01-03 20:00:03.000,1,AKTS,1558,3.328817e+05,1.180044e+05,1.435389e+05,770,...,330,1.148249e+05,1.467184e+05,777,781,19498.99,51839.37,74,180,2024-01-03
98,2024-01-03,2024-01-03 16:10:00.000,2024-01-03 20:00:03.000,1,AKYA,1650,8.761572e+05,3.104218e+05,4.435482e+05,662,...,315,3.330351e+05,4.209350e+05,678,972,76074.88,46112.28,69,26,2024-01-03
99,2024-01-03,2024-01-03 19:01:00.000,2024-01-03 20:00:03.000,1,AL,13614,3.407100e+07,1.585978e+07,1.707499e+07,5846,...,2092,1.665089e+07,1.628388e+07,5954,7660,439541.83,696688.65,185,132,2024-01-03

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_daily_v1_2_1_trial', key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-13,2007-02-13 19:59:00.000,2007-02-13 20:00:03.000,1,AAPL,100533,1.735861e+09,7.703071e+08,8.408666e+08,46963,...,11817,7.692750e+08,8.418987e+08,49350,51183,6.915395e+07,5.553327e+07,1515,1128,2007-02-13
1,2007-01-29,2007-01-29 19:58:00.000,2007-01-29 20:00:03.000,1,AAPL,150123,2.694978e+09,1.283721e+09,1.273261e+09,70677,...,18967,1.281411e+09,1.275571e+09,75817,74306,8.132427e+07,5.667151e+07,1666,908,2007-01-29
2,2007-01-25,2007-01-25 19:58:00.000,2007-01-25 20:00:03.000,1,AAPL,142310,2.804558e+09,1.253033e+09,1.312986e+09,67401,...,21101,1.248192e+09,1.317826e+09,69921,72389,1.356121e+08,1.029274e+08,2765,1837,2007-01-25
3,2007-02-06,2007-02-06 19:58:00.000,2007-02-06 20:00:03.000,1,AAPL,141501,2.558329e+09,1.196953e+09,1.177160e+09,68630,...,17244,1.194111e+09,1.180001e+09,71438,70063,1.106801e+08,7.353638e+07,1969,1371,2007-02-06
4,2007-02-02,2007-02-02 20:00:00.000,2007-02-02 20:00:03.000,1,AAPL,98067,1.832543e+09,8.493283e+08,8.699275e+08,45879,...,12798,8.469274e+08,8.723284e+08,48827,49240,6.720740e+07,4.608002e+07,1321,937,2007-02-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-07-20,2007-07-20 20:00:00.000,2007-07-20 20:00:03.000,1,AAPL,182395,5.916479e+09,2.752056e+09,2.743608e+09,89873,...,29625,2.750322e+09,2.745343e+09,91355,91040,2.329773e+08,1.878375e+08,3210,2220,2007-07-20
96,2007-06-12,2007-06-12 20:00:00.000,2007-06-12 20:00:03.000,1,AAPL,247839,6.054687e+09,2.825556e+09,2.811887e+09,123637,...,40114,2.817106e+09,2.820338e+09,124829,123010,2.330923e+08,1.841505e+08,3317,2050,2007-06-12
97,2007-07-05,2007-07-05 20:00:00.000,2007-07-05 20:00:03.000,1,AAPL,229511,6.706400e+09,3.164874e+09,2.918163e+09,117578,...,40546,3.164165e+09,2.918872e+09,119002,110509,3.131605e+08,3.102022e+08,4796,3506,2007-07-05
98,2007-06-08,2007-06-08 20:00:00.000,2007-06-08 20:00:03.000,1,AAPL,210114,5.401985e+09,2.525541e+09,2.484462e+09,104271,...,36784,2.529349e+09,2.480654e+09,105651,104462,2.087104e+08,1.832716e+08,2787,1933,2007-06-08
99,2007-05-30,2007-05-30 20:00:00.000,2007-05-30 20:00:03.000,1,AAPL,230896,6.085271e+09,2.917533e+09,2.756442e+09,118167,...,35410,2.921736e+09,2.752239e+09,119083,111813,2.208064e+08,1.904894e+08,2969,2392,2007-05-30

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_daily_v1_2_1_trial',key='AAPL', back_to='2022-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2022-01-18,2022-01-18 20:00:00.000,2022-01-18 20:00:03.000,1,AAPL,767029,1.483433e+10,6.281025e+09,7.029297e+09,368999,...,165334,6.271842e+09,7.038480e+09,367852,399175,8.066969e+08,7.173098e+08,45747,28902,2022-01-18
1,2022-01-07,2022-01-07 20:00:00.000,2022-01-07 20:00:03.000,1,AAPL,711666,1.344828e+10,5.956904e+09,5.840731e+09,351378,...,153941,5.797197e+09,6.000438e+09,350095,361569,8.461815e+08,8.044663e+08,46317,31092,2022-01-07
2,2022-01-28,2022-01-28 20:00:00.000,2022-01-28 20:00:03.000,1,AAPL,1511942,2.812656e+10,1.256273e+10,1.248664e+10,757466,...,313971,1.253689e+10,1.251249e+10,755451,756491,1.613927e+09,1.463257e+09,69435,53992,2022-01-28
3,2022-01-13,2022-01-13 20:00:00.000,2022-01-13 20:00:03.000,1,AAPL,689514,1.420486e+10,6.040447e+09,6.526145e+09,335703,...,146888,5.922502e+09,6.644090e+09,333716,355797,9.008735e+08,7.373910e+08,38234,25617,2022-01-13
4,2022-02-08,2022-02-08 20:00:00.000,2022-02-08 20:00:03.000,1,AAPL,632268,1.241643e+10,5.641002e+09,5.221946e+09,324513,...,124205,5.618261e+09,5.244687e+09,324176,308092,8.110031e+08,7.424756e+08,32647,26855,2022-02-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-01-18,2023-01-18 20:00:00.000,2023-01-18 20:00:03.000,1,AAPL,573396,9.255416e+09,3.609657e+09,4.354573e+09,261127,...,122573,3.588779e+09,4.375451e+09,261884,311511,6.735633e+08,6.176226e+08,59552,26975,2023-01-18
96,2023-02-02,2023-02-02 20:00:00.000,2023-02-02 20:00:03.000,1,AAPL,990233,1.621296e+10,7.486839e+09,6.848655e+09,508715,...,226832,7.429731e+09,6.905763e+09,507653,482579,9.811926e+08,8.962757e+08,83452,45890,2023-02-02
97,2023-02-01,2023-02-01 20:00:00.000,2023-02-01 20:00:03.000,1,AAPL,688684,1.093996e+10,4.745077e+09,4.716565e+09,353124,...,150747,4.817906e+09,4.643735e+09,352080,336604,7.419244e+08,7.363980e+08,63994,32514,2023-02-01
98,2023-02-13,2023-02-13 20:00:00.000,2023-02-13 20:00:03.000,1,AAPL,502791,9.094067e+09,4.048869e+09,3.754409e+09,232007,...,103921,4.056552e+09,3.746726e+09,233735,269056,6.565309e+08,6.342583e+08,73420,28284,2023-02-13
99,2023-02-22,2023-02-22 20:00:00.000,2023-02-22 20:00:03.000,1,AAPL,426248,7.466282e+09,3.022950e+09,3.370748e+09,196943,...,100103,2.977946e+09,3.415752e+09,197157,229091,5.125048e+08,5.600793e+08,48584,23837,2023-02-22

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_daily_v1_2_1_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for lseg_us_eqt_flow_r3k_daily_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_r3k_daily_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_daily_v1_2_1_trial", target_location="./data")