In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-09,2007-01-09 04:30:00.000,2007-01-09 04:30:03.000,1,AAPL,None,1,77400.0,38700.0,38700.0,...,1,77400.0,0,1,0,0,0,0,0,2007-01-09
1,2007-01-09,2007-01-09 04:41:00.000,2007-01-09 04:41:03.000,1,AAPL,None,1,17240.0,17240.0,0.0,...,0,17240.0,0,1,0,0,0,0,0,2007-01-09
2,2007-01-09,2007-01-09 05:00:00.000,2007-01-09 05:00:03.000,1,EBAY,None,1,4276.8,2138.4,2138.4,...,1,4276.8,0,1,0,0,0,0,0,2007-01-09
3,2007-01-09,2007-01-09 05:14:00.000,2007-01-09 05:14:03.000,1,AAPL,None,2,68955.0,68955.0,0.0,...,1,68955.0,0,2,0,0,0,0,0,2007-01-09
4,2007-01-09,2007-01-09 05:22:00.000,2007-01-09 05:22:03.000,1,AAPL,None,1,8620.0,8620.0,0.0,...,0,8620.0,0,1,0,0,0,0,0,2007-01-09
5,2007-01-09,2007-01-09 05:28:00.000,2007-01-09 05:28:03.000,1,AAPL,None,1,8620.0,0.0,8620.0,...,0,0.0,8620,0,1,0,0,0,0,2007-01-09
6,2007-01-09,2007-01-09 05:54:00.000,2007-01-09 05:54:03.000,1,IBM,None,1,9905.0,4952.5,4952.5,...,1,9905.0,0,1,0,0,0,0,0,2007-01-09
7,2007-01-09,2007-01-09 05:58:00.000,2007-01-09 05:58:03.000,1,AAPL,None,1,8629.0,8629.0,0.0,...,0,8629.0,0,1,0,0,0,0,0,2007-01-09
8,2007-01-09,2007-01-09 06:01:00.000,2007-01-09 06:01:03.000,1,AAPL,None,1,8629.0,8629.0,0.0,...,0,8629.0,0,1,0,0,0,0,0,2007-01-09
9,2007-01-09,2007-01-09 06:02:00.000,2007-01-09 06:02:03.000,1,IBM,None,1,9910.0,9910.0,0.0,...,0,9910.0,0,1,0,0,0,0,0,2007-01-09

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AADI,US00032Q1040,1,40.7100,20.36,20.36,...,1,40.71,0.00,1,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,US0378331005,163,891117.1800,563098.59,328018.59,...,44,541230.68,349886.50,99,64,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,US00287Y1091,4,4122.7000,3607.36,515.34,...,2,2061.35,2061.35,2,2,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABNB,US0090661010,10,23302.4700,19807.10,3495.37,...,5,16311.73,6990.74,6,2,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABT,US0028241000,1,1134.1000,567.05,567.05,...,1,1134.10,0.00,1,0,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FLNG,BMG359472021,1,1519.5000,759.75,759.75,...,1,0.00,1519.50,0,1,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FMC,US3024913036,1,114.9800,57.49,57.49,...,1,57.49,57.49,0,0,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FSR,US33813J1060,29,4471.2685,3469.09,1002.18,...,14,2775.27,1696.00,18,11,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FTI,GB00BDSFG982,2,183.6000,45.90,137.70,...,1,0.00,183.60,0,2,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,GDDY,US3802371076,2,11881.0000,5940.50,5940.50,...,1,0.00,11881.00,0,2,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-13,2007-03-13 07:18:00.000,2007-03-13 07:18:03.000,1,AAPL,US0378331005,4,6.289100e+04,55029.62,7861.38,...,2,62891.00,0.00,4,0,0.00,0.00,0,0,2007-03-13
1,2007-03-13,2007-03-13 07:46:00.000,2007-03-13 07:46:03.000,1,AAPL,US0378331005,2,2.688500e+04,0.00,26885.00,...,2,0.00,26885.00,0,2,0.00,0.00,0,0,2007-03-13
2,2007-03-13,2007-03-13 07:49:00.000,2007-03-13 07:49:03.000,1,AAPL,US0378331005,1,8.960000e+03,0.00,8960.00,...,1,0.00,8960.00,0,1,0.00,0.00,0,0,2007-03-13
3,2007-03-13,2007-03-13 07:50:00.000,2007-03-13 07:50:03.000,1,AAPL,US0378331005,3,2.688000e+04,8960.00,17920.00,...,0,8960.00,17920.00,1,2,0.00,0.00,0,0,2007-03-13
4,2007-03-13,2007-03-13 07:51:00.000,2007-03-13 07:51:03.000,1,AAPL,US0378331005,1,8.960000e+03,0.00,8960.00,...,0,0.00,8960.00,0,1,0.00,0.00,0,0,2007-03-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-03-13,2007-03-13 09:52:00.000,2007-03-13 09:52:03.000,0,AAPL,US0378331005,483,9.148165e+06,4789725.14,3812140.64,...,41,4695023.64,3906842.14,272,211,456737.75,89561.00,4,1,2007-03-13
96,2007-03-13,2007-03-13 09:53:00.000,2007-03-13 09:53:03.000,0,AAPL,US0378331005,556,8.903688e+06,4292140.92,3810914.57,...,66,4260113.26,3842942.22,297,259,495993.27,304638.90,9,5,2007-03-13
97,2007-03-13,2007-03-13 09:54:00.000,2007-03-13 09:54:03.000,0,AAPL,US0378331005,426,6.245954e+06,2442833.80,3328243.01,...,52,2413510.07,3357566.74,197,229,474877.04,0.00,7,0,2007-03-13
98,2007-03-13,2007-03-13 09:55:00.000,2007-03-13 09:55:03.000,0,AAPL,US0378331005,778,1.301840e+07,6380066.75,5616362.68,...,115,6672897.00,5323532.43,432,346,555826.93,466139.98,9,5,2007-03-13
99,2007-03-13,2007-03-13 09:56:00.000,2007-03-13 09:56:03.000,0,AAPL,US0378331005,525,7.585115e+06,2303926.27,4725293.75,...,71,2123328.29,4905891.73,160,365,188325.90,367569.39,2,7,2007-03-13

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial',key='AAPL', back_to='2019-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2019-04-10,2019-04-10 04:01:00.000,2019-04-10 04:01:03.000,1,AAPL,US0378331005,56,1414020.15,896387.77,517632.38,...,12,820636.69,593383.46,23,14,0,0,0,0,2019-04-10
1,2019-04-10,2019-04-10 04:02:00.000,2019-04-10 04:02:03.000,1,AAPL,US0378331005,15,288432.35,192288.23,96144.12,...,5,153830.59,134601.76,8,7,0,0,0,0,2019-04-10
2,2019-04-10,2019-04-10 04:03:00.000,2019-04-10 04:03:03.000,1,AAPL,US0378331005,4,46860.72,35145.54,11715.18,...,2,23430.36,23430.36,2,2,0,0,0,0,2019-04-10
3,2019-04-10,2019-04-10 04:04:00.000,2019-04-10 04:04:03.000,1,AAPL,US0378331005,6,106387.94,88656.62,17731.32,...,2,53193.97,53193.97,3,3,0,0,0,0,2019-04-10
4,2019-04-10,2019-04-10 04:05:00.000,2019-04-10 04:05:03.000,1,AAPL,US0378331005,11,134937.97,12267.09,122670.88,...,6,12267.09,122670.88,1,10,0,0,0,0,2019-04-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-04-10,2019-04-10 06:32:00.000,2019-04-10 06:32:03.000,1,AAPL,US0378331005,20,669916.56,100487.48,569429.08,...,6,100487.48,569429.08,3,17,0,0,0,0,2019-04-10
96,2019-04-10,2019-04-10 06:33:00.000,2019-04-10 06:33:03.000,1,AAPL,US0378331005,12,472876.44,275844.59,197031.85,...,5,197031.85,275844.59,5,7,0,0,0,0,2019-04-10
97,2019-04-10,2019-04-10 06:34:00.000,2019-04-10 06:34:03.000,1,AAPL,US0378331005,3,3953.50,2635.67,1317.83,...,0,2635.67,1317.83,2,1,0,0,0,0,2019-04-10
98,2019-04-10,2019-04-10 06:36:00.000,2019-04-10 06:36:03.000,1,AAPL,US0378331005,1,18593.20,18593.20,0.00,...,0,18593.20,0.00,1,0,0,0,0,0,2019-04-10
99,2019-04-10,2019-04-10 06:37:00.000,2019-04-10 06:37:03.000,1,AAPL,US0378331005,5,45493.74,9098.75,36394.99,...,2,18197.50,27296.24,2,3,0,0,0,0,2019-04-10

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial", target_location="./data", asof_date='2025-01-17')

Starting native python replication for lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial", target_location="./data")