In [2]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [3]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_r3k_1min_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-16,2007-01-16 04:16:00.000,2007-01-16 04:16:03.000,1,AAPL,1,38208.00,19104.00,19104.00,0,...,1,38208.00,0.00,1,0,0,0,0,0,2007-01-16
1,2007-01-16,2007-01-16 04:16:00.000,2007-01-16 04:16:03.000,1,CSCO,21,516982.89,135400.28,381582.61,5,...,14,123091.16,393891.73,4,15,0,0,0,0,2007-01-16
2,2007-01-16,2007-01-16 04:17:00.000,2007-01-16 04:17:03.000,1,CSCO,10,266534.00,0.00,266534.00,0,...,9,0.00,266534.00,0,10,0,0,0,0,2007-01-16
3,2007-01-16,2007-01-16 04:20:00.000,2007-01-16 04:20:03.000,1,MOT,1,5478.00,2739.00,2739.00,0,...,1,0.00,5478.00,0,1,0,0,0,0,2007-01-16
4,2007-01-16,2007-01-16 04:22:00.000,2007-01-16 04:22:03.000,1,INWK,1,7890.00,3945.00,3945.00,0,...,1,0.00,7890.00,0,1,0,0,0,0,2007-01-16
5,2007-01-16,2007-01-16 04:26:00.000,2007-01-16 04:26:03.000,1,MSFT,1,6272.00,3136.00,3136.00,0,...,1,6272.00,0.00,1,0,0,0,0,0,2007-01-16
6,2007-01-16,2007-01-16 04:56:00.000,2007-01-16 04:56:03.000,1,PFE,1,2664.00,1332.00,1332.00,0,...,1,1332.00,1332.00,0,0,0,0,0,0,2007-01-16
7,2007-01-16,2007-01-16 05:06:00.000,2007-01-16 05:06:03.000,1,SIRI,1,8340.00,4170.00,4170.00,0,...,1,8340.00,0.00,1,0,0,0,0,0,2007-01-16
8,2007-01-16,2007-01-16 05:11:00.000,2007-01-16 05:11:03.000,1,INTC,1,2202.00,1101.00,1101.00,0,...,1,0.00,2202.00,0,1,0,0,0,0,2007-01-16
9,2007-01-16,2007-01-16 05:12:00.000,2007-01-16 05:12:03.000,1,PNSN,1,2900.00,1450.00,1450.00,0,...,1,1450.00,1450.00,0,0,0,0,0,0,2007-01-16

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_1min_v1_2_1_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AADI,1,40.7100,20.36,20.36,0,...,1,40.71,0.00,1,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,163,891117.1800,563098.59,328018.59,98,...,44,541230.68,349886.50,99,64,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,4,4122.7000,3607.36,515.34,3,...,2,2061.35,2061.35,2,2,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABNB,10,23302.4700,19807.10,3495.37,8,...,5,16311.73,6990.74,6,2,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABT,1,1134.1000,567.05,567.05,0,...,1,1134.10,0.00,1,0,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FLNG,1,1519.5000,759.75,759.75,0,...,1,0.00,1519.50,0,1,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FMC,1,114.9800,57.49,57.49,0,...,1,57.49,57.49,0,0,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FSR,29,4471.2685,3469.09,1002.18,17,...,14,2775.27,1696.00,18,11,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FTI,2,183.6000,45.90,137.70,0,...,1,0.00,183.60,0,2,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,GDDY,2,11881.0000,5940.50,5940.50,0,...,1,0.00,11881.00,0,2,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_1min_v1_2_1_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-23,2007-03-23 07:59:00.000,2007-03-23 07:59:03.000,1,AAPL,1,9.390000e+03,4695.00,4695.00,0,...,1,9390.00,0.00,1,0,0.00,0.00,0,0,2007-03-23
1,2007-03-23,2007-03-23 08:01:00.000,2007-03-23 08:01:03.000,1,AAPL,1,9.379000e+03,9379.00,0.00,1,...,1,0.00,9379.00,0,1,0.00,0.00,0,0,2007-03-23
2,2007-03-23,2007-03-23 08:03:00.000,2007-03-23 08:03:03.000,1,AAPL,6,1.193161e+05,0.00,119316.10,0,...,4,0.00,119316.10,0,6,0.00,0.00,0,0,2007-03-23
3,2007-03-23,2007-03-23 08:04:00.000,2007-03-23 08:04:03.000,1,AAPL,3,7.489600e+04,49930.67,24965.33,2,...,1,49930.67,24965.33,2,1,0.00,0.00,0,0,2007-03-23
4,2007-03-23,2007-03-23 08:05:00.000,2007-03-23 08:05:03.000,1,AAPL,7,2.946280e+05,0.00,294628.00,0,...,3,0.00,294628.00,0,7,0.00,0.00,0,0,2007-03-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-03-23,2007-03-23 09:38:00.000,2007-03-23 09:38:03.000,0,AAPL,301,4.620385e+06,2154915.80,2317867.78,150,...,49,2154915.80,2317867.78,150,151,147601.87,0.00,4,0,2007-03-23
96,2007-03-23,2007-03-23 09:39:00.000,2007-03-23 09:39:03.000,0,AAPL,410,7.372164e+06,3222080.24,3443415.63,206,...,56,3204099.36,3461396.52,205,205,481982.80,224685.64,9,2,2007-03-23
97,2007-03-23,2007-03-23 09:40:00.000,2007-03-23 09:40:03.000,0,AAPL,400,8.425942e+06,3613880.22,4537994.19,176,...,60,3550685.65,4601188.76,173,227,93534.35,180533.44,4,5,2007-03-23
98,2007-03-23,2007-03-23 09:41:00.000,2007-03-23 09:41:03.000,0,AAPL,406,8.014256e+06,3695166.85,3646413.49,197,...,61,3665557.53,3676022.81,198,208,242872.77,429802.95,5,5,2007-03-23
99,2007-03-23,2007-03-23 09:42:00.000,2007-03-23 09:42:03.000,0,AAPL,211,3.983216e+06,1997138.65,1097539.01,138,...,20,1959383.05,1135294.61,136,75,607997.95,280540.50,4,3,2007-03-23

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_1min_v1_2_1_trial',key='AAPL', back_to='2019-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2019-02-20,2019-02-20 04:01:00.000,2019-02-20 04:01:03.000,1,AAPL,1,342.00,171.00,171.00,0,...,1,171.00,171.00,0,0,0,0.0,0,0,2019-02-20
1,2019-02-20,2019-02-20 04:29:00.000,2019-02-20 04:29:03.000,1,AAPL,2,34190.00,34190.00,0.00,2,...,1,17095.00,17095.00,1,1,0,0.0,0,0,2019-02-20
2,2019-02-20,2019-02-20 04:36:00.000,2019-02-20 04:36:03.000,1,AAPL,11,256934.01,23357.64,233576.37,1,...,2,23357.64,233576.37,1,10,0,0.0,0,0,2019-02-20
3,2019-02-20,2019-02-20 04:38:00.000,2019-02-20 04:38:03.000,1,AAPL,1,16582.15,16582.15,0.00,1,...,1,16582.15,0.00,1,0,0,0.0,0,0,2019-02-20
4,2019-02-20,2019-02-20 04:47:00.000,2019-02-20 04:47:03.000,1,AAPL,6,42681.08,0.00,42681.08,0,...,3,0.00,42681.08,0,6,0,0.0,0,0,2019-02-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-02-20,2019-02-20 08:32:00.000,2019-02-20 08:32:03.000,1,AAPL,9,134225.79,104397.84,29827.95,7,...,1,119311.81,14913.98,8,1,0,0.0,0,0,2019-02-20
96,2019-02-20,2019-02-20 08:33:00.000,2019-02-20 08:33:03.000,1,AAPL,1,5628.48,5628.48,0.00,1,...,1,5628.48,0.00,1,0,0,0.0,0,0,2019-02-20
97,2019-02-20,2019-02-20 08:34:00.000,2019-02-20 08:34:03.000,1,AAPL,1,682.08,0.00,682.08,0,...,1,0.00,682.08,0,1,0,0.0,0,0,2019-02-20
98,2019-02-20,2019-02-20 08:36:00.000,2019-02-20 08:36:03.000,1,AAPL,4,77951.96,58463.97,19487.99,3,...,0,58463.97,19487.99,3,1,0,0.0,0,0,2019-02-20
99,2019-02-20,2019-02-20 08:37:00.000,2019-02-20 08:37:03.000,1,AAPL,15,234370.16,171871.45,62498.71,11,...,1,218745.48,15624.68,14,1,0,0.0,0,0,2019-02-20

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_1min_v1_2_1_trial", target_location="./data", asof_date='2025-01-17')

Starting native python replication for lseg_us_eqt_flow_r3k_1min_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_r3k_1min_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_1min_v1_2_1_trial", target_location="./data")