In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-25,2007-01-25 18:04:00.000,2007-01-25 20:00:03.000,1,A,US00846U1016,7001,5.933080e+07,2.392191e+07,3.446212e+07,...,1099,2.462355e+07,3.376049e+07,2923,4078,6.289103e+05,3.178507e+05,42,24,2007-01-25
1,2007-01-25,2007-01-25 16:32:00.000,2007-01-25 20:00:03.000,1,AA,US0138171014,17162,1.788008e+08,9.232022e+07,8.280496e+07,...,2266,9.074833e+07,8.437685e+07,8697,8465,1.790223e+06,1.885404e+06,114,123,2007-01-25
2,2007-01-25,2007-01-25 16:01:00.000,2007-01-25 20:00:03.000,1,AACC,US04543P1003,585,1.409675e+06,6.519575e+05,6.721884e+05,...,118,6.344275e+05,6.897184e+05,280,305,1.860751e+04,6.692174e+04,5,6,2007-01-25
3,2007-01-25,2007-01-25 18:20:00.000,2007-01-25 20:00:03.000,1,AAI,US00949P1084,7220,3.188076e+07,1.377182e+07,1.756636e+07,...,849,1.373805e+07,1.760013e+07,3227,3992,4.028657e+05,1.397226e+05,58,21,2007-01-25
4,2007-01-25,2007-01-25 16:01:00.000,2007-01-25 20:00:03.000,1,AAON,US0003602069,269,1.105723e+06,5.424674e+05,5.493262e+05,...,88,5.277838e+05,5.640098e+05,124,143,1.392962e+04,0.000000e+00,2,0,2007-01-25
5,2007-01-25,2007-01-25 16:02:00.000,2007-01-25 20:00:03.000,1,AAP,US00751Y1064,2669,2.688443e+07,1.287385e+07,1.393984e+07,...,455,1.328562e+07,1.352808e+07,1338,1331,4.472446e+04,2.601622e+04,5,2,2007-01-25
6,2007-01-25,2007-01-25 19:58:00.000,2007-01-25 20:00:03.000,1,AAPL,US0378331005,142310,2.804558e+09,1.253033e+09,1.312986e+09,...,21101,1.248192e+09,1.317826e+09,69921,72389,1.356121e+08,1.029274e+08,2765,1837,2007-01-25
7,2007-01-25,2007-01-25 16:01:00.000,2007-01-25 20:00:03.000,1,AATI,US00752J1088,1469,2.150593e+06,1.079640e+06,9.122270e+05,...,166,1.089126e+06,9.027416e+05,706,762,1.061941e+05,5.253141e+04,13,10,2007-01-25
8,2007-01-25,2007-01-25 16:01:00.000,2007-01-25 20:00:03.000,1,AAWW,US0491642056,996,6.164241e+06,3.459573e+06,2.654490e+06,...,218,3.497351e+06,2.616712e+06,536,459,4.542840e+04,4.750010e+03,3,1,2007-01-25
9,2007-01-25,2007-01-25 16:01:00.000,2007-01-25 20:00:03.000,1,ABAX,US0025671050,1626,6.717249e+06,2.944703e+06,3.493090e+06,...,341,3.116260e+06,3.321533e+06,769,857,1.604110e+05,1.190453e+05,22,31,2007-01-25

## Retrieve data for a specific date range using the back_to and up_to parameters

In [15]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-03,2024-01-03 19:45:00.000,2024-01-03 20:00:03.000,1,A,US00846U1016,40118,2.456688e+08,1.346988e+08,1.056200e+08,...,9755,1.359247e+08,1.043941e+08,19561,20557,2852794.01,2497150.36,670,575,2024-01-03
1,2024-01-03,2024-01-03 19:58:00.000,2024-01-03 20:00:03.000,1,AA,US0138721065,58059,2.295624e+08,1.024996e+08,1.010211e+08,...,8814,1.050930e+08,9.842772e+07,28727,29331,14021097.00,12020564.48,934,1056,2024-01-03
2,2024-01-03,2024-01-03 19:51:00.000,2024-01-03 20:00:03.000,1,AADI,US00032Q1040,2831,8.863158e+05,3.067795e+05,4.105110e+05,...,381,2.739500e+05,4.433405e+05,1108,1723,89473.77,79551.32,149,78,2024-01-03
3,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAL,US02376R1023,99031,5.188467e+08,2.050433e+08,2.350984e+08,...,15404,2.053650e+08,2.347768e+08,47186,51844,41812932.87,36892018.61,4156,2584,2024-01-03
4,2024-01-03,2024-01-03 19:01:00.000,2024-01-03 20:00:03.000,1,AAN,US00258W1080,5819,4.621547e+06,2.361119e+06,2.111310e+06,...,706,1.967432e+06,2.504997e+06,2751,3067,113446.51,35671.36,37,41,2024-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-03,2024-01-03 19:01:00.000,2024-01-03 20:00:03.000,1,AKR,US0042391096,8884,1.771578e+07,9.927397e+06,7.652824e+06,...,1244,9.877704e+06,7.702517e+06,4745,4139,79358.48,56205.72,60,24,2024-01-03
96,2024-01-03,2024-01-03 19:24:00.000,2024-01-03 20:00:03.000,1,AKRO,US00973Y1082,11021,1.454053e+07,6.976612e+06,6.998613e+06,...,2128,8.372093e+06,5.603132e+06,4964,6055,350093.76,215210.54,84,74,2024-01-03
97,2024-01-03,2024-01-03 19:35:00.000,2024-01-03 20:00:03.000,1,AKTS,US00973N1028,1558,3.328817e+05,1.180044e+05,1.435389e+05,...,330,1.148249e+05,1.467184e+05,777,781,19498.99,51839.37,74,180,2024-01-03
98,2024-01-03,2024-01-03 16:10:00.000,2024-01-03 20:00:03.000,1,AKYA,US00974H1041,1650,8.761572e+05,3.104218e+05,4.435482e+05,...,315,3.330351e+05,4.209350e+05,678,972,76074.88,46112.28,69,26,2024-01-03
99,2024-01-03,2024-01-03 19:01:00.000,2024-01-03 20:00:03.000,1,AL,US00912X3026,13614,3.407100e+07,1.585978e+07,1.707499e+07,...,2092,1.665089e+07,1.628388e+07,5954,7660,439541.83,696688.65,185,132,2024-01-03

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [14]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-27,2007-02-27 20:00:00.000,2007-02-27 20:00:03.000,1,AAPL,US0378331005,204768,3.462581e+09,1.603680e+09,1.693561e+09,...,30203,1.589605e+09,1.707637e+09,100346,104422,9.099216e+07,7.434741e+07,2085,1818,2007-02-27
1,2007-02-12,2007-02-12 19:59:00.000,2007-02-12 20:00:03.000,1,AAPL,US0378331005,121601,2.158328e+09,1.050587e+09,9.607316e+08,...,15637,1.049415e+09,9.619030e+08,63360,58241,8.014698e+07,6.686251e+07,1812,1304,2007-02-12
2,2007-01-19,2007-01-19 20:00:00.000,2007-01-19 20:00:03.000,1,AAPL,US0378331005,226821,4.264110e+09,2.040741e+09,2.010729e+09,...,29790,2.033817e+09,2.017653e+09,113992,112829,1.150057e+08,9.763356e+07,2574,1493,2007-01-19
3,2007-01-17,2007-01-17 20:00:00.000,2007-01-17 20:00:03.000,1,AAPL,US0378331005,253950,5.708468e+09,2.631401e+09,2.790156e+09,...,40567,2.628920e+09,2.792638e+09,124461,129489,1.713975e+08,1.155127e+08,3827,2098,2007-01-17
4,2007-03-02,2007-03-02 19:57:00.000,2007-03-02 20:00:03.000,1,AAPL,US0378331005,150055,2.618265e+09,1.183569e+09,1.271055e+09,...,20264,1.176221e+09,1.278403e+09,73321,76734,9.560770e+07,6.803295e+07,1711,1134,2007-03-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-06-15,2007-06-15 20:00:00.000,2007-06-15 20:00:03.000,1,AAPL,US0378331005,106495,3.180462e+09,1.505567e+09,1.484284e+09,...,12410,1.496813e+09,1.493038e+09,53333,53162,1.040892e+08,8.652155e+07,1580,1190,2007-06-15
96,2007-07-17,2007-07-17 19:57:00.000,2007-07-17 20:00:03.000,1,AAPL,US0378331005,111778,3.463065e+09,1.601619e+09,1.617194e+09,...,17727,1.603396e+09,1.615416e+09,55673,56105,1.292858e+08,1.149673e+08,1543,1288,2007-07-17
97,2007-02-28,2007-02-28 20:00:00.000,2007-02-28 20:00:03.000,1,AAPL,US0378331005,157713,2.757976e+09,1.302530e+09,1.312842e+09,...,23534,1.302335e+09,1.313038e+09,78995,78718,8.344847e+07,5.915453e+07,2118,1154,2007-02-28
98,2007-06-21,2007-06-21 20:00:00.000,2007-06-21 20:00:03.000,1,AAPL,US0378331005,136949,3.757300e+09,1.717541e+09,1.688828e+09,...,23928,1.718522e+09,1.687848e+09,69639,67310,1.939309e+08,1.569993e+08,2443,1754,2007-06-21
99,2007-06-28,2007-06-28 20:00:00.000,2007-06-28 20:00:03.000,1,AAPL,US0378331005,126976,3.653755e+09,1.641372e+09,1.687148e+09,...,22593,1.636534e+09,1.691986e+09,64035,62941,1.672249e+08,1.580102e+08,2499,1887,2007-06-28

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [19]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial', key='AAPL', back_to='2022-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2022-01-26,2022-01-26 20:00:00.000,2022-01-26 20:00:03.000,1,AAPL,US0378331005,1013722,1.672295e+10,7.311719e+09,7.720357e+09,...,230304,7.194426e+09,7.837649e+09,494756,518966,9.404790e+08,7.503969e+08,58113,32894,2022-01-26
1,2022-01-14,2022-01-14 20:00:00.000,2022-01-14 20:00:03.000,1,AAPL,US0378331005,667382,1.262481e+10,5.241022e+09,5.907281e+09,...,141861,5.531662e+09,5.616642e+09,324678,342704,7.965006e+08,6.800007e+08,35446,23549,2022-01-14
2,2022-02-02,2022-02-02 20:00:00.000,2022-02-02 20:00:03.000,1,AAPL,US0378331005,673340,1.352860e+10,6.141379e+09,5.955380e+09,...,142922,6.198500e+09,5.898259e+09,342390,330950,7.666940e+08,6.651463e+08,36272,26869,2022-02-02
3,2022-02-16,2022-02-16 20:00:00.000,2022-02-16 20:00:03.000,1,AAPL,US0378331005,540337,9.783475e+09,4.325077e+09,4.429030e+09,...,104894,4.210080e+09,4.544028e+09,266128,274208,5.380722e+08,4.912954e+08,27060,19800,2022-02-16
4,2022-03-21,2022-03-21 20:00:00.000,2022-03-21 20:00:03.000,1,AAPL,US0378331005,708510,1.395959e+10,6.208503e+09,6.195365e+09,...,141637,6.193564e+09,6.210304e+09,343612,364898,8.027371e+08,7.529852e+08,33328,29497,2022-03-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-04-27,2022-04-27 20:00:00.000,2022-04-27 20:00:03.000,1,AAPL,US0378331005,774243,1.296751e+10,5.811970e+09,5.775584e+09,...,176661,5.757637e+09,5.829917e+09,378296,395947,7.085353e+08,6.714240e+08,45020,29328,2022-04-27
96,2022-01-12,2022-01-12 20:00:00.000,2022-01-12 20:00:03.000,1,AAPL,US0378331005,639626,1.265867e+10,5.526064e+09,5.454205e+09,...,133085,5.305173e+09,5.675096e+09,317642,321984,8.911687e+08,7.872321e+08,38432,27641,2022-01-12
97,2023-01-04,2023-01-04 20:00:00.000,2023-01-04 20:00:03.000,1,AAPL,US0378331005,764845,1.094430e+10,4.667323e+09,4.855148e+09,...,171501,4.598532e+09,4.923938e+09,388669,376176,8.022826e+08,6.195456e+08,79450,30807,2023-01-04
98,2023-05-25,2023-05-25 20:00:00.000,2023-05-25 20:00:03.000,1,AAPL,US0378331005,530754,8.882548e+09,4.236061e+09,3.781790e+09,...,108652,4.246405e+09,3.771446e+09,294488,236266,4.447472e+08,4.199505e+08,32805,19816,2023-05-25
99,2023-03-27,2023-03-27 20:00:00.000,2023-03-27 20:00:03.000,1,AAPL,US0378331005,513918,7.780312e+09,3.681789e+09,3.052527e+09,...,103726,3.668827e+09,3.065489e+09,281763,232153,5.101346e+08,5.358610e+08,31430,25594,2023-03-27

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial", target_location="./data")