In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [3]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Futures Reference Table

In [ ]:
df =  Unifier.get_dataframe(name="xtech_futures_flow_forecasts_ident")
display(df)

,identifier,sector,name,contract_multiplier,asof_date
0,CC,Agriculture,Cocoa,10.0,2026-06-09
1,CT,Agriculture,Cotton No. 2,500.0,2026-06-09
2,DC,Agriculture,Class III Milk,2000.0,2026-06-09
3,GF,Agriculture,Feeder Cattle,500.0,2026-06-09
4,HE,Agriculture,Lean Hogs,400.0,2026-06-09
5,KC,Agriculture,Coffee C,375.0,2026-06-09
6,KE,Agriculture,KC HRW Wheat,50.0,2026-06-09
7,LBR,Agriculture,Lumber,27.5,2026-06-09
8,LCC,Agriculture,London Cocoa,10.0,2026-06-09
9,LE,Agriculture,Live Cattle,400.0,2026-06-09
10,LRC,Agriculture,Robusta Coffee,10.0,2026-06-09
11,LSU,Agriculture,White Sugar,50.0,2026-06-09
12,MWE,Agriculture,MGEX Wheat,50.0,2026-06-09
13,OJ,Agriculture,FCOJ-A Orange Juice,150.0,2026-06-09
14,RS,Agriculture,Canola,20.0,2026-06-09
15,SB,Agriculture,Sugar No. 11,1120.0,2026-06-09
16,ZC,Agriculture,Corn,50.0,2026-06-09
17,ZL,Agriculture,Soybean Oil,600.0,2026-06-09
18,ZM,Agriculture,Soybean Meal,100.0,2026-06-09
19,ZO,Agriculture,Oats,50.0,2026-06-09

## XTech Global Futures Flow Position

In [11]:
df =  Unifier.get_dataframe(name="xtech_futures_flow_forecasts_positions",  back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,long_contracts_sensitivity_1,long_contracts_sensitivity_2,long_contracts_sensitivity_3,long_contracts_sensitivity_4,short_contracts_sensitivity_1,short_contracts_sensitivity_2,short_contracts_sensitivity_3,short_contracts_sensitivity_4,asof_date
0,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,BRN,202602,False,producer_merchant,1171302,None,None,None,1427216,None,None,None,2025-12-17
1,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,CC,202603,False,producer_merchant,34928,None,None,None,40320,None,None,None,2025-12-17
2,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,CL,202601,False,producer_merchant,634058,None,None,None,378022,None,None,None,2025-12-17
3,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,CT,202603,False,producer_merchant,67564,None,None,None,68425,None,None,None,2025-12-17
4,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,DC,202512,False,producer_merchant,10863,None,None,None,11730,None,None,None,2025-12-17
5,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,GAS,202601,False,producer_merchant,284199,None,None,None,366389,None,None,None,2025-12-17
6,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,GC,202602,False,producer_merchant,11959,None,None,None,72228,None,None,None,2025-12-17
7,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,GF,202601,False,producer_merchant,7311,None,None,None,13337,None,None,None,2025-12-17
8,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,HE,202602,False,producer_merchant,33434,None,None,None,108598,None,None,None,2025-12-17
9,2025-12-17 07:00:00.000,2025-12-16 00:00:00.000,HG,202603,False,producer_merchant,18738,None,None,None,111882,None,None,None,2025-12-17

In [12]:
df = Unifier.get_dataframe(name="xtech_futures_flow_forecasts_positions", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,long_contracts_sensitivity_1,long_contracts_sensitivity_2,long_contracts_sensitivity_3,long_contracts_sensitivity_4,short_contracts_sensitivity_1,short_contracts_sensitivity_2,short_contracts_sensitivity_3,short_contracts_sensitivity_4,asof_date
0,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,6A,202403,False,managed_money,3859,4410,11417,17385,3587,4099,10612,16159,2024-01-13
1,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,6B,202403,False,managed_money,14821,16938,32268,33897,83,95,181,190,2024-01-13
2,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,6C,202403,False,managed_money,8410,9611,10892,17950,8560,9783,11087,18271,2024-01-13
3,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,6E,202403,False,managed_money,20178,23060,32868,37971,11784,13467,19195,22175,2024-01-13
4,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,6J,202403,False,managed_money,2387,2728,4356,5452,13879,15862,25327,31700,2024-01-13
5,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,6M,202403,False,managed_money,31223,35684,52621,54963,0,0,0,0,2024-01-13
6,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,6N,202403,False,managed_money,5444,6221,6221,9675,2685,3068,3068,4772,2024-01-13
7,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,6S,202403,False,managed_money,2659,3039,3039,6002,0,0,0,0,2024-01-13
8,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,AHD,NaN,None,managed_money,4979,5690,12567,10719,21856,24979,55164,47053,2024-01-13
9,2024-01-13 07:00:00.000,2024-01-12 00:00:00.000,BRN,202403,False,managed_money,19498,22284,22284,43491,23230,26549,26549,51816,2024-01-13

In [ ]:
df =  Unifier.get_dataframe(name="xtech_futures_flow_forecasts_positions", key="JOBY", back_to='2025-11-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_at,okey_ts,okey_tk,okey_yr,okey_mn,okey_dy,...,svolm10,sopxm10,sdivm10,serrm10,pnlm10,pnlm10err,multihedge,timestamp_cst,securityid,asof_date
0,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 15:36:36.466,JOBY,EQT,NMS,JOBY,2026,2,20,...,0.772385,1.385890,-0.012965,None,-0.023672,None,None,2026-01-09 09:36:36.466228,6648092,2026-01-09
1,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 15:36:43.530,JOBY,EQT,NMS,JOBY,2026,2,20,...,0.772296,1.787340,-0.013060,None,0.007659,None,None,2026-01-09 09:36:43.530374,6648092,2026-01-09
2,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 15:36:43.695,JOBY,EQT,NMS,JOBY,2026,1,16,...,0.779971,0.185827,0.021943,None,0.008769,None,None,2026-01-09 09:36:43.694658,6648092,2026-01-09
3,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 15:36:46.159,JOBY,EQT,NMS,JOBY,2026,2,20,...,0.779940,1.018920,-0.013060,None,0.011324,None,None,2026-01-09 09:36:46.158900,6648092,2026-01-09
4,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:13.733,JOBY,EQT,NMS,JOBY,2026,7,17,...,0.823930,2.459430,0.008123,None,0.091538,None,None,2026-01-09 11:44:13.732576,6648092,2026-01-09
5,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:14.434,JOBY,EQT,NMS,JOBY,2026,1,9,...,1.343260,5.325000,0.000000,None,-0.261035,None,None,2026-01-09 11:44:14.433511,6648092,2026-01-09
6,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:16.843,JOBY,EQT,NMS,JOBY,2026,2,20,...,0.802298,1.276780,-0.010508,None,0.008894,None,None,2026-01-09 11:44:16.842993,6648092,2026-01-09
7,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:16.963,JOBY,EQT,NMS,JOBY,2026,7,17,...,0.818642,1.475850,0.008123,None,-0.031432,None,None,2026-01-09 11:44:16.963467,6648092,2026-01-09
8,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:20.457,JOBY,EQT,NMS,JOBY,2026,7,17,...,0.823927,2.460140,0.007930,None,0.096831,None,None,2026-01-09 11:44:20.457210,6648092,2026-01-09
9,2026-01-09,2026-01-09 23:30:00.000,2026-01-09 17:44:24.367,JOBY,EQT,NMS,JOBY,2026,1,9,...,1.343260,5.325000,0.000000,None,-0.251740,None,None,2026-01-09 11:44:24.367138,6648092,2026-01-09