In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_equity_flow_r3k_1min_trial", asof_date='2024-01-18', limit=10)
display(df)

Unifier query error: ErrorCode: 400
Short Description: Unexpected system error
Technical Instructions:
If contacting your internal technical support team, provide the following details:
- ErrorCode: 400
- Error Message: Retry the operation to see if the error resolves itself. Check your internet connection and system status.

Firewall Configuration:
The following endpoints and ports must be allowed in your firewall:
- Endpoint: https://unifier.exponential-tech.ai
- Ports: 80 (HTTP), 443 (HTTPS)
- Protocol: TCP

For direct support, contact support@exponential-tech.ai.

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date range using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_1min_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RYTM,US76243J1051,171,2.710691e+05,72919.16,194979.50,...,28,1585.20,266313.46,1,170,0.00,3170.40,0,2,2024-01-31
1,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SAFT,US78648T1007,121,4.248283e+05,203636.72,221191.61,...,36,0.00,424828.33,0,121,0.00,0.00,0,0,2024-01-31
2,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SCPH,US8106481059,64,2.166084e+04,9138.16,12184.22,...,9,676.90,20645.48,2,62,0.00,338.45,0,1,2024-01-31
3,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SFBS,US81768T1088,244,6.275718e+05,365226.20,262345.58,...,61,622427.74,5144.03,242,2,0.00,0.00,0,0,2024-01-31
4,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SFIX,US8608971078,160,9.331935e+04,67364.91,24787.95,...,15,45784.81,46368.05,2,1,1166.49,0.00,2,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,BMY,US1101221083,1496,1.342233e+07,3840079.77,9340007.10,...,213,26916.45,13153170.42,19,1477,143554.38,98693.64,16,11,2024-01-31
96,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,BOKF,US05561Q2012,240,1.156955e+06,583297.91,564015.33,...,44,949666.85,197646.40,197,43,0.00,9641.29,0,2,2024-01-31
97,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,BSVN,US06652N1072,7,1.159620e+03,165.66,993.96,...,1,165.66,993.96,1,6,0.00,0.00,0,0,2024-01-31
98,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,BTMD,US0906831039,3,7.866000e+02,393.30,393.30,...,0,393.30,393.30,0,0,0.00,0.00,0,0,2024-01-31
99,2024-01-31,2024-01-31 15:59:00.000,2024-01-31 15:59:03.000,0,BTU,US7045511000,401,1.206469e+06,520496.78,685972.63,...,58,42121.13,1164348.29,14,387,0.00,0.00,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_1min_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2013-05-13,2013-05-13 05:53:00.000,2013-05-13 05:53:03.000,1,AAPL,US0378331005,1,4.507000e+04,0.00,45070.00,...,1,0.00,45070.00,0,1,0.00,0.00,0,0,2013-05-13
1,2013-05-13,2013-05-13 06:06:00.000,2013-05-13 06:06:03.000,1,AAPL,US0378331005,2,1.125175e+05,0.00,112517.50,...,1,0.00,112517.50,0,2,0.00,0.00,0,0,2013-05-13
2,2013-05-13,2013-05-13 06:10:00.000,2013-05-13 06:10:03.000,1,AAPL,US0378331005,2,1.350230e+05,0.00,135023.00,...,1,0.00,135023.00,0,2,0.00,0.00,0,0,2013-05-13
3,2013-05-13,2013-05-13 06:47:00.000,2013-05-13 06:47:03.000,1,AAPL,US0378331005,1,4.498000e+04,0.00,44980.00,...,1,0.00,44980.00,0,1,0.00,0.00,0,0,2013-05-13
4,2013-05-13,2013-05-13 07:19:00.000,2013-05-13 07:19:03.000,1,AAPL,US0378331005,1,3.654406e+05,0.00,365440.60,...,0,365440.60,0.00,1,0,0.00,0.00,0,0,2013-05-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2013-05-13,2013-05-13 09:30:00.000,2013-05-13 09:30:03.000,1,AAPL,US0378331005,311,8.047512e+07,27687580.75,48129813.28,...,120,15266983.78,60550410.25,75,236,4140198.99,517524.87,16,2,2013-05-13
96,2013-05-13,2013-05-13 09:31:00.000,2013-05-13 09:31:03.000,0,AAPL,US0378331005,874,5.679746e+07,26514148.13,25279420.64,...,273,21965152.12,29828416.64,392,482,3509225.49,1494670.12,54,23,2013-05-13
97,2013-05-13,2013-05-13 09:33:00.000,2013-05-13 09:33:03.000,0,AAPL,US0378331005,904,6.762139e+07,39346074.32,22889541.34,...,251,55727804.89,6507810.77,798,106,3964528.40,1421246.03,53,19,2013-05-13
98,2013-05-13,2013-05-13 09:32:00.000,2013-05-13 09:32:03.000,0,AAPL,US0378331005,694,4.645831e+07,19346472.19,24032468.92,...,181,5288482.02,38090459.09,111,583,2142169.93,937199.34,32,14,2013-05-13
99,2013-05-13,2013-05-13 09:37:00.000,2013-05-13 09:37:03.000,0,AAPL,US0378331005,862,5.976030e+07,29464185.54,22184798.52,...,265,46449421.91,5199562.15,743,119,5060907.16,3050409.80,73,44,2013-05-13

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_1min_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-30,2024-01-30 16:02:00.000,2024-01-30 16:02:03.000,1,AAPL,US0378331005,182,1.302233e+06,801374.40,493703.87,...,59,1280768.02,14310.26,179,3,0.00,7155.13,0,1,2024-01-30
1,2024-01-30,2024-01-30 16:03:00.000,2024-01-30 16:03:03.000,1,AAPL,US0378331005,150,1.883064e+06,602580.58,1280483.74,...,33,1054516.02,828548.30,84,66,0.00,0.00,0,0,2024-01-30
2,2024-01-30,2024-01-30 16:04:00.000,2024-01-30 16:04:03.000,1,AAPL,US0378331005,296,3.322423e+06,1391825.76,1930597.02,...,101,11224.40,3311198.37,1,295,0.00,0.00,0,0,2024-01-30
3,2024-01-30,2024-01-30 16:08:00.000,2024-01-30 16:08:03.000,1,AAPL,US0378331005,73,1.344651e+06,792054.78,552596.36,...,26,18419.88,1326231.26,1,72,0.00,0.00,0,0,2024-01-30
4,2024-01-30,2024-01-30 16:09:00.000,2024-01-30 16:09:03.000,1,AAPL,US0378331005,120,3.491613e+06,2647806.77,843806.55,...,33,2618709.99,872903.33,90,30,0.00,0.00,0,0,2024-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-30,2024-01-30 17:27:00.000,2024-01-30 17:27:03.000,1,AAPL,US0378331005,33,6.426893e+04,40898.41,23370.52,...,11,0.00,64268.94,0,33,0.00,0.00,0,0,2024-01-30
96,2024-01-30,2024-01-30 17:28:00.000,2024-01-30 17:28:03.000,1,AAPL,US0378331005,78,1.168893e+06,674361.49,479545.95,...,24,14985.81,1138921.63,1,77,0.00,14985.81,0,1,2024-01-30
97,2024-01-30,2024-01-30 17:29:00.000,2024-01-30 17:29:03.000,1,AAPL,US0378331005,32,3.325782e+04,12471.68,18707.52,...,10,0.00,31179.20,0,32,1039.31,1039.31,1,1,2024-01-30
98,2024-01-30,2024-01-30 17:40:00.000,2024-01-30 17:40:03.000,1,AAPL,US0378331005,38,4.642937e+05,207710.33,256583.35,...,11,48873.02,415420.67,4,34,0.00,0.00,0,0,2024-01-30
99,2024-01-30,2024-01-30 17:41:00.000,2024-01-30 17:41:03.000,1,AAPL,US0378331005,37,1.260479e+05,88574.17,37473.69,...,13,0.00,126047.86,0,37,0.00,0.00,0,0,2024-01-30

## Download data file for a specific date using asof_date

In [6]:
Unifier.replicate(name="xtech_us_equity_flow_r3k_1min_trial", target_location="./data", asof_date='2007-01-03')

Starting native python replication for xtech_us_equity_flow_r3k_1min_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_flow_r3k_1min_trial. Downloaded 1 files.