In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-16,2007-03-16 06:03:00.000,2007-03-16 06:03:03.000,1,DOW,US2605431038,1,4600,2300.0,2300.0,...,1,2300.0,2300.0,0,0,0,0,0,0,2007-03-16
1,2007-03-16,2007-03-16 06:48:00.000,2007-03-16 06:48:03.000,1,MER,US5901881087,1,8016,4008.0,4008.0,...,1,0.0,8016.0,0,1,0,0,0,0,2007-03-16
2,2007-03-16,2007-03-16 06:53:00.000,2007-03-16 06:53:03.000,1,JNJ,US4781601046,1,6061,3030.5,3030.5,...,1,3030.5,3030.5,0,0,0,0,0,0,2007-03-16
3,2007-03-16,2007-03-16 06:53:00.000,2007-03-16 06:53:03.000,1,MCO,US6153691059,1,6366,3183.0,3183.0,...,1,0.0,6366.0,0,1,0,0,0,0,2007-03-16
4,2007-03-16,2007-03-16 06:55:00.000,2007-03-16 06:55:03.000,1,TAP,US60871R2094,1,8793,4396.5,4396.5,...,1,4396.5,4396.5,0,0,0,0,0,0,2007-03-16
5,2007-03-16,2007-03-16 07:04:00.000,2007-03-16 07:04:03.000,1,BRL,US0683061099,1,4749,2374.5,2374.5,...,1,0.0,4749.0,0,1,0,0,0,0,2007-03-16
6,2007-03-16,2007-03-16 07:04:00.000,2007-03-16 07:04:03.000,1,SGP,US8066051017,2,9264,2316.0,6948.0,...,1,0.0,9264.0,0,2,0,0,0,0,2007-03-16
7,2007-03-16,2007-03-16 07:07:00.000,2007-03-16 07:07:03.000,1,SGP,US8066051017,1,4632,0.0,4632.0,...,0,0.0,4632.0,0,1,0,0,0,0,2007-03-16
8,2007-03-16,2007-03-16 07:08:00.000,2007-03-16 07:08:03.000,1,HOG,US4128221086,1,6107,3053.5,3053.5,...,1,0.0,6107.0,0,1,0,0,0,0,2007-03-16
9,2007-03-16,2007-03-16 07:13:00.000,2007-03-16 07:13:03.000,1,LEND,US00437P1075,2,4420,3315.0,1105.0,...,1,4420.0,0.0,2,0,0,0,0,0,2007-03-16

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AADI,US00032Q1040,1,40.7100,20.36,20.36,...,1,40.71,0.00,1,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,US0378331005,163,891117.1800,563098.59,328018.59,...,44,541230.68,349886.50,99,64,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,US00287Y1091,4,4122.7000,3607.36,515.34,...,2,2061.35,2061.35,2,2,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABNB,US0090661010,10,23302.4700,19807.10,3495.37,...,5,16311.73,6990.74,6,2,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABT,US0028241000,1,1134.1000,567.05,567.05,...,1,1134.10,0.00,1,0,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FLNG,BMG359472021,1,1519.5000,759.75,759.75,...,1,0.00,1519.50,0,1,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FMC,US3024913036,1,114.9800,57.49,57.49,...,1,57.49,57.49,0,0,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FSR,US33813J1060,29,4471.2685,3469.09,1002.18,...,14,2775.27,1696.00,18,11,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FTI,GB00BDSFG982,2,183.6000,45.90,137.70,...,1,0.00,183.60,0,2,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,GDDY,US3802371076,2,11881.0000,5940.50,5940.50,...,1,0.00,11881.00,0,2,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-13,2007-03-13 07:18:00.000,2007-03-13 07:18:03.000,1,AAPL,US0378331005,4,6.289100e+04,55029.62,7861.38,...,2,62891.00,0.00,4,0,0.00,0.00,0,0,2007-03-13
1,2007-03-13,2007-03-13 07:46:00.000,2007-03-13 07:46:03.000,1,AAPL,US0378331005,2,2.688500e+04,0.00,26885.00,...,2,0.00,26885.00,0,2,0.00,0.00,0,0,2007-03-13
2,2007-03-13,2007-03-13 07:49:00.000,2007-03-13 07:49:03.000,1,AAPL,US0378331005,1,8.960000e+03,0.00,8960.00,...,1,0.00,8960.00,0,1,0.00,0.00,0,0,2007-03-13
3,2007-03-13,2007-03-13 07:50:00.000,2007-03-13 07:50:03.000,1,AAPL,US0378331005,3,2.688000e+04,8960.00,17920.00,...,0,8960.00,17920.00,1,2,0.00,0.00,0,0,2007-03-13
4,2007-03-13,2007-03-13 07:51:00.000,2007-03-13 07:51:03.000,1,AAPL,US0378331005,1,8.960000e+03,0.00,8960.00,...,0,0.00,8960.00,0,1,0.00,0.00,0,0,2007-03-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-03-13,2007-03-13 09:52:00.000,2007-03-13 09:52:03.000,0,AAPL,US0378331005,483,9.148165e+06,4789725.14,3812140.64,...,41,4695023.64,3906842.14,272,211,456737.75,89561.00,4,1,2007-03-13
96,2007-03-13,2007-03-13 09:53:00.000,2007-03-13 09:53:03.000,0,AAPL,US0378331005,556,8.903688e+06,4292140.92,3810914.57,...,66,4260113.26,3842942.22,297,259,495993.27,304638.90,9,5,2007-03-13
97,2007-03-13,2007-03-13 09:54:00.000,2007-03-13 09:54:03.000,0,AAPL,US0378331005,426,6.245954e+06,2442833.80,3328243.01,...,52,2413510.07,3357566.74,197,229,474877.04,0.00,7,0,2007-03-13
98,2007-03-13,2007-03-13 09:55:00.000,2007-03-13 09:55:03.000,0,AAPL,US0378331005,778,1.301840e+07,6380066.75,5616362.68,...,115,6672897.00,5323532.43,432,346,555826.93,466139.98,9,5,2007-03-13
99,2007-03-13,2007-03-13 09:56:00.000,2007-03-13 09:56:03.000,0,AAPL,US0378331005,525,7.585115e+06,2303926.27,4725293.75,...,71,2123328.29,4905891.73,160,365,188325.90,367569.39,2,7,2007-03-13

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial',key='AAPL', back_to='2024-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-12,2024-01-12 04:01:00.000,2024-01-12 04:01:03.000,1,AAPL,US0378331005,35,58571.59,24265.37,34306.22,...,10,26775.58,31796.01,15,18,0,0,0,0,2024-01-12
1,2024-01-12,2024-01-12 04:02:00.000,2024-01-12 04:02:03.000,1,AAPL,US0378331005,15,29497.38,0.00,29497.38,...,4,3932.98,25564.40,2,13,0,0,0,0,2024-01-12
2,2024-01-12,2024-01-12 04:03:00.000,2024-01-12 04:03:03.000,1,AAPL,US0378331005,17,77745.55,22866.34,54879.21,...,1,22866.34,54879.21,5,12,0,0,0,0,2024-01-12
3,2024-01-12,2024-01-12 04:04:00.000,2024-01-12 04:04:03.000,1,AAPL,US0378331005,17,18921.55,5565.16,13356.39,...,7,4452.13,14469.42,4,13,0,0,0,0,2024-01-12
4,2024-01-12,2024-01-12 04:05:00.000,2024-01-12 04:05:03.000,1,AAPL,US0378331005,10,10018.14,4007.26,6010.88,...,3,4007.26,6010.88,4,6,0,0,0,0,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-12,2024-01-12 05:38:00.000,2024-01-12 05:38:03.000,1,AAPL,US0378331005,10,3709.78,1112.93,2596.85,...,3,1112.93,2596.85,3,7,0,0,0,0,2024-01-12
96,2024-01-12,2024-01-12 05:39:00.000,2024-01-12 05:39:03.000,1,AAPL,US0378331005,12,26709.13,0.00,26709.13,...,2,2225.76,24483.37,1,11,0,0,0,0,2024-01-12
97,2024-01-12,2024-01-12 05:40:00.000,2024-01-12 05:40:03.000,1,AAPL,US0378331005,5,18731.58,0.00,18731.58,...,2,0.00,18731.58,0,5,0,0,0,0,2024-01-12
98,2024-01-12,2024-01-12 05:41:00.000,2024-01-12 05:41:03.000,1,AAPL,US0378331005,26,131481.98,10114.00,121367.98,...,6,10114.00,121367.98,2,24,0,0,0,0,2024-01-12
99,2024-01-12,2024-01-12 05:42:00.000,2024-01-12 05:42:03.000,1,AAPL,US0378331005,4,1669.03,1251.77,417.26,...,2,417.26,1251.77,1,3,0,0,0,0,2024-01-12

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial", target_location="./data", asof_date='2024-01-17')

Starting native python replication for xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial (parallel)...
Found 1 files to download.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1_trial", target_location="./data")