In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_daily_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-05,2007-02-05 16:01:00.000,2007-02-05 20:00:03.000,1,A,8455,8.004575e+07,3.878823e+07,3.995830e+07,3929,...,1166,3.951294e+07,3.923359e+07,3979,4475,508678.41,790547.15,41,85,2007-02-05
1,2007-02-05,2007-02-05 18:22:00.000,2007-02-05 20:00:03.000,1,AA,18675,2.085751e+08,1.208906e+08,8.410040e+07,10878,...,2116,1.202215e+08,8.476951e+07,10880,7794,1272092.19,2311997.79,73,121,2007-02-05
2,2007-02-05,2007-02-05 16:01:00.000,2007-02-05 20:00:03.000,1,AACC,303,8.393545e+05,3.710924e+05,4.362720e+05,151,...,70,3.520125e+05,4.553519e+05,141,162,15890.38,16099.78,2,4,2007-02-05
3,2007-02-05,2007-02-05 16:01:00.000,2007-02-05 20:00:03.000,1,AAI,3930,1.242787e+07,5.972384e+06,6.087100e+06,1939,...,514,5.971044e+06,6.088439e+06,1939,1991,254041.77,114340.57,28,16,2007-02-05
4,2007-02-05,2007-02-05 16:01:00.000,2007-02-05 20:00:03.000,1,AAON,89,3.425497e+05,1.167135e+05,2.230872e+05,31,...,30,1.307252e+05,2.090755e+05,36,52,0.00,2749.01,0,1,2007-02-05
5,2007-02-05,2007-02-05 16:02:00.000,2007-02-05 20:00:03.000,1,AAP,2547,2.008599e+07,9.715259e+06,1.024314e+07,1172,...,485,9.606529e+06,1.035187e+07,1182,1365,33739.26,93850.59,4,7,2007-02-05
6,2007-02-05,2007-02-05 20:00:00.000,2007-02-05 20:00:03.000,1,AAPL,96779,1.695616e+09,7.890906e+08,7.957218e+08,45981,...,11835,7.879070e+08,7.969054e+08,48809,47970,62459238.27,48344111.24,1347,1047,2007-02-05
7,2007-02-05,2007-02-05 16:05:00.000,2007-02-05 20:00:03.000,1,AATI,1139,1.573223e+06,7.539803e+05,7.465826e+05,576,...,160,7.577979e+05,7.427650e+05,575,564,32802.30,39857.65,11,6,2007-02-05
8,2007-02-05,2007-02-05 16:01:00.000,2007-02-05 20:00:03.000,1,AAWW,535,4.090795e+06,1.866318e+06,2.166313e+06,221,...,139,2.025686e+06,2.006944e+06,234,301,0.00,58164.73,0,3,2007-02-05
9,2007-02-05,2007-02-05 16:01:00.000,2007-02-05 20:00:03.000,1,ABAX,838,2.797893e+06,1.336799e+06,1.349870e+06,394,...,204,1.317759e+06,1.368909e+06,390,448,74414.97,36809.90,5,8,2007-02-05

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_daily_v1_2_1_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-08,2024-01-08 19:01:00.000,2024-01-08 20:00:03.000,1,A,24462,1.632557e+08,1.052314e+08,5.371729e+07,13581,...,5613,1.040284e+08,5.492026e+07,13497,10964,2661418.69,1645589.38,441,306,2024-01-08
1,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AA,46948,1.500690e+08,6.576694e+07,6.618504e+07,22485,...,6999,5.820643e+07,7.374556e+07,22802,24146,9402977.83,8714056.07,924,826,2024-01-08
2,2024-01-08,2024-01-08 19:57:00.000,2024-01-08 20:00:03.000,1,AADI,2508,8.570716e+05,4.046190e+05,3.379180e+05,1308,...,415,4.070869e+05,3.354501e+05,1324,1184,38070.84,76463.72,137,112,2024-01-08
3,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAL,145264,8.455748e+08,3.623520e+08,3.747814e+08,74005,...,23459,3.638610e+08,3.732724e+08,74375,70888,59954048.37,48487279.84,5383,5030,2024-01-08
4,2024-01-08,2024-01-08 19:01:00.000,2024-01-08 20:00:03.000,1,AAN,4054,2.664774e+06,1.174707e+06,1.414832e+06,2079,...,633,1.157302e+06,1.432237e+06,2073,1978,46526.93,28707.89,30,32,2024-01-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-08,2024-01-08 19:56:00.000,2024-01-08 20:00:03.000,1,AKR,8327,2.056472e+07,1.238269e+07,8.048855e+06,4376,...,1036,1.237200e+07,8.059550e+06,4362,3965,92321.45,40851.86,87,56,2024-01-08
96,2024-01-08,2024-01-08 19:27:00.000,2024-01-08 20:00:03.000,1,AKRO,13011,2.169628e+07,9.174492e+06,1.220706e+07,7126,...,2122,8.661140e+06,1.272041e+07,7182,5828,146630.70,168098.61,95,79,2024-01-08
97,2024-01-08,2024-01-08 18:56:00.000,2024-01-08 20:00:03.000,1,AKTS,1346,3.280769e+05,8.201159e+04,1.420046e+05,721,...,347,8.338239e+04,1.406337e+05,744,602,73078.09,30982.65,216,111,2024-01-08
98,2024-01-08,2024-01-08 19:28:00.000,2024-01-08 20:00:03.000,1,AKYA,4803,3.621642e+06,1.879072e+06,1.226661e+06,2810,...,923,1.851844e+06,1.253890e+06,2736,2067,225429.81,290479.02,197,109,2024-01-08
99,2024-01-08,2024-01-08 19:39:00.000,2024-01-08 20:00:03.000,1,AL,9884,2.387698e+07,1.362071e+07,9.738291e+06,4773,...,1752,1.361881e+07,9.740187e+06,4718,5166,374228.76,143757.89,193,78,2024-01-08

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_daily_v1_2_1_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-09,2007-01-09 20:00:00.000,2007-01-09 20:00:03.000,1,AAPL,569528,1.068223e+10,5.235078e+09,4.946351e+09,244117,...,93772,5.245913e+09,4.935516e+09,292982,276546,2.744386e+08,2.263630e+08,6049,4246,2007-01-09
1,2007-01-12,2007-01-12 20:00:00.000,2007-01-12 20:00:03.000,1,AAPL,212665,4.364616e+09,1.982492e+09,2.050683e+09,97201,...,30552,1.980831e+09,2.052344e+09,105120,107545,1.772093e+08,1.542316e+08,3351,3359,2007-01-12
2,2007-02-06,2007-02-06 19:58:00.000,2007-02-06 20:00:03.000,1,AAPL,141501,2.558329e+09,1.196953e+09,1.177160e+09,68630,...,17244,1.194111e+09,1.180001e+09,71438,70063,1.106801e+08,7.353638e+07,1969,1371,2007-02-06
3,2007-01-04,2007-01-04 20:00:00.000,2007-01-04 20:00:03.000,1,AAPL,132141,2.458420e+09,1.149540e+09,1.148633e+09,61844,...,20310,1.157005e+09,1.141168e+09,66842,65299,9.386545e+07,6.638126e+07,2153,1483,2007-01-04
4,2007-01-05,2007-01-05 20:00:00.000,2007-01-05 20:00:03.000,1,AAPL,134289,2.423835e+09,1.164763e+09,1.109271e+09,58631,...,17993,1.159160e+09,1.114873e+09,68882,65407,9.048056e+07,5.932143e+07,2748,1175,2007-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-05-24,2007-05-24 19:59:00.000,2007-05-24 20:00:03.000,1,AAPL,146642,3.494981e+09,1.567287e+09,1.699913e+09,70336,...,25282,1.567035e+09,1.700165e+09,70822,75820,1.308972e+08,9.688360e+07,2019,1582,2007-05-24
96,2007-06-28,2007-06-28 20:00:00.000,2007-06-28 20:00:03.000,1,AAPL,126976,3.653755e+09,1.641372e+09,1.687148e+09,63151,...,22593,1.636534e+09,1.691986e+09,64035,62941,1.672249e+08,1.580102e+08,2499,1887,2007-06-28
97,2007-04-16,2007-04-16 20:00:00.000,2007-04-16 20:00:03.000,1,AAPL,91881,1.880618e+09,9.426996e+08,8.207070e+08,48904,...,9166,9.464835e+08,8.169231e+08,49121,42759,6.042095e+07,5.679048e+07,1220,947,2007-04-16
98,2007-06-20,2007-06-20 20:00:00.000,2007-06-20 20:00:03.000,1,AAPL,142865,3.854771e+09,1.702723e+09,1.825206e+09,68831,...,23718,1.701937e+09,1.825992e+09,69627,73238,1.755249e+08,1.513173e+08,2147,1748,2007-06-20
99,2007-03-06,2007-03-06 20:00:00.000,2007-03-06 20:00:03.000,1,AAPL,129377,2.224355e+09,1.017304e+09,1.080195e+09,60997,...,14141,1.020088e+09,1.077411e+09,63614,65763,7.752688e+07,4.932911e+07,1380,841,2007-03-06

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_daily_v1_2_1_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,990710,1.406572e+10,6.739308e+09,5.706525e+09,562908,...,203637,6.718754e+09,5.727078e+09,558557,432153,8.381063e+08,7.817779e+08,69901,36457,2024-01-02
1,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,547902,7.957503e+09,3.802293e+09,3.215115e+09,331119,...,100340,3.825576e+09,3.191832e+09,330178,217724,5.180600e+08,4.220353e+08,33851,20631,2024-01-10
2,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,675337,1.058505e+10,4.966160e+09,4.240622e+09,390963,...,132526,4.993287e+09,4.213496e+09,389878,285451,7.655776e+08,6.126888e+08,46270,25440,2024-01-05
3,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,527636,8.032383e+09,3.920825e+09,3.412678e+09,313998,...,92767,3.889177e+09,3.444326e+09,312636,214999,3.436649e+08,3.552153e+08,24908,19583,2024-01-26
4,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,776996,1.390008e+10,6.246976e+09,6.053243e+09,438197,...,144853,6.214716e+09,6.085502e+09,438270,338726,8.478937e+08,7.519638e+08,39267,31652,2024-01-18
5,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,704292,1.117920e+10,4.903110e+09,4.848632e+09,407780,...,141705,4.847464e+09,4.904278e+09,404312,299980,8.093261e+08,6.181319e+08,52306,25291,2024-01-04
6,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,635508,9.891279e+09,4.744796e+09,4.130843e+09,372405,...,110062,4.674756e+09,4.200882e+09,371266,264241,5.258774e+08,4.897631e+08,31153,25473,2024-01-25
7,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,646606,9.724189e+09,4.725496e+09,3.810025e+09,374656,...,129159,4.727787e+09,3.807734e+09,374680,271926,5.098485e+08,6.788193e+08,36482,31635,2024-01-03
8,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,587962,9.457487e+09,4.396980e+09,4.025837e+09,348045,...,105630,4.417371e+09,4.005446e+09,348478,239484,4.926221e+08,5.420481e+08,27663,27274,2024-01-24
9,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,754607,1.047012e+10,5.324264e+09,4.027101e+09,436856,...,140374,5.294603e+09,4.056762e+09,436132,318474,5.894122e+08,5.293452e+08,44543,28370,2024-01-16
10,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,672809,1.207373e+10,5.862620e+09,5.141551e+09,388844,...,121439,5.773583e+09,5.230588e+09,390683,282126,5.512614e+08,5.182930e+08,32778,25601,2024-01-19
11,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,470667,6.941078e+09,3.434455e+09,2.791790e+09,288123,...,82988,3.442340e+09,2.783905e+09,286746,183919,4.031384e+08,3.116944e+08,29492,17846,2024-01-12
12,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,589939,7.998797e+09,3.962558e+09,3.250855e+09,364379,...,105210,3.856046e+09,3.357367e+09,362427,227509,4.216349e+08,3.637488e+08,31244,22398,2024-01-29
13,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,530828,7.405986e+09,3.703151e+09,2.830986e+09,317939,...,98430,3.666996e+09,2.867141e+09,316857,213971,4.414514e+08,4.303981e+08,32092,23895,2024-01-09
14,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,573585,8.242853e+09,3.807336e+09,3.516374e+09,330364,...,105517,3.842186e+09,3.481524e+09,329199,244386,5.234246e+08,3.957190e+08,35207,19919,2024-01-11
15,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,659234,1.011811e+10,5.140608e+09,3.874886e+09,411671,...,122228,5.194947e+09,3.820547e+09,410217,249013,6.224780e+08,4.801413e+08,45877,26645,2024-01-08
16,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,527086,7.671505e+09,3.881987e+09,2.852431e+09,319880,...,91847,3.861606e+09,2.872812e+09,319856,207229,4.602497e+08,4.768365e+08,25365,23987,2024-01-23
17,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,682093,9.944367e+09,4.911012e+09,3.772293e+09,387356,...,131699,4.867751e+09,3.815554e+09,384467,297626,6.964564e+08,5.646060e+08,41131,26399,2024-01-30
18,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,708796,1.073480e+10,5.462671e+09,4.016835e+09,422157,...,125197,5.574549e+09,3.904957e+09,422318,286474,6.501838e+08,6.051145e+08,34884,29397,2024-01-22
19,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,673751,9.609475e+09,4.544943e+09,4.074560e+09,382567,...,129057,4.461645e+09,4.157858e+09,380986,292765,5.103516e+08,4.796210e+08,36375,23940,2024-01-31
20,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,585481,8.165045e+09,3.881386e+09,3.334522e+09,342783,...,105856,3.852553e+09,3.363355e+09,340434,245045,5.133696e+08,4.357680e+08,33131,20739,2024-01-17

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_daily_v1_2_1_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for xtech_us_eqt_flow_r3k_daily_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_daily_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_daily_v1_2_1_trial", target_location="./data")