In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_1min_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-28,2007-03-28 06:13:00.000,2007-03-28 06:13:03.000,1,MO,5,170000,153000.0,17000.0,4,...,1,170000.0,0.0,5,0,0,0,0,0,2007-03-28
1,2007-03-28,2007-03-28 06:21:00.000,2007-03-28 06:21:03.000,1,MO,1,8550,4275.0,4275.0,0,...,0,8550.0,0.0,1,0,0,0,0,0,2007-03-28
2,2007-03-28,2007-03-28 06:29:00.000,2007-03-28 06:29:03.000,1,MO,1,8535,0.0,8535.0,0,...,1,0.0,8535.0,0,1,0,0,0,0,2007-03-28
3,2007-03-28,2007-03-28 06:44:00.000,2007-03-28 06:44:03.000,1,RMBS,1,10775,5387.5,5387.5,0,...,1,0.0,10775.0,0,1,0,0,0,0,2007-03-28
4,2007-03-28,2007-03-28 06:48:00.000,2007-03-28 06:48:03.000,1,HUM,1,5965,2982.5,2982.5,0,...,1,2982.5,2982.5,0,0,0,0,0,0,2007-03-28
5,2007-03-28,2007-03-28 06:54:00.000,2007-03-28 06:54:03.000,1,BZH,2,26040,19530.0,6510.0,1,...,1,26040.0,0.0,2,0,0,0,0,0,2007-03-28
6,2007-03-28,2007-03-28 06:56:00.000,2007-03-28 06:56:03.000,1,BZH,4,78075,0.0,78075.0,0,...,1,0.0,78075.0,0,4,0,0,0,0,2007-03-28
7,2007-03-28,2007-03-28 06:57:00.000,2007-03-28 06:57:03.000,1,BZH,2,52000,0.0,52000.0,0,...,0,0.0,52000.0,0,2,0,0,0,0,2007-03-28
8,2007-03-28,2007-03-28 06:58:00.000,2007-03-28 06:58:03.000,1,BZH,5,145626,29125.2,116500.8,1,...,0,29125.2,116500.8,1,4,0,0,0,0,2007-03-28
9,2007-03-28,2007-03-28 07:00:00.000,2007-03-28 07:00:03.000,1,BZH,1,2601,2601.0,0.0,1,...,0,2601.0,0.0,1,0,0,0,0,0,2007-03-28

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_1min_v1_2_1_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AADI,1,40.7100,20.36,20.36,0,...,1,40.71,0.00,1,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,163,891117.1800,563098.59,328018.59,98,...,44,541230.68,349886.50,99,64,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,4,4122.7000,3607.36,515.34,3,...,2,2061.35,2061.35,2,2,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABNB,10,23302.4700,19807.10,3495.37,8,...,5,16311.73,6990.74,6,2,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABT,1,1134.1000,567.05,567.05,0,...,1,1134.10,0.00,1,0,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FLNG,1,1519.5000,759.75,759.75,0,...,1,0.00,1519.50,0,1,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FMC,1,114.9800,57.49,57.49,0,...,1,57.49,57.49,0,0,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FSR,29,4471.2685,3469.09,1002.18,17,...,14,2775.27,1696.00,18,11,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FTI,2,183.6000,45.90,137.70,0,...,1,0.00,183.60,0,2,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,GDDY,2,11881.0000,5940.50,5940.50,0,...,1,0.00,11881.00,0,2,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_1min_v1_2_1_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-29,2007-01-29 07:01:00.000,2007-01-29 07:01:03.000,1,AAPL,2,8.095900e+04,40479.50,40479.50,0,...,1,0.00,80959.00,0,2,0.00,0.00,0,0,2007-01-29
1,2007-01-29,2007-01-29 07:44:00.000,2007-01-29 07:44:03.000,1,AAPL,2,5.114500e+04,0.00,51145.00,0,...,1,0.00,51145.00,0,2,0.00,0.00,0,0,2007-01-29
2,2007-01-29,2007-01-29 07:47:00.000,2007-01-29 07:47:03.000,1,AAPL,2,1.279800e+05,63990.00,63990.00,1,...,0,63990.00,63990.00,1,1,0.00,0.00,0,0,2007-01-29
3,2007-01-29,2007-01-29 07:53:00.000,2007-01-29 07:53:03.000,1,AAPL,2,8.532000e+04,42660.00,42660.00,1,...,0,42660.00,42660.00,1,1,0.00,0.00,0,0,2007-01-29
4,2007-01-29,2007-01-29 07:59:00.000,2007-01-29 07:59:03.000,1,AAPL,26,4.194950e+05,258150.77,161344.23,16,...,2,258150.77,161344.23,16,10,0.00,0.00,0,0,2007-01-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-01-29,2007-01-29 09:30:00.000,2007-01-29 09:30:03.000,1,AAPL,22,2.983433e+05,189854.85,108488.49,14,...,5,189854.85,108488.49,14,8,0.00,0.00,0,0,2007-01-29
96,2007-01-29,2007-01-29 09:31:00.000,2007-01-29 09:31:03.000,0,AAPL,786,3.650586e+07,16102519.33,19752203.43,312,...,213,15870293.76,19984428.99,343,443,60379.93,590755.98,2,4,2007-01-29
97,2007-01-29,2007-01-29 09:32:00.000,2007-01-29 09:32:03.000,0,AAPL,935,1.948108e+07,8277732.57,10274044.96,398,...,244,8173555.65,10378221.88,427,508,723153.28,206153.14,17,4,2007-01-29
98,2007-01-29,2007-01-29 09:33:00.000,2007-01-29 09:33:03.000,0,AAPL,622,1.070401e+07,5803631.68,4516532.85,352,...,128,5820840.69,4499323.84,359,263,357195.21,26646.75,13,2,2007-01-29
99,2007-01-29,2007-01-29 09:34:00.000,2007-01-29 09:34:03.000,0,AAPL,787,1.280236e+07,6358335.80,5899979.48,354,...,177,6252598.40,6005716.88,412,375,449525.81,94517.54,9,3,2007-01-29

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_1min_v1_2_1_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,163,891117.18,563098.59,328018.59,98,...,44,541230.68,349886.50,99,64,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:02:00.000,2024-01-31 04:02:03.000,1,AAPL,73,1780030.24,877823.13,902207.11,36,...,18,902207.11,877823.13,37,36,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:03:00.000,2024-01-31 04:03:03.000,1,AAPL,78,549742.82,422879.09,126863.73,60,...,13,415831.11,133911.71,59,19,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:04:00.000,2024-01-31 04:04:03.000,1,AAPL,17,112694.17,39774.41,72919.76,6,...,10,39774.41,72919.76,6,11,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:05:00.000,2024-01-31 04:05:03.000,1,AAPL,27,250688.37,194979.84,55708.53,21,...,5,167125.58,83562.79,18,9,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 05:36:00.000,2024-01-31 05:36:03.000,1,AAPL,8,28966.78,10862.54,18104.24,3,...,3,3620.85,25345.93,1,7,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 05:37:00.000,2024-01-31 05:37:03.000,1,AAPL,1,934.40,934.40,0.00,1,...,0,934.40,0.00,1,0,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 05:38:00.000,2024-01-31 05:38:03.000,1,AAPL,9,12521.72,11130.42,1391.30,8,...,2,9739.12,2782.60,7,2,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 05:39:00.000,2024-01-31 05:39:03.000,1,AAPL,18,36436.99,2024.28,34412.71,1,...,3,4048.55,32388.44,2,16,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 05:40:00.000,2024-01-31 05:40:03.000,1,AAPL,17,10462.59,2461.79,8000.80,4,...,6,4308.13,6154.46,7,10,0,0,0,0,2024-01-31

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_1min_v1_2_1_trial", target_location="./data", asof_date='2007-01-03')

Starting native python replication for xtech_us_eqt_flow_r3k_1min_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_1min_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_1min_v1_2_1_trial", target_location="./data")