In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_equity_flow_r3k_1min_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-23,2007-03-23 04:16:00.000,2007-03-23 04:16:03.000,1,PXR,2,25170,18877.5,6292.5,1,...,1,25170,0,2,0,0,0,0,0,2007-03-23
1,2007-03-23,2007-03-23 05:10:00.000,2007-03-23 05:10:03.000,1,AMGN,1,5820,2910.0,2910.0,0,...,1,5820,0,1,0,0,0,0,0,2007-03-23
2,2007-03-23,2007-03-23 05:51:00.000,2007-03-23 05:51:03.000,1,AMGN,1,5815,5815.0,0.0,1,...,1,5815,0,1,0,0,0,0,0,2007-03-23
3,2007-03-23,2007-03-23 06:06:00.000,2007-03-23 06:06:03.000,1,IMCL,2,15328,11496.0,3832.0,1,...,1,15328,0,2,0,0,0,0,0,2007-03-23
4,2007-03-23,2007-03-23 06:17:00.000,2007-03-23 06:17:03.000,1,XTO,1,5436,2718.0,2718.0,0,...,1,5436,0,1,0,0,0,0,0,2007-03-23
5,2007-03-23,2007-03-23 06:20:00.000,2007-03-23 06:20:03.000,1,AMGN,1,58150,0.0,58150.0,0,...,0,0,58150,0,1,0,0,0,0,2007-03-23
6,2007-03-23,2007-03-23 06:23:00.000,2007-03-23 06:23:03.000,1,AMGN,4,116000,0.0,116000.0,0,...,1,87000,29000,2,0,0,0,0,0,2007-03-23
7,2007-03-23,2007-03-23 06:34:00.000,2007-03-23 06:34:03.000,1,FTO,2,33100,16550.0,16550.0,0,...,1,16550,16550,0,0,0,0,0,0,2007-03-23
8,2007-03-23,2007-03-23 06:34:00.000,2007-03-23 06:34:03.000,1,VLO,2,62900,31450.0,31450.0,0,...,1,0,62900,0,2,0,0,0,0,2007-03-23
9,2007-03-23,2007-03-23 06:37:00.000,2007-03-23 06:37:03.000,1,HAL,1,3080,1540.0,1540.0,0,...,1,0,3080,0,1,0,0,0,0,2007-03-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_1min_v1_2_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AADI,1,40.7100,20.36,20.36,0,...,1,20.36,20.36,0,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,163,891117.1800,563098.59,328018.59,98,...,44,194077.67,697039.51,35,127,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,4,4122.7000,3607.36,515.34,3,...,2,1030.68,3092.02,0,2,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABNB,10,23302.4700,19807.10,3495.37,8,...,5,8155.86,15146.61,0,3,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABT,1,1134.1000,567.05,567.05,0,...,1,1134.10,0.00,1,0,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FLNG,1,1519.5000,759.75,759.75,0,...,1,0.00,1519.50,0,1,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FMC,1,114.9800,57.49,57.49,0,...,1,57.49,57.49,0,0,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FSR,29,4471.2685,3469.09,1002.18,17,...,14,2158.54,2312.73,0,1,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,FTI,2,183.6000,45.90,137.70,0,...,1,0.00,183.60,0,2,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,GDDY,2,11881.0000,5940.50,5940.50,0,...,1,0.00,11881.00,0,2,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_1min_v1_2_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-19,2007-01-19 04:25:00.000,2007-01-19 04:25:03.000,1,AAPL,1,8897.00,4448.50,4448.50,0,...,1,0.0,8897.00,0,1,0,0,0,0,2007-01-19
1,2007-01-19,2007-01-19 04:36:00.000,2007-01-19 04:36:03.000,1,AAPL,1,8897.00,0.00,8897.00,0,...,0,0.0,8897.00,0,1,0,0,0,0,2007-01-19
2,2007-01-19,2007-01-19 04:53:00.000,2007-01-19 04:53:03.000,1,AAPL,1,26727.00,26727.00,0.00,1,...,0,26727.0,0.00,1,0,0,0,0,0,2007-01-19
3,2007-01-19,2007-01-19 07:06:00.000,2007-01-19 07:06:03.000,1,AAPL,2,88730.00,0.00,88730.00,0,...,1,0.0,88730.00,0,2,0,0,0,0,2007-01-19
4,2007-01-19,2007-01-19 07:10:00.000,2007-01-19 07:10:03.000,1,AAPL,1,8890.00,8890.00,0.00,1,...,0,0.0,8890.00,0,1,0,0,0,0,2007-01-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-01-19,2007-01-19 09:04:00.000,2007-01-19 09:04:03.000,1,AAPL,3,35496.00,23664.00,11832.00,2,...,1,0.0,35496.00,0,3,0,0,0,0,2007-01-19
96,2007-01-19,2007-01-19 09:05:00.000,2007-01-19 09:05:03.000,1,AAPL,7,114098.50,48899.36,65199.14,3,...,3,0.0,114098.50,0,7,0,0,0,0,2007-01-19
97,2007-01-19,2007-01-19 09:06:00.000,2007-01-19 09:06:03.000,1,AAPL,25,296956.00,130660.64,166295.36,5,...,8,0.0,296956.00,0,25,0,0,0,0,2007-01-19
98,2007-01-19,2007-01-19 09:07:00.000,2007-01-19 09:07:03.000,1,AAPL,7,207189.05,73996.09,133192.96,2,...,1,0.0,207189.05,0,7,0,0,0,0,2007-01-19
99,2007-01-19,2007-01-19 09:08:00.000,2007-01-19 09:08:03.000,1,AAPL,2,17736.00,17736.00,0.00,2,...,0,0.0,17736.00,0,2,0,0,0,0,2007-01-19

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_1min_v1_2_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-09,2024-01-09 04:01:00.000,2024-01-09 04:01:03.000,1,AAPL,106,319481.06,293862.30,25618.76,97,...,22,262215.59,57265.47,82,14,0,0,0,0,2024-01-09
1,2024-01-09,2024-01-09 04:02:00.000,2024-01-09 04:02:03.000,1,AAPL,57,286042.72,245896.37,40146.35,49,...,9,270987.84,15054.88,54,3,0,0,0,0,2024-01-09
2,2024-01-09,2024-01-09 04:03:00.000,2024-01-09 04:03:03.000,1,AAPL,47,238281.35,136885.03,101396.32,27,...,6,228141.72,10139.63,45,2,0,0,0,0,2024-01-09
3,2024-01-09,2024-01-09 04:04:00.000,2024-01-09 04:04:03.000,1,AAPL,56,461320.85,354228.51,107092.34,43,...,10,461320.85,0.00,56,0,0,0,0,0,2024-01-09
4,2024-01-09,2024-01-09 04:05:00.000,2024-01-09 04:05:03.000,1,AAPL,17,67542.33,27811.55,39730.78,7,...,5,67542.33,0.00,17,0,0,0,0,0,2024-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-09,2024-01-09 05:36:00.000,2024-01-09 05:36:03.000,1,AAPL,14,19984.58,5709.88,14274.70,4,...,3,19984.58,0.00,14,0,0,0,0,0,2024-01-09
96,2024-01-09,2024-01-09 05:37:00.000,2024-01-09 05:37:03.000,1,AAPL,3,740.14,246.71,493.43,1,...,0,740.14,0.00,3,0,0,0,0,0,2024-01-09
97,2024-01-09,2024-01-09 05:38:00.000,2024-01-09 05:38:03.000,1,AAPL,12,90324.36,52689.21,37635.15,7,...,5,90324.36,0.00,12,0,0,0,0,0,2024-01-09
98,2024-01-09,2024-01-09 05:39:00.000,2024-01-09 05:39:03.000,1,AAPL,2,3146.38,3146.38,0.00,2,...,0,3146.38,0.00,2,0,0,0,0,0,2024-01-09
99,2024-01-09,2024-01-09 05:40:00.000,2024-01-09 05:40:03.000,1,AAPL,7,8143.81,6980.41,1163.40,6,...,2,8143.81,0.00,7,0,0,0,0,0,2024-01-09

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_equity_flow_r3k_1min_v1_2_trial", target_location="./data", asof_date='2007-01-03')

Starting native python replication for xtech_us_equity_flow_r3k_1min_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_flow_r3k_1min_v1_2_trial. Downloaded 1 files.