In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [2]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.17)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: boto3 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (1.42.30)
Requirement already satisfied: botocore<1.43.0,>=1.42.30 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (1.42.31)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from botocore<1.43.0,>=1.42.30->boto3->unifier) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from botocore<1.43.0,>=1.42.30->boto3->unifier) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.30->boto3->unifier) (1.17.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.0.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_equity_flow_r3k_daily_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-08,2007-03-08 16:10:00.000,2007-03-08 20:00:03.000,1,A,13228,1.189052e+08,5.507442e+07,6.299992e+07,5379,...,1955,5.844607e+07,5.962828e+07,860,999,274458.02,556436.81,34,52,2007-03-08
1,2007-03-08,2007-03-08 19:38:00.000,2007-03-08 20:00:03.000,1,AA,25841,2.315046e+08,1.181442e+08,1.115522e+08,10280,...,2526,1.160249e+08,1.136716e+08,1582,1312,924722.71,883378.78,102,87,2007-03-08
2,2007-03-08,2007-03-08 16:22:00.000,2007-03-08 20:00:03.000,1,AACC,609,1.460940e+06,5.785773e+05,8.154469e+05,223,...,150,6.652646e+05,7.287596e+05,47,61,61817.60,5097.78,5,2,2007-03-08
3,2007-03-08,2007-03-08 16:01:00.000,2007-03-08 20:00:03.000,1,AAI,6840,1.879185e+07,9.859596e+06,8.735033e+06,3538,...,555,1.608501e+07,2.509615e+06,5615,637,126152.81,71071.44,44,20,2007-03-08
4,2007-03-08,2007-03-08 16:16:00.000,2007-03-08 20:00:03.000,1,AAON,181,5.829819e+05,1.778632e+05,3.792589e+05,57,...,58,1.881966e+05,3.689255e+05,25,78,11582.29,14277.45,3,5,2007-03-08
5,2007-03-08,2007-03-08 16:03:00.000,2007-03-08 20:00:03.000,1,AAP,3310,3.299883e+07,1.772358e+07,1.507822e+07,1691,...,629,1.649394e+07,1.630785e+07,287,274,59555.63,137482.52,7,11,2007-03-08
6,2007-03-08,2007-03-08 19:59:00.000,2007-03-08 20:00:03.000,1,AAPL,87342,1.599326e+09,7.528443e+08,8.105660e+08,40937,...,10573,7.442825e+08,8.191278e+08,26859,30675,21407822.04,14507628.19,1179,787,2007-03-08
7,2007-03-08,2007-03-08 16:01:00.000,2007-03-08 20:00:03.000,1,AATI,1571,1.836960e+06,8.661705e+05,9.293500e+05,665,...,223,8.938847e+05,9.016358e+05,86,115,28270.99,13168.40,15,11,2007-03-08
8,2007-03-08,2007-03-08 16:01:00.000,2007-03-08 20:00:03.000,1,AAWW,3044,3.322927e+07,1.947637e+07,1.364330e+07,1625,...,630,1.810070e+07,1.501897e+07,1540,1504,52928.00,56665.14,5,7,2007-03-08
9,2007-03-08,2007-03-08 16:01:00.000,2007-03-08 20:00:03.000,1,ABAX,791,2.769739e+06,1.537418e+06,1.198558e+06,417,...,204,1.376958e+06,1.359018e+06,71,60,23287.10,10475.92,6,4,2007-03-08

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_daily_v1_2_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-09,2024-01-09 19:01:00.000,2024-01-09 20:00:03.000,1,A,26210,1.803748e+08,9.441029e+07,8.177886e+07,12504,...,6499,4.808760e+07,1.281015e+08,9191,17019,1748618.26,2437023.21,325,379,2024-01-09
1,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AA,47941,1.780283e+08,8.377741e+07,8.849630e+07,22190,...,6843,5.550603e+07,1.167677e+08,17679,30238,3292198.10,2462396.38,903,705,2024-01-09
2,2024-01-09,2024-01-09 18:57:00.000,2024-01-09 20:00:03.000,1,AADI,3097,1.056914e+06,3.944167e+05,6.069301e+05,981,...,509,4.893865e+05,5.119603e+05,66,105,34850.89,20715.84,81,39,2024-01-09
3,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAL,88531,4.981809e+08,2.289374e+08,2.366943e+08,34902,...,12662,2.324871e+08,2.331446e+08,778,775,16872450.77,15676708.85,2915,2893,2024-01-09
4,2024-01-09,2024-01-09 19:01:00.000,2024-01-09 20:00:03.000,1,AAN,5299,2.425806e+06,8.732902e+05,1.529035e+06,1840,...,912,8.279431e+05,1.574382e+06,959,2058,5934.22,17545.87,14,30,2024-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-09,2024-01-09 19:01:00.000,2024-01-09 20:00:03.000,1,AKR,31889,9.284668e+07,5.440626e+07,3.648561e+07,17685,...,3895,6.446775e+07,2.642412e+07,20459,11427,1504493.21,450320.92,317,179,2024-01-09
96,2024-01-09,2024-01-09 17:58:00.000,2024-01-09 20:00:03.000,1,AKRO,12383,1.773746e+07,8.616269e+06,8.896557e+06,5614,...,2088,6.797515e+06,1.071531e+07,3716,8667,101342.35,123286.64,75,83,2024-01-09
97,2024-01-09,2024-01-09 17:48:00.000,2024-01-09 20:00:03.000,1,AKTS,565,1.260339e+05,4.591593e+04,6.093055e+04,288,...,162,5.311457e+04,5.373184e+04,19,16,7377.38,11810.07,33,44,2024-01-09
98,2024-01-09,2024-01-09 18:54:00.000,2024-01-09 20:00:03.000,1,AKYA,2068,1.257652e+06,6.811680e+05,5.147972e+05,1118,...,343,1.116985e+06,7.897994e+04,1923,63,21126.86,40559.91,42,66,2024-01-09
99,2024-01-09,2024-01-09 19:01:00.000,2024-01-09 20:00:03.000,1,AL,7692,1.451280e+07,7.471871e+06,6.392836e+06,3445,...,1443,1.010839e+07,3.756322e+06,5294,2398,402537.22,245554.26,246,159,2024-01-09

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_daily_v1_2_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-08,2007-02-08 20:00:00.000,2007-02-08 20:00:03.000,1,AAPL,112598,2.032911e+09,9.969550e+08,9.863288e+08,52970,...,15532,1.010496e+09,9.727882e+08,57111,55476,28308223.18,21319423.81,1565,1177,2007-02-08
1,2007-03-19,2007-03-19 20:00:00.000,2007-03-19 20:00:03.000,1,AAPL,121243,2.286806e+09,1.198190e+09,1.038447e+09,64434,...,12661,1.716606e+09,5.200302e+08,93911,27331,30161917.38,20007420.35,1563,1040,2007-03-19
2,2007-01-11,2007-01-11 20:00:00.000,2007-01-11 20:00:03.000,1,AAPL,231957,4.861693e+09,2.323565e+09,2.408443e+09,106226,...,32571,2.103386e+09,2.628622e+09,101463,130149,67452135.59,62232804.83,3154,2943,2007-01-11
3,2007-01-03,2007-01-03 20:00:00.000,2007-01-03 20:00:03.000,1,AAPL,186192,3.664161e+09,1.732849e+09,1.824200e+09,84897,...,29704,1.684214e+09,1.872835e+09,82011,104150,64355165.14,42757224.74,3308,2179,2007-01-03
4,2007-02-28,2007-02-28 20:00:00.000,2007-02-28 20:00:03.000,1,AAPL,157713,2.757976e+09,1.353766e+09,1.344589e+09,73485,...,23534,1.384258e+09,1.314098e+09,80750,76961,38780151.99,20840095.57,2118,1154,2007-02-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-06-26,2007-06-26 20:00:00.000,2007-06-26 20:00:03.000,1,AAPL,227189,5.594831e+09,2.681404e+09,2.802627e+09,108082,...,39625,2.139526e+09,3.344504e+09,88327,138860,67627401.25,43173221.92,2697,1756,2007-06-26
96,2007-05-25,2007-05-25 19:55:00.000,2007-05-25 20:00:03.000,1,AAPL,95341,2.473254e+09,1.271585e+09,1.120653e+09,50547,...,15061,2.155203e+09,2.370358e+08,85139,10185,47378400.26,33637107.57,1796,1294,2007-05-25
97,2007-05-10,2007-05-10 20:00:00.000,2007-05-10 20:00:03.000,1,AAPL,182976,4.505032e+09,2.253258e+09,2.175238e+09,91927,...,31956,2.997160e+09,1.431336e+09,120677,57291,49304041.60,27230881.33,1960,1092,2007-05-10
98,2007-07-10,2007-07-10 20:00:00.000,2007-07-10 20:00:03.000,1,AAPL,199499,5.747954e+09,2.779759e+09,2.831026e+09,97470,...,36510,2.485394e+09,3.125392e+09,89593,109894,72007107.40,65161186.00,2475,2178,2007-07-10
99,2007-05-14,2007-05-14 19:54:00.000,2007-05-14 20:00:03.000,1,AAPL,100016,2.464979e+09,1.191367e+09,1.214805e+09,49398,...,14930,1.047325e+09,1.358847e+09,41578,58438,35474623.21,23332322.59,1415,951,2007-05-14

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_r3k_daily_v1_2_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,672874,1.247752e+10,6.400096e+09,5.082925e+09,417858,...,121471,7.644141e+09,3.838881e+09,532463,140411,5.415680e+08,4.529306e+08,32810,25615,2024-01-19
1,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,527096,7.690177e+09,4.095794e+09,2.835907e+09,327963,...,91853,4.247200e+09,2.684500e+09,294083,229944,3.875323e+08,3.709440e+08,25365,23987,2024-01-23
2,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,990770,1.412446e+10,6.623133e+09,6.059657e+09,542285,...,203661,5.313069e+09,7.369722e+09,246489,744247,9.361314e+08,5.055404e+08,69922,36466,2024-01-02
3,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,682124,9.997138e+09,5.243468e+09,3.764531e+09,398518,...,131716,4.989186e+09,4.018813e+09,331875,350249,5.983342e+08,3.908052e+08,41139,26414,2024-01-30
4,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,708837,1.076401e+10,5.608460e+09,4.200627e+09,424080,...,125211,4.332346e+09,5.476742e+09,387027,321791,5.172395e+08,4.376786e+08,34889,29419,2024-01-22
5,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,754695,1.064378e+10,5.534916e+09,4.143439e+09,447716,...,140422,6.128546e+09,3.549808e+09,468751,285943,5.864017e+08,3.790271e+08,44587,28380,2024-01-16
6,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,527653,8.164333e+09,3.866420e+09,3.615050e+09,311708,...,92776,4.173273e+09,3.308197e+09,306436,220072,3.827252e+08,3.001382e+08,24914,19586,2024-01-26
7,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,573593,8.499696e+09,4.130628e+09,3.580027e+09,335537,...,105521,4.536398e+09,3.174257e+09,254275,319317,4.970836e+08,2.919579e+08,35207,19919,2024-01-11
8,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,587965,9.464530e+09,4.085500e+09,4.528231e+09,329297,...,105631,2.183976e+09,6.429755e+09,217942,370023,4.297140e+08,4.210849e+08,27663,27274,2024-01-24
9,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,704321,1.160613e+10,5.085703e+09,5.255791e+09,410959,...,141719,3.824969e+09,6.516526e+09,285462,418792,8.521401e+08,4.124940e+08,52306,25296,2024-01-04
10,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,673799,9.649775e+09,4.751167e+09,4.091920e+09,399686,...,129080,4.310247e+09,4.532841e+09,419311,254487,4.901400e+08,3.165473e+08,36382,23948,2024-01-31
11,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,675348,1.073244e+10,5.060611e+09,4.557467e+09,394186,...,132532,3.601085e+09,6.016993e+09,349875,324250,7.120352e+08,4.023235e+08,46270,25440,2024-01-05
12,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,777010,1.407412e+10,6.441001e+09,6.411099e+09,444246,...,144863,6.152252e+09,6.699848e+09,461588,313288,6.676443e+08,5.543803e+08,39269,31654,2024-01-18
13,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,646673,9.850288e+09,4.962282e+09,3.895570e+09,384971,...,129184,5.887301e+09,2.970551e+09,337365,309308,5.323861e+08,4.600496e+08,36499,31646,2024-01-03
14,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,470683,6.976981e+09,3.291219e+09,3.002975e+09,281035,...,82997,1.538530e+09,4.755664e+09,141921,326966,4.153750e+08,2.674128e+08,29498,17852,2024-01-12
15,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,547962,8.236493e+09,4.186085e+09,3.235029e+09,347582,...,100367,5.489186e+09,1.931929e+09,394721,153237,4.965947e+08,3.187833e+08,33865,20667,2024-01-10
16,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,659244,1.029335e+10,5.566822e+09,3.684005e+09,432591,...,122232,7.146958e+09,2.103868e+09,426813,231163,6.522098e+08,3.903147e+08,45879,26647,2024-01-08
17,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,585486,8.177438e+09,4.069354e+09,3.347696e+09,350633,...,105859,4.263990e+09,3.153060e+09,301897,283518,4.652283e+08,2.951595e+08,33131,20739,2024-01-17
18,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,635511,9.921383e+09,4.652936e+09,4.391468e+09,364205,...,110064,4.187532e+09,4.856872e+09,305904,329605,4.808354e+08,3.961437e+08,31153,25473,2024-01-25
19,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,590109,8.135219e+09,3.895651e+09,3.483823e+09,360768,...,105286,2.352413e+09,5.027061e+09,218967,369775,4.377972e+08,3.179474e+08,31284,22478,2024-01-29
20,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,530847,7.457587e+09,4.198502e+09,2.517493e+09,348168,...,98441,5.814233e+09,9.017617e+08,453102,77735,4.232342e+08,3.183575e+08,32096,23905,2024-01-09

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_equity_flow_r3k_daily_v1_2_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for xtech_us_equity_flow_r3k_daily_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_flow_r3k_daily_v1_2_trial. Downloaded 1 files.