In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-15,2007-03-15 17:43:00.000,2007-03-15 20:00:03.000,1,A,US00846U1016,8323,6.779714e+07,2.918967e+07,3.829896e+07,...,984,2.924296e+07,3.824566e+07,3592,4731,102145.97,206375.23,8,24,2007-03-15
1,2007-03-15,2007-03-15 16:11:00.000,2007-03-15 20:00:03.000,1,AA,US0138171014,41549,4.459834e+08,2.449838e+08,1.947370e+08,...,4257,2.436123e+08,1.961085e+08,22623,18926,3646053.43,2616506.96,208,145,2007-03-15
2,2007-03-15,2007-03-15 17:06:00.000,2007-03-15 20:00:03.000,1,AACC,US04543P1003,651,2.125328e+06,8.696138e+05,1.220402e+06,...,115,9.356803e+05,1.154336e+06,265,386,12833.95,22477.63,4,4,2007-03-15
3,2007-03-15,2007-03-15 17:06:00.000,2007-03-15 20:00:03.000,1,AAI,US00949P1084,7651,2.336350e+07,1.004328e+07,1.288659e+07,...,641,1.018825e+07,1.274161e+07,3393,4258,300278.03,133361.30,43,23,2007-03-15
4,2007-03-15,2007-03-15 17:07:00.000,2007-03-15 20:00:03.000,1,AAON,US0003602069,226,8.536817e+05,3.166087e+05,5.050256e+05,...,83,2.797337e+05,5.419006e+05,89,137,11435.60,20611.81,2,2,2007-03-15
5,2007-03-15,2007-03-15 16:03:00.000,2007-03-15 20:00:03.000,1,AAP,US00751Y1064,2921,2.441351e+07,1.389837e+07,1.044279e+07,...,607,1.384580e+07,1.049535e+07,1609,1311,68539.93,3812.10,10,1,2007-03-15
6,2007-03-15,2007-03-15 19:55:00.000,2007-03-15 20:00:03.000,1,AAPL,US0378331005,96026,1.750556e+09,8.498256e+08,7.769597e+08,...,12607,8.521414e+08,7.746438e+08,48361,47665,69841874.14,53928494.91,1233,757,2007-03-15
7,2007-03-15,2007-03-15 17:06:00.000,2007-03-15 20:00:03.000,1,AATI,US00752J1088,1752,3.112305e+06,1.605598e+06,1.391709e+06,...,289,1.574773e+06,1.422533e+06,871,881,97544.68,17454.12,23,7,2007-03-15
8,2007-03-15,2007-03-15 17:06:00.000,2007-03-15 20:00:03.000,1,AAWW,US0491642056,1145,1.475244e+07,9.655547e+06,5.096890e+06,...,204,9.524398e+06,5.228038e+06,588,557,0.00,0.00,0,0,2007-03-15
9,2007-03-15,2007-03-15 17:07:00.000,2007-03-15 20:00:03.000,1,ABAX,US0025671050,678,2.371769e+06,1.273862e+06,1.089978e+06,...,130,1.271084e+06,1.092757e+06,375,302,2274.99,5653.25,1,1,2007-03-15

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-08,2024-01-08 19:01:00.000,2024-01-08 20:00:03.000,1,A,US00846U1016,24462,1.632557e+08,1.052314e+08,5.371729e+07,...,5613,1.040284e+08,5.492026e+07,13497,10964,2661418.69,1645589.38,441,306,2024-01-08
1,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AA,US0138721065,46948,1.500690e+08,6.576694e+07,6.618504e+07,...,6999,5.820643e+07,7.374556e+07,22802,24146,9402977.83,8714056.07,924,826,2024-01-08
2,2024-01-08,2024-01-08 19:57:00.000,2024-01-08 20:00:03.000,1,AADI,US00032Q1040,2508,8.570716e+05,4.046190e+05,3.379180e+05,...,415,4.070869e+05,3.354501e+05,1324,1184,38070.84,76463.72,137,112,2024-01-08
3,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAL,US02376R1023,145264,8.455748e+08,3.623520e+08,3.747814e+08,...,23459,3.638610e+08,3.732724e+08,74375,70888,59954048.37,48487279.84,5383,5030,2024-01-08
4,2024-01-08,2024-01-08 19:01:00.000,2024-01-08 20:00:03.000,1,AAN,US00258W1080,4054,2.664774e+06,1.174707e+06,1.414832e+06,...,633,1.157302e+06,1.432237e+06,2073,1978,46526.93,28707.89,30,32,2024-01-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-08,2024-01-08 19:56:00.000,2024-01-08 20:00:03.000,1,AKR,US0042391096,8327,2.056472e+07,1.238269e+07,8.048855e+06,...,1036,1.237200e+07,8.059550e+06,4362,3965,92321.45,40851.86,87,56,2024-01-08
96,2024-01-08,2024-01-08 19:27:00.000,2024-01-08 20:00:03.000,1,AKRO,US00973Y1082,13011,2.169628e+07,9.174492e+06,1.220706e+07,...,2122,8.661140e+06,1.272041e+07,7182,5828,146630.70,168098.61,95,79,2024-01-08
97,2024-01-08,2024-01-08 18:56:00.000,2024-01-08 20:00:03.000,1,AKTS,US00973N1028,1346,3.280769e+05,8.201159e+04,1.420046e+05,...,347,8.338239e+04,1.406337e+05,744,602,73078.09,30982.65,216,111,2024-01-08
98,2024-01-08,2024-01-08 19:28:00.000,2024-01-08 20:00:03.000,1,AKYA,US00974H1041,4803,3.621642e+06,1.879072e+06,1.226661e+06,...,923,1.851844e+06,1.253890e+06,2736,2067,225429.81,290479.02,197,109,2024-01-08
99,2024-01-08,2024-01-08 19:39:00.000,2024-01-08 20:00:03.000,1,AL,US00912X3026,9884,2.387698e+07,1.362071e+07,9.738291e+06,...,1752,1.361881e+07,9.740187e+06,4718,5166,374228.76,143757.89,193,78,2024-01-08

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-04,2007-01-04 20:00:00.000,2007-01-04 20:00:03.000,1,AAPL,US0378331005,132141,2.458420e+09,1.149540e+09,1.148633e+09,...,20310,1.157005e+09,1.141168e+09,66842,65299,9.386545e+07,6.638126e+07,2153,1483,2007-01-04
1,2007-01-11,2007-01-11 20:00:00.000,2007-01-11 20:00:03.000,1,AAPL,NaN,231957,4.861693e+09,2.236786e+09,2.299434e+09,...,32571,2.232042e+09,2.304178e+09,114902,117055,1.735344e+08,1.519386e+08,3154,2943,2007-01-11
2,2007-01-19,2007-01-19 20:00:00.000,2007-01-19 20:00:03.000,1,AAPL,US0378331005,226821,4.264110e+09,2.040741e+09,2.010729e+09,...,29790,2.033817e+09,2.017653e+09,113992,112829,1.150057e+08,9.763356e+07,2574,1493,2007-01-19
3,2007-01-10,2007-01-10 20:00:00.000,2007-01-10 20:00:03.000,1,AAPL,US0378331005,472060,9.897434e+09,4.620889e+09,4.701053e+09,...,68123,4.639290e+09,4.682652e+09,236048,236012,3.206451e+08,2.548465e+08,5918,4512,2007-01-10
4,2007-01-22,2007-01-22 19:59:00.000,2007-01-22 20:00:03.000,1,AAPL,US0378331005,242059,4.396510e+09,2.088338e+09,2.094325e+09,...,33730,2.088578e+09,2.094085e+09,120774,121285,1.173658e+08,9.648159e+07,2102,1697,2007-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-04-30,2007-04-30 19:59:00.000,2007-04-30 20:00:03.000,1,AAPL,US0378331005,92216,2.155373e+09,9.087315e+08,1.110063e+09,...,12217,9.091530e+08,1.109641e+09,42656,49560,7.218697e+07,6.439178e+07,1324,1313,2007-04-30
96,2007-06-27,2007-06-27 20:00:00.000,2007-06-27 20:00:03.000,1,AAPL,US0378331005,156434,4.138958e+09,1.959430e+09,1.861982e+09,...,28853,1.958302e+09,1.863110e+09,80538,75896,1.698650e+08,1.476807e+08,2508,1832,2007-06-27
97,2007-06-04,2007-06-04 20:00:00.000,2007-06-04 20:00:03.000,1,AAPL,US0378331005,144701,3.802201e+09,1.790145e+09,1.715911e+09,...,24189,1.788857e+09,1.717199e+09,74140,70561,1.660215e+08,1.301230e+08,2076,1492,2007-06-04
98,2007-04-23,2007-04-23 20:00:00.000,2007-04-23 20:00:03.000,1,AAPL,US0378331005,114118,2.534833e+09,1.149607e+09,1.147590e+09,...,13756,1.146563e+09,1.150634e+09,58533,55585,1.325802e+08,1.050563e+08,2245,1550,2007-04-23
99,2007-07-17,2007-07-17 19:57:00.000,2007-07-17 20:00:03.000,1,AAPL,US0378331005,111778,3.463065e+09,1.601619e+09,1.617194e+09,...,17727,1.603396e+09,1.615416e+09,55673,56105,1.292858e+08,1.149673e+08,1543,1288,2007-07-17

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [10]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial',key='AAPL', back_to='2022-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2022-01-11,2022-01-11 20:00:00.000,2022-01-11 20:00:03.000,1,AAPL,US0378331005,646449,1.299387e+10,5.773775e+09,5.577933e+09,...,144418,5.747799e+09,5.603909e+09,319781,326666,8.626667e+08,7.794930e+08,40958,29709,2022-01-11
1,2022-01-07,2022-01-07 20:00:00.000,2022-01-07 20:00:03.000,1,AAPL,US0378331005,711666,1.344828e+10,5.956904e+09,5.840731e+09,...,153941,5.797197e+09,6.000438e+09,350095,361569,8.461815e+08,8.044663e+08,46317,31092,2022-01-07
2,2022-01-25,2022-01-25 20:00:00.000,2022-01-25 20:00:03.000,1,AAPL,US0378331005,1004097,1.666131e+10,7.293212e+09,7.575493e+09,...,223479,7.116904e+09,7.751801e+09,486039,518058,9.270545e+08,8.655477e+08,57156,36658,2022-01-25
3,2022-01-20,2022-01-20 20:00:00.000,2022-01-20 20:00:03.000,1,AAPL,US0378331005,788833,1.415136e+10,5.890217e+09,6.634542e+09,...,163948,5.839139e+09,6.685619e+09,379074,409758,8.419941e+08,7.846123e+08,44758,29867,2022-01-20
4,2022-01-06,2022-01-06 20:00:00.000,2022-01-06 20:00:03.000,1,AAPL,US0378331005,953226,1.575368e+10,7.035133e+09,7.102923e+09,...,201412,6.977277e+09,7.160779e+09,461703,491521,8.572152e+08,7.584082e+08,52850,31056,2022-01-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-03-30,2023-03-30 20:00:00.000,2023-03-30 20:00:03.000,1,AAPL,US0378331005,452442,7.423575e+09,3.342989e+09,3.133010e+09,...,90207,3.315258e+09,3.160741e+09,251021,201418,5.002073e+08,4.473687e+08,31878,21875,2023-03-30
96,2023-03-29,2023-03-29 20:00:00.000,2023-03-29 20:00:03.000,1,AAPL,US0378331005,469066,7.980000e+09,3.692745e+09,3.298012e+09,...,93108,3.700874e+09,3.289883e+09,264339,204727,5.260997e+08,4.631431e+08,31917,23755,2023-03-29
97,2023-02-24,2023-02-24 20:00:00.000,2023-02-24 20:00:03.000,1,AAPL,US0378331005,469379,7.969184e+09,3.495078e+09,3.482228e+09,...,101029,3.501172e+09,3.476134e+09,233869,235510,5.387998e+08,4.530787e+08,58064,20692,2023-02-24
98,2023-04-26,2023-04-26 20:00:00.000,2023-04-26 20:00:03.000,1,AAPL,US0378331005,490154,7.290991e+09,3.353673e+09,3.089235e+09,...,93068,3.356592e+09,3.086315e+09,266950,223204,4.329345e+08,4.151491e+08,27868,20869,2023-04-26
99,2023-05-15,2023-05-15 20:00:00.000,2023-05-15 20:00:03.000,1,AAPL,US0378331005,440698,6.015579e+09,2.789642e+09,2.399567e+09,...,82135,2.790133e+09,2.399076e+09,265997,174701,3.993602e+08,4.270095e+08,26370,21599,2023-05-15

## Download data file for a specific date using asof_date

In [11]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1_trial", target_location="./data")