In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_daily_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-03-21,2007-03-21 15:07:00.000,2007-03-21 20:00:03.000,0,IMB,US4566071001,7,21216.0000,4246.00,16970.00,...,4,12022.00,9194.00,2,0,0.00,0,0,0,2007-03-21
1,2007-03-21,2007-03-21 15:15:00.000,2007-03-21 20:00:03.000,0,KCLI,US4848361014,8,36484.0000,18290.00,18194.00,...,2,11415.00,25069.00,0,3,0.00,0,0,0,2007-03-21
2,2007-03-21,2007-03-21 15:18:00.000,2007-03-21 20:00:03.000,0,FCNCA,US31946M1036,23,720606.5400,138817.33,581789.21,...,10,138817.33,581789.21,6,17,0.00,0,0,0,2007-03-21
3,2007-03-21,2007-03-21 15:26:00.000,2007-03-21 20:00:03.000,0,ERI,US29246J2006,14,8138.0000,6966.00,1172.00,...,2,4176.00,3962.00,3,2,0.00,0,0,0,2007-03-21
4,2007-03-21,2007-03-21 15:26:00.000,2007-03-21 20:00:03.000,0,VALU,US9204371002,8,36437.0000,11408.00,25029.00,...,4,22771.67,13665.33,3,1,0.00,0,0,0,2007-03-21
5,2007-03-21,2007-03-21 15:35:00.000,2007-03-21 20:00:03.000,0,NASB,US6289681099,8,33105.0500,22544.05,10561.00,...,3,23612.52,9492.52,3,0,0.00,0,0,0,2007-03-21
6,2007-03-21,2007-03-21 15:35:00.000,2007-03-21 20:00:03.000,0,YDNT,US9875201033,87,291859.8739,178151.53,90099.81,...,27,152392.58,115858.76,24,7,23608.53,0,5,0,2007-03-21
7,2007-03-21,2007-03-21 15:40:00.000,2007-03-21 20:00:03.000,0,TRBN,US89778N1028,68,189988.8600,60870.75,129118.11,...,24,96437.65,93551.23,5,5,0.00,0,0,0,2007-03-21
8,2007-03-21,2007-03-21 15:46:00.000,2007-03-21 20:00:03.000,0,WSC,US9508171066,48,558885.6990,300568.87,258316.83,...,17,287328.87,271556.83,25,23,0.00,0,0,0,2007-03-21
9,2007-03-21,2007-03-21 15:48:00.000,2007-03-21 20:00:03.000,0,LAWS,US5207761058,44,172707.2500,101863.50,70843.75,...,17,116292.17,56415.07,18,3,0.00,0,0,0,2007-03-21

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,0,AFRI,GI000A3DNK69,137,1.159667e+05,58664.61,57302.07,...,21,57460.90,58505.88,1,1,0.00,0.00,0,0,2024-01-30
1,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,0,BHRB,US12135Y1082,407,4.890747e+05,133802.24,339153.15,...,160,118405.67,354549.72,72,335,2944.57,13174.75,4,7,2024-01-30
2,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,1,BSVN,US06652N1072,1023,8.464414e+05,310265.46,503784.44,...,275,234303.52,579746.33,276,747,30606.47,1785.13,15,5,2024-01-30
3,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,1,DRVN,US26210V1026,8138,8.300793e+06,4226888.90,3832195.03,...,1075,3929061.12,4130022.54,186,201,196439.00,45270.15,165,67,2024-01-30
4,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,1,PINC,US74051N1028,15739,4.038017e+07,17039383.75,23135644.12,...,1664,17448954.10,22726073.75,4648,11091,83175.27,121965.22,48,68,2024-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-30,2024-01-30 16:07:00.000,2024-01-30 20:00:03.000,1,USCB,US90355N1019,138,3.150803e+05,78961.72,235393.98,...,49,154281.79,160073.87,0,4,0.00,724.66,0,3,2024-01-30
96,2024-01-30,2024-01-30 16:07:00.000,2024-01-30 20:00:03.000,1,XOMA,US98419J2069,492,3.207303e+05,196486.39,118930.51,...,140,66059.51,249357.43,33,302,1532.89,3780.52,3,3,2024-01-30
97,2024-01-30,2024-01-30 16:08:00.000,2024-01-30 20:00:03.000,1,AMNB,US0277451086,267,6.823503e+05,121448.55,513647.29,...,93,194785.39,440310.48,106,161,13981.78,33272.65,12,10,2024-01-30
98,2024-01-30,2024-01-30 16:08:00.000,2024-01-30 20:00:03.000,1,AROW,US0427441029,787,8.288660e+05,253104.92,552824.65,...,239,41329.51,764600.05,27,754,10411.21,12525.25,12,12,2024-01-30
99,2024-01-30,2024-01-30 16:08:00.000,2024-01-30 20:00:03.000,1,ARTNA,US0431132085,495,4.782765e+05,203873.34,258731.83,...,153,131249.85,331355.37,160,335,6606.45,9064.78,7,7,2024-01-30

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-07,2007-02-07 20:01:00.000,2007-02-07 20:00:03.000,1,AAPL,US0378331005,163849,3.223635e+09,1.659573e+09,1.485046e+09,...,20584,2.054095e+09,1.090524e+09,98150,60236,4.869629e+07,30319753.64,2462,1531,2007-02-07
1,2007-03-15,2007-03-15 19:56:00.000,2007-03-15 20:00:03.000,1,AAPL,US0378331005,96025,1.750510e+09,8.654880e+08,8.493707e+08,...,12606,3.707120e+08,1.344147e+09,22903,72885,2.195176e+07,13699898.49,1233,757,2007-03-15
2,2007-01-23,2007-01-23 20:00:00.000,2007-01-23 20:00:03.000,1,AAPL,US0378331005,210641,3.700886e+09,1.815347e+09,1.801014e+09,...,31045,1.842480e+09,1.773881e+09,110651,99961,5.165385e+07,32871406.09,2916,1867,2007-01-23
3,2007-03-14,2007-03-14 20:00:00.000,2007-03-14 20:00:03.000,1,AAPL,US0378331005,142908,2.432287e+09,1.267730e+09,1.120348e+09,...,18520,1.786347e+09,6.017304e+08,105165,37740,2.584720e+07,18361807.72,1513,1055,2007-03-14
4,2007-02-01,2007-02-01 20:01:00.000,2007-02-01 20:00:03.000,1,AAPL,US0378331005,110375,2.007913e+09,9.806625e+08,9.926012e+08,...,13013,9.643504e+08,1.008913e+09,54404,55971,2.067391e+07,13975484.09,1142,714,2007-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-06-29,2007-06-29 20:01:00.000,2007-06-29 20:00:03.000,1,AAPL,US0378331005,177426,4.829559e+09,2.400018e+09,2.263022e+09,...,30757,2.760402e+09,1.902637e+09,103031,73825,9.338348e+07,73135767.93,3396,2650,2007-06-29
96,2007-07-31,2007-07-31 20:01:00.000,2007-07-31 20:00:03.000,1,AAPL,US0378331005,290979,8.498393e+09,4.094456e+09,4.187167e+09,...,69251,3.629904e+09,4.651720e+09,129915,161047,1.207712e+08,95999139.74,4172,3309,2007-07-31
97,2007-06-21,2007-06-21 20:01:00.000,2007-06-21 20:00:03.000,1,AAPL,US0378331005,136946,3.732650e+09,1.875804e+09,1.741022e+09,...,23927,2.467692e+09,1.149133e+09,93014,43927,6.744796e+07,48376491.94,2443,1754,2007-06-21
98,2007-03-05,2007-03-05 20:01:00.000,2007-03-05 20:00:03.000,1,AAPL,US0378331005,146349,2.575116e+09,1.199052e+09,1.294136e+09,...,18340,7.456572e+08,1.747531e+09,42726,103623,4.646321e+07,35464730.99,1958,1348,2007-03-05
99,2007-06-25,2007-06-25 20:00:00.000,2007-06-25 20:00:03.000,1,AAPL,US0378331005,159672,4.180452e+09,1.973917e+09,2.062481e+09,...,28165,1.277137e+09,2.759262e+09,51526,108141,8.461701e+07,59437007.65,3165,2203,2007-06-25

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,US0378331005,585485,8.177436e+09,4.069209e+09,3.347815e+09,...,105858,4.263993e+09,3.153031e+09,301896,283518,4.652386e+08,2.951733e+08,33131,20739,2024-01-17
1,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,US0378331005,704320,1.160613e+10,5.085719e+09,5.255783e+09,...,141718,3.824973e+09,6.516528e+09,285462,418792,8.521382e+08,4.124884e+08,52306,25296,2024-01-04
2,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,US0378331005,682123,9.997138e+09,5.243521e+09,3.764508e+09,...,131715,4.989138e+09,4.018891e+09,331875,350248,5.983166e+08,3.907921e+08,41139,26414,2024-01-30
3,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,US0378331005,777009,1.407412e+10,6.525488e+09,6.259469e+09,...,144862,6.136234e+09,6.648724e+09,461588,313287,6.972198e+08,5.919468e+08,39269,31654,2024-01-18
4,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,US0378331005,672873,1.247752e+10,6.453219e+09,5.029133e+09,...,121470,7.644821e+09,3.837530e+09,532463,140410,5.415875e+08,4.535793e+08,32810,25615,2024-01-19
5,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,US0378331005,573592,8.499694e+09,4.130572e+09,3.580104e+09,...,105520,4.536361e+09,3.174315e+09,254275,319317,4.970823e+08,2.919359e+08,35207,19919,2024-01-11
6,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,US0378331005,590108,8.135218e+09,3.895377e+09,3.484026e+09,...,105285,2.352155e+09,5.027247e+09,218967,369775,4.378415e+08,3.179740e+08,31284,22478,2024-01-29
7,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,US0378331005,530846,7.457582e+09,4.200570e+09,2.515406e+09,...,98440,5.819325e+09,8.966506e+08,453101,77735,4.232381e+08,3.183680e+08,32096,23905,2024-01-09
8,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,US0378331005,527652,8.164331e+09,3.866378e+09,3.615130e+09,...,92775,4.173297e+09,3.308211e+09,306436,220071,3.827613e+08,3.000617e+08,24914,19586,2024-01-26
9,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,US0378331005,635510,9.921383e+09,4.653089e+09,4.391300e+09,...,110063,4.187310e+09,4.857079e+09,305904,329605,4.808374e+08,3.961562e+08,31153,25473,2024-01-25
10,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,US0378331005,754694,1.064376e+10,5.534914e+09,4.143446e+09,...,140421,6.128538e+09,3.549822e+09,468751,285943,5.863861e+08,3.790186e+08,44587,28380,2024-01-16
11,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,US0378331005,673798,9.649756e+09,4.751073e+09,4.092012e+09,...,129079,4.309913e+09,4.533171e+09,419310,254487,4.901228e+08,3.165486e+08,36382,23948,2024-01-31
12,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,US0378331005,646672,9.850288e+09,4.962202e+09,3.895633e+09,...,129183,5.887228e+09,2.970608e+09,337365,309307,5.323952e+08,4.600564e+08,36499,31646,2024-01-03
13,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,US0378331005,587964,9.464511e+09,4.085833e+09,4.527814e+09,...,105630,2.184623e+09,6.429024e+09,217941,370023,4.297317e+08,4.211323e+08,27663,27274,2024-01-24
14,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,US0378331005,990769,1.412446e+10,6.623136e+09,6.059647e+09,...,203660,5.313102e+09,7.369681e+09,246488,744247,9.361353e+08,5.055433e+08,69922,36466,2024-01-02
15,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,US0378331005,527095,7.690176e+09,4.116604e+09,2.814792e+09,...,91852,4.246585e+09,2.684811e+09,294083,229943,3.876772e+08,3.711025e+08,25365,23987,2024-01-23
16,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,US0378331005,675347,1.073244e+10,5.070129e+09,4.547816e+09,...,132531,3.601071e+09,6.016874e+09,349875,324250,7.121559e+08,4.023349e+08,46270,25440,2024-01-05
17,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,US0378331005,470682,6.976980e+09,3.297618e+09,2.996437e+09,...,82996,1.538823e+09,4.755232e+09,141921,326966,4.154052e+08,2.675194e+08,29498,17852,2024-01-12
18,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,US0378331005,708836,1.076400e+10,5.608608e+09,4.200468e+09,...,125210,4.332822e+09,5.476253e+09,387027,321791,5.172445e+08,4.376840e+08,34889,29419,2024-01-22
19,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,US0378331005,547961,8.236493e+09,4.186066e+09,3.235051e+09,...,100366,5.489185e+09,1.931931e+09,394720,153237,4.965958e+08,3.187805e+08,33865,20667,2024-01-10
20,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,US0378331005,659243,1.029335e+10,5.566881e+09,3.683946e+09,...,122231,7.146960e+09,2.103867e+09,426813,231163,6.522086e+08,3.903154e+08,45879,26647,2024-01-08

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_daily_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for xtech_us_eqt_flow_r3k_with_isin_daily_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_with_isin_daily_trial. Downloaded 1 files.