In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-24,2007-01-24 16:07:00.000,2007-01-24 20:00:03.000,1,A,US00846U1016,7651,9.407512e+07,4.095221e+07,5.238044e+07,...,1167,7.634462e+06,8.569819e+07,697,6857,281375.88,461097.05,26,50,2007-01-24
1,2007-01-24,2007-01-24 17:00:00.000,2007-01-24 20:00:03.000,1,AA,US0138171014,24356,3.160401e+08,1.781749e+08,1.346658e+08,...,2338,1.576922e+08,1.551484e+08,1222,1034,1448256.92,1751229.59,108,136,2007-01-24
2,2007-01-24,2007-01-24 16:57:00.000,2007-01-24 20:00:03.000,1,AACC,US04543P1003,568,1.445130e+06,6.039634e+05,8.249404e+05,...,128,6.589260e+05,7.699778e+05,34,65,9796.04,6430.25,3,2,2007-01-24
3,2007-01-24,2007-01-24 16:57:00.000,2007-01-24 20:00:03.000,1,AAI,US00949P1084,7083,2.580337e+07,1.101998e+07,1.446857e+07,...,940,1.244873e+07,1.303982e+07,342,451,235046.93,79768.86,67,20,2007-01-24
4,2007-01-24,2007-01-24 16:57:00.000,2007-01-24 20:00:03.000,1,AAON,US0003602069,120,4.105394e+05,1.960326e+05,2.027905e+05,...,44,3.623049e+05,3.651822e+04,108,9,11716.33,0.00,2,0,2007-01-24
5,2007-01-24,2007-01-24 16:05:00.000,2007-01-24 20:00:03.000,1,AAP,US00751Y1064,1559,1.071294e+07,6.128901e+06,4.517672e+06,...,344,5.266783e+06,5.379790e+06,108,122,29607.62,36763.37,5,5,2007-01-24
6,2007-01-24,2007-01-24 20:00:00.000,2007-01-24 20:00:03.000,1,AAPL,US0378331005,148219,2.778857e+09,1.272891e+09,1.429485e+09,...,17925,7.244373e+08,1.977938e+09,10648,73667,47128856.52,29352081.76,2509,1553,2007-01-24
7,2007-01-24,2007-01-24 16:57:00.000,2007-01-24 20:00:03.000,1,AATI,US00752J1088,1336,2.017575e+06,1.122597e+06,8.607132e+05,...,171,9.643751e+05,1.018935e+06,70,120,26511.33,7753.11,12,5,2007-01-24
8,2007-01-24,2007-01-24 16:57:00.000,2007-01-24 20:00:03.000,1,AAWW,US0491642056,941,1.088504e+07,6.558105e+06,4.273682e+06,...,220,8.451614e+06,2.380173e+06,662,263,12188.42,41069.45,1,3,2007-01-24
9,2007-01-24,2007-01-24 16:57:00.000,2007-01-24 20:00:03.000,1,ABAX,US0025671050,573,1.494811e+06,7.664405e+05,6.775645e+05,...,140,6.771258e+05,7.668793e+05,42,81,32751.19,18055.14,7,5,2007-01-24

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-25,2024-01-25 19:01:00.000,2024-01-25 20:00:03.000,1,A,US00846U1016,22063,1.374927e+08,4.847966e+07,8.534832e+07,...,5062,2.821631e+07,1.056117e+08,6563,15498,2394862.08,1269820.41,423,268,2024-01-25
1,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AA,US0138721065,45262,1.327183e+08,4.989987e+07,7.900162e+07,...,5737,8.361985e+06,1.205395e+08,2727,42479,1942295.49,1874548.70,671,652,2024-01-25
2,2024-01-25,2024-01-25 19:42:00.000,2024-01-25 20:00:03.000,1,AADI,US00032Q1040,1160,3.318284e+05,1.420257e+05,1.644286e+05,...,180,1.506694e+05,1.557849e+05,24,34,14810.08,10564.07,36,34,2024-01-25
3,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAL,US02376R1023,267015,1.415083e+09,7.551153e+08,5.709447e+08,...,38659,1.101619e+09,2.244414e+08,217041,49974,37972262.33,51050760.73,7400,10086,2024-01-25
4,2024-01-25,2024-01-25 19:01:00.000,2024-01-25 20:00:03.000,1,AAN,US00258W1080,2747,1.656648e+06,7.812205e+05,8.521422e+05,...,387,6.896006e+05,9.437619e+05,48,56,16727.16,6558.55,29,10,2024-01-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-25,2024-01-25 19:29:00.000,2024-01-25 20:00:03.000,1,AKR,US0042391096,12266,2.165018e+07,1.110673e+07,1.033656e+07,...,1425,1.081522e+07,1.062807e+07,350,268,141117.15,65777.01,84,43,2024-01-25
96,2024-01-25,2024-01-25 16:09:00.000,2024-01-25 20:00:03.000,1,AKRO,US00973Y1082,9742,1.299084e+07,8.139446e+06,4.730205e+06,...,1673,1.104137e+07,1.828286e+06,7739,2003,48149.13,73041.78,44,81,2024-01-25
97,2024-01-25,2024-01-25 19:29:00.000,2024-01-25 20:00:03.000,1,AKTS,US00973N1028,8709,2.752469e+06,1.288441e+06,9.824673e+05,...,1909,1.099283e+06,1.171625e+06,162,164,290390.32,191170.61,850,691,2024-01-25
98,2024-01-25,2024-01-25 19:26:00.000,2024-01-25 20:00:03.000,1,AKYA,US00974H1041,710,3.145046e+05,1.868149e+05,1.183807e+05,...,140,2.794885e+04,2.772468e+05,89,621,5898.99,3409.92,13,10,2024-01-25
99,2024-01-25,2024-01-25 19:01:00.000,2024-01-25 20:00:03.000,1,AL,US00912X3026,14926,4.459450e+07,3.068130e+07,1.295297e+07,...,2536,4.241527e+07,1.219007e+06,14518,368,545053.61,415178.58,213,165,2024-01-25

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-13,2007-02-13 19:59:00.000,2007-02-13 20:00:03.000,1,AAPL,US0378331005,100533,1.735861e+09,7.666717e+08,9.226778e+08,...,11817,4.338331e+08,1.255516e+09,27679,71790,2.599329e+07,20518113.71,1515,1128,2007-02-13
1,2007-01-31,2007-01-31 20:00:00.000,2007-01-31 20:00:03.000,1,AAPL,US0378331005,136890,2.567410e+09,1.234216e+09,1.287828e+09,...,17677,9.978179e+08,1.524226e+09,54371,82517,2.677577e+07,18590418.47,1418,1012,2007-01-31
2,2007-02-08,2007-02-08 20:00:00.000,2007-02-08 20:00:03.000,1,AAPL,US0378331005,112598,2.032911e+09,9.969550e+08,9.863288e+08,...,15532,1.010496e+09,9.727882e+08,57111,55476,2.830822e+07,21319423.81,1565,1177,2007-02-08
3,2007-01-08,2007-01-08 19:59:00.000,2007-01-08 20:00:03.000,1,AAPL,NaN,130324,2.421748e+09,1.193551e+09,1.157076e+09,...,17413,9.546285e+08,1.395998e+09,53191,77129,4.614739e+07,24974119.20,2462,1317,2007-01-08
4,2007-03-01,2007-03-01 19:58:00.000,2007-03-01 20:00:03.000,1,AAPL,US0378331005,248202,4.302542e+09,2.225738e+09,2.004932e+09,...,34648,3.103854e+09,1.126817e+09,182664,65534,3.848018e+07,33391744.59,2148,1861,2007-03-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-08-01,2007-08-01 20:00:00.000,2007-08-01 20:00:03.000,1,AAPL,US0378331005,288994,8.154617e+09,4.019104e+09,3.919784e+09,...,73341,4.407059e+09,3.531829e+09,157679,131304,1.201791e+08,95550737.72,4164,3287,2007-08-01
96,2007-06-28,2007-06-28 20:00:00.000,2007-06-28 20:00:03.000,1,AAPL,US0378331005,126974,3.538269e+09,1.643460e+09,1.773569e+09,...,22593,9.583380e+08,2.458692e+09,38737,87995,6.884142e+07,52397943.48,2499,1887,2007-06-28
97,2007-06-22,2007-06-22 20:00:00.000,2007-06-22 20:00:03.000,1,AAPL,US0378331005,97119,2.635967e+09,1.218543e+09,1.309482e+09,...,18635,1.059705e+09,1.468320e+09,41009,56024,6.929325e+07,38648605.91,1977,1284,2007-06-22
98,2007-07-12,2007-07-12 20:00:00.000,2007-07-12 20:00:03.000,1,AAPL,US0378331005,107141,3.224439e+09,1.608542e+09,1.532499e+09,...,17411,1.780490e+09,1.360550e+09,58507,48629,4.420674e+07,39191637.12,1459,1281,2007-07-12
99,2007-03-09,2007-03-09 19:46:00.000,2007-03-09 20:00:03.000,1,AAPL,US0378331005,77687,1.398205e+09,6.579510e+08,7.054014e+08,...,9750,6.223274e+08,7.410250e+08,31058,36805,1.681228e+07,18040168.12,888,641,2007-03-09

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,US0378331005,990770,1.412446e+10,6.623133e+09,6.059657e+09,...,203661,5.313069e+09,7.369722e+09,246489,744247,9.361314e+08,5.055404e+08,69922,36466,2024-01-02
1,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,US0378331005,777010,1.407412e+10,6.441001e+09,6.411099e+09,...,144863,6.152252e+09,6.699848e+09,461588,313288,6.676443e+08,5.543803e+08,39269,31654,2024-01-18
2,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,US0378331005,470683,6.976981e+09,3.291219e+09,3.002975e+09,...,82997,1.538530e+09,4.755664e+09,141921,326966,4.153750e+08,2.674128e+08,29498,17852,2024-01-12
3,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,US0378331005,708837,1.076401e+10,5.608460e+09,4.200627e+09,...,125211,4.332346e+09,5.476742e+09,387027,321791,5.172395e+08,4.376786e+08,34889,29419,2024-01-22
4,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,US0378331005,547962,8.236493e+09,4.186085e+09,3.235029e+09,...,100367,5.489186e+09,1.931929e+09,394721,153237,4.965947e+08,3.187833e+08,33865,20667,2024-01-10
5,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,US0378331005,682124,9.997138e+09,5.243468e+09,3.764531e+09,...,131716,4.989186e+09,4.018813e+09,331875,350249,5.983342e+08,3.908052e+08,41139,26414,2024-01-30
6,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,US0378331005,675348,1.073244e+10,5.060611e+09,4.557467e+09,...,132532,3.601085e+09,6.016993e+09,349875,324250,7.120352e+08,4.023235e+08,46270,25440,2024-01-05
7,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,US0378331005,527653,8.164333e+09,3.866420e+09,3.615050e+09,...,92776,4.173273e+09,3.308197e+09,306436,220072,3.827252e+08,3.001382e+08,24914,19586,2024-01-26
8,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,US0378331005,673799,9.649775e+09,4.751167e+09,4.091920e+09,...,129080,4.310247e+09,4.532841e+09,419311,254487,4.901400e+08,3.165473e+08,36382,23948,2024-01-31
9,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,US0378331005,587965,9.464530e+09,4.085500e+09,4.528231e+09,...,105631,2.183976e+09,6.429755e+09,217942,370023,4.297140e+08,4.210849e+08,27663,27274,2024-01-24
10,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,US0378331005,635511,9.921383e+09,4.652936e+09,4.391468e+09,...,110064,4.187532e+09,4.856872e+09,305904,329605,4.808354e+08,3.961437e+08,31153,25473,2024-01-25
11,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,US0378331005,646673,9.850288e+09,4.962282e+09,3.895570e+09,...,129184,5.887301e+09,2.970551e+09,337365,309308,5.323861e+08,4.600496e+08,36499,31646,2024-01-03
12,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,US0378331005,530847,7.457587e+09,4.198502e+09,2.517493e+09,...,98441,5.814233e+09,9.017617e+08,453102,77735,4.232342e+08,3.183575e+08,32096,23905,2024-01-09
13,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,US0378331005,590109,8.135219e+09,3.895651e+09,3.483823e+09,...,105286,2.352413e+09,5.027061e+09,218967,369775,4.377972e+08,3.179474e+08,31284,22478,2024-01-29
14,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,US0378331005,754695,1.064378e+10,5.534916e+09,4.143439e+09,...,140422,6.128546e+09,3.549808e+09,468751,285943,5.864017e+08,3.790271e+08,44587,28380,2024-01-16
15,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,US0378331005,672874,1.247752e+10,6.400096e+09,5.082925e+09,...,121471,7.644141e+09,3.838881e+09,532463,140411,5.415680e+08,4.529306e+08,32810,25615,2024-01-19
16,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,US0378331005,585486,8.177438e+09,4.069354e+09,3.347696e+09,...,105859,4.263990e+09,3.153060e+09,301897,283518,4.652283e+08,2.951595e+08,33131,20739,2024-01-17
17,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,US0378331005,527096,7.690177e+09,4.095794e+09,2.835907e+09,...,91853,4.247200e+09,2.684500e+09,294083,229944,3.875323e+08,3.709440e+08,25365,23987,2024-01-23
18,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,US0378331005,659244,1.029335e+10,5.566822e+09,3.684005e+09,...,122232,7.146958e+09,2.103868e+09,426813,231163,6.522098e+08,3.903147e+08,45879,26647,2024-01-08
19,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,US0378331005,704321,1.160613e+10,5.085703e+09,5.255791e+09,...,141719,3.824969e+09,6.516526e+09,285462,418792,8.521401e+08,4.124940e+08,52306,25296,2024-01-04
20,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,US0378331005,573593,8.499696e+09,4.130628e+09,3.580027e+09,...,105521,4.536398e+09,3.174257e+09,254275,319317,4.970836e+08,2.919579e+08,35207,19919,2024-01-11

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_trial. Downloaded 1 files.