In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-01,2007-02-01 04:18:00.000,2007-02-01 04:18:03.000,1,DELL,US24702R1014,1,2525.0,1262.5,1262.5,...,1,1262.5,1262.5,0,0,0,0,0,0,2007-02-01
1,2007-02-01,2007-02-01 04:23:00.000,2007-02-01 04:23:03.000,1,GILD,US3755581036,1,6735.0,3367.5,3367.5,...,1,6735.0,0.0,1,0,0,0,0,0,2007-02-01
2,2007-02-01,2007-02-01 05:35:00.000,2007-02-01 05:35:03.000,1,GILD,US3755581036,1,6775.0,6775.0,0.0,...,0,6775.0,0.0,1,0,0,0,0,0,2007-02-01
3,2007-02-01,2007-02-01 05:54:00.000,2007-02-01 05:54:03.000,1,DELL,US24702R1014,1,5088.0,5088.0,0.0,...,0,2544.0,2544.0,0,0,0,0,0,0,2007-02-01
4,2007-02-01,2007-02-01 05:55:00.000,2007-02-01 05:55:03.000,1,MLNM,US5999021034,1,4436.0,2218.0,2218.0,...,1,2218.0,2218.0,0,0,0,0,0,0,2007-02-01
5,2007-02-01,2007-02-01 05:58:00.000,2007-02-01 05:58:03.000,1,DELL,US24702R1014,2,50700.0,50700.0,0.0,...,1,25350.0,25350.0,0,0,0,0,0,0,2007-02-01
6,2007-02-01,2007-02-01 05:59:00.000,2007-02-01 05:59:03.000,1,DELL,US24702R1014,3,63375.0,63375.0,0.0,...,0,42250.0,21125.0,1,0,0,0,0,0,2007-02-01
7,2007-02-01,2007-02-01 06:06:00.000,2007-02-01 06:06:03.000,1,AAPL,US0378331005,1,8590.0,4295.0,4295.0,...,1,4295.0,4295.0,0,0,0,0,0,0,2007-02-01
8,2007-02-01,2007-02-01 06:14:00.000,2007-02-01 06:14:03.000,1,GILD,US3755581036,1,6800.0,6800.0,0.0,...,0,6800.0,0.0,1,0,0,0,0,0,2007-02-01
9,2007-02-01,2007-02-01 06:20:00.000,2007-02-01 06:20:03.000,1,DELL,US24702R1014,2,114750.0,114750.0,0.0,...,0,57375.0,57375.0,0,0,0,0,0,0,2007-02-01

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RLJ,US74965L1017,84,9.574961e+04,6839.26,86630.60,...,6,43315.30,50154.56,0,4,2279.75,0.00,2,0,2024-01-31
1,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RLYB,US75120L1008,25,1.942495e+03,854.70,1087.80,...,2,932.40,1010.10,0,1,0.00,0.00,0,0,2024-01-31
2,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RM,US75902K1060,15,4.500485e+03,600.06,3900.42,...,6,0.00,4500.48,0,15,0.00,0.00,0,0,2024-01-31
3,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RMAX,US75524W1080,24,9.464626e+03,1971.80,7098.47,...,7,0.00,9070.27,0,24,394.36,0.00,1,0,2024-01-31
4,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,RMBS,US7509171069,369,1.253948e+06,506336.90,747611.53,...,57,16991.17,1236957.26,5,364,0.00,0.00,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SDRL,BMG7997W1029,161,6.317897e+05,164814.72,427733.43,...,35,0.00,592548.15,2,159,39241.60,0.00,10,0,2024-01-31
96,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SEAS,US81282V1008,191,7.188193e+05,139247.72,579571.60,...,28,7526.90,711292.42,2,189,0.00,0.00,0,0,2024-01-31
97,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SEAT,US92854T1007,48,1.987317e+04,0.00,19459.16,...,7,828.05,18631.11,2,46,0.00,414.02,0,1,2024-01-31
98,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SEB,US8115431079,18,9.710432e+04,26973.42,70130.90,...,11,26973.42,70130.90,5,13,0.00,0.00,0,0,2024-01-31
99,2024-01-31,2024-01-31 15:58:00.000,2024-01-31 15:58:03.000,0,SEE,US81211K1007,253,1.243127e+06,624020.13,614193.05,...,28,19654.18,1218559.00,4,249,0.00,4913.54,0,1,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-09,2007-02-09 06:02:00.000,2007-02-09 06:02:03.000,1,AAPL,US0378331005,3,4.290500e+04,35754.17,7150.83,...,1,21452.50,21452.50,0,0,0.00,0.00,0,0,2007-02-09
1,2007-02-09,2007-02-09 06:33:00.000,2007-02-09 06:33:03.000,1,AAPL,US0378331005,2,3.430000e+04,0.00,34300.00,...,1,17150.00,17150.00,0,0,0.00,0.00,0,0,2007-02-09
2,2007-02-09,2007-02-09 06:36:00.000,2007-02-09 06:36:03.000,1,AAPL,US0378331005,1,8.577000e+03,0.00,8577.00,...,0,0.00,8577.00,0,1,0.00,0.00,0,0,2007-02-09
3,2007-02-09,2007-02-09 06:38:00.000,2007-02-09 06:38:03.000,1,AAPL,US0378331005,4,3.430900e+04,0.00,34309.00,...,1,0.00,34309.00,0,4,0.00,0.00,0,0,2007-02-09
4,2007-02-09,2007-02-09 06:46:00.000,2007-02-09 06:46:03.000,1,AAPL,US0378331005,1,8.620000e+03,8620.00,0.00,...,0,8620.00,0.00,1,0,0.00,0.00,0,0,2007-02-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-02-09,2007-02-09 09:41:00.000,2007-02-09 09:41:03.000,0,AAPL,US0378331005,691,1.065507e+07,4278991.53,6206465.18,...,124,3731589.01,6753867.70,249,442,107938.52,61679.16,7,4,2007-02-09
96,2007-02-09,2007-02-09 09:42:00.000,2007-02-09 09:42:03.000,0,AAPL,US0378331005,396,5.847757e+06,2170758.19,3514560.88,...,70,679284.88,5006034.19,51,345,73835.31,88602.37,5,6,2007-02-09
97,2007-02-09,2007-02-09 09:43:00.000,2007-02-09 09:43:03.000,0,AAPL,US0378331005,418,7.680006e+06,2351772.10,5217994.34,...,64,312344.73,7257421.71,21,397,73492.88,36746.44,4,2,2007-02-09
98,2007-02-09,2007-02-09 09:44:00.000,2007-02-09 09:44:03.000,0,AAPL,US0378331005,470,9.939178e+06,4557218.84,5085898.53,...,79,169177.50,9473939.87,16,454,169177.50,126883.12,8,6,2007-02-09
99,2007-02-09,2007-02-09 09:45:00.000,2007-02-09 09:45:03.000,0,AAPL,US0378331005,401,9.034476e+06,3931461.35,4900245.53,...,55,405537.56,8426169.32,24,377,135179.19,67589.59,6,3,2007-02-09

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_trial',key='AAPL', back_to='2024-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-12,2024-01-12 04:01:00.000,2024-01-12 04:01:03.000,1,AAPL,US0378331005,35,58571.59,24265.37,34306.22,...,10,28449.06,30122.53,0,1,0,0,0,0,2024-01-12
1,2024-01-12,2024-01-12 04:02:00.000,2024-01-12 04:02:03.000,1,AAPL,US0378331005,15,29497.38,0.00,29497.38,...,4,14748.69,14748.69,0,0,0,0,0,0,2024-01-12
2,2024-01-12,2024-01-12 04:03:00.000,2024-01-12 04:03:03.000,1,AAPL,US0378331005,17,77745.55,11433.17,66312.38,...,1,38872.78,38872.78,0,0,0,0,0,0,2024-01-12
3,2024-01-12,2024-01-12 04:04:00.000,2024-01-12 04:04:03.000,1,AAPL,US0378331005,17,18921.55,5565.16,13356.39,...,7,9460.78,9460.78,0,0,0,0,0,0,2024-01-12
4,2024-01-12,2024-01-12 04:05:00.000,2024-01-12 04:05:03.000,1,AAPL,US0378331005,10,10018.14,3005.44,7012.70,...,3,5009.07,5009.07,0,0,0,0,0,0,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-12,2024-01-12 05:38:00.000,2024-01-12 05:38:03.000,1,AAPL,US0378331005,10,3709.78,1112.93,2596.85,...,3,1854.89,1854.89,0,0,0,0,0,0,2024-01-12
96,2024-01-12,2024-01-12 05:39:00.000,2024-01-12 05:39:03.000,1,AAPL,US0378331005,12,26709.13,0.00,26709.13,...,2,13354.56,13354.56,0,0,0,0,0,0,2024-01-12
97,2024-01-12,2024-01-12 05:40:00.000,2024-01-12 05:40:03.000,1,AAPL,US0378331005,5,18731.58,0.00,18731.58,...,2,9365.79,9365.79,0,0,0,0,0,0,2024-01-12
98,2024-01-12,2024-01-12 05:41:00.000,2024-01-12 05:41:03.000,1,AAPL,US0378331005,26,131481.98,10114.00,121367.98,...,6,65740.99,65740.99,0,0,0,0,0,0,2024-01-12
99,2024-01-12,2024-01-12 05:42:00.000,2024-01-12 05:42:03.000,1,AAPL,US0378331005,4,1669.03,1251.77,417.26,...,2,834.51,834.51,0,0,0,0,0,0,2024-01-12

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_trial", target_location="./data", asof_date='2024-01-17')

Starting native python replication for xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_trial. Downloaded 1 files.