In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_1min_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-23,2007-02-23 06:37:00.000,2007-02-23 06:37:03.000,1,MSFT,US5949181045,2,72725.0,0.00,72725.00,...,1,36362.50,36362.50,0,0,0,0,0,0,2007-02-23
1,2007-02-23,2007-02-23 06:38:00.000,2007-02-23 06:38:03.000,1,MSFT,US5949181045,1,29170.0,0.00,29170.00,...,0,14585.00,14585.00,0,0,0,0,0,0,2007-02-23
2,2007-02-23,2007-02-23 06:52:00.000,2007-02-23 06:52:03.000,1,KO,US1912161007,2,66510.0,0.00,66510.00,...,0,0.00,66510.00,0,2,0,0,0,0,2007-02-23
3,2007-02-23,2007-02-23 06:54:00.000,2007-02-23 06:54:03.000,1,KO,US1912161007,1,47610.0,0.00,47610.00,...,0,0.00,47610.00,0,1,0,0,0,0,2007-02-23
4,2007-02-23,2007-02-23 06:55:00.000,2007-02-23 06:55:03.000,1,KO,US1912161007,2,47620.0,0.00,47620.00,...,0,23810.00,23810.00,0,0,0,0,0,0,2007-02-23
5,2007-02-23,2007-02-23 07:08:00.000,2007-02-23 07:08:03.000,1,SUNW,US8668102036,1,6930.0,6930.00,0.00,...,0,3465.00,3465.00,0,0,0,0,0,0,2007-02-23
6,2007-02-23,2007-02-23 07:09:00.000,2007-02-23 07:09:03.000,1,SUNW,US8668102036,1,8271.9,0.00,8271.90,...,0,4135.95,4135.95,0,0,0,0,0,0,2007-02-23
7,2007-02-23,2007-02-23 07:14:00.000,2007-02-23 07:14:03.000,1,MSFT,US5949181045,3,67183.0,22394.33,44788.67,...,0,33591.50,33591.50,0,0,0,0,0,0,2007-02-23
8,2007-02-23,2007-02-23 07:15:00.000,2007-02-23 07:15:03.000,1,CQB,US1700328099,2,3300.0,3300.00,0.00,...,0,3300.00,0.00,2,0,0,0,0,0,2007-02-23
9,2007-02-23,2007-02-23 07:15:00.000,2007-02-23 07:15:03.000,1,MSFT,US5949181045,1,75946.0,0.00,75946.00,...,0,37973.00,37973.00,0,0,0,0,0,0,2007-02-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,US0378331005,162,872419.18,551993.62,320425.56,...,43,185792.97,686626.21,34,127,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,US00287Y1091,3,2473.70,2473.70,0.00,...,1,412.28,2061.42,0,2,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABNB,US0090661010,9,22856.82,20317.17,2539.65,...,4,8888.76,13968.06,0,2,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ADM,US0394831020,19,31622.03,4992.95,26629.08,...,7,4992.95,26629.08,0,13,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AEHR,US00760J1088,2,47.22,23.61,23.61,...,1,0.00,47.22,0,2,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,MMM,US88579Y1010,1,9119.05,9119.05,0.00,...,0,0.00,9119.05,0,1,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,MRNA,US60770K1079,2,306.60,0.00,306.60,...,1,153.30,153.30,0,0,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,MRVL,US5738741041,3,2698.05,899.35,1798.70,...,1,449.68,2248.38,0,2,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,MSFT,US5949181045,97,2103658.67,1301232.17,802426.50,...,36,1301232.17,802426.50,60,37,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,MSTR,US5949724083,6,37769.36,18884.68,18884.68,...,3,18884.68,18884.68,3,3,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-22,2007-01-22 06:17:00.000,2007-01-22 06:17:03.000,1,AAPL,US0378331005,1,1.773400e+04,0.00,17734.00,...,1,0.00,17734.00,0,1,0.00,0.00,0,0,2007-01-22
1,2007-01-22,2007-01-22 06:18:00.000,2007-01-22 06:18:03.000,1,AAPL,US0378331005,1,4.431500e+04,0.00,44315.00,...,1,0.00,44315.00,0,1,0.00,0.00,0,0,2007-01-22
2,2007-01-22,2007-01-22 06:39:00.000,2007-01-22 06:39:03.000,1,AAPL,US0378331005,1,8.880000e+03,0.00,8880.00,...,0,0.00,8880.00,0,1,0.00,0.00,0,0,2007-01-22
3,2007-01-22,2007-01-22 07:36:00.000,2007-01-22 07:36:03.000,1,AAPL,US0378331005,2,8.890000e+04,88900.00,0.00,...,0,66675.00,22225.00,1,0,0.00,0.00,0,0,2007-01-22
4,2007-01-22,2007-01-22 07:38:00.000,2007-01-22 07:38:03.000,1,AAPL,US0378331005,1,4.446000e+04,44460.00,0.00,...,0,22230.00,22230.00,0,0,0.00,0.00,0,0,2007-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-01-22,2007-01-22 09:38:00.000,2007-01-22 09:38:03.000,0,AAPL,US0378331005,1158,1.947789e+07,9318436.92,9722123.72,...,218,370046.23,18670514.41,38,1120,269124.53,168202.83,16,10,2007-01-22
96,2007-01-22,2007-01-22 09:39:00.000,2007-01-22 09:39:03.000,0,AAPL,US0378331005,622,1.332265e+07,6318620.99,6682744.91,...,120,235609.60,12765756.31,21,601,214190.54,107095.27,10,5,2007-01-22
97,2007-01-22,2007-01-22 09:40:00.000,2007-01-22 09:40:03.000,0,AAPL,US0378331005,461,1.061632e+07,4225802.08,6321431.45,...,86,437548.99,10109684.54,22,439,69086.68,0.00,3,0,2007-01-22
98,2007-01-22,2007-01-22 09:41:00.000,2007-01-22 09:41:03.000,0,AAPL,US0378331005,1507,2.902788e+07,8687175.54,19974725.14,...,293,1463914.28,27197986.40,89,1418,250406.39,115572.18,13,6,2007-01-22
99,2007-01-22,2007-01-22 09:42:00.000,2007-01-22 09:42:03.000,0,AAPL,US0378331005,1260,2.806584e+07,13320138.35,14322489.90,...,245,10491279.53,17151348.71,482,778,245019.27,178195.83,11,8,2007-01-22

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [12]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_trial',key='AAPL', back_to='2024-01-01', up_to='2024-06-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_1min_trial", target_location="./data", asof_date='2026-01-13')

Starting native python replication for xtech_us_eqt_flow_r3k_with_isin_1min_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_with_isin_1min_trial. Downloaded 1 files.