In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [5]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_short_interest_factor_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2026-02-18 20:00:03.000,2026-02-18 19:46:00.000,2026-02-18,A,19416342.60,-556325.50,2.604588e+07,-1.675450e+05,-1.770149e+07,-1.724782e+05,-4.443758e+07,1.535270e+06,1.458653e+07,2.510381e+06,-8.546245e+07,3.604604e+06,4.358797e+08,2.120851e+06,2026-02-18
1,2026-02-18 20:00:03.000,2026-02-18 19:59:00.000,2026-02-18,AA,12482673.79,-94148.98,2.408307e+07,-4.030321e+06,6.708633e+07,-2.452871e+06,3.438998e+07,-7.722353e+05,6.581071e+07,-7.260878e+06,2.351782e+07,-9.157057e+06,1.352232e+08,1.278197e+07,2026-02-18
2,2026-02-18 20:00:03.000,2026-02-18 20:01:00.000,2026-02-18,AAA,21552.23,-44609.56,1.345179e+04,-5.651408e+04,6.437534e+04,-1.201134e+05,2.602027e+04,-1.211296e+05,6.845424e+05,-2.688529e+05,3.848266e+05,-3.930790e+05,9.306071e+05,-7.917403e+05,2026-02-18
3,2026-02-18 20:00:03.000,2026-02-18 20:01:00.000,2026-02-18,AAAA,8761.50,-30030.17,-2.002201e+05,-1.120513e+05,-3.675071e+05,-2.473496e+05,-1.109097e+06,-3.274215e+05,-1.824390e+06,-4.717034e+05,-2.514119e+06,-6.130009e+05,-9.392557e+06,-1.619292e+06,2026-02-18
4,2026-02-18 20:00:03.000,2026-02-18 20:01:00.000,2026-02-18,AAAC,-22562.81,21303.59,-1.555065e+05,5.741522e+03,-2.517451e+05,-5.456280e+03,4.479356e+04,1.995946e+05,-4.686538e+04,2.009406e+05,7.798048e+04,2.005459e+05,-2.801701e+06,1.994395e+05,2026-02-18
5,2026-02-18 20:00:03.000,2026-02-18 20:00:00.000,2026-02-18,AAAU,4825660.77,-2860725.67,1.072824e+06,-6.698960e+06,-4.917487e+06,-9.954435e+06,-3.031871e+06,-1.574921e+07,1.700113e+07,-1.905263e+07,2.875822e+07,-2.139998e+07,4.142920e+07,-4.677072e+07,2026-02-18
6,2026-02-18 20:00:03.000,2026-02-18 11:51:00.000,2026-02-18,AACB,-20.69,1641.49,-7.737250e+04,1.620298e+03,-1.285475e+05,1.582989e+03,-5.609513e+05,1.436136e+03,-2.109427e+06,1.411370e+03,-2.856003e+06,1.649413e+03,-1.403904e+07,-4.281065e+03,2026-02-18
7,2026-02-18 20:00:03.000,2026-02-18 15:37:00.000,2026-02-18,AACBR,17.87,0.00,7.100567e+02,1.973643e+02,1.137545e+03,-3.720634e+03,2.470213e+03,-3.482495e+03,8.097996e+03,-1.575255e+04,9.665482e+03,-1.575896e+04,4.824619e+04,-1.795408e+04,2026-02-18
8,2026-02-18 20:00:03.000,2026-02-18 16:11:00.000,2026-02-18,AACG,-1344.86,-2497.92,7.722226e+02,-3.874784e+03,2.975058e+03,-6.649959e+03,3.891833e+03,-1.294600e+04,-1.057648e+04,-2.117859e+04,-1.310019e+04,-3.196320e+04,-4.317744e+04,-5.414581e+04,2026-02-18
9,2026-02-18 20:00:03.000,2026-02-18 17:49:00.000,2026-02-18,AACIU,-24359573.15,-92687.15,-2.441807e+07,-9.832847e+04,-2.463378e+07,-1.062548e+05,-2.511923e+07,-1.367588e+05,-2.573618e+07,-1.626446e+05,-2.641257e+07,-1.904637e+05,-3.939177e+07,-5.489668e+05,2026-02-18

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_short_interest_factor_daily_v1_2_1', back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2024-01-24 20:00:03.000,2024-01-24 19:01:00.000,2024-01-24,A,-11966238.82,-166488.74,3.124196e+07,-5.604448e+05,9.610030e+07,-2.033625e+06,1.588953e+08,-4.186411e+05,3.192670e+08,1.735875e+06,3.914769e+08,1.644181e+06,1.097940e+09,1.272624e+07,2024-01-24
1,2024-01-24 20:00:03.000,2024-01-24 20:00:00.000,2024-01-24,AA,13061331.24,3309260.55,5.869312e+07,4.343967e+06,6.143698e+07,8.774404e+06,4.073746e+06,1.080472e+07,-4.508364e+07,1.776675e+07,-1.553669e+06,1.522261e+07,1.583268e+08,9.565214e+06,2024-01-24
2,2024-01-24 20:00:03.000,2024-01-24 20:01:00.000,2024-01-24,AAA,7438.13,3915.78,-3.630603e+04,1.593366e+03,-1.614954e+05,-3.190105e+03,-2.819962e+05,1.334182e+05,-2.759828e+05,1.838636e+05,-3.794538e+05,1.487653e+05,1.593455e+06,2.446005e+05,2024-01-24
3,2024-01-24 20:00:03.000,2024-01-24 20:01:00.000,2024-01-24,AAAU,-4562000.67,1493898.72,-1.604603e+07,1.099898e+06,-1.743682e+07,7.677061e+05,-2.350761e+07,3.483654e+06,-2.159594e+07,4.009300e+06,-1.590840e+07,3.679555e+06,-6.820348e+06,9.870164e+06,2024-01-24
4,2024-01-24 20:00:03.000,2024-01-24 18:42:00.000,2024-01-24,AACG,486.85,-627.79,-1.314263e+04,-2.191201e+03,-1.342922e+04,-2.438811e+03,-2.821076e+04,-1.090746e+04,-3.233302e+04,-1.417721e+04,-1.178671e+04,-1.633673e+04,-2.542130e+04,-1.779029e+04,2024-01-24
5,2024-01-24 20:00:03.000,2024-01-24 16:01:00.000,2024-01-24,AACI,970.18,-98.01,-1.002474e+05,1.221655e+04,-2.358936e+04,1.529538e+04,1.288753e+05,2.359512e+04,-6.585664e+04,3.195863e+04,4.312626e+05,4.161097e+04,4.104040e+06,1.217363e+05,2024-01-24
6,2024-01-24 20:00:03.000,2024-01-24 11:44:00.000,2024-01-24,AACIU,0.00,0.00,2.282826e+03,-1.202143e+02,3.772690e+03,-2.044757e+02,7.119049e+03,-4.317136e+02,1.063944e+04,-6.874235e+02,1.338398e+04,-9.797757e+02,-1.113874e+04,-1.645955e+02,2024-01-24
7,2024-01-24 20:00:03.000,2024-01-24 10:52:00.000,2024-01-24,AACIW,0.00,-0.53,1.145912e+03,-2.481299e+01,2.947958e+03,-4.135873e+01,3.011309e+03,2.251743e+01,2.911964e+03,-1.150483e+01,3.007673e+03,2.803958e+01,9.462441e+03,7.741575e+02,2024-01-24
8,2024-01-24 20:00:03.000,2024-01-24 19:01:00.000,2024-01-24,AACT,-1315155.06,-69842.19,2.364271e+06,-7.552586e+04,2.973664e+06,-7.937338e+04,-7.643598e+05,-1.037544e+05,-1.233363e+06,-1.185572e+05,1.695631e+06,-1.307692e+05,1.187280e+07,-1.324122e+05,2024-01-24
9,2024-01-24 20:00:03.000,2024-01-24 19:01:00.000,2024-01-24,AACT.WS,873.58,1680.52,1.504620e+04,1.434890e+03,3.059219e+04,1.255530e+03,-2.245250e+04,1.644027e+03,2.150227e+04,2.321160e+03,4.642967e+04,2.586572e+03,-7.010323e+04,8.230361e+03,2024-01-24

In [7]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_short_interest_factor_daily_v1_2_1", key='PSR', back_to='2020-10-29',up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2024-01-30 20:00:03.000,2024-01-30 20:01:00.000,2024-01-30,PSR,-10644.26,14376.33,-1.225589e+06,-56435.269470,-1.066001e+06,-44159.330384,-7.047026e+06,-163900.871874,-6.735012e+06,-213510.846866,-5.179820e+06,-205626.706402,-3.228570e+06,-1.154997e+06,2024-01-30
1,2024-01-19 20:00:03.000,2024-01-19 20:01:00.000,2024-01-19,PSR,-5925440.08,38922.52,-5.874967e+06,-99378.027087,-5.726647e+06,-172789.371973,-6.092945e+06,-325223.236956,-5.017065e+06,-71132.788119,-6.147233e+06,-205091.349353,-8.577666e+06,-1.892281e+06,2024-01-19
2,2024-01-05 20:00:03.000,2024-01-05 20:01:00.000,2024-01-05,PSR,-116530.95,25975.95,4.004888e+06,-82403.692727,9.621595e+05,233426.468484,-3.445973e+05,131951.185536,-3.418688e+06,133378.652786,-5.397119e+06,-453109.854475,-3.338481e+06,-1.536902e+06,2024-01-05
3,2024-01-26 20:00:03.000,2024-01-26 20:01:00.000,2024-01-26,PSR,-48609.33,-47133.72,1.371769e+05,-39986.189896,3.154021e+04,-57079.993374,-5.696935e+06,-233573.615377,-6.065495e+06,-389854.511729,-4.991476e+06,-139723.939859,-8.813162e+06,-1.285822e+06,2024-01-26
4,2023-12-27 20:00:03.000,2023-12-27 20:01:00.000,2023-12-27,PSR,115261.71,11277.35,-9.340148e+05,-29262.534791,-1.144363e+06,-138546.936248,-4.217308e+06,-65523.237780,-6.006798e+06,-813074.762427,-4.725529e+06,-631275.543055,-2.441816e+06,-1.756981e+06,2023-12-27
5,2023-12-29 20:00:03.000,2023-12-29 20:01:00.000,2023-12-29,PSR,-951371.33,29877.94,-9.148805e+05,61575.749658,-1.977191e+06,26171.797730,-4.934834e+06,-109003.486317,-7.070873e+06,-655744.858221,-6.773701e+06,-570589.343027,-4.719340e+06,-1.728946e+06,2023-12-29
6,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,2024-01-17,PSR,91262.09,-40471.95,2.432833e+05,-120498.615001,4.160988e+05,-100806.948824,4.041304e+06,-375322.469166,4.442234e+05,-25615.423537,-8.595081e+05,-200015.244533,-2.929754e+06,-1.851999e+06,2024-01-17
7,2024-01-29 20:00:03.000,2024-01-29 20:01:00.000,2024-01-29,PSR,-1256264.00,-6474.55,-1.184166e+06,-51855.010724,-1.039706e+06,-46259.959855,-7.111356e+06,-187542.509159,-7.179030e+06,-420830.041868,-6.147039e+06,-186938.587518,-1.001993e+07,-1.177630e+06,2024-01-29
8,2023-12-26 20:00:03.000,2023-12-26 20:01:00.000,2023-12-26,PSR,-641521.52,-1939.38,-1.288844e+06,-140352.163562,-1.433358e+06,-126276.491249,-4.485383e+06,-693109.431258,-6.352221e+06,-699071.410870,-3.941405e+06,-633123.263360,-2.645415e+06,-1.749702e+06,2023-12-26
9,2024-01-04 20:00:03.000,2024-01-04 20:01:00.000,2024-01-04,PSR,-388394.76,-24487.91,2.046769e+06,191448.961936,1.004063e+06,249489.968367,-1.986616e+05,110692.345244,-3.332043e+06,183411.229052,-5.184521e+06,-564647.802644,-3.148860e+06,-1.541536e+06,2024-01-04

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_short_interest_factor_daily_v1_2_1", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_short_interest_factor_daily_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_eqt_short_interest_factor_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_short_interest_factor_daily_v1_2_1", target_location="./data")