In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [ ]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_short_interest_factor_1min_v1_2", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2026-05-07 09:31:03.000,2026-05-07 09:31:00.000,2026-05-07,FSZ,-82.79,0.00,-82.79,1319.97,-42666.66,-40.16,-42666.66,-40.16,-198851.38,1948.04,2026-05-07
1,2026-05-07 09:44:03.000,2026-05-07 09:44:00.000,2026-05-07,FSZ,0.00,82.71,-82.79,1402.68,-42666.66,42.55,-42666.66,42.55,-198690.44,2030.75,2026-05-07
2,2026-05-07 09:46:03.000,2026-05-07 09:46:00.000,2026-05-07,FSZ,-82.65,0.00,-165.44,1402.68,-42749.31,42.55,-42749.31,42.55,-198773.09,2030.75,2026-05-07
3,2026-05-07 10:17:03.000,2026-05-07 10:17:00.000,2026-05-07,FSZ,-82.64,0.00,-248.08,1402.68,-42831.95,42.55,-42831.95,42.55,-198775.09,2030.75,2026-05-07
4,2026-05-07 11:21:03.000,2026-05-07 11:21:00.000,2026-05-07,FSZ,0.00,0.00,-248.08,1402.68,-42831.95,42.55,-42831.95,42.55,-198694.61,1950.27,2026-05-07
5,2026-05-07 11:23:03.000,2026-05-07 11:23:00.000,2026-05-07,FSZ,0.00,0.00,-248.08,1402.68,-42831.95,42.55,-42831.95,42.55,-198694.61,1950.27,2026-05-07
6,2026-05-07 16:05:03.000,2026-05-07 16:05:00.000,2026-05-07,FSZ,0.00,-81.82,-248.08,0.89,-43716.50,1240.64,-42831.95,-39.27,-198694.61,4277.83,2026-05-07
7,2026-05-07 04:01:03.000,2026-05-07 04:01:00.000,2026-05-07,FTCI,-11042.22,290.58,-240196.49,-8615.24,-4506883.36,105704.83,-4506997.29,105704.83,-4863814.55,102740.91,2026-05-07
8,2026-05-07 04:02:03.000,2026-05-07 04:02:00.000,2026-05-07,FTCI,-520.86,-520.85,-240717.35,-9136.09,-4507073.63,105183.98,-4507518.15,105183.98,-4864335.41,102220.06,2026-05-07
9,2026-05-07 04:04:03.000,2026-05-07 04:04:00.000,2026-05-07,FTCI,8.04,0.00,-240709.31,-9136.09,-4509406.58,103424.82,-4507510.11,105183.98,-4864327.37,102220.06,2026-05-07

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_eqt_short_interest_factor_1min_v1_2', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2021-01-26 05:19:03.000,2021-01-26 05:19:00.000,2021-01-26,A,0.00,0.00,45882653.04,186276.38,45882653.04,186276.38,1.096022e+08,-608838.86,2.604846e+08,-911463.85,2021-01-26
1,2021-01-26 05:50:03.000,2021-01-26 05:50:00.000,2021-01-26,A,126.72,0.00,45882779.76,186276.38,45882779.76,186276.38,1.096023e+08,-608838.86,2.604848e+08,-911463.85,2021-01-26
2,2021-01-26 07:21:03.000,2021-01-26 07:21:00.000,2021-01-26,A,-125.48,0.00,45889369.26,186276.38,45882654.28,186276.38,1.096015e+08,-608838.86,2.604846e+08,-911463.85,2021-01-26
3,2021-01-26 08:27:03.000,2021-01-26 08:27:00.000,2021-01-26,A,-251.34,0.00,45882622.05,186276.38,45882402.94,186276.38,1.096013e+08,-608838.86,2.604844e+08,-911463.85,2021-01-26
4,2021-01-26 09:31:03.000,2021-01-26 09:31:00.000,2021-01-26,A,-2783822.30,0.00,44451580.07,186276.38,43098580.64,186276.38,1.028602e+08,-633457.97,2.577006e+08,-911463.85,2021-01-26
5,2021-01-26 09:32:03.000,2021-01-26 09:32:00.000,2021-01-26,A,-586380.72,0.00,42319362.85,186276.38,42512199.92,186276.38,1.020503e+08,-633457.97,2.571142e+08,-911463.85,2021-01-26
6,2021-01-26 09:33:03.000,2021-01-26 09:33:00.000,2021-01-26,A,-961721.26,-8510.81,41429361.12,177765.57,41550478.66,177765.57,1.004801e+08,-634637.17,2.561524e+08,-919974.66,2021-01-26
7,2021-01-26 09:34:03.000,2021-01-26 09:34:00.000,2021-01-26,A,-117731.88,0.00,41390951.23,183053.70,41432746.78,177765.57,9.548948e+07,-730182.97,2.560347e+08,-919974.66,2021-01-26
8,2021-01-26 09:35:03.000,2021-01-26 09:35:00.000,2021-01-26,A,-555301.51,-8413.66,41073205.87,162457.67,40877445.27,169351.91,9.448081e+07,-721488.24,2.554794e+08,-928388.32,2021-01-26
9,2021-01-26 09:36:03.000,2021-01-26 09:36:00.000,2021-01-26,A,-83130.77,11875.82,41094106.24,174333.49,40794314.50,181227.73,9.364938e+07,-709612.42,2.553963e+08,-916512.50,2021-01-26

In [ ]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_short_interest_factor_1min_v1_2", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2026-04-29 09:31:03.000,2026-04-29 09:31:00.000,2026-04-29,PSR,-99.89,0.00,10990.57,7129.08,-105140.64,6428.06,-94747.21,5977.72,-44488.94,17460.25,2026-04-29
1,2026-04-29 09:36:03.000,2026-04-29 09:36:00.000,2026-04-29,PSR,300.72,0.00,11291.29,7129.08,-104839.92,6428.06,-94446.49,5977.72,-44188.22,17460.25,2026-04-29
2,2026-04-29 09:46:03.000,2026-04-29 09:46:00.000,2026-04-29,PSR,100.02,0.00,11690.93,7129.08,-104739.90,6428.06,-93947.92,5977.72,-44088.20,17460.25,2026-04-29
3,2026-04-29 10:04:03.000,2026-04-29 10:04:00.000,2026-04-29,PSR,0.00,100.20,11790.44,7229.28,-104739.90,6528.26,-93947.92,6077.92,-44088.20,17560.45,2026-04-29
4,2026-04-29 10:08:03.000,2026-04-29 10:08:00.000,2026-04-29,PSR,0.00,100.20,11790.44,7230.26,-104739.90,6628.46,-93947.92,6077.76,-44088.20,17660.65,2026-04-29
5,2026-04-29 10:17:03.000,2026-04-29 10:17:00.000,2026-04-29,PSR,4912.25,4912.25,16702.69,12142.51,-99827.65,11540.71,-89035.67,10889.57,-39175.95,22572.90,2026-04-29
6,2026-04-29 10:30:03.000,2026-04-29 10:30:00.000,2026-04-29,PSR,23609.02,0.00,40311.71,15220.82,-76218.63,11540.71,-65426.65,10889.57,-15566.93,22572.90,2026-04-29
7,2026-04-29 10:54:03.000,2026-04-29 10:54:00.000,2026-04-29,PSR,-2895.65,0.00,37416.06,15220.82,-79114.28,11540.71,-68322.30,10889.57,-18462.58,22572.90,2026-04-29
8,2026-04-29 10:57:03.000,2026-04-29 10:57:00.000,2026-04-29,PSR,-5793.04,0.00,31623.02,14220.32,-84907.32,11540.71,-74115.34,10889.57,-24255.62,22572.90,2026-04-29
9,2026-04-29 11:55:03.000,2026-04-29 11:55:00.000,2026-04-29,PSR,-9060.87,0.00,27160.77,12320.32,-93968.19,11540.71,-83678.88,10889.57,-33316.49,22572.90,2026-04-29

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_eqt_short_interest_factor_1min_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_eqt_short_interest_factor_1min_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_short_interest_factor_1min_v1_2. Downloaded 1 files.