In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [ ]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_short_interest_factor_daily_v1_2", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2025-12-11 20:00:03.000,2025-12-11 19:57:00.000,2025-12-11,AA,2.561927e+08,-314121.09,3.192864e+08,-9.151821e+05,3.711133e+08,-4.952289e+05,1.959829e+08,-2.194931e+06,6.603323e+08,-2.025366e+06,4.238062e+08,-5.726467e+06,8.535050e+08,-3.957872e+07,2025-12-11
1,2025-12-11 20:00:03.000,2025-12-11 15:59:00.000,2025-12-11,AACBR,7.760000e+00,-7.75,-2.478364e+02,1.195380e+02,-5.269920e+02,1.891840e+02,-8.179481e+03,9.191391e+01,-6.840311e+03,-1.943711e+03,-7.269841e+03,-2.106892e+03,-1.238482e+03,2.415721e+03,2025-12-11
2,2025-12-11 20:00:03.000,2025-12-11 16:11:00.000,2025-12-11,AAME,-3.007340e+03,4423.54,-3.663913e+03,7.293228e+03,-2.625852e+03,9.189482e+03,-2.292465e+03,7.947750e+03,-1.675629e+03,8.441158e+03,-1.047311e+05,-1.998209e+04,-8.471244e+05,1.905583e+04,2025-12-11
3,2025-12-11 20:00:03.000,2025-12-11 19:59:00.000,2025-12-11,AAOI,6.113322e+07,-146043.09,1.552682e+08,-1.078584e+06,2.852413e+08,-1.745972e+06,2.888271e+08,-1.679522e+06,5.404330e+08,-2.831978e+06,4.527470e+08,-8.907352e+05,2.984083e+08,7.614010e+06,2025-12-11
4,2025-12-11 20:00:03.000,2025-12-11 19:01:00.000,2025-12-11,AAT,-4.077854e+04,75426.86,1.311634e+07,8.673056e+04,8.656489e+06,1.905119e+05,3.779667e+06,2.478682e+05,3.925110e+06,2.511094e+05,-2.537218e+06,3.017245e+05,5.753149e+06,8.011353e+04,2025-12-11
5,2025-12-11 20:00:03.000,2025-12-11 20:01:00.000,2025-12-11,AAUM,0.000000e+00,-97.59,1.388879e+03,-7.085137e+02,-8.583450e+03,-1.138508e+03,-7.170280e+03,-7.751111e+02,-5.499044e+03,-1.894753e+03,6.475724e+03,-3.106087e+03,3.860428e+04,-1.481145e+04,2025-12-11
6,2025-12-11 20:00:03.000,2025-12-11 19:01:00.000,2025-12-11,ABRpD,3.477925e+04,-35475.77,1.153525e+05,-3.098851e+04,2.360196e+05,-9.876897e+04,2.342421e+05,-8.790799e+04,4.000685e+05,-3.595955e+04,2.291127e+05,-2.045193e+04,8.770647e+05,7.790093e+04,2025-12-11
7,2025-12-11 20:00:03.000,2025-12-11 17:57:00.000,2025-12-11,ACDC,-3.162400e+03,13865.05,9.294484e+04,-1.905797e+04,2.401226e+05,-1.277458e+05,5.911616e+06,-1.369411e+05,6.037028e+06,-1.153320e+05,2.468839e+06,-3.018991e+05,1.511320e+07,-1.610506e+06,2025-12-11
8,2025-12-11 20:00:03.000,2025-12-11 20:01:00.000,2025-12-11,ACEI,-5.995969e+04,40175.92,-5.400326e+04,-2.671375e+04,-3.269868e+05,-6.002172e+04,1.336911e+04,1.534394e+05,2.250665e+05,1.781195e+05,1.677886e+05,1.093200e+05,1.797602e+06,-5.911311e+05,2025-12-11
9,2025-12-11 20:00:03.000,2025-12-11 16:11:00.000,2025-12-11,ACGLN,1.503200e+04,-101349.69,3.414984e+05,-1.670187e+05,5.046088e+05,-1.411076e+05,1.029647e+06,-1.139641e+04,1.687717e+06,-2.477442e+04,2.092712e+06,-9.001892e+03,5.084642e+06,-1.178768e+05,2025-12-11

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_eqt_short_interest_factor_daily_v1_2', back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2024-01-18 20:00:03.000,2024-01-18 19:10:00.000,2024-01-18,A,1.244689e+08,183784.73,9.960375e+07,-8.913950e+05,2.258291e+08,-6.630723e+05,2.840375e+08,-7.864624e+05,9.987645e+06,-6.155830e+05,1.621436e+08,-3.960758e+06,-4.715201e+08,-3.410179e+06,2024-01-18
1,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18,AADI,8.191070e+03,-2355.50,6.087371e+05,-5.555890e+03,1.008475e+06,1.056767e+02,7.980008e+05,8.334231e+04,2.463318e+06,1.763362e+05,5.760725e+06,2.816279e+05,-3.256155e+06,5.631354e+05,2024-01-18
2,2024-01-18 20:00:03.000,2024-01-18 15:59:00.000,2024-01-18,ABLLL,-1.014300e+04,0.00,-6.921292e+04,4.611732e+04,-9.208509e+04,4.980281e+04,-9.138931e+04,8.573847e+04,-1.225064e+05,1.035716e+05,-1.319296e+05,8.382715e+04,-7.388152e+04,8.544342e+04,2024-01-18
3,2024-01-18 20:00:03.000,2024-01-18 16:01:00.000,2024-01-18,ABLLW,3.975300e+02,640.05,8.304930e+02,2.287425e+03,-3.106944e+03,7.727019e+03,-2.089017e+04,1.213040e+04,-2.526286e+04,1.317072e+03,-2.585790e+04,-1.249835e+02,-1.102064e+04,2.251470e+04,2024-01-18
4,2024-01-18 20:00:03.000,2024-01-18 19:01:00.000,2024-01-18,ABRpF,-2.272442e+05,-38268.07,-5.008032e+05,-4.738598e+04,-4.425348e+05,-3.299653e+04,-1.741486e+06,1.160609e+04,-2.238970e+06,-4.611508e+04,-2.032708e+06,-1.578307e+05,-2.332838e+06,-1.245170e+05,2024-01-18
5,2024-01-18 20:00:03.000,2024-01-18 19:01:00.000,2024-01-18,ACCO,5.411260e+03,10952.59,-1.481722e+06,-3.352175e+04,-1.154972e+06,-9.085357e+04,5.406087e+05,-1.457288e+05,1.449126e+07,1.378128e+05,1.496015e+07,1.400783e+05,1.073804e+07,-2.091266e+05,2024-01-18
6,2024-01-18 20:00:03.000,2024-01-18 20:01:00.000,2024-01-18,ACES,-2.113944e+05,-83295.51,-5.751242e+06,9.613395e+05,-9.903120e+06,1.699999e+06,-3.027093e+07,3.416504e+06,-3.760238e+07,5.285234e+06,-2.969984e+07,7.212752e+06,1.295729e+07,-1.204364e+06,2024-01-18
7,2024-01-18 20:00:03.000,2024-01-18 16:01:00.000,2024-01-18,ACHC,4.625669e+06,-92798.00,1.472269e+07,-2.695988e+05,3.303264e+07,-1.801344e+05,9.426698e+07,-2.818556e+05,9.190398e+07,-2.377644e+05,1.407417e+08,-2.551198e+05,1.194416e+08,1.110106e+06,2024-01-18
8,2024-01-18 20:00:03.000,2024-01-18 19:59:00.000,2024-01-18,ACHR,-1.981498e+06,404793.65,-1.547596e+07,-8.065629e+05,-1.562986e+07,-1.396202e+06,-1.593270e+07,-3.242341e+06,-5.844360e+07,-4.298520e+06,-5.920818e+07,-6.380990e+06,-7.770930e+07,-1.339129e+07,2024-01-18
9,2024-01-18 20:00:03.000,2024-01-18 19:29:00.000,2024-01-18,ACN,2.176923e+08,-1118265.80,4.157050e+08,-3.153699e+06,5.516216e+08,-5.014273e+06,1.033659e+09,-6.996968e+06,1.027382e+08,-1.039959e+07,5.538300e+08,-1.645228e+07,3.757412e+09,-5.915441e+07,2024-01-18

In [ ]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_short_interest_factor_daily_v1_2", key='PSR', back_to='2020-10-29',up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,15day_institutional_short_interest_factor,15day_retail_short_interest_factor,20day_institutional_short_interest_factor,20day_retail_short_interest_factor,60day_institutional_short_interest_factor,60day_retail_short_interest_factor,asof_date
0,2022-10-13 20:00:03.000,2022-10-13 20:01:00.000,2022-10-13,PSR,13869.81,-115661.50,-7.493760e+04,-189385.584989,-7.760232e+05,-195841.203118,-1.980173e+06,109037.865893,-3.827454e+06,390946.422405,-4.637548e+06,315283.791636,2.547246e+06,6.458902e+05,2022-10-13
1,2022-08-30 20:00:03.000,2022-08-30 20:01:00.000,2022-08-30,PSR,-909714.14,47723.48,-1.014983e+06,72837.106774,-2.699265e+05,-55256.188653,4.147524e+06,1584.833156,8.281277e+06,317477.526927,7.822294e+06,308110.522516,3.860994e+06,8.772894e+05,2022-08-30
2,2022-05-03 20:00:03.000,2022-05-03 20:01:00.000,2022-05-03,PSR,-155880.97,-19577.57,-6.215867e+06,-146588.204308,-5.943303e+06,-428974.358537,-6.622549e+06,-590763.488141,-5.040319e+06,-574932.352901,-4.944967e+06,-566503.574778,1.273668e+06,-9.487360e+05,2022-05-03
3,2022-09-19 20:00:03.000,2022-09-19 20:01:00.000,2022-09-19,PSR,35117.03,-49426.40,1.265531e+05,-109682.880968,-1.099309e+05,-78254.063942,3.964651e+05,27396.480796,-3.087972e+06,73994.480277,-3.843624e+06,-24500.867420,3.066643e+06,9.227372e+05,2022-09-19
4,2022-04-27 20:00:03.000,2022-04-27 20:01:00.000,2022-04-27,PSR,432070.66,-215776.05,4.094342e+05,-177186.947351,-5.110902e+05,-238511.119419,3.409975e+06,-407892.822176,1.659841e+06,-341308.154261,7.276323e+06,-545815.558105,8.903245e+06,-3.654275e+05,2022-04-27
5,2022-10-06 20:00:03.000,2022-10-06 20:01:00.000,2022-10-06,PSR,-267498.56,96070.86,-3.859032e+05,156430.118341,-1.217353e+06,305703.048088,-3.077916e+06,588315.343698,-3.900385e+06,513285.905815,-4.145758e+06,630208.956195,3.379413e+06,1.480176e+06,2022-10-06
6,2022-09-15 20:00:03.000,2022-09-15 20:01:00.000,2022-09-15,PSR,-89598.75,-5816.82,-3.406626e+05,19643.934883,-1.451186e+05,132252.491785,-4.970561e+05,72599.828074,-3.549566e+06,51067.413032,1.216667e+06,105368.766704,3.759596e+06,9.376319e+05,2022-09-15
7,2022-08-23 20:00:03.000,2022-08-23 20:01:00.000,2022-08-23,PSR,-1036337.17,5245.83,4.139534e+06,50934.546769,4.387132e+06,50340.681462,8.487466e+06,359501.407901,7.993734e+06,343222.016425,1.083315e+07,431059.647431,9.596532e+06,1.377629e+06,2022-08-23
8,2022-08-26 20:00:03.000,2022-08-26 20:01:00.000,2022-08-26,PSR,-170210.87,-19017.72,5.470507e+05,-153417.207809,-6.846596e+05,-98482.302219,8.906873e+06,276809.150484,8.862790e+06,201372.565028,8.481679e+06,265046.752616,5.118314e+06,8.479381e+05,2022-08-26
9,2022-06-15 20:00:03.000,2022-06-15 20:01:00.000,2022-06-15,PSR,404215.44,-75538.31,4.055873e+05,-103705.860079,1.504247e+05,-120092.352176,6.927001e+05,-59804.733564,5.866189e+06,239985.264195,5.620317e+06,90477.430218,5.273578e+06,-7.320099e+05,2022-06-15

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_eqt_short_interest_factor_daily_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_eqt_short_interest_factor_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_short_interest_factor_daily_v1_2. Downloaded 1 files.