In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [8]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_short_interest_factor_1min_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2026-01-21 16:11:03.000,2026-01-21 16:11:00.000,2026-01-21,AAAC,0.00,0,0.00,0.00,120.66,0.00,120.66,0.00,-9460.69,2.013000e+01,2026-01-21
1,2026-01-21 18:31:03.000,2026-01-21 18:31:00.000,2026-01-21,AAAC,0.00,0,0.00,0.00,120.66,0.00,120.66,0.00,-9460.69,2.013000e+01,2026-01-21
2,2026-01-21 20:01:03.000,2026-01-21 20:01:00.000,2026-01-21,AAAC,0.00,0,0.00,0.00,120.66,0.00,120.66,0.00,-9460.69,2.013000e+01,2026-01-21
3,2026-01-21 04:01:03.000,2026-01-21 04:01:00.000,2026-01-21,AAL,-14.96,0,-16770164.76,24122058.86,-16706779.83,24122058.86,-24717139.59,37982535.22,-46621825.89,1.675085e+08,2026-01-21
4,2026-01-21 04:04:03.000,2026-01-21 04:04:00.000,2026-01-21,AAL,0.00,0,-16772561.38,24122058.86,-16706779.83,24122058.86,-24717139.59,37982535.22,-46621825.89,1.675085e+08,2026-01-21
5,2026-01-21 04:06:03.000,2026-01-21 04:06:00.000,2026-01-21,AAL,-1652.20,0,-16774062.68,24122058.86,-16708432.03,24122058.86,-24718791.79,37982535.22,-46623478.09,1.675085e+08,2026-01-21
6,2026-01-21 04:08:03.000,2026-01-21 04:08:00.000,2026-01-21,AAL,-5211.94,0,-16776411.86,24122058.86,-16713643.97,24122058.86,-24724003.73,37982535.22,-46628690.03,1.675085e+08,2026-01-21
7,2026-01-21 04:09:03.000,2026-01-21 04:09:00.000,2026-01-21,AAL,-15.02,0,-16759703.23,24122058.86,-16713658.99,24122058.86,-24724018.75,37982535.22,-46628705.05,1.675085e+08,2026-01-21
8,2026-01-21 04:14:03.000,2026-01-21 04:14:00.000,2026-01-21,AAL,-570.76,0,-16756815.59,24122058.86,-16714229.75,24122058.86,-24716410.07,37982535.22,-46629275.81,1.675085e+08,2026-01-21
9,2026-01-21 04:18:03.000,2026-01-21 04:18:00.000,2026-01-21,AAL,1503.00,0,-16755312.59,24122058.86,-16712726.75,24122058.86,-24714922.83,37982535.22,-46627772.81,1.675085e+08,2026-01-21

In [9]:
df = Unifier.get_dataframe(name='xtech_us_eqt_short_interest_factor_1min_v1_2_1', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2021-01-25 09:31:03.000,2021-01-25 09:31:00.000,2021-01-25,AAA,25.17,0.00,25.17,0.00,34115.49,2089.13,-8697.28,-44088.33,42253.93,19159.42,2021-01-25
1,2021-01-25 10:57:03.000,2021-01-25 10:57:00.000,2021-01-25,AAA,-100.64,0.00,-75.47,0.00,34014.85,2089.13,-8797.92,-44088.33,4946.07,19461.13,2021-01-25
2,2021-01-25 10:58:03.000,2021-01-25 10:58:00.000,2021-01-25,AAA,0.00,-50.32,-75.47,-50.32,-125.79,-478.09,-8772.78,-44138.65,4920.93,19385.67,2021-01-25
3,2021-01-25 11:09:03.000,2021-01-25 11:09:00.000,2021-01-25,AAA,-25.16,0.00,-100.63,-50.32,-150.95,-478.09,-8797.94,-44138.65,4392.97,19385.67,2021-01-25
4,2021-01-25 11:31:03.000,2021-01-25 11:31:00.000,2021-01-25,AAA,-75.45,0.00,-176.08,-50.32,-226.40,-478.09,-8873.39,-44138.65,4317.52,19385.67,2021-01-25
5,2021-01-25 12:52:03.000,2021-01-25 12:52:00.000,2021-01-25,AAA,0.00,-25.15,-176.08,-75.47,-226.40,-503.24,-8873.39,-44163.80,2397.62,6772.05,2021-01-25
6,2021-01-25 14:30:03.000,2021-01-25 14:30:00.000,2021-01-25,AAA,25.17,0.00,-150.91,-75.47,-150.91,-75.47,-9527.27,-44163.80,1417.19,6772.05,2021-01-25
7,2021-01-25 15:44:03.000,2021-01-25 15:44:00.000,2021-01-25,AAA,-804.96,0.00,-955.87,-75.47,-955.87,-75.47,-10357.38,-44163.80,-393.37,6772.05,2021-01-25
8,2021-01-25 15:45:03.000,2021-01-25 15:45:00.000,2021-01-25,AAA,-25.16,0.00,-981.03,-75.47,-981.03,-75.47,-10382.54,-44163.80,-418.53,6772.05,2021-01-25
9,2021-01-25 16:11:03.000,2021-01-25 16:11:00.000,2021-01-25,AAA,0.00,0.00,-981.03,-75.47,-981.03,-75.47,-10382.54,-44163.80,-921.33,6772.05,2021-01-25

In [10]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_short_interest_factor_1min_v1_2_1", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,asof_datetime,timestamp,date,ticker,1min_institutional_short_interest_factor,1min_retail_short_interest_factor,1day_institutional_short_interest_factor,1day_retail_short_interest_factor,3day_institutional_short_interest_factor,3day_retail_short_interest_factor,5day_institutional_short_interest_factor,5day_retail_short_interest_factor,10day_institutional_short_interest_factor,10day_retail_short_interest_factor,asof_date
0,2026-01-28 09:31:03.000,2026-01-28 09:31:00.000,2026-01-28,PSR,-733.52,0.00,-523337.85,10901.58,-492231.77,42790.84,-498773.23,52323.60,-661404.05,61303.34,2026-01-28
1,2026-01-28 09:37:03.000,2026-01-28 09:37:00.000,2026-01-28,PSR,0.00,92.08,-523337.85,10809.83,-492231.77,42882.92,-498773.23,52598.28,-661404.05,61395.42,2026-01-28
2,2026-01-28 09:38:03.000,2026-01-28 09:38:00.000,2026-01-28,PSR,-91800.00,0.00,-615137.85,10809.83,-584031.77,42882.92,-590573.23,52598.28,-753204.05,61395.42,2026-01-28
3,2026-01-28 09:48:03.000,2026-01-28 09:48:00.000,2026-01-28,PSR,0.00,0.00,-614405.21,10809.83,-584031.77,42882.92,-590481.83,52598.28,-753204.05,61395.42,2026-01-28
4,2026-01-28 10:09:03.000,2026-01-28 10:09:00.000,2026-01-28,PSR,-4869.63,0.00,-619274.84,10809.83,-588901.40,42882.92,-595351.47,52872.59,-758073.68,61395.42,2026-01-28
5,2026-01-28 10:24:03.000,2026-01-28 10:24:00.000,2026-01-28,PSR,91.88,0.00,-619274.90,10809.83,-588809.52,42882.92,-595259.59,48115.64,-757981.80,61395.42,2026-01-28
6,2026-01-28 10:47:03.000,2026-01-28 10:47:00.000,2026-01-28,PSR,276.09,0.00,-618998.81,10809.83,-588533.43,42882.92,-594983.50,48206.97,-757705.71,61395.42,2026-01-28
7,2026-01-28 11:16:03.000,2026-01-28 11:16:00.000,2026-01-28,PSR,0.00,-7628.03,-618998.81,3181.80,-588533.43,35254.89,-595259.03,38014.99,-757705.71,53767.39,2026-01-28
8,2026-01-28 11:54:03.000,2026-01-28 11:54:00.000,2026-01-28,PSR,183.68,-183.68,-618815.13,5014.03,-588349.75,35071.21,-595715.81,37831.31,-757522.03,53583.71,2026-01-28
9,2026-01-28 12:09:03.000,2026-01-28 12:09:00.000,2026-01-28,PSR,0.00,-91.84,-618815.13,4922.19,-588349.75,34979.37,-604879.29,37739.47,-757522.03,53491.87,2026-01-28

## Download data file for a specific date using asof_date

In [11]:
Unifier.replicate(name="xtech_us_eqt_short_interest_factor_1min_v1_2_1", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_short_interest_factor_1min_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_eqt_short_interest_factor_1min_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_short_interest_factor_1min_v1_2_1", target_location="./data")