In [3]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [4]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Futures Reference Table

In [6]:
df =  Unifier.get_dataframe(name="lseg_futures_flow_forecasts_ident")
display(df)

,identifier,sector,name,contract_multiplier,asof_date
0,BTC,Crypto,Bitcoin,5.0,2026-06-09
1,6A,Currency,Australian Dollar,100000.0,2026-06-09
2,CRA,Rates,3-Month CORRA,2500.0,2026-06-09
3,ZW,Agriculture,Chicago SRW Wheat,50.0,2026-06-09
4,LFT,Equities,FTSE 100,10.0,2026-06-09
...,...,...,...,...,...
79,YM,Equities,E-mini Dow,5.0,2026-06-09
80,6E,Currency,Euro FX,125000.0,2026-06-09
81,CGB,Treasuries,Canadian Govt Bond,1000.0,2026-06-09
82,ZB,Treasuries,US 30-Year Bond,1000.0,2026-06-09
83,FOAT,Treasuries,Euro-OAT,1000.0,2026-06-09

## LSEG Global Futures Flow Forecasts

In [7]:
df =  Unifier.get_dataframe(name="lseg_futures_flow_forecasts_scenarios",  back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,scenario_type,scenario_label,shock_price,buy_contracts_sensitivity_1,buy_contracts_sensitivity_2,buy_contracts_sensitivity_3,buy_contracts_sensitivity_4,sell_contracts_sensitivity_1,sell_contracts_sensitivity_2,sell_contracts_sensitivity_3,sell_contracts_sensitivity_4,asof_date
0,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,trigger,sell_trigger_1,2766.0,0,0,0,0,8081,9236,9236,12685,2025-11-28
1,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,reference,ref_-2pct,2755.0,0,0,0,0,8990,10275,10275,14112,2025-11-28
2,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,reference,ref_-3pct,2726.5,0,0,0,0,11837,13529,13529,18581,2025-11-28
3,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,reference,ref_-4pct,2698.5,0,0,0,0,14985,17127,17127,23524,2025-11-28
4,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,trigger,sell_trigger_2_pre,2672.5,0,0,0,0,17955,20520,20520,28184,2025-11-28
5,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,trigger,sell_trigger_2,2672.0,0,0,0,0,23364,26702,26702,36675,2025-11-28
6,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,reference,ref_-5pct,2670.5,0,0,0,0,23517,26876,26876,36915,2025-11-28
7,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,trigger,sell_trigger_3_pre,2623.5,0,0,0,0,28027,32030,32030,43994,2025-11-28
8,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,trigger,sell_trigger_3,2623.0,0,0,0,0,32893,37591,37591,51633,2025-11-28
9,2025-11-28 07:00:00.000,2025-11-27 00:00:00.000,AHD,None,None,managed_money,trigger,sell_trigger_4_pre,2608.5,0,0,0,0,34008,38866,38866,53384,2025-11-28

In [8]:
df = Unifier.get_dataframe(name="lseg_futures_flow_forecasts_scenarios", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,scenario_type,scenario_label,shock_price,buy_contracts_sensitivity_1,buy_contracts_sensitivity_2,buy_contracts_sensitivity_3,buy_contracts_sensitivity_4,sell_contracts_sensitivity_1,sell_contracts_sensitivity_2,sell_contracts_sensitivity_3,sell_contracts_sensitivity_4,asof_date
0,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,reference,ref_-2pct,0.64600,0,None,None,None,1296,None,None,None,2024-01-26
1,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,current,current,0.65915,0,None,None,None,453,None,None,None,2024-01-26
2,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,trigger,flow_flip,0.66590,0,None,None,None,2,None,None,None,2024-01-26
3,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,reference,ref_+2pct,0.67230,381,None,None,None,0,None,None,None,2024-01-26
4,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,trigger,week_flip,0.67480,529,None,None,None,0,None,None,None,2024-01-26
5,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,reference,ref_+5pct,0.69210,1524,None,None,None,0,None,None,None,2024-01-26
6,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,reference,ref_+10pct,0.72510,3222,None,None,None,0,None,None,None,2024-01-26
7,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,trigger,heavy_buy,0.73950,3873,None,None,None,0,None,None,None,2024-01-26
8,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,nonreportable,reference,ref_+15pct,0.75800,4636,None,None,None,0,None,None,None,2024-01-26
9,2024-01-26 07:00:00.000,2024-01-25 00:00:00.000,6A,202403,False,other_reportables,reference,ref_+15pct,0.75800,0,None,None,None,1030,None,None,None,2024-01-26

In [9]:
df =  Unifier.get_dataframe(name="lseg_futures_flow_forecasts_scenarios", key="6A", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,scenario_type,scenario_label,shock_price,buy_contracts_sensitivity_1,buy_contracts_sensitivity_2,buy_contracts_sensitivity_3,buy_contracts_sensitivity_4,sell_contracts_sensitivity_1,sell_contracts_sensitivity_2,sell_contracts_sensitivity_3,sell_contracts_sensitivity_4,asof_date
0,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,trigger,sell_trigger_3_pre,0.6567,0,0,0,0,4792,5478,11997,14713,2026-01-01
1,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,trigger,sell_trigger_2,0.6604,0,0,0,0,3950,4514,9887,12126,2026-01-01
2,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,trigger,sell_trigger_2_pre,0.6605,0,0,0,0,2975,3400,7446,9132,2026-01-01
3,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,reference,ref_-1pct,0.6606,0,0,0,0,2952,3374,7390,9064,2026-01-01
4,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,trigger,sell_trigger_1,0.6657,115,131,287,353,0,0,0,0,2026-01-01
5,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,trigger,sell_trigger_1_pre,0.6658,124,141,310,381,0,0,0,0,2026-01-01
6,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,current,current,0.6673,0,0,0,0,0,0,0,0,2026-01-01
7,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,reference,ref_+1pct,0.6740,0,0,0,0,704,805,1762,2161,2026-01-01
8,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,reference,ref_+2pct,0.6806,0,0,0,0,2646,3024,6624,8123,2026-01-01
9,2026-01-01 07:00:00.000,2025-12-31 00:00:00.000,6A,202603,False,managed_money,reference,ref_+3pct,0.6873,0,0,0,0,4608,5267,11535,14147,2026-01-01