In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Futures Reference Table

In [9]:
df =  Unifier.get_dataframe(name="lseg_futures_flow_forecasts_ident")
display(df)

,identifier,sector,name,contract_multiplier,asof_date
0,ZO,Agriculture,Oats,50.0,2026-06-09
1,ZW,Agriculture,Chicago SRW Wheat,50.0,2026-06-09
2,CRA,Rates,3-Month CORRA,2500.0,2026-06-09
3,KE,Agriculture,KC HRW Wheat,50.0,2026-06-09
4,FSMI,Equities,Swiss SMI,10.0,2026-06-09
...,...,...,...,...,...
79,MWE,Agriculture,MGEX Wheat,50.0,2026-06-09
80,EMD,Equities,E-mini S&P Midcap 400,100.0,2026-06-09
81,6N,Currency,New Zealand Dollar,100000.0,2026-06-09
82,6E,Currency,Euro FX,125000.0,2026-06-09
83,LLG,Treasuries,Long Gilt,1000.0,2026-06-09

## LSEG Global Futures Flow Position

In [10]:
df =  Unifier.get_dataframe(name="lseg_futures_flow_forecasts_positions",  back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,long_contracts_sensitivity_1,long_contracts_sensitivity_2,long_contracts_sensitivity_3,long_contracts_sensitivity_4,short_contracts_sensitivity_1,short_contracts_sensitivity_2,short_contracts_sensitivity_3,short_contracts_sensitivity_4,asof_date
0,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6A,202603,False,nonreportable,117619,NaN,NaN,NaN,93874,NaN,NaN,NaN,2025-12-23
1,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6A,202603,False,other_reportables,7322,NaN,NaN,NaN,739,NaN,NaN,NaN,2025-12-23
2,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6A,202603,False,managed_money,13591,15533.0,34025.0,41730.0,0,0.0,0.0,0.0,2025-12-23
3,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6B,202603,False,managed_money,19300,22057.0,23225.0,45388.0,2242,2563.0,2699.0,5274.0,2025-12-23
4,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6B,202603,False,nonreportable,109407,NaN,NaN,NaN,109414,NaN,NaN,NaN,2025-12-23
5,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6B,202603,False,other_reportables,0,NaN,NaN,NaN,896,NaN,NaN,NaN,2025-12-23
6,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6C,202603,False,nonreportable,25946,NaN,NaN,NaN,29007,NaN,NaN,NaN,2025-12-23
7,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6C,202603,False,managed_money,6189,7073.0,18109.0,34403.0,1857,2122.0,5434.0,10323.0,2025-12-23
8,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6C,202603,False,other_reportables,11809,NaN,NaN,NaN,184,NaN,NaN,NaN,2025-12-23
9,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,6E,202603,False,nonreportable,236199,NaN,NaN,NaN,184676,NaN,NaN,NaN,2025-12-23

In [6]:
df = Unifier.get_dataframe(name="lseg_futures_flow_forecasts_positions", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,long_contracts_sensitivity_1,long_contracts_sensitivity_2,long_contracts_sensitivity_3,long_contracts_sensitivity_4,short_contracts_sensitivity_1,short_contracts_sensitivity_2,short_contracts_sensitivity_3,short_contracts_sensitivity_4,asof_date
0,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,AHD,NaN,None,managed_money,4479,5119.0,11306.0,9643.0,22247,25425.0,56149.0,47893.0,2024-01-16
1,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,AHD,NaN,None,producer_merchant,253340,NaN,NaN,NaN,375069,NaN,NaN,NaN,2024-01-16
2,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,BRN,202403,False,swap_dealer,363437,NaN,NaN,NaN,66922,NaN,NaN,NaN,2024-01-16
3,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,BRN,202403,False,nonreportable,63415,NaN,NaN,NaN,50013,NaN,NaN,NaN,2024-01-16
4,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,BRN,202403,False,managed_money,19583,22380.0,22380.0,43680.0,23197,26511.0,26511.0,51741.0,2024-01-16
5,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,BRN,202403,False,producer_merchant,714782,NaN,NaN,NaN,1031011,NaN,NaN,NaN,2024-01-16
6,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,BRN,202403,False,other_reportables,156417,NaN,NaN,NaN,366672,NaN,NaN,NaN,2024-01-16
7,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,CGB,202403,False,managed_money,15366,48838.0,73257.0,122095.0,13940,44306.0,66458.0,110764.0,2024-01-16
8,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,CRA,202312,False,managed_money,5557,12188.0,18282.0,30469.0,28322,62119.0,93179.0,155298.0,2024-01-16
9,2024-01-16 07:00:00.000,2024-01-15 00:00:00.000,DX,202403,False,managed_money,1912,2185.0,2484.0,3441.0,3366,3847.0,4375.0,6060.0,2024-01-16

In [8]:
df =  Unifier.get_dataframe(name="lseg_futures_flow_forecasts_positions", key="AHD", back_to='2025-11-18', limit=10)
display(df)

,asof_datetime,timestamp,identifier,active_delivery_month,is_continuous_roll_date,xt_group,long_contracts_sensitivity_1,long_contracts_sensitivity_2,long_contracts_sensitivity_3,long_contracts_sensitivity_4,short_contracts_sensitivity_1,short_contracts_sensitivity_2,short_contracts_sensitivity_3,short_contracts_sensitivity_4,asof_date
0,2026-02-10 07:00:00.000,2026-02-09 00:00:00.000,AHD,None,None,managed_money,46499,53142.0,53142.0,75146.0,8316,9504.0,9504.0,13439.0,2026-02-10
1,2026-02-10 07:00:00.000,2026-02-09 00:00:00.000,AHD,None,None,producer_merchant,240983,NaN,NaN,NaN,404993,NaN,NaN,NaN,2026-02-10
2,2026-02-11 07:00:00.000,2026-02-10 00:00:00.000,AHD,None,None,producer_merchant,241573,NaN,NaN,NaN,408740,NaN,NaN,NaN,2026-02-11
3,2026-02-11 07:00:00.000,2026-02-10 00:00:00.000,AHD,None,None,managed_money,46341,52961.0,52961.0,74891.0,8329,9519.0,9519.0,13461.0,2026-02-11
4,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,AHD,None,None,producer_merchant,239667,NaN,NaN,NaN,425218,NaN,NaN,NaN,2025-12-23
5,2025-12-23 07:00:00.000,2025-12-22 00:00:00.000,AHD,None,None,managed_money,82545,94337.0,94337.0,133400.0,0,0.0,0.0,0.0,2025-12-23
6,2025-12-06 07:00:00.000,2025-12-05 00:00:00.000,AHD,None,None,managed_money,91882,105008.0,105008.0,148489.0,0,0.0,0.0,0.0,2025-12-06
7,2025-12-06 07:00:00.000,2025-12-05 00:00:00.000,AHD,None,None,producer_merchant,215437,NaN,NaN,NaN,400693,NaN,NaN,NaN,2025-12-06
8,2026-01-03 07:00:00.000,2026-01-02 00:00:00.000,AHD,None,None,managed_money,77194,88222.0,88222.0,124752.0,0,0.0,0.0,0.0,2026-01-03
9,2026-01-03 07:00:00.000,2026-01-02 00:00:00.000,AHD,None,None,producer_merchant,237070,NaN,NaN,NaN,421517,NaN,NaN,NaN,2026-01-03