In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [3]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [5]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_r3k_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2026-02-04,118,2026-02-04 19:01:00.000,2026-02-04 20:00:03.000,1.536373e+10,1.575870e+10,None,1.481349e+10,1.630894e+10,None,...,2510057,2492376,2480082,2522322,991273,992193,2509685,2492824,Consumer Staples,2026-02-04
1,2026-02-04,71,2026-02-04 19:01:00.000,2026-02-04 20:00:03.000,7.567700e+09,7.905733e+09,None,7.350546e+09,8.122887e+09,None,...,1373715,1502685,1378485,1497893,580444,586715,1373761,1502682,Utilities,2026-02-04
2,2026-02-04,137,2026-02-04 19:06:00.000,2026-02-04 20:00:03.000,9.716125e+09,9.966250e+09,None,9.684693e+09,9.997681e+09,None,...,2439201,2501677,2432734,2508119,876681,878375,2439740,2501230,Energy,2026-02-04
3,2026-02-04,313,2026-02-04 19:23:00.000,2026-02-04 20:00:03.000,4.235300e+10,3.996245e+10,None,4.136295e+10,4.095250e+10,None,...,6047719,6058986,5967460,6139166,2670729,2675138,6067611,6039272,Consumer Discretionary,2026-02-04
4,2026-02-04,475,2026-02-04 19:43:00.000,2026-02-04 20:00:03.000,3.389730e+10,3.402425e+10,None,3.365198e+10,3.426957e+10,None,...,5811399,5932734,5804943,5938976,2518022,2536452,5810209,5934229,Health Care,2026-02-04
5,2026-02-04,157,2026-02-04 19:48:00.000,2026-02-04 20:00:03.000,6.132050e+09,6.025862e+09,None,6.372645e+09,5.785268e+09,None,...,1558483,1591640,1564470,1585623,574331,575482,1558155,1592067,Real Estate,2026-02-04
6,2026-02-04,554,2026-02-04 19:50:00.000,2026-02-04 20:00:03.000,4.246441e+10,4.379447e+10,None,4.214509e+10,4.411379e+10,None,...,6937168,7179585,6918991,7197599,2863377,2873082,6941485,7175589,Financials,2026-02-04
7,2026-02-04,125,2026-02-04 20:00:00.000,2026-02-04 20:00:03.000,3.741062e+10,3.620582e+10,None,3.680107e+10,3.681537e+10,None,...,4096940,4200717,4052979,4244651,1854536,1866406,4101233,4196509,Communication Services,2026-02-04
8,2026-02-04,422,2026-02-04 20:00:00.000,2026-02-04 20:00:03.000,4.717294e+10,4.895565e+10,None,4.701243e+10,4.911616e+10,None,...,7220004,7496883,7201086,7515679,3430441,3453125,7223857,7493286,Industrials,2026-02-04
9,2026-02-04,341,2026-02-04 20:00:00.000,2026-02-04 20:00:03.000,1.433532e+11,1.406102e+11,None,1.397149e+11,1.442485e+11,None,...,16550256,16877547,16343985,17083734,7681101,7730392,16610837,16817174,Information Technology,2026-02-04

In [6]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_r3k_daily_v1_2_1", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-22,472,2024-01-22 18:18:00.000,2024-01-22 20:00:03.000,1.871584e+10,1.741386e+10,None,1.808264e+10,1.804706e+10,None,...,3332405,3306604,3321388,3317556,1209807,1207624,3331840,3307434,Financials,2024-01-22
1,2024-01-22,427,2024-01-22 19:01:00.000,2024-01-22 20:00:03.000,1.567147e+10,1.502887e+10,None,1.538498e+10,1.531536e+10,None,...,3022050,3002614,3027419,2997165,1225835,1223387,3022306,3002635,Health Care,2024-01-22
2,2024-01-22,68,2024-01-22 19:01:00.000,2024-01-22 20:00:03.000,2.655047e+09,2.973278e+09,None,2.696848e+09,2.931477e+09,None,...,640338,657338,638306,659364,202522,203896,640392,657327,Utilities,2024-01-22
3,2024-01-22,146,2024-01-22 19:06:00.000,2024-01-22 20:00:03.000,3.961291e+09,5.071930e+09,None,3.967462e+09,5.065759e+09,None,...,1007955,1006116,1003318,1010741,332847,334246,1008007,1006144,Real Estate,2024-01-22
4,2024-01-22,109,2024-01-22 19:38:00.000,2024-01-22 20:00:03.000,7.721865e+09,8.321871e+09,None,7.845743e+09,8.197994e+09,None,...,1293797,1249779,1286102,1257466,483423,485852,1294448,1249189,Consumer Staples,2024-01-22
5,2024-01-22,306,2024-01-22 19:45:00.000,2024-01-22 20:00:03.000,2.604191e+10,2.354804e+10,None,2.587273e+10,2.371722e+10,None,...,3567545,3413246,3530275,3450475,1415133,1413157,3569405,3411570,Consumer Discretionary,2024-01-22
6,2024-01-22,119,2024-01-22 19:54:00.000,2024-01-22 20:00:03.000,5.030487e+09,4.425092e+09,None,4.901720e+09,4.553858e+09,None,...,1085038,1095192,1084221,1095992,350454,347937,1085044,1095267,Energy,2024-01-22
7,2024-01-22,115,2024-01-22 19:56:00.000,2024-01-22 20:00:03.000,3.732978e+09,3.376283e+09,None,3.757338e+09,3.351923e+09,None,...,761868,757801,760954,758697,276555,275458,761755,757979,Materials,2024-01-22
8,2024-01-22,103,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1.108245e+10,1.095469e+10,None,1.098919e+10,1.104795e+10,None,...,1446547,1402725,1439813,1409451,529134,530203,1445619,1403713,Communication Services,2024-01-22
9,2024-01-22,395,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1.380066e+10,1.380578e+10,None,1.363642e+10,1.397002e+10,None,...,2715761,2679046,2707079,2687677,1069509,1061951,2715141,2679897,Industrials,2024-01-22

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="lseg_us_equity_sector_flow_r3k_daily_v1_2_1", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for lseg_us_equity_sector_flow_r3k_daily_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_equity_sector_flow_r3k_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_sector_flow_r3k_daily_v1_2_1", target_location="./data")