In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [3]:
from unifier import unifier as Unifier

In [13]:
# Unifier.user = 'unifier username'
# Unifier.token = 'unifier api token'
Unifier.user='maciej.pomalecki@qube-rt.com'
Unifier.token='bbcb2abf-d2ff-46b5-a917-bfc582e33c1d'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [14]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_daily_v1_2", key="sp500", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2026-05-08 00:00:00.000,73,2026-05-08 20:00:00.000,2026-05-08 20:00:03.000,1.413774e+11,1.269247e+11,1.445276e+10,1.441888e+11,1.241133e+11,2.007549e+10,...,7237229,7884629,7197190,3897008,3902428,8262139,6819508,Information Technology,sp500,2026-05-08 00:00:00.000
1,2026-04-15 00:00:00.000,36,2026-04-15 19:45:00.000,2026-04-15 20:00:03.000,6.595142e+09,6.929360e+09,-3.342180e+08,6.496459e+09,7.028044e+09,-5.315853e+08,...,963256,982161,960796,392037,391554,921273,927410,Consumer Staples,sp500,2026-04-15 00:00:00.000
2,2026-04-15 00:00:00.000,31,2026-04-15 19:46:00.000,2026-04-15 20:00:03.000,3.065828e+09,2.960171e+09,1.056575e+08,3.158377e+09,2.867622e+09,2.907552e+08,...,459728,476859,452378,202872,200698,441695,430642,Real Estate,sp500,2026-04-15 00:00:00.000
3,2026-04-30 00:00:00.000,76,2026-04-30 16:59:00.000,2026-04-30 20:00:03.000,2.296327e+10,2.092406e+10,2.039208e+09,2.333879e+10,2.054854e+10,2.790252e+09,...,1938795,2584009,1870547,1001110,1003622,2801591,1609151,Financials,sp500,2026-04-30 00:00:00.000
4,2026-04-30 00:00:00.000,58,2026-04-30 19:13:00.000,2026-04-30 20:00:03.000,2.100730e+10,1.854708e+10,2.460224e+09,2.060379e+10,1.895059e+10,1.653195e+09,...,1730586,1932137,1714177,857352,856171,1963029,1633529,Health Care,sp500,2026-04-30 00:00:00.000
5,2026-04-30 00:00:00.000,23,2026-04-30 19:58:00.000,2026-04-30 20:00:03.000,4.131080e+10,3.845757e+10,2.853229e+09,4.158858e+10,3.817979e+10,3.408788e+09,...,2230162,2440647,2225418,1110676,1117941,2524617,2112214,Communication Services,sp500,2026-04-30 00:00:00.000
6,2026-04-16 00:00:00.000,36,2026-04-16 19:45:00.000,2026-04-16 20:00:03.000,6.608156e+09,7.036326e+09,-4.281702e+08,6.172285e+09,7.472197e+09,-1.299912e+09,...,1025897,858239,1032665,383241,381932,741216,1036732,Consumer Staples,sp500,2026-04-16 00:00:00.000
7,2026-04-16 00:00:00.000,31,2026-04-16 19:58:00.000,2026-04-16 20:00:03.000,3.070381e+09,2.790354e+09,2.800275e+08,3.107474e+09,2.753260e+09,3.542139e+08,...,407941,467122,395345,197577,196519,448973,325639,Real Estate,sp500,2026-04-16 00:00:00.000
8,2026-04-30 00:00:00.000,79,2026-04-30 19:47:00.000,2026-04-30 20:00:03.000,2.480189e+10,2.181434e+10,2.987553e+09,2.560177e+10,2.101447e+10,4.587301e+09,...,1873130,2230022,1834430,1065748,1064887,2290780,1772313,Industrials,sp500,2026-04-30 00:00:00.000
9,2026-04-30 00:00:00.000,48,2026-04-30 19:59:00.000,2026-04-30 20:00:03.000,3.250586e+10,3.049022e+10,2.015640e+09,3.264927e+10,3.034680e+10,2.302471e+09,...,2434747,2582633,2452593,1182744,1183768,2555109,2437361,Consumer Discretionary,sp500,2026-04-30 00:00:00.000

In [15]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_daily_v1_2", key="sp500", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2024-01-16 00:00:00.000,30,2024-01-16 19:47:00.000,2024-01-16 20:00:03.000,2.326628e+09,3.229015e+09,-9.023875e+08,2.145076e+09,3.410567e+09,-1.265490e+09,...,575749,402561,582974,154617,155074,290489,651628,Utilities,sp500,2024-01-16 00:00:00.000
1,2024-01-16 00:00:00.000,23,2024-01-16 19:58:00.000,2024-01-16 20:00:03.000,3.694589e+09,6.154383e+09,-2.459794e+09,3.240030e+09,6.608941e+09,-3.368911e+09,...,968881,524143,1019134,275462,275265,269140,1259806,Energy,sp500,2024-01-16 00:00:00.000
2,2024-01-16 00:00:00.000,28,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,2.711085e+09,3.150670e+09,-4.395851e+08,2.557803e+09,3.303951e+09,-7.461483e+08,...,523160,378007,529771,180859,181277,280234,598096,Materials,sp500,2024-01-16 00:00:00.000
3,2024-01-16 00:00:00.000,38,2024-01-16 19:29:00.000,2024-01-16 20:00:03.000,5.748915e+09,5.561269e+09,1.876461e+08,5.497008e+09,5.813175e+09,-3.161669e+08,...,910825,709253,919110,317462,317812,525848,989057,Consumer Staples,sp500,2024-01-16 00:00:00.000
4,2024-01-16 00:00:00.000,31,2024-01-16 19:41:00.000,2024-01-16 20:00:03.000,2.581595e+09,2.892187e+09,-3.105916e+08,2.625442e+09,2.848340e+09,-2.228977e+08,...,432567,413315,429391,177599,176979,367129,370492,Real Estate,sp500,2024-01-16 00:00:00.000
5,2024-01-19 00:00:00.000,31,2024-01-19 19:00:00.000,2024-01-19 20:00:03.000,2.924213e+09,2.914072e+09,1.014107e+07,3.019326e+09,2.818959e+09,2.003673e+08,...,397748,460320,387567,169710,169142,455065,332131,Real Estate,sp500,2024-01-19 00:00:00.000
6,2024-01-19 00:00:00.000,38,2024-01-19 19:47:00.000,2024-01-19 20:00:03.000,5.901381e+09,6.429852e+09,-5.284715e+08,5.841110e+09,6.490123e+09,-6.490130e+08,...,809875,780741,808270,302900,303869,658564,835181,Consumer Staples,sp500,2024-01-19 00:00:00.000
7,2024-01-12 00:00:00.000,64,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,3.068960e+10,2.711426e+10,3.575342e+09,3.019990e+10,2.760397e+10,2.595928e+09,...,1905920,2013777,1920286,909622,911488,1853764,1996953,Information Technology,sp500,2024-01-12 00:00:00.000
8,2024-01-23 00:00:00.000,64,2024-01-23 19:00:00.000,2024-01-23 20:00:03.000,1.053736e+10,9.111600e+09,1.425764e+09,1.067147e+10,8.977496e+09,1.693973e+09,...,942179,1099348,925405,487575,487444,1122316,814880,Health Care,sp500,2024-01-23 00:00:00.000
9,2024-01-23 00:00:00.000,72,2024-01-23 19:13:00.000,2024-01-23 20:00:03.000,1.060159e+10,1.024371e+10,3.578732e+08,1.091590e+10,9.929400e+09,9.865006e+08,...,1321969,1291788,1314947,517075,518804,1164926,1253248,Financials,sp500,2024-01-23 00:00:00.000

In [16]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_daily_v1_2", key="r1k", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2026-05-05 00:00:00.000,36,2026-05-05 17:54:00.000,2026-05-05 20:00:03.000,6.678659e+09,6.265792e+09,4.128676e+08,6.722876e+09,6.221575e+09,5.013012e+08,...,955742,1018548,948247,384703,386131,1009497,906502,Energy,r1k,2026-05-05 00:00:00.000
1,2026-05-05 00:00:00.000,40,2026-05-05 19:44:00.000,2026-05-05 20:00:03.000,4.510188e+09,4.768748e+09,-2.585604e+08,4.669879e+09,4.609057e+09,6.082135e+07,...,765194,836517,757447,331071,331713,850051,716862,Utilities,r1k,2026-05-05 00:00:00.000
2,2026-05-05 00:00:00.000,52,2026-05-05 20:00:00.000,2026-05-05 20:00:03.000,4.811682e+09,5.139890e+09,-3.282074e+08,4.772688e+09,5.178884e+09,-4.061958e+08,...,937993,961420,933196,414810,414267,955240,903134,Materials,r1k,2026-05-05 00:00:00.000
3,2026-05-05 00:00:00.000,60,2026-05-05 19:34:00.000,2026-05-05 20:00:03.000,7.878217e+09,8.176957e+09,-2.987392e+08,8.210384e+09,7.844790e+09,3.655944e+08,...,1285993,1454374,1265118,577656,576086,1443732,1137732,Consumer Staples,r1k,2026-05-05 00:00:00.000
4,2026-05-05 00:00:00.000,64,2026-05-05 19:41:00.000,2026-05-05 20:00:03.000,3.552006e+09,3.375117e+09,1.768893e+08,3.691703e+09,3.235420e+09,4.562827e+08,...,650919,752692,631563,308791,307086,750475,536717,Real Estate,r1k,2026-05-05 00:00:00.000
5,2026-05-05 00:00:00.000,159,2026-05-05 19:44:00.000,2026-05-05 20:00:03.000,2.150599e+10,2.341515e+10,-1.909160e+09,2.209381e+10,2.282733e+10,-7.335199e+08,...,3023480,3270097,2986221,1407537,1410036,3295991,2711134,Financials,r1k,2026-05-05 00:00:00.000
6,2026-05-05 00:00:00.000,106,2026-05-05 19:44:00.000,2026-05-05 20:00:03.000,1.740290e+10,1.756294e+10,-1.600443e+08,1.738005e+10,1.758579e+10,-2.057385e+08,...,2175944,2160033,2174319,1004513,1003844,2111242,2090055,Health Care,r1k,2026-05-05 00:00:00.000
7,2026-05-05 00:00:00.000,46,2026-05-05 20:00:00.000,2026-05-05 20:00:03.000,1.971102e+10,2.080696e+10,-1.095937e+09,1.968599e+10,2.083199e+10,-1.146002e+09,...,2306344,1860862,2353170,917899,921263,1718672,2414485,Communication Services,r1k,2026-05-05 00:00:00.000
8,2026-04-23 00:00:00.000,159,2026-04-23 17:49:00.000,2026-04-23 20:00:03.000,2.338256e+10,2.276137e+10,6.211882e+08,2.355089e+10,2.259304e+10,9.578495e+08,...,3105313,3246145,3072512,1394902,1400164,3241949,2757383,Financials,r1k,2026-04-23 00:00:00.000
9,2026-04-23 00:00:00.000,106,2026-04-23 19:33:00.000,2026-04-23 20:00:03.000,1.819766e+10,1.820362e+10,-5.953458e+06,1.798921e+10,1.841207e+10,-4.228536e+08,...,2349854,2038780,2381761,1016635,1020416,1918658,2410186,Health Care,r1k,2026-04-23 00:00:00.000

In [17]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_daily_v1_2", key="r1k", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2024-01-31 00:00:00.000,63,2024-01-31 19:33:00.000,2024-01-31 20:00:03.000,3.968808e+09,5.201969e+09,-1.233161e+09,3.824501e+09,5.346276e+09,-1.521775e+09,...,776157,692127,782431,300866,302959,598252,705752,Real Estate,r1k,2024-01-31 00:00:00.000
1,2024-01-31 00:00:00.000,59,2024-01-31 19:50:00.000,2024-01-31 20:00:03.000,7.505902e+09,8.634821e+09,-1.128920e+09,7.183808e+09,8.956915e+09,-1.773107e+09,...,1055497,932544,1071561,395909,398353,773440,1032091,Consumer Staples,r1k,2024-01-31 00:00:00.000
2,2024-01-29 00:00:00.000,59,2024-01-29 19:11:00.000,2024-01-29 20:00:03.000,7.478584e+09,6.203831e+09,1.274754e+09,7.729582e+09,5.952833e+09,1.776749e+09,...,811481,952950,796716,348276,346019,885267,637514,Consumer Staples,r1k,2024-01-29 00:00:00.000
3,2024-01-29 00:00:00.000,63,2024-01-29 19:46:00.000,2024-01-29 20:00:03.000,3.231462e+09,2.874223e+09,3.572387e+08,3.335641e+09,2.770044e+09,5.655972e+08,...,520033,608893,507993,220914,219232,563715,414002,Real Estate,r1k,2024-01-29 00:00:00.000
4,2024-01-26 00:00:00.000,157,2024-01-26 18:19:00.000,2024-01-26 20:00:03.000,1.620376e+10,1.556787e+10,6.358882e+08,1.682000e+10,1.495163e+10,1.868369e+09,...,2032556,2182213,1998455,882930,882231,2066174,1695835,Financials,r1k,2024-01-26 00:00:00.000
5,2024-01-26 00:00:00.000,117,2024-01-26 19:00:00.000,2024-01-26 20:00:03.000,1.385863e+10,1.360392e+10,2.547110e+08,1.407201e+10,1.339053e+10,6.814753e+08,...,1483920,1415723,1466970,670056,671223,1287712,1383925,Health Care,r1k,2024-01-26 00:00:00.000
6,2024-01-26 00:00:00.000,48,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1.302881e+10,1.216600e+10,8.628130e+08,1.324597e+10,1.194884e+10,1.297127e+09,...,1150680,1170544,1145651,476380,476747,1021200,1136531,Communication Services,r1k,2024-01-26 00:00:00.000
7,2024-01-24 00:00:00.000,131,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,5.827313e+10,5.522618e+10,3.046960e+09,5.802350e+10,5.547581e+10,2.547696e+09,...,3947034,3972587,3991451,1893874,1904097,3703009,4048618,Information Technology,r1k,2024-01-24 00:00:00.000
8,2024-01-16 00:00:00.000,157,2024-01-16 17:28:00.000,2024-01-16 20:00:03.000,1.778078e+10,1.651073e+10,1.270056e+09,1.785929e+10,1.643223e+10,1.427060e+09,...,2643954,2379906,2648094,996113,995504,2173073,2588646,Financials,r1k,2024-01-16 00:00:00.000
9,2024-01-16 00:00:00.000,118,2024-01-16 19:38:00.000,2024-01-16 20:00:03.000,1.289492e+10,1.306110e+10,-1.661837e+08,1.256112e+10,1.339490e+10,-8.337809e+08,...,1622757,1470004,1617602,726067,726576,1386906,1526385,Health Care,r1k,2024-01-16 00:00:00.000

In [18]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_daily_v1_2", key="r2k", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2026-04-30 00:00:00.000,207,2026-04-30 20:00:00.000,2026-04-30 20:00:03.000,1.059713e+10,8.995745e+09,1.601381e+09,1.076239e+10,8.830483e+09,1.931903e+09,...,2557933,3083217,2488739,1217457,1211276,3148194,2100520,Information Technology,r2k,2026-04-30 00:00:00.000
1,2026-04-30 00:00:00.000,77,2026-04-30 16:20:00.000,2026-04-30 20:00:03.000,7.703038e+08,7.542211e+08,1.608278e+07,7.917115e+08,7.328134e+08,5.889802e+07,...,465720,491271,442922,242216,242071,333426,247770,Communication Services,r2k,2026-04-30 00:00:00.000
2,2026-04-30 00:00:00.000,389,2026-04-30 16:55:00.000,2026-04-30 20:00:03.000,5.496896e+09,5.231746e+09,2.651493e+08,5.663993e+09,5.064649e+09,5.993446e+08,...,2061538,2360426,1966497,1038398,1035162,2195091,1568800,Health Care,r2k,2026-04-30 00:00:00.000
3,2026-04-30 00:00:00.000,409,2026-04-30 17:14:00.000,2026-04-30 20:00:03.000,2.787579e+09,2.741538e+09,4.604077e+07,2.906119e+09,2.622998e+09,2.831206e+08,...,1188621,1389987,1117971,619601,615967,1352297,880283,Financials,r2k,2026-04-30 00:00:00.000
4,2026-05-05 00:00:00.000,31,2026-05-05 18:49:00.000,2026-05-05 20:00:03.000,5.247956e+08,6.141187e+08,-8.932306e+07,5.139756e+08,6.249387e+08,-1.109631e+08,...,182189,191554,183308,97146,97829,195192,174190,Utilities,r2k,2026-05-05 00:00:00.000
5,2026-05-05 00:00:00.000,104,2026-05-05 19:17:00.000,2026-05-05 20:00:03.000,2.098610e+09,2.197349e+09,-9.873850e+07,2.109179e+09,2.186780e+09,-7.760089e+07,...,879165,807302,852372,373823,374027,706968,732421,Energy,r2k,2026-05-05 00:00:00.000
6,2026-05-05 00:00:00.000,81,2026-05-05 19:57:00.000,2026-05-05 20:00:03.000,1.360912e+09,1.394895e+09,-3.398301e+07,1.371374e+09,1.384432e+09,-1.305825e+07,...,570216,594712,553909,250934,250352,541332,468604,Materials,r2k,2026-05-05 00:00:00.000
7,2026-01-02 00:00:00.000,106,2026-01-02 16:02:00.000,2026-01-02 20:00:03.000,7.142718e+08,6.328781e+08,8.139374e+07,7.077039e+08,6.394459e+08,6.825801e+07,...,319401,304991,311160,130058,128873,228332,211726,Real Estate,r2k,2026-01-02 00:00:00.000
8,2026-01-02 00:00:00.000,61,2026-01-02 16:03:00.000,2026-01-02 20:00:03.000,3.028175e+08,3.490962e+08,-4.627864e+07,2.901046e+08,3.618091e+08,-7.170456e+07,...,220517,151904,217603,93833,94422,112775,199566,Consumer Staples,r2k,2026-01-02 00:00:00.000
9,2026-04-15 00:00:00.000,31,2026-04-15 18:42:00.000,2026-04-15 20:00:03.000,9.905054e+08,9.647674e+08,2.573805e+07,1.009500e+09,9.457728e+08,6.372715e+07,...,240822,261270,238810,125696,126231,261424,224906,Utilities,r2k,2026-04-15 00:00:00.000

In [19]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_daily_v1_2", key="r2k", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2024-01-11 00:00:00.000,414,2024-01-11 16:08:00.000,2024-01-11 20:00:03.000,3.719342e+09,3.697205e+09,2.213674e+07,3.680993e+09,3.735554e+09,-5.456083e+07,...,1730005,1572178,1705165,651776,655037,1222742,1541110,Health Care,r2k,2024-01-11 00:00:00.000
1,2024-01-11 00:00:00.000,77,2024-01-11 18:53:00.000,2024-01-11 20:00:03.000,3.095958e+08,3.811703e+08,-7.157446e+07,2.975204e+08,3.932457e+08,-9.572525e+07,...,252201,197924,246885,86030,86528,106244,203315,Communication Services,r2k,2024-01-11 00:00:00.000
2,2024-01-11 00:00:00.000,376,2024-01-11 19:00:00.000,2024-01-11 20:00:03.000,1.582727e+09,1.535647e+09,4.707972e+07,1.605471e+09,1.512903e+09,9.256867e+07,...,754466,698225,746659,294353,292899,551472,652632,Financials,r2k,2024-01-11 00:00:00.000
3,2024-01-24 00:00:00.000,276,2024-01-24 16:20:00.000,2024-01-24 20:00:03.000,1.568159e+09,1.850502e+09,-2.823430e+08,1.492742e+09,1.925920e+09,-4.331787e+08,...,927118,676171,921694,360196,367607,420208,820937,Industrials,r2k,2024-01-24 00:00:00.000
4,2024-01-24 00:00:00.000,222,2024-01-24 19:00:00.000,2024-01-24 20:00:03.000,1.482922e+09,1.755890e+09,-2.729681e+08,1.403162e+09,1.835651e+09,-4.324890e+08,...,814140,567985,814939,297277,303085,350560,747448,Consumer Discretionary,r2k,2024-01-24 00:00:00.000
5,2024-01-31 00:00:00.000,106,2024-01-31 16:36:00.000,2024-01-31 20:00:03.000,1.195020e+09,1.520746e+09,-3.257255e+08,1.125080e+09,1.590685e+09,-4.656046e+08,...,605600,447452,604810,194411,198005,260591,514874,Energy,r2k,2024-01-31 00:00:00.000
6,2024-01-31 00:00:00.000,33,2024-01-31 19:00:00.000,2024-01-31 20:00:03.000,3.463108e+08,4.322506e+08,-8.593986e+07,3.315142e+08,4.470472e+08,-1.155329e+08,...,134712,91373,139864,48236,49354,81580,130077,Utilities,r2k,2024-01-31 00:00:00.000
7,2024-01-31 00:00:00.000,75,2024-01-31 19:58:00.000,2024-01-31 20:00:03.000,3.464397e+08,4.618650e+08,-1.154252e+08,3.190871e+08,4.892176e+08,-1.701306e+08,...,225767,162015,226824,81416,84266,112107,197598,Materials,r2k,2024-01-31 00:00:00.000
8,2024-01-18 00:00:00.000,106,2024-01-18 16:41:00.000,2024-01-18 20:00:03.000,1.324968e+09,1.216129e+09,1.088392e+08,1.393872e+09,1.147225e+09,2.466470e+08,...,508009,566509,494486,187407,185488,499175,308904,Energy,r2k,2024-01-18 00:00:00.000
9,2024-01-18 00:00:00.000,33,2024-01-18 19:00:00.000,2024-01-18 20:00:03.000,2.414786e+08,2.443955e+08,-2.916838e+06,2.442501e+08,2.416240e+08,2.626178e+06,...,96962,92614,94489,39569,39250,78162,76353,Utilities,r2k,2024-01-18 00:00:00.000

In [20]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_daily_v1_2", key="r3k", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2026-04-23 00:00:00.000,323,2026-04-23 19:45:00.000,2026-04-23 20:00:03.000,3.451086e+10,3.725329e+10,-2.742432e+09,3.401184e+10,3.775231e+10,-3.740472e+09,...,4859168,4320836,4873110,2117709,2134438,4004897,4755005,Consumer Discretionary,r3k,2026-04-23 00:00:00.000
1,2026-04-23 00:00:00.000,433,2026-04-23 20:00:00.000,2026-04-23 20:00:03.000,3.683760e+10,3.602629e+10,8.113155e+08,3.704763e+10,3.581626e+10,1.231372e+09,...,5688915,5425614,5678358,2669136,2676913,5270362,5471801,Industrials,r3k,2026-04-23 00:00:00.000
2,2026-04-16 00:00:00.000,570,2026-04-16 17:06:00.000,2026-04-16 20:00:03.000,2.726232e+10,2.870539e+10,-1.443072e+09,2.726714e+10,2.870057e+10,-1.433429e+09,...,4682199,4150326,4659367,1967450,1977310,3747859,4366001,Financials,r3k,2026-04-16 00:00:00.000
3,2026-04-16 00:00:00.000,498,2026-04-16 19:44:00.000,2026-04-16 20:00:03.000,2.106844e+10,2.079564e+10,2.727989e+08,2.092483e+10,2.093925e+10,-1.441533e+07,...,4112682,3926676,4046604,1860167,1868911,3655162,3555205,Health Care,r3k,2026-04-16 00:00:00.000
4,2026-04-16 00:00:00.000,123,2026-04-16 20:00:00.000,2026-04-16 20:00:03.000,1.947032e+10,1.616566e+10,3.304663e+09,1.968954e+10,1.594645e+10,3.743094e+09,...,2024310,2432703,1979507,958230,961067,2412062,1553730,Communication Services,r3k,2026-04-16 00:00:00.000
5,2026-05-08 00:00:00.000,343,2026-05-08 20:00:00.000,2026-05-08 20:00:03.000,1.635594e+11,1.469864e+11,1.657300e+10,1.667159e+11,1.438298e+11,2.288607e+10,...,12279005,13190768,12196315,6194352,6198273,13520292,11490433,Information Technology,r3k,2026-05-08 00:00:00.000
6,2026-04-15 00:00:00.000,345,2026-04-15 20:00:00.000,2026-04-15 20:00:03.000,1.089656e+11,9.726686e+10,1.169872e+10,1.118565e+11,9.437595e+10,1.748054e+10,...,9173293,10924398,8946038,4462765,4462676,11614634,7677682,Information Technology,r3k,2026-04-15 00:00:00.000
7,2026-04-15 00:00:00.000,498,2026-04-15 19:12:00.000,2026-04-15 20:00:03.000,1.928605e+10,2.025874e+10,-9.726943e+08,1.980859e+10,1.973620e+10,7.238864e+07,...,3927738,3783627,3882299,1760868,1760915,3527096,3469319,Health Care,r3k,2026-04-15 00:00:00.000
8,2026-04-15 00:00:00.000,570,2026-04-15 19:35:00.000,2026-04-15 20:00:03.000,3.071605e+10,3.059053e+10,1.255201e+08,3.076013e+10,3.054646e+10,2.136712e+08,...,4368476,4880332,4240729,2049843,2044263,4780626,3525808,Financials,r3k,2026-04-15 00:00:00.000
9,2026-04-15 00:00:00.000,123,2026-04-15 20:00:00.000,2026-04-15 20:00:03.000,2.034940e+10,1.783176e+10,2.517641e+09,2.043811e+10,1.774306e+10,2.695044e+09,...,1994752,2318167,1957368,955414,953489,2261825,1496280,Communication Services,r3k,2026-04-15 00:00:00.000

In [21]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_daily_v1_2", key="r3k", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,index,asof_date
0,2024-01-17 00:00:00.000,532,2024-01-17 19:17:00.000,2024-01-17 20:00:03.000,1.458092e+10,1.409156e+10,None,1.457087e+10,1.410161e+10,None,...,2901296,2756583,2872403,1206731,1205549,2368271,2533526,Health Care,r3k,2024-01-17 00:00:00.000
1,2024-01-17 00:00:00.000,532,2024-01-17 19:55:00.000,2024-01-17 20:00:03.000,1.667408e+10,1.666628e+10,None,1.675688e+10,1.658349e+10,None,...,3196819,2933934,3186096,1187662,1185108,2586122,3055750,Financials,r3k,2024-01-17 00:00:00.000
2,2024-01-17 00:00:00.000,125,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1.026625e+10,1.004512e+10,None,1.045327e+10,9.858100e+09,None,...,1321021,1363670,1300755,542805,543888,1129868,1116347,Communication Services,r3k,2024-01-17 00:00:00.000
3,2024-01-22 00:00:00.000,346,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,5.875043e+10,5.722083e+10,None,5.830243e+10,5.766883e+10,None,...,5084830,5368714,5088667,2372882,2384687,5130592,4899543,Information Technology,r3k,2024-01-22 00:00:00.000
4,2024-01-11 00:00:00.000,532,2024-01-11 19:00:00.000,2024-01-11 20:00:03.000,1.646088e+10,1.691252e+10,None,1.648796e+10,1.688544e+10,None,...,3348493,3164642,3306991,1373124,1375212,2738993,3061962,Health Care,r3k,2024-01-11 00:00:00.000
5,2024-01-11 00:00:00.000,532,2024-01-11 19:44:00.000,2024-01-11 20:00:03.000,1.781871e+10,1.822796e+10,None,1.809933e+10,1.794733e+10,None,...,3240832,2938311,3218376,1244130,1245427,2536323,3142378,Financials,r3k,2024-01-11 00:00:00.000
6,2024-01-11 00:00:00.000,125,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1.149768e+10,1.154568e+10,None,1.159728e+10,1.144609e+10,None,...,1602444,1472808,1598147,614960,618319,1305146,1516125,Communication Services,r3k,2024-01-11 00:00:00.000
7,2024-01-24 00:00:00.000,74,2024-01-24 19:00:00.000,2024-01-24 20:00:03.000,3.356854e+09,4.050226e+09,None,3.187595e+09,4.219484e+09,None,...,863485,586726,882605,239455,244548,419824,951838,Utilities,r3k,2024-01-24 00:00:00.000
8,2024-01-24 00:00:00.000,142,2024-01-24 19:58:00.000,2024-01-24 20:00:03.000,6.828925e+09,5.557467e+09,None,7.028661e+09,5.357730e+09,None,...,1188616,1371806,1161247,452440,449373,1322097,810708,Energy,r3k,2024-01-24 00:00:00.000
9,2024-01-24 00:00:00.000,131,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,4.597787e+09,5.258061e+09,None,4.364530e+09,5.491318e+09,None,...,1069975,818192,1086385,376521,382056,622648,1074383,Materials,r3k,2024-01-24 00:00:00.000

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="lseg_us_equity_sector_flow_daily_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_equity_sector_flow_r3k_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_equity_sector_flow_r3k_daily_v1_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_sector_flow_daily_v1_2", target_location="./data")