In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_sp500_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2025-11-20,59,2025-11-20 19:01:00.000,2025-11-20 20:00:03.000,1.480956e+10,1.484782e+10,-3.826108e+07,1.471161e+10,1.494577e+10,-2.341584e+08,...,1788117,1797496,1770619,1814989,859119,861596,1789143,1796509,Health Care,2025-11-20
1,2025-11-20,31,2025-11-20 19:01:00.000,2025-11-20 20:00:03.000,4.747664e+09,4.775635e+09,-2.797018e+07,4.800365e+09,4.722934e+09,7.743184e+07,...,839198,860105,836638,862664,312758,314870,839405,859917,Utilities,2025-11-20
2,2025-11-20,20,2025-11-20 19:03:00.000,2025-11-20 20:00:03.000,3.445633e+09,4.156387e+09,-7.107548e+08,3.404478e+09,4.197542e+09,-7.930643e+08,...,708230,739900,709170,738958,267221,270142,708192,739950,Energy,2025-11-20
3,2025-11-20,30,2025-11-20 19:44:00.000,2025-11-20 20:00:03.000,2.813080e+09,3.739747e+09,-9.266669e+08,2.948785e+09,3.604043e+09,-6.552582e+08,...,561830,578481,558536,581762,236671,238489,561973,578356,Real Estate,2025-11-20
4,2025-11-20,36,2025-11-20 19:55:00.000,2025-11-20 20:00:03.000,8.695062e+09,9.133214e+09,-4.381513e+08,8.577338e+09,9.250937e+09,-6.735988e+08,...,1508965,1457915,1481496,1485378,570926,572107,1508809,1458094,Consumer Staples,2025-11-20
5,2025-11-20,75,2025-11-20 19:56:00.000,2025-11-20 20:00:03.000,1.983137e+10,2.253924e+10,-2.707876e+09,1.980217e+10,2.256845e+10,-2.766280e+09,...,2646102,2746900,2628866,2764125,1234712,1241507,2647495,2745544,Financials,2025-11-20
6,2025-11-20,79,2025-11-20 19:56:00.000,2025-11-20 20:00:03.000,1.657851e+10,1.769162e+10,-1.113107e+09,1.643880e+10,1.783134e+10,-1.392536e+09,...,2028034,2085504,2018016,2095501,1017267,1025167,2028369,2085210,Industrials,2025-11-20
7,2025-11-20,49,2025-11-20 19:59:00.000,2025-11-20 20:00:03.000,3.531083e+10,3.399762e+10,1.313215e+09,3.461963e+10,3.468882e+10,-6.919305e+07,...,3025914,2968810,2958834,3035873,1546521,1558656,3038412,2956346,Consumer Discretionary,2025-11-20
8,2025-11-20,23,2025-11-20 20:00:00.000,2025-11-20 20:00:03.000,2.449837e+10,2.380582e+10,6.925485e+08,2.384862e+10,2.445556e+10,-6.069422e+08,...,2379535,2406008,2333293,2452244,1141602,1154573,2377350,2408220,Communication Services,2025-11-20
9,2025-11-20,68,2025-11-20 20:00:00.000,2025-11-20 20:00:03.000,8.192379e+10,8.373660e+10,-1.812807e+09,8.047045e+10,8.518993e+10,-4.719479e+09,...,7960034,8131478,7807482,8284008,3977694,4016064,8016344,8075216,Information Technology,2025-11-20

In [5]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_sp500_daily_v1_2_1", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-11,61,2024-01-11 19:01:00.000,2024-01-11 20:00:03.000,1.051009e+10,1.098335e+10,-4.732625e+08,1.070847e+10,1.078497e+10,-7.649957e+07,...,1140521,1158831,1141980,1157368,520170,520261,1140785,1158603,Health Care,2024-01-11
1,2024-01-11,30,2024-01-11 19:16:00.000,2024-01-11 20:00:03.000,2.555296e+09,2.290920e+09,2.643757e+08,2.610750e+09,2.235466e+09,3.752837e+08,...,402559,411149,402957,410741,156292,156162,402755,410975,Real Estate,2024-01-11
2,2024-01-11,70,2024-01-11 19:45:00.000,2024-01-11 20:00:03.000,1.175952e+10,1.112733e+10,6.321892e+08,1.160768e+10,1.127916e+10,3.285223e+08,...,1452527,1490617,1462884,1480253,549452,550933,1452631,1490557,Financials,2024-01-11
3,2024-01-11,30,2024-01-11 19:50:00.000,2024-01-11 20:00:03.000,2.299345e+09,2.664958e+09,-3.656131e+08,2.449754e+09,2.514549e+09,-6.479451e+07,...,523341,542954,522523,543772,164636,167619,523564,542749,Utilities,2024-01-11
4,2024-01-11,19,2024-01-11 19:53:00.000,2024-01-11 20:00:03.000,9.348538e+09,9.438274e+09,-8.973592e+07,9.111016e+09,9.675797e+09,-5.647808e+08,...,948287,959244,946933,960591,388720,391380,948446,959101,Communication Services,2024-01-11
5,2024-01-11,36,2024-01-11 19:59:00.000,2024-01-11 20:00:03.000,5.587193e+09,5.019931e+09,5.672618e+08,5.624918e+09,4.982206e+09,6.427125e+08,...,782141,773465,781270,774327,277864,277637,782247,773379,Consumer Staples,2024-01-11
6,2024-01-11,52,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1.937944e+10,1.794744e+10,1.431997e+09,1.867074e+10,1.865614e+10,1.460406e+07,...,1807298,1768061,1789312,1786040,805067,807761,1809894,1765497,Consumer Discretionary,2024-01-11
7,2024-01-11,18,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,2.971760e+09,2.897842e+09,7.391845e+07,2.762309e+09,3.107293e+09,-3.449837e+08,...,479383,496864,478474,497769,167162,167152,479348,496907,Energy,2024-01-11
8,2024-01-11,78,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,9.296041e+09,9.235326e+09,6.071539e+07,9.498046e+09,9.033321e+09,4.647254e+08,...,1157004,1240403,1165833,1231562,511389,513283,1157109,1240338,Industrials,2024-01-11
9,2024-01-11,61,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,3.735035e+10,3.646643e+10,8.839169e+08,3.699601e+10,3.682076e+10,1.752522e+08,...,2461219,2387227,2450854,2397579,1157064,1163070,2460300,2388179,Information Technology,2024-01-11

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="lseg_us_equity_sector_flow_sp500_daily_v1_2_1", target_location="./data", asof_date='2025-03-06')

Downloading using native python implementation for lseg_us_equity_sector_flow_sp500_daily_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_equity_sector_flow_sp500_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_sector_flow_sp500_daily_v1_2_1", target_location="./data")