In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [5]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_r1k_daily_v1_2", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2026-02-17,158,2026-02-17 17:45:00.000,2026-02-17 20:00:03.000,2.715581e+10,2.680989e+10,3.459152e+08,2.735234e+10,2.661336e+10,7.389807e+08,...,3466668,3530995,3430795,3527085,1533323,1535045,3276991,3436032,Financials,2026-02-17
1,2026-02-17,105,2026-02-17 19:01:00.000,2026-02-17 20:00:03.000,1.957858e+10,1.861295e+10,9.656278e+08,1.921189e+10,1.897964e+10,2.322516e+08,...,2255549,2246796,2191798,2294557,1060533,1060559,2115428,2290235,Health Care,2026-02-17
2,2026-02-17,40,2026-02-17 19:09:00.000,2026-02-17 20:00:03.000,5.484010e+09,5.760043e+09,-2.760325e+08,5.226534e+09,6.017519e+09,-7.909848e+08,...,794188,1056117,747812,1097189,371402,373741,607624,1199644,Utilities,2026-02-17
3,2026-02-17,60,2026-02-17 19:15:00.000,2026-02-17 20:00:03.000,1.205922e+10,1.122232e+10,8.369014e+08,1.193034e+10,1.135121e+10,5.791287e+08,...,1819627,1839693,1724245,1918320,730149,732642,1598371,1950679,Consumer Staples,2026-02-17
4,2026-02-17,64,2026-02-17 19:23:00.000,2026-02-17 20:00:03.000,5.488273e+09,4.407242e+09,1.081031e+09,5.556792e+09,4.338723e+09,1.218069e+09,...,1048577,970227,1039786,966144,413425,412241,1017564,899654,Real Estate,2026-02-17
5,2026-02-17,52,2026-02-17 19:49:00.000,2026-02-17 20:00:03.000,6.260446e+09,6.181323e+09,7.912291e+07,5.970898e+09,6.470871e+09,-4.999727e+08,...,1047034,1086109,1029892,1095296,466842,468881,979130,1070533,Materials,2026-02-17
6,2026-02-17,35,2026-02-17 19:52:00.000,2026-02-17 20:00:03.000,6.818306e+09,6.421141e+09,3.971648e+08,7.163158e+09,6.076289e+09,1.086869e+09,...,995900,1067261,984116,1078014,376584,378764,932297,1127302,Energy,2026-02-17
7,2026-02-17,126,2026-02-17 19:58:00.000,2026-02-17 20:00:03.000,3.505078e+10,2.921047e+10,5.840305e+09,3.556181e+10,2.869945e+10,6.862358e+09,...,4213260,3671550,4116332,3739402,1838499,1838525,4254801,3449272,Consumer Discretionary,2026-02-17
8,2026-02-17,46,2026-02-17 20:00:00.000,2026-02-17 20:00:03.000,1.904900e+10,1.806155e+10,9.874516e+08,1.878191e+10,1.832864e+10,4.532709e+08,...,2321501,2102120,2258800,2151424,1011336,1013146,2277894,1992045,Communication Services,2026-02-17
9,2026-02-17,172,2026-02-17 20:00:00.000,2026-02-17 20:00:03.000,2.469589e+10,2.396524e+10,7.306468e+08,2.497036e+10,2.369077e+10,1.279598e+09,...,3048324,2853508,3062706,2831099,1473760,1478953,3140394,2697911,Industrials,2026-02-17

In [6]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_r1k_daily_v1_2", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-25,127,2024-01-25 19:00:00.000,2024-01-25 20:00:03.000,2.987554e+10,2.837519e+10,1.500355e+09,2.881456e+10,2.943616e+10,-6.216006e+08,...,3480531,3389115,3344798,3484379,1547634,1551777,2963461,3487262,Consumer Discretionary,2024-01-25
1,2024-01-25,36,2024-01-25 19:00:00.000,2024-01-25 20:00:03.000,6.305865e+09,5.394937e+09,9.109286e+08,6.980922e+09,4.719880e+09,2.261042e+09,...,977374,784071,984876,768571,302705,298960,1016070,609098,Energy,2024-01-25
2,2024-01-25,117,2024-01-25 19:00:00.000,2024-01-25 20:00:03.000,1.834446e+10,1.611312e+10,2.231338e+09,1.827982e+10,1.617776e+10,2.102065e+09,...,1792514,1726490,1781294,1726674,810158,808983,1686092,1715276,Health Care,2024-01-25
3,2024-01-25,157,2024-01-25 19:33:00.000,2024-01-25 20:00:03.000,1.783980e+10,1.577528e+10,2.064516e+09,1.804016e+10,1.557492e+10,2.465246e+09,...,2552172,2406468,2530143,2392741,988602,984592,2271191,2239121,Financials,2024-01-25
4,2024-01-25,59,2024-01-25 19:39:00.000,2024-01-25 20:00:03.000,7.811319e+09,5.454297e+09,2.357022e+09,8.136267e+09,5.129348e+09,3.006919e+09,...,1124101,841265,1125730,830963,368958,366641,1192768,668102,Consumer Staples,2024-01-25
5,2024-01-25,42,2024-01-25 19:45:00.000,2024-01-25 20:00:03.000,3.139171e+09,2.824697e+09,3.144749e+08,3.255253e+09,2.708615e+09,5.466380e+08,...,651243,588031,645970,582836,200232,199769,558638,488651,Utilities,2024-01-25
6,2024-01-25,63,2024-01-25 19:59:00.000,2024-01-25 20:00:03.000,3.434676e+09,3.053100e+09,3.815766e+08,3.578077e+09,2.909699e+09,6.683776e+08,...,681874,629512,677693,625243,246798,248094,613348,579000,Real Estate,2024-01-25
7,2024-01-25,48,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1.457518e+10,1.189457e+10,2.680602e+09,1.519529e+10,1.127446e+10,3.920837e+09,...,1560179,1298340,1555009,1283120,564028,563282,1540295,1126804,Communication Services,2024-01-25
8,2024-01-25,165,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1.797531e+10,1.596599e+10,2.009324e+09,1.830144e+10,1.563986e+10,2.661582e+09,...,2538401,2337716,2536963,2318699,1025804,1024050,2497323,2211302,Industrials,2024-01-25
9,2024-01-25,131,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,5.816295e+10,5.616965e+10,1.993308e+09,5.903245e+10,5.530015e+10,3.732306e+09,...,4138461,4105022,4082533,4154597,1917778,1936921,3891443,4271753,Information Technology,2024-01-25

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="lseg_us_equity_sector_flow_r1k_daily_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_equity_sector_flow_r1k_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_equity_sector_flow_r1k_daily_v1_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_sector_flow_r1k_daily_v1_2", target_location="./data")