In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_r2k_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2025-11-18,58,2025-11-18 16:04:00.000,2025-11-18 20:00:03.000,3.534269e+08,3.570932e+08,-3.666259e+06,3.594988e+08,3.510213e+08,8.477581e+06,...,262116,262852,261225,263738,113928,114046,262192,262811,Consumer Staples,2025-11-18
1,2025-11-18,75,2025-11-18 17:39:00.000,2025-11-18 20:00:03.000,5.458451e+08,5.380797e+08,7.765375e+06,5.361004e+08,5.478244e+08,-1.172395e+07,...,435869,440469,435816,440512,157110,156624,435902,440492,Communication Services,2025-11-18
2,2025-11-18,366,2025-11-18 18:30:00.000,2025-11-18 20:00:03.000,4.727350e+09,4.874609e+09,-1.472591e+08,4.776795e+09,4.825163e+09,-4.836818e+07,...,2916323,2970506,2916970,2969767,1232349,1235477,2881088,3005972,Health Care,2025-11-18
3,2025-11-18,393,2025-11-18 19:01:00.000,2025-11-18 20:00:03.000,1.951543e+09,2.039042e+09,-8.749882e+07,1.957082e+09,2.033503e+09,-7.642062e+07,...,1168852,1203876,1182047,1190637,457699,458398,1168982,1203989,Financials,2025-11-18
4,2025-11-18,245,2025-11-18 19:01:00.000,2025-11-18 20:00:03.000,3.931484e+09,4.101623e+09,-1.701392e+08,3.905038e+09,4.128070e+09,-2.230315e+08,...,1805067,1823361,1807709,1820678,723901,724040,1805919,1822662,Industrials,2025-11-18
5,2025-11-18,94,2025-11-18 19:01:00.000,2025-11-18 20:00:03.000,6.431858e+08,6.294901e+08,1.369571e+07,6.309992e+08,6.416767e+08,-1.067747e+07,...,373820,377682,375089,376394,119435,119287,373770,377797,Real Estate,2025-11-18
6,2025-11-18,31,2025-11-18 19:01:00.000,2025-11-18 20:00:03.000,8.036686e+08,7.463915e+08,5.727710e+07,8.048780e+08,7.451822e+08,5.969584e+07,...,203410,211822,202613,212619,107225,108303,203431,211818,Utilities,2025-11-18
7,2025-11-18,102,2025-11-18 19:25:00.000,2025-11-18 20:00:03.000,1.325591e+09,1.269506e+09,5.608472e+07,1.323436e+09,1.271660e+09,5.177627e+07,...,745696,743870,748331,741215,262381,261151,745722,743906,Energy,2025-11-18
8,2025-11-18,188,2025-11-18 20:00:00.000,2025-11-18 20:00:03.000,1.796632e+09,1.870225e+09,-7.359350e+07,1.788962e+09,1.877895e+09,-8.893248e+07,...,1129564,1133985,1134528,1128983,424550,423070,1130080,1133593,Consumer Discretionary,2025-11-18
9,2025-11-18,203,2025-11-18 20:00:00.000,2025-11-18 20:00:03.000,6.013946e+09,5.951804e+09,6.214147e+07,6.042606e+09,5.923144e+09,1.194618e+08,...,2660295,2646552,2638430,2668370,965428,965998,2663574,2643398,Information Technology,2025-11-18

In [5]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_r2k_daily_v1_2_1", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-19,62,2024-01-19 16:01:00.000,2024-01-19 20:00:03.000,3.033416e+08,2.700821e+08,3.325947e+07,2.977772e+08,2.756465e+08,2.213072e+07,...,262201,256738,261294,257637,78319,77575,262481,256494,Communication Services,2024-01-19
1,2024-01-19,322,2024-01-19 16:05:00.000,2024-01-19 20:00:03.000,1.357834e+09,1.162715e+09,1.951185e+08,1.339174e+09,1.181374e+09,1.578001e+08,...,716061,672235,711792,676471,246622,239903,716253,672214,Financials,2024-01-19
2,2024-01-19,54,2024-01-19 16:21:00.000,2024-01-19 20:00:03.000,3.757602e+08,4.372262e+08,-6.146596e+07,3.831678e+08,4.298186e+08,-4.665087e+07,...,152162,157264,153297,156117,62655,63675,152167,157289,Consumer Staples,2024-01-19
3,2024-01-19,182,2024-01-19 16:21:00.000,2024-01-19 20:00:03.000,6.791438e+09,6.049305e+09,7.421332e+08,6.745217e+09,6.095527e+09,6.496899e+08,...,1300861,1258051,1286798,1272090,510287,504671,1301117,1257911,Information Technology,2024-01-19
4,2024-01-19,29,2024-01-19 16:21:00.000,2024-01-19 20:00:03.000,2.003026e+08,2.303505e+08,-3.004787e+07,2.078789e+08,2.227742e+08,-1.489531e+07,...,72591,72792,72490,72892,28258,27977,72614,72787,Utilities,2024-01-19
5,2024-01-19,237,2024-01-19 18:52:00.000,2024-01-19 20:00:03.000,1.683247e+09,1.306000e+09,3.772469e+08,1.647895e+09,1.341352e+09,3.065427e+08,...,755664,741491,747605,749519,272488,270305,755742,741531,Industrials,2024-01-19
6,2024-01-19,184,2024-01-19 19:01:00.000,2024-01-19 20:00:03.000,1.412596e+09,1.386543e+09,2.605396e+07,1.386019e+09,1.413120e+09,-2.710131e+07,...,679967,678069,679716,678291,244200,241258,680147,677990,Consumer Discretionary,2024-01-19
7,2024-01-19,86,2024-01-19 19:01:00.000,2024-01-19 20:00:03.000,5.926878e+08,6.010801e+08,-8.392250e+06,5.968013e+08,5.969666e+08,-1.653170e+05,...,315664,302442,314605,303483,89913,86965,315875,302279,Real Estate,2024-01-19
8,2024-01-19,89,2024-01-19 19:13:00.000,2024-01-19 20:00:03.000,9.875897e+08,9.456867e+08,4.190303e+07,1.000816e+09,9.324604e+08,6.835557e+07,...,456451,450594,455472,451559,138055,136531,456553,450542,Energy,2024-01-19
9,2024-01-19,321,2024-01-19 19:29:00.000,2024-01-19 20:00:03.000,1.829483e+09,1.942666e+09,-1.131825e+08,1.873027e+09,1.899122e+09,-2.609481e+07,...,1181297,1185536,1179600,1187178,400995,399085,1181727,1185325,Health Care,2024-01-19

## Download data file for a specific date using asof_date

In [6]:
Unifier.replicate(name="lseg_us_equity_sector_flow_r2k_daily_v1_2_1", target_location="./data", asof_date='2025-03-07')

Downloading using native python implementation for lseg_us_equity_sector_flow_r2k_daily_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_equity_sector_flow_r2k_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_sector_flow_r2k_daily_v1_2_1", target_location="./data")