In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [5]:
df =  Unifier.get_dataframe(name="lseg_us_equity_sector_flow_r1k_daily_v1_2_1", back_to='2025-11-18', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2025-11-25,153,2025-11-25 18:58:00.000,2025-11-25 20:00:03.000,2.130339e+10,2.006722e+10,1.236171e+09,2.104189e+10,2.032871e+10,7.131761e+08,...,2987406,2968271,2979048,2976597,1256789,1254474,2987145,2968623,Financials,2025-11-25
1,2025-11-25,40,2025-11-25 19:01:00.000,2025-11-25 20:00:03.000,3.907908e+09,3.863759e+09,4.414848e+07,4.051086e+09,3.720581e+09,3.305053e+08,...,673979,698542,674369,698148,258593,258581,673951,698594,Utilities,2025-11-25
2,2025-11-25,61,2025-11-25 19:26:00.000,2025-11-25 20:00:03.000,3.765187e+09,3.866146e+09,-1.009588e+08,3.632540e+09,3.998793e+09,-3.662534e+08,...,789794,794133,787070,796854,305295,305976,789853,794109,Real Estate,2025-11-25
3,2025-11-25,51,2025-11-25 19:43:00.000,2025-11-25 20:00:03.000,4.971879e+09,4.714037e+09,2.578422e+08,4.735758e+09,4.950158e+09,-2.144001e+08,...,940771,943557,944071,940256,378031,375986,941196,943165,Materials,2025-11-25
4,2025-11-25,33,2025-11-25 19:51:00.000,2025-11-25 20:00:03.000,3.586906e+09,3.894967e+09,-3.080606e+08,3.585382e+09,3.896491e+09,-3.111086e+08,...,731572,737393,731519,737439,257240,257017,731791,737193,Energy,2025-11-25
5,2025-11-25,123,2025-11-25 19:55:00.000,2025-11-25 20:00:03.000,3.635134e+10,3.159292e+10,4.758420e+09,3.515268e+10,3.279157e+10,2.361103e+09,...,4011549,3834572,3936014,3910082,1786578,1779528,4019274,3826918,Consumer Discretionary,2025-11-25
6,2025-11-25,60,2025-11-25 19:55:00.000,2025-11-25 20:00:03.000,9.458139e+09,8.268927e+09,1.189213e+09,9.190601e+09,8.536465e+09,6.541367e+08,...,1611573,1499409,1587364,1523610,573332,568226,1611146,1499872,Consumer Staples,2025-11-25
7,2025-11-25,103,2025-11-25 19:58:00.000,2025-11-25 20:00:03.000,1.994919e+10,1.789954e+10,2.049645e+09,1.997539e+10,1.787334e+10,2.102048e+09,...,2309672,2225039,2298738,2235951,1066277,1062211,2307830,2226947,Health Care,2025-11-25
8,2025-11-25,47,2025-11-25 20:00:00.000,2025-11-25 20:00:03.000,3.488415e+10,3.280104e+10,2.083104e+09,3.422683e+10,3.345836e+10,7.684747e+08,...,2699530,2742772,2650462,2791832,1323145,1330693,2688188,2754136,Communication Services,2025-11-25
9,2025-11-25,173,2025-11-25 20:00:00.000,2025-11-25 20:00:03.000,2.011639e+10,1.916367e+10,9.527228e+08,1.929925e+10,1.998082e+10,-6.815646e+08,...,2774439,2760608,2773513,2761509,1314619,1310826,2773531,2761607,Industrials,2025-11-25

In [6]:
df = Unifier.get_dataframe(name="lseg_us_equity_sector_flow_r1k_daily_v1_2_1", back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,date,num_tickers,timestamp,asof_datetime,method1_inst_buy,method1_inst_sell,method1_net_flow,method2_inst_buy,method2_inst_sell,method2_net_flow,...,method2_inst_buy_count,method2_inst_sell_count,method3_inst_buy_count,method3_inst_sell_count,method4_inst_buy_count,method4_inst_sell_count,method5_inst_buy_count,method5_inst_sell_count,gics_sector,asof_date
0,2024-01-17,39,2024-01-17 19:01:00.000,2024-01-17 20:00:03.000,2.774293e+09,2.899451e+09,-1.251585e+08,2.820641e+09,2.853103e+09,-3.246212e+07,...,624575,619552,623022,621100,189150,190835,624732,619421,Utilities,2024-01-17
1,2024-01-17,60,2024-01-17 19:12:00.000,2024-01-17 20:00:03.000,3.463171e+09,3.391969e+09,7.120218e+07,3.436356e+09,3.418784e+09,1.757181e+07,...,725596,720805,719749,726641,267163,267896,725632,720809,Real Estate,2024-01-17
2,2024-01-17,106,2024-01-17 19:18:00.000,2024-01-17 20:00:03.000,1.150316e+10,1.119732e+10,3.058377e+08,1.168748e+10,1.101301e+10,6.744666e+08,...,1491259,1480534,1491957,1479828,644634,646404,1491629,1480227,Health Care,2024-01-17
3,2024-01-17,30,2024-01-17 19:50:00.000,2024-01-17 20:00:03.000,3.289734e+09,3.591506e+09,-3.017723e+08,3.387512e+09,3.493728e+09,-1.062157e+08,...,658189,678879,657456,679605,218269,220324,658359,678731,Energy,2024-01-17
4,2024-01-17,55,2024-01-17 19:53:00.000,2024-01-17 20:00:03.000,5.381157e+09,5.277099e+09,1.040578e+08,5.257724e+09,5.400532e+09,-1.428074e+08,...,896232,891796,892774,895244,324705,324976,896256,891808,Consumer Staples,2024-01-17
5,2024-01-17,150,2024-01-17 19:55:00.000,2024-01-17 20:00:03.000,1.557373e+10,1.433683e+10,1.236904e+09,1.508982e+10,1.482074e+10,2.690712e+08,...,2418156,2453721,2411856,2460005,895708,894730,2418702,2453244,Financials,2024-01-17
6,2024-01-17,122,2024-01-17 19:56:00.000,2024-01-17 20:00:03.000,2.136569e+10,1.980156e+10,1.564131e+09,2.102585e+10,2.014139e+10,8.844608e+08,...,2636029,2554358,2612717,2577654,1064962,1067444,2638437,2552021,Consumer Discretionary,2024-01-17
7,2024-01-17,41,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,9.495609e+09,9.169472e+09,3.261365e+08,9.329741e+09,9.335340e+09,-5.599565e+06,...,1162747,1134318,1155458,1141600,437248,439035,1162492,1134599,Communication Services,2024-01-17
8,2024-01-17,158,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1.205377e+10,1.232760e+10,-2.738313e+08,1.210761e+10,1.227376e+10,-1.661429e+08,...,1898432,1956147,1894171,1960394,800489,803423,1898264,1956408,Industrials,2024-01-17
9,2024-01-17,121,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,4.045440e+10,3.800416e+10,2.450237e+09,3.992118e+10,3.853738e+10,1.383793e+09,...,3356015,3258995,3348145,3266848,1500919,1502539,3354926,3260145,Information Technology,2024-01-17

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="lseg_us_equity_sector_flow_r1k_daily_v1_2_1", target_location="./data", asof_date='2025-03-04')

Downloading using native python implementation for lseg_us_equity_sector_flow_r1k_daily_v1_2_1...
Found 1 files to download.
Native replication completed for lseg_us_equity_sector_flow_r1k_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_sector_flow_r1k_daily_v1_2_1", target_location="./data")