In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="kalshi_trades_tick", asof_date='2026-10-21', limit=10)
display(df)

,trade_id,ticker,event_ticker,series_ticker,timestamp,date,yes_price,no_price,count,taker_price,notional_usd,taker_outcome_side,taker_book_side,is_block_trade,source_tier,asof_datetime,asof_date
0,07242b2e-4cf9-a643-4ad4-ad3a089774df,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 01:28:33.020,2026-10-21,0.0920,0.9080,1021.99,0.0920,94.0231,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
1,07242b2f-e6d9-9d2f-eaad-a529e9852427,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 01:29:00.511,2026-10-21,0.0920,0.9080,204.39,0.0920,18.8039,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
2,07242b2c-9c79-b143-6482-be5b0081d2cb,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 01:29:17.220,2026-10-21,0.0920,0.9080,223.12,0.0920,20.5270,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
3,07242b33-fed9-bf9f-a0b7-da4f67cb8e23,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 01:30:04.628,2026-10-21,0.0920,0.9080,255.49,0.0920,23.5051,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
4,07242b31-31f9-82af-55a3-094f2d0c630f,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 01:30:33.727,2026-10-21,0.0920,0.9080,51.09,0.0920,4.7003,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
5,07242b0f-c299-b61b-2f85-cdf25778df67,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 01:37:42.102,2026-10-21,0.0920,0.9080,107.05,0.0920,9.8486,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
6,072424bb-05a1-aff6-4f06-0eb566f66017,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 12:59:57.798,2026-10-21,0.0940,0.9060,200.07,0.0940,18.8066,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
7,072424ba-e101-864e-8363-9ce382a28fc7,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 13:00:28.891,2026-10-21,0.0940,0.9060,20.00,0.0940,1.8800,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
8,072424f2-5e71-a558-05dc-787cf2bd5440,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 13:15:05.074,2026-10-21,0.0940,0.9060,20.00,0.0940,1.8800,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21
9,072424f8-f771-a72c-f1b3-3fcacdfede54,CONTROLH-2026-R,CONTROLH-2026,CONTROLH,2026-10-21 13:16:49.529,2026-10-21,0.0940,0.9060,10.00,0.0940,0.9400,yes,bid,False,live,2026-10-22 02:16:31.306,2026-10-21

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='kalshi_trades_tick', back_to='2026-10-01', up_to='2026-10-21', limit=10)
display(df)

,trade_id,ticker,event_ticker,series_ticker,timestamp,date,yes_price,no_price,count,taker_price,notional_usd,taker_outcome_side,taker_book_side,is_block_trade,source_tier,asof_datetime,asof_date
0,072472df-6341-830e-4302-1508bd1f8495,KXAAAGASDCA-26OCT19-6.2200,KXAAAGASDCA-26OCT19,KXAAAGASDCA,2026-10-18 14:19:31.233,2026-10-18,0.0100,0.9900,26.17,0.9900,25.9083,no,ask,False,live,2026-10-19 11:46:05.695,2026-10-18
1,07247365-15c9-8adf-5004-f305c9829e60,KXAAAGASDCA-26OCT19-6.2200,KXAAAGASDCA-26OCT19,KXAAAGASDCA,2026-10-18 14:19:31.233,2026-10-18,0.0100,0.9900,100.00,0.9900,99.0000,no,ask,False,live,2026-10-19 11:46:05.695,2026-10-18
2,072472d2-44e1-9aaa-9426-ee123b858cd9,KXAAAGASDCA-26OCT19-6.2200,KXAAAGASDCA-26OCT19,KXAAAGASDCA,2026-10-18 14:20:18.351,2026-10-18,0.0100,0.9900,8.83,0.9900,8.7417,no,ask,False,live,2026-10-19 11:46:05.695,2026-10-18
3,072472eb-d249-99a5-917a-965910199adf,KXAAAGASDCA-26OCT19-6.2200,KXAAAGASDCA-26OCT19,KXAAAGASDCA,2026-10-18 14:20:18.351,2026-10-18,0.0100,0.9900,117.34,0.9900,116.1666,no,ask,False,live,2026-10-19 11:46:05.695,2026-10-18
4,072472b5-1001-8fb0-7d2e-00010f4bfce2,KXALLSVENSKANGAME-26OCT18ORGGAIS-GAIS,KXALLSVENSKANGAME-26OCT18ORGGAIS,KXALLSVENSKANGAME,2026-10-18 14:20:34.613,2026-10-18,0.6200,0.3800,100.55,0.6200,62.3410,yes,bid,False,live,2026-10-19 11:46:05.695,2026-10-18
5,0724737a-9911-8fc3-9c1d-1aac3a44ee14,KXALLSVENSKANTOTAL-26OCT18HALHIF-5,KXALLSVENSKANTOTAL-26OCT18HALHIF,KXALLSVENSKANTOTAL,2026-10-18 14:19:35.493,2026-10-18,0.2600,0.7400,1.00,0.2600,0.2600,yes,bid,False,live,2026-10-19 11:46:05.695,2026-10-18
6,072473c2-e609-b464-9925-ab3106cdea04,KXALLSVENSKANTOTAL-26OCT18MALHAC-4,KXALLSVENSKANTOTAL-26OCT18MALHAC,KXALLSVENSKANTOTAL,2026-10-18 14:20:16.725,2026-10-18,0.4100,0.5900,46.84,0.4100,19.2044,yes,bid,False,live,2026-10-19 11:46:05.695,2026-10-18
7,072473c7-81e9-8fb8-ed4c-fc15b8e18788,KXALLSVENSKANTOTAL-26OCT18MALHAC-4,KXALLSVENSKANTOTAL-26OCT18MALHAC,KXALLSVENSKANTOTAL,2026-10-18 14:20:59.742,2026-10-18,0.4100,0.5900,46.84,0.4100,19.2044,yes,bid,False,live,2026-10-19 11:46:05.695,2026-10-18
8,072472db-9bb9-b62c-7f8a-93fd6ba897fb,KXATPCHALLENGERMATCH-26OCT18YUZGUL-YUZ,KXATPCHALLENGERMATCH-26OCT18YUZGUL,KXATPCHALLENGERMATCH,2026-10-18 14:18:53.189,2026-10-18,0.0600,0.9400,575.00,0.9400,540.5000,no,ask,False,live,2026-10-19 11:46:05.695,2026-10-18
9,072472da-18b9-b6a8-4f1b-6a499ba0c512,KXATPCHALLENGERMATCH-26OCT18YUZGUL-YUZ,KXATPCHALLENGERMATCH-26OCT18YUZGUL,KXATPCHALLENGERMATCH,2026-10-18 14:18:53.189,2026-10-18,0.0600,0.9400,3.00,0.9400,2.8200,no,ask,False,live,2026-10-19 11:46:05.695,2026-10-18

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='kalshi_trades_tick',key='KXFEDDECISION-26OCT-H0', asof_date='2026-10-21', limit=10)
display(df)

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='kalshi_trades_tick',key='KXFEDDECISION-26OCT-H0', back_to='2026-10-01', up_to='2026-10-21', limit=10)
display(df)

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="kalshi_trades_tick", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_trades_tick...
Found 1 files to download.
Native replication completed for kalshi_trades_tick. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_trades_tick", target_location="./data")