In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name="kalshi_market_settlements", asof_date='2026-10-18', limit=10)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,settlement_bounds_type,settlement_floor,settlement_timer_seconds,is_provisional,volume,open_interest,last_price,source_tier,asof_datetime,asof_date
0,KX10YRDIRHM-27JAN01H-T5.01,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.01...,5.02% or above,5.02% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,4517.75,2181.75,0.9900,live,2026-10-08 12:05:34.357,2026-09-24
1,KX10YRDIRHM-27JAN01H-T5.02,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.02...,5.03% or above,5.03% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,1783.01,658.00,0.9300,live,2026-10-08 12:05:34.357,2026-09-24
2,KX10YRDIRHM-27JAN01H-T5.03,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.03...,5.04% or above,5.04% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,1249.65,612.06,0.9800,live,2026-10-08 12:05:34.357,2026-09-24
3,KX10YRDIRHM-27JAN01H-T5.04,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.04...,5.05% or above,5.05% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,619.70,326.22,0.9300,live,2026-10-08 12:05:34.357,2026-09-24
4,KX10YRDIRHM-27JAN01H-T5.05,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.05...,5.06% or above,5.06% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,871.00,668.00,0.9600,live,2026-10-08 12:05:34.357,2026-09-24
5,KX10YRDIRHM-27JAN01H-T5.06,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.06...,5.07% or above,5.07% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,404.00,103.00,0.8500,live,2026-10-08 12:05:34.357,2026-09-24
6,KX10YRDIRHM-27JAN01H-T5.07,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.07...,5.08% or above,5.08% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,2.00,2.00,0.8900,live,2026-10-08 12:05:34.357,2026-09-24
7,KX10YRDIRHM-27JAN01H-T5.08,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.08...,5.09% or above,5.09% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,1.00,1.00,0.7400,live,2026-10-08 12:05:34.357,2026-09-24
8,KX10YRDIRHM-27JAN01H-T5.09,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.09...,5.1% or above,5.1% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,101.00,101.00,0.7400,live,2026-10-08 12:05:34.357,2026-09-24
9,KX10YRDIRHM-27JAN01H-T5.10,KX10YRDIRHM-27JAN01H,KX10YRDIRHM,binary,Will the 10Y U.S. Treasury yield be above 5.10...,5.11% or above,5.11% or above,finalized,yes,2026-09-17 23:16:36.600,...,default,None,3600,None,577.00,472.00,0.9600,live,2026-10-08 12:05:34.357,2026-09-24

## Retrieve data for a specific date range using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='kalshi_market_settlements', back_to='2026-10-01', up_to='2026-10-18', limit=100)
display(df)

,ticker,event_ticker,series_ticker,market_type,title,yes_sub_title,no_sub_title,status,result,created_time,...,settlement_bounds_type,settlement_floor,settlement_timer_seconds,is_provisional,volume,open_interest,last_price,source_tier,asof_datetime,asof_date
0,KX2YRDIRLM-26OCT30L-T4.79,KX2YRDIRLM-26OCT30L,KX2YRDIRLM,binary,Will the 2-year U.S. Treasury yield be below 4...,4.78% or below,4.78% or below,finalized,yes,2026-09-30 21:15:35.322,...,default,None,3600,None,1900.00,1900.00,0.9900,live,2026-10-08 12:05:34.357,2026-10-01
1,KX2YRDIRLM-26OCT30L-T4.80,KX2YRDIRLM-26OCT30L,KX2YRDIRLM,binary,Will the 2-year U.S. Treasury yield be below 4...,4.79% or below,4.79% or below,finalized,yes,2026-09-30 21:15:35.322,...,default,None,3600,None,1100.00,1100.00,0.9900,live,2026-10-08 12:05:34.357,2026-10-01
2,KX2YRDIRLM-26OCT30L-T4.81,KX2YRDIRLM-26OCT30L,KX2YRDIRLM,binary,Will the 2-year U.S. Treasury yield be below 4...,4.8% or below,4.8% or below,finalized,yes,2026-09-30 21:15:35.322,...,default,None,3600,None,1100.00,1100.00,0.9900,live,2026-10-08 12:05:34.357,2026-10-01
3,KX2YRDIRLM-26OCT30L-T4.82,KX2YRDIRLM-26OCT30L,KX2YRDIRLM,binary,Will the 2-year U.S. Treasury yield be below 4...,4.81% or below,4.81% or below,finalized,yes,2026-09-30 21:15:35.322,...,default,None,3600,None,2547.19,2547.19,0.9900,live,2026-10-08 12:05:34.357,2026-10-01
4,KX2YRDIRLM-26OCT30L-T4.83,KX2YRDIRLM-26OCT30L,KX2YRDIRLM,binary,Will the 2-year U.S. Treasury yield be below 4...,4.82% or below,4.82% or below,finalized,yes,2026-09-30 21:15:35.322,...,default,None,3600,None,1000.00,1000.00,0.9900,live,2026-10-08 12:05:34.357,2026-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,KXAAAGASDAZ-26OCT01-4.8000,KXAAAGASDAZ-26OCT01,KXAAAGASDAZ,binary,Will average **gas prices** be above $4.8000?,Above 4.8000,Above 4.8000,finalized,no,2026-09-30 10:00:47.388,...,default,None,300,None,0.00,0.00,0.0000,live,2026-10-08 12:05:34.357,2026-10-01
96,KXAAAGASDAZ-26OCT01-4.8050,KXAAAGASDAZ-26OCT01,KXAAAGASDAZ,binary,Will average **gas prices** be above $4.8050?,Above 4.8050,Above 4.8050,finalized,no,2026-09-30 10:00:47.388,...,default,None,300,None,1900.00,1900.00,0.0300,live,2026-10-08 12:05:34.357,2026-10-01
97,KXAAAGASDAZ-26OCT01-4.8100,KXAAAGASDAZ-26OCT01,KXAAAGASDAZ,binary,Will average **gas prices** be above $4.8100?,Above 4.8100,Above 4.8100,finalized,no,2026-09-30 10:00:47.388,...,default,None,300,None,0.00,0.00,0.0000,live,2026-10-08 12:05:34.357,2026-10-01
98,KXAAAGASDAZ-26OCT01-4.8150,KXAAAGASDAZ-26OCT01,KXAAAGASDAZ,binary,Will average **gas prices** be above $4.8150?,Above 4.8150,Above 4.8150,finalized,no,2026-09-30 10:00:47.388,...,default,None,300,None,1143.00,1143.00,0.0100,live,2026-10-08 12:05:34.357,2026-10-01
99,KXAAAGASDAZ-26OCT01-4.8200,KXAAAGASDAZ-26OCT01,KXAAAGASDAZ,binary,Will average **gas prices** be above $4.8200?,Above 4.8200,Above 4.8200,finalized,no,2026-09-30 10:00:47.388,...,default,None,300,None,4240.00,2640.00,0.0100,live,2026-10-08 12:05:34.357,2026-10-01

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [12]:
df = Unifier.get_dataframe(name='kalshi_market_settlements',key='KXNFLGAME-26OCT18BUFLV-LV', asof_date='2026-10-18', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [13]:
df = Unifier.get_dataframe(name='kalshi_market_settlements',key='KXNFLGAME-26OCT18BUFLV-LV', back_to='2026-10-01', up_to='2026-10-18', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [14]:
Unifier.replicate(name="kalshi_market_settlements", target_location="./data", asof_date='2026-10-18')

Downloading using native python implementation for kalshi_market_settlements...
Found 1 files to download.
Native replication completed for kalshi_market_settlements. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_market_settlements", target_location="./data")