In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name="kalshi_events_daily", asof_date='2026-10-21', limit=10)
display(df)

,event_ticker,series_ticker,title,sub_title,category,mutually_exclusive,collateral_return_type,strike_date,strike_period,settlement_sources,fee_type_override,fee_multiplier_override,last_updated_ts,exchange_index,asof_datetime,asof_date
0,AMAZONFTC-29DEC31,KXAMAZONFTC,Courts consider Amazon a monopoly?,Before 2030,Politics,False,NaN,None,None,"[{""name"":""PACER"",""url"":""https://pacer.uscourts...",None,None,2026-08-27 23:24:25.229,0,2026-10-21 04:11:00.804,2026-10-21
1,APPLEUS,KXAPPLEUS,Courts consider Apple a monopoly?,Before 2030,Companies,False,NaN,None,None,"[{""name"":""PACER"",""url"":""https://pacer.uscourts...",None,None,2026-10-16 03:27:45.997,0,2026-10-21 04:11:00.804,2026-10-21
2,BEYONCEGENRE-30,KXBEYONCEGENRE,What genre will Beyonce’s next album be?,Next Beyonce album genre,Entertainment,False,NaN,None,None,"[{""name"":""Billboard"",""url"":""https://www.billbo...",None,None,2026-10-16 03:27:45.997,0,2026-10-21 04:11:00.804,2026-10-21
3,BILLBOARDPEAKLLL-24SEP07,KXBILLBOARDPEAKLLL,"""Lies Lies Lies"" peak on Billboard Hot 100 by ...","By Sep 7, 2024 chart",Entertainment,False,NaN,None,None,"[{""name"":""Billboard"",""url"":""https://www.billbo...",None,None,2026-10-16 03:57:49.924,0,2026-10-21 04:11:00.804,2026-10-21
4,BILLBOARDPEAKWW-24SEP14,KXBILLBOARDPEAKWW,"""Woman's World"" peak on Billboard Hot 100 by S...","By Sep 14, 2024 chart",Entertainment,False,NaN,None,None,"[{""name"":""Billboard"",""url"":""https://www.billbo...",None,None,2026-10-16 03:57:49.924,0,2026-10-21 04:11:00.804,2026-10-21
5,CBVOLUME-24-Q1,KXCBVOLUME,Coinbase volume in Q1 2024?,In Q1 2024,Companies,False,NaN,None,None,"[{""name"":""Coinbase"",""url"":""https://investor.co...",None,None,2026-10-16 03:57:49.924,0,2026-10-21 04:11:00.804,2026-10-21
6,CHINAUSGDP,KXCHINAUSGDP,China overtakes USA’s economy by 2030?,By 2030,Economics,False,NaN,None,None,"[{""name"":""IMF"",""url"":""https://www.imf.org/en/P...",None,None,2026-10-16 03:29:33.021,0,2026-10-21 04:11:00.804,2026-10-21
7,CONTROLH-2026,CONTROLH,Which party will win the U.S. House?,In 2026,Elections,True,MECNET,None,None,"[{""name"":""Library of Congress"",""url"":""https://...",None,None,2026-08-28 01:38:04.373,0,2026-10-21 04:11:00.804,2026-10-21
8,CONTROLH-2028,CONTROLH,2028 House winner,In 2028,Elections,True,MECNET,None,None,"[{""name"":""Library of Congress"",""url"":""https://...",None,None,2026-08-28 01:38:04.373,0,2026-10-21 04:11:00.804,2026-10-21
9,CONTROLS-2026,CONTROLS,Which party will win the U.S. Senate?,In 2026,Elections,True,MECNET,None,None,"[{""name"":""Library of Congress"",""url"":""https://...",None,None,2026-09-28 17:53:29.955,0,2026-10-21 04:11:00.804,2026-10-21

## Retrieve data for a specific date range using the back_to and up_to parameters

In [20]:
df = Unifier.get_dataframe(name='kalshi_events_daily', back_to='2026-10-19', up_to='2026-10-22', limit=100)
display(df)

,event_ticker,series_ticker,title,sub_title,category,mutually_exclusive,collateral_return_type,strike_date,strike_period,settlement_sources,fee_type_override,fee_multiplier_override,last_updated_ts,exchange_index,asof_datetime,asof_date
0,AMAZONFTC-29DEC31,KXAMAZONFTC,Courts consider Amazon a monopoly?,Before 2030,Politics,False,NaN,NaN,None,"[{""name"":""PACER"",""url"":""https://pacer.uscourts...",None,None,2026-08-27 23:24:25.229,0,2026-10-19 10:33:32.802,2026-10-19
1,APPLEUS,KXAPPLEUS,Courts consider Apple a monopoly?,Before 2030,Companies,False,NaN,NaN,None,"[{""name"":""PACER"",""url"":""https://pacer.uscourts...",None,None,2026-10-16 03:27:45.997,0,2026-10-19 10:33:32.802,2026-10-19
2,BEYONCEGENRE-30,KXBEYONCEGENRE,What genre will Beyonce’s next album be?,Next Beyonce album genre,Entertainment,False,NaN,NaN,None,"[{""name"":""Billboard"",""url"":""https://www.billbo...",None,None,2026-10-16 03:27:45.997,0,2026-10-19 10:33:32.802,2026-10-19
3,BILLBOARDPEAKLLL-24SEP07,KXBILLBOARDPEAKLLL,"""Lies Lies Lies"" peak on Billboard Hot 100 by ...","By Sep 7, 2024 chart",Entertainment,False,NaN,NaN,None,"[{""name"":""Billboard"",""url"":""https://www.billbo...",None,None,2026-10-16 03:57:49.924,0,2026-10-19 10:33:32.802,2026-10-19
4,BILLBOARDPEAKWW-24SEP14,KXBILLBOARDPEAKWW,"""Woman's World"" peak on Billboard Hot 100 by S...","By Sep 14, 2024 chart",Entertainment,False,NaN,NaN,None,"[{""name"":""Billboard"",""url"":""https://www.billbo...",None,None,2026-10-16 03:57:49.924,0,2026-10-19 10:33:32.802,2026-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,HOUSEIN1-26,HOUSEIN1,IN-01 House winner?,In 2026,Elections,True,MECNET,NaN,None,"[{""name"":""Library of Congress"",""url"":""https://...",None,None,2026-08-27 12:34:23.078,0,2026-10-19 10:33:32.802,2026-10-19
96,HOUSEME2-26,HOUSEME2,ME-02 House winner?,In 2026,Elections,True,MECNET,NaN,None,"[{""name"":""Library of Congress"",""url"":""https://...",None,None,2026-09-10 20:17:18.080,0,2026-10-19 10:33:32.802,2026-10-19
97,HOUSEMI10-26,HOUSEMI10,MI-10 House winner?,In 2026,Elections,True,MECNET,NaN,None,"[{""name"":""Library of Congress"",""url"":""https://...",None,None,2026-09-10 20:17:18.143,0,2026-10-19 10:33:32.802,2026-10-19
98,HOUSEMI3-26,HOUSEMI3,MI-03 House winner?,In 2026,Elections,True,MECNET,NaN,None,"[{""name"":""Library of Congress"",""url"":""https://...",None,None,2026-09-10 20:17:18.199,0,2026-10-19 10:33:32.802,2026-10-19
99,HOUSEMI4-26,HOUSEMI4,MI-04 House winner?,In 2026,Elections,True,MECNET,NaN,None,"[{""name"":""Library of Congress"",""url"":""https://...",None,None,2026-09-10 20:17:18.258,0,2026-10-19 10:33:32.802,2026-10-19

## Retrieve data for a specific date with a specific event_ticker (key='event_ticker') using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name='kalshi_events_daily',key='KXFED-26DEC', asof_date='2026-10-21', limit=100)
display(df)

,event_ticker,series_ticker,title,sub_title,category,mutually_exclusive,collateral_return_type,strike_date,strike_period,settlement_sources,fee_type_override,fee_multiplier_override,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXFED-26DEC,KXFED,Fed funds rate after Dec 2026 meeting?,"On Dec 9, 2026",Economics,False,DIRECNET,2026-12-09 19:00:00.000,NaN,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 13:58:06.438,0,2026-10-19 10:33:32.802,2026-10-19
1,KXFED-26DEC,KXFED,Fed funds rate after Dec 2026 meeting?,"On Dec 9, 2026",Economics,False,DIRECNET,2026-12-09 19:00:00.000,,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-09-30 19:09:10.108,0,2026-10-08 12:04:30.069,2026-10-08

## Retrieve data for a specific date range with a specific event_ticker (key='event_ticker') using the back_to and up_to parameters

In [22]:
df = Unifier.get_dataframe(name='kalshi_events_daily',key='KXFED-26DEC', back_to='2026-10-19', up_to='2026-10-21', limit=100)
display(df)

,event_ticker,series_ticker,title,sub_title,category,mutually_exclusive,collateral_return_type,strike_date,strike_period,settlement_sources,fee_type_override,fee_multiplier_override,last_updated_ts,exchange_index,asof_datetime,asof_date
0,KXFED-26DEC,KXFED,Fed funds rate after Dec 2026 meeting?,"On Dec 9, 2026",Economics,False,DIRECNET,2026-12-09 19:00:00.000,None,"[{""name"":""Federal Reserve Board of Governors"",...",None,None,2026-10-15 13:58:06.438,0,2026-10-19 10:33:32.802,2026-10-19

## Download data file for a specific date using asof_date

In [23]:
Unifier.replicate(name="kalshi_events_daily", target_location="./data", asof_date='2026-10-19')

Downloading using native python implementation for kalshi_events_daily...
Found 1 files to download.
Native replication completed for kalshi_events_daily. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_events_daily", target_location="./data")