In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="kalshi_candles_1d", asof_date='2026-10-22', limit=10)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,AMAZONFTC-29DEC31,1440,2026-10-19 04:00:00.000,2026-10-19,0.4600,0.4800,0.4400,0.4600,0.5300,0.5300,...,0.4800,0.4400,0.4600,0.4617,0.5300,9.94,6859.11,live,2026-10-21 14:44:50.203,2026-10-19
1,APPLEUS-29DEC31,1440,2026-10-19 04:00:00.000,2026-10-19,0.2800,0.2800,0.2500,0.2700,0.3100,0.3100,...,0.2900,0.2700,0.2700,0.2766,0.2700,12.33,7636.23,live,2026-10-21 14:44:50.203,2026-10-19
2,BEYONCEGENRE-30-TGA,1440,2026-10-19 04:00:00.000,2026-10-19,0.1700,0.1700,0.1600,0.1700,0.2500,0.2500,...,NaN,NaN,NaN,NaN,0.2400,0.00,105.16,live,2026-10-21 14:44:50.203,2026-10-19
3,CONTROLH-2026-D,1440,2026-10-19 04:00:00.000,2026-10-19,0.9010,0.9010,0.9000,0.9010,0.9020,0.9020,...,0.9020,0.9000,0.9010,0.9016,0.9020,198238.51,13816790.87,live,2026-10-21 14:44:50.203,2026-10-19
4,CONTROLH-2026-R,1440,2026-10-19 04:00:00.000,2026-10-19,0.1000,0.1000,0.1000,0.1000,0.1100,0.1100,...,0.1100,0.1000,0.1100,0.1083,0.1100,345759.32,29635571.50,live,2026-10-21 14:44:50.203,2026-10-19
5,CONTROLH-2028-D,1440,2026-10-19 04:00:00.000,2026-10-19,0.7500,0.7500,0.7500,0.7500,0.7600,0.7600,...,0.7600,0.7600,0.7600,0.7600,0.7600,6.47,8464.43,live,2026-10-21 14:44:50.203,2026-10-19
6,CONTROLH-2028-R,1440,2026-10-19 04:00:00.000,2026-10-19,0.2600,0.2600,0.2600,0.2600,0.2700,0.2700,...,0.2700,0.2700,0.2700,0.2700,0.2700,17.61,7271.78,live,2026-10-21 14:44:50.203,2026-10-19
7,CONTROLS-2026-D,1440,2026-10-19 04:00:00.000,2026-10-19,0.6200,0.6200,0.6200,0.6200,0.6300,0.6300,...,0.6300,0.6200,0.6300,0.6282,0.6300,27241.95,3547893.58,live,2026-10-21 14:44:50.203,2026-10-19
8,CONTROLS-2026-R,1440,2026-10-19 04:00:00.000,2026-10-19,0.3700,0.3800,0.3700,0.3800,0.3800,0.3900,...,0.3900,0.3700,0.3900,0.3869,0.3700,98808.21,5584313.95,live,2026-10-21 14:44:50.203,2026-10-19
9,CONTROLS-2028-D,1440,2026-10-19 04:00:00.000,2026-10-19,0.5300,0.5300,0.5300,0.5300,0.5400,0.5400,...,NaN,NaN,NaN,NaN,0.5400,0.00,1017.91,live,2026-10-21 14:44:50.203,2026-10-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='kalshi_candles_1d', back_to='2026-10-01', up_to='2026-10-22', limit=100)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,APPLEUS-29DEC31,1440,2026-10-21 04:00:00.000,2026-10-21,0.2300,0.2800,0.2300,0.2700,0.2900,0.3100,...,0.3100,0.2800,0.2800,0.2957,0.2400,23.03,7614.21,live,2026-10-22 03:09:20.167,2026-10-21
1,CHINAUSGDP-30,1440,2026-10-21 04:00:00.000,2026-10-21,0.1900,0.1900,0.1900,0.1900,0.2100,0.2100,...,NaN,NaN,NaN,NaN,0.2200,0.00,42503.68,live,2026-10-22 03:09:20.167,2026-10-21
2,CONTROLH-2026-D,1440,2026-10-21 04:00:00.000,2026-10-21,0.9010,0.9080,0.9010,0.9070,0.9020,0.9100,...,0.9100,0.9010,0.9080,0.9035,0.9020,280833.59,14135172.41,live,2026-10-22 03:09:20.167,2026-10-21
3,CONTROLH-2026-R,1440,2026-10-21 04:00:00.000,2026-10-21,0.0990,0.0990,0.0880,0.0930,0.1000,0.1000,...,0.1000,0.0880,0.0940,0.0948,0.1000,1219061.58,31036687.51,live,2026-10-22 03:09:20.167,2026-10-21
4,CONTROLH-2028-D,1440,2026-10-21 04:00:00.000,2026-10-21,0.7500,0.7500,0.7200,0.7200,0.7600,0.7600,...,0.7500,0.7300,0.7300,0.7447,0.7600,1246.94,8973.78,live,2026-10-22 03:09:20.167,2026-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,HOUSECA13-26-R,1440,2026-10-21 04:00:00.000,2026-10-21,0.0460,0.0540,0.0230,0.0500,0.0570,0.0750,...,0.0730,0.0450,0.0730,0.0713,0.0720,1106.60,6679.44,live,2026-10-22 03:09:20.167,2026-10-21
96,HOUSECA21-26-D,1440,2026-10-21 04:00:00.000,2026-10-21,0.9430,0.9460,0.9380,0.9440,0.9470,0.9470,...,0.9460,0.9460,0.9460,0.9460,0.9470,30.00,3443.20,live,2026-10-22 03:09:20.167,2026-10-21
97,HOUSECA21-26-R,1440,2026-10-21 04:00:00.000,2026-10-21,0.0490,0.0510,0.0490,0.0500,0.0510,0.0520,...,0.0510,0.0510,0.0510,0.0510,0.0500,63.01,18978.54,live,2026-10-22 03:09:20.167,2026-10-21
98,HOUSECA22-26-D,1440,2026-10-21 04:00:00.000,2026-10-21,0.8900,0.8900,0.8800,0.8900,0.9010,0.9010,...,0.9010,0.9000,0.9000,0.9001,0.8800,40.80,41761.92,live,2026-10-22 03:09:20.167,2026-10-21
99,HOUSECA22-26-R,1440,2026-10-21 04:00:00.000,2026-10-21,0.0960,0.1100,0.0870,0.1100,0.1100,0.1200,...,0.1200,0.1100,0.1200,0.1199,0.1200,1398.84,53524.05,live,2026-10-22 03:09:20.167,2026-10-21

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name='kalshi_candles_1d',key='KXFEDDECISION-26OCT-H0', asof_date='2026-10-22', limit=100)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXFEDDECISION-26OCT-H0,1440,2026-10-19 04:00:00.000,2026-10-19,0.8600,0.8600,0.8600,0.8600,0.8700,0.8700,...,0.8700,0.8600,0.8700,0.8679,0.8600,28757.58,1827302.25,live,2026-10-21 14:44:50.203,2026-10-19
1,KXFEDDECISION-26OCT-H0,1440,2026-10-20 04:00:00.000,2026-10-20,0.8600,0.8600,0.8500,0.8500,0.8700,0.8700,...,0.8700,0.8500,0.8600,0.8607,0.8700,114290.40,1910364.48,live,2026-10-22 03:11:05.100,2026-10-20
2,KXFEDDECISION-26OCT-H0,1440,2026-10-21 04:00:00.000,2026-10-21,0.8500,0.8700,0.8500,0.8700,0.8600,0.8800,...,0.8800,0.8500,0.8800,0.8737,0.8600,141397.97,2025347.01,live,2026-10-22 03:09:20.167,2026-10-21

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='kalshi_candles_1d',key='KXFEDDECISION-26OCT-H0', back_to='2026-10-01', up_to='2026-10-22', limit=100)
display(df)

,ticker,period_minutes,timestamp,date,yes_bid_open,yes_bid_high,yes_bid_low,yes_bid_close,yes_ask_open,yes_ask_high,...,price_high,price_low,price_close,price_mean,price_previous,volume,open_interest,source_tier,asof_datetime,asof_date
0,KXFEDDECISION-26OCT-H0,1440,2026-10-19 04:00:00.000,2026-10-19,0.8600,0.8600,0.8600,0.8600,0.8700,0.8700,...,0.8700,0.8600,0.8700,0.8679,0.8600,28757.58,1827302.25,live,2026-10-21 14:44:50.203,2026-10-19
1,KXFEDDECISION-26OCT-H0,1440,2026-10-20 04:00:00.000,2026-10-20,0.8600,0.8600,0.8500,0.8500,0.8700,0.8700,...,0.8700,0.8500,0.8600,0.8607,0.8700,114290.40,1910364.48,live,2026-10-22 03:11:05.100,2026-10-20
2,KXFEDDECISION-26OCT-H0,1440,2026-10-21 04:00:00.000,2026-10-21,0.8500,0.8700,0.8500,0.8700,0.8600,0.8800,...,0.8800,0.8500,0.8800,0.8737,0.8600,141397.97,2025347.01,live,2026-10-22 03:09:20.167,2026-10-21

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="kalshi_candles_1d", target_location="./data", asof_date='2026-10-21')

Downloading using native python implementation for kalshi_candles_1d...
Found 1 files to download.
Native replication completed for kalshi_candles_1d. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="kalshi_candles_1d", target_location="./data")