In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [2]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.17)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (3.0.0)
Requirement already satisfied: boto3 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (1.42.66)
Requirement already satisfied: botocore<1.43.0,>=1.42.66 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (1.42.66)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from botocore<1.43.0,>=1.42.66->boto3->unifier) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from botocore<1.43.0,>=1.42.66->boto3->unifier) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.66->boto3->unifier) (1.17.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.4.1)
Requirement already satisfied: tzdata in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_etf_options_flow_1min_v2_2", asof_date='2024-01-18', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Call,2,7,...,0,1,0,0,0,0.00,0.4472,0,0.0000,2021-06-29
1,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Call,2,7,...,0,1,0,0,0,0.00,0.0403,0,0.0000,2021-06-29
2,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Call,2,7,...,0,1,0,0,0,0.00,0.0690,0,0.0000,2021-06-29
3,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Call,2,7,...,0,0,0,3,3,0.14,0.0000,0,0.1278,2021-06-29
4,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Call,9,7,...,0,1,0,0,0,0.00,0.0969,0,0.0000,2021-06-29
5,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Put,9,7,...,0,3,0,0,0,0.00,2.2287,0,0.0000,2021-06-29
6,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Call,9,7,...,0,0,0,1,1,1.20,0.0000,0,0.1030,2021-06-29
7,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Call,9,7,...,0,0,0,1,1,1.11,0.0000,0,0.1033,2021-06-29
8,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Call,16,7,...,0,1,0,2,2,16.70,0.0852,0,0.0213,2021-06-29
9,2021-06-29,2021-06-29 23:30:30.000,2021-06-29 13:31:00.000,XLK,XLK,RegularMkt,EQT,Put,16,7,...,0,1,0,0,0,0.00,0.0532,0,0.0000,2021-06-29

## Retrieve data for a specific date range using the back_to and up_to parameters

In [12]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_1min_v2_2', back_to='2022-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Put,15,9,...,0,1,0,0,0,0.00,0.009005,0,0.000000,2023-09-12
1,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Call,15,9,...,0,1,0,0,0,0.00,0.004803,0,0.000000,2023-09-12
2,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Put,20,10,...,0,0,0,1,1,1.30,0.000000,0,0.037033,2023-09-12
3,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Call,20,10,...,0,1,0,0,0,0.00,0.023664,0,0.000000,2023-09-12
4,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Put,27,10,...,0,0,0,1,1,0.98,0.000000,0,0.037531,2023-09-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:40:00.000,KWEB,KWEB,RegularMkt,EQT,Put,17,11,...,0,0,0,1,1,0.36,0.000000,0,0.027472,2023-09-12
96,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:40:00.000,KWEB,KWEB,RegularMkt,EQT,Call,19,1,...,0,0,0,3,8,3.20,0.000000,0,0.510119,2023-09-12
97,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:51:00.000,KWEB,KWEB,RegularMkt,EQT,Call,29,9,...,0,0,0,3,15,1.04,0.000000,0,0.381314,2023-09-12
98,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:51:00.000,KWEB,KWEB,RegularMkt,EQT,Call,20,10,...,0,0,0,1,20,0.73,0.000000,0,0.690766,2023-09-12
99,2023-09-12,2023-09-12 23:30:30.000,2023-09-12 13:52:00.000,KWEB,KWEB,RegularMkt,EQT,Call,22,9,...,0,0,0,1,1,0.41,0.000000,0,0.019036,2023-09-12

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [14]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_1min_v2_2',key='KWEB', asof_date='2023-09-12', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2019-02-08,2019-02-08 23:30:30.000,2019-02-08 14:31:00.000,KWEB,KWEB,RegularMkt,EQT,Put,15,2,...,0,0,0,1,1,10.90,0.0000,0,0.0000,2019-02-08
1,2019-02-08,2019-02-08 23:30:30.000,2019-02-08 14:32:00.000,KWEB,KWEB,RegularMkt,EQT,Put,18,4,...,0,1,0,0,0,0.00,0.1498,0,0.0000,2019-02-08
2,2019-02-08,2019-02-08 23:30:30.000,2019-02-08 14:32:00.000,KWEB,KWEB,RegularMkt,EQT,Put,18,4,...,0,1,0,0,0,0.00,0.0828,0,0.0000,2019-02-08
3,2019-02-08,2019-02-08 23:30:30.000,2019-02-08 14:34:00.000,KWEB,KWEB,RegularMkt,EQT,Call,15,2,...,0,1,0,0,0,0.00,0.0231,0,0.0000,2019-02-08
4,2019-02-08,2019-02-08 23:30:30.000,2019-02-08 14:34:00.000,KWEB,KWEB,RegularMkt,EQT,Call,15,2,...,0,1,0,0,0,0.00,0.0167,0,0.0000,2019-02-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-02-11,2019-02-11 23:30:30.000,2019-02-11 14:37:00.000,KWEB,KWEB,RegularMkt,EQT,Call,18,4,...,0,0,0,1,2,1.82,0.0000,0,0.1510,2019-02-11
96,2019-02-11,2019-02-11 23:30:30.000,2019-02-11 14:39:00.000,KWEB,KWEB,RegularMkt,EQT,Put,15,2,...,0,0,0,1,1,0.95,0.0000,0,0.0223,2019-02-11
97,2019-02-11,2019-02-11 23:30:30.000,2019-02-11 14:40:00.000,KWEB,KWEB,RegularMkt,EQT,Call,15,2,...,0,0,0,1,3,0.50,0.0000,0,0.0666,2019-02-11
98,2019-02-11,2019-02-11 23:30:30.000,2019-02-11 15:02:00.000,KWEB,KWEB,RegularMkt,EQT,Call,17,5,...,0,0,0,1,25,5.13,0.0000,0,1.9050,2019-02-11
99,2019-02-11,2019-02-11 23:30:30.000,2019-02-11 15:05:00.000,KWEB,KWEB,RegularMkt,EQT,Call,15,2,...,0,1,0,0,0,0.00,0.2190,0,0.0000,2019-02-11

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [15]:
df = Unifier.get_dataframe(name='xtech_us_etf_options_flow_1min_v2_2',key='KWEB', back_to='2022-01-01', up_to='2024-06-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Call,1,9,...,0,1,0,0,0,0.000000,0.003172,0,0.000000,2023-08-30
1,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Put,1,9,...,0,1,0,0,0,0.000000,0.002035,0,0.000000,2023-08-30
2,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Put,1,9,...,0,0,0,1,10,0.370000,0.000000,0,0.114417,2023-08-30
3,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Call,1,9,...,0,1,0,3,20,0.080000,0.014065,0,0.124473,2023-08-30
4,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:31:00.000,KWEB,KWEB,RegularMkt,EQT,Put,8,9,...,0,0,0,1,1,0.410000,0.000000,0,0.015198,2023-08-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:37:00.000,KWEB,KWEB,RegularMkt,EQT,Call,1,9,...,0,0,0,9,19,0.340000,0.000000,0,0.211962,2023-08-30
96,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:37:00.000,KWEB,KWEB,RegularMkt,EQT,Put,1,9,...,0,0,0,4,25,0.560000,0.000000,0,0.281147,2023-08-30
97,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:37:00.000,KWEB,KWEB,RegularMkt,EQT,Call,1,9,...,0,0,0,1,2,0.100000,0.000000,0,0.014084,2023-08-30
98,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:37:00.000,KWEB,KWEB,RegularMkt,EQT,Put,8,9,...,0,0,0,2,3,0.396667,0.000000,0,0.049937,2023-08-30
99,2023-08-30,2023-08-30 23:30:30.000,2023-08-30 13:37:00.000,KWEB,KWEB,RegularMkt,EQT,Call,8,9,...,0,1,0,0,0,0.000000,0.017969,0,0.000000,2023-08-30

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_etf_options_flow_1min_v2_2", target_location="./data", asof_date='2026-01-13')

Starting native python replication for xtech_us_etf_options_flow_1min_v2_2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_etf_options_flow_1min_v2_2. Downloaded 1 files.