In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [4]:
Unifier.user = 'demo'
Unifier.token ='qZy7KpE+L5Fg2MmjFqC/1xmweo7pgnnACCcK3JNEAec='
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_with_isin_daily", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2012-07-25,2012-07-25 13:57:00.000,2012-07-25 20:00:03.000,0,FLG,US34416W6012,11,6.678056e+04,20832.00,18214.00,...,2,22129.00,16917.00,2,3,27734.56,0.00,2,0,2012-07-25
1,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,1,ACAS,US02503Y1038,13075,2.428396e+07,13807026.29,9993459.77,...,1395,11898174.21,11902311.87,556,670,173917.34,309560.27,63,160,2012-07-25
2,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,0,ADES,US00770C1018,415,1.232770e+06,590941.24,555260.03,...,117,998647.97,147553.29,353,62,53232.83,33335.98,16,5,2012-07-25
3,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,0,ANGI,US0347541015,2073,4.186294e+06,2267946.75,1784266.77,...,418,2007198.84,2045014.66,191,193,87882.65,46197.72,37,24,2012-07-25
4,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,0,ANV,US0193441005,6009,2.052999e+07,10800934.32,9275130.14,...,1264,12239735.94,7836328.52,3623,2201,356795.49,97133.18,94,23,2012-07-25
5,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,1,ATRS,US0366421065,3986,5.124586e+06,2420482.00,2396983.55,...,569,3164463.74,1653001.79,2523,1082,161078.29,146042.48,122,102,2012-07-25
6,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,0,CCMP,US12709P1030,1399,5.235246e+06,2868312.25,2204734.81,...,363,2521520.20,2551526.90,122,118,102481.08,59717.56,26,14,2012-07-25
7,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,0,DAKT,US2342641097,479,7.475629e+05,245932.24,436484.64,...,115,363371.11,319045.78,53,43,15591.75,49554.31,6,26,2012-07-25
8,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,1,EBTC,US2936681095,29,8.770280e+04,32262.51,55440.29,...,14,34685.51,53017.29,2,8,0.00,0.00,0,0,2012-07-25
9,2012-07-25,2012-07-25 16:00:00.000,2012-07-25 20:00:03.000,0,FLDM,US34385P1084,406,8.013512e+05,292512.28,478106.17,...,100,271787.63,498830.82,127,220,15453.71,15279.03,5,6,2012-07-25

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_daily', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-10,2024-01-10 16:00:00.000,2024-01-10 20:00:03.000,1,ACRV,US0048901096,339,6.622361e+04,23858.14,40322.66,...,117,31303.18,32877.59,3,7,573.15,1469.68,4,6,2024-01-10
1,2024-01-10,2024-01-10 16:00:00.000,2024-01-10 20:00:03.000,0,HQI,US4335351015,300,2.120845e+05,53743.54,157889.34,...,95,51022.03,160610.87,35,265,338.75,112.89,4,1,2024-01-10
2,2024-01-10,2024-01-10 16:01:00.000,2024-01-10 20:00:03.000,0,OVLY,US6718071052,233,2.028531e+05,107531.41,85489.34,...,96,1103.95,191916.81,17,215,396.32,9435.98,4,9,2024-01-10
3,2024-01-10,2024-01-10 16:01:00.000,2024-01-10 20:00:03.000,0,PWOD,US7084301032,444,3.150739e+05,91230.77,209847.71,...,146,154589.81,146488.82,1,3,1312.46,12682.98,3,13,2024-01-10
4,2024-01-10,2024-01-10 16:01:00.000,2024-01-10 20:00:03.000,0,SSBK,US8438783073,258,2.581333e+05,104239.06,146464.28,...,90,67520.62,183182.75,41,112,3900.56,3529.37,8,4,2024-01-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-10,2024-01-10 19:00:00.000,2024-01-10 20:00:03.000,1,EXPD,US3021301094,23292,1.172836e+08,49123232.38,66015533.13,...,5296,68315363.13,46823402.37,11332,11960,1153708.15,991130.16,294,251,2024-01-10
96,2024-01-10,2024-01-10 19:00:00.000,2024-01-10 20:00:03.000,1,FAF,US31847R1023,9575,2.550445e+07,12929267.71,12160407.43,...,1867,8492064.41,16597610.84,1191,8327,206503.40,208267.87,109,105,2024-01-10
97,2024-01-10,2024-01-10 19:00:00.000,2024-01-10 20:00:03.000,1,FBIN,US34964C1062,15629,6.834397e+07,35743945.44,31370098.84,...,2521,59465216.36,7648828.01,15037,588,291370.78,938557.05,89,184,2024-01-10
98,2024-01-10,2024-01-10 19:00:00.000,2024-01-10 20:00:03.000,1,FFWM,US32026V1044,6575,6.861772e+06,2631618.79,4053697.59,...,973,2977106.34,3708209.92,184,197,56597.63,119858.23,52,127,2024-01-10
99,2024-01-10,2024-01-10 19:00:00.000,2024-01-10 20:00:03.000,1,FSS,US3138551086,4159,1.427664e+07,7335539.52,6679494.28,...,983,13625339.90,389693.96,3997,162,119631.78,141970.11,52,52,2024-01-10

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_daily',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2012-03-29,2012-03-29 20:00:00.000,2012-03-29 20:00:03.000,1,AAPL,US0378331005,125051,1.322232e+10,5.772849e+09,6.226438e+09,...,40243,5.824888e+09,6.174400e+09,60881,64169,6.126912e+08,6.103428e+08,5887,5840,2012-03-29
1,2012-09-25,2012-09-25 20:00:00.000,2012-09-25 20:00:03.000,1,AAPL,US0378331005,107137,1.229080e+10,5.199941e+09,6.069367e+09,...,35784,4.336237e+09,6.933072e+09,42256,64881,5.035313e+08,5.179560e+08,4363,4529,2012-09-25
2,2012-02-22,2012-02-22 20:00:00.000,2012-02-22 20:00:03.000,1,AAPL,US0378331005,101529,8.690442e+09,4.238924e+09,3.789794e+09,...,30370,4.442856e+09,3.585862e+09,56032,45497,3.447430e+08,3.169811e+08,3969,3699,2012-02-22
3,2012-05-09,2012-05-09 19:59:00.000,2012-05-09 20:00:03.000,1,AAPL,US0378331005,99199,9.662372e+09,4.493414e+09,4.344607e+09,...,32729,4.731293e+09,4.106728e+09,54057,45141,4.273323e+08,3.970184e+08,4365,4110,2012-05-09
4,2012-12-11,2012-12-11 20:00:00.000,2012-12-11 20:00:03.000,1,AAPL,US0378331005,119363,1.126304e+10,5.187039e+09,4.947205e+09,...,41213,5.554200e+09,4.580045e+09,64492,54870,5.737195e+08,5.550728e+08,6017,5841,2012-12-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018-08-07,2018-08-07 20:00:00.000,2018-08-07 20:00:03.000,1,AAPL,US0378331005,197886,5.201362e+09,2.339394e+09,2.413622e+09,...,38665,3.095573e+09,1.657443e+09,119371,64080,2.356329e+08,2.127127e+08,9672,8684,2018-08-07
96,2018-04-26,2018-04-26 19:59:00.000,2018-04-26 20:00:03.000,1,AAPL,US0378331005,193471,4.439204e+09,1.859251e+09,2.329789e+09,...,33307,2.803336e+09,1.385704e+09,122027,71121,1.289373e+08,1.212267e+08,6221,5902,2018-04-26
97,2012-08-31,2012-08-31 20:00:00.000,2012-08-31 20:00:03.000,1,AAPL,US0378331005,72441,7.900323e+09,3.646557e+09,3.636586e+09,...,23996,3.735868e+09,3.547275e+09,36580,35860,3.142072e+08,3.029730e+08,2913,2795,2012-08-31
98,2018-05-01,2018-05-01 20:00:00.000,2018-05-01 20:00:03.000,1,AAPL,US0378331005,352702,8.796524e+09,4.112377e+09,4.023509e+09,...,77449,4.787939e+09,3.347946e+09,200284,152396,3.709926e+08,2.896462e+08,15658,12284,2018-05-01
99,2018-09-24,2018-09-24 20:00:00.000,2018-09-24 20:00:03.000,1,AAPL,US0378331005,197198,5.713912e+09,2.449029e+09,2.827584e+09,...,41298,2.969061e+09,2.307551e+09,129526,67662,2.486835e+08,1.886160e+08,8989,7569,2018-09-24

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_daily',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,US0378331005,547961,8.236493e+09,4.186066e+09,3.235051e+09,...,100366,5.489185e+09,1.931931e+09,394720,153237,4.965958e+08,3.187805e+08,33865,20667,2024-01-10
1,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,US0378331005,672873,1.247752e+10,6.453219e+09,5.029133e+09,...,121470,7.644821e+09,3.837530e+09,532463,140410,5.415875e+08,4.535793e+08,32810,25615,2024-01-19
2,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,US0378331005,990769,1.412446e+10,6.623136e+09,6.059647e+09,...,203660,5.313102e+09,7.369681e+09,246488,744247,9.361353e+08,5.055433e+08,69922,36466,2024-01-02
3,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,US0378331005,470682,6.976980e+09,3.297618e+09,2.996437e+09,...,82996,1.538823e+09,4.755232e+09,141921,326966,4.154052e+08,2.675194e+08,29498,17852,2024-01-12
4,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,US0378331005,587964,9.464511e+09,4.085833e+09,4.527814e+09,...,105630,2.184623e+09,6.429024e+09,217941,370023,4.297317e+08,4.211323e+08,27663,27274,2024-01-24
5,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,US0378331005,573592,8.499694e+09,4.130572e+09,3.580104e+09,...,105520,4.536361e+09,3.174315e+09,254275,319317,4.970823e+08,2.919359e+08,35207,19919,2024-01-11
6,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,US0378331005,673798,9.649756e+09,4.751073e+09,4.092012e+09,...,129079,4.309913e+09,4.533171e+09,419310,254487,4.901228e+08,3.165486e+08,36382,23948,2024-01-31
7,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,US0378331005,659243,1.029335e+10,5.566881e+09,3.683946e+09,...,122231,7.146960e+09,2.103867e+09,426813,231163,6.522086e+08,3.903154e+08,45879,26647,2024-01-08
8,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,US0378331005,704320,1.160613e+10,5.085719e+09,5.255783e+09,...,141718,3.824973e+09,6.516528e+09,285462,418792,8.521382e+08,4.124884e+08,52306,25296,2024-01-04
9,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,US0378331005,777009,1.407412e+10,6.525488e+09,6.259469e+09,...,144862,6.136234e+09,6.648724e+09,461588,313287,6.972198e+08,5.919468e+08,39269,31654,2024-01-18
10,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,US0378331005,527652,8.164331e+09,3.866378e+09,3.615130e+09,...,92775,4.173297e+09,3.308211e+09,306436,220071,3.827613e+08,3.000617e+08,24914,19586,2024-01-26
11,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,US0378331005,635510,9.921383e+09,4.653089e+09,4.391300e+09,...,110063,4.187310e+09,4.857079e+09,305904,329605,4.808374e+08,3.961562e+08,31153,25473,2024-01-25
12,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,US0378331005,708836,1.076400e+10,5.608608e+09,4.200468e+09,...,125210,4.332822e+09,5.476253e+09,387027,321791,5.172445e+08,4.376840e+08,34889,29419,2024-01-22
13,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,US0378331005,527095,7.690176e+09,4.116604e+09,2.814792e+09,...,91852,4.246585e+09,2.684811e+09,294083,229943,3.876772e+08,3.711025e+08,25365,23987,2024-01-23
14,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,US0378331005,646672,9.850288e+09,4.962202e+09,3.895633e+09,...,129183,5.887228e+09,2.970608e+09,337365,309307,5.323952e+08,4.600564e+08,36499,31646,2024-01-03
15,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,US0378331005,682123,9.997138e+09,5.243521e+09,3.764508e+09,...,131715,4.989138e+09,4.018891e+09,331875,350248,5.983166e+08,3.907921e+08,41139,26414,2024-01-30
16,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,US0378331005,585485,8.177436e+09,4.069209e+09,3.347815e+09,...,105858,4.263993e+09,3.153031e+09,301896,283518,4.652386e+08,2.951733e+08,33131,20739,2024-01-17
17,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,US0378331005,675347,1.073244e+10,5.070129e+09,4.547816e+09,...,132531,3.601071e+09,6.016874e+09,349875,324250,7.121559e+08,4.023349e+08,46270,25440,2024-01-05
18,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,US0378331005,530846,7.457582e+09,4.200570e+09,2.515406e+09,...,98440,5.819325e+09,8.966506e+08,453101,77735,4.232381e+08,3.183680e+08,32096,23905,2024-01-09
19,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,US0378331005,754694,1.064376e+10,5.534914e+09,4.143446e+09,...,140421,6.128538e+09,3.549822e+09,468751,285943,5.863861e+08,3.790186e+08,44587,28380,2024-01-16
20,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,US0378331005,590108,8.135218e+09,3.895377e+09,3.484026e+09,...,105285,2.352155e+09,5.027247e+09,218967,369775,4.378415e+08,3.179740e+08,31284,22478,2024-01-29

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_with_isin_daily", target_location="./data", asof_date='2026-01-12')

Starting native python replication for xtech_us_eqt_flow_with_isin_daily (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_with_isin_daily. Downloaded 1 files.

None