In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2018-08-17,2018-08-17 16:24:00.000,2018-08-17 20:00:03.000,1,A,US00846U1016,20111,1.556988e+08,8.142263e+07,6.996524e+07,...,3049,8.225055e+07,6.913732e+07,10202,9907,1.396533e+06,2.914379e+06,163,254,2018-08-17
1,2018-08-17,2018-08-17 18:04:00.000,2018-08-17 20:00:03.000,1,AA,US0138721065,16533,9.364421e+07,4.091873e+07,4.205455e+07,...,2747,4.145627e+07,4.151701e+07,7901,8630,6.656910e+06,4.014024e+06,297,233,2018-08-17
2,2018-08-17,2018-08-17 16:27:00.000,2018-08-17 20:00:03.000,1,AAC,US0003071083,2088,2.323389e+06,1.074818e+06,1.194822e+06,...,280,1.043430e+06,1.226210e+06,1033,1055,4.601457e+04,7.734680e+03,19,4,2018-08-17
3,2018-08-17,2018-08-17 18:52:00.000,2018-08-17 20:00:03.000,1,AAL,US02376R1023,28846,2.380206e+08,1.023749e+08,1.262724e+08,...,3779,1.019433e+08,1.267041e+08,14409,14437,5.157400e+06,4.215842e+06,309,286,2018-08-17
4,2018-08-17,2018-08-17 16:25:00.000,2018-08-17 20:00:03.000,1,AAN,US0025353006,3658,1.731675e+07,8.228810e+06,8.520778e+06,...,804,8.292238e+06,8.457350e+06,2021,1637,2.528352e+05,3.143229e+05,40,38,2018-08-17
5,2018-08-17,2018-08-17 17:39:00.000,2018-08-17 20:00:03.000,1,AAOI,US03823U1025,4545,2.711262e+07,1.252317e+07,1.055005e+07,...,1084,1.261082e+07,1.046240e+07,2268,2277,1.586705e+06,2.452691e+06,106,180,2018-08-17
6,2018-08-17,2018-08-17 16:01:00.000,2018-08-17 20:00:03.000,1,AAON,US0003602069,1186,4.741596e+06,2.074537e+06,2.350948e+06,...,201,2.136496e+06,2.288988e+06,589,596,1.950359e+05,1.210761e+05,35,21,2018-08-17
7,2018-08-17,2018-08-17 16:10:00.000,2018-08-17 20:00:03.000,1,AAP,US00751Y1064,11543,1.529032e+08,8.028604e+07,6.794035e+07,...,2928,7.875458e+07,6.947180e+07,5637,5906,2.406743e+06,2.270092e+06,159,141,2018-08-17
8,2018-08-17,2018-08-17 20:00:00.000,2018-08-17 20:00:03.000,1,AAPL,US0378331005,258788,7.295677e+09,2.903082e+09,3.248675e+09,...,50888,2.862265e+09,3.289491e+09,126050,132738,6.124309e+08,5.314892e+08,14910,10853,2018-08-17
9,2018-08-17,2018-08-17 16:25:00.000,2018-08-17 20:00:03.000,1,AAT,US0240131047,1707,6.150227e+06,2.207679e+06,3.780152e+06,...,374,2.132920e+06,3.854912e+06,909,798,7.940021e+04,8.299555e+04,13,14,2018-08-17

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-18,2024-01-18 19:10:00.000,2024-01-18 20:00:03.000,1,A,US00846U1016,25520,1.750170e+08,1.049853e+08,6.635762e+07,...,6070,9.043013e+07,8.091282e+07,12700,12819,1285700.75,2388355.43,285,277,2024-01-18
1,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AA,US0138721065,93882,3.377525e+08,1.468367e+08,1.481972e+08,...,13385,1.493002e+08,1.457338e+08,45756,48126,22292872.44,20425622.26,2120,1404,2024-01-18
2,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AADI,US00032Q1040,2983,8.954040e+05,4.239287e+05,3.893006e+05,...,416,4.138702e+05,3.993592e+05,1524,1458,40505.72,41668.93,62,68,2024-01-18
3,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAL,US02376R1023,130948,7.659771e+08,3.672347e+08,3.291868e+08,...,17475,3.733003e+08,3.231212e+08,70098,60848,35031262.41,34524350.68,3443,2964,2024-01-18
4,2024-01-18,2024-01-18 19:29:00.000,2024-01-18 20:00:03.000,1,AAN,US00258W1080,3088,2.047241e+06,1.094444e+06,8.796911e+05,...,454,1.116873e+06,8.572621e+05,1592,1495,29420.46,43685.69,21,29,2024-01-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-18,2024-01-18 19:01:00.000,2024-01-18 20:00:03.000,1,AKR,US0042391096,6825,1.143222e+07,4.656062e+06,6.710033e+06,...,916,4.533073e+06,6.833022e+06,3264,3561,40644.48,25484.05,35,35,2024-01-18
96,2024-01-18,2024-01-18 19:54:00.000,2024-01-18 20:00:03.000,1,AKRO,US00973Y1082,8576,1.371385e+07,8.123442e+06,5.405073e+06,...,1573,8.205325e+06,5.323189e+06,3881,4695,58614.89,126718.76,55,79,2024-01-18
97,2024-01-18,2024-01-18 19:45:00.000,2024-01-18 20:00:03.000,1,AKTS,US00973N1028,8498,3.399689e+06,1.296451e+06,1.204733e+06,...,2053,1.300298e+06,1.200885e+06,4177,4320,413775.21,484730.50,791,1040,2024-01-18
98,2024-01-18,2024-01-18 16:01:00.000,2024-01-18 20:00:03.000,1,AKYA,US00974H1041,1467,7.649267e+05,2.830309e+05,4.137058e+05,...,274,2.800224e+05,4.167143e+05,677,789,26361.28,41828.72,18,39,2024-01-18
99,2024-01-18,2024-01-18 19:49:00.000,2024-01-18 20:00:03.000,1,AL,US00912X3026,10701,2.311940e+07,1.005886e+07,1.241389e+07,...,1613,1.071594e+07,1.175681e+07,5056,5643,301959.30,344692.78,101,125,2024-01-18

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2016-07-13,2016-07-13 20:00:00.000,2016-07-13 20:00:03.000,1,AAPL,US0378331005,144495,2.437937e+09,9.025030e+08,1.267047e+09,...,20289,9.254879e+08,1.244062e+09,68786,75709,1.290393e+08,1.393476e+08,5043,5260,2016-07-13
1,2016-09-30,2016-09-30 20:00:00.000,2016-09-30 20:00:03.000,1,AAPL,US0378331005,183592,3.950656e+09,1.997589e+09,1.558984e+09,...,25739,2.004272e+09,1.552302e+09,89218,94372,1.970648e+08,1.970177e+08,5278,6276,2016-09-30
2,2014-09-05,2014-09-05 20:00:00.000,2014-09-05 20:00:03.000,1,AAPL,US0378331005,264967,5.430174e+09,2.397714e+09,2.389614e+09,...,40731,2.383124e+09,2.404203e+09,133290,131675,3.544550e+08,2.883918e+08,12086,6436,2014-09-05
3,2016-06-13,2016-06-13 20:00:00.000,2016-06-13 20:00:03.000,1,AAPL,US0378331005,225498,3.586462e+09,1.567709e+09,1.599626e+09,...,31018,1.557489e+09,1.609846e+09,114289,111207,2.273705e+08,1.917567e+08,9475,6408,2016-06-13
4,2014-09-25,2014-09-25 20:00:00.000,2014-09-25 20:00:03.000,1,AAPL,US0378331005,489929,9.814685e+09,3.854912e+09,4.676688e+09,...,81647,3.847155e+09,4.684446e+09,227909,262019,6.846787e+08,5.984055e+08,22432,14215,2014-09-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2016-07-26,2016-07-26 20:00:00.000,2016-07-26 20:00:03.000,1,AAPL,US0378331005,288385,5.390980e+09,2.385256e+09,2.401215e+09,...,48008,2.414561e+09,2.371910e+09,141769,146613,2.792448e+08,3.252644e+08,9898,11881,2016-07-26
96,2018-10-31,2018-10-31 20:00:00.000,2018-10-31 20:00:03.000,1,AAPL,US0378331005,300155,8.212389e+09,3.776439e+09,3.346404e+09,...,72109,3.633222e+09,3.489620e+09,148708,151446,5.631875e+08,5.263595e+08,14761,12034,2018-10-31
97,2016-09-09,2016-09-09 20:00:00.000,2016-09-09 20:00:03.000,1,AAPL,US0378331005,274790,4.714910e+09,1.794300e+09,2.332476e+09,...,42112,1.795207e+09,2.331568e+09,126886,147899,2.968118e+08,2.913222e+08,10636,9491,2016-09-09
98,2018-08-17,2018-08-17 20:00:00.000,2018-08-17 20:00:03.000,1,AAPL,US0378331005,258788,7.295677e+09,2.903082e+09,3.248675e+09,...,50888,2.862265e+09,3.289491e+09,126050,132738,6.124309e+08,5.314892e+08,14910,10853,2018-08-17
99,2016-05-31,2016-05-31 20:00:00.000,2016-05-31 20:00:03.000,1,AAPL,US0378331005,197986,4.012637e+09,1.662322e+09,1.920780e+09,...,29563,1.826078e+09,1.757024e+09,94292,103692,2.135220e+08,2.160132e+08,7782,7104,2016-05-31

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,US0378331005,587962,9.457487e+09,4.396980e+09,4.025837e+09,...,105630,4.417371e+09,4.005446e+09,348478,239484,4.926221e+08,5.420481e+08,27663,27274,2024-01-24
1,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,US0378331005,646606,9.724189e+09,4.725496e+09,3.810025e+09,...,129159,4.727787e+09,3.807734e+09,374680,271926,5.098485e+08,6.788193e+08,36482,31635,2024-01-03
2,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,US0378331005,682093,9.944367e+09,4.911012e+09,3.772293e+09,...,131699,4.867751e+09,3.815554e+09,384467,297626,6.964564e+08,5.646060e+08,41131,26399,2024-01-30
3,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,US0378331005,547902,7.957503e+09,3.802293e+09,3.215115e+09,...,100340,3.825576e+09,3.191832e+09,330178,217724,5.180600e+08,4.220353e+08,33851,20631,2024-01-10
4,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,US0378331005,585481,8.165045e+09,3.881386e+09,3.334522e+09,...,105856,3.852553e+09,3.363355e+09,340434,245045,5.133696e+08,4.357680e+08,33131,20739,2024-01-17
5,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,US0378331005,704292,1.117920e+10,4.903110e+09,4.848632e+09,...,141705,4.847464e+09,4.904278e+09,404312,299980,8.093261e+08,6.181319e+08,52306,25291,2024-01-04
6,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,US0378331005,673751,9.609475e+09,4.544943e+09,4.074560e+09,...,129057,4.461645e+09,4.157858e+09,380986,292765,5.103516e+08,4.796210e+08,36375,23940,2024-01-31
7,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,US0378331005,527086,7.671505e+09,3.881987e+09,2.852431e+09,...,91847,3.861606e+09,2.872812e+09,319856,207229,4.602497e+08,4.768365e+08,25365,23987,2024-01-23
8,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,US0378331005,708796,1.073480e+10,5.462671e+09,4.016835e+09,...,125197,5.574549e+09,3.904957e+09,422318,286474,6.501838e+08,6.051145e+08,34884,29397,2024-01-22
9,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,US0378331005,470667,6.941078e+09,3.434455e+09,2.791790e+09,...,82988,3.442340e+09,2.783905e+09,286746,183919,4.031384e+08,3.116944e+08,29492,17846,2024-01-12
10,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,US0378331005,635508,9.891279e+09,4.744796e+09,4.130843e+09,...,110062,4.674756e+09,4.200882e+09,371266,264241,5.258774e+08,4.897631e+08,31153,25473,2024-01-25
11,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,US0378331005,675337,1.058505e+10,4.966160e+09,4.240622e+09,...,132526,4.993287e+09,4.213496e+09,389878,285451,7.655776e+08,6.126888e+08,46270,25440,2024-01-05
12,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,US0378331005,990710,1.406572e+10,6.739308e+09,5.706525e+09,...,203637,6.718754e+09,5.727078e+09,558557,432153,8.381063e+08,7.817779e+08,69901,36457,2024-01-02
13,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,US0378331005,530828,7.405986e+09,3.703151e+09,2.830986e+09,...,98430,3.666996e+09,2.867141e+09,316857,213971,4.414514e+08,4.303981e+08,32092,23895,2024-01-09
14,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,US0378331005,776996,1.390008e+10,6.246976e+09,6.053243e+09,...,144853,6.214716e+09,6.085502e+09,438270,338726,8.478937e+08,7.519638e+08,39267,31652,2024-01-18
15,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,US0378331005,672809,1.207373e+10,5.862620e+09,5.141551e+09,...,121439,5.773583e+09,5.230588e+09,390683,282126,5.512614e+08,5.182930e+08,32778,25601,2024-01-19
16,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,US0378331005,573585,8.242853e+09,3.807336e+09,3.516374e+09,...,105517,3.842186e+09,3.481524e+09,329199,244386,5.234246e+08,3.957190e+08,35207,19919,2024-01-11
17,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,US0378331005,527636,8.032383e+09,3.920825e+09,3.412678e+09,...,92767,3.889177e+09,3.444326e+09,312636,214999,3.436649e+08,3.552153e+08,24908,19583,2024-01-26
18,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,US0378331005,589939,7.998797e+09,3.962558e+09,3.250855e+09,...,105210,3.856046e+09,3.357367e+09,362427,227509,4.216349e+08,3.637488e+08,31244,22398,2024-01-29
19,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,US0378331005,754607,1.047012e+10,5.324264e+09,4.027101e+09,...,140374,5.294603e+09,4.056762e+09,436132,318474,5.894122e+08,5.293452e+08,44543,28370,2024-01-16
20,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,US0378331005,659234,1.011811e+10,5.140608e+09,3.874886e+09,...,122228,5.194947e+09,3.820547e+09,410217,249013,6.224780e+08,4.801413e+08,45877,26645,2024-01-08

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1", target_location="./data", asof_date='2026-01-12')

Downloading using native python implementation for xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_daily_v1_2_1", target_location="./data")