In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_equity_flow_1min_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-02-21,2023-02-21 07:11:00.000,2023-02-21 07:11:03.000,1,AAAU,1,18.170,9.09,9.09,0,...,1,18.17,0.00,1,0,0,0,0,0,2023-02-21
1,2023-02-21,2023-02-21 07:17:00.000,2023-02-21 07:17:03.000,1,AAAU,3,21997.815,0.00,21997.82,0,...,1,0.00,21997.82,0,3,0,0,0,0,2023-02-21
2,2023-02-21,2023-02-21 07:39:00.000,2023-02-21 07:39:03.000,1,AAAU,1,18.160,0.00,18.16,0,...,1,0.00,18.16,0,1,0,0,0,0,2023-02-21
3,2023-02-21,2023-02-21 08:01:00.000,2023-02-21 08:01:03.000,1,AAAU,1,18.180,18.18,0.00,1,...,0,18.18,0.00,1,0,0,0,0,0,2023-02-21
4,2023-02-21,2023-02-21 08:02:00.000,2023-02-21 08:02:03.000,1,AAAU,1,18.165,0.00,18.16,0,...,1,0.00,18.16,0,1,0,0,0,0,2023-02-21
5,2023-02-21,2023-02-21 08:37:00.000,2023-02-21 08:37:03.000,1,AAAU,1,36.430,36.43,0.00,1,...,0,36.43,0.00,1,0,0,0,0,0,2023-02-21
6,2023-02-21,2023-02-21 09:02:00.000,2023-02-21 09:02:03.000,1,AAAU,1,200.475,200.48,0.00,1,...,0,200.48,0.00,1,0,0,0,0,0,2023-02-21
7,2023-02-21,2023-02-21 09:22:00.000,2023-02-21 09:22:03.000,1,AAAU,1,109.440,109.44,0.00,1,...,0,109.44,0.00,1,0,0,0,0,0,2023-02-21
8,2023-02-21,2023-02-21 09:23:00.000,2023-02-21 09:23:03.000,1,AAAU,1,36.490,36.49,0.00,1,...,0,36.49,0.00,1,0,0,0,0,0,2023-02-21
9,2023-02-21,2023-02-21 09:27:00.000,2023-02-21 09:27:03.000,1,AAAU,1,456.500,456.50,0.00,1,...,0,456.50,0.00,1,0,0,0,0,0,2023-02-21

## Retrieve data for a specific date range using the back_to and up_to parameters

In [13]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_1min_v1_2', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AADI,US00032Q1040,1,40.71,20.36,20.36,...,1,20.36,20.36,0,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPB,US38747R8842,1,192.60,96.30,96.30,...,1,96.30,96.30,0,0,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPD,US25461A3041,1,396.53,198.26,198.26,...,1,0.00,396.53,0,1,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,AAPL,US0378331005,163,891117.18,563098.59,328018.59,...,44,194077.67,697039.51,35,127,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ABBV,US00287Y1091,4,4122.70,3607.36,515.34,...,2,1030.68,3092.02,0,2,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,BULZ,US0636795595,2,1043.67,782.75,260.92,...,1,521.84,521.84,0,0,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,C,US1729674242,7,21848.50,15606.07,6242.43,...,3,18727.29,3121.21,6,1,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,CAG,US2058871029,1,29.45,14.72,14.72,...,1,29.45,0.00,1,0,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,CAN,US1347481020,5,2179.00,1525.30,653.70,...,2,1089.50,1089.50,0,0,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,CATX,US46489V1044,1,11.40,5.70,5.70,...,1,5.70,5.70,0,0,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_1min_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-04-17,2023-04-17 04:01:00.000,2023-04-17 04:01:03.000,1,AAPL,71,418945.91,179969.72,238976.19,30,...,11,159317.46,259628.45,27,44,0,0,0,0,2023-04-17
1,2023-04-17,2023-04-17 04:02:00.000,2023-04-17 04:02:03.000,1,AAPL,37,114040.95,3082.19,110958.76,1,...,12,33904.07,80136.88,11,26,0,0,0,0,2023-04-17
2,2023-04-17,2023-04-17 04:03:00.000,2023-04-17 04:03:03.000,1,AAPL,10,41199.24,20599.62,20599.62,5,...,3,24719.54,16479.70,6,4,0,0,0,0,2023-04-17
3,2023-04-17,2023-04-17 04:04:00.000,2023-04-17 04:04:03.000,1,AAPL,8,171292.60,107057.88,64234.73,5,...,2,85646.30,85646.30,4,4,0,0,0,0,2023-04-17
4,2023-04-17,2023-04-17 04:05:00.000,2023-04-17 04:05:03.000,1,AAPL,3,7281.89,7281.89,0.00,3,...,1,4854.59,2427.30,2,1,0,0,0,0,2023-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-04-17,2023-04-17 05:43:00.000,2023-04-17 05:43:03.000,1,AAPL,4,8914.40,0.00,8914.40,0,...,2,0.00,8914.40,0,4,0,0,0,0,2023-04-17
96,2023-04-17,2023-04-17 05:44:00.000,2023-04-17 05:44:03.000,1,AAPL,13,37469.41,0.00,37469.41,0,...,3,2882.26,34587.15,1,12,0,0,0,0,2023-04-17
97,2023-04-17,2023-04-17 05:45:00.000,2023-04-17 05:45:03.000,1,AAPL,2,9570.61,4785.30,4785.30,1,...,1,4785.30,4785.30,1,1,0,0,0,0,2023-04-17
98,2023-04-17,2023-04-17 05:46:00.000,2023-04-17 05:46:03.000,1,AAPL,35,102798.76,2937.11,99861.65,1,...,3,5874.21,96924.55,2,33,0,0,0,0,2023-04-17
99,2023-04-17,2023-04-17 05:47:00.000,2023-04-17 05:47:03.000,1,AAPL,14,62219.43,22221.22,39998.20,5,...,3,22221.22,39998.20,5,9,0,0,0,0,2023-04-17

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_1min_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_equity_flow_1min_v1_2_1", target_location="./data", asof_date='2026-01-12')

Starting native python replication for xtech_us_equity_flow_1min_v1_2_1 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_flow_1min_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_flow_1min_v1_2_1", target_location="./data")