In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-07-25,2023-07-25 04:16:00.000,2023-07-25 04:16:03.000,1,AA,US0138721065,1,172.10,86.05,86.05,...,1,172.10,0.00,1,0,0,0,0,0,2023-07-25
1,2023-07-25,2023-07-25 04:51:00.000,2023-07-25 04:51:03.000,1,AA,US0138721065,2,3423.00,1711.50,1711.50,...,1,0.00,3423.00,0,2,0,0,0,0,2023-07-25
2,2023-07-25,2023-07-25 04:54:00.000,2023-07-25 04:54:03.000,1,AA,US0138721065,16,17726.27,12186.81,5539.46,...,2,11078.92,6647.35,10,6,0,0,0,0,2023-07-25
3,2023-07-25,2023-07-25 05:02:00.000,2023-07-25 05:02:03.000,1,AA,US0138721065,1,1550.25,0.00,1550.25,...,1,0.00,1550.25,0,1,0,0,0,0,2023-07-25
4,2023-07-25,2023-07-25 05:03:00.000,2023-07-25 05:03:03.000,1,AA,US0138721065,2,379.28,189.64,189.64,...,1,189.64,189.64,1,1,0,0,0,0,2023-07-25
5,2023-07-25,2023-07-25 05:30:00.000,2023-07-25 05:30:03.000,1,AA,US0138721065,4,10347.00,10347.00,0.00,...,0,10347.00,0.00,4,0,0,0,0,0,2023-07-25
6,2023-07-25,2023-07-25 05:35:00.000,2023-07-25 05:35:03.000,1,AA,US0138721065,1,172.35,172.35,0.00,...,1,0.00,172.35,0,1,0,0,0,0,2023-07-25
7,2023-07-25,2023-07-25 05:53:00.000,2023-07-25 05:53:03.000,1,AA,US0138721065,6,51768.28,43140.23,8628.05,...,2,43140.23,8628.05,5,1,0,0,0,0,2023-07-25
8,2023-07-25,2023-07-25 05:58:00.000,2023-07-25 05:58:03.000,1,AA,US0138721065,1,2405.20,0.00,2405.20,...,1,0.00,2405.20,0,1,0,0,0,0,2023-07-25
9,2023-07-25,2023-07-25 06:03:00.000,2023-07-25 06:03:03.000,1,AA,US0138721065,2,4207.78,4207.78,0.00,...,0,4207.78,0.00,2,0,0,0,0,0,2023-07-25

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:03:00.000,2024-01-31 04:03:03.000,1,AA,US0138721065,2,61.0500,45.79,15.26,...,2,61.05,0.00,2,0,0.00,0.00,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:17:00.000,2024-01-31 04:17:03.000,1,AA,US0138721065,1,1525.0000,1525.00,0.00,...,0,1525.00,0.00,1,0,0.00,0.00,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:32:00.000,2024-01-31 04:32:03.000,1,AA,US0138721065,2,60.8000,60.80,0.00,...,1,30.40,30.40,1,1,0.00,0.00,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:47:00.000,2024-01-31 04:47:03.000,1,AA,US0138721065,10,13204.2900,10563.43,2640.86,...,0,11883.86,1320.43,9,1,0.00,0.00,0,0,2024-01-31
4,2024-01-31,2024-01-31 05:05:00.000,2024-01-31 05:05:03.000,1,AA,US0138721065,1,30.5600,30.56,0.00,...,1,0.00,30.56,0,1,0.00,0.00,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 10:13:00.000,2024-01-31 10:13:03.000,0,AA,US0138721065,125,265637.7534,103553.57,159990.73,...,14,101428.47,162115.84,48,77,576.43,1517.02,1,1,2024-01-31
96,2024-01-31,2024-01-31 10:14:00.000,2024-01-31 10:14:03.000,0,AA,US0138721065,135,267012.6241,140047.20,96549.35,...,17,140047.20,96549.35,77,58,12248.89,18167.18,3,2,2024-01-31
97,2024-01-31,2024-01-31 10:15:00.000,2024-01-31 10:15:03.000,0,AA,US0138721065,143,506738.7509,214631.04,276402.96,...,20,225261.92,265772.07,68,75,15704.76,0.00,7,0,2024-01-31
98,2024-01-31,2024-01-31 10:16:00.000,2024-01-31 10:16:03.000,0,AA,US0138721065,146,323980.5633,108265.88,135729.91,...,21,112703.97,131291.82,80,66,64819.63,15165.15,5,1,2024-01-31
99,2024-01-31,2024-01-31 10:17:00.000,2024-01-31 10:17:03.000,0,AA,US0138721065,94,164429.6900,41629.34,89419.74,...,11,48626.35,82422.73,33,61,9098.97,24281.64,1,2,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-09-28,2023-09-28 04:01:00.000,2023-09-28 04:01:03.000,1,AAPL,US0378331005,79,267732.03,113531.94,154200.09,...,26,115226.44,152505.59,34,45,0,0,0,0,2023-09-28
1,2023-09-28,2023-09-28 04:02:00.000,2023-09-28 04:02:03.000,1,AAPL,US0378331005,78,451012.05,104079.70,346932.35,...,25,109861.91,341150.14,19,59,0,0,0,0,2023-09-28
2,2023-09-28,2023-09-28 04:03:00.000,2023-09-28 04:03:03.000,1,AAPL,US0378331005,50,176592.19,88296.10,88296.10,...,16,70636.88,105955.31,20,30,0,0,0,0,2023-09-28
3,2023-09-28,2023-09-28 04:04:00.000,2023-09-28 04:04:03.000,1,AAPL,US0378331005,122,483006.91,87099.61,395907.30,...,19,39590.73,443416.18,10,112,0,0,0,0,2023-09-28
4,2023-09-28,2023-09-28 04:05:00.000,2023-09-28 04:05:03.000,1,AAPL,US0378331005,29,186654.42,102981.75,83672.67,...,7,90109.03,96545.39,14,15,0,0,0,0,2023-09-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-09-28,2023-09-28 05:36:00.000,2023-09-28 05:36:03.000,1,AAPL,US0378331005,2,13402.85,0.00,13402.85,...,1,0.00,13402.85,0,2,0,0,0,0,2023-09-28
96,2023-09-28,2023-09-28 05:37:00.000,2023-09-28 05:37:03.000,1,AAPL,US0378331005,9,66873.08,52012.40,14860.68,...,1,59442.74,7430.34,8,1,0,0,0,0,2023-09-28
97,2023-09-28,2023-09-28 05:38:00.000,2023-09-28 05:38:03.000,1,AAPL,US0378331005,12,46688.38,46688.38,0.00,...,1,46688.38,0.00,12,0,0,0,0,0,2023-09-28
98,2023-09-28,2023-09-28 05:39:00.000,2023-09-28 05:39:03.000,1,AAPL,US0378331005,4,3733.74,2800.30,933.44,...,2,1866.87,1866.87,2,2,0,0,0,0,2023-09-28
99,2023-09-28,2023-09-28 05:40:00.000,2023-09-28 05:40:03.000,1,AAPL,US0378331005,9,42416.96,14138.99,28277.97,...,4,14138.99,28277.97,3,6,0,0,0,0,2023-09-28

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-16,2024-01-16 04:01:00.000,2024-01-16 04:01:03.000,1,AAPL,US0378331005,271,1103816.47,771856.90,331959.57,...,52,641516.95,462299.52,157,113,0,0,0,0,2024-01-16
1,2024-01-16,2024-01-16 04:02:00.000,2024-01-16 04:02:03.000,1,AAPL,US0378331005,137,594871.02,186711.34,408159.68,...,23,208421.96,386449.06,48,89,0,0,0,0,2024-01-16
2,2024-01-16,2024-01-16 04:03:00.000,2024-01-16 04:03:03.000,1,AAPL,US0378331005,89,781148.79,280862.49,500286.30,...,34,245754.68,535394.11,28,61,0,0,0,0,2024-01-16
3,2024-01-16,2024-01-16 04:04:00.000,2024-01-16 04:04:03.000,1,AAPL,US0378331005,40,259206.04,64801.51,194404.53,...,11,71281.66,187924.38,11,29,0,0,0,0,2024-01-16
4,2024-01-16,2024-01-16 04:05:00.000,2024-01-16 04:05:03.000,1,AAPL,US0378331005,64,483358.26,173706.87,309651.39,...,15,128392.04,354966.22,17,47,0,0,0,0,2024-01-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-16,2024-01-16 05:36:00.000,2024-01-16 05:36:03.000,1,AAPL,US0378331005,11,48586.94,30918.96,17667.98,...,5,26501.97,22084.97,6,5,0,0,0,0,2024-01-16
96,2024-01-16,2024-01-16 05:37:00.000,2024-01-16 05:37:03.000,1,AAPL,US0378331005,56,220210.35,7864.66,212345.69,...,17,11796.98,208413.37,3,53,0,0,0,0,2024-01-16
97,2024-01-16,2024-01-16 05:38:00.000,2024-01-16 05:38:03.000,1,AAPL,US0378331005,15,217545.91,159533.67,58012.24,...,4,159533.67,58012.24,11,4,0,0,0,0,2024-01-16
98,2024-01-16,2024-01-16 05:39:00.000,2024-01-16 05:39:03.000,1,AAPL,US0378331005,15,21920.43,21920.43,0.00,...,2,17536.34,4384.09,12,3,0,0,0,0,2024-01-16
99,2024-01-16,2024-01-16 05:40:00.000,2024-01-16 05:40:03.000,1,AAPL,US0378331005,20,173751.81,156376.63,17375.18,...,8,86875.90,86875.90,10,10,0,0,0,0,2024-01-16

## Download data file for a specific date using asof_date

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1", target_location="./data", asof_date='2026-01-08')

Downloading using native python implementation for xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1...
Found 1 files to download.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_1min_v1_2_1", target_location="./data")