In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_equity_flow_daily_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2010-04-19,2010-04-19 16:20:00.000,2010-04-19 20:00:03.000,1,A,15891,9.479130e+07,4.638889e+07,4.453712e+07,7803,...,2062,4.657308e+07,4.435294e+07,7846,8045,2.016715e+06,1.848569e+06,282,229,2010-04-19
1,2010-04-19,2010-04-19 19:59:00.000,2010-04-19 20:00:03.000,1,AA,83396,5.045454e+08,2.432023e+08,2.241986e+08,43182,...,9005,2.406130e+08,2.267879e+08,42811,40585,2.325857e+07,1.388587e+07,3062,1402,2010-04-19
2,2010-04-19,2010-04-19 16:01:00.000,2010-04-19 20:00:03.000,1,AACC,39,3.438551e+04,2.005552e+04,1.364576e+04,24,...,12,2.005552e+04,1.364576e+04,24,14,0.000000e+00,6.842300e+02,0,1,2010-04-19
3,2010-04-19,2010-04-19 16:01:00.000,2010-04-19 20:00:03.000,1,AAI,14604,2.863953e+07,1.285319e+07,1.423039e+07,6727,...,1382,1.289221e+07,1.419138e+07,6808,7795,7.613377e+05,7.946061e+05,197,218,2010-04-19
4,2010-04-19,2010-04-19 14:31:00.000,2010-04-19 20:00:03.000,0,AAME,6,3.136860e+03,7.200000e+02,2.122900e+03,0,...,3,0.000000e+00,2.842900e+03,0,6,0.000000e+00,2.939600e+02,0,1,2010-04-19
5,2010-04-19,2010-04-19 16:02:00.000,2010-04-19 20:00:03.000,1,AAN,6343,2.303970e+07,1.094795e+07,1.148135e+07,3096,...,1054,1.101018e+07,1.141912e+07,3096,3247,2.572786e+05,3.531215e+05,57,73,2010-04-19
6,2010-04-19,2010-04-19 12:36:00.000,2010-04-19 20:00:03.000,0,AAN.A,33,6.189300e+04,2.776942e+04,3.412358e+04,14,...,15,2.870542e+04,3.318758e+04,15,18,0.000000e+00,0.000000e+00,0,0,2010-04-19
7,2010-04-19,2010-04-19 16:01:00.000,2010-04-19 20:00:03.000,1,AAON,333,1.107287e+06,6.157714e+05,4.564065e+05,178,...,118,6.057964e+05,4.663815e+05,177,155,1.893665e+04,1.617254e+04,7,5,2010-04-19
8,2010-04-19,2010-04-19 16:03:00.000,2010-04-19 20:00:03.000,1,AAP,10976,6.566304e+07,3.442511e+07,2.955113e+07,5967,...,1824,3.436944e+07,2.960680e+07,5976,5000,8.629387e+05,8.238646e+05,60,80,2010-04-19
9,2010-04-19,2010-04-19 20:02:00.000,2010-04-19 20:00:03.000,1,AAPL,110689,4.888897e+09,2.096929e+09,2.149614e+09,54755,...,29698,2.097154e+09,2.149389e+09,54870,55819,3.320353e+08,3.103188e+08,4985,4481,2010-04-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_daily_v1_2_1', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-23,2024-01-23 19:01:00.000,2024-01-23 20:00:03.000,1,A,19094,1.023307e+08,5.660209e+07,4.229884e+07,9310,...,4969,5.772645e+07,4.117448e+07,9560,9533,1236773.72,2193030.06,307,257,2024-01-23
1,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AA,76570,2.647145e+08,1.345395e+08,1.025955e+08,40270,...,11518,1.339311e+08,1.032039e+08,40190,36380,14628825.24,12950686.72,1604,1283,2024-01-23
2,2024-01-23,2024-01-23 20:01:00.000,2024-01-23 20:00:03.000,1,AAA,61,1.212875e+05,5.925234e+04,6.072928e+04,42,...,14,5.746940e+04,6.251222e+04,37,21,25.13,1280.75,1,2,2024-01-23
3,2024-01-23,2024-01-23 20:01:00.000,2024-01-23 20:00:03.000,1,AAAU,1511,4.272364e+07,1.797367e+07,1.838015e+07,772,...,349,1.763644e+07,1.871738e+07,755,756,3459593.45,2910225.87,155,115,2024-01-23
4,2024-01-23,2024-01-23 17:32:00.000,2024-01-23 20:00:03.000,1,AACG,76,3.103547e+03,5.036300e+02,2.205480e+03,26,...,24,5.388100e+02,2.170310e+03,29,46,110.75,283.65,2,4,2024-01-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-23,2024-01-23 15:30:00.000,2024-01-23 20:00:03.000,0,ACONW,51,1.326670e+03,9.416400e+02,1.421500e+02,43,...,9,9.075200e+02,1.762700e+02,39,12,107.40,135.48,4,1,2024-01-23
96,2024-01-23,2024-01-23 16:19:00.000,2024-01-23 20:00:03.000,1,ACOR,101,6.566798e+04,2.339448e+04,4.175507e+04,46,...,38,2.524525e+04,3.990427e+04,41,58,0.00,518.42,0,2,2024-01-23
97,2024-01-23,2024-01-23 19:51:00.000,2024-01-23 20:00:03.000,1,ACP,999,1.291462e+06,4.727820e+05,6.231970e+05,450,...,228,4.538539e+05,6.421251e+05,439,560,61351.39,134131.30,57,61,2024-01-23
98,2024-01-23,2024-01-23 19:01:00.000,2024-01-23 20:00:03.000,1,ACPpA,8,6.113090e+03,3.695730e+03,2.417360e+03,4,...,3,3.875090e+03,2.238000e+03,4,4,0.00,0.00,0,0,2024-01-23
99,2024-01-23,2024-01-23 19:01:00.000,2024-01-23 20:00:03.000,1,ACR,340,2.718626e+05,8.133634e+04,1.836926e+05,134,...,76,7.751283e+04,1.875161e+05,129,211,395.62,6438.04,3,10,2024-01-23

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_daily_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2011-01-27,2011-01-27 20:00:00.000,2011-01-27 20:00:03.000,1,AAPL,56707,3.383849e+09,1.429972e+09,1.506897e+09,27644,...,16399,1.383858e+09,1.553011e+09,27253,29454,2.305132e+08,2.164666e+08,2362,2450,2011-01-27
1,2010-12-10,2010-12-10 19:59:00.000,2010-12-10 20:00:03.000,1,AAPL,52067,2.817381e+09,1.266739e+09,1.203318e+09,25721,...,14387,1.268947e+09,1.201111e+09,25877,26190,1.718210e+08,1.755032e+08,2062,2299,2010-12-10
2,2010-10-26,2010-10-26 20:00:00.000,2010-10-26 20:00:03.000,1,AAPL,73849,4.150158e+09,1.887330e+09,1.697518e+09,37542,...,21210,1.877038e+09,1.707810e+09,37464,36385,2.821312e+08,2.831781e+08,3428,3431,2010-10-26
3,2011-01-20,2011-01-20 20:00:00.000,2011-01-20 20:00:03.000,1,AAPL,162238,8.968125e+09,4.115173e+09,3.764013e+09,82542,...,47429,4.038916e+09,3.840270e+09,81852,80386,5.441336e+08,5.448057e+08,7178,7287,2011-01-20
4,2011-01-28,2011-01-28 20:00:00.000,2011-01-28 20:00:03.000,1,AAPL,129865,7.002872e+09,2.940616e+09,3.164010e+09,64179,...,39639,2.821961e+09,3.282664e+09,62034,67831,4.422991e+08,4.559471e+08,5081,4648,2011-01-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2010-04-26,2010-04-26 20:00:00.000,2010-04-26 20:00:03.000,1,AAPL,91080,4.517586e+09,1.913100e+09,1.959123e+09,44222,...,24795,1.908610e+09,1.963613e+09,44266,46814,3.372426e+08,3.081196e+08,4663,4062,2010-04-26
96,2009-08-26,2009-08-26 20:00:00.000,2009-08-26 20:00:03.000,1,AAPL,59524,1.761872e+09,7.277304e+08,8.068593e+08,28836,...,14118,7.306873e+08,8.039024e+08,29255,30268,1.177917e+08,1.094909e+08,1781,1819,2009-08-26
97,2010-10-06,2010-10-06 20:00:00.000,2010-10-06 20:00:03.000,1,AAPL,130088,6.688239e+09,2.837712e+09,2.723417e+09,65766,...,38549,2.819361e+09,2.741768e+09,65626,64462,5.751775e+08,5.519328e+08,7279,6460,2010-10-06
98,2010-07-26,2010-07-26 20:00:00.000,2010-07-26 20:00:03.000,1,AAPL,79803,3.797434e+09,1.649691e+09,1.661793e+09,38770,...,21286,1.636359e+09,1.675125e+09,38874,40929,2.453392e+08,2.406111e+08,3828,3960,2010-07-26
99,2010-01-07,2010-01-07 20:00:00.000,2010-01-07 20:00:03.000,1,AAPL,90566,3.543506e+09,1.526902e+09,1.529563e+09,44457,...,22703,1.527073e+09,1.529393e+09,44655,45911,2.412951e+08,2.457450e+08,3469,3366,2010-01-07

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_equity_flow_daily_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-03,2024-01-03 20:00:00.000,2024-01-03 20:00:03.000,1,AAPL,646606,9.724189e+09,4.725496e+09,3.810025e+09,374656,...,129159,4.727787e+09,3.807734e+09,374680,271926,5.098485e+08,6.788193e+08,36482,31635,2024-01-03
1,2024-01-04,2024-01-04 20:00:00.000,2024-01-04 20:00:03.000,1,AAPL,704292,1.117920e+10,4.903110e+09,4.848632e+09,407780,...,141705,4.847464e+09,4.904278e+09,404312,299980,8.093261e+08,6.181319e+08,52306,25291,2024-01-04
2,2024-01-08,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,1,AAPL,659234,1.011811e+10,5.140608e+09,3.874886e+09,411671,...,122228,5.194947e+09,3.820547e+09,410217,249013,6.224780e+08,4.801413e+08,45877,26645,2024-01-08
3,2024-01-31,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,1,AAPL,673751,9.609475e+09,4.544943e+09,4.074560e+09,382567,...,129057,4.461645e+09,4.157858e+09,380986,292765,5.103516e+08,4.796210e+08,36375,23940,2024-01-31
4,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAPL,708796,1.073480e+10,5.462671e+09,4.016835e+09,422157,...,125197,5.574549e+09,3.904957e+09,422318,286474,6.501838e+08,6.051145e+08,34884,29397,2024-01-22
5,2024-01-26,2024-01-26 20:00:00.000,2024-01-26 20:00:03.000,1,AAPL,527636,8.032383e+09,3.920825e+09,3.412678e+09,313998,...,92767,3.889177e+09,3.444326e+09,312636,214999,3.436649e+08,3.552153e+08,24908,19583,2024-01-26
6,2024-01-09,2024-01-09 20:00:00.000,2024-01-09 20:00:03.000,1,AAPL,530828,7.405986e+09,3.703151e+09,2.830986e+09,317939,...,98430,3.666996e+09,2.867141e+09,316857,213971,4.414514e+08,4.303981e+08,32092,23895,2024-01-09
7,2024-01-02,2024-01-02 20:00:00.000,2024-01-02 20:00:03.000,1,AAPL,990710,1.406572e+10,6.739308e+09,5.706525e+09,562908,...,203637,6.718754e+09,5.727078e+09,558557,432153,8.381063e+08,7.817779e+08,69901,36457,2024-01-02
8,2024-01-25,2024-01-25 20:00:00.000,2024-01-25 20:00:03.000,1,AAPL,635508,9.891279e+09,4.744796e+09,4.130843e+09,372405,...,110062,4.674756e+09,4.200882e+09,371266,264241,5.258774e+08,4.897631e+08,31153,25473,2024-01-25
9,2024-01-05,2024-01-05 20:00:00.000,2024-01-05 20:00:03.000,1,AAPL,675337,1.058505e+10,4.966160e+09,4.240622e+09,390963,...,132526,4.993287e+09,4.213496e+09,389878,285451,7.655776e+08,6.126888e+08,46270,25440,2024-01-05
10,2024-01-29,2024-01-29 20:00:00.000,2024-01-29 20:00:03.000,1,AAPL,589939,7.998797e+09,3.962558e+09,3.250855e+09,364379,...,105210,3.856046e+09,3.357367e+09,362427,227509,4.216349e+08,3.637488e+08,31244,22398,2024-01-29
11,2024-01-23,2024-01-23 20:00:00.000,2024-01-23 20:00:03.000,1,AAPL,527086,7.671505e+09,3.881987e+09,2.852431e+09,319880,...,91847,3.861606e+09,2.872812e+09,319856,207229,4.602497e+08,4.768365e+08,25365,23987,2024-01-23
12,2024-01-19,2024-01-19 20:00:00.000,2024-01-19 20:00:03.000,1,AAPL,672809,1.207373e+10,5.862620e+09,5.141551e+09,388844,...,121439,5.773583e+09,5.230588e+09,390683,282126,5.512614e+08,5.182930e+08,32778,25601,2024-01-19
13,2024-01-12,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,1,AAPL,470667,6.941078e+09,3.434455e+09,2.791790e+09,288123,...,82988,3.442340e+09,2.783905e+09,286746,183919,4.031384e+08,3.116944e+08,29492,17846,2024-01-12
14,2024-01-18,2024-01-18 20:00:00.000,2024-01-18 20:00:03.000,1,AAPL,776996,1.390008e+10,6.246976e+09,6.053243e+09,438197,...,144853,6.214716e+09,6.085502e+09,438270,338726,8.478937e+08,7.519638e+08,39267,31652,2024-01-18
15,2024-01-10,2024-01-10 20:00:00.000,2024-01-10 20:00:03.000,1,AAPL,547902,7.957503e+09,3.802293e+09,3.215115e+09,331119,...,100340,3.825576e+09,3.191832e+09,330178,217724,5.180600e+08,4.220353e+08,33851,20631,2024-01-10
16,2024-01-24,2024-01-24 20:00:00.000,2024-01-24 20:00:03.000,1,AAPL,587962,9.457487e+09,4.396980e+09,4.025837e+09,348045,...,105630,4.417371e+09,4.005446e+09,348478,239484,4.926221e+08,5.420481e+08,27663,27274,2024-01-24
17,2024-01-17,2024-01-17 20:00:00.000,2024-01-17 20:00:03.000,1,AAPL,585481,8.165045e+09,3.881386e+09,3.334522e+09,342783,...,105856,3.852553e+09,3.363355e+09,340434,245045,5.133696e+08,4.357680e+08,33131,20739,2024-01-17
18,2024-01-30,2024-01-30 20:00:00.000,2024-01-30 20:00:03.000,1,AAPL,682093,9.944367e+09,4.911012e+09,3.772293e+09,387356,...,131699,4.867751e+09,3.815554e+09,384467,297626,6.964564e+08,5.646060e+08,41131,26399,2024-01-30
19,2024-01-11,2024-01-11 20:00:00.000,2024-01-11 20:00:03.000,1,AAPL,573585,8.242853e+09,3.807336e+09,3.516374e+09,330364,...,105517,3.842186e+09,3.481524e+09,329199,244386,5.234246e+08,3.957190e+08,35207,19919,2024-01-11
20,2024-01-16,2024-01-16 20:00:00.000,2024-01-16 20:00:03.000,1,AAPL,754607,1.047012e+10,5.324264e+09,4.027101e+09,436856,...,140374,5.294603e+09,4.056762e+09,436132,318474,5.894122e+08,5.293452e+08,44543,28370,2024-01-16

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_equity_flow_daily_v1_2_1", target_location="./data", asof_date='2026-01-12')

Starting native python replication for xtech_us_equity_flow_daily_v1_2_1 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_equity_flow_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_equity_flow_daily_v1_2_1", target_location="./data")