In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_with_isin_daily_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-01-19,2007-01-19 16:10:00.000,2007-01-19 20:00:03.000,1,A,US00846U1016,7490,8.964939e+07,3.884082e+07,4.978291e+07,...,1051,4.477798e+07,43845751.30,603,525,287220.50,738442.10,32,73,2007-01-19
1,2007-01-19,2007-01-19 18:52:00.000,2007-01-19 20:00:03.000,1,AA,US0138171014,35516,4.089700e+08,2.230228e+08,1.779946e+08,...,4460,3.252258e+08,75791622.62,24473,1610,3817271.93,4135305.50,356,382,2007-01-19
2,2007-01-19,2007-01-19 15:54:00.000,2007-01-19 20:00:03.000,0,AAA,US02143N1037,86,7.220749e+05,6.413037e+05,7.453625e+04,...,29,4.091984e+05,306641.61,18,6,6234.88,0.00,1,0,2007-01-19
3,2007-01-19,2007-01-19 15:57:00.000,2007-01-19 20:00:03.000,0,AAB.WS,NaN,17,8.560100e+04,3.189000e+03,8.241200e+04,...,9,2.363750e+04,61963.50,1,3,0.00,0.00,0,0,2007-01-19
4,2007-01-19,2007-01-19 15:58:00.000,2007-01-19 20:00:03.000,1,AAC,US05461P1057,30,3.523200e+04,2.204600e+04,1.318600e+04,...,6,1.700750e+04,18224.50,1,5,0.00,0.00,0,0,2007-01-19
5,2007-01-19,2007-01-19 16:03:00.000,2007-01-19 20:00:03.000,1,AACC,US04543P1003,521,1.170652e+06,5.415880e+05,5.861754e+05,...,106,5.419617e+05,585801.65,52,67,16589.43,26299.52,6,6,2007-01-19
6,2007-01-19,2007-01-19 16:04:00.000,2007-01-19 20:00:03.000,1,AAI,US00949P1084,4607,1.665235e+07,7.532117e+06,8.957890e+06,...,593,1.165119e+07,4838819.37,2196,319,70677.71,91661.74,20,19,2007-01-19
7,2007-01-19,2007-01-19 12:42:00.000,2007-01-19 20:00:03.000,0,AAME,US0482091008,2,3.729000e+03,1.700000e+03,2.029000e+03,...,1,1.864500e+03,1864.50,0,0,0.00,0.00,0,0,2007-01-19
8,2007-01-19,2007-01-19 15:57:00.000,2007-01-19 20:00:03.000,0,AANB,US0033901010,7,1.910160e+04,2.023000e+03,6.069000e+03,...,4,4.046000e+03,4046.00,0,0,0.00,11009.60,0,1,2007-01-19
9,2007-01-19,2007-01-19 16:13:00.000,2007-01-19 20:00:03.000,1,AAON,US0003602069,156,5.981691e+05,3.192061e+05,2.359706e+05,...,41,2.901201e+05,265056.64,61,68,22530.03,20462.31,2,1,2007-01-19

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_daily_v1_2', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-22,2024-01-22 19:01:00.000,2024-01-22 20:00:03.000,1,A,US00846U1016,24845,1.562852e+08,99673223.95,53642515.61,...,5213,1.284889e+08,24826835.88,18945,5900,1547909.85,1421592.18,328,278,2024-01-22
1,2024-01-22,2024-01-22 19:56:00.000,2024-01-22 20:00:03.000,1,AA,US0138721065,46609,1.467629e+08,93640844.80,47984892.92,...,6431,1.359445e+08,5681230.88,44857,1735,3238229.37,1898896.03,1128,672,2024-01-22
2,2024-01-22,2024-01-22 20:01:00.000,2024-01-22 20:00:03.000,1,AAA,US46144X6105,24,6.091857e+04,18807.68,37077.54,...,8,2.794259e+04,27942.59,2,0,5033.35,0.00,5,0,2024-01-22
3,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,AAAU,US38150K1034,1926,6.144968e+07,20750638.57,33377130.97,...,401,4.678125e+07,7346518.43,1544,161,4047935.22,3273973.61,179,131,2024-01-22
4,2024-01-22,2024-01-22 19:07:00.000,2024-01-22 20:00:03.000,1,AACG,US00211V1061,168,1.922372e+04,467.76,16656.42,...,42,8.363580e+03,8760.56,3,10,477.02,1622.58,11,14,2024-01-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-22,2024-01-22 16:01:00.000,2024-01-22 20:00:03.000,1,ACNT,US8715651076,143,4.586393e+04,18901.52,26846.77,...,43,2.354488e+04,22203.40,5,1,83.98,31.56,1,2,2024-01-22
96,2024-01-22,2024-01-22 20:00:00.000,2024-01-22 20:00:03.000,1,ACON,US6551872012,2005,2.726378e+05,53796.58,179751.56,...,723,2.956752e+04,203980.59,130,1875,21255.57,17834.08,229,251,2024-01-22
97,2024-01-22,2024-01-22 14:26:00.000,2024-01-22 20:00:03.000,0,ACONW,US6551871105,1,3.900000e+00,0.00,0.00,...,1,0.000000e+00,0.00,0,0,3.90,0.00,1,0,2024-01-22
98,2024-01-22,2024-01-22 19:14:00.000,2024-01-22 20:00:03.000,1,ACOR,US00484M7002,111,2.359460e+05,180210.96,49210.67,...,39,1.853516e+05,44070.03,60,51,6473.54,50.88,3,2,2024-01-22
99,2024-01-22,2024-01-22 19:57:00.000,2024-01-22 20:00:03.000,1,ACP,US0030571063,2162,3.984211e+06,2186135.99,1540099.86,...,419,1.804736e+06,1921499.75,40,54,191918.87,66056.38,87,22,2024-01-22

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_daily_v1_2',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-08,2007-02-08 20:00:00.000,2007-02-08 20:00:03.000,1,AAPL,US0378331005,112598,2.032911e+09,9.969550e+08,9.863288e+08,...,15532,1.010496e+09,9.727882e+08,57111,55476,28308223.18,21319423.81,1565,1177,2007-02-08
1,2007-01-11,2007-01-11 20:00:00.000,2007-01-11 20:00:03.000,1,AAPL,US0378331005,231957,4.861693e+09,2.323565e+09,2.408443e+09,...,32571,2.103386e+09,2.628622e+09,101463,130149,67452135.59,62232804.83,3154,2943,2007-01-11
2,2007-02-05,2007-02-05 20:00:00.000,2007-02-05 20:00:03.000,1,AAPL,US0378331005,96779,1.695616e+09,7.598101e+08,8.929953e+08,...,11835,3.026589e+08,1.350147e+09,15505,76943,23822862.93,18987486.66,1347,1047,2007-02-05
3,2007-02-26,2007-02-26 20:00:00.000,2007-02-26 20:00:03.000,1,AAPL,US0378331005,102005,1.935809e+09,9.507773e+08,9.310895e+08,...,14418,1.150675e+09,7.311919e+08,62623,39356,27594296.76,26347891.02,1446,1364,2007-02-26
4,2007-02-13,2007-02-13 19:59:00.000,2007-02-13 20:00:03.000,1,AAPL,US0378331005,100533,1.735861e+09,7.666717e+08,9.226778e+08,...,11817,4.338331e+08,1.255516e+09,27679,71790,25993288.65,20518113.71,1515,1128,2007-02-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-06-19,2007-06-19 20:00:00.000,2007-06-19 20:00:03.000,1,AAPL,US0378331005,144641,4.027333e+09,1.853637e+09,2.040225e+09,...,24733,1.390324e+09,2.503538e+09,52027,92566,78603398.20,54868277.98,2780,1934,2007-06-19
96,2007-06-20,2007-06-20 20:00:00.000,2007-06-20 20:00:03.000,1,AAPL,US0378331005,142863,3.816616e+09,1.755577e+09,1.955162e+09,...,23716,1.104609e+09,2.606130e+09,43290,99533,58399867.46,47477556.83,2147,1748,2007-06-20
97,2007-06-28,2007-06-28 20:00:00.000,2007-06-28 20:00:03.000,1,AAPL,US0378331005,126974,3.538269e+09,1.643460e+09,1.773569e+09,...,22593,9.583380e+08,2.458692e+09,38737,87995,68841415.16,52397943.48,2499,1887,2007-06-28
98,2007-04-27,2007-04-27 19:59:00.000,2007-04-27 20:00:03.000,1,AAPL,US0378331005,92993,2.241219e+09,1.090425e+09,1.065621e+09,...,13763,1.295624e+09,8.604224e+08,52990,39764,44798473.32,40374780.73,1859,1631,2007-04-27
99,2007-06-15,2007-06-15 20:00:00.000,2007-06-15 20:00:03.000,1,AAPL,US0378331005,106493,2.661257e+09,1.361937e+09,1.226623e+09,...,12410,2.414433e+09,1.741262e+08,98547,7572,42480714.27,30217103.23,1580,1190,2007-06-15

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_daily_v1_2',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_flow_with_isin_daily_v1_2", target_location="./data", asof_date='2026-01-12')

Starting native python replication for xtech_us_eqt_flow_with_isin_daily_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_with_isin_daily_v1_2. Downloaded 1 files.