In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [12]:
df = Unifier.get_dataframe(name="xtech_us_eqt_flow_with_isin_1min_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2023-05-11,2023-05-11 06:28:00.000,2023-05-11 06:28:03.000,1,NA,None,1,16.6500,8.33,8.33,...,1,16.65,0.00,1,0,0.00,0.00,0,0,2023-05-11
1,2023-05-11,2023-05-11 08:46:00.000,2023-05-11 08:46:03.000,1,NA,None,3,332.5000,332.50,0.00,...,1,332.50,0.00,3,0,0.00,0.00,0,0,2023-05-11
2,2023-05-11,2023-05-11 09:16:00.000,2023-05-11 09:16:03.000,1,NA,None,1,1.1000,1.10,0.00,...,1,1.10,0.00,1,0,0.00,0.00,0,0,2023-05-11
3,2023-05-11,2023-05-11 09:31:00.000,2023-05-11 09:31:03.000,0,TANNI,None,1,25.1500,12.58,12.58,...,1,0.00,25.15,0,1,0.00,0.00,0,0,2023-05-11
4,2023-05-11,2023-05-11 09:31:00.000,2023-05-11 09:31:03.000,0,NA,None,2,207.4500,103.73,103.73,...,1,103.73,103.73,1,1,0.00,0.00,0,0,2023-05-11
5,2023-05-11,2023-05-11 09:37:00.000,2023-05-11 09:37:03.000,0,TANNI,None,1,6194.2800,0.00,6194.28,...,0,0.00,6194.28,0,1,0.00,0.00,0,0,2023-05-11
6,2023-05-11,2023-05-11 09:46:00.000,2023-05-11 09:46:03.000,0,NA,None,1,105.0000,0.00,105.00,...,0,0.00,105.00,0,1,0.00,0.00,0,0,2023-05-11
7,2023-05-11,2023-05-11 09:48:00.000,2023-05-11 09:48:03.000,0,NA,None,1,1.0637,0.00,0.00,...,0,0.00,0.00,0,1,0.00,1.06,0,1,2023-05-11
8,2023-05-11,2023-05-11 09:50:00.000,2023-05-11 09:50:03.000,0,NA,None,12,1227.6285,305.80,920.72,...,2,305.80,920.72,3,9,1.11,0.00,1,0,2023-05-11
9,2023-05-11,2023-05-11 09:51:00.000,2023-05-11 09:51:03.000,0,NA,None,1,105.7200,0.00,0.00,...,1,0.00,0.00,0,1,105.72,0.00,1,0,2023-05-11

## Retrieve data for a specific date range using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_1min_v1_2_1', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-31,2024-01-31 04:01:00.000,2024-01-31 04:01:03.000,1,ATEST.G,None,1,6009.6,3004.80,3004.80,...,1,3004.80,3004.80,0,0,0,0,0,0,2024-01-31
1,2024-01-31,2024-01-31 04:03:00.000,2024-01-31 04:03:03.000,1,ATEST.G,None,1,1502.4,1502.40,0.00,...,0,751.20,751.20,0,0,0,0,0,0,2024-01-31
2,2024-01-31,2024-01-31 04:04:00.000,2024-01-31 04:04:03.000,1,ATEST.G,None,1,1501.8,750.90,750.90,...,1,0.00,1501.80,0,1,0,0,0,0,2024-01-31
3,2024-01-31,2024-01-31 04:22:00.000,2024-01-31 04:22:03.000,1,ATEST.G,None,1,1500.6,750.30,750.30,...,1,0.00,1500.60,0,1,0,0,0,0,2024-01-31
4,2024-01-31,2024-01-31 04:30:00.000,2024-01-31 04:30:03.000,1,ATEST.G,None,1,1500.6,0.00,1500.60,...,0,0.00,1500.60,0,1,0,0,0,0,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 08:06:00.000,2024-01-31 08:06:03.000,1,ATEST.G,None,1,1504.2,1504.20,0.00,...,0,1504.20,0.00,1,0,0,0,0,0,2024-01-31
96,2024-01-31,2024-01-31 08:07:00.000,2024-01-31 08:07:03.000,1,ATEST.G,None,2,2754.1,1377.05,1377.05,...,1,1377.05,1377.05,1,1,0,0,0,0,2024-01-31
97,2024-01-31,2024-01-31 08:07:00.000,2024-01-31 08:07:03.000,1,ATEST.C,None,2,1504.1,752.05,752.05,...,2,752.05,752.05,1,1,0,0,0,0,2024-01-31
98,2024-01-31,2024-01-31 08:08:00.000,2024-01-31 08:08:03.000,1,ATEST.C,None,1,250.6,0.00,250.60,...,0,0.00,250.60,0,1,0,0,0,0,2024-01-31
99,2024-01-31,2024-01-31 08:08:00.000,2024-01-31 08:08:03.000,1,ATEST.G,None,2,1502.4,0.00,1502.40,...,1,0.00,1502.40,0,2,0,0,0,0,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_1min_v1_2_1',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2022-12-30,2022-12-30 04:01:00.000,2022-12-30 04:01:03.000,1,AAPL,US0378331005,99,916075.84,763396.53,152679.31,...,28,777276.47,138799.37,84,15,0,0,0,0,2022-12-30
1,2022-12-30,2022-12-30 04:02:00.000,2022-12-30 04:02:03.000,1,AAPL,US0378331005,30,206229.49,137486.33,68743.16,...,13,96240.43,109989.06,14,16,0,0,0,0,2022-12-30
2,2022-12-30,2022-12-30 04:03:00.000,2022-12-30 04:03:03.000,1,AAPL,US0378331005,31,114370.96,55340.79,59030.17,...,5,59030.17,55340.79,16,15,0,0,0,0,2022-12-30
3,2022-12-30,2022-12-30 04:04:00.000,2022-12-30 04:04:03.000,1,AAPL,US0378331005,17,26136.03,3074.83,23061.20,...,4,3074.83,23061.20,2,15,0,0,0,0,2022-12-30
4,2022-12-30,2022-12-30 04:05:00.000,2022-12-30 04:05:03.000,1,AAPL,US0378331005,14,30777.41,15388.70,15388.70,...,3,19785.48,10991.93,9,5,0,0,0,0,2022-12-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-12-30,2022-12-30 05:36:00.000,2022-12-30 05:36:03.000,1,AAPL,US0378331005,5,4643.53,2786.12,1857.41,...,2,2786.12,1857.41,3,2,0,0,0,0,2022-12-30
96,2022-12-30,2022-12-30 05:37:00.000,2022-12-30 05:37:03.000,1,AAPL,US0378331005,1,128.98,0.00,128.98,...,1,0.00,128.98,0,1,0,0,0,0,2022-12-30
97,2022-12-30,2022-12-30 05:38:00.000,2022-12-30 05:38:03.000,1,AAPL,US0378331005,4,40374.75,20187.38,20187.38,...,0,20187.38,20187.38,2,2,0,0,0,0,2022-12-30
98,2022-12-30,2022-12-30 05:39:00.000,2022-12-30 05:39:03.000,1,AAPL,US0378331005,3,110682.08,36894.03,73788.05,...,0,36894.03,73788.05,1,2,0,0,0,0,2022-12-30
99,2022-12-30,2022-12-30 05:40:00.000,2022-12-30 05:40:03.000,1,AAPL,US0378331005,13,97779.89,15043.06,82736.83,...,6,22564.59,75215.30,3,10,0,0,0,0,2022-12-30

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_with_isin_1min_v1_2_1',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-24,2024-01-24 04:01:00.000,2024-01-24 04:01:03.000,1,AAPL,US0378331005,34,219690.86,158306.65,61384.21,...,17,155075.90,64614.96,24,10,0,0,0,0,2024-01-24
1,2024-01-24,2024-01-24 04:02:00.000,2024-01-24 04:02:03.000,1,AAPL,US0378331005,37,268619.05,152459.46,116159.59,...,7,174239.38,94379.67,24,13,0,0,0,0,2024-01-24
2,2024-01-24,2024-01-24 04:03:00.000,2024-01-24 04:03:03.000,1,AAPL,US0378331005,29,149944.25,118921.30,31022.95,...,1,139603.27,10340.98,27,2,0,0,0,0,2024-01-24
3,2024-01-24,2024-01-24 04:04:00.000,2024-01-24 04:04:03.000,1,AAPL,US0378331005,12,20283.28,1690.27,18593.01,...,3,1690.27,18593.01,1,11,0,0,0,0,2024-01-24
4,2024-01-24,2024-01-24 04:05:00.000,2024-01-24 04:05:03.000,1,AAPL,US0378331005,27,165812.91,49129.75,116683.16,...,7,73694.63,92118.28,12,15,0,0,0,0,2024-01-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-24,2024-01-24 05:36:00.000,2024-01-24 05:36:03.000,1,AAPL,US0378331005,13,26484.88,2037.30,24447.58,...,2,16298.39,10186.49,8,5,0,0,0,0,2024-01-24
96,2024-01-24,2024-01-24 05:37:00.000,2024-01-24 05:37:03.000,1,AAPL,US0378331005,16,39348.59,17215.01,22133.58,...,4,29511.44,9837.15,12,4,0,0,0,0,2024-01-24
97,2024-01-24,2024-01-24 05:38:00.000,2024-01-24 05:38:03.000,1,AAPL,US0378331005,10,25133.61,15080.17,10053.44,...,3,10053.44,15080.17,4,6,0,0,0,0,2024-01-24
98,2024-01-24,2024-01-24 05:39:00.000,2024-01-24 05:39:03.000,1,AAPL,US0378331005,17,31562.07,18565.92,12996.15,...,5,16709.33,14852.74,9,8,0,0,0,0,2024-01-24
99,2024-01-24,2024-01-24 05:40:00.000,2024-01-24 05:40:03.000,1,AAPL,US0378331005,17,72679.62,59853.80,12825.82,...,3,55578.53,17101.09,13,4,0,0,0,0,2024-01-24

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_flow_with_isin_1min_v1_2_1", target_location="./data", asof_date='2026-01-08')

Downloading using native python implementation for xtech_us_eqt_flow_with_isin_1min_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_with_isin_1min_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_flow_with_isin_1min_v1_2_1", target_location="./data")