In [1]:
import os
from IPython.display import display

In [2]:
%pip install unifier --upgrade

Requirement already satisfied: unifier in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (0.1.20)
Requirement already satisfied: requests in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (3.0.1)
Requirement already satisfied: boto3 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (1.42.75)
Requirement already satisfied: botocore<1.43.0,>=1.42.75 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.42.75)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from unifier import unifier

In [ ]:


unifier.user = 'unifier email'
unifier.token ='unifier api token'
os.environ['UNIFIER_USER'] = unifier.user
os.environ['UNIFIER_TOKEN'] = unifier.token

Your 'unifier username' is your account email address, and your 'unifier api token' is your account api token found in the access my data page.

Dataset: xtech_apollo_group_aggregates_red_eagle,
 xtech_apollo_group_style_aggregates_gross_position_style_red_eagle, 
 xtech_apollo_group_style_aggregates_trade_size_style_red_eagle, 
 xtech_apollo_group_style_aggregates_turnover_style_red_eagle

In [ ]:
# Replicate a large dataset to a local folder
# Note: rclone must be installed on your system
unifier.replicate(
    name="xtech_apollo_group_aggregates_red_eagle",
    target_location="./your_local_path",
    back_to="",    # Optional: fetch history back to this date
    up_to="",    # Optional: fetch history up to this date
    bandwidth_limit=20       # Optional: limit download speed to 20MB/s
)

Downloading using native python implementation for xtech_apollo_group_aggregates_red_eagle...
Found 1880 files to download.
Downloaded 10/1880 files...
Downloaded 20/1880 files...
Downloaded 30/1880 files...

KeyboardInterrupt:

In [ ]:
df = unifier.get_dataframe(name="xtech_apollo_group_aggregates_red_eagle", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,trade_date,sector,mds_exchange,exchange_country,reportable_product,product_name,xt_group,direction,long_dollar_value,short_dollar_value,net_dollar_value,gross_dollar_value,long_position,short_position,net_position,gross_position,long_position_concentration,short_position_concentration,combined_position_concentration
0,2021-01-05 00:00:00.000,20210104,EQY,EUREX,DEU,(H,EUREX STOXX EUROPE 600 ESG-X FUTURES,other_reportables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,1.0,7.371172e+08,4.775354e+08,2.595817e+08,1.214653e+09,35017.0,28519.0,6498.0,63536.0,0.050021,0.053017,0.026616
2,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,1.0,2.644754e+07,1.546508e+07,1.098246e+07,4.191262e+07,706.0,431.0,275.0,1137.0,0.043663,0.239159,0.049947
3,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,other_reportables,1.0,7.936906e+07,2.591101e+07,5.345805e+07,1.052801e+08,2262.0,1003.0,1259.0,3265.0,0.176800,0.183634,0.111606
4,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,-1.0,8.190700e+06,2.750862e+07,-1.931792e+07,3.569932e+07,203.0,657.0,-454.0,860.0,0.134883,0.647071,0.391311
5,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,managed_money,1.0,6.862702e+07,9.317720e+06,5.930930e+07,7.794474e+07,1752.0,346.0,1406.0,2098.0,0.083932,0.548584,0.072904
6,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,producer,-1.0,2.006969e+08,2.108687e+08,-1.017180e+07,4.115657e+08,13846.0,14092.0,-246.0,27938.0,0.102484,0.076300,0.044400
7,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,1.0,8.901712e+07,7.795236e+06,8.122188e+07,9.681235e+07,3836.0,473.0,3363.0,4309.0,0.075421,0.354733,0.066064
8,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,other_reportables,1.0,9.437258e+07,2.926698e+07,6.510560e+07,1.236396e+08,3971.0,1305.0,2666.0,5276.0,0.077201,0.216523,0.057111
9,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,swap,-1.0,9.648540e+05,1.395262e+07,-1.298777e+07,1.491748e+07,39.0,554.0,-515.0,593.0,0.303820,0.470708,0.413058
10,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,managed_money,1.0,9.735136e+07,1.988843e+07,7.746293e+07,1.172398e+08,4085.0,947.0,3138.0,5032.0,0.072371,0.621546,0.067786
11,2021-01-05 00:00:00.000,20210104,NRG,IPE,GBR,14Y,ICEEU ULSD 10PPM CIF NWE CARGOES F,other_reportables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,producer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,nonreportable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,other_reportables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,swap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-01-05 00:00:00.000,20210104,AGR,CBOT,USA,14,CBOT CRC ROUGH RICE FUTURE,managed_money,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-01-05 00:00:00.000,20210104,INT,CBOT,USA,17,CBOT US TREASURY BOND FUTURE,producer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2021-01-05 00:00:00.000,20210104,INT,CBOT,USA,17,CBOT US TREASURY BOND FUTURE,nonreportable,1.0,4.233210e+09,9.170656e+06,4.224039e+09,4.242380e+09,24465.0,53.0,24412.0,24518.0,0.493449,0.177643,0.491319
19,2021-01-05 00:00:00.000,20210104,INT,CBOT,USA,17,CBOT US TREASURY BOND FUTURE,other_reportables,-1.0,5.588909e+07,1.197376e+08,-6.384853e+07,1.756267e+08,328.0,697.0,-369.0,1025.0,0.347219,0.246709,0.149836

In [10]:
df = unifier.get_dataframe(name="xtech_apollo_group_style_aggregates_gross_position_style_red_eagle", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,trade_date,sector,mds_exchange,exchange_country,reportable_product,product_name,xt_group,position_style,direction,...,short_dollar_value,net_dollar_value,gross_dollar_value,long_position,short_position,net_position,gross_position,long_position_concentration,short_position_concentration,combined_position_concentration
0,2021-01-13 00:00:00.000,20210112,EQY,EUREX,DEU,(H,EUREX STOXX EUROPE 600 ESG-X FUTURES,other_reportables,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,managed_money,small,1,...,0.0,2349930.0,2.349930e+06,70.0,20.0,50.0,90.0,0.085954,0.000000,0.085954
2,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,managed_money,medium,1,...,1023880.0,6717480.0,8.765240e+06,190.0,44.0,146.0,234.0,0.206893,0.537190,0.168711
3,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,managed_money,large,1,...,15120.0,46308620.0,4.633886e+07,1331.0,326.0,1005.0,1657.0,0.159425,1.000000,0.159321
4,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,small,1,...,187800.0,2188630.0,2.564230e+06,54.0,6.0,48.0,60.0,0.063647,0.245698,0.055983
5,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,other_reportables,small,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,other_reportables,medium,1,...,1045060.0,2748450.0,4.838570e+06,121.0,61.0,60.0,182.0,0.126877,0.576736,0.104893
9,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,other_reportables,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,small,1,...,487680.0,9533920.0,1.050928e+07,239.0,24.0,215.0,263.0,0.051520,0.189304,0.047257
11,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,medium,1,...,14551020.0,28980960.0,5.808300e+07,1186.0,510.0,676.0,1696.0,0.032083,0.279374,0.035555
12,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,large,1,...,351610340.0,297614260.0,1.000835e+09,28725.0,21795.0,6930.0,50520.0,0.271686,0.082170,0.124464
13,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,small,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,large,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,managed_money,small,1,...,77628.0,2143914.0,2.299170e+06,93.0,9.0,84.0,102.0,0.062793,0.542966,0.059243
17,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,managed_money,medium,1,...,9750.0,6128052.0,6.147552e+06,270.0,30.0,240.0,300.0,0.066896,0.226374,0.066685
18,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,managed_money,large,1,...,109200.0,61842318.0,6.206072e+07,3439.0,976.0,2463.0,4415.0,0.112697,0.199441,0.112301
19,2021-01-13 00:00:00.000,20210112,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,small,1,...,76734.0,816444.0,9.699120e+05,37.0,5.0,32.0,42.0,0.062266,1.000000,0.059063

In [11]:
df = unifier.get_dataframe(name="xtech_apollo_group_style_aggregates_trade_size_style_red_eagle", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,trade_date,sector,mds_exchange,exchange_country,reportable_product,product_name,xt_group,trade_size_style,direction,...,short_dollar_value,net_dollar_value,gross_dollar_value,long_position,short_position,net_position,gross_position,long_position_concentration,short_position_concentration,combined_position_concentration
0,2021-01-07 00:00:00.000,20210106,EQY,EUREX,DEU,(H,EUREX STOXX EUROPE 600 ESG-X FUTURES,other_reportables,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,managed_money,small,1,...,525960.0,48213820.0,49265740.0,1172.0,66.0,1106.0,1238.0,0.133714,0.513889,0.130933
2,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,managed_money,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,small,1,...,6885640.0,28184350.0,41955630.0,1012.0,301.0,711.0,1313.0,0.331012,0.403146,0.242136
4,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,other_reportables,small,1,...,896430.0,50821530.0,52614390.0,1363.0,192.0,1171.0,1555.0,0.397390,0.263324,0.384041
6,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,other_reportables,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,small,1,...,104876260.0,112558510.0,322311030.0,6956.0,4275.0,2681.0,11231.0,0.062496,0.165492,0.045964
8,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,medium,1,...,239232810.0,176421670.0,654887290.0,19217.0,14845.0,4372.0,34062.0,0.580607,0.149467,0.253837
9,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,large,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,small,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,large,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,managed_money,small,1,...,269976.0,61238862.0,61778814.0,2512.0,174.0,2338.0,2686.0,0.099706,0.082467,0.098838
14,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,managed_money,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,small,1,...,64122.0,86220066.0,86348310.0,3644.0,205.0,3439.0,3849.0,0.569706,0.684232,0.568860
16,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,other_reportables,small,1,...,15010506.0,44824584.0,74845596.0,2416.0,620.0,1796.0,3036.0,0.552351,0.964038,0.391791
18,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,other_reportables,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-01-07 00:00:00.000,20210106,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,producer,small,1,...,121535718.0,4758852.0,247830288.0,6527.0,6258.0,269.0,12785.0,0.223175,0.165915,0.097858

In [12]:
df = unifier.get_dataframe(name="xtech_apollo_group_style_aggregates_turnover_style_red_eagle", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,trade_date,sector,mds_exchange,exchange_country,reportable_product,product_name,xt_group,turnover_style,direction,...,short_dollar_value,net_dollar_value,gross_dollar_value,long_position,short_position,net_position,gross_position,long_position_concentration,short_position_concentration,combined_position_concentration
0,2021-01-12 00:00:00.000,20210111,EQY,EUREX,DEU,(H,EUREX STOXX EUROPE 600 ESG-X FUTURES,other_reportables,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,managed_money,low,1,...,1563800.0,46198670.0,49326270.0,1491.0,446.0,1045.0,1937.0,0.138632,0.369796,0.130352
2,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,managed_money,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,low,1,...,12025640.0,15326090.0,39377370.0,766.0,395.0,371.0,1161.0,0.281986,0.313726,0.165312
4,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,nonreportable,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,other_reportables,low,1,...,8770060.0,44703940.0,62244060.0,1813.0,775.0,1038.0,2588.0,0.366425,0.698277,0.284305
6,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,other_reportables,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,low,1,...,246613460.0,418448680.0,911675600.0,20306.0,10418.0,9888.0,30724.0,0.268255,0.115588,0.151213
8,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,producer,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,low,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,06,CBOT SOYBEAN MEAL FUTURE,swap,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,managed_money,low,1,...,234552.0,71883642.0,72352746.0,3867.0,1009.0,2858.0,4876.0,0.084744,0.139003,0.084197
12,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,managed_money,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,low,1,...,148968.0,91701942.0,91999878.0,4204.0,482.0,3722.0,4686.0,0.607616,0.455250,0.605651
14,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,nonreportable,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,other_reportables,low,1,...,18541848.0,55731300.0,92814996.0,3119.0,863.0,2256.0,3982.0,0.357513,0.628314,0.254014
16,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,other_reportables,medium,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,producer,low,-1,...,152731434.0,-12847566.0,292615302.0,12269.0,12697.0,-428.0,24966.0,0.218830,0.107984,0.079428
18,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,producer,medium,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-01-12 00:00:00.000,20210111,AGR,CBOT,USA,07,CBOT SOYBEAN OIL FUTURE,swap,low,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN