In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_daily_regular_v2", back_to='2025-11-18', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,AAAU,46.64,46.8250,46.44,46.680,1168454,5313,46.618770,46.616981,46.622281,46.68,46.69,46.685,2026-05-11,2026-05-11
1,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,AACB,10.38,10.4092,10.38,10.390,493,3,10.380316,10.380316,NaN,10.39,10.43,10.410,2026-05-11,2026-05-11
2,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,AACG,1.17,1.2400,1.14,1.180,28346,162,1.188029,1.169183,1.197745,1.14,1.18,1.160,2026-05-11,2026-05-11
3,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,AAP,55.67,55.9700,51.76,51.820,1541786,30568,52.617873,52.659968,52.529280,51.82,51.85,51.835,2026-05-11,2026-05-11
4,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,ABIG,33.60,33.6600,33.47,33.470,51122,19,33.645575,33.470782,33.646961,33.48,33.52,33.500,2026-05-11,2026-05-11
5,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,ABLS,20.48,20.8000,20.48,20.570,11,7,20.664091,20.685000,20.570000,20.52,20.57,20.545,2026-05-11,2026-05-11
6,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,ABNY,43.31,44.3250,41.93,41.940,5392,127,42.774679,42.942215,42.594146,41.66,41.95,41.805,2026-05-11,2026-05-11
7,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,ABOT,36.97,37.6100,36.97,37.330,51,4,37.422745,37.527083,NaN,37.38,37.42,37.400,2026-05-11,2026-05-11
8,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,ABR,7.18,7.2000,6.60,6.655,10864634,38796,6.789604,6.809443,6.779342,6.65,6.66,6.655,2026-05-11,2026-05-11
9,2026-05-11 20:00:00.000,2026-05-11 20:00:03.000,ACGCU,10.01,10.0100,9.98,10.010,555,5,9.997964,9.980000,10.010000,9.99,10.01,10.000,2026-05-11,2026-05-11

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_sip_bardata_flow_daily_regular_v2', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,AAN,20.5700,20.9000,20.2501,20.8500,502352,3411,20.687458,20.682081,20.707144,20.85,20.86,20.855,2021-01-12,2021-01-12
1,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,AAXN,126.3600,135.0500,126.0000,135.0100,1025351,13954,131.238773,131.761627,132.369376,135.01,135.03,135.020,2021-01-12,2021-01-12
2,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,ABC,107.4900,107.8000,106.1001,106.5200,1114501,17268,106.888518,106.845749,106.911139,106.52,106.53,106.525,2021-01-12,2021-01-12
3,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,ABEO,1.8400,1.9500,1.7800,1.8300,2193039,7059,1.852893,1.851805,1.854660,1.82,1.83,1.825,2021-01-12,2021-01-12
4,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,ABG,163.5200,172.3700,162.5750,167.4900,139182,3357,168.846484,168.632152,169.036072,167.55,167.69,167.620,2021-01-12,2021-01-12
5,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,ABIO,4.3100,4.3900,4.2700,4.3400,246376,1426,4.330329,4.322558,4.339548,4.30,4.34,4.320,2021-01-12,2021-01-12
6,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,ABRpA,25.6002,25.6599,25.6000,25.6599,207,4,25.601351,NaN,25.601351,25.50,25.66,25.580,2021-01-12,2021-01-12
7,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,ACACU,10.9137,11.1500,10.7738,11.1300,95511,133,11.058908,11.065090,11.019532,11.00,11.15,11.075,2021-01-12,2021-01-12
8,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,ACEVW,2.7500,2.8300,2.6100,2.6600,584865,1165,2.690478,2.675068,2.694201,2.66,2.69,2.675,2021-01-12,2021-01-12
9,2021-01-12 21:00:00.000,2021-01-12 21:00:03.000,ACIC.U,11.0200,11.2900,10.9475,11.0500,335606,883,11.073463,11.073087,11.070436,11.03,11.05,11.040,2021-01-12,2021-01-12

In [6]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_daily_regular_v2", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-07-09 20:00:00.000,2026-07-09 20:00:03.000,PSR,102.82,103.9200,102.820,103.4117,3746,56,103.440852,103.068085,103.664780,103.25,103.40,103.325,2026-07-09,2026-07-09
1,2026-03-20 20:00:00.000,2026-03-20 20:00:03.000,PSR,95.70,95.7000,92.410,92.5600,6263,88,93.302620,92.804063,93.485420,92.46,92.56,92.510,2026-03-20,2026-03-20
2,2026-03-17 20:00:00.000,2026-03-17 20:00:03.000,PSR,97.70,98.0999,97.260,97.3300,687,20,97.534241,97.458279,97.574555,97.27,97.34,97.305,2026-03-17,2026-03-17
3,2026-05-08 20:00:00.000,2026-05-08 20:00:03.000,PSR,101.47,102.5050,101.470,102.0100,640,30,102.170863,102.048836,102.296120,102.01,102.09,102.050,2026-05-08,2026-05-08
4,2026-03-18 20:00:00.000,2026-03-18 20:00:03.000,PSR,96.96,97.0687,96.155,96.1550,628,22,96.829966,96.864969,96.822711,95.91,95.97,95.940,2026-03-18,2026-03-18
5,2026-09-04 20:00:00.000,2026-09-04 20:00:03.000,PSR,102.00,102.9600,102.000,102.3300,512,22,102.788600,102.464212,102.953193,102.05,102.13,102.090,2026-09-04,2026-09-04
6,2026-04-16 20:00:00.000,2026-04-16 20:00:03.000,PSR,98.45,99.4850,98.450,99.4850,1036,28,99.263306,99.306199,99.210278,99.50,99.58,99.540,2026-04-16,2026-04-16
7,2026-07-07 20:00:00.000,2026-07-07 20:00:03.000,PSR,103.53,105.2400,103.530,104.7100,1813,42,105.054450,105.067792,105.052117,104.55,104.66,104.605,2026-07-07,2026-07-07
8,2026-04-14 20:00:00.000,2026-04-14 20:00:03.000,PSR,97.95,98.6850,97.525,98.6000,1341,49,98.054676,98.208147,97.965958,98.60,98.65,98.625,2026-04-14,2026-04-14
9,2026-05-20 20:00:00.000,2026-05-20 20:00:03.000,PSR,101.21,102.2500,101.210,102.2196,1011,25,101.938308,101.930805,102.039413,102.41,102.50,102.455,2026-05-20,2026-05-20

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_daily_regular_v2", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_daily_regular_v2...
Found 1 files to download.
Native replication completed for xtech_us_eqt_sip_bardata_flow_daily_regular_v2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_daily_regular_v2", target_location="./data")