In [3]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [4]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [6]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_1min_v2", back_to='2025-11-18', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-09-08 15:10:00.000,2026-09-08 15:10:03.000,AAPX,36.33,36.33,36.33,36.33,55.0,1.0,36.330000,NaN,36.330000,36.25,36.29,36.270,2026-09-08,2026-09-08
1,2026-09-08 15:14:00.000,2026-09-08 15:14:03.000,AAPX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.41,36.45,36.430,2026-09-08,2026-09-08
2,2026-09-08 15:22:00.000,2026-09-08 15:22:03.000,AAPX,36.30,36.30,36.27,36.29,561.0,4.0,36.270410,36.27,36.290909,36.27,36.30,36.285,2026-09-08,2026-09-08
3,2026-09-08 15:36:00.000,2026-09-08 15:36:03.000,AAPX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.37,36.41,36.390,2026-09-08,2026-09-08
4,2026-09-08 15:17:00.000,2026-09-08 15:17:03.000,AAPX,36.42,36.42,36.40,36.40,304.0,2.0,36.417105,NaN,36.417105,36.38,36.41,36.395,2026-09-08,2026-09-08
5,2026-09-08 15:30:00.000,2026-09-08 15:30:03.000,AAPX,36.43,36.44,36.43,36.44,36.0,2.0,36.433056,NaN,36.433056,36.36,36.39,36.375,2026-09-08,2026-09-08
6,2026-09-08 15:20:00.000,2026-09-08 15:20:03.000,AAPX,36.30,36.30,36.30,36.30,1.0,1.0,36.300000,36.30,NaN,36.28,36.31,36.295,2026-09-08,2026-09-08
7,2026-09-08 15:34:00.000,2026-09-08 15:34:03.000,AAPX,36.38,36.39,36.36,36.36,1235.0,9.0,36.379830,36.36,36.380614,36.36,36.40,36.380,2026-09-08,2026-09-08
8,2026-09-08 15:28:00.000,2026-09-08 15:28:03.000,AAPX,36.43,36.43,36.40,36.41,52.0,4.0,36.415988,36.40,36.419795,36.37,36.41,36.390,2026-09-08,2026-09-08
9,2026-09-08 17:14:00.000,2026-09-08 17:14:03.000,AAPX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.35,36.38,36.365,2026-09-08,2026-09-08

In [9]:
df = Unifier.get_dataframe(name='xtech_us_eqt_sip_bardata_flow_1min_v2', back_to='2018-01-11', up_to='2021-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2018-06-22 15:47:00.000,2018-06-22 15:47:03.000,ABCB,57.1500,57.1500,57.1000,57.1000,402,7,57.137562,57.137562,NaN,57.05,57.10,57.075,2018-06-22,2018-06-22
1,2018-06-22 13:37:00.000,2018-06-22 13:37:03.000,ABCB,57.3500,57.4500,57.3000,57.4500,124,3,57.421371,57.302083,57.450000,57.30,57.45,57.375,2018-06-22,2018-06-22
2,2018-06-22 16:23:00.000,2018-06-22 16:23:03.000,ABCB,57.1000,57.1000,57.1000,57.1000,400,3,57.100000,57.100000,NaN,57.10,57.20,57.150,2018-06-22,2018-06-22
3,2018-06-22 16:56:00.000,2018-06-22 16:56:03.000,ABCB,56.8000,56.8000,56.8000,56.8000,100,1,56.800000,NaN,NaN,56.75,56.85,56.800,2018-06-22,2018-06-22
4,2018-06-22 17:58:00.000,2018-06-22 17:58:03.000,ABCB,57.1178,57.1500,57.1178,57.1500,431,2,57.125271,57.150000,57.117800,57.10,57.20,57.150,2018-06-22,2018-06-22
5,2018-06-22 15:31:00.000,2018-06-22 15:31:03.000,ABCB,57.0000,57.0500,57.0000,57.0000,2409,22,57.002076,57.000000,57.008237,56.95,57.00,56.975,2018-06-22,2018-06-22
6,2018-06-22 16:44:00.000,2018-06-22 16:44:03.000,ABCB,56.9499,56.9499,56.9499,56.9499,1,1,56.949900,NaN,56.949900,NaN,NaN,NaN,2018-06-22,2018-06-22
7,2018-06-22 19:44:00.000,2018-06-22 19:44:03.000,ABCB,56.4500,56.4500,56.4000,56.4000,1601,18,56.432823,56.422222,56.450000,56.40,56.45,56.425,2018-06-22,2018-06-22
8,2018-06-22 19:30:00.000,2018-06-22 19:30:03.000,ABCB,56.4500,56.5000,56.4500,56.4750,251,5,56.479980,56.450000,NaN,56.45,56.50,56.475,2018-06-22,2018-06-22
9,2018-06-22 15:24:00.000,2018-06-22 15:24:03.000,ABCB,57.1000,57.1000,56.9500,57.0000,714,10,56.993137,56.991843,57.100000,56.95,57.05,57.000,2018-06-22,2018-06-22

In [8]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_1min_v2", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-08-27 15:08:00.000,2026-08-27 15:08:03.000,PSR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.07,104.19,104.130,2026-08-27,2026-08-27
1,2026-08-27 15:33:00.000,2026-08-27 15:33:03.000,PSR,104.17,104.17,104.17,104.17,73.0,1.0,104.17,104.17,NaN,104.20,104.30,104.250,2026-08-27,2026-08-27
2,2026-08-27 15:02:00.000,2026-08-27 15:02:03.000,PSR,104.19,104.19,104.19,104.19,2.0,1.0,104.19,NaN,104.19,104.04,104.19,104.115,2026-08-27,2026-08-27
3,2026-08-27 15:24:00.000,2026-08-27 15:24:03.000,PSR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.18,104.30,104.240,2026-08-27,2026-08-27
4,2026-08-27 15:21:00.000,2026-08-27 15:21:03.000,PSR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.22,104.35,104.285,2026-08-27,2026-08-27
5,2026-08-27 15:17:00.000,2026-08-27 15:17:03.000,PSR,104.31,104.31,104.31,104.31,1.0,1.0,104.31,NaN,104.31,104.18,104.31,104.245,2026-08-27,2026-08-27
6,2026-08-27 15:36:00.000,2026-08-27 15:36:03.000,PSR,104.33,104.33,104.33,104.33,55.0,1.0,104.33,NaN,104.33,104.22,104.35,104.285,2026-08-27,2026-08-27
7,2026-08-27 15:12:00.000,2026-08-27 15:12:03.000,PSR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.15,104.29,104.220,2026-08-27,2026-08-27
8,2026-08-27 15:09:00.000,2026-08-27 15:09:03.000,PSR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.04,104.17,104.105,2026-08-27,2026-08-27
9,2026-08-27 15:14:00.000,2026-08-27 15:14:03.000,PSR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.18,104.32,104.250,2026-08-27,2026-08-27

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_1min_v2", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_1min_v2...
Found 1 files to download.
Native replication completed for xtech_us_eqt_sip_bardata_flow_1min_v2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_1min_v2", target_location="./data")