In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [9]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_60min_v2", back_to='2025-11-18', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-09-08 14:00:00.000,2026-09-08 14:00:03.000,AAA,24.8900,24.9700,24.7500,24.9700,1756,3,24.890103,24.889920,NaN,24.92,25.02,24.970,2026-09-08,2026-09-08
1,2026-09-08 15:00:00.000,2026-09-08 15:00:03.000,AAA,24.9500,25.0900,24.9500,25.0900,9127,96,25.079454,24.963333,25.079500,25.00,25.09,25.045,2026-09-08,2026-09-08
2,2026-09-08 16:00:00.000,2026-09-08 16:00:03.000,AAA,25.0400,25.0400,25.0100,25.0100,688,9,25.033765,25.010000,25.040000,24.99,25.04,25.015,2026-09-08,2026-09-08
3,2026-09-08 17:00:00.000,2026-09-08 17:00:03.000,AAA,25.0400,25.0400,25.0001,25.0001,2001,4,25.039980,25.000100,25.040000,25.00,25.04,25.020,2026-09-08,2026-09-08
4,2026-09-08 18:00:00.000,2026-09-08 18:00:03.000,AAA,25.0400,25.0400,25.0100,25.0100,131,5,25.018048,25.010000,25.037150,25.00,25.04,25.020,2026-09-08,2026-09-08
5,2026-09-08 19:00:00.000,2026-09-08 19:00:03.000,AAA,25.0200,25.0200,25.0000,25.0100,308,11,25.005543,25.005108,NaN,24.98,25.04,25.010,2026-09-08,2026-09-08
6,2026-09-08 20:00:00.000,2026-09-08 20:00:03.000,AAA,24.9801,25.0400,24.9801,24.9900,2214,15,24.992710,24.990147,25.022022,24.98,25.04,25.010,2026-09-08,2026-09-08
7,2026-09-08 21:00:00.000,2026-09-08 21:00:03.000,AAA,25.0100,25.0100,25.0100,25.0100,1,1,25.010000,25.010000,NaN,NaN,NaN,NaN,2026-09-08,2026-09-08
8,2026-09-08 14:00:00.000,2026-09-08 14:00:03.000,AAAD,49.3100,49.3157,49.3100,49.3157,4,2,49.314275,49.314275,NaN,49.31,49.35,49.330,2026-09-08,2026-09-08
9,2026-09-08 15:00:00.000,2026-09-08 15:00:03.000,AAAD,49.3243,49.3243,49.3057,49.3057,3,3,49.318100,NaN,49.318100,49.30,49.33,49.315,2026-09-08,2026-09-08

In [10]:
df = Unifier.get_dataframe(name='xtech_us_eqt_sip_bardata_flow_60min_v2', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2021-01-14 13:00:00.000,2021-01-14 13:00:03.000,AACQU,11.8500,11.8500,11.8500,11.8500,30,1,11.850000,11.850000,NaN,NaN,NaN,NaN,2021-01-14,2021-01-14
1,2021-01-14 14:00:00.000,2021-01-14 14:00:03.000,AACQU,12.4900,12.5000,12.4500,12.5000,10800,19,12.497622,12.497049,12.499335,12.00,13.49,12.745,2021-01-14,2021-01-14
2,2021-01-14 15:00:00.000,2021-01-14 15:00:03.000,AACQU,12.0700,12.1000,11.8000,11.9600,63809,818,11.915523,11.926774,11.909384,NaN,NaN,NaN,2021-01-14,2021-01-14
3,2021-01-14 16:00:00.000,2021-01-14 16:00:03.000,AACQU,11.9400,11.9700,11.8500,11.9100,91916,384,11.913150,11.923699,11.897812,11.90,11.95,11.925,2021-01-14,2021-01-14
4,2021-01-14 17:00:00.000,2021-01-14 17:00:03.000,AACQU,11.9250,12.1400,11.9000,12.0700,122442,579,12.059491,12.070141,12.003421,12.06,12.10,12.080,2021-01-14,2021-01-14
5,2021-01-14 18:00:00.000,2021-01-14 18:00:03.000,AACQU,12.0600,12.0600,11.9400,11.9500,706,12,11.971955,11.970000,NaN,11.98,12.04,12.010,2021-01-14,2021-01-14
6,2021-01-14 19:00:00.000,2021-01-14 19:00:03.000,AACQU,11.9700,11.9800,11.9000,11.9600,38230,144,11.939402,11.935359,11.928728,11.94,11.98,11.960,2021-01-14,2021-01-14
7,2021-01-14 20:00:00.000,2021-01-14 20:00:03.000,AACQU,11.9799,11.9799,11.9219,11.9305,52871,28,11.949732,11.949610,11.972714,11.93,11.98,11.955,2021-01-14,2021-01-14
8,2021-01-14 21:00:00.000,2021-01-14 21:00:03.000,AACQU,11.9000,11.9100,11.8500,11.9000,55063,424,11.891487,11.885774,11.893723,11.86,11.91,11.885,2021-01-14,2021-01-14
9,2021-01-14 22:00:00.000,2021-01-14 22:00:03.000,AACQU,11.8850,11.9100,11.8600,11.9000,7741,31,11.892618,11.887072,11.900297,11.50,12.50,12.000,2021-01-14,2021-01-14

In [11]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_60min_v2", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-09-03 14:00:00.000,2026-09-03 14:00:03.000,PSR,102.1000,102.100,102.0100,102.0200,10,3,102.083000,102.083000,NaN,102.18,102.38,102.280,2026-09-03,2026-09-03
1,2026-09-03 15:00:00.000,2026-09-03 15:00:03.000,PSR,102.1700,102.270,101.9700,102.2700,25,5,102.182000,102.120000,NaN,102.28,102.41,102.345,2026-09-03,2026-09-03
2,2026-09-03 16:00:00.000,2026-09-03 16:00:03.000,PSR,102.4950,102.750,102.4950,102.7500,185,4,102.638378,102.502037,NaN,102.73,102.83,102.780,2026-09-03,2026-09-03
3,2026-09-03 17:00:00.000,2026-09-03 17:00:03.000,PSR,102.7600,102.760,102.4553,102.4800,61,6,102.593911,102.468144,102.760000,102.61,102.71,102.660,2026-09-03,2026-09-03
4,2026-09-03 18:00:00.000,2026-09-03 18:00:03.000,PSR,102.6350,102.635,102.5526,102.5526,6,2,102.593800,102.552600,NaN,102.49,102.59,102.540,2026-09-03,2026-09-03
5,2026-09-03 19:00:00.000,2026-09-03 19:00:03.000,PSR,102.5400,102.610,102.5400,102.5800,260,7,102.588508,102.580000,102.606619,102.64,102.72,102.680,2026-09-03,2026-09-03
6,2026-09-03 20:00:00.000,2026-09-03 20:00:03.000,PSR,102.7700,102.770,102.5900,102.6400,154,6,102.655080,102.668520,NaN,102.66,102.77,102.715,2026-09-03,2026-09-03
7,2026-09-03 21:00:00.000,2026-09-03 21:00:03.000,PSR,102.7100,102.710,102.6768,102.6768,7,4,102.695771,102.710000,102.676800,NaN,NaN,NaN,2026-09-03,2026-09-03
8,2026-08-25 14:00:00.000,2026-08-25 14:00:03.000,PSR,105.7400,105.740,105.2250,105.2250,143,8,105.436555,105.319700,105.574762,105.15,105.38,105.265,2026-08-25,2026-08-25
9,2026-08-25 15:00:00.000,2026-08-25 15:00:03.000,PSR,105.3099,105.510,105.0527,105.5100,23,6,105.332113,NaN,105.239907,105.49,105.62,105.555,2026-08-25,2026-08-25

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_60min_v2", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_60min_v2...
Found 1 files to download.
Native replication completed for xtech_us_eqt_sip_bardata_flow_60min_v2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_60min_v2", target_location="./data")