In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_5min_v2", back_to='2025-11-18', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-03-04 15:40:00.000,2026-03-04 15:40:03.000,AAVM,32.8200,32.8200,32.8200,32.8200,150,1,32.820000,NaN,NaN,32.77,32.89,32.830,2026-03-04,2026-03-04
1,2026-03-04 18:45:00.000,2026-03-04 18:45:03.000,AAVM,32.8500,32.8600,32.8500,32.8600,69,2,32.850435,NaN,32.850435,32.75,32.88,32.815,2026-03-04,2026-03-04
2,2026-03-04 18:55:00.000,2026-03-04 18:55:03.000,AAVM,32.8899,32.8899,32.8899,32.8899,10,1,32.889900,NaN,32.889900,32.77,32.89,32.830,2026-03-04,2026-03-04
3,2026-03-04 20:15:00.000,2026-03-04 20:15:03.000,AAVM,32.8278,32.8278,32.8278,32.8278,1,1,32.827800,32.8278,NaN,32.82,32.92,32.870,2026-03-04,2026-03-04
4,2026-03-04 20:35:00.000,2026-03-04 20:35:03.000,AAVM,32.9100,32.9100,32.9100,32.9100,304,3,32.910000,NaN,32.910000,32.83,32.93,32.880,2026-03-04,2026-03-04
5,2026-03-04 21:00:00.000,2026-03-04 21:00:03.000,AAVM,32.8800,32.8800,32.8800,32.8800,25,1,32.880000,NaN,NaN,32.84,32.92,32.880,2026-03-04,2026-03-04
6,2026-03-04 21:10:00.000,2026-03-04 21:10:03.000,AAVM,32.8726,32.8726,32.8726,32.8726,1,1,32.872600,32.8726,NaN,23.00,49.18,36.090,2026-03-04,2026-03-04
7,2026-03-04 14:40:00.000,2026-03-04 14:40:03.000,AAVM,32.8033,32.8033,32.8033,32.8033,2,1,32.803300,NaN,32.803300,32.58,32.72,32.650,2026-03-04,2026-03-04
8,2026-03-04 14:50:00.000,2026-03-04 14:50:03.000,AAVM,32.5916,32.5916,32.5916,32.5916,1,1,32.591600,32.5916,NaN,32.55,32.69,32.620,2026-03-04,2026-03-04
9,2026-03-04 15:00:00.000,2026-03-04 15:00:03.000,AAVM,32.6150,32.6150,32.6150,32.6150,8,1,32.615000,NaN,32.615000,32.55,32.67,32.610,2026-03-04,2026-03-04

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_sip_bardata_flow_5min_v2', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2021-01-25 16:10:00.000,2021-01-25 16:10:03.000,AACQU,12.00,12.0000,11.90,11.9150,24891,71,11.937518,11.937564,NaN,11.88,11.95,11.915,2021-01-25,2021-01-25
1,2021-01-25 16:15:00.000,2021-01-25 16:15:03.000,AACQU,11.88,11.8800,11.87,11.8700,160,2,11.876875,11.876875,NaN,11.86,11.92,11.890,2021-01-25,2021-01-25
2,2021-01-25 16:20:00.000,2021-01-25 16:20:03.000,AACQU,11.88,11.8800,11.88,11.8800,100,1,11.880000,NaN,11.880000,11.87,11.92,11.895,2021-01-25,2021-01-25
3,2021-01-25 16:25:00.000,2021-01-25 16:25:03.000,AACQU,11.88,11.8800,11.88,11.8800,100,1,11.880000,11.880000,NaN,11.89,11.95,11.920,2021-01-25,2021-01-25
4,2021-01-25 16:40:00.000,2021-01-25 16:40:03.000,AACQU,11.95,11.9500,11.95,11.9500,100,1,11.950000,11.950000,NaN,11.90,11.97,11.935,2021-01-25,2021-01-25
5,2021-01-25 16:50:00.000,2021-01-25 16:50:03.000,AACQU,11.90,11.9268,11.90,11.9268,200,2,11.913400,11.913400,NaN,11.90,11.98,11.940,2021-01-25,2021-01-25
6,2021-01-25 16:55:00.000,2021-01-25 16:55:03.000,AACQU,11.94,11.9800,11.94,11.9500,12100,95,11.953256,11.953672,11.950968,11.93,11.99,11.960,2021-01-25,2021-01-25
7,2021-01-25 17:10:00.000,2021-01-25 17:10:03.000,AACQU,11.90,11.9000,11.90,11.9000,100,1,11.900000,11.900000,NaN,11.90,11.95,11.925,2021-01-25,2021-01-25
8,2021-01-25 17:25:00.000,2021-01-25 17:25:03.000,AACQU,11.91,11.9100,11.91,11.9100,200,2,11.910000,NaN,11.910000,11.86,11.92,11.890,2021-01-25,2021-01-25
9,2021-01-25 17:30:00.000,2021-01-25 17:30:03.000,AACQU,11.86,11.8600,11.86,11.8600,100,1,11.860000,11.860000,NaN,11.85,11.90,11.875,2021-01-25,2021-01-25

In [6]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_5min_v2", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-03-20 13:35:00.000,2026-03-20 13:35:03.000,PSR,95.7000,95.7000,95.7000,95.7000,16,1,95.700000,NaN,95.7000,95.34,95.68,95.510,2026-03-20,2026-03-20
1,2026-03-20 13:50:00.000,2026-03-20 13:50:03.000,PSR,95.4000,95.4000,95.4000,95.4000,445,2,95.400000,95.40000,95.4000,95.38,95.61,95.495,2026-03-20,2026-03-20
2,2026-03-20 14:05:00.000,2026-03-20 14:05:03.000,PSR,94.7609,94.7609,94.7609,94.7609,19,1,94.760900,94.76090,NaN,94.48,94.65,94.565,2026-03-20,2026-03-20
3,2026-03-20 14:10:00.000,2026-03-20 14:10:03.000,PSR,94.6499,94.6499,94.6499,94.6499,1,1,94.649900,NaN,94.6499,94.45,94.61,94.530,2026-03-20,2026-03-20
4,2026-03-20 14:15:00.000,2026-03-20 14:15:03.000,PSR,94.5000,94.5289,94.5000,94.5289,60,2,94.502890,NaN,94.5289,94.23,94.40,94.315,2026-03-20,2026-03-20
5,2026-03-20 14:25:00.000,2026-03-20 14:25:03.000,PSR,94.1001,94.1001,94.1000,94.1000,110,2,94.100050,94.10005,NaN,94.11,94.25,94.180,2026-03-20,2026-03-20
6,2026-03-20 14:40:00.000,2026-03-20 14:40:03.000,PSR,94.4200,94.4200,94.4200,94.4200,102,1,94.420000,94.42000,NaN,94.31,94.46,94.385,2026-03-20,2026-03-20
7,2026-03-20 14:50:00.000,2026-03-20 14:50:03.000,PSR,94.1700,94.1700,94.1700,94.1700,1,1,94.170000,NaN,94.1700,94.06,94.20,94.130,2026-03-20,2026-03-20
8,2026-03-20 15:00:00.000,2026-03-20 15:00:03.000,PSR,94.0650,94.1450,94.0650,94.1450,11,2,94.072273,NaN,NaN,94.07,94.21,94.140,2026-03-20,2026-03-20
9,2026-03-20 15:05:00.000,2026-03-20 15:05:03.000,PSR,94.1570,94.1570,94.1570,94.1570,2,1,94.157000,94.15700,NaN,94.08,94.21,94.145,2026-03-20,2026-03-20

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_5min_v2", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_5min_v2...
Found 1 files to download.
Native replication completed for xtech_us_eqt_sip_bardata_flow_5min_v2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_5min_v2", target_location="./data")