In [2]:
import os
from IPython.display import display

In [2]:
%pip install unifier --upgrade

Requirement already satisfied: unifier in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (0.1.20)
Requirement already satisfied: requests in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (3.0.1)
Requirement already satisfied: boto3 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (1.42.75)
Requirement already satisfied: botocore<1.43.0,>=1.42.75 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.42.75)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from unifier import unifier

In [ ]:


unifier.user = 'unifier email'
unifier.token ='unifier api token'
os.environ['UNIFIER_USER'] = unifier.user
os.environ['UNIFIER_TOKEN'] = unifier.token

Your 'unifier username' is your account email address, and your 'unifier api token' is your account api token found in the access my data page.

Dataset: xtech_us_eqt_sip_bardata_flow_1min,
 xtech_us_eqt_sip_bardata_flow_1min_extra, 
 xtech_us_eqt_sip_bardata_flow_5min, 
 xtech_us_eqt_sip_bardata_flow_15min,
 xtech_us_eqt_sip_bardata_flow_30min,
 xtech_us_eqt_sip_bardata_flow_60min, 
 xtech_us_eqt_sip_bardata_flow_daily_regular, 
 xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction

In [ ]:
# Replicate a large dataset to a local folder
# Note: rclone must be installed on your system
unifier.replicate(
    name="xtech_us_eqt_sip_bardata_flow_1min_extra",
    target_location="./your_local_path",
    back_to="",    # Optional: fetch history back to this date
    up_to="",    # Optional: fetch history up to this date
    bandwidth_limit=20       # Optional: limit download speed to 20MB/s
)

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_1min_extra...
No files found to replicate for xtech_us_eqt_sip_bardata_flow_1min_extra

In [8]:
df = unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_1min_extra", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date
0,2021-01-12,2021-01-12 03:01:00.000,2021-01-12 03:01:03.000,ATEST.A,14.4852,14.7873,11.0474,14.7873,555,5,13.8071,None,None,None,None,None,2021-01-12
1,2021-01-12,2021-01-12 03:01:00.000,2021-01-12 03:01:03.000,CTEST.A,10.6507,13.1160,10.0892,12.7393,777,7,11.8285,None,None,None,None,None,2021-01-12
2,2021-01-12,2021-01-12 03:01:00.000,2021-01-12 03:01:03.000,MTEST.A,12.8364,14.6458,11.5808,14.6458,666,6,12.6238,None,None,None,None,None,2021-01-12
3,2021-01-12,2021-01-12 03:01:00.000,2021-01-12 03:01:03.000,PTEST.A,11.0917,12.6929,10.7166,12.6929,444,4,11.4927,None,None,None,None,None,2021-01-12
4,2021-01-12,2021-01-12 03:02:00.000,2021-01-12 03:02:03.000,ATEST.A,14.7668,14.7668,11.5217,12.4270,666,6,12.9264,None,None,None,None,None,2021-01-12
5,2021-01-12,2021-01-12 03:02:00.000,2021-01-12 03:02:03.000,CTEST.A,10.2841,11.8397,9.9888,11.3026,666,6,10.8496,None,None,None,None,None,2021-01-12
6,2021-01-12,2021-01-12 03:02:00.000,2021-01-12 03:02:03.000,MTEST.A,12.1877,13.7881,10.0122,13.7881,555,5,11.7174,None,None,None,None,None,2021-01-12
7,2021-01-12,2021-01-12 03:02:00.000,2021-01-12 03:02:03.000,PTEST.A,12.6328,13.2835,11.3353,13.0126,555,5,12.5862,None,None,None,None,None,2021-01-12
8,2021-01-12,2021-01-12 03:03:00.000,2021-01-12 03:03:03.000,ATEST.A,13.5155,14.1013,12.7913,12.7913,444,4,13.3517,None,None,None,None,None,2021-01-12
9,2021-01-12,2021-01-12 03:03:00.000,2021-01-12 03:03:03.000,CTEST.A,14.5420,14.5420,10.1286,13.0621,555,5,12.3023,None,None,None,None,None,2021-01-12
10,2021-01-12,2021-01-12 03:03:00.000,2021-01-12 03:03:03.000,MTEST.A,13.4545,14.7286,13.1484,14.1456,555,5,13.8334,None,None,None,None,None,2021-01-12
11,2021-01-12,2021-01-12 03:03:00.000,2021-01-12 03:03:03.000,PTEST.A,12.2492,14.9837,10.1247,14.4078,777,7,12.7297,None,None,None,None,None,2021-01-12
12,2021-01-12,2021-01-12 03:04:00.000,2021-01-12 03:04:03.000,ATEST.A,13.7620,14.8623,11.2399,11.3436,555,5,12.7131,None,None,None,None,None,2021-01-12
13,2021-01-12,2021-01-12 03:04:00.000,2021-01-12 03:04:03.000,CTEST.A,12.5283,14.9827,10.4323,14.9827,666,6,12.8565,None,None,None,None,None,2021-01-12
14,2021-01-12,2021-01-12 03:04:00.000,2021-01-12 03:04:03.000,MTEST.A,12.9582,14.8647,10.2953,10.2953,555,5,11.9186,None,None,None,None,None,2021-01-12
15,2021-01-12,2021-01-12 03:04:00.000,2021-01-12 03:04:03.000,PTEST.A,11.0550,13.9209,10.3033,12.6915,555,5,12.2374,None,None,None,None,None,2021-01-12
16,2021-01-12,2021-01-12 03:05:00.000,2021-01-12 03:05:03.000,ATEST.A,10.8149,14.0968,10.4265,13.6675,555,5,12.0930,None,None,None,None,None,2021-01-12
17,2021-01-12,2021-01-12 03:05:00.000,2021-01-12 03:05:03.000,CTEST.A,10.3398,13.2613,10.3398,13.0296,666,6,12.0794,None,None,None,None,None,2021-01-12
18,2021-01-12,2021-01-12 03:05:00.000,2021-01-12 03:05:03.000,MTEST.A,10.4874,12.6658,10.4874,12.6658,777,7,11.5313,None,None,None,None,None,2021-01-12
19,2021-01-12,2021-01-12 03:05:00.000,2021-01-12 03:05:03.000,PTEST.A,10.4898,12.1306,10.4898,12.1306,666,6,11.2974,None,None,None,None,None,2021-01-12

In [11]:
df = unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_1min", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date
0,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USB,50.2100,50.2300,50.2100,50.2231,4899.0,51,50.2188,50.2182,50.2224,50.22,50.23,50.225,2021-01-07
1,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USBpA,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,935.50,950.00,942.750,2021-01-07
2,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USBpH,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,24.41,24.43,24.420,2021-01-07
3,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USBpM,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,26.46,26.48,26.470,2021-01-07
4,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USBpO,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,25.00,25.01,25.005,2021-01-07
5,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USBpP,27.4100,27.4100,27.4100,27.4100,20.0,1,27.4100,27.4100,NaN,27.40,27.59,27.495,2021-01-07
6,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USBpQ,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,24.47,24.50,24.485,2021-01-07
7,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USCI,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,33.42,33.50,33.460,2021-01-07
8,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USCR,50.5500,50.6600,50.5500,50.6500,2736.0,14,50.5999,NaN,50.6478,50.47,50.71,50.590,2021-01-07
9,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USD,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,112.08,112.18,112.130,2021-01-07
10,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USDP,3.6100,3.6100,3.6090,3.6090,401.0,4,3.6095,NaN,3.6095,3.61,3.62,3.615,2021-01-07
11,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USDU,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,25.07,25.08,25.075,2021-01-07
12,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USEG,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,3.85,3.89,3.870,2021-01-07
13,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USEP,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,27.11,27.25,27.180,2021-01-07
14,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USEQ,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,31.74,31.84,31.790,2021-01-07
15,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USFD,33.3800,33.4100,33.3700,33.3900,3607.0,64,33.3938,33.3836,33.4047,33.38,33.43,33.405,2021-01-07
16,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USFR,25.1001,25.1038,25.1000,25.1000,1350.0,4,25.1010,25.1010,NaN,25.10,25.11,25.105,2021-01-07
17,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USHG,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,30.81,31.01,30.910,2021-01-07
18,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USHY,41.2656,41.2750,41.2656,41.2700,204.0,3,41.2724,41.2700,41.2746,41.27,41.28,41.275,2021-01-07
19,2021-01-07,2021-01-07 14:44:00.000,2021-01-07 14:44:03.000,USI,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,24.84,24.87,24.855,2021-01-07

In [12]:
df = unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_5min", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date
0,2021-01-19,2021-01-19 12:35:00.000,2021-01-19 12:35:03.000,INDS,36.0750,36.0750,36.0750,36.0750,81,1,36.0750,NaN,NaN,36.00,36.07,36.035,2021-01-19
1,2021-01-19,2021-01-19 12:40:00.000,2021-01-19 12:40:03.000,INDS,36.0400,36.0400,36.0400,36.0400,2,1,36.0400,NaN,NaN,36.02,36.09,36.055,2021-01-19
2,2021-01-19,2021-01-19 12:50:00.000,2021-01-19 12:50:03.000,INDS,36.1539,36.1539,36.1400,36.1400,550,2,36.1526,NaN,36.1526,36.07,36.14,36.105,2021-01-19
3,2021-01-19,2021-01-19 12:55:00.000,2021-01-19 12:55:03.000,INDS,36.1050,36.1050,36.1050,36.1050,250,2,36.1050,36.1050,NaN,36.07,36.14,36.105,2021-01-19
4,2021-01-19,2021-01-19 13:00:00.000,2021-01-19 13:00:03.000,INDS,36.0984,36.0984,36.0984,36.0984,50,1,36.0984,NaN,36.0984,36.06,36.12,36.090,2021-01-19
5,2021-01-19,2021-01-19 13:05:00.000,2021-01-19 13:05:03.000,INDS,36.1199,36.1199,36.1199,36.1199,122,1,36.1199,NaN,36.1199,35.99,36.06,36.025,2021-01-19
6,2021-01-19,2021-01-19 13:10:00.000,2021-01-19 13:10:03.000,INDS,36.0550,36.0550,36.0550,36.0550,150,1,36.0550,36.0550,NaN,36.03,36.10,36.065,2021-01-19
7,2021-01-19,2021-01-19 13:15:00.000,2021-01-19 13:15:03.000,INDS,36.0777,36.0850,36.0777,36.0850,140,3,36.0778,36.0777,36.0850,36.06,36.12,36.090,2021-01-19
8,2021-01-19,2021-01-19 13:20:00.000,2021-01-19 13:20:03.000,INDS,36.0500,36.0600,36.0500,36.0600,125,3,36.0584,36.0500,NaN,36.02,36.08,36.050,2021-01-19
9,2021-01-19,2021-01-19 13:25:00.000,2021-01-19 13:25:03.000,INDS,36.0400,36.0700,36.0400,36.0700,12,3,36.0675,NaN,36.0700,36.00,36.06,36.030,2021-01-19
10,2021-01-19,2021-01-19 13:50:00.000,2021-01-19 13:50:03.000,INDS,36.0100,36.0199,36.0000,36.0199,102,3,36.0196,NaN,36.0199,35.96,36.02,35.990,2021-01-19
11,2021-01-19,2021-01-19 13:55:00.000,2021-01-19 13:55:03.000,INDS,36.0000,36.0000,35.9875,35.9875,270,2,35.9907,35.9875,NaN,35.97,36.03,36.000,2021-01-19
12,2021-01-19,2021-01-19 14:00:00.000,2021-01-19 14:00:03.000,INDS,35.9900,35.9900,35.9900,35.9900,6,2,35.9900,NaN,NaN,35.96,36.02,35.990,2021-01-19
13,2021-01-19,2021-01-19 14:05:00.000,2021-01-19 14:05:03.000,INDS,35.9800,36.0000,35.9700,36.0000,40,4,35.9808,35.9797,36.0000,35.94,36.00,35.970,2021-01-19
14,2021-01-19,2021-01-19 14:10:00.000,2021-01-19 14:10:03.000,INDS,35.9700,35.9800,35.9200,35.9200,538,5,35.9609,35.9200,35.9750,35.94,35.99,35.965,2021-01-19
15,2021-01-19,2021-01-19 14:15:00.000,2021-01-19 14:15:03.000,INDS,35.9800,36.0000,35.9800,36.0000,122,3,35.9806,NaN,35.9806,35.93,35.99,35.960,2021-01-19
16,2021-01-19,2021-01-19 14:20:00.000,2021-01-19 14:20:03.000,INDS,35.9600,35.9600,35.9600,35.9600,53,1,35.9600,NaN,NaN,35.93,36.00,35.965,2021-01-19
17,2021-01-19,2021-01-19 14:25:00.000,2021-01-19 14:25:03.000,INDS,35.9715,35.9715,35.9700,35.9700,714,2,35.9714,NaN,35.9715,35.93,35.99,35.960,2021-01-19
18,2021-01-19,2021-01-19 14:30:00.000,2021-01-19 14:30:03.000,INDS,35.9851,35.9900,35.9650,35.9650,129,3,35.9868,NaN,35.9891,35.95,36.00,35.975,2021-01-19
19,2021-01-19,2021-01-19 14:35:00.000,2021-01-19 14:35:03.000,INDS,35.9900,35.9900,35.9900,35.9900,6,1,35.9900,NaN,NaN,35.94,36.00,35.970,2021-01-19

In [13]:
df = unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_15min", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date
0,2021-01-29,2021-01-29 07:15:00.000,2021-01-29 07:15:03.000,A,120.990,120.990,120.99,120.990,2,1,120.990,120.990,NaN,NaN,NaN,NaN,2021-01-29
1,2021-01-29,2021-01-29 08:15:00.000,2021-01-29 08:15:03.000,A,121.560,121.560,121.56,121.560,1,1,121.560,121.560,NaN,120.20,123.23,121.715,2021-01-29
2,2021-01-29,2021-01-29 08:30:00.000,2021-01-29 08:30:03.000,A,120.510,120.600,120.26,120.260,30,6,120.364,120.364,NaN,120.20,121.56,120.880,2021-01-29
3,2021-01-29,2021-01-29 09:00:00.000,2021-01-29 09:00:03.000,A,120.260,121.560,120.21,121.560,456,5,120.259,120.259,NaN,NaN,NaN,NaN,2021-01-29
4,2021-01-29,2021-01-29 09:15:00.000,2021-01-29 09:15:03.000,A,121.560,121.560,120.20,121.560,83,3,120.905,120.905,NaN,NaN,NaN,NaN,2021-01-29
5,2021-01-29,2021-01-29 09:30:00.000,2021-01-29 09:30:03.000,A,121.940,121.940,121.94,121.940,2,1,121.940,NaN,121.940,120.66,122.21,121.435,2021-01-29
6,2021-01-29,2021-01-29 09:45:00.000,2021-01-29 09:45:03.000,A,121.210,121.550,120.12,120.890,142716,842,121.022,120.931,121.093,120.73,120.97,120.850,2021-01-29
7,2021-01-29,2021-01-29 10:00:00.000,2021-01-29 10:00:03.000,A,120.810,121.761,120.61,121.130,49552,845,121.155,121.160,121.144,121.18,121.45,121.315,2021-01-29
8,2021-01-29,2021-01-29 10:15:00.000,2021-01-29 10:15:03.000,A,121.200,121.685,121.01,121.269,40115,617,121.354,121.287,121.421,121.24,121.43,121.335,2021-01-29
9,2021-01-29,2021-01-29 10:30:00.000,2021-01-29 10:30:03.000,A,121.330,121.640,121.12,121.360,45948,752,121.388,121.374,121.408,121.31,121.35,121.330,2021-01-29
10,2021-01-29,2021-01-29 10:45:00.000,2021-01-29 10:45:03.000,A,121.350,121.475,120.88,120.917,42840,697,121.117,121.105,121.124,120.88,120.95,120.915,2021-01-29
11,2021-01-29,2021-01-29 11:00:00.000,2021-01-29 11:00:03.000,A,120.915,121.340,120.59,121.185,41931,642,120.911,120.862,121.013,121.12,121.24,121.180,2021-01-29
12,2021-01-29,2021-01-29 11:15:00.000,2021-01-29 11:15:03.000,A,121.170,121.570,120.51,120.705,41619,742,121.000,120.977,121.041,120.62,120.71,120.665,2021-01-29
13,2021-01-29,2021-01-29 11:30:00.000,2021-01-29 11:30:03.000,A,120.689,120.925,120.49,120.612,28135,598,120.652,120.643,120.662,120.56,120.67,120.615,2021-01-29
14,2021-01-29,2021-01-29 11:45:00.000,2021-01-29 11:45:03.000,A,120.640,120.740,120.17,120.490,39684,634,120.425,120.427,120.424,120.48,120.53,120.505,2021-01-29
15,2021-01-29,2021-01-29 12:00:00.000,2021-01-29 12:00:03.000,A,120.530,120.650,120.23,120.410,30695,527,120.420,120.407,120.443,120.34,120.45,120.395,2021-01-29
16,2021-01-29,2021-01-29 12:15:00.000,2021-01-29 12:15:03.000,A,120.400,120.450,120.03,120.140,37300,684,120.211,120.211,120.207,120.09,120.15,120.120,2021-01-29
17,2021-01-29,2021-01-29 12:30:00.000,2021-01-29 12:30:03.000,A,120.120,120.150,119.50,119.832,53152,819,119.813,119.809,119.817,119.78,119.86,119.820,2021-01-29
18,2021-01-29,2021-01-29 12:45:00.000,2021-01-29 12:45:03.000,A,119.797,119.900,119.51,119.720,35265,653,119.703,119.695,119.710,119.61,119.71,119.660,2021-01-29
19,2021-01-29,2021-01-29 13:00:00.000,2021-01-29 13:00:03.000,A,119.710,119.910,119.23,119.490,33337,671,119.561,119.546,119.564,119.47,119.56,119.515,2021-01-29

In [14]:
df = unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_30min", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date
0,2021-01-20,2021-01-20 07:30:00.000,2021-01-20 07:30:03.000,A,127.910,127.91,127.350,127.350,2,2,127.630,NaN,127.630,NaN,NaN,NaN,2021-01-20
1,2021-01-20,2021-01-20 08:30:00.000,2021-01-20 08:30:03.000,A,127.350,128.00,127.350,128.000,2069,6,127.351,NaN,127.351,124.00,130.00,127.000,2021-01-20
2,2021-01-20,2021-01-20 09:30:00.000,2021-01-20 09:30:03.000,A,127.980,128.00,127.980,128.000,79,2,127.998,127.998,NaN,127.18,128.43,127.805,2021-01-20
3,2021-01-20,2021-01-20 10:00:00.000,2021-01-20 10:00:03.000,A,128.140,128.54,127.240,128.530,127145,1472,127.795,127.781,127.798,128.48,128.58,128.530,2021-01-20
4,2021-01-20,2021-01-20 10:30:00.000,2021-01-20 10:30:03.000,A,128.547,128.92,128.175,128.175,67533,1354,128.551,128.560,128.543,128.08,128.15,128.115,2021-01-20
5,2021-01-20,2021-01-20 11:00:00.000,2021-01-20 11:00:03.000,A,128.120,128.46,128.030,128.270,128835,1201,128.165,128.197,128.146,128.26,128.28,128.270,2021-01-20
6,2021-01-20,2021-01-20 11:30:00.000,2021-01-20 11:30:03.000,A,128.270,128.31,127.920,127.995,67008,1214,128.107,128.105,128.109,127.98,128.03,128.005,2021-01-20
7,2021-01-20,2021-01-20 12:00:00.000,2021-01-20 12:00:03.000,A,128.005,128.43,127.890,128.269,100510,1238,128.147,128.162,128.126,128.02,128.09,128.055,2021-01-20
8,2021-01-20,2021-01-20 12:30:00.000,2021-01-20 12:30:03.000,A,128.040,128.60,127.910,128.100,87280,1269,128.366,128.309,128.390,128.08,128.14,128.110,2021-01-20
9,2021-01-20,2021-01-20 13:00:00.000,2021-01-20 13:00:03.000,A,128.110,128.28,128.070,128.090,32333,686,128.171,128.169,128.173,128.05,128.11,128.080,2021-01-20
10,2021-01-20,2021-01-20 13:30:00.000,2021-01-20 13:30:03.000,A,128.115,128.24,127.860,127.940,54867,888,128.118,128.105,128.125,127.92,127.96,127.940,2021-01-20
11,2021-01-20,2021-01-20 14:00:00.000,2021-01-20 14:00:03.000,A,128.053,128.33,127.840,128.090,71192,749,128.183,128.085,128.073,128.06,128.09,128.075,2021-01-20
12,2021-01-20,2021-01-20 14:30:00.000,2021-01-20 14:30:03.000,A,128.010,128.10,127.680,128.030,120866,1019,127.954,127.959,127.941,128.01,128.04,128.025,2021-01-20
13,2021-01-20,2021-01-20 15:00:00.000,2021-01-20 15:00:03.000,A,128.025,128.23,127.990,128.000,51111,977,128.113,128.118,128.099,127.96,128.01,127.985,2021-01-20
14,2021-01-20,2021-01-20 15:30:00.000,2021-01-20 15:30:03.000,A,127.990,128.16,127.830,128.060,49852,1132,128.031,128.042,128.017,128.04,128.08,128.060,2021-01-20
15,2021-01-20,2021-01-20 16:00:00.000,2021-01-20 16:00:03.000,A,128.060,128.44,128.010,128.270,178024,2778,128.312,128.309,128.314,128.27,128.29,128.280,2021-01-20
16,2021-01-20,2021-01-20 16:30:00.000,2021-01-20 16:30:03.000,A,128.290,128.29,128.100,128.110,1480760,461,128.113,128.112,128.255,NaN,NaN,NaN,2021-01-20
17,2021-01-20,2021-01-20 17:00:00.000,2021-01-20 17:00:03.000,A,128.110,128.11,128.110,128.110,174381,2,128.110,128.110,NaN,127.10,130.00,128.550,2021-01-20
18,2021-01-20,2021-01-20 17:30:00.000,2021-01-20 17:30:03.000,A,128.120,128.12,128.120,128.120,1,1,128.120,128.120,NaN,NaN,NaN,NaN,2021-01-20
19,2021-01-20,2021-01-20 18:30:00.000,2021-01-20 18:30:03.000,A,128.120,128.12,128.120,128.120,5,1,128.120,128.120,NaN,NaN,NaN,NaN,2021-01-20

In [15]:
df = unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_60min", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date
0,2021-01-06,2021-01-06 05:00:00.000,2021-01-06 05:00:03.000,A,120.300,120.30,120.300,120.300,20,2,120.3000,NaN,120.3000,116.75,121.48,119.115,2021-01-06
1,2021-01-06,2021-01-06 08:00:00.000,2021-01-06 08:00:03.000,A,119.000,119.18,119.000,119.180,118,4,119.0270,119.1780,119.0000,117.00,124.00,120.500,2021-01-06
2,2021-01-06,2021-01-06 09:00:00.000,2021-01-06 09:00:03.000,A,119.610,119.70,119.260,119.260,1303,22,119.2620,119.2620,NaN,NaN,NaN,NaN,2021-01-06
3,2021-01-06,2021-01-06 10:00:00.000,2021-01-06 10:00:03.000,A,119.260,121.52,118.100,121.332,408807,2590,119.7020,119.3650,119.8960,121.31,121.37,121.340,2021-01-06
4,2021-01-06,2021-01-06 11:00:00.000,2021-01-06 11:00:03.000,A,121.330,122.35,120.860,122.280,262462,4210,121.5100,121.5120,121.5950,122.26,122.32,122.290,2021-01-06
5,2021-01-06,2021-01-06 12:00:00.000,2021-01-06 12:00:03.000,A,122.310,122.42,121.450,121.840,177547,2914,121.7920,121.7830,121.8230,121.81,121.88,121.845,2021-01-06
6,2021-01-06,2021-01-06 13:00:00.000,2021-01-06 13:00:03.000,A,121.840,122.27,121.540,122.068,157311,2506,121.9550,121.9480,121.9580,122.02,122.09,122.055,2021-01-06
7,2021-01-06,2021-01-06 14:00:00.000,2021-01-06 14:00:03.000,A,122.090,123.40,122.051,123.280,284737,3628,122.8560,122.9160,122.7750,123.27,123.31,123.290,2021-01-06
8,2021-01-06,2021-01-06 15:00:00.000,2021-01-06 15:00:03.000,A,123.305,123.90,122.860,123.430,287942,4482,123.4220,123.4760,123.4270,123.41,123.50,123.455,2021-01-06
9,2021-01-06,2021-01-06 16:00:00.000,2021-01-06 16:00:03.000,A,123.410,123.88,122.850,122.960,399441,7464,123.2550,123.2530,123.2510,122.94,123.00,122.970,2021-01-06
10,2021-01-06,2021-01-06 17:00:00.000,2021-01-06 17:00:03.000,A,122.950,123.00,122.050,122.890,1084080,755,122.8920,122.8910,122.9370,122.05,123.99,123.020,2021-01-06
11,2021-01-06,2021-01-06 18:00:00.000,2021-01-06 18:00:03.000,A,122.890,122.89,122.050,122.050,29315,3,122.8900,122.8900,NaN,122.05,124.00,123.025,2021-01-06
12,2021-01-06,2021-01-06 19:00:00.000,2021-01-06 19:00:03.000,A,122.850,122.89,122.850,122.890,319650,2,122.8900,122.8900,122.8500,NaN,NaN,NaN,2021-01-06
13,2021-01-06,2021-01-06 20:00:00.000,2021-01-06 20:00:03.000,A,122.890,122.89,122.800,122.800,319560,2,122.8900,122.8900,NaN,NaN,NaN,NaN,2021-01-06
14,2021-01-06,2021-01-06 05:00:00.000,2021-01-06 05:00:03.000,AA,23.650,23.70,23.650,23.700,875,4,23.6957,NaN,23.6957,23.00,24.65,23.825,2021-01-06
15,2021-01-06,2021-01-06 07:00:00.000,2021-01-06 07:00:03.000,AA,23.220,24.60,23.220,24.500,7087,16,24.5919,24.5909,24.5922,24.15,24.65,24.400,2021-01-06
16,2021-01-06,2021-01-06 08:00:00.000,2021-01-06 08:00:03.000,AA,24.510,24.51,24.150,24.400,5791,74,24.3786,24.3260,24.3865,24.32,24.40,24.360,2021-01-06
17,2021-01-06,2021-01-06 09:00:00.000,2021-01-06 09:00:03.000,AA,24.440,24.47,24.150,24.330,16025,83,24.3671,24.3088,24.3923,24.32,24.38,24.350,2021-01-06
18,2021-01-06,2021-01-06 10:00:00.000,2021-01-06 10:00:03.000,AA,24.370,25.20,24.300,24.870,1064960,5149,24.7402,24.7522,24.7272,24.85,24.88,24.865,2021-01-06
19,2021-01-06,2021-01-06 11:00:00.000,2021-01-06 11:00:03.000,AA,24.865,25.29,24.820,25.135,947003,6197,25.0705,25.0629,25.0801,25.11,25.16,25.135,2021-01-06

In [16]:
df = unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_daily_regular", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date
0,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAAG,26.000,27.350,26.0000,27.2700,457,25,27.08770,26.147500,27.243500,27.2700,27.3100,27.29000,2021-01-08
1,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAC,8.230,8.390,8.1900,8.3600,241724,1930,8.32062,8.317960,8.323040,8.3500,8.3600,8.35500,2021-01-08
2,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TACA.U,10.460,10.550,10.4001,10.5000,34108,29,10.49570,10.463800,10.498800,10.5000,10.5500,10.52500,2021-01-08
3,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TACE,25.260,25.260,24.7759,24.7759,1392,19,24.79900,24.790300,24.935700,24.8700,24.9300,24.90000,2021-01-08
4,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TACO,9.470,9.580,9.1900,9.2300,183998,2239,9.28037,9.274420,9.287480,9.2400,9.2500,9.24500,2021-01-08
5,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TACT,8.690,9.090,8.5400,9.0200,59473,436,8.88964,8.846700,8.914370,8.9600,9.0200,8.99000,2021-01-08
6,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TADS,26.670,26.670,26.4450,26.4450,852,19,26.50370,26.480300,26.598900,26.5700,26.6200,26.59500,2021-01-08
7,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAEQ,26.361,26.425,26.2850,26.3200,678,10,26.32980,26.366700,26.303700,26.3900,26.4500,26.42000,2021-01-08
8,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAGS,22.820,22.820,21.7400,21.9292,3710,42,21.86090,21.857200,21.870700,21.7700,21.9800,21.87500,2021-01-08
9,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAIL,20.200,20.300,20.1300,20.1400,800661,695,20.15920,20.159500,20.176500,20.1400,20.1900,20.16500,2021-01-08
10,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAIT,3.330,3.330,3.2000,3.2600,13616,98,3.28357,3.273570,3.312300,3.2100,3.2700,3.24000,2021-01-08
11,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAK,18.000,18.400,17.9000,18.2500,4457960,23267,18.24300,18.240000,18.246300,18.2500,18.2600,18.25500,2021-01-08
12,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAL,65.720,67.950,65.3000,67.8300,4286320,36852,66.82610,66.920300,66.688000,67.8200,67.8300,67.82500,2021-01-08
13,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TALO,9.870,9.960,9.2000,9.3400,607850,5021,9.46112,9.373570,9.545120,9.3300,9.3400,9.33500,2021-01-08
14,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TALO.WS,0.070,0.070,0.0540,0.0598,65396,54,0.05729,0.055715,0.063172,0.0573,0.0598,0.05855,2021-01-08
15,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TAN,123.380,123.690,116.7400,118.6700,3910060,60137,119.35000,119.010000,119.702000,118.6700,118.7600,118.71500,2021-01-08
16,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TANH,1.590,1.660,1.5000,1.5350,4385420,9962,1.57131,1.557290,1.587740,1.5300,1.5400,1.53500,2021-01-08
17,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TANNI,25.570,26.000,25.5700,25.8200,3848,37,25.77500,25.726800,25.829100,25.7500,25.8900,25.82000,2021-01-08
18,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TANNL,25.460,25.550,25.4600,25.4691,5219,51,25.48530,25.476400,25.499400,25.4600,25.5000,25.48000,2021-01-08
19,2021-01-08,2021-01-08 16:00:00.000,2021-01-08 16:00:03.000,TANNZ,25.300,25.450,24.9000,25.1910,21213,105,25.16430,25.121800,25.239400,25.1600,25.4500,25.30500,2021-01-08

In [17]:
df = unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction", back_to="2021-01-03" , up_to="2021-02-03", limit=20)
display(df)

,asof_date,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date
0,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SVT,8.56,8.9338,8.550,8.70,6249,46,8.65072,8.61165,8.66729,NaN,NaN,NaN,2021-01-21
1,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SVVC,5.10,5.1495,4.784,5.08,16925,104,5.07748,5.08246,5.05529,5.07,5.35,5.210,2021-01-21
2,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SVXY,41.68,41.8800,41.345,41.80,2263260,17624,41.67950,41.68250,41.67560,41.75,41.81,41.780,2021-01-21
3,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWAN,32.92,32.9400,32.770,32.84,160894,459,32.84760,32.84240,32.85930,NaN,NaN,NaN,2021-01-21
4,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWAV,133.29,134.8700,128.120,131.49,345695,7526,131.34400,131.19500,131.48300,128.00,133.99,130.995,2021-01-21
5,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWBI,18.87,19.1436,17.720,17.88,3306710,25760,18.07840,18.04530,18.13360,17.84,17.91,17.875,2021-01-21
6,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWBK.U,12.24,12.2900,12.010,12.25,591223,1728,12.14130,12.13310,12.15050,11.95,12.35,12.150,2021-01-21
7,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWCH,16.77,16.8600,16.190,16.44,1372520,11451,16.39970,16.40030,16.39700,NaN,NaN,NaN,2021-01-21
8,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWETU,10.37,10.5100,10.370,10.46,161684,475,10.44200,10.43670,10.45030,10.32,10.51,10.415,2021-01-21
9,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWI,15.74,16.0600,15.530,15.78,1417210,8214,15.88760,15.86800,15.89940,15.65,15.89,15.770,2021-01-21
10,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWIR,18.02,20.0000,17.480,19.80,193413,1623,18.32220,18.19370,18.45170,19.00,19.98,19.490,2021-01-21
11,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWK,176.01,178.3300,174.710,177.01,1792450,16949,177.09400,177.06200,177.14700,175.72,178.90,177.310,2021-01-21
12,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWKH,13.34,13.7132,12.800,13.26,4900,85,13.29310,13.25340,13.42110,NaN,NaN,NaN,2021-01-21
13,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWKS,163.10,164.8000,160.600,164.75,1579900,22868,162.65900,162.68100,162.75000,159.01,166.00,162.505,2021-01-21
14,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWM,41.84,42.3900,41.040,41.31,188173,1937,41.41740,41.38390,41.51810,NaN,NaN,NaN,2021-01-21
15,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWN,3.41,3.5200,3.280,3.42,18681300,37900,3.38032,3.38551,3.37635,3.37,3.42,3.395,2021-01-21
16,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWT,109.86,112.7080,109.860,110.78,170404,204,110.55400,110.47700,110.79800,NaN,NaN,NaN,2021-01-21
17,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWTX,78.99,84.2300,76.020,79.89,379024,5186,80.28070,80.30570,80.46600,NaN,NaN,NaN,2021-01-21
18,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWX,58.27,58.3500,57.230,57.55,540407,6217,57.56010,57.54530,57.61440,NaN,NaN,NaN,2021-01-21
19,2021-01-21,2021-01-21 16:15:00.000,2021-01-21 16:15:03.000,SWZ,9.15,9.1600,9.110,9.16,17180,94,9.13849,9.13952,9.13684,NaN,NaN,NaN,2021-01-21