In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_30min_v2", back_to='2025-11-18', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-09-08 14:00:00.000,2026-09-08 14:00:03.000,AAC,10.1500,10.1500,10.0610,10.0610,6,3,10.090667,10.061000,10.1500,10.06,10.15,10.105,2026-09-08,2026-09-08
1,2026-09-08 08:30:00.000,2026-09-08 08:30:03.000,AAC,10.0600,10.0600,10.0600,10.0600,2,1,10.060000,10.060000,NaN,NaN,NaN,NaN,2026-09-08,2026-09-08
2,2026-09-08 20:30:00.000,2026-09-08 20:30:03.000,AAC,10.0727,10.0727,10.0727,10.0727,1,1,10.072700,NaN,10.0727,10.06,10.16,10.110,2026-09-08,2026-09-08
3,2026-09-08 20:00:00.000,2026-09-08 20:00:03.000,AAC,10.0600,10.0600,10.0600,10.0600,21,1,10.060000,10.060000,NaN,10.06,10.15,10.105,2026-09-08,2026-09-08
4,2026-09-08 15:00:00.000,2026-09-08 15:00:03.000,AAC,10.1500,10.1500,10.1500,10.1500,1,1,10.150000,NaN,10.1500,10.06,10.15,10.105,2026-09-08,2026-09-08
5,2026-09-08 14:30:00.000,2026-09-08 14:30:03.000,AAC,10.1500,10.1500,10.1500,10.1500,3,3,10.150000,NaN,10.1500,10.06,10.15,10.105,2026-09-08,2026-09-08
6,2026-09-08 17:00:00.000,2026-09-08 17:00:03.000,AACIW,0.2301,0.2360,0.2301,0.2360,50,2,0.230218,0.230218,NaN,NaN,NaN,NaN,2026-09-08,2026-09-08
7,2026-09-08 15:30:00.000,2026-09-08 15:30:03.000,AACIW,0.2600,0.2600,0.2400,0.2400,400,2,0.250000,NaN,0.2600,0.23,0.26,0.245,2026-09-08,2026-09-08
8,2026-09-08 14:00:00.000,2026-09-08 14:00:03.000,AACIW,0.2200,0.2200,0.2200,0.2200,5,1,0.220000,NaN,0.2200,0.22,0.26,0.240,2026-09-08,2026-09-08
9,2026-09-08 16:00:00.000,2026-09-08 16:00:03.000,AACIW,0.2600,0.2600,0.2600,0.2600,11,1,0.260000,NaN,0.2600,0.23,0.26,0.245,2026-09-08,2026-09-08

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_sip_bardata_flow_30min_v2', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2021-01-26 14:30:00.000,2021-01-26 14:30:03.000,AAIC,3.8200,3.8200,3.8100,3.8100,3003,3,3.819993,NaN,3.819993,3.74,3.82,3.780,2021-01-26,2021-01-26
1,2021-01-26 15:00:00.000,2021-01-26 15:00:03.000,AAIC,3.8200,3.8200,3.7500,3.8048,12264,136,3.803081,3.794754,3.815696,3.80,3.82,3.810,2021-01-26,2021-01-26
2,2021-01-26 15:30:00.000,2021-01-26 15:30:03.000,AAIC,3.8100,3.8200,3.8000,3.8100,12805,55,3.814065,3.809880,3.819888,3.81,3.82,3.815,2021-01-26,2021-01-26
3,2021-01-26 16:00:00.000,2021-01-26 16:00:03.000,AAIC,3.8116,3.8600,3.8100,3.8500,31544,127,3.840477,3.844735,3.836298,3.84,3.85,3.845,2021-01-26,2021-01-26
4,2021-01-26 16:30:00.000,2021-01-26 16:30:03.000,AAIC,3.8401,3.8450,3.8222,3.8250,7592,69,3.837633,3.836631,3.844286,3.82,3.83,3.825,2021-01-26,2021-01-26
5,2021-01-26 17:00:00.000,2021-01-26 17:00:03.000,AAIC,3.8300,3.8300,3.8105,3.8150,5112,66,3.819569,3.818378,3.824889,3.81,3.82,3.815,2021-01-26,2021-01-26
6,2021-01-26 17:30:00.000,2021-01-26 17:30:03.000,AAIC,3.8150,3.8184,3.8000,3.8100,2566,54,3.808850,3.809867,3.807219,3.80,3.81,3.805,2021-01-26,2021-01-26
7,2021-01-26 18:00:00.000,2021-01-26 18:00:03.000,AAIC,3.8100,3.8161,3.8100,3.8150,3131,64,3.813413,3.813838,3.811315,3.81,3.82,3.815,2021-01-26,2021-01-26
8,2021-01-26 18:30:00.000,2021-01-26 18:30:03.000,AAIC,3.8150,3.8200,3.8150,3.8200,4123,66,3.816613,NaN,3.820000,3.81,3.82,3.815,2021-01-26,2021-01-26
9,2021-01-26 19:00:00.000,2021-01-26 19:00:03.000,AAIC,3.8150,3.8300,3.8150,3.8300,10305,128,3.821941,3.820000,3.822344,3.82,3.83,3.825,2021-01-26,2021-01-26

In [6]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_30min_v2", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-09-04 14:00:00.000,2026-09-04 14:00:03.000,PSR,102.0000,102.9600,102.0000,102.7350,258,9,102.791613,102.567269,102.95703,102.63,102.84,102.735,2026-09-04,2026-09-04
1,2026-09-04 14:30:00.000,2026-09-04 14:30:03.000,PSR,102.5950,102.7700,102.5950,102.7700,3,3,102.706667,102.595000,NaN,102.84,102.99,102.915,2026-09-04,2026-09-04
2,2026-09-04 15:00:00.000,2026-09-04 15:00:03.000,PSR,102.8750,102.8750,102.8750,102.8750,110,2,102.875000,NaN,NaN,102.79,102.91,102.850,2026-09-04,2026-09-04
3,2026-09-04 15:30:00.000,2026-09-04 15:30:03.000,PSR,102.8400,102.9490,102.8400,102.9490,84,2,102.947702,102.840000,102.94900,102.80,102.90,102.850,2026-09-04,2026-09-04
4,2026-09-04 16:00:00.000,2026-09-04 16:00:03.000,PSR,102.8400,102.8400,102.8400,102.8400,2,1,102.840000,102.840000,NaN,102.79,102.88,102.835,2026-09-04,2026-09-04
5,2026-09-04 16:30:00.000,2026-09-04 16:30:03.000,PSR,102.9400,102.9400,102.9400,102.9400,3,1,102.940000,NaN,102.94000,102.88,102.99,102.935,2026-09-04,2026-09-04
6,2026-09-04 18:30:00.000,2026-09-04 18:30:03.000,PSR,102.3150,102.3500,102.3150,102.3500,3,2,102.326667,NaN,NaN,102.28,102.36,102.320,2026-09-04,2026-09-04
7,2026-09-04 19:30:00.000,2026-09-04 19:30:03.000,PSR,102.2800,102.3300,102.2800,102.3300,49,2,102.327959,102.330000,NaN,102.32,102.39,102.355,2026-09-04,2026-09-04
8,2026-09-04 20:30:00.000,2026-09-04 20:30:03.000,PSR,102.1009,102.1009,102.1009,102.1009,4,4,102.100900,102.100900,NaN,NaN,NaN,NaN,2026-09-04,2026-09-04
9,2026-09-08 14:00:00.000,2026-09-08 14:00:03.000,PSR,101.5800,102.3600,101.5800,102.3600,72,5,102.012087,101.990016,NaN,102.41,102.63,102.520,2026-09-08,2026-09-08

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_30min_v2", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_30min_v2...
Found 1 files to download.
Native replication completed for xtech_us_eqt_sip_bardata_flow_30min_v2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_30min_v2", target_location="./data")