In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [8]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_15min_v2", back_to='2025-11-18', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-05-13 14:00:00.000,2026-05-13 14:00:03.000,AACIW,0.2400,0.2400,0.2400,0.2400,105,1,0.240000,0.240000,NaN,NaN,NaN,NaN,2026-05-13,2026-05-13
1,2026-05-13 19:15:00.000,2026-05-13 19:15:03.000,AACIW,0.2601,0.2601,0.2601,0.2601,7,1,0.260100,0.260100,NaN,NaN,NaN,NaN,2026-05-13,2026-05-13
2,2026-05-13 17:00:00.000,2026-05-13 17:00:03.000,AADR,87.4700,87.4700,87.4700,87.4700,30,1,87.470000,NaN,NaN,87.09,87.88,87.485,2026-05-13,2026-05-13
3,2026-05-13 17:15:00.000,2026-05-13 17:15:03.000,AADR,87.4500,87.4500,87.4500,87.4500,1,1,87.450000,87.450000,NaN,87.09,87.88,87.485,2026-05-13,2026-05-13
4,2026-05-13 18:00:00.000,2026-05-13 18:00:03.000,AADR,87.0900,87.0900,87.0900,87.0900,1,1,87.090000,87.090000,NaN,87.09,87.92,87.505,2026-05-13,2026-05-13
5,2026-05-13 19:45:00.000,2026-05-13 19:45:03.000,AADR,87.3420,87.3420,87.3420,87.3420,105,1,87.342000,87.342000,NaN,86.97,87.75,87.360,2026-05-13,2026-05-13
6,2026-05-13 20:15:00.000,2026-05-13 20:15:03.000,AADR,87.0100,87.3600,87.0100,87.3600,4,4,87.185000,87.010000,87.36,43.55,130.63,87.090,2026-05-13,2026-05-13
7,2026-05-13 13:45:00.000,2026-05-13 13:45:03.000,AADR,85.7400,86.1100,85.7400,86.0700,227,9,85.820969,85.820969,NaN,86.06,86.85,86.455,2026-05-13,2026-05-13
8,2026-05-13 14:00:00.000,2026-05-13 14:00:03.000,AADR,86.0600,86.4600,86.0600,86.3900,110,15,86.301909,86.294381,86.46,86.42,87.20,86.810,2026-05-13,2026-05-13
9,2026-05-13 15:15:00.000,2026-05-13 15:15:03.000,AADR,86.9250,86.9950,86.9250,86.9950,861,2,86.925081,86.925000,NaN,86.65,87.34,86.995,2026-05-13,2026-05-13

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_sip_bardata_flow_15min_v2', back_to='2024-01-11', up_to='2024-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2024-01-16 09:15:00.000,2024-01-16 09:15:03.000,AAAU,20.250,20.2500,20.215,20.215,118,5,20.221483,20.220000,20.2500,20.20,20.21,20.205,2024-01-16,2024-01-16
1,2024-01-16 09:30:00.000,2024-01-16 09:30:03.000,AAAU,20.190,20.1900,20.190,20.190,70,1,20.190000,NaN,20.1900,20.20,20.21,20.205,2024-01-16,2024-01-16
2,2024-01-16 09:45:00.000,2024-01-16 09:45:03.000,AAAU,20.200,20.2000,20.200,20.200,104,2,20.200000,20.200000,NaN,20.19,20.20,20.195,2024-01-16,2024-01-16
3,2024-01-16 11:30:00.000,2024-01-16 11:30:03.000,AAAU,20.200,20.2000,20.200,20.200,1,1,20.200000,NaN,20.2000,20.19,20.20,20.195,2024-01-16,2024-01-16
4,2024-01-16 11:45:00.000,2024-01-16 11:45:03.000,AAAU,20.200,20.2000,20.190,20.190,323,2,20.191300,20.190000,20.2000,20.19,20.20,20.195,2024-01-16,2024-01-16
5,2024-01-16 12:00:00.000,2024-01-16 12:00:03.000,AAAU,20.190,20.2100,20.190,20.210,140,2,20.195714,20.190000,20.2100,20.19,20.20,20.195,2024-01-16,2024-01-16
6,2024-01-16 12:15:00.000,2024-01-16 12:15:03.000,AAAU,20.205,20.2050,20.190,20.190,1100,2,20.203636,20.190000,NaN,20.16,20.17,20.165,2024-01-16,2024-01-16
7,2024-01-16 12:45:00.000,2024-01-16 12:45:03.000,AAAU,20.200,20.2000,20.200,20.200,25,1,20.200000,NaN,20.2000,20.18,20.19,20.185,2024-01-16,2024-01-16
8,2024-01-16 13:15:00.000,2024-01-16 13:15:03.000,AAAU,20.180,20.1999,20.160,20.160,951,6,20.177886,20.173764,20.1999,20.15,20.16,20.155,2024-01-16,2024-01-16
9,2024-01-16 13:30:00.000,2024-01-16 13:30:03.000,AAAU,20.120,20.1300,20.120,20.120,1800,4,20.121111,20.120588,20.1300,20.12,20.13,20.125,2024-01-16,2024-01-16

In [9]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_15min_v2", key='PSR', back_to='2020-10-29',up_to='2024-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2021-04-23 12:15:00.000,2021-04-23 12:15:03.000,PSR,97.3300,97.3300,97.3300,97.3300,2,1,97.330000,NaN,97.330000,94.63,103.67,99.150,2021-04-23,2021-04-23
1,2021-04-23 13:45:00.000,2021-04-23 13:45:03.000,PSR,99.2700,99.2700,98.8300,99.0201,251,5,99.255419,99.255800,NaN,99.01,99.21,99.110,2021-04-23,2021-04-23
2,2021-04-23 14:00:00.000,2021-04-23 14:00:03.000,PSR,99.1076,99.4700,99.1076,99.4550,60,7,99.154225,99.134427,99.335000,99.39,99.51,99.450,2021-04-23,2021-04-23
3,2021-04-23 14:15:00.000,2021-04-23 14:15:03.000,PSR,99.3360,99.3360,99.3360,99.3360,24,1,99.336000,NaN,99.336000,99.23,99.32,99.275,2021-04-23,2021-04-23
4,2021-04-23 14:30:00.000,2021-04-23 14:30:03.000,PSR,99.4139,99.4139,99.1100,99.1550,449,5,99.165324,99.225232,NaN,99.09,99.18,99.135,2021-04-23,2021-04-23
5,2021-04-23 14:45:00.000,2021-04-23 14:45:03.000,PSR,99.3200,99.3200,99.3200,99.3200,1,1,99.320000,NaN,99.320000,99.24,99.32,99.280,2021-04-23,2021-04-23
6,2021-04-23 15:00:00.000,2021-04-23 15:00:03.000,PSR,99.3350,99.4150,99.3350,99.4150,39,4,99.405492,99.407917,99.376400,99.42,99.50,99.460,2021-04-23,2021-04-23
7,2021-04-23 15:15:00.000,2021-04-23 15:15:03.000,PSR,99.5050,99.5050,99.4350,99.4350,53,3,99.452075,NaN,99.482632,99.55,99.62,99.585,2021-04-23,2021-04-23
8,2021-04-23 15:30:00.000,2021-04-23 15:30:03.000,PSR,99.6300,99.6300,99.5050,99.5050,35,4,99.618286,NaN,99.630000,99.44,99.52,99.480,2021-04-23,2021-04-23
9,2021-04-23 15:45:00.000,2021-04-23 15:45:03.000,PSR,99.5520,99.5520,99.5500,99.5500,46,2,99.551957,99.551957,NaN,99.52,99.60,99.560,2021-04-23,2021-04-23

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_15min_v2", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_15min_v2...
Found 1 files to download.
Native replication completed for xtech_us_eqt_sip_bardata_flow_15min_v2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_15min_v2", target_location="./data")