In [1]:
import os
from IPython.display import display

In [ ]:
pip install unifier

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

In [4]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction_v2", back_to='2025-11-18', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,AAAU,43.51,43.8450,43.43,43.6710,1615789,5780,43.647376,43.637264,43.651233,43.67,43.69,43.680,2026-09-04,2026-09-04
1,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,AAC.U,10.15,10.1900,10.15,10.1900,157,10,10.151019,10.150000,10.190000,7.62,12.29,9.955,2026-09-04,2026-09-04
2,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,AACG,0.91,0.9200,0.88,0.9059,3039,71,0.899494,0.886053,0.913320,0.87,0.92,0.895,2026-09-04,2026-09-04
3,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,AACP,10.06,10.1000,10.06,10.0600,10,9,10.071000,10.060000,10.082000,9.93,10.19,10.060,2026-09-04,2026-09-04
4,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,AAP,42.51,44.2300,42.42,43.9971,1264814,21947,43.673100,43.523808,43.831000,43.00,44.18,43.590,2026-09-04,2026-09-04
5,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,AAPE,15.98,16.0000,15.00,15.1700,16041,137,15.254801,15.286669,15.238172,15.18,15.20,15.190,2026-09-04,2026-09-04
6,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,ABIG,35.25,35.3342,35.20,35.2247,25763,22,35.275747,35.210193,35.279610,NaN,NaN,NaN,2026-09-04,2026-09-04
7,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,ABLS,22.00,22.2800,22.00,22.2112,11,9,22.148400,22.078333,22.232480,NaN,NaN,NaN,2026-09-04,2026-09-04
8,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,ABOT,43.00,43.9800,43.00,43.8600,219,17,43.887557,43.773571,43.891321,NaN,NaN,NaN,2026-09-04,2026-09-04
9,2026-09-04 20:15:00.000,2026-09-04 20:15:03.000,ABR,5.16,5.2600,5.12,5.2500,2501436,11924,5.202680,5.184050,5.220130,NaN,NaN,NaN,2026-09-04,2026-09-04

In [5]:
df = Unifier.get_dataframe(name='xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction_v2', back_to='2021-01-11', up_to='2021-02-01', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,AACQ,11.0800,11.3000,11.0100,11.1100,1641536,7992,11.143395,11.135357,11.147249,NaN,NaN,NaN,2021-01-14,2021-01-14
1,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,ABCL,44.3000,47.0000,41.4600,46.4600,955142,9179,44.261125,43.953442,44.470180,45.02,46.80,45.910,2021-01-14,2021-01-14
2,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,ABM,41.8800,42.9699,41.5700,42.0500,307654,3959,42.326328,42.232889,42.422580,NaN,NaN,NaN,2021-01-14,2021-01-14
3,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,ABRpB,25.3600,25.4409,25.3500,25.4340,3197,10,25.392635,25.392635,NaN,25.23,25.69,25.460,2021-01-14,2021-01-14
4,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,ABRpC,25.7700,25.9100,25.7100,25.8201,3425,27,25.833483,25.826717,25.783244,23.87,26.22,25.045,2021-01-14,2021-01-14
5,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,AC,34.2000,36.1608,34.2000,35.5000,9597,273,35.263857,35.219510,35.366643,25.00,44.70,34.850,2021-01-14,2021-01-14
6,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,ACACW,2.3500,2.5140,2.2605,2.4900,15019,32,2.341672,2.366839,2.337061,2.25,23.00,12.625,2021-01-14,2021-01-14
7,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,ACER,2.7404,2.9600,2.7000,2.8800,665687,2832,2.811467,2.797700,2.830390,2.76,2.88,2.820,2021-01-14,2021-01-14
8,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,ACKIU,10.6000,10.6000,10.4600,10.4700,71886,150,10.479071,10.478550,10.479459,10.42,10.87,10.645,2021-01-14,2021-01-14
9,2021-01-14 21:15:00.000,2021-01-14 21:15:03.000,ACP,11.0100,11.1700,10.9500,11.1400,87953,433,11.076871,11.078119,11.073914,10.99,11.20,11.095,2021-01-14,2021-01-14

In [6]:
df =  Unifier.get_dataframe(name="xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction_v2", key='PSR', back_to='2025-10-29', limit=10)
display(df)

,timestamp,asof_datetime,ident,open,high,low,close,volume,trade_count,vwap,bidvwap,askvwap,close_bid,close_ask,close_mid,date,asof_date
0,2026-02-12 21:15:00.000,2026-02-12 21:15:03.000,PSR,97.580,98.8250,97.3940,97.4263,2283,62,98.118127,98.042553,98.180152,None,None,None,2026-02-12,2026-02-12
1,2025-11-14 21:15:00.000,2025-11-14 21:15:03.000,PSR,91.480,91.6200,91.0150,91.5044,2715,56,91.321501,91.395258,91.443925,None,None,None,2025-11-14,2025-11-14
2,2025-12-04 21:15:00.000,2025-12-04 21:15:03.000,PSR,91.325,91.9611,91.1801,91.2271,322,35,91.487089,91.590414,91.357255,None,None,None,2025-12-04,2025-12-04
3,2026-02-24 21:15:00.000,2026-02-24 21:15:03.000,PSR,96.470,98.7657,96.4700,98.7657,598,20,98.323643,98.228638,98.494207,None,None,None,2026-02-24,2026-02-24
4,2026-01-09 21:15:00.000,2026-01-09 21:15:03.000,PSR,91.180,91.8700,91.1800,91.4112,671,40,91.547160,91.590370,91.307208,None,None,None,2026-01-09,2026-01-09
5,2026-09-03 20:15:00.000,2026-09-03 20:15:03.000,PSR,102.100,102.7700,101.9700,102.6768,708,37,102.596096,102.543647,102.618600,None,None,None,2026-09-03,2026-09-03
6,2026-02-03 21:15:00.000,2026-02-03 21:15:03.000,PSR,91.260,91.6999,90.7700,91.5603,1289,62,91.299815,91.329003,91.271709,None,None,None,2026-02-03,2026-02-03
7,2026-01-28 21:15:00.000,2026-01-28 21:15:03.000,PSR,91.690,92.0791,90.9894,90.9894,15128,49,91.591470,91.598514,91.634536,None,None,None,2026-01-28,2026-01-28
8,2025-11-28 21:15:00.000,2025-11-28 21:15:03.000,PSR,92.720,93.2281,92.4995,93.0331,195,31,93.037054,92.767886,93.046245,None,None,None,2025-11-28,2025-11-28
9,2025-11-24 21:15:00.000,2025-11-24 21:15:03.000,PSR,91.580,91.6200,90.9880,91.4727,1068,51,91.387790,91.252295,91.466405,None,None,None,2025-11-24,2025-11-24

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction_v2", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction_v2...
Found 1 files to download.
Native replication completed for xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction_v2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_eqt_sip_bardata_flow_daily_regular_plus_auction_v2", target_location="./data")