In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name="lseg_us_equity_options_flow_daily_v2_4", asof_date='2024-01-31', limit=10)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:32:00.000 UTC,AA,AA,RegularMkt,EQT,Call,19,1,...,0,1,0,0,0,0.000,0.0231,0,0.0000,2023-04-20
1,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:32:00.000 UTC,AA,AA,RegularMkt,EQT,Call,19,1,...,0,0,0,1,1,0.540,0.0000,0,0.0618,2023-04-20
2,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:32:00.000 UTC,AA,AA,RegularMkt,EQT,Call,19,1,...,0,2,0,0,0,0.000,1.1312,0,0.0000,2023-04-20
3,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:32:00.000 UTC,AA,AA,RegularMkt,EQT,Call,19,1,...,0,0,0,2,5,0.180,0.0000,0,0.1580,2023-04-20
4,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:32:00.000 UTC,AA,AA,RegularMkt,EQT,Put,5,5,...,0,0,0,2,2,0.415,0.0000,0,0.0368,2023-04-20
5,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:33:00.000 UTC,AA,AA,RegularMkt,EQT,Call,19,1,...,0,0,0,1,1,0.400,0.0000,0,0.0439,2023-04-20
6,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:35:00.000 UTC,AA,AA,RegularMkt,EQT,Put,20,10,...,0,1,0,0,0,0.000,0.0030,0,0.0000,2023-04-20
7,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:35:00.000 UTC,AA,AA,RegularMkt,EQT,Put,21,4,...,0,6,0,3,5,4.470,0.1548,0,0.0371,2023-04-20
8,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:35:00.000 UTC,AA,AA,RegularMkt,EQT,Call,21,4,...,0,0,0,2,4,4.700,0.0000,0,0.0010,2023-04-20
9,2023-04-20 20:16:03.000 UTC,2023-04-20,2023-04-20 13:36:00.000 UTC,AA,AA,RegularMkt,EQT,Call,16,6,...,0,0,0,1,5,0.050,0.0000,0,0.0395,2023-04-20

## Retrieve data for a specific date range using the back_to and up_to parameters

In [10]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_daily_v2_4', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 18:32:00.000 UTC,AAN,AAN,RegularMkt,EQT,Call,15,3,...,0,1,0,0,0,0.000000,0.182355,0,0.000000,2024-01-31
1,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:05:00.000 UTC,AAN,AAN,RegularMkt,EQT,Put,21,6,...,0,0,0,1,10,4.600000,0.000000,0,0.164217,2024-01-31
2,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:07:00.000 UTC,AAN,AAN,RegularMkt,EQT,Put,15,3,...,0,1,0,1,2,0.550000,0.109742,0,0.027617,2024-01-31
3,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:39:00.000 UTC,AAN,AAN,RegularMkt,EQT,Call,20,9,...,0,0,0,1,1,1.000000,0.000000,0,0.031859,2024-01-31
4,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 17:03:00.000 UTC,ABEO,ABEO,RegularMkt,EQT,Call,15,3,...,0,3,0,0,0,0.000000,0.079559,0,0.000000,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:33:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Put,9,2,...,0,6,0,2,51,0.469804,0.090928,0,0.202625,2024-01-31
96,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:39:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Put,15,3,...,0,7,0,3,11,0.611818,0.225578,0,0.124971,2024-01-31
97,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:41:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Call,1,3,...,0,5,0,4,5,0.308000,0.073850,0,0.052348,2024-01-31
98,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:42:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Call,21,6,...,0,44,0,10,156,0.357628,26.302694,0,3.476745,2024-01-31
99,2024-01-31 21:15:03.000 UTC,2024-01-31,2024-01-31 20:43:00.000 UTC,AGNC,AGNC,RegularMkt,EQT,Call,16,1,...,0,0,0,4,14,0.280714,0.000000,0,0.831380,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [11]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_daily_v2_4', key='SPXW', asof_date='2024-01-01', limit=10)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 04:53:00.000 UTC,SPXW,SPXW,NextDay,EQT,Call,5,5,...,0,1,0,0,0,0.0,0.112730,0,0.000000,2023-05-01
1,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 04:53:00.000 UTC,SPXW,SPXW,NextDay,EQT,Put,30,6,...,0,1,0,0,0,0.0,97.333959,0,0.000000,2023-05-01
2,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 05:24:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,30,6,...,0,0,0,1,15,3.5,0.000000,0,9.905085,2023-05-01
3,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 06:01:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,12,5,...,0,1,0,0,0,0.0,1.955828,0,0.000000,2023-05-01
4,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 06:16:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,31,5,...,0,1,0,0,0,0.0,23.002250,0,0.000000,2023-05-01
5,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 06:30:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,31,5,...,0,1,0,0,0,0.0,33.471999,0,0.000000,2023-05-01
6,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 07:01:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,24,5,...,0,1,0,0,0,0.0,64.545883,0,0.000000,2023-05-01
7,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 07:01:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,24,5,...,0,1,0,0,0,0.0,48.205751,0,0.000000,2023-05-01
8,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 07:02:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,30,6,...,0,1,0,0,0,0.0,11.543070,0,0.000000,2023-05-01
9,2023-05-01 20:15:03.000 UTC,2023-05-01,2023-05-01 07:03:00.000 UTC,SPXW,SPXW,PreMkt,EQT,Put,30,6,...,0,2,0,0,0,0.0,70.598002,0,0.000000,2023-05-01

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [12]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_daily_v2_4',key='SPX', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 06:44:00.000 UTC,SPX,SPX,PreMkt,EQT,Call,15,3,...,0,2,0,0,0,0.000000,2.171804,0,0.00000,2024-01-18
1,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 07:31:00.000 UTC,SPX,SPX,PreMkt,EQT,Call,17,5,...,0,1,0,0,0,0.000000,7.096340,0,0.00000,2024-01-18
2,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 09:05:00.000 UTC,SPX,SPX,PreMkt,EQT,Put,19,7,...,0,0,0,2,20,1.400000,0.000000,0,4.73353,2024-01-18
3,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 09:08:00.000 UTC,SPX,SPX,PreMkt,EQT,Put,15,3,...,0,1,0,0,0,0.000000,0.350865,0,0.00000,2024-01-18
4,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 10:41:00.000 UTC,SPX,SPX,PreMkt,EQT,Put,20,9,...,0,2,0,0,0,0.000000,749.177135,0,0.00000,2024-01-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 15:27:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,15,3,...,0,1,0,1,1,33.400002,5.312730,0,5.29533,2024-01-18
96,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 15:27:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,20,12,...,0,0,0,1,1,476.700012,0.000000,0,15.96520,2024-01-18
97,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 15:28:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,17,5,...,0,0,0,2,2,90.450001,0.000000,0,19.89693,2024-01-18
98,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 15:28:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,20,12,...,0,0,0,1,1,168.399994,0.000000,0,15.95490,2024-01-18
99,2024-01-18 21:15:03.000 UTC,2024-01-18,2024-01-18 15:29:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,1,0,0,0,0.000000,18.366849,0,0.00000,2024-01-18

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_equity_options_flow_daily_v2_4", target_location="./data", asof_date='2014-03-03')

Downloading using native python implementation for lseg_us_equity_options_flow_daily_v2_4...
Found 1 files to download.
Native replication completed for lseg_us_equity_options_flow_daily_v2_4. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_options_flow_daily_v2_4", target_location="./data")