In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="lseg_us_equity_options_flow_1min_v2_4", asof_date='2024-01-31', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2014-04-29,2014-04-29 13:37:03.000,2014-04-29 13:37:00.000,ABMD,ABMD,RegularMkt,EQT,Call,21,6,...,0,0,0,1,5,0.25,0.000,0,0.095,2014-04-29
1,2014-04-29,2014-04-29 13:57:03.000,2014-04-29 13:57:00.000,ABMD,ABMD,RegularMkt,EQT,Call,21,6,...,0,0,0,1,1,0.41,0.000,0,0.024,2014-04-29
2,2014-04-29,2014-04-29 15:27:03.000,2014-04-29 15:27:00.000,ABMD,ABMD,RegularMkt,EQT,Call,21,6,...,0,0,0,1,1,0.30,0.000,0,0.021,2014-04-29
3,2014-04-29,2014-04-29 16:11:03.000,2014-04-29 16:11:00.000,ABMD,ABMD,RegularMkt,EQT,Call,21,6,...,0,1,0,0,0,0.00,0.105,0,0.000,2014-04-29
4,2014-04-29,2014-04-29 16:45:03.000,2014-04-29 16:45:00.000,ABMD,ABMD,RegularMkt,EQT,Call,21,6,...,0,1,0,0,0,0.00,0.345,0,0.000,2014-04-29
5,2014-04-29,2014-04-29 17:22:03.000,2014-04-29 17:22:00.000,ABMD,ABMD,RegularMkt,EQT,Call,21,6,...,0,1,0,0,0,0.00,0.074,0,0.000,2014-04-29
6,2014-04-29,2014-04-29 18:47:03.000,2014-04-29 18:47:00.000,ABMD,ABMD,RegularMkt,EQT,Put,21,6,...,0,1,0,0,0,0.00,0.132,0,0.000,2014-04-29
7,2014-04-29,2014-04-29 17:21:03.000,2014-04-29 17:21:00.000,ACHN,ACHN,RegularMkt,EQT,Call,20,12,...,0,0,0,1,4,0.35,0.000,0,0.032,2014-04-29
8,2014-04-29,2014-04-29 19:29:03.000,2014-04-29 19:29:00.000,ACHN,ACHN,RegularMkt,EQT,Call,21,6,...,0,1,0,0,0,0.00,0.006,0,0.000,2014-04-29
9,2014-04-29,2014-04-29 16:32:03.000,2014-04-29 16:32:00.000,AEC,AEC,RegularMkt,EQT,Put,20,12,...,0,1,0,0,0,0.00,0.052,0,0.000,2014-04-29

## Retrieve data for a specific date range using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_1min_v2_4', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31,2024-01-31 18:40:03.000,2024-01-31 18:40:00.000,ACGL,ACGL,RegularMkt,EQT,Put,15,3,...,0,0,0,1,2,0.65,0.000000,0,0.133514,2024-01-31
1,2024-01-31,2024-01-31 18:41:03.000,2024-01-31 18:41:00.000,ACGL,ACGL,RegularMkt,EQT,Call,16,2,...,0,0,0,1,2,1.00,0.000000,0,0.129144,2024-01-31
2,2024-01-31,2024-01-31 18:42:03.000,2024-01-31 18:42:00.000,ACGL,ACGL,RegularMkt,EQT,Call,15,3,...,0,1,0,0,0,0.00,0.420624,0,0.000000,2024-01-31
3,2024-01-31,2024-01-31 18:59:03.000,2024-01-31 18:59:00.000,ACGL,ACGL,RegularMkt,EQT,Call,15,3,...,0,1,0,0,0,0.00,0.050081,0,0.000000,2024-01-31
4,2024-01-31,2024-01-31 19:01:03.000,2024-01-31 19:01:00.000,ACGL,ACGL,RegularMkt,EQT,Call,16,2,...,0,0,0,1,1,0.95,0.000000,0,0.063550,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 18:42:03.000,2024-01-31 18:42:00.000,ADBE,ADBE,RegularMkt,EQT,Call,9,2,...,0,1,0,0,0,0.00,1.366304,0,0.000000,2024-01-31
96,2024-01-31,2024-01-31 18:42:03.000,2024-01-31 18:42:00.000,ADBE,ADBE,RegularMkt,EQT,Call,23,2,...,0,0,0,4,9,2.27,0.000000,0,2.673126,2024-01-31
97,2024-01-31,2024-01-31 18:44:03.000,2024-01-31 18:44:00.000,ADBE,ADBE,RegularMkt,EQT,Call,19,4,...,0,1,0,0,0,0.00,1.142380,0,0.000000,2024-01-31
98,2024-01-31,2024-01-31 18:44:03.000,2024-01-31 18:44:00.000,ADBE,ADBE,RegularMkt,EQT,Put,9,2,...,0,1,0,0,0,0.00,0.347604,0,0.000000,2024-01-31
99,2024-01-31,2024-01-31 18:44:03.000,2024-01-31 18:44:00.000,ADBE,ADBE,RegularMkt,EQT,Put,2,2,...,0,0,0,1,1,1.10,0.000000,0,0.111915,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_1min_v2_4', key='SPXW', asof_date='2024-01-01', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Put,26,2,...,0,0,0,1,1,37.200001,0.0000,0.0000,3.472600,2021-01-26
1,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Put,27,1,...,0,0,0,1,5,22.900000,0.0000,0.0000,5.254500,2021-01-26
2,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Call,29,1,...,1,0,1,0,0,0.000000,0.0000,0.4523,0.000000,2021-01-26
3,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Put,1,2,...,0,0,0,1,10,31.299999,0.0000,0.0000,20.606000,2021-01-26
4,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Put,26,2,...,0,0,0,2,2,39.450001,0.0000,0.0000,7.176300,2021-01-26
5,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Put,27,1,...,0,1,0,0,0,0.000000,1.0626,0.0000,0.000000,2021-01-26
6,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Call,27,1,...,0,3,0,0,0,0.000000,2.9433,0.0000,0.000000,2021-01-26
7,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Call,27,1,...,0,0,0,1,50,18.700001,0.0000,0.0000,56.209999,2021-01-26
8,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Call,29,1,...,2,0,1,0,0,0.000000,0.0000,3.1094,0.000000,2021-01-26
9,2021-01-26,2021-01-26 16:30:03.000,2021-01-26 16:30:00.000,SPXW,SPXW,RegularMkt,EQT,Put,27,1,...,0,0,0,2,4,15.225000,0.0000,0.0000,4.545200,2021-01-26

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_1min_v2_4',key='SPX', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-24,2024-01-24 17:55:03.000,2024-01-24 17:55:00.000,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,1,0,0,0,0.000000,21.870251,0,0.000000,2024-01-24
1,2024-01-24,2024-01-24 17:55:03.000,2024-01-24 17:55:00.000,SPX,SPX,RegularMkt,EQT,Call,15,3,...,0,1,0,0,0,0.000000,7.191840,0,0.000000,2024-01-24
2,2024-01-24,2024-01-24 17:55:03.000,2024-01-24 17:55:00.000,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,1,0,0,0,0.000000,39.795799,0,0.000000,2024-01-24
3,2024-01-24,2024-01-24 17:55:03.000,2024-01-24 17:55:00.000,SPX,SPX,RegularMkt,EQT,Call,19,4,...,0,0,0,1,1,250.600006,0.000000,0,7.517780,2024-01-24
4,2024-01-24,2024-01-24 17:55:03.000,2024-01-24 17:55:00.000,SPX,SPX,RegularMkt,EQT,Put,19,4,...,0,0,0,1,6,31.500000,0.000000,0,34.803540,2024-01-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-24,2024-01-24 18:16:03.000,2024-01-24 18:16:00.000,SPX,SPX,RegularMkt,EQT,Put,19,4,...,0,2,0,0,0,0.000000,66.127041,0,0.000000,2024-01-24
96,2024-01-24,2024-01-24 18:16:03.000,2024-01-24 18:16:00.000,SPX,SPX,RegularMkt,EQT,Put,21,6,...,0,1,0,0,0,0.000000,12.050400,0,0.000000,2024-01-24
97,2024-01-24,2024-01-24 18:16:03.000,2024-01-24 18:16:00.000,SPX,SPX,RegularMkt,EQT,Call,21,6,...,0,0,0,3,3,181.166667,0.000000,0,36.611901,2024-01-24
98,2024-01-24,2024-01-24 18:16:03.000,2024-01-24 18:16:00.000,SPX,SPX,RegularMkt,EQT,Put,21,6,...,0,0,0,1,1,137.500000,0.000000,0,12.316900,2024-01-24
99,2024-01-24,2024-01-24 18:16:03.000,2024-01-24 18:16:00.000,SPX,SPX,RegularMkt,EQT,Call,16,2,...,0,2,0,0,0,0.000000,207.672926,0,0.000000,2024-01-24

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_equity_options_flow_1min_v2_4", target_location="./data", asof_date='2014-01-31')

Downloading using native python implementation for lseg_us_equity_options_flow_1min_v2_4...
Found 1 files to download.
Native replication completed for lseg_us_equity_options_flow_1min_v2_4. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_options_flow_1min_v2_4", target_location="./data")