In [4]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'

os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [14]:
df = Unifier.get_dataframe(name="lseg_us_eqt_options_flow_r3k_with_isin_1min_trial", asof_date='2024-01-31', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,GSAT,US3789734080,GSAT,RegularMkt,EQT,Put,24,...,0,1,0,0,0,0.00,0.002209,0,0.000000,2023-10-24
1,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,GT,US3825501014,GT,RegularMkt,EQT,Put,10,...,0,0,0,1,8,0.50,0.000000,0,0.084678,2023-10-24
2,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,GT,US3825501014,GT,RegularMkt,EQT,Call,10,...,0,0,0,1,8,0.55,0.000000,0,0.087570,2023-10-24
3,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,GTLS,US16115Q3083,GTLS,RegularMkt,EQT,Call,15,...,0,0,0,1,5,0.85,0.000000,0,0.378344,2023-10-24
4,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,INCY,US45337C1027,INCY,RegularMkt,EQT,Put,17,...,0,1,0,0,0,0.00,0.029505,0,0.000000,2023-10-24
5,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,INCY,US45337C1027,INCY,RegularMkt,EQT,Call,17,...,0,0,0,1,1,0.06,0.000000,0,0.010643,2023-10-24
6,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,JNJ,US4781601046,JNJ,RegularMkt,EQT,Call,27,...,0,0,0,1,1,0.67,0.000000,0,0.059147,2023-10-24
7,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,JNJ,US4781601046,JNJ,RegularMkt,EQT,Call,17,...,0,1,0,0,0,0.00,0.152161,0,0.000000,2023-10-24
8,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,JNJ,US4781601046,JNJ,RegularMkt,EQT,Put,17,...,0,1,0,0,0,0.00,0.761415,0,0.000000,2023-10-24
9,2023-10-24,2023-10-24 23:30:30.000,2023-10-24 19:32:00.000,JNJ,US4781601046,JNJ,RegularMkt,EQT,Call,17,...,0,2,0,0,0,0.00,0.437265,0,0.000000,2023-10-24

## Retrieve data for a specific date range using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_options_flow_r3k_with_isin_1min_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:45:00.000,NVDA,US67066G1040,NVDA,RegularMkt,EQT,Call,17,...,0,0,0,1,1,28.750000,0.000000,0,1.255800,2024-01-31
1,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:45:00.000,NVDA,US67066G1040,NVDA,RegularMkt,EQT,Call,17,...,0,0,0,1,1,27.450000,0.000000,0,1.239180,2024-01-31
2,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:45:00.000,NVDA,US67066G1040,NVDA,RegularMkt,EQT,Call,17,...,0,0,0,2,3,17.616667,0.000000,0,3.164070,2024-01-31
3,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:45:00.000,NVDA,US67066G1040,NVDA,RegularMkt,EQT,Put,21,...,0,1,0,0,0,0.000000,0.371235,0,0.000000,2024-01-31
4,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:45:00.000,NVDA,US67066G1040,NVDA,RegularMkt,EQT,Call,21,...,0,0,0,1,1,206.400000,0.000000,0,0.502778,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:44:00.000,INTC,US4581401001,INTC,RegularMkt,EQT,Put,23,...,0,0,0,2,5,0.310000,0.000000,0,0.134000,2024-01-31
96,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:44:00.000,INTC,US4581401001,INTC,RegularMkt,EQT,Call,23,...,0,0,0,1,1,1.890000,0.000000,0,0.043048,2024-01-31
97,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:44:00.000,INTC,US4581401001,INTC,RegularMkt,EQT,Put,23,...,0,0,0,1,1,1.660000,0.000000,0,0.043407,2024-01-31
98,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:44:00.000,INTC,US4581401001,INTC,RegularMkt,EQT,Call,23,...,0,0,0,2,3,0.963333,0.000000,0,0.123598,2024-01-31
99,2024-01-31,2024-01-31 23:30:30.000,2024-01-31 19:44:00.000,INTC,US4581401001,INTC,RegularMkt,EQT,Call,23,...,0,0,0,2,30,0.460000,0.000000,0,0.928113,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [11]:
df = Unifier.get_dataframe(name='lseg_us_eqt_options_flow_r3k_with_isin_1min_trial',key='AAPL', asof_date='2024-01-01', limit=10)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,24,...,0,1,0,0,0,0.000000,0.0060,0,0.0000,2020-12-23
1,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,24,...,0,0,0,1,1,11.980000,0.0000,0,0.0014,2020-12-23
2,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,24,...,0,0,0,1,1,0.010000,0.0000,0,0.0013,2020-12-23
3,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,24,...,0,0,0,1,7,8.990000,0.0000,0,0.0189,2020-12-23
4,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,24,...,0,1,0,0,0,0.000000,0.0170,0,0.0000,2020-12-23
5,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,24,...,0,1,0,0,0,0.000000,0.0343,0,0.0000,2020-12-23
6,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,24,...,0,2,0,0,0,0.000000,0.0216,0,0.0000,2020-12-23
7,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,24,...,0,0,0,3,15,0.040000,0.0000,0,0.0900,2020-12-23
8,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,24,...,0,2,0,2,6,2.171667,0.1000,0,0.1161,2020-12-23
9,2020-12-23,2020-12-23 23:30:30.000,2020-12-23 18:25:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,24,...,0,6,0,0,0,0.000000,0.2940,0,0.0000,2020-12-23

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='lseg_us_eqt_options_flow_r3k_with_isin_1min_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,asof_datetime,timestamp,ident,isin,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 21:00:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,16,...,0,3,0,5,6,1.823333,1.484700,0,0.890820,2024-01-26
1,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 21:00:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,16,...,0,0,0,1,2,6.060000,0.000000,0,0.360202,2024-01-26
2,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 21:00:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,16,...,0,1,0,1,4,3.350000,0.180526,0,0.722104,2024-01-26
3,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 21:00:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,16,...,0,1,0,5,15,4.620000,0.185759,0,2.786385,2024-01-26
4,2024-01-26,2024-01-26 23:30:30.000,2024-01-26 21:00:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,16,...,0,1,0,1,1,4.470000,0.185575,0,0.185575,2024-01-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-24,2024-01-24 23:30:30.000,2024-01-24 19:33:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,16,...,0,0,0,1,1,4.450000,0.000000,0,0.475270,2024-01-24
96,2024-01-24,2024-01-24 23:30:30.000,2024-01-24 19:34:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,26,...,0,2,0,0,0,0.000000,0.026236,0,0.000000,2024-01-24
97,2024-01-24,2024-01-24 23:30:30.000,2024-01-24 19:34:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,26,...,0,0,0,1,1,0.040000,0.000000,0,0.010354,2024-01-24
98,2024-01-24,2024-01-24 23:30:30.000,2024-01-24 19:34:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Put,26,...,0,2,0,0,0,0.000000,0.292516,0,0.000000,2024-01-24
99,2024-01-24,2024-01-24 23:30:30.000,2024-01-24 19:34:00.000,AAPL,US0378331005,AAPL,RegularMkt,EQT,Call,26,...,0,0,0,1,10,2.930000,0.000000,0,0.484239,2024-01-24

## Download data file for a specific date using asof_date

In [10]:
Unifier.replicate(name="lseg_us_eqt_options_flow_r3k_with_isin_1min_trial", target_location="./data", asof_date='2014-01-31')

Starting native python replication for lseg_us_eqt_options_flow_r3k_with_isin_1min_trial (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_options_flow_r3k_with_isin_1min_trial. Downloaded 1 files.

## Download All data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_options_flow_r3k_with_isin_1min_trial", target_location="./data")