In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [12]:
# Unifier.user = 'unifier username'
# Unifier.token = 'unifier api token'
Unifier.user = 'demo'
Unifier.token ='qZy7KpE+L5Fg2MmjFqC/1xmweo7pgnnACCcK3JNEAec='
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [13]:
df = Unifier.get_dataframe(name="lseg_us_equity_options_flow_daily_v2_3", asof_date='2024-01-31', limit=10)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 15:48:00.000 UTC,IHI,IHI,RegularMkt,EQT,Call,20,1,...,0,1,0,0,0,0.000000,3.7074,0.0000,0.0000,2022-12-23
1,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 21:00:00.000 UTC,TLT,TLT,RegularMkt,EQT,Put,30,12,...,2,5,1,20,110,3.782909,0.4814,0.0358,2.0429,2022-12-23
2,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 16:04:00.000 UTC,LABD,LABD,RegularMkt,EQT,Call,13,1,...,0,0,0,1,2,2.950000,0.0000,0.0000,0.0308,2022-12-23
3,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 16:06:00.000 UTC,LABD,LABD,RegularMkt,EQT,Put,13,1,...,0,7,0,0,0,0.000000,0.6160,0.0000,0.0000,2022-12-23
4,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 18:34:00.000 UTC,DOCU,DOCU,RegularMkt,EQT,Put,30,12,...,0,1,0,2,10,0.055000,0.0645,0.0000,0.0475,2022-12-23
5,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 20:50:00.000 UTC,VOO,VOO,RegularMkt,EQT,Put,16,6,...,0,0,0,2,2,19.190000,0.0000,0.0000,1.8794,2022-12-23
6,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 19:51:00.000 UTC,EQT,EQT,RegularMkt,EQT,Call,17,3,...,0,0,0,1,7,0.800000,0.0000,0.0000,0.3164,2022-12-23
7,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 20:17:00.000 UTC,PARA,PARA,RegularMkt,EQT,Call,17,3,...,0,21,0,10,30,0.139333,2.9985,0.0000,0.3800,2022-12-23
8,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 19:11:00.000 UTC,IBB,IBB,RegularMkt,EQT,Put,17,3,...,0,0,0,1,1,5.300000,0.0000,0.0000,0.2426,2022-12-23
9,2022-12-23 22:00:03.000 UTC,2022-12-23,2022-12-23 16:04:00.000 UTC,RIOT,RIOT,RegularMkt,EQT,Put,13,1,...,0,0,0,1,2,0.010000,0.0000,0.0000,0.0004,2022-12-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_daily_v2_3', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 20:09:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,19,7,...,0,5,0,1,1,80.100000,230.53840,0.0,10.340200,2024-01-31
1,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:02:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,18,10,...,0,2,0,0,0,0.000000,29.99990,0.0,0.000000,2024-01-31
2,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:15:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,19,12,...,0,0,0,2,31,317.072903,0.00000,0.0,759.898300,2024-01-31
3,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 17:23:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,17,5,...,0,1,0,1,1,62.500000,8.55177,0.0,8.517150,2024-01-31
4,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:26:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,20,12,...,0,0,0,6,2250,18.820000,0.00000,0.0,7271.572500,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:17:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,19,4,...,0,0,0,1,1,9.900000,0.00000,0.0,3.701110,2024-01-31
96,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 19:15:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,19,4,...,0,1,0,1,27,19.300000,31.18256,0.0,103.105980,2024-01-31
97,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 20:58:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,19,4,...,0,0,0,7,14,52.074286,0.00000,0.0,113.046660,2024-01-31
98,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:35:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,17,5,...,0,2,0,0,0,0.000000,21.07260,0.0,0.000000,2024-01-31
99,2024-01-31 22:44:03.000 UTC,2024-01-31,2024-01-31 18:21:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,0,0,2,21,1.050000,0.00000,0.0,4.930554,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_daily_v2_3', key='SPXW', asof_date='2024-01-01', limit=10)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:15:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Call,27,7,...,0,1,0,0,0,0,0.086,0.000,0,2018-07-23
1,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:14:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,8,8,...,0,1,0,0,0,0,1.070,0.000,0,2018-07-23
2,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:12:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,14,9,...,2,0,1,0,0,0,0.000,8.604,0,2018-07-23
3,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:12:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Call,25,7,...,0,1,0,0,0,0,0.172,0.000,0,2018-07-23
4,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:11:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Call,15,8,...,0,2,0,0,0,0,4.962,0.000,0,2018-07-23
5,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:11:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,17,8,...,0,2,0,0,0,0,7.504,0.000,0,2018-07-23
6,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:11:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,24,8,...,0,1,0,0,0,0,4.800,0.000,0,2018-07-23
7,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:11:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,21,9,...,0,1,0,0,0,0,12.375,0.000,0,2018-07-23
8,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:10:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Put,28,9,...,0,1,0,0,0,0,1.139,0.000,0,2018-07-23
9,2018-07-23 20:39:03.000 UTC,2018-07-23,2018-07-23 20:10:00.000 UTC,SPXW,SPXW,RegularMkt,EQT,Call,31,8,...,1,0,1,0,0,0,0.000,0.955,0,2018-07-23

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='lseg_us_equity_options_flow_daily_v2_3',key='SPX', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,date,timestamp,ident,okey_tk,tradingsession,okey_at,okey_cp,okey_dy,okey_mn,...,m4_neutral_volume,m4_num_buy_trades,m4_num_neutral_trades,m4_num_sell_trades,m4_sell_volume,m4_sell_vwap,m4_vega_buy_volume,m4_vega_neutral_volume,m4_vega_sell_volume,asof_date
0,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 18:31:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,19,4,...,0,2,0,0,0,0.000000,1.521974,0.0,0.00000,2024-01-09
1,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 20:38:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,21,6,...,0,2,0,2,2,135.370000,24.582600,0.0,24.63100,2024-01-09
2,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 20:45:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,21,6,...,0,1,0,1,45,15.900000,11.302340,0.0,256.71465,2024-01-09
3,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 19:30:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,16,8,...,0,5,0,1,2,213.540000,145.227200,0.0,29.05260,2024-01-09
4,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 19:11:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,19,7,...,0,0,0,2,10,0.200000,0.000000,0.0,1.67395,2024-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 18:39:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,20,12,...,0,5,0,0,0,0.000000,1028.606840,0.0,0.00000,2024-01-09
96,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 20:41:00.000 UTC,SPX,SPX,RegularMkt,EQT,Call,19,12,...,0,2,0,9,1017,1116.663963,50.501400,0.0,17037.58230,2024-01-09
97,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 19:20:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,3,0,0,0,0.000000,137.121600,0.0,0.00000,2024-01-09
98,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 18:19:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,1,0,0,0,0.000000,95.752000,0.0,0.00000,2024-01-09
99,2024-01-09 22:04:03.000 UTC,2024-01-09,2024-01-09 15:41:00.000 UTC,SPX,SPX,RegularMkt,EQT,Put,16,2,...,0,1,0,0,0,0.000000,1.272780,0.0,0.00000,2024-01-09

## Download data file for a specific date using asof_date

In [14]:
Unifier.replicate(name="lseg_us_equity_options_flow_daily_v2_3", target_location="./data", asof_date='2014-01-31')

Starting native python replication for lseg_us_equity_options_flow_daily_v2_3 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_equity_options_flow_daily_v2_3. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_equity_options_flow_daily_v2_3", target_location="./data")