In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [9]:
df = Unifier.get_dataframe(name="xtech_us_etf_flow_1min_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2013-07-23 04:02:03.000,2013-07-23 04:02:00.000,1,GDXJ,1,4270.00,2135.00,2135.00,0,0,...,2135.00,2135.00,0,0,0,0,0,0,2013-07-23,2013-07-23
1,2013-07-23 05:40:03.000,2013-07-23 05:40:00.000,1,BOIL,1,3880.00,1940.00,1940.00,0,0,...,1940.00,1940.00,0,0,0,0,0,0,2013-07-23,2013-07-23
2,2013-07-23 07:10:03.000,2013-07-23 07:10:00.000,1,SPXL,3,63908.00,53256.67,10651.33,2,0,...,31954.00,31954.00,0,0,0,0,0,0,2013-07-23,2013-07-23
3,2013-07-23 07:50:03.000,2013-07-23 07:50:00.000,1,FXI,1,10987.22,5493.61,5493.61,0,0,...,5493.61,5493.61,0,0,0,0,0,0,2013-07-23,2013-07-23
4,2013-07-23 07:55:03.000,2013-07-23 07:55:00.000,1,JNK,1,12240.00,6120.00,6120.00,0,0,...,6120.00,6120.00,0,0,0,0,0,0,2013-07-23,2013-07-23
5,2013-07-23 08:01:03.000,2013-07-23 08:01:00.000,1,FXI,2,10402.00,5201.00,5201.00,1,1,...,5201.00,5201.00,0,0,0,0,0,0,2013-07-23,2013-07-23
6,2013-07-23 08:01:03.000,2013-07-23 08:01:00.000,1,GDXJ,1,10690.00,0.00,10690.00,0,1,...,5345.00,5345.00,0,0,0,0,0,0,2013-07-23,2013-07-23
7,2013-07-23 08:01:03.000,2013-07-23 08:01:00.000,1,SPXL,3,52308.86,34872.57,17436.29,2,1,...,26154.43,26154.43,0,0,0,0,0,0,2013-07-23,2013-07-23
8,2013-07-23 08:04:03.000,2013-07-23 08:04:00.000,1,ZSL,1,9529.00,4764.50,4764.50,0,0,...,9529.00,0.00,1,0,0,0,0,0,2013-07-23,2013-07-23
9,2013-07-23 08:06:03.000,2013-07-23 08:06:00.000,1,FXI,3,3231333.00,0.00,3231333.00,0,3,...,1615666.50,1615666.50,0,0,0,0,0,0,2013-07-23,2013-07-23

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,ARKK,1,1023.00,511.50,511.50,0,0,...,511.50,511.50,0,0,0,0,0,0,2024-01-31,2024-01-31
1,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,NVDX,1,50.03,25.02,25.02,0,0,...,50.03,0.00,1,0,0,0,0,0,2024-01-31,2024-01-31
2,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,SPY,11,61637.71,16810.28,44827.43,1,6,...,30818.86,30818.86,0,0,0,0,0,0,2024-01-31,2024-01-31
3,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,TSLS,5,1510.15,1359.14,151.01,4,0,...,755.08,755.08,0,0,0,0,0,0,2024-01-31,2024-01-31
4,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,UPRO,1,58.97,29.48,29.48,0,0,...,0.00,58.97,0,1,0,0,0,0,2024-01-31,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 04:26:03.000,2024-01-31 04:26:00.000,1,TSLS,1,2041.80,2041.80,0.00,1,0,...,0.00,2041.80,0,1,0,0,0,0,2024-01-31,2024-01-31
96,2024-01-31 04:26:03.000,2024-01-31 04:26:00.000,1,UPRO,1,3578.87,3578.87,0.00,1,0,...,1789.44,1789.44,0,0,0,0,0,0,2024-01-31,2024-01-31
97,2024-01-31 04:27:03.000,2024-01-31 04:27:00.000,1,NVDX,2,250.65,250.65,0.00,2,0,...,250.65,0.00,2,0,0,0,0,0,2024-01-31,2024-01-31
98,2024-01-31 04:27:03.000,2024-01-31 04:27:00.000,1,SPY,5,495410.46,99082.09,396328.37,1,4,...,0.00,495410.46,0,5,0,0,0,0,2024-01-31,2024-01-31
99,2024-01-31 04:27:03.000,2024-01-31 04:27:00.000,1,TSLS,3,968.35,322.78,645.57,1,2,...,322.78,645.57,1,2,0,0,0,0,2024-01-31,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_trial',key='ARKK', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2022-01-31 04:01:03.000,2022-01-31 04:01:00.000,1,ARKK,14,9295.90,995.99,8299.91,1,12,...,1327.99,7967.91,2,12,0,0,0,0,2022-01-31,2022-01-31
1,2022-01-31 04:02:03.000,2022-01-31 04:02:00.000,1,ARKK,1,696.30,0.00,696.30,0,1,...,0.00,696.30,0,1,0,0,0,0,2022-01-31,2022-01-31
2,2022-01-31 04:03:03.000,2022-01-31 04:03:00.000,1,ARKK,3,4410.00,1470.00,2940.00,1,2,...,4410.00,0.00,3,0,0,0,0,0,2022-01-31,2022-01-31
3,2022-01-31 04:04:03.000,2022-01-31 04:04:00.000,1,ARKK,1,140.00,0.00,140.00,0,1,...,140.00,0.00,1,0,0,0,0,0,2022-01-31,2022-01-31
4,2022-01-31 04:05:03.000,2022-01-31 04:05:00.000,1,ARKK,8,8008.97,6006.73,2002.24,6,2,...,7007.85,1001.12,7,1,0,0,0,0,2022-01-31,2022-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-01-31 06:55:03.000,2022-01-31 06:55:00.000,1,ARKK,2,1249.60,0.00,1249.60,0,2,...,0.00,1249.60,0,2,0,0,0,0,2022-01-31,2022-01-31
96,2022-01-31 06:57:03.000,2022-01-31 06:57:00.000,1,ARKK,2,4441.62,0.00,4441.62,0,2,...,0.00,4441.62,0,2,0,0,0,0,2022-01-31,2022-01-31
97,2022-01-31 06:58:03.000,2022-01-31 06:58:00.000,1,ARKK,1,69.32,0.00,69.32,0,1,...,0.00,69.32,0,1,0,0,0,0,2022-01-31,2022-01-31
98,2022-01-31 06:59:03.000,2022-01-31 06:59:00.000,1,ARKK,1,69.56,69.56,0.00,1,0,...,0.00,69.56,0,1,0,0,0,0,2022-01-31,2022-01-31
99,2022-01-31 07:01:03.000,2022-01-31 07:01:00.000,1,ARKK,30,150549.21,75274.61,75274.61,15,15,...,0.00,150549.21,0,30,0,0,0,0,2022-01-31,2022-01-31

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_trial',key='NVDX', back_to='2024-01-01', up_to='2024-06-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-04-16 04:01:03.000,2024-04-16 04:01:00.000,1,NVDX,1,1017.61,508.80,508.80,0,0,...,0.00,1017.61,0,1,0.0,0,0,0,2024-04-16,2024-04-16
1,2024-04-16 04:02:03.000,2024-04-16 04:02:00.000,1,NVDX,2,9722.16,0.00,9722.16,0,2,...,0.00,9722.16,0,2,0.0,0,0,0,2024-04-16,2024-04-16
2,2024-04-16 04:03:03.000,2024-04-16 04:03:00.000,1,NVDX,1,9900.00,0.00,9900.00,0,1,...,0.00,9900.00,0,1,0.0,0,0,0,2024-04-16,2024-04-16
3,2024-04-16 04:06:03.000,2024-04-16 04:06:00.000,1,NVDX,1,180.10,180.10,0.00,1,0,...,180.10,0.00,1,0,0.0,0,0,0,2024-04-16,2024-04-16
4,2024-04-16 04:07:03.000,2024-04-16 04:07:00.000,1,NVDX,2,1343.55,0.00,1343.55,0,2,...,0.00,1343.55,0,2,0.0,0,0,0,2024-04-16,2024-04-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-04-16 08:15:03.000,2024-04-16 08:15:00.000,1,NVDX,2,12072.78,0.00,12072.78,0,2,...,12072.78,0.00,2,0,0.0,0,0,0,2024-04-16,2024-04-16
96,2024-04-16 08:16:03.000,2024-04-16 08:16:00.000,1,NVDX,1,61837.18,0.00,61837.18,0,1,...,61837.18,0.00,1,0,0.0,0,0,0,2024-04-16,2024-04-16
97,2024-04-16 08:17:03.000,2024-04-16 08:17:00.000,1,NVDX,3,2917.77,972.59,1945.18,1,2,...,2917.77,0.00,3,0,0.0,0,0,0,2024-04-16,2024-04-16
98,2024-04-16 08:18:03.000,2024-04-16 08:18:00.000,1,NVDX,4,27303.00,0.00,27303.00,0,4,...,20477.25,6825.75,3,1,0.0,0,0,0,2024-04-16,2024-04-16
99,2024-04-16 08:19:03.000,2024-04-16 08:19:00.000,1,NVDX,5,15289.68,9173.81,6115.87,3,2,...,15289.68,0.00,5,0,0.0,0,0,0,2024-04-16,2024-04-16

## Download data file for a specific date using asof_date

In [4]:
Unifier.replicate(name="xtech_us_etf_flow_1min_v1_2_trial", target_location="./data", asof_date='2025-01-13')

Starting native python replication for xtech_us_etf_flow_1min_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_etf_flow_1min_v1_2_trial. Downloaded 1 files.