In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_etf_flow_daily_v1_2_trial", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2022-03-29 20:00:03.000,2022-03-29 17:46:00.000,1,MCHI,39387,3.430942e+08,1.530457e+08,1.845934e+08,16787,22594,...,3.280066e+07,3.048385e+08,5715,33667,4111318.35,1343682.34,211,192,2022-03-29,2022-03-29
1,2022-03-29 20:00:03.000,2022-03-29 18:31:00.000,1,INDA,13169,1.382918e+08,8.624813e+07,4.932215e+07,8379,4775,...,1.340982e+08,1.472095e+06,12941,201,1463220.21,1258288.32,185,137,2022-03-29,2022-03-29
2,2022-03-29 20:00:03.000,2022-03-29 19:05:00.000,1,SPYV,11284,1.935091e+08,1.003609e+08,7.112353e+07,6815,4468,...,1.697882e+08,1.696191e+06,11027,257,9288291.83,12736454.64,464,504,2022-03-29,2022-03-29
3,2022-03-29 20:00:03.000,2022-03-29 19:31:00.000,1,WCLD,4613,2.038970e+07,1.148155e+07,7.323991e+06,2643,1967,...,1.461848e+07,4.187052e+06,3521,1031,967126.03,617036.89,218,125,2022-03-29,2022-03-29
4,2022-03-29 20:00:03.000,2022-03-29 19:39:00.000,1,SPHQ,5999,4.918052e+07,2.344719e+07,2.089007e+07,3216,2774,...,4.030066e+07,4.036603e+06,5381,617,2869836.29,1973417.07,309,192,2022-03-29,2022-03-29
5,2022-03-29 20:00:03.000,2022-03-29 19:57:00.000,1,IAU,21685,5.194296e+08,2.551369e+08,2.133780e+08,11987,9690,...,4.621394e+08,6.375540e+06,21067,403,29901597.63,21013003.58,1388,984,2022-03-29,2022-03-29
6,2022-03-29 20:00:03.000,2022-03-29 19:57:00.000,1,SVXY,39446,2.257698e+08,1.159165e+08,1.045858e+08,20720,18448,...,1.600276e+08,6.047469e+07,28017,10030,2826115.20,2441392.49,390,374,2022-03-29,2022-03-29
7,2022-03-29 20:00:03.000,2022-03-29 19:59:00.000,1,DRIP,25551,1.457013e+08,6.913780e+07,7.071387e+07,12481,13069,...,6.279611e+07,7.705556e+07,11721,13815,2771259.07,3078370.23,497,549,2022-03-29,2022-03-29
8,2022-03-29 20:00:03.000,2022-03-29 19:59:00.000,1,IWM,251063,5.692420e+09,2.787240e+09,2.810034e+09,125012,125038,...,2.753940e+09,2.843335e+09,134441,116614,56293991.59,38851321.82,2675,1897,2022-03-29,2022-03-29
9,2022-03-29 20:00:03.000,2022-03-29 19:59:00.000,1,NAIL,9925,4.204958e+07,1.880395e+07,1.852316e+07,4897,5027,...,1.687311e+07,2.045399e+07,4451,5474,2324203.54,2398272.77,470,515,2022-03-29,2022-03-29

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-02 20:00:03.000,2024-01-02 16:16:00.000,1,FTCS,2746,2.941589e+07,1.220156e+07,9.932868e+06,1466,1279,...,1.916997e+07,2.964453e+06,2252,493,3714505.32,3566961.98,393,386,2024-01-02,2024-01-02
1,2024-01-02 20:00:03.000,2024-01-02 18:51:00.000,1,VYMI,4203,4.040453e+07,1.764068e+07,1.484818e+07,2457,1745,...,2.833687e+07,4.152001e+06,3458,736,4283700.59,3631956.60,569,304,2024-01-02,2024-01-02
2,2024-01-02 20:00:03.000,2024-01-02 18:57:00.000,1,KBWB,7268,5.703730e+07,3.825376e+07,1.738038e+07,4312,2955,...,5.174232e+07,3.891820e+06,6697,571,700989.31,702170.98,154,161,2024-01-02,2024-01-02
3,2024-01-02 20:00:03.000,2024-01-02 19:11:00.000,1,EDV,6890,6.235841e+07,3.035722e+07,2.626724e+07,3393,3496,...,5.418869e+07,2.435773e+06,6362,526,3138321.26,2595626.30,351,275,2024-01-02,2024-01-02
4,2024-01-02 20:00:03.000,2024-01-02 19:48:00.000,1,SCO,12953,4.794965e+07,2.405513e+07,1.997471e+07,7030,5894,...,3.970928e+07,4.320566e+06,11504,1442,1999152.99,1920654.17,528,525,2024-01-02,2024-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-10 20:00:03.000,2024-01-10 20:01:00.000,1,IWO,6600,1.051240e+08,5.107437e+07,4.564839e+07,3610,2984,...,6.844608e+07,2.827667e+07,4744,1660,4407602.02,3993641.90,267,270,2024-01-10,2024-01-10
96,2024-01-10 20:00:03.000,2024-01-10 20:01:00.000,1,JNUG,8269,3.921468e+07,1.826306e+07,1.715899e+07,4256,3982,...,2.629959e+07,9.122459e+06,6003,2256,2045856.66,1746769.89,370,312,2024-01-10,2024-01-10
97,2024-01-10 20:00:03.000,2024-01-10 20:01:00.000,1,LQD,103155,3.294171e+09,1.480204e+09,1.759427e+09,46712,56434,...,1.823546e+09,1.416085e+09,56921,46234,29985191.89,24555197.26,876,809,2024-01-10,2024-01-10
98,2024-01-10 20:00:03.000,2024-01-10 20:01:00.000,1,NVDX,1827,8.625652e+06,4.090437e+06,3.023476e+06,967,859,...,5.037685e+06,2.076228e+06,1260,565,623298.37,888440.60,104,110,2024-01-10,2024-01-10
99,2024-01-10 20:00:03.000,2024-01-10 20:01:00.000,1,SCHB,5607,4.814731e+07,2.565312e+07,1.438020e+07,3413,2193,...,3.974436e+07,2.889591e+05,5533,58,4455390.17,3658598.39,630,451,2024-01-10,2024-01-10

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_trial',key='FTCS', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2020-12-31 20:00:03.000,2020-12-31 16:01:00.000,1,FTCS,1762,2.194621e+07,8664144.82,6441725.85,1045,716,...,8577282.76,6528587.91,982,780,4153413.78,2686927.80,330,178,2020-12-31,2020-12-31
1,2022-06-27 20:00:03.000,2022-06-27 16:16:00.000,1,FTCS,1526,1.900853e+07,8274902.69,4987645.20,876,647,...,12894161.53,368386.58,1427,36,3527539.46,2218446.80,260,230,2022-06-27,2022-06-27
2,2020-07-14 20:00:03.000,2020-07-14 16:01:00.000,1,FTCS,2395,2.738691e+07,11258817.10,10620094.06,1191,1153,...,16917753.00,4961158.17,1510,269,3008539.23,2499459.91,259,220,2020-07-14,2020-07-14
3,2020-12-29 20:00:03.000,2020-12-29 16:01:00.000,1,FTCS,1760,2.429320e+07,7754395.69,8032809.97,887,838,...,4479769.58,11307436.21,397,989,5044204.06,3461790.49,370,258,2020-12-29,2020-12-29
4,2021-11-12 20:00:03.000,2021-11-12 16:01:00.000,1,FTCS,1423,1.343950e+07,4739489.62,3790476.02,847,574,...,7622884.08,907081.75,1237,186,2639694.45,2269843.41,296,244,2021-11-12,2021-11-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-04-05 20:00:03.000,2023-04-05 16:16:00.000,1,FTCS,2841,5.318158e+07,27228138.24,13538009.38,1581,1259,...,33039084.66,7727062.90,1918,909,5943352.10,6472080.85,407,270,2023-04-05,2023-04-05
96,2023-08-21 20:00:03.000,2023-08-21 16:16:00.000,1,FTCS,2057,2.356115e+07,8722512.17,8818489.05,1065,918,...,14404811.27,3136190.17,1365,63,2838699.13,3181446.51,294,307,2023-08-21,2023-08-21
97,2021-12-06 20:00:03.000,2021-12-06 16:01:00.000,1,FTCS,2197,1.944968e+07,8875118.82,5416789.43,1263,933,...,13915395.87,376512.55,2140,56,2745092.15,2412675.10,417,333,2021-12-06,2021-12-06
98,2020-05-06 20:00:03.000,2020-05-06 16:01:00.000,1,FTCS,1847,2.648623e+07,8223040.98,8915195.70,988,858,...,9549504.86,7588731.93,1090,757,5825769.33,3522223.86,422,231,2020-05-06,2020-05-06
99,2021-11-24 20:00:03.000,2021-11-24 16:01:00.000,1,FTCS,1840,1.484869e+07,5169663.33,5004527.62,966,873,...,5669763.00,4504428.09,1146,694,2525826.97,2148668.40,292,282,2021-11-24,2021-11-24

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [9]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_trial',key='FTCS', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-02 20:00:03.000,2024-01-02 16:16:00.000,1,FTCS,2746,2.941589e+07,12201558.71,9932868.31,1466,1279,...,19169974.23,2964452.84,2252,493,3714505.32,3566961.98,393,386,2024-01-02,2024-01-02
1,2024-01-29 20:00:03.000,2024-01-29 16:16:00.000,1,FTCS,2586,2.274960e+07,7341564.70,9911815.31,1296,1283,...,9747876.53,7505503.51,1383,1190,3530891.27,1965333.04,363,254,2024-01-29,2024-01-29
2,2024-01-16 20:00:03.000,2024-01-16 17:41:00.000,1,FTCS,2729,2.533248e+07,10278060.74,9645419.41,1434,1284,...,14015434.07,5908046.02,1950,663,3072773.02,2336224.01,397,261,2024-01-16,2024-01-16
3,2024-01-26 20:00:03.000,2024-01-26 16:16:00.000,1,FTCS,2434,2.382428e+07,8038692.71,10905475.18,1156,1277,...,10183064.32,8761103.53,973,1461,2975218.26,1904892.28,315,235,2024-01-26,2024-01-26
4,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,FTCS,2545,2.607478e+07,8272864.70,11966340.98,1218,1318,...,6532281.90,13706923.89,955,1530,3602759.04,2232813.47,366,228,2024-01-17,2024-01-17
5,2024-01-18 20:00:03.000,2024-01-18 16:16:00.000,1,FTCS,2500,2.714933e+07,10100906.80,10753794.62,1233,1224,...,12707257.93,8147443.47,1082,995,3618295.11,2676335.69,349,225,2024-01-18,2024-01-18

## Download data file for a specific date using asof_date

In [7]:
Unifier.replicate(name="xtech_us_etf_flow_daily_v1_2_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for xtech_us_etf_flow_daily_v1_2_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_etf_flow_daily_v1_2_trial. Downloaded 1 files.