In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_etf_flow_1min_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,ASHR,10,91420.00,86849.00,4571.00,9,0,...,45710.00,45710.00,0,0,0,0,0,0,2019-05-21,2019-05-21
1,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,CHAU,1,194.10,97.05,97.05,0,0,...,0.00,194.10,0,1,0,0,0,0,2019-05-21,2019-05-21
2,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,IWM,2,15209.00,11406.75,3802.25,1,0,...,7604.50,7604.50,0,0,0,0,0,0,2019-05-21,2019-05-21
3,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,QQQ,9,76672.68,72413.09,4259.59,8,0,...,72413.09,4259.59,8,0,0,0,0,0,2019-05-21,2019-05-21
4,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,REMX,20,155000.00,50375.00,104625.00,6,13,...,27125.00,127875.00,0,13,0,0,0,0,2019-05-21,2019-05-21
5,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,SLV,1,2708.00,1354.00,1354.00,0,0,...,1354.00,1354.00,0,0,0,0,0,0,2019-05-21,2019-05-21
6,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,SOXS,1,677.00,338.50,338.50,0,0,...,677.00,0.00,1,0,0,0,0,0,2019-05-21,2019-05-21
7,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,SPXS,1,2042.00,1021.00,1021.00,0,0,...,2042.00,0.00,1,0,0,0,0,0,2019-05-21,2019-05-21
8,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,SPY,13,205471.07,31610.93,173860.14,1,10,...,31610.93,173860.14,2,11,0,0,0,0,2019-05-21,2019-05-21
9,2019-05-21 04:01:03.000,2019-05-21 04:01:00.000,1,SQQQ,3,1280.97,1067.47,213.50,2,0,...,640.48,640.48,0,0,0,0,0,0,2019-05-21,2019-05-21

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_1_trial', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,ARKG,2,117.52,29.38,88.14,0,1,...,58.76,58.76,0,0,0,0,0,0,2024-01-31,2024-01-31
1,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,ARKK,1,1023.00,511.50,511.50,0,0,...,511.50,511.50,0,0,0,0,0,0,2024-01-31,2024-01-31
2,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,BITO,4,3934.54,491.82,3442.72,0,3,...,983.64,2950.90,1,3,0,0,0,0,2024-01-31,2024-01-31
3,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,BND,1,7335.00,3667.50,3667.50,0,0,...,0.00,7335.00,0,1,0,0,0,0,2024-01-31,2024-01-31
4,2024-01-31 04:01:03.000,2024-01-31 04:01:00.000,1,BNDX,1,7048.80,3524.40,3524.40,0,0,...,7048.80,0.00,1,0,0,0,0,0,2024-01-31,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 04:02:03.000,2024-01-31 04:02:00.000,1,ARKK,5,11123.40,0.00,11123.40,0,5,...,0.00,11123.40,0,5,0,0,0,0,2024-01-31,2024-01-31
96,2024-01-31 04:02:03.000,2024-01-31 04:02:00.000,1,BIL,1,734.24,367.12,367.12,0,0,...,0.00,734.24,0,1,0,0,0,0,2024-01-31,2024-01-31
97,2024-01-31 04:02:03.000,2024-01-31 04:02:00.000,1,BITO,3,11431.42,11431.42,0.00,3,0,...,7620.95,3810.47,2,1,0,0,0,0,2024-01-31,2024-01-31
98,2024-01-31 04:02:03.000,2024-01-31 04:02:00.000,1,BOIL,26,11806.26,9989.91,1816.35,22,4,...,8627.65,3178.61,19,7,0,0,0,0,2024-01-31,2024-01-31
99,2024-01-31 04:02:03.000,2024-01-31 04:02:00.000,1,DIA,3,57753.00,0.00,57753.00,0,3,...,0.00,57753.00,0,3,0,0,0,0,2024-01-31,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_1_trial',key='ARKK', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2019-06-27 09:31:03.000,2019-06-27 09:31:00.000,0,ARKK,2,106784.1600,26696.04,80088.12,0,1,...,0.00,106784.16,0,2,0.00,0.00,0,0,2019-06-27,2019-06-27
1,2019-06-27 09:33:03.000,2019-06-27 09:33:00.000,0,ARKK,4,8095.4000,4047.70,4047.70,2,2,...,8095.40,0.00,4,0,0.00,0.00,0,0,2019-06-27,2019-06-27
2,2019-06-27 09:34:03.000,2019-06-27 09:34:00.000,0,ARKK,1,539.4000,0.00,539.40,0,1,...,0.00,539.40,0,1,0.00,0.00,0,0,2019-06-27,2019-06-27
3,2019-06-27 09:35:03.000,2019-06-27 09:35:00.000,0,ARKK,7,76569.7928,21877.08,30680.21,2,5,...,32815.63,19741.67,3,4,0.00,24012.50,0,1,2019-06-27,2019-06-27
4,2019-06-27 09:36:03.000,2019-06-27 09:36:00.000,0,ARKK,2,4557.1400,4557.14,0.00,2,0,...,4557.14,0.00,2,0,0.00,0.00,0,0,2019-06-27,2019-06-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-06-27 11:34:03.000,2019-06-27 11:34:00.000,0,ARKK,3,9551.8611,6367.91,2686.09,2,1,...,6367.91,2686.09,2,1,0.00,497.86,0,1,2019-06-27,2019-06-27
96,2019-06-27 11:35:03.000,2019-06-27 11:35:00.000,0,ARKK,5,11998.3200,7018.29,0.00,5,0,...,7018.29,0.00,3,2,0.00,4980.03,0,2,2019-06-27,2019-06-27
97,2019-06-27 11:36:03.000,2019-06-27 11:36:00.000,0,ARKK,66,758783.5368,382339.85,310411.45,39,27,...,382339.85,310411.45,39,27,66032.24,0.00,1,0,2019-06-27,2019-06-27
98,2019-06-27 11:37:03.000,2019-06-27 11:37:00.000,0,ARKK,42,120340.0800,111744.36,8595.72,39,3,...,106013.88,14326.20,37,5,0.00,0.00,0,0,2019-06-27,2019-06-27
99,2019-06-27 11:38:03.000,2019-06-27 11:38:00.000,0,ARKK,30,53351.7900,53351.79,0.00,30,0,...,53351.79,0.00,30,0,0.00,0.00,0,0,2019-06-27,2019-06-27

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_1_trial',key='NVDX', back_to='2024-01-01', up_to='2024-06-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-03-15 04:01:03.000,2024-03-15 04:01:00.000,1,NVDX,7,11721.08,7534.98,4186.10,4,2,...,8372.20,3348.88,4,1,0,0,0,0,2024-03-15,2024-03-15
1,2024-03-15 04:02:03.000,2024-03-15 04:02:00.000,1,NVDX,6,17939.23,5979.74,11959.49,2,4,...,5979.74,11959.49,2,4,0,0,0,0,2024-03-15,2024-03-15
2,2024-03-15 04:03:03.000,2024-03-15 04:03:00.000,1,NVDX,11,205349.42,56004.39,149345.03,3,8,...,56004.39,149345.03,3,8,0,0,0,0,2024-03-15,2024-03-15
3,2024-03-15 04:04:03.000,2024-03-15 04:04:00.000,1,NVDX,3,283.00,283.00,0.00,3,0,...,188.67,94.33,2,1,0,0,0,0,2024-03-15,2024-03-15
4,2024-03-15 04:05:03.000,2024-03-15 04:05:00.000,1,NVDX,25,557910.67,513277.82,44632.85,23,2,...,513277.82,44632.85,23,2,0,0,0,0,2024-03-15,2024-03-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-03-15 06:05:03.000,2024-03-15 06:05:00.000,1,NVDX,8,9233.43,4616.72,4616.72,4,4,...,6925.07,2308.36,6,2,0,0,0,0,2024-03-15,2024-03-15
96,2024-03-15 06:06:03.000,2024-03-15 06:06:00.000,1,NVDX,4,1165.59,874.19,291.40,3,1,...,874.19,291.40,3,1,0,0,0,0,2024-03-15,2024-03-15
97,2024-03-15 06:07:03.000,2024-03-15 06:07:00.000,1,NVDX,4,1459.85,1459.85,0.00,4,0,...,729.92,729.92,2,2,0,0,0,0,2024-03-15,2024-03-15
98,2024-03-15 06:08:03.000,2024-03-15 06:08:00.000,1,NVDX,7,11415.60,9784.80,1630.80,6,1,...,8154.00,3261.60,5,2,0,0,0,0,2024-03-15,2024-03-15
99,2024-03-15 06:09:03.000,2024-03-15 06:09:00.000,1,NVDX,2,9169.70,9169.70,0.00,2,0,...,9169.70,0.00,2,0,0,0,0,0,2024-03-15,2024-03-15

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_etf_flow_1min_v1_2_1_trial", target_location="./data", asof_date='2025-01-13')

Starting native python replication for xtech_us_etf_flow_1min_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_etf_flow_1min_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_etf_flow_1min_v1_2_1_trial", target_location="./data")