In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_etf_flow_1min_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2023-07-14 09:31:03.000,2023-07-14 09:31:00.000,0,ACTV,1,1408.6800,704.34,704.34,0,0,...,1408.68,0.00,1,0,0.00,0.0,0,0,2023-07-14,2023-07-14
1,2023-07-14 09:38:03.000,2023-07-14 09:38:00.000,0,ACTV,1,914.2000,0.00,914.20,0,1,...,0.00,914.20,0,1,0.00,0.0,0,0,2023-07-14,2023-07-14
2,2023-07-14 09:43:03.000,2023-07-14 09:43:00.000,0,ACTV,5,7513.8100,4508.29,3005.52,3,2,...,4508.29,3005.52,3,2,0.00,0.0,0,0,2023-07-14,2023-07-14
3,2023-07-14 09:47:03.000,2023-07-14 09:47:00.000,0,ACTV,2,1885.0000,942.50,942.50,1,1,...,942.50,942.50,1,1,0.00,0.0,0,0,2023-07-14,2023-07-14
4,2023-07-14 09:52:03.000,2023-07-14 09:52:00.000,0,ACTV,1,648.8020,0.00,0.00,0,1,...,0.00,0.00,0,1,0.00,648.8,0,1,2023-07-14,2023-07-14
5,2023-07-14 10:06:03.000,2023-07-14 10:06:00.000,0,ACTV,2,3235.0000,0.00,3235.00,0,2,...,0.00,3235.00,0,2,0.00,0.0,0,0,2023-07-14,2023-07-14
6,2023-07-14 10:21:03.000,2023-07-14 10:21:00.000,0,ACTV,6,10037.7845,5018.90,0.00,6,0,...,5018.90,0.00,6,0,5018.88,0.0,3,0,2023-07-14,2023-07-14
7,2023-07-14 10:37:03.000,2023-07-14 10:37:00.000,0,ACTV,2,3388.3500,0.00,3388.35,0,2,...,0.00,3388.35,0,2,0.00,0.0,0,0,2023-07-14,2023-07-14
8,2023-07-14 10:48:03.000,2023-07-14 10:48:00.000,0,ACTV,1,3319.6900,0.00,3319.69,0,1,...,0.00,3319.69,0,1,0.00,0.0,0,0,2023-07-14,2023-07-14
9,2023-07-14 10:57:03.000,2023-07-14 10:57:00.000,0,ACTV,1,1806.0000,1806.00,0.00,1,0,...,1806.00,0.00,1,0,0.00,0.0,0,0,2023-07-14,2023-07-14

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_1', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-31 09:31:03.000,2024-01-31 09:31:00.000,0,ACTV,1,4686.0000,2343.00,2343.00,0,0,...,0.00,4686.00,0,1,0.00,0.00,0,0,2024-01-31,2024-01-31
1,2024-01-31 09:38:03.000,2024-01-31 09:38:00.000,0,ACTV,1,33.0500,33.05,0.00,1,0,...,33.05,0.00,1,0,0.00,0.00,0,0,2024-01-31,2024-01-31
2,2024-01-31 09:39:03.000,2024-01-31 09:39:00.000,0,ACTV,1,2710.1000,2710.10,0.00,1,0,...,2710.10,0.00,1,0,0.00,0.00,0,0,2024-01-31,2024-01-31
3,2024-01-31 09:42:03.000,2024-01-31 09:42:00.000,0,ACTV,1,2287.3500,2287.35,0.00,1,0,...,2287.35,0.00,1,0,0.00,0.00,0,0,2024-01-31,2024-01-31
4,2024-01-31 09:45:03.000,2024-01-31 09:45:00.000,0,ACTV,1,1460.8000,1460.80,0.00,1,0,...,1460.80,0.00,1,0,0.00,0.00,0,0,2024-01-31,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-31 10:13:03.000,2024-01-31 10:13:00.000,0,ACWX,5,81028.0000,48616.80,32411.20,3,2,...,48616.80,32411.20,3,2,0.00,0.00,0,0,2024-01-31,2024-01-31
96,2024-01-31 10:14:03.000,2024-01-31 10:14:00.000,0,ACWX,10,101379.8400,40551.94,60827.90,4,6,...,40551.94,60827.90,4,6,0.00,0.00,0,0,2024-01-31,2024-01-31
97,2024-01-31 10:15:03.000,2024-01-31 10:15:00.000,0,ACWX,14,112853.8537,40304.95,71385.30,5,9,...,56426.93,55263.32,7,7,0.00,1163.61,0,1,2024-01-31,2024-01-31
98,2024-01-31 10:16:03.000,2024-01-31 10:16:00.000,0,ACWX,22,171369.1950,113046.15,54526.56,15,7,...,113046.15,54526.56,15,7,3796.48,0.00,1,0,2024-01-31,2024-01-31
99,2024-01-31 10:17:03.000,2024-01-31 10:17:00.000,0,ACWX,12,61474.8500,40983.23,20491.62,8,4,...,40983.23,20491.62,8,4,0.00,0.00,0,0,2024-01-31,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_1',key='ARKK', asof_date='2024-01-01', limit=100)
display(df)

,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2023-06-08 04:01:03.000,2023-06-08 04:01:00.000,1,ARKK,2,2116.250,1587.19,529.06,1,0,...,1587.19,529.06,1,0,0.0,0.0,0,0,2023-06-08,2023-06-08
1,2023-06-08 04:04:03.000,2023-06-08 04:04:00.000,1,ARKK,2,4212.380,0.00,4212.38,0,2,...,0.00,4212.38,0,2,0.0,0.0,0,0,2023-06-08,2023-06-08
2,2023-06-08 04:22:03.000,2023-06-08 04:22:00.000,1,ARKK,1,421.100,0.00,421.10,0,1,...,0.00,421.10,0,1,0.0,0.0,0,0,2023-06-08,2023-06-08
3,2023-06-08 04:32:03.000,2023-06-08 04:32:00.000,1,ARKK,1,632.250,632.25,0.00,1,0,...,632.25,0.00,1,0,0.0,0.0,0,0,2023-06-08,2023-06-08
4,2023-06-08 04:36:03.000,2023-06-08 04:36:00.000,1,ARKK,1,210.950,210.95,0.00,1,0,...,210.95,0.00,1,0,0.0,0.0,0,0,2023-06-08,2023-06-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-06-08 08:33:03.000,2023-06-08 08:33:00.000,1,ARKK,26,113588.580,109219.79,4368.79,25,1,...,109219.79,4368.79,25,1,0.0,0.0,0,0,2023-06-08,2023-06-08
96,2023-06-08 08:34:03.000,2023-06-08 08:34:00.000,1,ARKK,7,21061.000,0.00,21061.00,0,7,...,0.00,21061.00,0,7,0.0,0.0,0,0,2023-06-08,2023-06-08
97,2023-06-08 08:35:03.000,2023-06-08 08:35:00.000,1,ARKK,5,53971.280,52117.18,0.00,5,0,...,41322.92,10794.26,4,1,1854.1,0.0,2,0,2023-06-08,2023-06-08
98,2023-06-08 08:36:03.000,2023-06-08 08:36:00.000,1,ARKK,7,15849.390,6792.60,9056.79,3,4,...,6792.60,9056.79,3,4,0.0,0.0,0,0,2023-06-08,2023-06-08
99,2023-06-08 08:37:03.000,2023-06-08 08:37:00.000,1,ARKK,3,126.525,84.35,42.18,2,1,...,84.35,42.18,2,1,0.0,0.0,0,0,2023-06-08,2023-06-08

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_1min_v1_2_1',key='NVDX', back_to='2024-01-01', up_to='2024-06-01', limit=100)
display(df)

,timestamp,asof_datetime,extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-02-07 04:01:03.000,2024-02-07 04:01:00.000,1,NVDX,5,1082.25,324.68,757.58,1,3,...,432.90,649.35,2,3,0,0,0,0,2024-02-07,2024-02-07
1,2024-02-07 04:02:03.000,2024-02-07 04:02:00.000,1,NVDX,10,11152.96,4461.18,6691.78,4,6,...,2230.59,8922.37,2,8,0,0,0,0,2024-02-07,2024-02-07
2,2024-02-07 04:03:03.000,2024-02-07 04:03:00.000,1,NVDX,1,900.00,900.00,0.00,1,0,...,900.00,0.00,1,0,0,0,0,0,2024-02-07,2024-02-07
3,2024-02-07 04:04:03.000,2024-02-07 04:04:00.000,1,NVDX,1,1490.50,0.00,1490.50,0,1,...,0.00,1490.50,0,1,0,0,0,0,2024-02-07,2024-02-07
4,2024-02-07 04:06:03.000,2024-02-07 04:06:00.000,1,NVDX,1,300.00,300.00,0.00,1,0,...,300.00,0.00,1,0,0,0,0,0,2024-02-07,2024-02-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-02-07 07:42:03.000,2024-02-07 07:42:00.000,1,NVDX,2,963.36,0.00,963.36,0,2,...,0.00,963.36,0,2,0,0,0,0,2024-02-07,2024-02-07
96,2024-02-07 07:44:03.000,2024-02-07 07:44:00.000,1,NVDX,1,2709.45,0.00,2709.45,0,1,...,0.00,2709.45,0,1,0,0,0,0,2024-02-07,2024-02-07
97,2024-02-07 07:45:03.000,2024-02-07 07:45:00.000,1,NVDX,1,602.20,0.00,602.20,0,1,...,0.00,602.20,0,1,0,0,0,0,2024-02-07,2024-02-07
98,2024-02-07 07:48:03.000,2024-02-07 07:48:00.000,1,NVDX,4,3274.17,3274.17,0.00,4,0,...,3274.17,0.00,4,0,0,0,0,0,2024-02-07,2024-02-07
99,2024-02-07 07:50:03.000,2024-02-07 07:50:00.000,1,NVDX,3,181.31,60.44,120.87,1,2,...,60.44,120.87,1,2,0,0,0,0,2024-02-07,2024-02-07

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_etf_flow_1min_v1_2_1", target_location="./data", asof_date='2025-01-13')

Downloading using native python implementation for xtech_us_etf_flow_1min_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_etf_flow_1min_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_etf_flow_1min_v1_2_1", target_location="./data")