In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [3]:
pip install unifier

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unifier in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from unifier) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->unifier) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->unifier) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\kiwitech\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\kiwitech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Simply Import and initialize Unifier and Go!

In [3]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name="xtech_us_etf_flow_with_isin_daily_trial", asof_date='2024-01-18', limit=10)
display(df)

,date,timestamp,asof_datetime,extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2012-01-09,2012-01-09 16:01:00.000,2012-01-09 20:00:03.000,1,EXPD,US3021301094,7967,4.700568e+07,23455941.45,20719242.37,...,1394,20836438.50,23338745.35,590,696,2350405.70,480092.81,392,72,2012-01-09
1,2012-01-09,2012-01-09 16:01:00.000,2012-01-09 20:00:03.000,1,PTEN,US7034811015,14445,4.015406e+07,19295566.87,20248032.50,...,1731,19396124.21,20147475.19,686,923,377558.35,232903.05,108,65,2012-01-09
2,2012-01-09,2012-01-09 16:01:00.000,2012-01-09 20:00:03.000,1,PVH,US6936561009,6600,7.083147e+07,35415530.31,34336607.93,...,1744,43750016.72,26002121.52,4000,2599,613333.61,466002.95,56,45,2012-01-09
3,2012-01-09,2012-01-09 16:02:00.000,2012-01-09 20:00:03.000,1,APH,US0320951017,6866,4.631354e+07,21461561.24,23638263.48,...,1397,29272119.89,15827704.83,4047,2062,831494.77,382225.22,127,59,2012-01-09
4,2012-01-09,2012-01-09 16:02:00.000,2012-01-09 20:00:03.000,1,CPWR,US2056381096,7706,1.099765e+07,5599037.37,5018098.07,...,851,5364456.26,5252679.24,301,342,107685.74,272831.27,83,202,2012-01-09
5,2012-01-09,2012-01-09 16:02:00.000,2012-01-09 20:00:03.000,1,DHR,US2358511028,12949,9.750274e+07,54685837.75,39803451.35,...,1966,71531956.91,22957332.03,8098,2018,1371439.37,1642015.96,190,234,2012-01-09
6,2012-01-09,2012-01-09 16:02:00.000,2012-01-09 20:00:03.000,1,DLB,US25659T1079,3165,1.334051e+07,6970429.75,5468198.48,...,733,5933005.06,6505623.18,305,330,680497.92,221388.57,160,54,2012-01-09
7,2012-01-09,2012-01-09 16:02:00.000,2012-01-09 20:00:03.000,1,DNB,US26483E1001,1501,2.182821e+07,14378644.77,7016607.41,...,417,16568062.94,4827189.25,906,595,140787.43,292165.41,16,29,2012-01-09
8,2012-01-09,2012-01-09 16:02:00.000,2012-01-09 20:00:03.000,1,FDO,US3070001090,11074,8.149484e+07,41889635.52,36445604.51,...,2167,30095376.33,48239863.72,1851,4222,2238475.60,921125.18,320,128,2012-01-09
9,2012-01-09,2012-01-09 16:02:00.000,2012-01-09 20:00:03.000,1,IPI,US46121Y1029,3558,1.324163e+07,7232914.68,5550035.96,...,669,4486000.12,8296950.56,1064,2384,188669.50,270006.90,53,67,2012-01-09

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,0,AFRI,GI000A3DNK69,137,1.159667e+05,58664.61,57302.07,...,21,57460.90,58505.88,1,1,0.00,0.00,0,0,2024-01-30
1,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,0,BHRB,US12135Y1082,407,4.890747e+05,133802.24,339153.15,...,160,118405.67,354549.72,72,335,2944.57,13174.75,4,7,2024-01-30
2,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,1,BSVN,US06652N1072,1023,8.464414e+05,310265.46,503784.44,...,275,234303.52,579746.33,276,747,30606.47,1785.13,15,5,2024-01-30
3,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,1,DRVN,US26210V1026,8138,8.300793e+06,4226888.90,3832195.03,...,1075,3929061.12,4130022.54,186,201,196439.00,45270.15,165,67,2024-01-30
4,2024-01-30,2024-01-30 16:00:00.000,2024-01-30 20:00:03.000,1,PINC,US74051N1028,15739,4.038017e+07,17039383.75,23135644.12,...,1664,17448954.10,22726073.75,4648,11091,83175.27,121965.22,48,68,2024-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-30,2024-01-30 16:07:00.000,2024-01-30 20:00:03.000,1,USCB,US90355N1019,138,3.150803e+05,78961.72,235393.98,...,49,154281.79,160073.87,0,4,0.00,724.66,0,3,2024-01-30
96,2024-01-30,2024-01-30 16:07:00.000,2024-01-30 20:00:03.000,1,XOMA,US98419J2069,492,3.207303e+05,196486.39,118930.51,...,140,66059.51,249357.43,33,302,1532.89,3780.52,3,3,2024-01-30
97,2024-01-30,2024-01-30 16:08:00.000,2024-01-30 20:00:03.000,1,AMNB,US0277451086,267,6.823503e+05,121448.55,513647.29,...,93,194785.39,440310.48,106,161,13981.78,33272.65,12,10,2024-01-30
98,2024-01-30,2024-01-30 16:08:00.000,2024-01-30 20:00:03.000,1,AROW,US0427441029,787,8.288660e+05,253104.92,552824.65,...,239,41329.51,764600.05,27,754,10411.21,12525.25,12,12,2024-01-30
99,2024-01-30,2024-01-30 16:08:00.000,2024-01-30 20:00:03.000,1,ARTNA,US0431132085,495,4.782765e+05,203873.34,258731.83,...,153,131249.85,331355.37,160,335,6606.45,9064.78,7,7,2024-01-30

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_trial',key='AAPL', asof_date='2024-01-01', limit=100)
display(df)

,date,timestamp,asof_datetime,includes_extended_hours,ticker,isin,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,...,method4_inst_sell_count,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,asof_date
0,2007-02-07,2007-02-07 20:01:00.000,2007-02-07 20:00:03.000,1,AAPL,US0378331005,163849,3.223635e+09,1.659573e+09,1.485046e+09,...,20584,2.054095e+09,1.090524e+09,98150,60236,4.869629e+07,30319753.64,2462,1531,2007-02-07
1,2007-03-15,2007-03-15 19:56:00.000,2007-03-15 20:00:03.000,1,AAPL,US0378331005,96025,1.750510e+09,8.654880e+08,8.493707e+08,...,12606,3.707120e+08,1.344147e+09,22903,72885,2.195176e+07,13699898.49,1233,757,2007-03-15
2,2007-01-23,2007-01-23 20:00:00.000,2007-01-23 20:00:03.000,1,AAPL,US0378331005,210641,3.700886e+09,1.815347e+09,1.801014e+09,...,31045,1.842480e+09,1.773881e+09,110651,99961,5.165385e+07,32871406.09,2916,1867,2007-01-23
3,2007-03-14,2007-03-14 20:00:00.000,2007-03-14 20:00:03.000,1,AAPL,US0378331005,142908,2.432287e+09,1.267730e+09,1.120348e+09,...,18520,1.786347e+09,6.017304e+08,105165,37740,2.584720e+07,18361807.72,1513,1055,2007-03-14
4,2007-02-01,2007-02-01 20:01:00.000,2007-02-01 20:00:03.000,1,AAPL,US0378331005,110375,2.007913e+09,9.806625e+08,9.926012e+08,...,13013,9.643504e+08,1.008913e+09,54404,55971,2.067391e+07,13975484.09,1142,714,2007-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2007-06-29,2007-06-29 20:01:00.000,2007-06-29 20:00:03.000,1,AAPL,US0378331005,177426,4.829559e+09,2.400018e+09,2.263022e+09,...,30757,2.760402e+09,1.902637e+09,103031,73825,9.338348e+07,73135767.93,3396,2650,2007-06-29
96,2007-07-31,2007-07-31 20:01:00.000,2007-07-31 20:00:03.000,1,AAPL,US0378331005,290979,8.498393e+09,4.094456e+09,4.187167e+09,...,69251,3.629904e+09,4.651720e+09,129915,161047,1.207712e+08,95999139.74,4172,3309,2007-07-31
97,2007-06-21,2007-06-21 20:01:00.000,2007-06-21 20:00:03.000,1,AAPL,US0378331005,136946,3.732650e+09,1.875804e+09,1.741022e+09,...,23927,2.467692e+09,1.149133e+09,93014,43927,6.744796e+07,48376491.94,2443,1754,2007-06-21
98,2007-03-05,2007-03-05 20:01:00.000,2007-03-05 20:00:03.000,1,AAPL,US0378331005,146349,2.575116e+09,1.199052e+09,1.294136e+09,...,18340,7.456572e+08,1.747531e+09,42726,103623,4.646321e+07,35464730.99,1958,1348,2007-03-05
99,2007-06-25,2007-06-25 20:00:00.000,2007-06-25 20:00:03.000,1,AAPL,US0378331005,159672,4.180452e+09,1.973917e+09,2.062481e+09,...,28165,1.277137e+09,2.759262e+09,51526,108141,8.461701e+07,59437007.65,3165,2203,2007-06-25

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [11]:
df = Unifier.get_dataframe(name='xtech_us_eqt_flow_r3k_with_isin_daily_trial',key='AAPL', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="xtech_us_eqt_flow_r3k_with_isin_daily_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for xtech_us_eqt_flow_r3k_with_isin_daily_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_eqt_flow_r3k_with_isin_daily_trial. Downloaded 1 files.