In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [8]:
df = Unifier.get_dataframe(name="xtech_us_etf_flow_daily_v1_2_1_trial", asof_date='2024-01-18', limit=10)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2017-07-10 20:00:03.000,2017-07-10 16:01:00.000,1,ACWI,4195,4.987028e+07,27723698.69,19773040.29,2408,1786,...,27424992.97,20071746.03,2385,1810,1192307.35,1181238.05,121,57,2017-07-10,2017-07-10
1,2017-07-10 20:00:03.000,2017-07-10 16:01:00.000,1,FV,1317,1.145662e+07,4720416.67,4396979.82,628,688,...,4923570.78,4193825.70,685,632,1369515.17,969706.10,144,88,2017-07-10,2017-07-10
2,2017-07-10 20:00:03.000,2017-07-10 16:01:00.000,1,INDY,1388,1.243299e+07,4017077.88,7530217.70,679,708,...,3874171.22,7673124.35,678,710,411101.22,474592.59,82,43,2017-07-10,2017-07-10
3,2017-07-10 20:00:03.000,2017-07-10 16:01:00.000,1,KWEB,1093,7.225114e+06,3637647.93,2222930.00,700,392,...,3339440.94,2521137.02,637,455,801017.49,563518.32,106,74,2017-07-10,2017-07-10
4,2017-07-10 20:00:03.000,2017-07-10 16:01:00.000,1,MCHI,6643,4.527346e+07,26150506.63,18007151.15,3917,2725,...,25574622.63,18583035.20,3835,2807,676150.59,439650.94,42,34,2017-07-10,2017-07-10
5,2017-07-10 20:00:03.000,2017-07-10 16:01:00.000,1,QTEC,1331,2.613037e+07,14434550.63,8172814.90,730,600,...,14453906.87,8153458.69,741,590,1448193.05,2074813.57,87,81,2017-07-10,2017-07-10
6,2017-07-10 20:00:03.000,2017-07-10 16:01:00.000,1,SRTY,1589,1.157285e+07,4684055.03,5224033.56,761,827,...,4640716.95,5267371.65,762,827,607543.83,1057221.31,28,38,2017-07-10,2017-07-10
7,2017-07-10 20:00:03.000,2017-07-10 16:03:00.000,1,FVD,1745,1.599859e+07,5114410.12,4584117.79,1063,681,...,4616119.93,5082408.00,983,761,4639930.78,1660126.97,297,164,2017-07-10,2017-07-10
8,2017-07-10 20:00:03.000,2017-07-10 16:07:00.000,1,IXUS,1128,6.567501e+07,24342226.79,38892453.77,721,406,...,24166699.75,39067980.78,694,434,1756916.83,683416.02,186,93,2017-07-10,2017-07-10
9,2017-07-10 20:00:03.000,2017-07-10 16:07:00.000,1,SOXX,3293,4.688775e+07,25301266.71,19738852.78,1819,1473,...,24928166.92,20111952.58,1787,1506,912218.07,935416.24,82,61,2017-07-10,2017-07-10

## Retrieve data for a specific date range using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_1_trial', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,ACWI,42777,1.170716e+09,5.801483e+08,3.307043e+08,22439,20323,...,5.740260e+08,3.368266e+08,22156,20620,2.517515e+08,8112264.85,298,197,2024-01-17,2024-01-17
1,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,ACWX,8701,1.191556e+08,5.328136e+07,6.164189e+07,4605,4095,...,4.943427e+07,6.548898e+07,4158,4541,2.362631e+06,1869760.66,160,94,2024-01-17,2024-01-17
2,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,EMXC,11793,8.697794e+07,4.069370e+07,3.698514e+07,6684,5100,...,3.877587e+07,3.890297e+07,6394,5398,6.387066e+06,2912035.22,1225,508,2024-01-17,2024-01-17
3,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,MBB,14978,2.545059e+08,1.359059e+08,9.394953e+07,7740,7237,...,1.342579e+08,9.559753e+07,7627,7351,1.332423e+07,11326261.91,670,811,2024-01-17,2024-01-17
4,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,VCIT,21800,7.887554e+08,4.338002e+08,3.317426e+08,11287,10512,...,4.276703e+08,3.378725e+08,10800,10999,1.593489e+07,7277683.51,873,602,2024-01-17,2024-01-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-17 20:00:03.000,2024-01-17 20:00:00.000,1,LABD,29675,1.129584e+08,4.337816e+07,4.577300e+07,14720,14951,...,4.307286e+07,4.607830e+07,14595,15080,1.240143e+07,11405841.94,1993,1312,2024-01-17,2024-01-17
96,2024-01-17 20:00:03.000,2024-01-17 20:00:00.000,1,LABU,41510,3.278938e+08,1.384191e+08,1.536565e+08,19557,21935,...,1.379767e+08,1.540989e+08,19459,22051,1.824794e+07,17570222.90,1441,1315,2024-01-17,2024-01-17
97,2024-01-17 20:00:03.000,2024-01-17 20:00:00.000,1,LIT,7209,2.433629e+07,9.934430e+06,1.158193e+07,3516,3690,...,9.983938e+06,1.153242e+07,3487,3721,1.206715e+06,1613214.69,370,365,2024-01-17,2024-01-17
98,2024-01-17 20:00:03.000,2024-01-17 20:00:00.000,1,NUGT,28491,1.083234e+08,4.866591e+07,4.888862e+07,14217,14267,...,4.811041e+07,4.944412e+07,14069,14422,6.992170e+06,3776685.13,1327,655,2024-01-17,2024-01-17
99,2024-01-17 20:00:03.000,2024-01-17 20:00:00.000,1,PSQ,10179,2.126334e+08,8.416512e+07,9.785454e+07,5378,4800,...,8.178913e+07,1.002305e+08,5171,5008,1.966998e+07,10943718.78,1355,645,2024-01-17,2024-01-17

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_1_trial',key='FTCS', asof_date='2024-01-01', limit=100)
display(df)

,asof_datetime,timestamp,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2020-05-13 20:00:03.000,2020-05-13 16:01:00.000,1,FTCS,4709,6.511946e+07,19037057.23,33936420.23,2083,2625,...,18964805.96,34008671.55,2052,2657,8241444.53,3904533.70,556,285,2020-05-13,2020-05-13
1,2020-12-02 20:00:03.000,2020-12-02 16:01:00.000,1,FTCS,3201,2.919948e+07,11685626.35,9426805.97,1833,1367,...,11546677.28,9565755.05,1788,1413,5969281.53,2117761.50,440,191,2020-12-02,2020-12-02
2,2020-09-15 20:00:03.000,2020-09-15 16:01:00.000,1,FTCS,3954,3.944573e+07,14530432.38,9606771.74,2266,1687,...,14167036.90,9970167.18,2184,1770,8682674.90,6625848.06,883,643,2020-09-15,2020-09-15
3,2020-09-09 20:00:03.000,2020-09-09 16:01:00.000,1,FTCS,3281,5.207557e+07,28601485.98,15048863.73,1953,1327,...,27995415.05,15654934.59,1952,1328,5183837.57,3241384.64,355,264,2020-09-09,2020-09-09
4,2020-04-16 20:00:03.000,2020-04-16 16:01:00.000,1,FTCS,3647,4.865040e+07,22093888.12,12511598.21,2218,1428,...,21508943.42,13096542.93,2109,1537,7168605.27,6876312.42,684,376,2020-04-16,2020-04-16
5,2020-11-11 20:00:03.000,2020-11-11 16:01:00.000,1,FTCS,3145,4.725883e+07,21102855.87,16739037.40,1819,1325,...,20461302.74,17380590.53,1767,1378,6255735.56,3161202.48,438,255,2020-11-11,2020-11-11
6,2020-05-05 20:00:03.000,2020-05-05 16:01:00.000,1,FTCS,2927,3.717035e+07,17199586.96,11717777.96,1726,1200,...,16424284.80,12493080.13,1641,1286,4117904.98,4135080.64,331,270,2020-05-05,2020-05-05
7,2020-09-18 20:00:03.000,2020-09-18 16:01:00.000,1,FTCS,3225,5.112983e+07,19425579.95,20636019.60,1463,1761,...,18753253.84,21308345.73,1449,1776,6717454.47,4350775.88,335,178,2020-09-18,2020-09-18
8,2018-12-28 20:00:03.000,2018-12-28 16:01:00.000,1,FTCS,3290,4.907579e+07,27898843.18,12814576.22,2174,1115,...,27375673.32,13337746.17,2153,1137,4430585.77,3931784.20,184,183,2018-12-28,2018-12-28
9,2021-08-04 20:00:03.000,2021-08-04 16:01:00.000,1,FTCS,3198,3.565894e+07,17419543.27,12331149.10,1979,1218,...,17314515.57,12436176.84,1963,1234,3956717.77,1951530.00,380,273,2021-08-04,2021-08-04
10,2021-04-07 20:00:03.000,2021-04-07 16:01:00.000,1,FTCS,2939,3.300532e+07,14337845.62,9376071.37,1924,1014,...,13997587.18,9716329.86,1868,1071,6063053.03,3228349.64,439,332,2021-04-07,2021-04-07
11,2023-06-29 20:00:03.000,2023-06-29 16:16:00.000,1,FTCS,4116,5.708877e+07,21333350.11,20039379.46,2125,1990,...,23226296.83,18146432.77,2273,1843,10210468.60,5505572.96,677,386,2023-06-29,2023-06-29
12,2019-10-14 20:00:03.000,2019-10-14 16:01:00.000,1,FTCS,1382,1.418473e+07,5950152.37,3316852.72,819,562,...,5930511.00,3336494.12,823,559,3634089.26,1283632.69,183,125,2019-10-14,2019-10-14
13,2019-08-29 20:00:03.000,2019-08-29 17:22:00.000,1,FTCS,2435,2.879730e+07,11945639.69,7104549.83,1512,922,...,10553831.41,8496358.10,1387,1048,6569137.21,3177974.76,425,234,2019-08-29,2019-08-29
14,2020-01-03 20:00:03.000,2020-01-03 16:01:00.000,1,FTCS,2195,2.535665e+07,12238692.46,7047574.18,1328,866,...,11790605.83,7495660.78,1309,886,4388200.49,1682183.80,261,167,2020-01-03,2020-01-03
15,2019-10-15 20:00:03.000,2019-10-15 16:01:00.000,1,FTCS,1531,1.725166e+07,9415822.36,3025048.54,943,587,...,9200839.95,3240030.97,937,594,2876713.78,1934073.06,189,144,2019-10-15,2019-10-15
16,2020-01-24 20:00:03.000,2020-01-24 17:24:00.000,1,FTCS,2472,1.864080e+07,8282364.56,4944093.58,1472,999,...,8251922.89,4974535.24,1452,1018,3079472.89,2334870.80,304,204,2020-01-24,2020-01-24
17,2019-11-13 20:00:03.000,2019-11-13 16:01:00.000,1,FTCS,2449,2.008564e+07,8479755.12,7304472.83,1412,1036,...,7935128.52,7849099.48,1365,1084,3242316.96,1059093.71,268,130,2019-11-13,2019-11-13
18,2019-11-15 20:00:03.000,2019-11-15 16:01:00.000,1,FTCS,1911,1.437196e+07,4900236.66,3068807.56,1336,574,...,3936461.30,4032582.95,1157,754,5290207.98,1112706.52,544,170,2019-11-15,2019-11-15

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_1_trial',key='FTCS', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

Empty DataFrame
Columns: []
Index: []

## Download data file for a specific date using asof_date

In [4]:
Unifier.replicate(name="xtech_us_etf_flow_daily_v1_2_1_trial", target_location="./data", asof_date='2007-01-04')

Starting native python replication for xtech_us_etf_flow_daily_v1_2_1_trial (parallel)...
Found 1 files to download.
Native replication completed for xtech_us_etf_flow_daily_v1_2_1_trial. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_etf_flow_daily_v1_2_1_trial", target_location="./data")