In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [4]:
df = Unifier.get_dataframe(name="xtech_us_etf_flow_daily_v1_2_1", asof_date='2024-01-18', limit=10)
display(df)

,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2013-11-29 20:00:03.000,2013-11-29 09:31:00.000,0,AADR,1,3.720000e+03,1860.00,1860.00,0,0,...,3720.00,0.00,1,0,0.00,0.00,0,0,2013-11-29,2013-11-29
1,2013-11-29 20:00:03.000,2013-11-29 13:01:00.000,1,AAXJ,1436,6.095806e+07,42728125.38,17192116.65,930,505,...,42229202.63,17691039.42,905,530,306815.44,731004.06,19,29,2013-11-29,2013-11-29
2,2013-11-29 20:00:03.000,2013-11-29 12:51:00.000,0,ACCU,105,3.003260e+05,147306.81,153019.19,51,53,...,148737.31,151588.69,52,53,0.00,0.00,0,0,2013-11-29,2013-11-29
3,2013-11-29 20:00:03.000,2013-11-29 13:01:00.000,1,ACWI,2174,5.916404e+07,19007300.21,39229182.31,837,1335,...,18881575.60,39354906.92,837,1337,486158.28,441396.72,38,14,2013-11-29,2013-11-29
4,2013-11-29 20:00:03.000,2013-11-29 12:56:00.000,0,ACWV,49,7.909124e+05,416762.72,254271.25,30,18,...,429761.47,241272.50,31,18,105399.48,14478.98,6,1,2013-11-29,2013-11-29
5,2013-11-29 20:00:03.000,2013-11-29 13:00:00.000,1,ACWX,403,7.236263e+06,3177793.84,3755485.11,160,241,...,3286488.49,3646790.47,165,238,220496.54,82487.85,15,8,2013-11-29,2013-11-29
6,2013-11-29 20:00:03.000,2013-11-29 09:37:00.000,0,ADRA,7,2.663600e+04,12333.33,14302.67,2,4,...,14800.00,11836.00,3,4,0.00,0.00,0,0,2013-11-29,2013-11-29
7,2013-11-29 20:00:03.000,2013-11-29 13:00:00.000,0,ADRE,35,2.847475e+05,161977.36,98197.04,16,18,...,161977.36,98197.04,17,17,20762.94,3810.10,2,1,2013-11-29,2013-11-29
8,2013-11-29 20:00:03.000,2013-11-29 13:00:00.000,0,ADRU,11,9.965971e+04,54762.27,27578.28,8,2,...,32114.99,50225.57,8,3,17319.15,0.00,4,0,2013-11-29,2013-11-29
9,2013-11-29 20:00:03.000,2013-11-29 12:53:00.000,0,AFK,31,3.207013e+05,145786.82,137417.18,17,11,...,133336.30,149867.69,17,14,24146.83,13350.44,4,2,2013-11-29,2013-11-29

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_1', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,AAA,127,2.246526e+05,1.094576e+05,28917.80,105,21,...,1.116783e+05,26697.11,108,19,75747.19,10529.98,9,2,2024-01-17,2024-01-17
1,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,AAAU,3399,6.624657e+07,2.667810e+07,29378166.93,1636,1762,...,2.608865e+07,29967623.63,1674,1725,6350279.57,3840018.09,394,233,2024-01-17,2024-01-17
2,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,AADR,16,3.519601e+04,1.948973e+04,3158.67,7,8,...,1.906589e+04,3582.51,8,8,0.00,12547.62,0,3,2024-01-17,2024-01-17
3,2024-01-17 20:00:03.000,2024-01-17 19:42:00.000,1,AAPB,323,3.018304e+05,1.047499e+05,176665.31,147,175,...,1.076188e+05,173796.44,139,184,6565.59,13849.61,20,11,2024-01-17,2024-01-17
4,2024-01-17 20:00:03.000,2024-01-17 19:56:00.000,1,AAPD,1092,8.001336e+06,3.573535e+06,2378422.50,613,478,...,3.566989e+06,2384969.03,605,487,1064649.07,984729.56,113,68,2024-01-17,2024-01-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,ARKA,138,3.852941e+05,1.370934e+05,112152.63,63,74,...,1.542146e+05,95031.39,64,74,31556.09,104491.94,12,15,2024-01-17,2024-01-17
96,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,ARKC,50,2.210774e+04,8.333320e+03,11380.39,18,31,...,6.021590e+03,13692.13,18,30,777.33,1616.71,4,6,2024-01-17,2024-01-17
97,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,ARKD,47,4.309259e+04,1.571839e+04,22529.72,19,27,...,1.653612e+04,21712.01,21,26,4375.93,468.55,4,2,2024-01-17,2024-01-17
98,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,ARKF,3875,1.427460e+07,5.498356e+06,6720446.00,1882,1992,...,5.606851e+06,6611950.87,1923,1952,614770.49,1441024.50,257,218,2024-01-17,2024-01-17
99,2024-01-17 20:00:03.000,2024-01-17 20:01:00.000,1,ARKG,36163,2.107627e+08,1.026093e+08,98554074.65,18461,17329,...,1.015601e+08,99603246.83,18435,17727,5407087.49,4192279.83,723,343,2024-01-17,2024-01-17

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_1',key='FTCS', asof_date='2024-01-01', limit=100)
display(df)

,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2013-11-29 20:00:03.000,2013-11-29 12:52:00.000,0,FTCS,36,5.978803e+05,455462.59,112272.98,30,5,...,448401.29,119334.28,30,6,20096.94,10047.84,2,1,2013-11-29,2013-11-29
1,2013-08-08 20:00:03.000,2013-08-08 15:52:00.000,0,FTCS,15,6.593577e+04,37130.95,7726.95,11,3,...,28483.22,16374.68,10,4,17013.27,4064.61,5,1,2013-08-08,2013-08-08
2,2020-02-14 20:00:03.000,2020-02-14 16:01:00.000,1,FTCS,1032,1.148773e+07,3975337.65,3589320.28,501,530,...,4151512.47,3413145.47,506,526,1969165.70,1953905.66,168,176,2020-02-14,2020-02-14
3,2013-11-04 20:00:03.000,2013-11-04 15:49:00.000,0,FTCS,19,1.850322e+05,112269.73,44997.06,10,8,...,115281.27,41985.52,10,9,27765.41,0.00,3,0,2013-11-04,2013-11-04
4,2013-08-21 20:00:03.000,2013-08-21 15:42:00.000,0,FTCS,43,3.622634e+05,43377.27,298427.94,5,37,...,44868.50,296936.71,6,37,7192.32,13265.84,1,2,2013-08-21,2013-08-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-01-05 20:00:03.000,2022-01-05 16:01:00.000,1,FTCS,3145,3.596112e+07,13547120.14,12406882.37,1690,1454,...,14133881.08,11820121.45,1625,1519,4752039.22,5255077.84,396,350,2022-01-05,2022-01-05
96,2013-09-06 20:00:03.000,2013-09-06 15:56:00.000,0,FTCS,24,1.736471e+05,53261.46,48933.28,11,12,...,47426.25,54768.49,11,13,41469.37,29982.95,5,4,2013-09-06,2013-09-06
97,2017-02-28 20:00:03.000,2017-02-28 16:01:00.000,1,FTCS,130,1.218054e+06,326340.51,414172.52,62,67,...,356772.75,383740.28,62,68,379575.74,97965.40,25,12,2017-02-28,2017-02-28
98,2020-01-30 20:00:03.000,2020-01-30 16:01:00.000,1,FTCS,1147,1.492158e+07,5610582.62,4840362.63,589,557,...,5836248.98,4614696.20,613,534,2158084.04,2312549.09,199,178,2020-01-30,2020-01-30
99,2019-11-05 20:00:03.000,2019-11-05 16:01:00.000,1,FTCS,1118,1.214052e+07,4070424.47,4295238.34,607,509,...,4483054.80,3882607.99,582,535,2237231.64,1537622.24,208,161,2019-11-05,2019-11-05

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='xtech_us_etf_flow_daily_v1_2_1',key='FTCS', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,timestamp,asof_datetime,includes_extended_hours,ticker,trade_count,dollar_volume,method1_inst_buy,method1_inst_sell,method1_inst_buy_count,method1_inst_sell_count,...,method5_inst_buy,method5_inst_sell,method5_inst_buy_count,method5_inst_sell_count,retail_buy,retail_sell,retail_buy_count,retail_sell_count,date,asof_date
0,2024-01-11 20:00:03.000,2024-01-11 16:16:00.000,1,FTCS,2876,3.769933e+07,12126521.23,18661891.24,1369,1506,...,11972154.67,18816257.87,1375,1501,3991278.51,2919641.39,368,265,2024-01-11,2024-01-11
1,2024-01-25 20:00:03.000,2024-01-25 16:16:00.000,1,FTCS,2273,2.626156e+07,7690799.90,9476452.75,1077,1192,...,8032995.99,9134256.58,1089,1183,4746742.12,4347567.11,294,272,2024-01-25,2024-01-25
2,2024-01-16 20:00:03.000,2024-01-16 17:41:00.000,1,FTCS,2729,2.533248e+07,9932380.80,10094523.55,1388,1340,...,9893769.63,10133134.69,1383,1346,3045199.62,2260373.36,397,261,2024-01-16,2024-01-16
3,2024-01-17 20:00:03.000,2024-01-17 16:16:00.000,1,FTCS,2545,2.607478e+07,9281362.80,11389683.81,1250,1293,...,9532694.54,11138352.00,1246,1299,3233279.52,2170452.17,366,228,2024-01-17,2024-01-17
4,2024-01-29 20:00:03.000,2024-01-29 16:16:00.000,1,FTCS,2586,2.274960e+07,7723746.00,9776073.19,1311,1274,...,7680586.73,9819232.53,1320,1265,3345728.83,1904056.29,363,254,2024-01-29,2024-01-29
5,2024-01-26 20:00:03.000,2024-01-26 16:16:00.000,1,FTCS,2434,2.382428e+07,8111250.13,10398250.92,1211,1222,...,8395069.85,10114431.23,1239,1195,3416506.80,1898270.61,315,235,2024-01-26,2024-01-26
6,2024-01-08 20:00:03.000,2024-01-08 16:16:00.000,1,FTCS,3039,3.176131e+07,11536626.67,11962007.27,1427,1610,...,11531466.85,11967167.11,1421,1618,2742212.27,5520467.24,343,330,2024-01-08,2024-01-08
7,2024-01-24 20:00:03.000,2024-01-24 16:16:00.000,1,FTCS,3747,3.818258e+07,15006685.95,15853581.48,1850,1896,...,14314765.25,16545502.06,1807,1940,3871194.39,3451118.66,353,257,2024-01-24,2024-01-24
8,2024-01-02 20:00:03.000,2024-01-02 16:16:00.000,1,FTCS,2746,2.941589e+07,11480743.58,11119110.84,1378,1367,...,11554128.46,11045725.98,1380,1365,4016792.65,2799247.27,393,386,2024-01-02,2024-01-02
9,2024-01-09 20:00:03.000,2024-01-09 16:16:00.000,1,FTCS,3172,4.018719e+07,14064823.80,17893960.79,1445,1726,...,14147166.14,17811618.47,1454,1718,4954438.12,3273967.11,379,304,2024-01-09,2024-01-09
10,2024-01-18 20:00:03.000,2024-01-18 16:16:00.000,1,FTCS,2500,2.714933e+07,9681016.63,9918394.14,1244,1255,...,9323922.14,10275488.61,1253,1245,3982835.02,3567086.56,349,225,2024-01-18,2024-01-18
11,2024-01-19 20:00:03.000,2024-01-19 16:16:00.000,1,FTCS,3070,3.253094e+07,15369433.02,9809684.50,1800,1268,...,15011920.28,10167197.23,1775,1295,4013711.83,3338112.09,354,236,2024-01-19,2024-01-19
12,2024-01-10 20:00:03.000,2024-01-10 16:16:00.000,1,FTCS,3591,2.639224e+07,9187483.25,9505854.65,1864,1726,...,9334174.36,9359163.63,1863,1728,3698044.04,4000862.71,628,332,2024-01-10,2024-01-10
13,2024-01-03 20:00:03.000,2024-01-03 16:16:00.000,1,FTCS,3038,4.342894e+07,11507781.41,25615143.33,1438,1599,...,11854462.28,25268462.50,1433,1605,3222308.48,3083704.81,394,363,2024-01-03,2024-01-03
14,2024-01-05 20:00:03.000,2024-01-05 16:36:00.000,1,FTCS,3632,3.652303e+07,15843540.36,13550915.55,1881,1750,...,15589302.24,13805153.73,1858,1774,3322880.72,3805690.95,358,318,2024-01-05,2024-01-05
15,2024-01-23 20:00:03.000,2024-01-23 16:16:00.000,1,FTCS,2661,2.648140e+07,10149130.57,10249554.41,1384,1275,...,10193972.72,10204712.25,1384,1277,2950364.18,3132352.13,345,277,2024-01-23,2024-01-23
16,2024-01-12 20:00:03.000,2024-01-12 19:49:00.000,1,FTCS,2723,3.820619e+07,12847803.02,18819868.23,1416,1306,...,12795356.55,18872314.69,1432,1291,4842558.68,1695958.01,356,208,2024-01-12,2024-01-12
17,2024-01-31 20:00:03.000,2024-01-31 16:16:00.000,1,FTCS,2850,4.868074e+07,18746114.84,22703416.26,1304,1545,...,18701495.88,22748035.26,1293,1557,4410874.10,2820337.59,365,211,2024-01-31,2024-01-31
18,2024-01-22 20:00:03.000,2024-01-22 16:16:00.000,1,FTCS,3236,3.573628e+07,15452704.22,13272948.57,1720,1515,...,15685504.39,13040148.45,1700,1535,3868944.94,3141685.45,448,287,2024-01-22,2024-01-22
19,2024-01-04 20:00:03.000,2024-01-04 16:16:00.000,1,FTCS,2652,2.630406e+07,8875059.73,9910971.95,1269,1382,...,9133688.97,9652342.77,1289,1363,2993734.38,4524291.20,399,377,2024-01-04,2024-01-04
20,2024-01-30 20:00:03.000,2024-01-30 16:16:00.000,1,FTCS,2341,2.346161e+07,6877857.70,10069055.57,1067,1273,...,7392148.28,9554765.00,1095,1246,3240877.96,3273820.25,349,306,2024-01-30,2024-01-30

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="xtech_us_etf_flow_daily_v1_2_1", target_location="./data", asof_date='2007-01-04')

Downloading using native python implementation for xtech_us_etf_flow_daily_v1_2_1...
Found 1 files to download.
Native replication completed for xtech_us_etf_flow_daily_v1_2_1. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="xtech_us_etf_flow_daily_v1_2_1", target_location="./data")