In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [10]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_features_with_isin_values_r2k_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,isin,asof_date
0,ACE,f_1c5965eaa2b4,-0.586980,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,CH0044328745,2010-01-04
1,COMS,f_1c5965eaa2b4,-0.571907,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US8855351040,2010-01-04
2,NDN,f_1c5965eaa2b4,-0.128196,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US65440K1060,2010-01-04
3,SHLM,f_1c5965eaa2b4,-1.123819,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US8081941044,2010-01-04
4,BLC,f_1c5965eaa2b4,-1.379124,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US0805551050,2010-01-04
5,AOS,f_1c5965eaa2b4,0.880414,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US8318652091,2010-01-04
6,AAON,f_1c5965eaa2b4,1.453807,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US0003602069,2010-01-04
7,AIR,f_1c5965eaa2b4,1.140744,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US0003611052,2010-01-04
8,ABAX,f_1c5965eaa2b4,0.664820,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US0025671050,2010-01-04
9,ABMD,f_1c5965eaa2b4,1.667685,False,2010-01-04 20:00:00.000,2010-01-04 20:00:03.000,R2000,US0036541003,2010-01-04

## Retrieve data for a specific date range using the back_to and up_to parameters

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_with_isin_values_r2k_v1_2', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,isin,asof_date
0,NTB,f_1c5965eaa2b4,-0.606037,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,BMG0772R2087,2024-01-31
1,CB,f_1c5965eaa2b4,0.206714,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,CH0044328745,2024-01-31
2,TARO,f_1c5965eaa2b4,1.439720,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,IL0010827181,2024-01-31
3,FLWS,f_1c5965eaa2b4,-1.032784,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,US68243Q1067,2024-01-31
4,SRCE,f_1c5965eaa2b4,1.249141,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,US3369011032,2024-01-31
...,...,...,...,...,...,...,...,...,...
95,CWST,f_1c5965eaa2b4,0.548717,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,US1474481041,2024-01-31
96,CASS,f_1c5965eaa2b4,-1.572437,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,US14808P1093,2024-01-31
97,CATY,f_1c5965eaa2b4,1.032813,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,US1491501045,2024-01-31
98,CBRL,f_1c5965eaa2b4,0.566066,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,US22410J1060,2024-01-31
99,CECO,f_1c5965eaa2b4,0.464443,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,US1251411013,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_with_isin_values_r2k_v1_2',key='AAN', asof_date='2024-01-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,isin,asof_date
0,AAN,f_1c5965eaa2b4,-0.412492,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
1,AAN,f_2fb0aa304e00,0.063772,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
2,AAN,f_bc10cc935812,0.602895,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
3,AAN,f_c3dcd381b16e,0.288846,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
4,AAN,f_f3ee13963aa5,-0.282284,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
...,...,...,...,...,...,...,...,...,...
95,AAN,f_382eda78dd6a,-0.399562,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
96,AAN,f_efab933f02cb,-0.604846,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
97,AAN,f_1b34ec59e402,-0.700420,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
98,AAN,f_d090aeabf528,0.359777,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28
99,AAN,f_6815d18f340c,0.165400,False,2021-01-28 20:00:00.000,2021-01-28 20:00:03.000,R2000,US00258W1080,2021-01-28

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_with_isin_values_r2k_v1_2',key='AAN', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,isin,asof_date
0,AAN,f_1c5965eaa2b4,0.483464,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
1,AAN,f_2fb0aa304e00,0.638217,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
2,AAN,f_bc10cc935812,0.308450,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
3,AAN,f_c3dcd381b16e,-0.155323,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
4,AAN,f_f1cfd15c650a,-0.447227,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
...,...,...,...,...,...,...,...,...,...
95,AAN,f_9a68c481cf24,-1.265778,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
96,AAN,f_adde335784dd,-0.457407,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
97,AAN,f_8e3ab669e1e8,-0.351314,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
98,AAN,f_0e1d9714492b,0.606989,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12
99,AAN,f_02f54dcbc799,0.696690,False,2024-01-12 20:00:00.000,2024-01-12 20:00:03.000,R2000,US00258W1080,2024-01-12

## Download data file for a specific date using asof_date

In [8]:
Unifier.replicate(name="lseg_us_eqt_flow_features_with_isin_values_r2k_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_eqt_flow_features_with_isin_values_r2k_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_features_with_isin_values_r2k_v1_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_features_with_isin_values_r2k_v1_2", target_location="./data")