In [9]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [2]:
pip install unifier

Requirement already satisfied: unifier in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (0.1.20)
Requirement already satisfied: requests in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (3.0.1)
Requirement already satisfied: boto3 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (1.42.75)
Requirement already satisfied: botocore<1.43.0,>=1.42.75 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.42.75)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Simply Import and initialize Unifier and Go!

In [10]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [12]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_features_labels_r2k_v1", asof_date='2024-01-18', limit=10)
display(df)

,use_risk_model,label_name,label_value,ticker,asof_datetime,timestamp,asof_date
0,False,target_fwd_ret_10d,-0.053346,AAI,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
1,False,target_fwd_ret_63d,-0.063179,AAI,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
2,False,target_fwd_ret_21d,-0.013072,AAI,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
3,False,target_fwd_ret_42d,-0.111771,AAI,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
4,False,target_fwd_ret_42d,0.176172,AAWW,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
5,False,target_fwd_ret_63d,0.332950,AAWW,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
6,False,target_fwd_ret_10d,0.041467,AAWW,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
7,False,target_fwd_ret_21d,-0.012247,AAWW,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
8,False,target_fwd_ret_63d,0.056716,ABAT,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24
9,False,target_fwd_ret_21d,-0.010667,ABAT,2009-12-24 20:00:03.000,2009-12-24 20:00:00.000,2009-12-24

## Retrieve data for a specific date range using the back_to and up_to parameters

In [13]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_labels_r2k_v1', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,ticker,asof_datetime,timestamp,asof_date
0,True,target_res_ret_63d,-0.234363,AAN,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
1,False,target_fwd_ret_63d,-0.318988,AAN,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
2,False,target_fwd_ret_42d,-0.362321,AAN,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
3,True,target_res_ret_21d,-0.026664,AAN,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
4,True,target_res_ret_42d,-0.351710,AAN,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
...,...,...,...,...,...,...,...
95,False,target_fwd_ret_63d,0.105781,ACDC,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
96,False,target_fwd_ret_21d,0.063222,ACDC,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
97,True,target_res_ret_21d,0.043915,ACDC,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
98,True,target_res_ret_42d,0.081837,ACDC,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18
99,False,target_fwd_ret_10d,0.055949,ACDC,2024-01-18 20:00:03.000,2024-01-18 20:00:00.000,2024-01-18

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [14]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_labels_r2k_v1',key='AAN', asof_date='2024-01-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,ticker,asof_datetime,timestamp,asof_date
0,False,target_fwd_ret_42d,-0.018098,AAN,2022-02-24 20:00:03.000,2022-02-24 20:00:00.000,2022-02-24
1,True,target_res_ret_42d,0.104145,AAN,2022-02-24 20:00:03.000,2022-02-24 20:00:00.000,2022-02-24
2,False,target_fwd_ret_21d,0.083212,AAN,2022-02-24 20:00:03.000,2022-02-24 20:00:00.000,2022-02-24
3,False,target_fwd_ret_63d,-0.079039,AAN,2022-02-24 20:00:03.000,2022-02-24 20:00:00.000,2022-02-24
4,True,target_res_ret_10d,0.098926,AAN,2022-02-24 20:00:03.000,2022-02-24 20:00:00.000,2022-02-24
...,...,...,...,...,...,...,...
95,True,target_res_ret_10d,0.019248,AAN,2022-12-05 20:00:03.000,2022-12-05 20:00:00.000,2022-12-05
96,False,target_fwd_ret_10d,-0.064505,AAN,2022-12-05 20:00:03.000,2022-12-05 20:00:00.000,2022-12-05
97,False,target_fwd_ret_21d,0.036941,AAN,2022-12-05 20:00:03.000,2022-12-05 20:00:00.000,2022-12-05
98,False,target_fwd_ret_42d,-0.462892,AAN,2022-08-23 20:00:03.000,2022-08-23 20:00:00.000,2022-08-23
99,False,target_fwd_ret_63d,-0.223785,AAN,2022-08-23 20:00:03.000,2022-08-23 20:00:00.000,2022-08-23

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [15]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_labels_r2k_v1',key='AAN', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,ticker,asof_datetime,timestamp,asof_date
0,False,target_fwd_ret_63d,-0.393073,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
1,True,target_res_ret_10d,-0.049877,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
2,True,target_res_ret_63d,-0.319573,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
3,False,target_fwd_ret_21d,-0.124118,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
4,False,target_fwd_ret_10d,-0.089707,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
...,...,...,...,...,...,...,...
95,True,target_res_ret_10d,-0.014009,AAN,2024-01-11 20:00:03.000,2024-01-11 20:00:00.000,2024-01-11
96,True,target_res_ret_21d,-0.049071,AAN,2024-01-11 20:00:03.000,2024-01-11 20:00:00.000,2024-01-11
97,False,target_fwd_ret_21d,-0.008299,AAN,2024-01-11 20:00:03.000,2024-01-11 20:00:00.000,2024-01-11
98,False,target_fwd_ret_10d,-0.013870,AAN,2024-01-11 20:00:03.000,2024-01-11 20:00:00.000,2024-01-11
99,True,target_res_ret_63d,-0.297792,AAN,2024-01-11 20:00:03.000,2024-01-11 20:00:00.000,2024-01-11

## Download data file for a specific date using asof_date

In [16]:
Unifier.replicate(name="lseg_us_eqt_flow_features_labels_r2k_v1", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_eqt_flow_features_labels_r2k_v1 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_features_labels_r2k_v1. Downloaded 1 files.