In [9]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [10]:
pip install unifier

Requirement already satisfied: unifier in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (0.1.20)
Requirement already satisfied: requests in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (2.32.5)
Requirement already satisfied: pandas in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (3.0.1)
Requirement already satisfied: boto3 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from unifier) (1.42.75)
Requirement already satisfied: botocore<1.43.0,>=1.42.75 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.42.75)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from boto3->unifier) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from pandas->unifier) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from requests->unifier) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/kiwitech/workspace/eponential_work_tracking/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->unifier) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Simply Import and initialize Unifier and Go!

In [11]:
from unifier import unifier as Unifier

In [12]:
Unifier.user = 'maciej.pomalecki@qube-rt.com'
Unifier.token = 'bbcb2abf-d2ff-46b5-a917-bfc582e33c1d'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [13]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_features_values_r2k_v1", asof_date='2024-01-18', limit=10)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,asof_date
0,AAMC,f_2112dc6667db,-1.215795,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
1,AAMC,f_5851a2a27a50,-1.096264,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
2,AAMC,f_c55a51bdb8a8,-1.286834,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
3,AAMC,f_01c24d5641bc,-0.385947,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
4,AAMC,f_1296b7facef7,-0.810764,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
5,AAMC,f_6c8b3ca972d9,-0.639156,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
6,AAMC,f_187e887bf966,-1.199264,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
7,AAMC,f_6815d18f340c,-0.398221,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
8,AAMC,f_6371ae2bc242,-0.056720,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07
9,AAMC,f_4f290354458e,-1.638197,True,2014-10-07 20:00:00.000,2014-10-07 20:00:03.000,R2000,2014-10-07

## Retrieve data for a specific date range using the back_to and up_to parameters

In [15]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_values_r2k_v1', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,asof_date
0,AAN,f_6a1e86772d84,-1.010319,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
1,AAN,f_878e367e01f4,-0.818122,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
2,AAN,f_2a88060ade7f,-1.078464,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
3,AAN,f_e69769352fa6,-1.058301,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
4,AAN,f_9a68da1c9dfa,-0.818873,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
...,...,...,...,...,...,...,...,...
95,AAN,f_a36571f616a5,2.061280,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
96,AAN,f_59b986d72dc0,1.188959,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
97,AAN,f_a80b88a07240,-0.454517,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
98,AAN,f_880a7e20bb79,-1.517081,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
99,AAN,f_e096ba03f2e6,-1.211249,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [17]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_values_r2k_v1',key='AAN', asof_date='2024-01-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,asof_date
0,AAN,f_cca314c7510f,0.282930,True,2020-12-23 20:00:00.000,2020-12-23 20:00:03.000,R2000,2020-12-23
1,AAN,f_2a88060ade7f,-0.696964,True,2020-12-23 20:00:00.000,2020-12-23 20:00:03.000,R2000,2020-12-23
2,AAN,f_f3ee13963aa5,0.179936,True,2020-12-23 20:00:00.000,2020-12-23 20:00:03.000,R2000,2020-12-23
3,AAN,f_1c5965eaa2b4,0.006458,True,2020-12-23 20:00:00.000,2020-12-23 20:00:03.000,R2000,2020-12-23
4,AAN,f_24fb44f1a4b8,0.606958,True,2020-12-23 20:00:00.000,2020-12-23 20:00:03.000,R2000,2020-12-23
...,...,...,...,...,...,...,...,...
95,AAN,f_d6ba58c3d97c,0.948801,True,2021-03-25 20:00:00.000,2021-03-25 20:00:03.000,R2000,2021-03-25
96,AAN,f_b56b14da7c29,1.509578,True,2021-03-25 20:00:00.000,2021-03-25 20:00:03.000,R2000,2021-03-25
97,AAN,f_0d2652d491fc,-0.827351,False,2021-03-25 20:00:00.000,2021-03-25 20:00:03.000,R2000,2021-03-25
98,AAN,f_6a1e86772d84,-0.103108,False,2021-03-25 20:00:00.000,2021-03-25 20:00:03.000,R2000,2021-03-25
99,AAN,f_32be9940a8fb,-1.278145,False,2021-03-25 20:00:00.000,2021-03-25 20:00:03.000,R2000,2021-03-25

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [18]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_values_r2k_v1',key='AAN', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,asof_date
0,AAN,f_e096ba03f2e6,0.336492,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
1,AAN,f_23666e44edde,-0.213961,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
2,AAN,f_ad361a8cb922,-0.027956,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
3,AAN,f_f5eb409029af,-0.120723,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
4,AAN,f_e791be8c04d7,0.104080,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
...,...,...,...,...,...,...,...,...
95,AAN,f_2f54a5b358f0,0.049919,False,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
96,AAN,f_a70459501d6f,0.078068,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
97,AAN,f_3cea060d711c,0.061587,False,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
98,AAN,f_27d153cd9f3a,0.606319,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
99,AAN,f_68181ad5b0a9,-0.003930,False,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08

## Download data file for a specific date using asof_date

In [19]:
Unifier.replicate(name="lseg_us_eqt_flow_features_values_r2k_v1", target_location="./data", asof_date='2025-03-12')

Downloading using native python implementation for lseg_us_eqt_flow_features_values_r2k_v1...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_features_values_r2k_v1. Downloaded 1 files.