In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [ ]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_features_values_r2k_v1", asof_date='2024-01-18', limit=10)
display(df)

## Retrieve data for a specific date range using the back_to and up_to parameters

In [4]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_values_r2k_v1', back_to='2024-01-31', up_to='2024-02-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,asof_date
0,AAN,f_6a1e86772d84,-1.010319,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
1,AAN,f_878e367e01f4,-0.818122,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
2,AAN,f_2a88060ade7f,-1.078464,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
3,AAN,f_e69769352fa6,-1.058301,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
4,AAN,f_9a68da1c9dfa,-0.818873,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
...,...,...,...,...,...,...,...,...
95,AAN,f_a36571f616a5,2.061280,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
96,AAN,f_59b986d72dc0,1.188959,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
97,AAN,f_a80b88a07240,-0.454517,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
98,AAN,f_880a7e20bb79,-1.517081,True,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31
99,AAN,f_e096ba03f2e6,-1.211249,False,2024-01-31 20:00:00.000,2024-01-31 20:00:03.000,R2000,2024-01-31

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [5]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_values_r2k_v1',key='AAN', asof_date='2024-01-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,asof_date
0,AAN,f_f103882b4d24,-0.448891,True,2020-12-24 20:00:00.000,2020-12-24 20:00:03.000,R2000,2020-12-24
1,AAN,f_cca314c7510f,0.160002,True,2020-12-24 20:00:00.000,2020-12-24 20:00:03.000,R2000,2020-12-24
2,AAN,f_2a88060ade7f,0.440857,True,2020-12-24 20:00:00.000,2020-12-24 20:00:03.000,R2000,2020-12-24
3,AAN,f_7ef9067b664a,1.767239,True,2020-12-24 20:00:00.000,2020-12-24 20:00:03.000,R2000,2020-12-24
4,AAN,f_d467bcaaeaac,-0.945762,True,2020-12-24 20:00:00.000,2020-12-24 20:00:03.000,R2000,2020-12-24
...,...,...,...,...,...,...,...,...
95,AAN,f_1e0b7bd37b8d,1.589038,False,2020-12-24 20:00:00.000,2020-12-24 20:00:03.000,R2000,2020-12-24
96,AAN,f_c762b61779ef,0.111921,True,2021-01-25 20:00:00.000,2021-01-25 20:00:03.000,R2000,2021-01-25
97,AAN,f_a414ab6a2027,-0.489543,True,2021-01-25 20:00:00.000,2021-01-25 20:00:03.000,R2000,2021-01-25
98,AAN,f_e69769352fa6,-0.332935,True,2021-01-25 20:00:00.000,2021-01-25 20:00:03.000,R2000,2021-01-25
99,AAN,f_1b34ec59e402,0.576614,True,2021-01-25 20:00:00.000,2021-01-25 20:00:03.000,R2000,2021-01-25

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [ ]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_values_r2k_v1',key='AAN', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,ticker,feature_id,feature_value,use_risk_model,timestamp,asof_datetime,index,asof_date
0,AAN,f_e096ba03f2e6,0.336492,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
1,AAN,f_23666e44edde,-0.213961,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
2,AAN,f_ad361a8cb922,-0.027956,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
3,AAN,f_f5eb409029af,-0.120723,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
4,AAN,f_e791be8c04d7,0.104080,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
...,...,...,...,...,...,...,...,...
95,AAN,f_2f54a5b358f0,0.049919,False,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
96,AAN,f_a70459501d6f,0.078068,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
97,AAN,f_3cea060d711c,0.061587,False,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
98,AAN,f_27d153cd9f3a,0.606319,True,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08
99,AAN,f_68181ad5b0a9,-0.003930,False,2024-01-08 20:00:00.000,2024-01-08 20:00:03.000,R2000,2024-01-08

## Download data file for a specific date using asof_date

In [6]:
Unifier.replicate(name="lseg_us_eqt_flow_features_values_r2k_v1", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_eqt_flow_features_values_r2k_v1 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_features_values_r2k_v1. Downloaded 1 files.