In [1]:
import os
from IPython.display import display

### If you have not installed unifier you can do so by running the following command:

In [ ]:
pip install unifier

## Simply Import and initialize Unifier and Go!

In [2]:
from unifier import unifier as Unifier

In [ ]:
Unifier.user = 'unifier username'
Unifier.token = 'unifier api token'
os.environ['UNIFIER_USER'] = Unifier.user
os.environ['UNIFIER_TOKEN'] = Unifier.token

## Retrieve data for a specific date using the asof_date parameter

In [13]:
df = Unifier.get_dataframe(name="lseg_us_eqt_flow_features_with_isin_labels_r2k_v1_2", asof_date='2024-01-18', limit=10)
display(df)

,use_risk_model,label_name,label_value,isin,ticker,asof_datetime,timestamp,asof_date
0,False,target_fwd_ret_10d,0.013685,CH0044328745,ACE,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
1,False,target_fwd_ret_10d,-0.001296,US8855351040,COMS,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
2,False,target_fwd_ret_10d,0.009587,US65440K1060,NDN,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
3,False,target_fwd_ret_10d,0.041428,US8081941044,SHLM,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
4,False,target_fwd_ret_10d,-0.031657,US0805551050,BLC,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
5,False,target_fwd_ret_10d,0.044104,US8318652091,AOS,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
6,False,target_fwd_ret_10d,0.015530,US0003611052,AIR,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
7,False,target_fwd_ret_10d,0.077346,US0025671050,ABAX,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
8,False,target_fwd_ret_10d,-0.025752,US0036541003,ABMD,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04
9,False,target_fwd_ret_10d,0.023507,US0009571003,ABM,2010-03-04 20:00:03.000,2010-03-04 20:00:00.000,2010-03-04

## Retrieve data for a specific date range using the back_to and up_to parameters

In [6]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_with_isin_labels_r2k_v1_2', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,isin,ticker,asof_datetime,timestamp,asof_date
0,False,target_fwd_ret_10d,-0.020277,BMG0772R2087,NTB,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19
1,False,target_fwd_ret_10d,-0.053001,BMG0772R2087,NTB,2024-01-29 20:00:03.000,2024-01-29 20:00:00.000,2024-01-29
2,False,target_fwd_ret_10d,-0.038769,US3369011032,SRCE,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19
3,False,target_fwd_ret_10d,-0.016495,US88554D2053,DDD,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19
4,False,target_fwd_ret_10d,0.041379,US0003602069,AAON,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19
...,...,...,...,...,...,...,...,...
95,False,target_fwd_ret_10d,-0.026754,US1689051076,PLCE,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19
96,False,target_fwd_ret_10d,0.248100,US88080T1043,WULF,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19
97,False,target_fwd_ret_10d,-0.029679,US1778351056,CHCO,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19
98,False,target_fwd_ret_10d,0.078414,US1910981026,COKE,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19
99,False,target_fwd_ret_10d,0.054371,US1921085049,CDE,2024-01-19 20:00:03.000,2024-01-19 20:00:00.000,2024-01-19

## Retrieve data for a specific date with a specific ticker (key='ticker') using the asof_date parameter

In [7]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_with_isin_labels_r2k_v1_2',key='AAN', asof_date='2024-01-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,isin,ticker,asof_datetime,timestamp,asof_date
0,False,target_fwd_ret_10d,0.101383,US00258R1095,AAN,2020-11-12 20:00:03.000,2020-11-12 20:00:00.000,2020-11-12
1,False,target_fwd_ret_21d,-0.131394,US00258R1095,AAN,2020-11-12 20:00:03.000,2020-11-12 20:00:00.000,2020-11-12
2,False,target_fwd_ret_42d,-0.002141,US00258R1095,AAN,2020-11-12 20:00:03.000,2020-11-12 20:00:00.000,2020-11-12
3,False,target_fwd_ret_63d,-0.122070,US00258R1095,AAN,2020-11-12 20:00:03.000,2020-11-12 20:00:00.000,2020-11-12
4,True,target_res_ret_10d,0.011751,US00258R1095,AAN,2020-11-12 20:00:03.000,2020-11-12 20:00:00.000,2020-11-12
...,...,...,...,...,...,...,...,...
95,True,target_res_ret_63d,0.069090,US00258W1080,AAN,2020-12-31 20:00:03.000,2020-12-31 20:00:00.000,2020-12-31
96,False,target_fwd_ret_10d,0.200725,US00258W1080,AAN,2020-12-24 20:00:03.000,2020-12-24 20:00:00.000,2020-12-24
97,False,target_fwd_ret_21d,0.071295,US00258W1080,AAN,2020-12-24 20:00:03.000,2020-12-24 20:00:00.000,2020-12-24
98,False,target_fwd_ret_42d,0.267668,US00258W1080,AAN,2020-12-24 20:00:03.000,2020-12-24 20:00:00.000,2020-12-24
99,False,target_fwd_ret_63d,0.400019,US00258W1080,AAN,2020-12-24 20:00:03.000,2020-12-24 20:00:00.000,2020-12-24

## Retrieve data for a specific date range with a specific ticker (key='ticker') using the back_to and up_to parameters

In [8]:
df = Unifier.get_dataframe(name='lseg_us_eqt_flow_features_with_isin_labels_r2k_v1_2',key='AAN', back_to='2024-01-01', up_to='2024-02-01', limit=100)
display(df)

,use_risk_model,label_name,label_value,isin,ticker,asof_datetime,timestamp,asof_date
0,False,target_fwd_ret_10d,-0.089707,US00258W1080,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
1,False,target_fwd_ret_21d,-0.124118,US00258W1080,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
2,False,target_fwd_ret_42d,-0.460985,US00258W1080,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
3,False,target_fwd_ret_63d,-0.393073,US00258W1080,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
4,True,target_res_ret_10d,-0.049877,US00258W1080,AAN,2024-01-08 20:00:03.000,2024-01-08 20:00:00.000,2024-01-08
...,...,...,...,...,...,...,...,...
95,True,target_res_ret_63d,-0.325926,US00258W1080,AAN,2024-01-26 20:00:03.000,2024-01-26 20:00:00.000,2024-01-26
96,False,target_fwd_ret_10d,-0.035058,US00258W1080,AAN,2024-01-22 20:00:03.000,2024-01-22 20:00:00.000,2024-01-22
97,False,target_fwd_ret_21d,-0.021465,US00258W1080,AAN,2024-01-22 20:00:03.000,2024-01-22 20:00:00.000,2024-01-22
98,False,target_fwd_ret_42d,-0.326076,US00258W1080,AAN,2024-01-22 20:00:03.000,2024-01-22 20:00:00.000,2024-01-22
99,False,target_fwd_ret_63d,-0.346252,US00258W1080,AAN,2024-01-22 20:00:03.000,2024-01-22 20:00:00.000,2024-01-22

## Download data file for a specific date using asof_date

In [9]:
Unifier.replicate(name="lseg_us_eqt_flow_features_with_isin_labels_r2k_v1_2", target_location="./data", asof_date='2025-03-12')

Starting native python replication for lseg_us_eqt_flow_features_with_isin_labels_r2k_v1_2 (parallel)...
Found 1 files to download.
Native replication completed for lseg_us_eqt_flow_features_with_isin_labels_r2k_v1_2. Downloaded 1 files.

## Download all data files

In [ ]:
Unifier.replicate(name="lseg_us_eqt_flow_features_with_isin_labels_r2k_v1_2", target_location="./data")